import * as THREE from "three";
const BUILD="PHASE-260-BETTING-ACTION-UI-LOCK";
const ACTIONS=["Fold","Check","Call","Raise","All In"];
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function tex(a,c="#7ffcff"){const cn=document.createElement("canvas");cn.width=512;cn.height=220;const g=cn.getContext("2d");g.fillStyle="#030711";g.fillRect(0,0,512,220);g.strokeStyle=c;g.lineWidth=8;g.strokeRect(14,14,484,192);g.textAlign="center";g.textBaseline="middle";g.fillStyle="#fff";g.font="900 48px system-ui,Arial";g.fillText(a.toUpperCase(),256,110);const t=new THREE.CanvasTexture(cn);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
function button(root,name,label,x,z,color){const p=new THREE.Mesh(new THREE.PlaneGeometry(1.05,.45),new THREE.MeshBasicMaterial({map:tex(label,color),transparent:true,side:THREE.DoubleSide,depthWrite:false}));p.name=name;p.position.set(x,1.02,z);p.renderOrder=850;root.add(p);return p}
function act(label){window.SVR_BETTING_STATE=window.SVR_BETTING_STATE||{pot:0,currentBet:0,playerChips:50000,history:[]};window.SVR_BETTING_STATE.lastAction=label;window.SVR_BETTING_STATE.history.push({action:label,at:new Date().toISOString()});window.dispatchEvent(new CustomEvent("svr:betting-action",{detail:window.SVR_BETTING_STATE}));const s=document.getElementById("status");if(s)s.textContent="Action selected: "+label;return true}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE260_BETTING_ACTION_UI_ROOT"))return;const root=new THREE.Group();root.name="PHASE260_BETTING_ACTION_UI_ROOT";scene.add(root);const xs=[-2.4,-1.2,0,1.2,2.4];ACTIONS.forEach((a,i)=>button(root,"PHASE260_ACTION_"+a.replace(/ /g,"_").toUpperCase(),a,xs[i],3.05,i===0?"#ff5b8c":"#7ffcff"));window.SVR_BETTING_ACTIONS=ACTIONS.slice();window.SVR_BETTING_STATE={pot:0,currentBet:0,playerChips:50000,history:[],phase:"awaiting-action",dealRule:window.SVR_DEAL_ORDER_LOCK?.direction||"left-to-right"};window.SVR_SELECT_ACTION=act;window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 260 ACTIVE • BETTING ACTION UI";const s=document.getElementById("status");if(s)s.textContent="Phase 260 betting action UI active"}
install();
