import * as THREE from "three";
const BUILD="PHASE-325-ANDROID-CONTROLS-TABLE-UNIFIER-LOCK";
const ua=navigator.userAgent||"";
const active=/Android/i.test(ua)&&!/Quest|Oculus|Meta Quest/i.test(ua)||/\/game\/android\.html$/i.test(location.pathname);
let installed=false,left={id:null,x:0,y:0,dx:0,dy:0},right={id:null,x:0,y:0,dx:0,dy:0},raf=0;
function scene(){return window.__SVR_SCENE__||null}
function root(){return scene()?.getObjectByName?.("PHASE200_ORDERED_GRAND_LOBBY_ROOT")||scene()}
function cam(){return window.__SVR_CAMERA__||window.camera||null}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null}
function dedupeControls(){const keep="svrAndroidGamePad325";let removed=0;["svrAndroidGamePad","svrAndroidGamePad324","svrTapMovePanel","svrAndroidAuthorityPanel","svrAndroidLiteHud","svrAndroidRecoverView","svrMobileControls","svrTouchControls","svrAndroidJoystickLayer"].forEach(id=>{const e=document.getElementById(id);if(e&&e.id!==keep){e.remove();removed++;}});document.querySelectorAll(".svr-stick,.svr-pad-buttons,.svr-pad-top,.svr-android-stick,.svr-mobile-stick,.svr-touch-stick").forEach(e=>{if(!e.closest(`#${keep}`)){const p=e.parentElement;if(p&&p.id!==keep&&p.childElementCount<8){p.remove();removed++;}else{e.remove();removed++;}}});return removed}
function css(){if(document.getElementById("svr-phase325-style"))return;const s=document.createElement("style");s.id="svr-phase325-style";s.textContent=`
body.svr-android-game-controls #svrAndroidGamePad,body.svr-android-game-controls #svrAndroidGamePad324{display:none!important;visibility:hidden!important;pointer-events:none!important}
#svrAndroidGamePad325{position:fixed;inset:0;z-index:999999;pointer-events:none;font-family:system-ui,Arial,sans-serif;color:#fff}#svrAndroidGamePad325 .stick{position:absolute;width:118px;height:118px;border:2px solid rgba(127,252,255,.48);border-radius:50%;background:rgba(2,5,12,.36);box-shadow:0 0 18px rgba(127,252,255,.16);pointer-events:auto;touch-action:none}#svrAndroidGamePad325 .stick b{position:absolute;left:39px;top:39px;width:40px;height:40px;border-radius:50%;background:rgba(127,252,255,.78);box-shadow:0 0 22px rgba(127,252,255,.55)}#svrMoveStick325{left:22px;bottom:24px}#svrLookStick325{right:22px;bottom:24px}#svrAndroidGamePad325 .buttons{position:absolute;right:18px;bottom:160px;display:grid;grid-template-columns:repeat(2,78px);gap:10px;pointer-events:auto}#svrAndroidGamePad325 button{height:47px;border:1px solid rgba(255,217,138,.72);border-radius:13px;background:rgba(5,7,14,.76);color:#fff;font-weight:900;font-size:15px}#svrAndroidGamePad325 .tag{position:absolute;left:50%;transform:translateX(-50%);bottom:18px;border:1px solid rgba(127,252,255,.55);border-radius:999px;background:rgba(0,0,0,.58);padding:7px 12px;font-size:12px;font-weight:900;letter-spacing:.05em}.svr-phase325-android #sceneNav,.svr-phase325-android #hud,.svr-phase325-android #log,.svr-phase325-android #err,.svr-phase325-android #svrPhaseBadge{display:none!important}`;document.head.appendChild(s)}
function makePad(){dedupeControls();let p=document.getElementById("svrAndroidGamePad325");if(p)return p;p=document.createElement("div");p.id="svrAndroidGamePad325";p.innerHTML=`<div id="svrMoveStick325" class="stick" aria-label="Move"><b></b></div><div id="svrLookStick325" class="stick" aria-label="Look"><b></b></div><div class="buttons"><button data-act="deal">DEAL</button><button data-act="sit">SIT</button><button data-act="check">CHECK</button><button data-act="call">CALL</button><button data-act="raise">RAISE</button><button data-act="clean">CLEAN</button></div><div class="tag">ANDROID CARD PLAY READY</div>`;document.body.appendChild(p);return p}
function bindStick(el,state){if(!el||el.__phase325)return;el.__phase325=true;const knob=el.querySelector("b");function reset(){state.id=null;state.dx=0;state.dy=0;if(knob)knob.style.transform="translate(0,0)"}el.addEventListener("pointerdown",e=>{state.id=e.pointerId;const r=el.getBoundingClientRect();state.x=r.left+r.width/2;state.y=r.top+r.height/2;el.setPointerCapture?.(e.pointerId);e.preventDefault()},{passive:false});el.addEventListener("pointermove",e=>{if(state.id!==e.pointerId)return;const mx=e.clientX-state.x,my=e.clientY-state.y;const cap=44,len=Math.max(1,Math.hypot(mx,my));state.dx=Math.max(-1,Math.min(1,mx/cap));state.dy=Math.max(-1,Math.min(1,my/cap));const k=Math.min(cap,len);if(knob)knob.style.transform=`translate(${mx/len*k}px,${my/len*k}px)`;e.preventDefault()},{passive:false});["pointerup","pointercancel","lostpointercapture"].forEach(t=>el.addEventListener(t,reset));}
function tableObj(){let out=null;root()?.traverse?.(o=>{const n=String(o.name||"");if(!out&&/PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED|PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT|POKER_TABLE|TABLE/i.test(n)&&!/CARD|CHIP|LABEL|TAG|PANEL|HITBOX|HUD|MARKER|FLOOR|MEDALLION/i.test(n))out=o;});return out}
function tableBounds(){const t=tableObj();if(!t)return null;t.visible=true;t.traverse?.(o=>{o.visible=true;if(o.isMesh){o.frustumCulled=false;o.castShadow=false;o.receiveShadow=true;}});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t);if(!Number.isFinite(b.min.y))return null;const s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{obj:t,b,s,c,top:b.max.y}}
function buildFallbackTable(){const r=root();if(!r)return null;let g=r.getObjectByName("PHASE325_ANDROID_FALLBACK_TABLE_ROOT");if(g)return g;g=new THREE.Group();g.name="PHASE325_ANDROID_FALLBACK_TABLE_ROOT";g.position.set(0,0,.75);r.add(g);const rail=new THREE.Mesh(new THREE.CylinderGeometry(2.35,2.35,.18,80),new THREE.MeshStandardMaterial({color:0x231416,roughness:.72,metalness:.05}));rail.scale.z=.63;rail.position.y=.76;g.add(rail);const felt=new THREE.Mesh(new THREE.CylinderGeometry(2.02,2.02,.045,80),new THREE.MeshStandardMaterial({color:0x06321d,roughness:.9,metalness:.02}));felt.scale.z=.56;felt.position.y=.88;g.add(felt);const ring=new THREE.Mesh(new THREE.TorusGeometry(2.0,.025,8,120),new THREE.MeshBasicMaterial({color:0xffd98a,transparent:true,opacity:.7,depthWrite:false}));ring.scale.z=.56;ring.rotation.x=Math.PI/2;ring.position.y=.915;g.add(ring);return g}
function clearFloatingUI(){let n=0;root()?.traverse?.(o=>{const nm=String(o.name||"");if(/PHASE214_|PHASE215_|PHASE168_|TABLE_STATUS_FLOATING|OPEN_PLAYER_SEAT_LABEL/i.test(nm)){o.visible=false;o.traverse?.(c=>c.visible=false);n++;}});return n}
function cardTex(a,b){const c=document.createElement("canvas");c.width=256;c.height=360;const x=c.getContext("2d");x.fillStyle="#f7f3e6";x.fillRect(0,0,256,360);x.strokeStyle="#101015";x.lineWidth=10;x.strokeRect(9,9,238,342);x.fillStyle=/H|D|♥|♦/.test(b)?"#b5142b":"#101015";x.font="900 62px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText(a,128,126);x.font="900 72px system-ui";x.fillText({S:"♠",H:"♥",D:"♦",C:"♣"}[b]||b,128,224);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function makeCard(p,n,pos,a,b){const m=new THREE.Mesh(new THREE.PlaneGeometry(.28,.39),new THREE.MeshBasicMaterial({map:cardTex(a,b),side:THREE.DoubleSide,depthWrite:false}));m.name=n;m.position.copy(pos);m.rotation.x=-Math.PI/2;m.renderOrder=3250;p.add(m);return m}
function chip(p,n,pos,color,count){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.CylinderGeometry(.066,.066,.015,28),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.13}));m.name=`${n}_${i}`;m.position.set(pos.x,pos.y+i*.016,pos.z);m.renderOrder=3251;p.add(m)}}
function alignCards(){const r=root();if(!r)return null;clearFloatingUI();let rec=tableBounds();if(!rec){buildFallbackTable();rec=tableBounds()}if(!rec)return null;const old=r.getObjectByName("PHASE325_ANDROID_CARD_TABLE_ROOT");if(old)old.parent?.remove(old);const g=new THREE.Group();g.name="PHASE325_ANDROID_CARD_TABLE_ROOT";r.add(g);const c=rec.c,w=Math.max(3.4,Math.min(rec.s.x*.76,4.8)),d=Math.max(1.8,Math.min(rec.s.z*.62,2.8)),y=Math.max(.83,rec.top)+.018;[["A","S",-.48,0],["K","H",-.24,0],["Q","D",0,0],["J","C",.24,0],["10","S",.48,0]].forEach(([a,b,x,z],i)=>makeCard(g,`PHASE325_COMMUNITY_CARD_${i}`,new THREE.Vector3(c.x+x,y,c.z+z),a,b));makeCard(g,"PHASE325_PLAYER_CARD_A",new THREE.Vector3(c.x-.17,y,c.z+d*.34),"9","H");makeCard(g,"PHASE325_PLAYER_CARD_B",new THREE.Vector3(c.x+.17,y,c.z+d*.34),"9","C");chip(g,"PHASE325_CENTER_POT",new THREE.Vector3(c.x,y+.005,c.z+d*.13),0xffd98a,8);[[0,d*.5,0x7ffcff],[-w*.38,d*.24,0xff5b8c],[-w*.42,-d*.18,0xffd98a],[0,-d*.47,0x8eff8e],[w*.42,-d*.18,0xa78bfa],[w*.38,d*.24,0xff8bd1]].forEach(([x,z,col],i)=>chip(g,`PHASE325_STACK_${i}`,new THREE.Vector3(c.x+x,y+.005,c.z+z),col,4));window.SVR_ANDROID_CARD_TABLE_STATE={build:BUILD,active:true,table:rec.obj.name,top:+rec.top.toFixed(3),cardY:+y.toFixed(3),chips:true,updatedAt:new Date().toISOString()};return window.SVR_ANDROID_CARD_TABLE_STATE}
function move(){const c=cam();if(!c)return;const f=-left.dy,strafe=-left.dx,turn=-right.dx;if(Math.abs(turn)>.06){const rr=rig();if(rr?.rotation)rr.rotation.y+=turn*.036;else c.rotation.y+=turn*.036}if(Math.abs(f)<.04&&Math.abs(strafe)<.04)return;const d=new THREE.Vector3();c.getWorldDirection(d);d.y=0;if(d.lengthSq()<.001)d.set(0,0,-1);d.normalize();const side=new THREE.Vector3().crossVectors(d,new THREE.Vector3(0,1,0)).normalize();const p=new THREE.Vector3();c.getWorldPosition(p);const speed=.061,nx=p.x+(d.x*f+side.x*strafe)*speed,nz=p.z+(d.z*f+side.z*strafe)*speed;const rr=rig();if(rr?.setPlayerPose)rr.setPlayerPose(nx,0,nz);else c.position.set(nx,c.position.y,nz)}
function act(a){try{if(a==="deal")return window.SVR_PRESS_DEAL?.()||window.SVR_PLAY_LEFT_TO_RIGHT_DEAL?.();if(a==="sit")return window.SVR_JOIN_TABLE?.()||window.SVR_SIT_AT_TABLE?.();if(a==="check")return window.SVR_SELECT_ACTION?.("Check");if(a==="call")return window.SVR_SELECT_ACTION?.("Call");if(a==="raise")return window.SVR_SELECT_ACTION?.("Raise");if(a==="clean")return alignCards();}catch(e){window.SVR_PHASE325_LAST_ERROR=String(e?.message||e)}return null}
function loop(){dedupeControls();move();window.SVR_PHASE325_ANDROID={build:BUILD,active,installed,move:{x:+left.dx.toFixed(2),y:+left.dy.toFixed(2)},look:{x:+right.dx.toFixed(2),y:+right.dy.toFixed(2)},table:window.SVR_ANDROID_CARD_TABLE_STATE||null,updatedAt:new Date().toISOString()};raf=requestAnimationFrame(loop)}
function install(){if(!active||installed)return;css();document.body.classList.add("svr-phase325-android","svr-android-game-controls");const pad=makePad();bindStick(pad.querySelector("#svrMoveStick325"),left);bindStick(pad.querySelector("#svrLookStick325"),right);pad.querySelectorAll("button[data-act]").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();act(b.dataset.act)}));installed=true;window.SVR_ANDROID_DEDUPE_CONTROLS=dedupeControls;window.SVR_ANDROID_ALIGN_CARDS=alignCards;window.SVR_PHASE325={build:BUILD,active:true,siteTouched:false,helpers:["SVR_ANDROID_DEDUPE_CONTROLS","SVR_ANDROID_ALIGN_CARDS"]};[500,1200,2400,4200,7000].forEach(ms=>setTimeout(alignCards,ms));if(!raf)loop()}
setTimeout(install,160);setTimeout(install,900);setTimeout(install,2200);
