import * as THREE from "three";
const BUILD="PHASE-324-ANDROID-GAME-ENTRY-CONTROLS-LOCK";
const ua=navigator.userAgent||"";
const isQuest=/Quest|Oculus|Meta Quest/i.test(ua);
const isAndroid=/Android/i.test(ua)&&!isQuest;
const isAndroidRoute=/\/game\/android\.html$/i.test(location.pathname);
const active=isAndroid||isAndroidRoute;
let installed=false,left={id:null,x:0,y:0,dx:0,dy:0},right={id:null,x:0,y:0,dx:0,dy:0},raf=0;
function css(){if(document.getElementById("svr-phase324-style"))return;const s=document.createElement("style");s.id="svr-phase324-style";s.textContent=`
body.svr-android-game-controls #startRuntimeBtn{font-size:16px;padding:13px 18px;border-radius:14px;background:linear-gradient(135deg,rgba(127,252,255,.22),rgba(255,217,138,.16));}
#svrAndroidGamePad{position:fixed;inset:0;z-index:99998;pointer-events:none;display:none;font-family:system-ui,Arial,sans-serif}body.svr-android-game-controls #svrAndroidGamePad{display:block}.svr-stick{position:absolute;width:126px;height:126px;border:2px solid rgba(127,252,255,.45);border-radius:50%;background:rgba(3,7,18,.42);backdrop-filter:blur(5px);pointer-events:auto;touch-action:none}.svr-stick b{position:absolute;left:41px;top:41px;width:44px;height:44px;border-radius:50%;background:rgba(127,252,255,.76);box-shadow:0 0 20px rgba(127,252,255,.5)}#svrMoveStick{left:22px;bottom:28px}#svrLookStick{right:22px;bottom:28px}.svr-pad-buttons{position:absolute;right:18px;bottom:172px;display:grid;grid-template-columns:repeat(2,82px);gap:10px;pointer-events:auto}.svr-pad-buttons button{height:48px;border:1px solid rgba(255,217,138,.75);border-radius:14px;background:rgba(6,9,18,.72);color:#fff;font-weight:900;letter-spacing:.03em}.svr-pad-top{position:absolute;left:50%;transform:translateX(-50%);bottom:26px;padding:8px 13px;border:1px solid rgba(127,252,255,.45);border-radius:999px;background:rgba(0,0,0,.55);color:#dffeff;font-weight:900;font-size:12px;pointer-events:none}`;document.head.appendChild(s)}
function make(){let p=document.getElementById("svrAndroidGamePad");if(p)return p;p=document.createElement("div");p.id="svrAndroidGamePad";p.innerHTML=`<div id="svrMoveStick" class="svr-stick" aria-label="Move"><b></b></div><div id="svrLookStick" class="svr-stick" aria-label="Turn"><b></b></div><div class="svr-pad-buttons"><button data-act="deal">DEAL</button><button data-act="sit">SIT</button><button data-act="check">CHECK</button><button data-act="call">CALL</button><button data-act="raise">RAISE</button><button data-act="clean">CLEAN</button></div><div class="svr-pad-top">ANDROID GAME CONTROLS ACTIVE</div>`;document.body.appendChild(p);return p}
function stick(el,state){const knob=el.querySelector("b");const reset=()=>{state.id=null;state.dx=0;state.dy=0;if(knob)knob.style.transform="translate(0,0)"};el.addEventListener("pointerdown",e=>{state.id=e.pointerId;const r=el.getBoundingClientRect();state.x=r.left+r.width/2;state.y=r.top+r.height/2;el.setPointerCapture?.(e.pointerId);e.preventDefault()},{passive:false});el.addEventListener("pointermove",e=>{if(state.id!==e.pointerId)return;const mx=e.clientX-state.x,my=e.clientY-state.y;const len=Math.max(1,Math.hypot(mx,my));const cap=46;state.dx=Math.max(-1,Math.min(1,mx/cap));state.dy=Math.max(-1,Math.min(1,my/cap));const k=Math.min(cap,len);if(knob)knob.style.transform=`translate(${mx/len*k}px,${my/len*k}px)`;e.preventDefault()},{passive:false});["pointerup","pointercancel","lostpointercapture"].forEach(t=>el.addEventListener(t,reset));}
function cam(){return window.__SVR_RENDERER__?.xr?.isPresenting?window.__SVR_RENDERER__.xr.getCamera(window.__SVR_CAMERA__):window.__SVR_CAMERA__}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null}
function move(){const c=cam();if(!c)return;const f=-left.dy,s=left.dx,turn=right.dx;if(Math.abs(turn)>.08){const r=rig();if(r?.rotation)r.rotation.y-=turn*.035;else c.rotation.y-=turn*.035}if(Math.abs(f)<.04&&Math.abs(s)<.04)return;const d=new THREE.Vector3();c.getWorldDirection(d);d.y=0;if(d.lengthSq()<.001)d.set(0,0,-1);d.normalize();const side=new THREE.Vector3().crossVectors(d,new THREE.Vector3(0,1,0)).normalize();const p=new THREE.Vector3();c.getWorldPosition(p);const speed=.065;const nx=p.x+(d.x*f+side.x*s)*speed,nz=p.z+(d.z*f+side.z*s)*speed;const rr=rig();if(rr?.setPlayerPose)rr.setPlayerPose(nx,0,nz);else c.position.set(nx,c.position.y,nz);}
function act(a){try{if(a==="deal")return window.SVR_PRESS_DEAL?.()||window.SVR_PLAY_LEFT_TO_RIGHT_DEAL?.();if(a==="check")return window.SVR_SELECT_ACTION?.("Check");if(a==="call")return window.SVR_SELECT_ACTION?.("Call");if(a==="raise")return window.SVR_SELECT_ACTION?.("Raise");if(a==="sit")return window.SVR_JOIN_TABLE?.()||window.SVR_SIT_AT_TABLE?.()||window.SVR_TRIGGER_DEAL_HITBOX?.();if(a==="clean")return window.SVR_RUN_OVERLAY_CLEANUP?.()||window.SVR_CLEAN_FACE_BOX?.();}catch(e){window.SVR_PHASE324_LAST_ERROR=String(e?.message||e)}return null}
function loop(){move();window.SVR_PHASE324_ANDROID_CONTROLS={build:BUILD,active,installed,move:{x:+left.dx.toFixed(2),y:+left.dy.toFixed(2)},look:{x:+right.dx.toFixed(2),y:+right.dy.toFixed(2)},checkedAt:new Date().toISOString()};raf=requestAnimationFrame(loop)}
function install(){if(!active||installed)return;css();document.body.classList.add("svr-android-game-controls");const btn=document.getElementById("startRuntimeBtn");if(btn)btn.textContent="Enter Android Game";const p=make();stick(p.querySelector("#svrMoveStick"),left);stick(p.querySelector("#svrLookStick"),right);p.querySelectorAll("button[data-act]").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();act(b.dataset.act)}));installed=true;if(!raf)loop();window.SVR_ENTER_ANDROID_GAME=()=>{document.body.classList.add("boot-released","runtime-visible","overlay-released","svr-android-game-controls");document.getElementById("safeStage")?.remove();window.__SVR_GAME_READY__=true;window.SVR_GAME_READY=true;return window.SVR_PHASE324_ANDROID_CONTROLS};window.SVR_PHASE324={build:BUILD,active:true,siteTouched:false,androidRoute:isAndroidRoute,helper:"SVR_ENTER_ANDROID_GAME"};}
setTimeout(install,120);setTimeout(install,900);setTimeout(install,2200);
