import * as THREE from "three";
const BUILD="PHASE-329-ANDROID-TABLE-PLAYTEST-UX-LOCK";
const ua=navigator.userAgent||"";
const active=(/Android/i.test(ua)&&!/Quest|Oculus|Meta Quest/i.test(ua))||/\/game\/android\.html$/i.test(location.pathname)||new URLSearchParams(location.search).get("channel")==="stable";
const KEY="SVR_ANDROID_TABLE_UX_V1";
let installed=false,raf=0,last=0;
let state={seated:false,turn:false,activeHand:false,amount:1000,cards:["--","--"],last:"LOBBY",hand:0};
const ranks=["A","K","Q","J","10","9","8","7","6","5","4","3","2"],suits=["♠","♥","♦","♣"];
function load(){try{state={...state,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}return state}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}return state}
function scene(){return window.__SVR_SCENE__||null}
function cam(){return window.__SVR_RENDERER__?.xr?.isPresenting?window.__SVR_RENDERER__.xr.getCamera(window.__SVR_CAMERA__):window.__SVR_CAMERA__}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null}
function root(){const s=scene();return s?.getObjectByName?.("PHASE200_ORDERED_GRAND_LOBBY_ROOT")||s}
function table(){const r=root();return r?.getObjectByName?.("PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED")||r?.getObjectByName?.("PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT")||r?.getObjectByName?.("PHASE326_ANDROID_TABLE_FALLBACK")||null}
function box(){const t=table();if(!t)return null;t.visible=true;t.traverse?.(o=>o.visible=true);t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),c=new THREE.Vector3(),z=new THREE.Vector3();b.getCenter(c);b.getSize(z);return{obj:t,box:b,center:c,size:z,top:b.max.y}}
function css(){if(document.getElementById("svr-phase329-style"))return;const s=document.createElement("style");s.id="svr-phase329-style";s.textContent=`#svrAndroidGamePad,#svrTapMovePanel,#svrAndroidSafeBadge153,#svrAndroidLiteHud,#svrAndroidRecoverView{display:none!important;opacity:0!important;pointer-events:none!important}body.svr-phase329-android .svr-stick:not(#svr326Move):not(#svr326Look){display:none!important;opacity:0!important;pointer-events:none!important}body.svr-phase329-android #svr326Root{z-index:999999!important}.svr329Invalid{opacity:.38!important;filter:grayscale(.8)!important}.svr329Valid{border-color:#7ffcff!important;box-shadow:0 0 18px rgba(127,252,255,.42)!important}.svr329Pulse{transform:scale(.92)!important}#svr329Toast{position:fixed;left:50%;top:58px;transform:translateX(-50%);z-index:1000000;padding:9px 14px;border:1px solid rgba(255,217,138,.72);border-radius:999px;background:rgba(0,0,0,.68);color:#fff;font:950 12px system-ui;letter-spacing:.08em;pointer-events:none}#svr329Info{position:fixed;left:10px;top:10px;z-index:999998;border:1px solid rgba(127,252,255,.45);border-radius:14px;background:rgba(0,0,0,.55);color:#dffeff;padding:8px 10px;font:900 11px system-ui;line-height:1.35;pointer-events:none}#svr329QA{position:fixed;right:10px;top:10px;z-index:999998;border:1px solid rgba(255,217,138,.45);border-radius:999px;background:rgba(0,0,0,.45);color:#ffd98a;padding:6px 10px;font:900 10px system-ui;letter-spacing:.06em;pointer-events:none}body:not(.svr-phase329-android) #svr329Toast,body:not(.svr-phase329-android) #svr329Info,body:not(.svr-phase329-android) #svr329QA{display:none!important}`;document.head.appendChild(s)}
function purge(){["#svrAndroidGamePad","#svrTapMovePanel","#svrAndroidSafeBadge153","#svrAndroidLiteHud","#svrAndroidRecoverView"].forEach(q=>document.querySelectorAll(q).forEach(e=>e.remove()));[...document.querySelectorAll(".svr-stick")].forEach(e=>{if(e.id!=="svr326Move"&&e.id!=="svr326Look")e.remove()});const roots=[...document.querySelectorAll("#svr326Root")];roots.slice(1).forEach(e=>e.remove());return{roots:document.querySelectorAll("#svr326Root").length,sticks:document.querySelectorAll("#svr326Move,#svr326Look").length}}
function toast(t){let e=document.getElementById("svr329Toast");if(!e){e=document.createElement("div");e.id="svr329Toast";document.body.appendChild(e)}e.textContent=t;clearTimeout(e._t);e.style.opacity=.98;e._t=setTimeout(()=>e.style.opacity=.28,1400);try{navigator.vibrate?.(24)}catch{}}
function draw(txt){const c=document.createElement("canvas");c.width=256;c.height=360;const x=c.getContext("2d");x.fillStyle="#f8f0dc";x.fillRect(0,0,256,360);x.strokeStyle="#111";x.lineWidth=10;x.strokeRect(10,10,236,340);x.fillStyle=/[♥♦]/.test(txt)?"#a00018":"#111";x.font="900 72px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText(txt,128,180);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function cards(){const b=root(),r=box();if(!b||!r)return;const old=b.getObjectByName("PHASE329_ANDROID_PLAYER_CARD_ROOT");if(old)old.parent.remove(old);const g=new THREE.Group();g.name="PHASE329_ANDROID_PLAYER_CARD_ROOT";b.add(g);state.cards.forEach((txt,i)=>{if(txt==="--")return;const m=new THREE.Mesh(new THREE.PlaneGeometry(.34,.47),new THREE.MeshBasicMaterial({map:draw(txt),side:THREE.DoubleSide,depthWrite:false}));m.position.set(r.center.x+(i?.2:-.2),r.top+.04,r.center.z+Math.max(.82,r.size.z*.35));m.rotation.x=-Math.PI/2;m.renderOrder=3290;g.add(m)})}
function ring(){const b=root(),r=box();if(!b||!r)return;let o=b.getObjectByName("PHASE329_ANDROID_TURN_RING");if(!o){o=new THREE.Mesh(new THREE.TorusGeometry(2.28,.025,8,112),new THREE.MeshBasicMaterial({color:0x7ffcff,transparent:true,opacity:.35,depthWrite:false}));o.name="PHASE329_ANDROID_TURN_RING";o.rotation.x=Math.PI/2;b.add(o)}o.position.set(r.center.x,r.top+.055,r.center.z);o.scale.set(Math.max(.75,r.size.x/4.5),Math.max(.55,r.size.z/3.1),1);o.visible=state.seated&&state.turn}
function dealCards(){const d=[];for(const r of ranks)for(const s of suits)d.push(r+s);d.sort(()=>Math.random()-.5);return[d[0],d[1]]}
function sit(){const r=box(),c=cam(),rr=rig();if(!r)return false;state.seated=true;state.turn=state.activeHand?state.turn:true;state.last="SEATED";try{const x=r.center.x,z=r.center.z+Math.max(2.55,r.size.z*.92);if(rr?.setPlayerPose)rr.setPlayerPose(x,0,z);else if(c)c.position.set(x,1.55,z);if(c)c.lookAt(r.center.x,r.top+.28,r.center.z)}catch{}save();cards();apply();toast("SEATED AT TABLE");return true}
function lobby(){state.seated=false;state.turn=false;state.last="LOBBY";save();try{window.SVR_ANDROID_LOBBY_MODE?.()}catch{}apply();toast("LOBBY MOVEMENT ON")}
function allowed(a){if(a==="sit"||a==="clean")return true;if(!state.seated)return a==="deal";if(!state.activeHand)return a==="deal";return state.turn&&(a==="check"||a==="call"||a==="raise")}
function act(a){if(a==="sit")return state.seated?lobby():sit();if(a==="clean"){purge();cards();return toast("CONTROL CLEANUP DONE")}if(a==="deal"){if(!state.seated)sit();state.activeHand=true;state.turn=true;state.hand++;state.cards=dealCards();state.last="CARDS DEALT";save();cards();try{window.SVR_PRESS_DEAL?.()||window.SVR_PLAY_LEFT_TO_RIGHT_DEAL?.()}catch{}apply();return toast("CARDS DEALT • YOUR TURN")}if(!allowed(a))return toast("ACTION NOT AVAILABLE");state.turn=false;state.last=a.toUpperCase()+" • WAITING";try{if(a==="check")window.SVR_SELECT_ACTION?.("Check");if(a==="call")window.SVR_SELECT_ACTION?.("Call");if(a==="raise")window.SVR_SELECT_ACTION?.("Raise")}catch{}save();apply();toast(state.last)}
function apply(){document.body.classList.add("svr-phase329-android");const turn=document.getElementById("svr326Turn");if(turn)turn.textContent=state.seated?(state.turn?"YOUR TURN":"SEATED • WAITING"):"LOBBY MODE";const status=document.getElementById("svr326Status");if(status)status.textContent=state.last;const cc=[...document.querySelectorAll("#svr326Cards .svr326Card")];state.cards.forEach((v,i)=>{if(cc[i]){cc[i].textContent=v;cc[i].classList.toggle("red",/[♥♦]/.test(v))}});const slider=document.getElementById("svr326RaiseSlider");if(slider){slider.min="500";slider.max="10000";slider.step="500";slider.value=String(state.amount);slider.oninput=()=>{state.amount=Number(slider.value)||1000;save();apply()}}const amt=document.getElementById("svr326RaiseText");if(amt)amt.textContent=Number(state.amount||0).toLocaleString();document.querySelectorAll("#svr326Root button[data-act]").forEach(b=>{const ok=allowed(b.dataset.act);b.classList.toggle("svr329Valid",ok);b.classList.toggle("svr329Invalid",!ok);if(b.dataset.act==="sit")b.textContent=state.seated?"LOBBY":"SIT"});let inf=document.getElementById("svr329Info");if(!inf){inf=document.createElement("div");inf.id="svr329Info";document.body.appendChild(inf)}inf.innerHTML=`HAND ${state.hand}<br>AMOUNT ${Number(state.amount).toLocaleString()}<br>${state.turn?"YOUR TURN":"WAIT"}`;let q=document.getElementById("svr329QA");if(!q){q=document.createElement("div");q.id="svr329QA";document.body.appendChild(q)}q.textContent="ANDROID UX LOCK • ONE CONTROL SET";ring();window.SVR_PHASE329_ANDROID_UX_STATE={build:BUILD,active:true,state:{...state},controls:purge(),forceUpdate:false,showUpdatePrompt:false,checkedAt:new Date().toISOString()};return window.SVR_PHASE329_ANDROID_UX_STATE}
function hooks(){document.addEventListener("pointerdown",e=>{const b=e.target?.closest?.("#svr326Root button[data-act]");if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();b.classList.add("svr329Pulse");setTimeout(()=>b.classList.remove("svr329Pulse"),130);act(b.dataset.act)},true);document.addEventListener("pointerdown",e=>{const b=e.target?.closest?.("#svr326Root button[data-small]");if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();if(b.dataset.small==="up")state.amount+=500;if(b.dataset.small==="down")state.amount-=500;if(b.dataset.small==="center")return sit();state.amount=Math.max(500,Math.min(10000,state.amount));save();apply();toast("AMOUNT "+state.amount.toLocaleString())},true)}
function perf(){const r=window.__SVR_RENDERER__;try{r?.setPixelRatio?.(Math.min(window.devicePixelRatio||1,1.15));if(r?.shadowMap)r.shadowMap.enabled=false}catch{}}
function qa(){return{build:BUILD,active,controls:purge(),root:!!document.getElementById("svr326Root"),state:{...state},release:{forceUpdate:false,showUpdatePrompt:false}}}
function install(){if(!active||installed)return;installed=true;load();css();hooks();window.SVR_ANDROID_ACTION=act;window.SVR_ANDROID_DEAL_HAND=()=>act("deal");window.SVR_ANDROID_SIT_TO_TABLE=sit;window.SVR_ANDROID_TABLE_PLAYTEST_QA=qa;window.SVR_PHASE329={build:BUILD,active:true,siteTouched:false,helpers:["SVR_ANDROID_ACTION","SVR_ANDROID_DEAL_HAND","SVR_ANDROID_TABLE_PLAYTEST_QA"]};const loop=()=>{const n=performance.now();purge();perf();if(n-last>420){apply();last=n}raf=requestAnimationFrame(loop)};setTimeout(()=>{cards();apply();toast("ANDROID TABLE UX READY")},700);if(!raf)loop()}
setTimeout(install,260);setTimeout(install,1200);setTimeout(install,3200);
