const BUILD="PHASE-327-ANDROID-APK-RELEASE-CANDIDATE-LOCK";
const ua=navigator.userAgent||"";
const isQuest=/Quest|Oculus|Meta Quest/i.test(ua);
const active=(/Android/i.test(ua)&&!isQuest)||/\/game\/android\.html$/i.test(location.pathname)||new URLSearchParams(location.search).get("channel")==="stable";
const RELEASE={build:BUILD,channel:"stable",apkVersionName:"0.1.0-rc1",apkVersionCode:1,webEntry:"/game/android.html?channel=stable",forceUpdate:false,updatePrompt:false,nextApkDrop:"after stable Android playtest batch",createdAt:"2026-07-30T13:40:00-05:00"};
function css(){if(document.getElementById("svr-phase327-style"))return;const s=document.createElement("style");s.id="svr-phase327-style";s.textContent=`body.svr-phase327-android-release #svrAndroidGamePad,body.svr-phase327-android-release #svrTapMovePanel,body.svr-phase327-android-release #svrAndroidSafeBadge153,body.svr-phase327-android-release #svrAndroidLiteHud,body.svr-phase327-android-release #svrAndroidRecoverView{display:none!important;opacity:0!important;pointer-events:none!important}body.svr-phase327-android-release .svr-stick:not(#svr326Move):not(#svr326Look){display:none!important;opacity:0!important;pointer-events:none!important}#svr327ReleaseBadge{position:fixed;left:10px;top:10px;z-index:999997;border:1px solid rgba(127,252,255,.52);border-radius:999px;background:rgba(0,0,0,.48);color:#dffeff;padding:6px 10px;font:900 11px system-ui;letter-spacing:.08em;pointer-events:none}`;document.head.appendChild(s)}
function purge(){for(const q of ["#svrAndroidGamePad","#svrTapMovePanel","#svrAndroidSafeBadge153","#svrAndroidLiteHud","#svrAndroidRecoverView"]){document.querySelectorAll(q).forEach(e=>e.remove())}document.querySelectorAll(".svr-stick").forEach(e=>{if(e.id!=="svr326Move"&&e.id!=="svr326Look")e.remove()});const roots=[...document.querySelectorAll("#svr326Root")];roots.slice(1).forEach(e=>e.remove());}
function badge(){let b=document.getElementById("svr327ReleaseBadge");if(!b){b=document.createElement("div");b.id="svr327ReleaseBadge";document.body.appendChild(b)}b.textContent="ANDROID RC1 • NO FORCED APK UPDATE";}
function publish(action="ready"){window.SVR_ANDROID_RELEASE_CANDIDATE=RELEASE;window.SVR_APK_UPDATE_POLICY={channel:RELEASE.channel,currentVersionCode:RELEASE.apkVersionCode,currentVersionName:RELEASE.apkVersionName,forceUpdate:false,showUpdatePrompt:false,reason:"APK updates are held until an approved release batch."};window.SVR_PHASE327={build:BUILD,active,siteTouched:false,release:RELEASE,action,checkedAt:new Date().toISOString()};return window.SVR_PHASE327;}
function install(){if(!active)return;css();document.body.classList.add("svr-phase327-android-release");purge();badge();publish("installed");setInterval(()=>{purge();publish("monitor")},3500)}
window.SVR_GET_ANDROID_RELEASE_STATUS=()=>publish("manual-check");window.SVR_ANDROID_RELEASE_STATUS=()=>publish("status");setTimeout(install,180);setTimeout(install,1200);setTimeout(install,3200);
