import * as THREE from "three";

const LABEL="PHASE-133-ARTIFACT-WORKFLOW-LOCK";
const ROOT="PHASE133_ARTIFACT_WORKFLOW_ROOT";
const DUP="PHASE103_MAIN_TABLE_SURFACE";
const GREEN=0x86ffb7, RED=0xff5b8c, GOLD=0xffd98a;
let boardCanvas=null, boardTexture=null, boardMesh=null, ringMesh=null, report=null;
function count(scene,re){let n=0;scene?.traverse?.((o)=>{if(re.test(String(o.name||""))&&o.visible!==false)n++;});return n;}
function removeDuplicateTable(scene){let removed=0;let dup=scene?.getObjectByName?.(DUP);while(dup){dup.parent?.remove(dup);removed++;dup=scene.getObjectByName(DUP);}return removed;}
function phase(name){return !!window[name];}
function qa(scene){const checks={phase132:phase("SVR_PHASE132_FRESH_GAME_PACKAGE_PREP_RELEASE_NOTES_LOCK"),oneTable:!scene?.getObjectByName?.(DUP),runtime:!!window.__SVR_SCENE__&&!!window.__SVR_RENDERER__,poker:phase("SVR_PHASE125_QUEST_POKER_BUTTON_HITBOX_SELECTION_LOCK"),routes:phase("SVR_PHASE129_STOREFRONT_ROUTE_PREVIEW_PORTAL_POLISH_LOCK"),final:phase("SVR_PHASE130_PRODUCTION_DEMO_FINAL_READINESS_LOCK"),handoff:phase("SVR_PHASE131_MANUAL_QUEST_DEMO_TEST_HANDOFF_LOCK"),workflowNote:true,siteUntouched:true};const failed=Object.entries(checks).filter(([,ok])=>!ok).map(([k])=>k);return{build:LABEL,accepted:failed.length===0,checks,failed,workflowPath:".github/workflows/package-game.yml",artifactName:"game-zip",hiddenQa:"window.SVR_RUN_PHASE133_ARTIFACT_WORKFLOW_QA()",note:"Artifact workflow is prepared; binary artifact is created by GitHub Actions after manual test.",counts:{pokerObjects:count(scene,/POKER|TABLE|CARD|CHIP/i),routePanels:count(scene,/PHASE129_STOREFRONT_PREVIEW_PANEL/i),presencePills:count(scene,/PHASE128_PRESENCE_PILL_/i),watchObjects:count(scene,/WATCH/i)},checkedAt:new Date().toISOString()};}
function texture(r){if(!boardCanvas){boardCanvas=document.createElement("canvas");boardCanvas.width=1200;boardCanvas.height=620;}const c=boardCanvas,x=c.getContext("2d"),ok=!!r?.accepted,accent=ok?GREEN:RED,hex=`#${accent.toString(16).padStart(6,"0")}`;const bg=x.createLinearGradient(0,0,c.width,c.height);bg.addColorStop(0,"#02040a");bg.addColorStop(.55,"#130617");bg.addColorStop(1,"#02040a");x.fillStyle=bg;x.fillRect(0,0,c.width,c.height);x.strokeStyle="rgba(255,217,138,.88)";x.lineWidth=14;x.strokeRect(28,28,c.width-56,c.height-56);x.strokeStyle=hex;x.lineWidth=8;x.strokeRect(72,72,c.width-144,c.height-144);x.textAlign="center";x.textBaseline="middle";x.shadowColor=hex;x.shadowBlur=22;x.fillStyle="#fff8df";x.font="900 58px system-ui,Arial";x.fillText("ARTIFACT WORKFLOW",c.width/2,105,c.width-120);x.fillStyle=ok?"#8dffb4":"#ff9ab7";x.font="900 38px system-ui,Arial";x.fillText(ok?"READY AFTER MANUAL TEST":"CHECK BEFORE RUN",c.width/2,175,c.width-120);x.shadowBlur=8;const rows=[["WORKFLOW","Package Game Zip"],["OUTPUT","game-zip artifact"],["VERIFY","index.html at root"],["SITE","not touched"],["AUTO COMMIT","not enabled"]];x.textAlign="left";x.font="900 28px system-ui,Arial";rows.forEach((row,i)=>{const y=265+i*52;x.fillStyle="#ffd98a";x.fillText(row[0],135,y,280);x.fillStyle="#bffcff";x.fillText(row[1],420,y,660);});x.textAlign="center";x.fillStyle="#8dffb4";x.font="800 22px system-ui,Arial";x.fillText("RUN QA: window.SVR_RUN_PHASE133_ARTIFACT_WORKFLOW_QA()",c.width/2,560,c.width-140);if(!boardTexture){boardTexture=new THREE.CanvasTexture(c);boardTexture.colorSpace=THREE.SRGBColorSpace;boardTexture.anisotropy=4;}boardTexture.needsUpdate=true;return boardTexture;}
function protect(scene){let n=0;scene?.traverse?.((o)=>{const name=String(o.name||"");if(/POKER|TABLE|CARD|CHIP|ACTION|WATCH|HAND|TELEPORT|PORTAL|DOORWAY|PHASE116|PHASE117|PHASE118|PHASE119|PHASE120|PHASE121|PHASE122|PHASE123|PHASE124|PHASE125|PHASE126|PHASE127|PHASE128|PHASE129|PHASE130|PHASE131|PHASE132|MOON|MARS|SECOND_FLOOR|BALCONY/i.test(name)){o.visible=true;o.userData.phase133CoreProtected=true;if(o.isMesh){o.frustumCulled=false;n++;}}});return n;}
function add(scene,r){const root=scene.getObjectByName(ROOT);boardMesh=new THREE.Mesh(new THREE.PlaneGeometry(4.9,2.55),new THREE.MeshBasicMaterial({map:texture(r),transparent:true,side:THREE.DoubleSide,depthWrite:false}));boardMesh.name="PHASE133_ARTIFACT_WORKFLOW_BOARD";boardMesh.position.set(0,3.05,8.25);boardMesh.renderOrder=997;root.add(boardMesh);ringMesh=new THREE.Mesh(new THREE.RingGeometry(1.55,1.78,96),new THREE.MeshBasicMaterial({color:r.accepted?GREEN:RED,transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));ringMesh.name="PHASE133_ARTIFACT_WORKFLOW_FLOOR_RING";ringMesh.position.set(0,.13,6.2);ringMesh.rotation.x=-Math.PI/2;ringMesh.renderOrder=996;root.add(ringMesh);}
function clean(){document.title="Scarlett Poker VR";const s=document.getElementById("safeStatus");if(s)s.textContent="Loading Scarlett Poker VR lobby...";document.querySelectorAll(".pill").forEach((el)=>{el.textContent="SCARLETT POKER VR";});}
function animate(){if(window.SVR_PHASE133_ARTIFACT_ANIMATION)return;window.SVR_PHASE133_ARTIFACT_ANIMATION=true;const tick=()=>{const t=performance.now()*.001;if(boardMesh){boardMesh.lookAt(0,1.55,0);boardMesh.position.y=3.05+Math.sin(t*1.05)*.018;}if(ringMesh){ringMesh.scale.setScalar(1+Math.sin(t*1.65)*.035);ringMesh.material.opacity=.18+Math.sin(t*2.1)*.055;}requestAnimationFrame(tick);};requestAnimationFrame(tick);}
function install(){const scene=window.__SVR_SCENE__;if(!scene)return false;const old=scene.getObjectByName(ROOT);if(old)old.parent?.remove(old);const root=new THREE.Group();root.name=ROOT;scene.add(root);clean();const removedDuplicateTable=removeDuplicateTable(scene);const protectedObjects=protect(scene);report=qa(scene);add(scene,report);animate();window.SVR_PHASE133_ARTIFACT_WORKFLOW_LOCK={build:LABEL,active:true,artifactWorkflow:true,accepted:report.accepted,removedDuplicateTable,protectedObjects,report,siteTouched:false,publicRootTouched:false,pokerLogicTouched:false,portalRoutesTouched:false,watchTouched:false,movementTouched:false,binaryArtifactCreatedHere:false,questSafe:true,checkedAt:new Date().toISOString()};window.SVR_RUN_PHASE133_ARTIFACT_WORKFLOW_QA=()=>{report=qa(scene);if(boardMesh?.material){boardMesh.material.map=texture(report);boardMesh.material.needsUpdate=true;}if(ringMesh?.material)ringMesh.material.color.setHex(report.accepted?GREEN:RED);return report;};window.SVR_LIVE_BUILD_POINTER=LABEL;window.SVR_LOCKED_FINAL_BUILD=LABEL;return true;}
install();let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>40)clearInterval(timer);},300);[900,2000,4000,8000,12000].forEach((d)=>setTimeout(install,d));
