import * as THREE from "three";
const BUILD="PHASE-250-LOBBY-FINAL-TABLE-SEAT-LOCK";
const GOLD=0xffd98a,CYAN=0x7ffcff,GREEN=0x8dffb4,RED=0xff5b5b,PURPLE=0xa77cff;
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function glow(c,o=.4){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending})}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.35})}
function labelTex(a,b,color="#ffd98a"){const c=document.createElement("canvas");c.width=900;c.height=360;const g=c.getContext("2d");g.fillStyle="#030711";g.fillRect(0,0,900,360);g.strokeStyle=color;g.lineWidth=10;g.strokeRect(20,20,860,320);g.textAlign="center";g.textBaseline="middle";g.fillStyle="#fff";g.font="900 54px system-ui,Arial";g.fillText(a.toUpperCase(),450,132);g.fillStyle=color;g.font="800 32px system-ui,Arial";g.fillText(b,450,230);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
function panel(root,name,a,b,x,y,z,color,w=2.25,h=.9){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:labelTex(a,b,"#"+color.toString(16).padStart(6,"0")),transparent:true,side:THREE.DoubleSide,depthWrite:false}));p.name=name;p.position.set(x,y,z);p.renderOrder=600;root.add(p);return p}
function hideExtra(scene){let hidden=0;scene.traverse(o=>{if(!o.name)return;if(/^PHASE248_MAIN_READABILITY_BOARD/.test(o.name)){o.visible=false;hidden++}if(/^PHASE249_CLEAR_CENTER_AISLE_GUIDE/.test(o.name)){o.visible=false;hidden++}});return hidden}
function addTableFinal(scene){const root=new THREE.Group();root.name="PHASE250_LOBBY_FINAL_TABLE_SEAT_ROOT";scene.add(root);const ring=new THREE.Mesh(new THREE.RingGeometry(3.45,3.55,160),glow(GOLD,.42));ring.name="PHASE250_FINAL_TABLE_CLEARANCE_RING";ring.rotation.x=-Math.PI/2;ring.position.set(0,.18,.55);root.add(ring);const active=new THREE.Mesh(new THREE.RingGeometry(.82,1.02,96),glow(GREEN,.62));active.name="PHASE250_OPEN_FRONT_SOUTH_SEAT_FINAL";active.rotation.x=-Math.PI/2;active.position.set(0,.21,3.55);root.add(active);panel(root,"PHASE250_OPEN_SEAT_FLOAT_LABEL","OPEN SEAT","Walk here to join",0,1.18,3.55,GREEN,2.7,.82);const seats=[[0,3.55,"YOU","OPEN",GREEN],[-2.85,2.2,"BOT 1","READY",CYAN],[-3.25,-.85,"BOT 2","READY",CYAN],[-1.55,-3.05,"BOT 3","READY",CYAN],[1.55,-3.05,"BOT 4","READY",CYAN],[3.25,-.85,"BOT 5","READY",CYAN],[2.85,2.2,"DEALER","AUTO",GOLD]];seats.forEach(([x,z,a,b,c],i)=>{const pad=new THREE.Mesh(new THREE.RingGeometry(.48,.58,64),glow(c,.34));pad.name=`PHASE250_SEAT_PAD_${i}`;pad.rotation.x=-Math.PI/2;pad.position.set(x,.19,z);root.add(pad);panel(root,`PHASE250_SEAT_LABEL_${i}`,a,b,x,.92,z,c,1.25,.48)});const pot=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.12,48),basic(GOLD,.7));pot.name="PHASE250_FINAL_POT_MARKER";pot.position.set(0,.38,.38);root.add(pot);panel(root,"PHASE250_TABLE_STATUS_PANEL","POKER TABLE","5 bots ready • 1 open seat",0,2.22,-2.75,GOLD,3.7,.78);return root}
function addFinalLobbySeal(scene){const root=scene.getObjectByName("PHASE250_LOBBY_FINAL_TABLE_SEAT_ROOT");if(!root)return;panel(root,"PHASE250_LOBBY_FINISHED_SEAL","SVR LOBBY","Finished hub layout locked",0,5.05,-13.85,PURPLE,4.2,.9);const line=new THREE.Mesh(new THREE.PlaneGeometry(32,.06),glow(CYAN,.30));line.name="PHASE250_FINAL_BACK_WALL_CYAN_SEAL";line.position.set(0,4.55,-13.8);root.add(line)}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE250_LOBBY_FINAL_TABLE_SEAT_ROOT"))return;const hidden=hideExtra(scene);addTableFinal(scene);addFinalLobbySeal(scene);window.SVR_PHASE250_LOBBY_FINAL_TABLE_SEAT={build:BUILD,active:true,siteTouched:false,hidden,finishedLobby:true,tableReady:true,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 250 ACTIVE • FINISHED LOBBY TABLE READY";const s=document.getElementById("status");if(s)s.textContent="Phase 250 finished lobby table/seat lock active"}
install();
