import * as THREE from "three";
const BUILD="PHASE-254-JOIN-TABLE-FLOW-LOCK";
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function glow(c,o=.45){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending})}
function tex(a,b,c="#8dffb4"){const cn=document.createElement("canvas");cn.width=900;cn.height=360;const g=cn.getContext("2d");g.fillStyle="#030711";g.fillRect(0,0,900,360);g.strokeStyle=c;g.lineWidth=10;g.strokeRect(20,20,860,320);g.textAlign="center";g.textBaseline="middle";g.fillStyle="#fff";g.font="900 50px system-ui,Arial";g.fillText(a.toUpperCase(),450,120);g.fillStyle=c;g.font="800 30px system-ui,Arial";g.fillText(b,450,230);const t=new THREE.CanvasTexture(cn);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
function panel(root,n,a,b,x,y,z,c="#8dffb4"){const p=new THREE.Mesh(new THREE.PlaneGeometry(2.6,.95),new THREE.MeshBasicMaterial({map:tex(a,b,c),transparent:true,side:THREE.DoubleSide,depthWrite:false}));p.name=n;p.position.set(x,y,z);p.renderOrder=760;root.add(p);return p}
function state(seated=false){window.SVR_TABLE_STATE={seated,seat:"south",playerChips:50000,bots:5,dealer:"auto",phase:"waiting",updatedAt:new Date().toISOString()}}
function join(){state(true);window.dispatchEvent(new CustomEvent("svr:table-joined",{detail:window.SVR_TABLE_STATE}));const s=document.getElementById("status");if(s)s.textContent="Joined table: south seat active";return true}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE254_JOIN_TABLE_FLOW_ROOT"))return;const root=new THREE.Group();root.name="PHASE254_JOIN_TABLE_FLOW_ROOT";scene.add(root);const ring=new THREE.Mesh(new THREE.RingGeometry(1.05,1.22,96),glow(0x8dffb4,.68));ring.name="PHASE254_JOIN_SEAT_ACTIVE_RING";ring.rotation.x=-Math.PI/2;ring.position.set(0,.33,3.55);root.add(ring);panel(root,"PHASE254_JOIN_PROMPT","JOIN TABLE","Confirm to sit",0,1.65,3.55,"#8dffb4");panel(root,"PHASE254_BOT_READY_PANEL","BOTS READY","5 players online",-2.8,1.55,1.75,"#7ffcff");panel(root,"PHASE254_DEALER_READY_PANEL","DEALER","Auto deal ready",2.8,1.55,1.75,"#ffd98a");state(false);window.SVR_JOIN_TABLE=join;window.addEventListener("svr:join-table",join);const oldConfirm=window.SVR_CONFIRM_INTERACTION;window.SVR_CONFIRM_INTERACTION=()=>{const near=window.SVR_PHASE253_INTERACTION_STATE?.near;if(near==="seat"||near==="play")return join();return oldConfirm?oldConfirm():false};window.SVR_PHASE254_JOIN_TABLE_FLOW={build:BUILD,active:true,siteTouched:false,helpers:["SVR_JOIN_TABLE","SVR_CONFIRM_INTERACTION"],checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 254 ACTIVE • JOIN TABLE FLOW";const s=document.getElementById("status");if(s)s.textContent="Phase 254 join table flow active"}
install();
