import * as THREE from "three";
const LABEL="PHASE-257-ROMAN-CANOPY-LOBBY-ARCH-LOCK";
const ROOT="PHASE257_ROMAN_CANOPY_ROOT";
const GOLD=0xffd98a,CYAN=0x7ffcff,STONE=0xd8d0bc,DARK=0x090b14,PURPLE=0x9f5cff;
function mat(c,a=1,m=.05,r=.55){return new THREE.MeshStandardMaterial({color:c,transparent:a<1,opacity:a,metalness:m,roughness:r,side:THREE.DoubleSide});}
function glow(c,a=.4){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:a,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending});}
function cyl(root,n,r,h,x,y,z,ma){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,32),ma);o.name=n;o.position.set(x,y,z);root.add(o);return o;}
function box(root,n,sx,sy,sz,x,y,z,ma){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),ma);o.name=n;o.position.set(x,y,z);root.add(o);return o;}
function arch(root,n,rad,tube,x,y,z,ma,ry=0){const o=new THREE.Mesh(new THREE.TorusGeometry(rad,tube,12,56,Math.PI),ma);o.name=n;o.position.set(x,y,z);o.rotation.y=ry;root.add(o);return o;}
function stamp(){window.SVR_PHASE257={build:LABEL,active:true,romanCanopy:true,cornerPillars:true,lobbyArchRhythm:true,siteTouched:false,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=LABEL;try{document.title=`SVR Poker • ${LABEL}`}catch{};const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 257 ACTIVE • ROMAN CANOPY";const s=document.getElementById("status");if(s)s.textContent="Phase 257 Roman canopy and pillar polish loaded";}
function textPanel(root){const c=document.createElement("canvas");c.width=900;c.height=260;const g=c.getContext("2d");g.fillStyle="rgba(4,6,16,.88)";g.fillRect(0,0,c.width,c.height);g.strokeStyle="#ffd98a";g.lineWidth=8;g.strokeRect(12,12,c.width-24,c.height-24);g.textAlign="center";g.textBaseline="middle";g.fillStyle="#ffd98a";g.font="900 42px system-ui,Arial";g.fillText("SVR ROMAN CANOPY",450,98);g.fillStyle="#7ffcff";g.font="800 24px system-ui,Arial";g.fillText("central arch feature • smooth lobby rhythm",450,164);const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;const p=new THREE.Mesh(new THREE.PlaneGeometry(4.4,1.05),new THREE.MeshBasicMaterial({map:tx,transparent:true,side:THREE.DoubleSide,depthWrite:false}));p.name="PHASE257_CANOPY_SIGN";p.position.set(0,4.2,1.05);p.rotation.y=Math.PI;root.add(p);}
function build(scene){const old=scene.getObjectByName(ROOT);if(old)old.parent?.remove(old);const root=new THREE.Group();root.name=ROOT;scene.add(root);const stone=mat(STONE,.94,.02,.48),gold=mat(GOLD,.92,.22,.38),dark=mat(DARK,.76,.02,.66),cg=glow(CYAN,.34),pg=glow(PURPLE,.22);const bx=3.1,bz=2.2,cz=-1.35,cy=3.55;[[-bx,-bz],[bx,-bz],[-bx,bz],[bx,bz]].forEach(([x,z],i)=>{cyl(root,`PHASE257_CANOPY_PILLAR_${i}`,.16,3.35,x,1.75,cz+z,stone);cyl(root,`PHASE257_CANOPY_BASE_${i}`,.30,.12,x,.12,cz+z,gold);cyl(root,`PHASE257_CANOPY_CAP_${i}`,.25,.14,x,3.5,cz+z,gold);});box(root,"PHASE257_CANOPY_FRONT_BEAM",6.65,.13,.15,0,cy,cz+bz,gold);box(root,"PHASE257_CANOPY_BACK_BEAM",6.65,.13,.15,0,cy,cz-bz,gold);box(root,"PHASE257_CANOPY_LEFT_BEAM",.15,.13,4.8,-bx,cy,cz,gold);box(root,"PHASE257_CANOPY_RIGHT_BEAM",.15,.13,4.8,bx,cy,cz,gold);box(root,"PHASE257_CANOPY_TOP_PANEL",6.2,.035,4.25,0,3.72,cz,dark);box(root,"PHASE257_CANOPY_CYAN_UNDERGLOW",5.9,.02,3.9,0,3.48,cz,cg);box(root,"PHASE257_CANOPY_PURPLE_DRAPE",1.35,.028,4.15,0,3.76,cz,pg);arch(root,"PHASE257_FRONT_ROMAN_ARCH",3.12,.035,0,3.18,cz+bz+.06,gold,0);arch(root,"PHASE257_BACK_ROMAN_ARCH",3.12,.035,0,3.18,cz-bz-.06,gold,Math.PI);const la=arch(root,"PHASE257_LEFT_ROMAN_ARCH",2.22,.035,-bx-.06,3.18,cz,gold,Math.PI/2);la.scale.x=1.38;const ra=arch(root,"PHASE257_RIGHT_ROMAN_ARCH",2.22,.035,bx+.06,3.18,cz,gold,-Math.PI/2);ra.scale.x=1.38;[[-12.8,-9.8],[12.8,-9.8],[-12.8,6.4],[12.8,6.4]].forEach(([x,z],i)=>{cyl(root,`PHASE257_CORNER_PILLAR_${i}`,.22,3.55,x,1.85,z,stone);cyl(root,`PHASE257_CORNER_BASE_${i}`,.36,.12,x,.12,z,gold);cyl(root,`PHASE257_CORNER_CAP_${i}`,.34,.14,x,3.62,z,gold);});for(let i=0;i<7;i++){const x=-9+i*3;cyl(root,`PHASE257_BACK_WALL_PILLAR_${i}`,.1,2.65,x,1.45,-11.5,stone);box(root,`PHASE257_BACK_WALL_RAIL_${i}`,2.35,.07,.07,x,2.84,-11.45,gold);arch(root,`PHASE257_BACK_WALL_ARCH_${i}`,1.08,.025,x,2.74,-11.38,gold,0);}[-1,1].forEach(side=>{for(let i=0;i<4;i++){const z=-7.5+i*3.4;cyl(root,`PHASE257_SIDE_${side}_PILLAR_${i}`,.1,2.45,side*13.3,1.35,z,stone);box(root,`PHASE257_SIDE_${side}_CYAN_RAIL_${i}`,.06,.055,2.25,side*13.18,2.72,z,cg);}});textPanel(root);window.SVR_PHASE257_GEOMETRY={build:LABEL,centerCanopy:true,cornerPillars:4,edgeArchRhythm:true,checkedAt:new Date().toISOString()};}
function install(){stamp();const scene=window.__SVR_SCENE__;if(!scene)return false;build(scene);return true;}
stamp();let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>180)clearInterval(timer)},180);setTimeout(install,1600);setTimeout(install,4200);
