import * as THREE from "three";
const BUILD="PHASE-261-TURN-TIMER-ACTIVE-PLAYER-RING-LOCK";
const ORDER=["seat-south","bot-left-front","bot-left-mid","bot-left-back","bot-right-back","bot-right-mid","bot-right-front"];
const POS={"seat-south":[0,3.05],"bot-left-front":[-2.55,1.85],"bot-left-mid":[-2.85,.25],"bot-left-back":[-1.45,-1.75],"bot-right-back":[1.45,-1.75],"bot-right-mid":[2.85,.25],"bot-right-front":[2.55,1.85]};
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function glow(c,o=.52){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending})}
function moveRing(r,seat){const p=POS[seat]||POS[ORDER[0]];r.position.set(p[0],.5,p[1])}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE261_TURN_TIMER_ROOT"))return;const root=new THREE.Group();root.name="PHASE261_TURN_TIMER_ROOT";scene.add(root);const ring=new THREE.Mesh(new THREE.RingGeometry(.7,.82,96),glow(0xffd98a,.68));ring.name="PHASE261_ACTIVE_PLAYER_RING";ring.rotation.x=-Math.PI/2;root.add(ring);const timerRing=new THREE.Mesh(new THREE.RingGeometry(.88,.94,96),glow(0x7ffcff,.42));timerRing.name="PHASE261_TURN_TIMER_RING";timerRing.rotation.x=-Math.PI/2;root.add(timerRing);let index=0;let expires=Date.now()+20000;function setTurn(i){index=((i%ORDER.length)+ORDER.length)%ORDER.length;const seat=ORDER[index];moveRing(ring,seat);moveRing(timerRing,seat);expires=Date.now()+20000;window.SVR_TURN_STATE={build:BUILD,active:true,currentSeat:seat,index,timeLimitMs:20000,expiresAt:expires,dealRule:window.SVR_DEAL_ORDER_LOCK?.direction||"left-to-right",updatedAt:new Date().toISOString()};const s=document.getElementById("status");if(s)s.textContent="Active turn: "+seat;return window.SVR_TURN_STATE}function tick(){const left=Math.max(0,expires-Date.now());const scale=.72+.24*(left/20000);timerRing.scale.set(scale,scale,scale);if(left<=0)setTurn(index+1);requestAnimationFrame(tick)}window.SVR_SET_ACTIVE_TURN=setTurn;window.SVR_NEXT_TURN=()=>setTurn(index+1);setTurn(0);tick();window.SVR_PHASE261_TURN_TIMER={build:BUILD,active:true,siteTouched:false,order:ORDER,helper:["SVR_SET_ACTIVE_TURN","SVR_NEXT_TURN"],checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 261 ACTIVE • TURN TIMER LOCK"}
install();
