import * as THREE from "three";
const BUILD = "PHASE-249-GEOMETRY-SMOOTHNESS-LOCK";
const GOLD = 0xffd98a, CYAN = 0x7ffcff, GREEN = 0x8dffb4;
function waitForScene(){ return new Promise((resolve)=>{ let n=0; const tick=()=>{ if(window.__SVR_SCENE__) return resolve(window.__SVR_SCENE__); if(++n>360) return resolve(null); requestAnimationFrame(tick); }; tick(); }); }
function basic(color, opacity=1){ return new THREE.MeshBasicMaterial({ color, transparent:opacity<1, opacity, side:THREE.DoubleSide, depthWrite:opacity>.35 }); }
function glow(color, opacity=.34){ return new THREE.MeshBasicMaterial({ color, transparent:true, opacity, side:THREE.DoubleSide, depthWrite:false, blending:THREE.AdditiveBlending }); }
function cleanVisualNoise(scene){ let hidden=0, tuned=0; const names=[/^PHASE244_.*PORTAL_CORE/,/^PHASE245_BACK_WINDOW_SKYLINE_LIGHTS/,/^PHASE247_POLISHED_MAIN_FLOOR_.*ACCENT/,/^PHASE248_READABLE_.*SIGN/]; scene.traverse((obj)=>{ if(obj.name && names.some(r=>r.test(obj.name))){ obj.visible=false; hidden++; } if(obj.isMesh){ obj.frustumCulled=true; const mats=Array.isArray(obj.material)?obj.material:[obj.material]; mats.forEach((m)=>{ if(!m) return; if(m.transparent && m.opacity>.55 && /GLASS|HALO|GLOW|RING/.test(obj.name||"")){ m.opacity=.32; tuned++; } if(m.roughness!==undefined && m.roughness<.45){ m.roughness=.58; tuned++; } }); } }); return {hidden,tuned}; }
function addGuides(scene){ const root=new THREE.Group(); root.name="PHASE249_GEOMETRY_SMOOTHNESS_ROOT"; scene.add(root); const tableRing=new THREE.Mesh(new THREE.RingGeometry(3.25,3.36,128),glow(GOLD,.22)); tableRing.name="PHASE249_CLEAN_TABLE_CLEARANCE_RING"; tableRing.rotation.x=-Math.PI/2; tableRing.position.set(0,.125,.55); root.add(tableRing); const aisle=new THREE.Mesh(new THREE.PlaneGeometry(4.8,12.5),basic(0x07111d,.20)); aisle.name="PHASE249_CLEAR_CENTER_AISLE_GUIDE"; aisle.rotation.x=-Math.PI/2; aisle.position.set(0,.118,2.8); root.add(aisle); const left=new THREE.Mesh(new THREE.PlaneGeometry(.08,13.2),glow(CYAN,.20)); left.name="PHASE249_LEFT_AISLE_EDGE"; left.rotation.x=-Math.PI/2; left.position.set(-2.55,.13,2.7); root.add(left); const right=left.clone(); right.name="PHASE249_RIGHT_AISLE_EDGE"; right.position.x=2.55; root.add(right); const seat=new THREE.Mesh(new THREE.RingGeometry(.78,.92,80),glow(GREEN,.52)); seat.name="PHASE249_OPEN_SOUTH_SEAT_MARKER"; seat.rotation.x=-Math.PI/2; seat.position.set(0,.16,3.35); root.add(seat); return true; }
async function install(){ const scene=await waitForScene(); if(!scene || scene.getObjectByName("PHASE249_GEOMETRY_SMOOTHNESS_ROOT")) return; const cleanup=cleanVisualNoise(scene); const guides=addGuides(scene); window.SVR_PHASE249_GEOMETRY_SMOOTHNESS_LOCK={build:BUILD,active:true,siteTouched:false,cleanup,guides,rules:["center aisle clearer","open south seat marked","visual glow reduced","materials softened","culling enabled"],checkedAt:new Date().toISOString()}; window.SVR_LOCKED_FINAL_BUILD=BUILD; const label=document.getElementById("svr-phase-label"); if(label) label.textContent="PHASE 249 ACTIVE • GEOMETRY SMOOTHNESS"; const status=document.getElementById("status"); if(status) status.textContent="Phase 249 geometry smoothness active"; }
install();
