import * as THREE from "three";
const BUILD="PHASE-258-LEFT-TO-RIGHT-DEAL-ANIMATION-FLOW-LOCK";
const ORDER=["seat-south","bot-left-front","bot-left-mid","bot-left-back","bot-right-back","bot-right-mid","bot-right-front"];
const POS={"seat-south":[0,2.72],"bot-left-front":[-2.55,1.85],"bot-left-mid":[-2.85,.25],"bot-left-back":[-1.45,-1.75],"bot-right-back":[1.45,-1.75],"bot-right-mid":[2.85,.25],"bot-right-front":[2.55,1.85]};
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function material(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.4})}
function card(name){const c=new THREE.Mesh(new THREE.PlaneGeometry(.32,.46),material(0xffffff,.95));c.name=name;c.rotation.x=-Math.PI/2;c.position.set(0,.72,-.55);return c}
function buildSequence(){const list=[];for(let round=1;round<=2;round++){ORDER.forEach(seat=>list.push({seat,round,target:POS[seat]}))}return list}
function run(root,list){const start=performance.now();const dur=420;function tick(now){const elapsed=now-start;list.forEach((step,i)=>{const obj=root.getObjectByName("PHASE258_CARD_"+i);if(!obj)return;const local=elapsed-i*130;if(local<0)return;const p=Math.min(1,local/dur);const e=p*p*(3-2*p);const tx=step.target[0],tz=step.target[1];obj.position.x=tx*e;obj.position.z=-.55+(tz+.55)*e;obj.position.y=.72-(.28*e)});if(elapsed<list.length*130+dur)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE258_DEAL_ANIMATION_ROOT"))return;const root=new THREE.Group();root.name="PHASE258_DEAL_ANIMATION_ROOT";scene.add(root);const list=buildSequence();list.forEach((s,i)=>root.add(card("PHASE258_CARD_"+i)));window.SVR_DEAL_ANIMATION_SEQUENCE=list;window.SVR_PLAY_LEFT_TO_RIGHT_DEAL=()=>{run(root,list);const st=document.getElementById("status");if(st)st.textContent="Dealing left to right";return true};window.SVR_PHASE258_DEAL_ANIMATION={build:BUILD,active:true,siteTouched:false,direction:"left-to-right",cards:list.length,order:ORDER,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 258 ACTIVE • DEAL ANIMATION LOCK";const s=document.getElementById("status");if(s)s.textContent="Phase 258 left-to-right deal animation ready"}
install();
