import * as THREE from "three";
const BUILD="PHASE-263-POT-CHIP-MOVEMENT-LOCK";
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function mat(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.4})}
function chip(name,x,z,c){const m=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,.06,24),mat(c,.92));m.name=name;m.position.set(x,.5,z);return m}
function format(n){return "$"+Number(n||0).toLocaleString()}
function updateText(){const s=document.getElementById("status");if(s&&window.SVR_CHIP_POT_STATE)s.textContent="Pot "+format(window.SVR_CHIP_POT_STATE.pot)+" • Chips "+format(window.SVR_CHIP_POT_STATE.playerChips)}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE263_POT_CHIP_ROOT"))return;const root=new THREE.Group();root.name="PHASE263_POT_CHIP_ROOT";scene.add(root);for(let i=0;i<12;i++)root.add(chip("PHASE263_POT_CHIP_"+i,(i%4)*.16-.24,.2+Math.floor(i/4)*.13,0xffd98a));for(let i=0;i<10;i++)root.add(chip("PHASE263_PLAYER_STACK_"+i,(i%5)*.13-.26,2.28+Math.floor(i/5)*.12,0x7ffcff));window.SVR_CHIP_POT_STATE={build:BUILD,active:true,pot:0,currentBet:0,playerChips:50000,lastMove:null,history:[],dealRule:window.SVR_DEAL_ORDER_LOCK?.direction||"left-to-right",updatedAt:new Date().toISOString()};const old=window.SVR_SELECT_ACTION;function apply(action,amount=1000){const st=window.SVR_CHIP_POT_STATE;let move=0;if(action==="Call")move=Math.min(amount,st.playerChips);if(action==="Raise")move=Math.min(amount*2,st.playerChips);if(action==="All In")move=st.playerChips;if(move>0){st.playerChips-=move;st.pot+=move;st.currentBet=Math.max(st.currentBet,move);st.lastMove={action,move,at:new Date().toISOString()};st.history.push(st.lastMove)}st.updatedAt=new Date().toISOString();updateText();return st}window.SVR_MOVE_CHIPS_TO_POT=apply;window.SVR_SELECT_ACTION=(action)=>{const result=apply(action);const ok=old?old(action)!==false:true;window.dispatchEvent(new CustomEvent("svr:pot-updated",{detail:result}));return ok};window.SVR_PHASE263_POT_CHIP_MOVEMENT={build:BUILD,active:true,siteTouched:false,helpers:["SVR_MOVE_CHIPS_TO_POT","SVR_SELECT_ACTION"],checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 263 ACTIVE • POT CHIP LOCK";updateText()}
install();
