import * as THREE from "three";
const BUILD="PHASE-326-ANDROID-PLAYABLE-POLISH-LOCK";
const ua=navigator.userAgent||"";
const active=/Android/i.test(ua)&&!/Quest|Oculus|Meta Quest/i.test(ua)||/\/game\/android\.html$/i.test(location.pathname);
let installed=false,raf=0,seated=false,myTurn=false,raiseAmount=1000;
const left={id:null,x:0,y:0,dx:0,dy:0},right={id:null,x:0,y:0,dx:0,dy:0};
function scene(){return window.__SVR_SCENE__||null}
function camera(){return window.__SVR_RENDERER__?.xr?.isPresenting?window.__SVR_RENDERER__.xr.getCamera(window.__SVR_CAMERA__):window.__SVR_CAMERA__}
function renderer(){return window.__SVR_RENDERER__||null}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null}
function base(){const s=scene();return s?.getObjectByName?.("PHASE200_ORDERED_GRAND_LOBBY_ROOT")||s}
function table(){const b=base();return b?.getObjectByName?.("PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED")||b?.getObjectByName?.("PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT")||b?.getObjectByName?.("PHASE326_ANDROID_TABLE_FALLBACK")||null}
function tb(){const t=table();if(!t)return null;t.visible=true;t.traverse?.(o=>o.visible=true);t.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(t),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);return{obj:t,box,size,center,top:box.max.y}}
function css(){if(document.getElementById("svr-phase326-style"))return;const s=document.createElement("style");s.id="svr-phase326-style";s.textContent=`
#svrAndroidGamePad,#svrTapMovePanel,#svrAndroidSafeBadge153,#svrAndroidLiteHud,#svrAndroidRecoverView{display:none!important;opacity:0!important;pointer-events:none!important}
body.svr-phase326-android .svr-stick:not(#svr326Move):not(#svr326Look){display:none!important;opacity:0!important;pointer-events:none!important}
#svr326Root{position:fixed;inset:0;z-index:999999;pointer-events:none;font-family:system-ui,Arial,sans-serif;color:white}#svr326Root *{box-sizing:border-box}#svr326Move,#svr326Look{position:absolute;width:128px;height:128px;border:2px solid rgba(127,252,255,.58);border-radius:50%;background:rgba(0,8,20,.32);box-shadow:0 0 22px rgba(127,252,255,.22);pointer-events:auto;touch-action:none}#svr326Move{left:22px;bottom:30px}#svr326Look{right:22px;bottom:30px}.svr326Knob{position:absolute;left:41px;top:41px;width:46px;height:46px;border-radius:50%;background:rgba(127,252,255,.78);box-shadow:0 0 26px rgba(127,252,255,.55)}.svr326Label{position:absolute;bottom:-34px;width:100%;text-align:center;font-weight:900;letter-spacing:.12em;text-shadow:0 2px 6px #000}.svr326Actions{position:absolute;right:14px;bottom:180px;display:grid;grid-template-columns:repeat(2,84px);gap:9px;pointer-events:auto}.svr326Actions button,.svr326Small button{height:48px;border:1px solid rgba(255,217,138,.76);border-radius:14px;background:rgba(5,8,16,.80);color:white;font-weight:950;font-size:15px;box-shadow:0 0 12px rgba(255,217,138,.08)}.svr326Actions button.ready{border-color:#7ffcff;background:rgba(0,80,92,.72);box-shadow:0 0 18px rgba(127,252,255,.35);transform:scale(1.04)}.svr326Actions button:active,.svr326Small button:active{transform:scale(.94)}#svr326Status{position:absolute;left:50%;transform:translateX(-50%);bottom:164px;min-width:210px;text-align:center;border:1px solid rgba(127,252,255,.42);border-radius:16px;background:rgba(0,0,0,.55);padding:9px 12px;font-weight:950;letter-spacing:.05em;pointer-events:none}#svr326Cards{position:absolute;left:50%;transform:translateX(-50%);bottom:238px;display:flex;align-items:center;gap:8px;padding:8px 10px;border:1px solid rgba(255,217,138,.72);border-radius:16px;background:rgba(0,0,0,.55);pointer-events:none}.svr326Card{width:48px;height:68px;border-radius:7px;background:#f7f2e5;color:#111;display:grid;place-items:center;font-weight:1000;font-size:21px;border:2px solid #111}.svr326Card.red{color:#a00018}#svr326Turn{position:absolute;left:50%;top:16px;transform:translateX(-50%);padding:9px 18px;border-radius:999px;border:1px solid rgba(127,252,255,.7);background:rgba(0,0,0,.62);font-weight:1000;letter-spacing:.08em;box-shadow:0 0 20px rgba(127,252,255,.22)}#svr326Raise{position:absolute;left:50%;transform:translateX(-50%);bottom:104px;width:min(70vw,360px);border:1px solid rgba(255,217,138,.62);border-radius:16px;background:rgba(0,0,0,.56);padding:8px 10px;pointer-events:auto;text-align:center;font-weight:950}#svr326Raise input{width:100%;accent-color:#ffd98a}.svr326Small{display:flex;gap:8px;justify-content:center;margin-top:5px}.svr326Small button{height:34px;min-width:68px;font-size:12px}body:not(.svr-phase326-android) #svr326Root{display:none!important}`;document.head.appendChild(s)}
function purge(){for(const e of Array.from(document.querySelectorAll("#svrAndroidGamePad,#svrTapMovePanel,#svrAndroidSafeBadge153,#svrAndroidLiteHud,#svrAndroidRecoverView")))e.remove();for(const e of Array.from(document.querySelectorAll(".svr-stick"))){if(e.id!=="svr326Move"&&e.id!=="svr326Look")e.remove();}const roots=Array.from(document.querySelectorAll("#svr326Root"));roots.slice(1).forEach(e=>e.remove());}
function makeUI(){let r=document.getElementById("svr326Root");if(r)return r;r=document.createElement("div");r.id="svr326Root";r.innerHTML=`<div id="svr326Turn">LOBBY MODE</div><div id="svr326Cards"><span style="font-weight:950;color:#ffd98a">YOUR CARDS</span><div class="svr326Card">--</div><div class="svr326Card">--</div></div><div class="svr326Actions"><button data-act="deal">DEAL</button><button data-act="sit">SIT</button><button data-act="check">CHECK</button><button data-act="call">CALL</button><button data-act="raise">RAISE</button><button data-act="clean">CLEAN</button></div><div id="svr326Raise"><div>RAISE AMOUNT: <span id="svr326RaiseText">1,000</span></div><input id="svr326RaiseSlider" type="range" min="500" max="10000" step="500" value="1000"><div class="svr326Small"><button data-small="down">-500</button><button data-small="up">+500</button><button data-small="center">CENTER</button></div></div><div id="svr326Status">ANDROID GAME CONTROLS</div><div id="svr326Move" class="svr-stick"><b class="svr326Knob"></b><div class="svr326Label">MOVE</div></div><div id="svr326Look" class="svr-stick"><b class="svr326Knob"></b><div class="svr326Label">LOOK</div></div>`;document.body.appendChild(r);return r}
function bindStick(el,st){if(!el||el.__svr326)return;el.__svr326=true;const k=el.querySelector("b");const reset=()=>{st.id=null;st.dx=0;st.dy=0;if(k)k.style.transform="translate(0,0)"};el.addEventListener("pointerdown",e=>{st.id=e.pointerId;const b=el.getBoundingClientRect();st.x=b.left+b.width/2;st.y=b.top+b.height/2;el.setPointerCapture?.(e.pointerId);e.preventDefault()},{passive:false});el.addEventListener("pointermove",e=>{if(st.id!==e.pointerId)return;const mx=e.clientX-st.x,my=e.clientY-st.y,len=Math.max(1,Math.hypot(mx,my)),cap=46;st.dx=Math.max(-1,Math.min(1,mx/cap));st.dy=Math.max(-1,Math.min(1,my/cap));const n=Math.min(cap,len);if(k)k.style.transform=`translate(${mx/len*n}px,${my/len*n}px)`;e.preventDefault()},{passive:false});["pointerup","pointercancel","lostpointercapture"].forEach(x=>el.addEventListener(x,reset));}
function fmt(n){return Number(n||0).toLocaleString()}
function status(t){const e=document.getElementById("svr326Status");if(e)e.textContent=t}
function updateUI(){document.getElementById("svr326Turn").textContent=seated?(myTurn?"YOUR TURN":"SEATED • WAITING"):"LOBBY MODE";document.querySelectorAll(".svr326Actions button").forEach(b=>{const a=b.dataset.act;b.classList.toggle("ready",seated&&(myTurn||a==="deal"||a==="sit")&&a!=="clean")});const rt=document.getElementById("svr326RaiseText");if(rt)rt.textContent=fmt(raiseAmount);window.SVR_PHASE326_ANDROID_PLAY_STATE={build:BUILD,active:true,seated,myTurn,raiseAmount,move:{x:+left.dx.toFixed(2),y:+left.dy.toFixed(2)},look:{x:+right.dx.toFixed(2),y:+right.dy.toFixed(2)},checkedAt:new Date().toISOString()};}
function setCards(a="A♠",b="K♥"){const c=[...document.querySelectorAll("#svr326Cards .svr326Card")];if(c[0]){c[0].textContent=a;c[0].classList.toggle("red",/[♥♦]/.test(a))}if(c[1]){c[1].textContent=b;c[1].classList.toggle("red",/[♥♦]/.test(b))}}
function enhanceLight(){const s=scene();if(!s||s.getObjectByName("PHASE326_ANDROID_LOBBY_LIGHTS"))return;const g=new THREE.Group();g.name="PHASE326_ANDROID_LOBBY_LIGHTS";s.add(g);const hemi=new THREE.HemisphereLight(0xcfefff,0x101018,.92);g.add(hemi);const a=new THREE.DirectionalLight(0xffffff,.82);a.position.set(-4,9,6);g.add(a);[[0,5,2,0xffd98a,1.1],[-8,4,-8,0x7ffcff,.85],[8,4,-8,0xa77cff,.75],[0,4.8,-13,0xffffff,.72]].forEach((v,i)=>{const l=new THREE.PointLight(v[3],v[4],26,2);l.name="PHASE326_ANDROID_POINT_LIGHT_"+i;l.position.set(v[0],v[1],v[2]);g.add(l)});}
function ensureFallbackTable(){const b=base();if(!b||table())return;const g=new THREE.Group();g.name="PHASE326_ANDROID_TABLE_FALLBACK";g.position.set(0,0,.75);const rail=new THREE.Mesh(new THREE.CylinderGeometry(2.35,2.35,.22,80),new THREE.MeshStandardMaterial({color:0x2a1810,roughness:.7,metalness:.05}));rail.scale.z=.64;rail.position.y=.78;g.add(rail);const felt=new THREE.Mesh(new THREE.CylinderGeometry(2.02,2.02,.05,80),new THREE.MeshStandardMaterial({color:0x06351f,roughness:.86}));felt.scale.z=.55;felt.position.y=.93;g.add(felt);b.add(g);}
function rebuildPlayerCards3D(){const b=base(),r=tb();if(!b||!r)return;const old=b.getObjectByName("PHASE326_ANDROID_PLAYER_CARD_FACE_ROOT");if(old)old.parent.remove(old);const root=new THREE.Group();root.name="PHASE326_ANDROID_PLAYER_CARD_FACE_ROOT";b.add(root);const y=r.top+.028,z=r.center.z+Math.max(.72,r.size.z*.32),x=r.center.x;function tex(txt){const c=document.createElement("canvas");c.width=256;c.height=360;const q=c.getContext("2d");q.fillStyle="#f8f0dc";q.fillRect(0,0,256,360);q.strokeStyle="#111";q.lineWidth=10;q.strokeRect(10,10,236,340);q.fillStyle=/[♥♦]/.test(txt)?"#a00018":"#111";q.font="900 70px system-ui";q.textAlign="center";q.textBaseline="middle";q.fillText(txt,128,180);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}[["A♠",-.18],["K♥",.18]].forEach(v=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(.32,.44),new THREE.MeshBasicMaterial({map:tex(v[0]),side:THREE.DoubleSide,depthWrite:false}));m.position.set(x+v[1],y,z);m.rotation.x=-Math.PI/2;m.renderOrder=3260;root.add(m)});}
function sit(){const r=tb();if(!r)return false;seated=true;myTurn=true;const z=r.center.z+Math.max(2.55,r.size.z*.92),x=r.center.x;const c=camera();const rr=rig();try{if(rr?.setPlayerPose)rr.setPlayerPose(x,0,z);else if(c)c.position.set(x,1.55,z);if(c)c.lookAt(r.center.x,1.05,r.center.z);}catch{}setCards();rebuildPlayerCards3D();status("SEATED AT TABLE");updateUI();return true;}
function lobby(){seated=false;myTurn=false;const c=camera();const rr=rig();try{if(rr?.setPlayerPose)rr.setPlayerPose(0,0,6.8);else if(c)c.position.set(0,1.6,6.8);if(c)c.lookAt(0,1.4,.75)}catch{}status("LOBBY MOVEMENT ON");updateUI();}
function center(){seated?sit():lobby()}
function move(){const c=camera();if(!c)return;const turn=right.dx;if(Math.abs(turn)>.05){const rr=rig();if(rr?.rotation)rr.rotation.y+=turn*.035;else c.rotation.y+=turn*.035;}if(seated)return;const f=-left.dy,strafe=-left.dx;if(Math.abs(f)<.04&&Math.abs(strafe)<.04)return;const d=new THREE.Vector3();c.getWorldDirection(d);d.y=0;if(d.lengthSq()<.001)d.set(0,0,-1);d.normalize();const side=new THREE.Vector3().crossVectors(d,new THREE.Vector3(0,1,0)).normalize();const p=new THREE.Vector3();c.getWorldPosition(p);const speed=.078,nx=p.x+(d.x*f+side.x*strafe)*speed,nz=p.z+(d.z*f+side.z*strafe)*speed;const rr=rig();try{if(rr?.setPlayerPose)rr.setPlayerPose(nx,Math.max(0,Math.round((p.y-1.55)/3.15)*3.15),nz);else c.position.set(nx,c.position.y,nz)}catch{c.position.set(nx,c.position.y,nz)}}
function action(a){if(a==="sit")return seated?lobby():sit();if(a==="clean"){purge();return status("CONTROL CLEANUP DONE")}if(a==="deal"){if(!seated)sit();myTurn=true;setCards("A♠","K♥");rebuildPlayerCards3D();try{window.SVR_PRESS_DEAL?.()||window.SVR_PLAY_LEFT_TO_RIGHT_DEAL?.()}catch{}status("CARDS DEALT • YOUR TURN");return updateUI()}if(a==="check"||a==="call"||a==="raise"){if(!seated)sit();window.SVR_ANDROID_RAISE_AMOUNT=raiseAmount;try{window.SVR_SELECT_ACTION?.(a==="check"?"Check":a==="call"?"Call":"Raise")}catch(e){window.SVR_PHASE326_LAST_ERROR=String(e?.message||e)}myTurn=false;status(a==="raise"?`RAISE ${fmt(raiseAmount)} SENT`:`${a.toUpperCase()} SENT`);return updateUI();}}
function bindButtons(){document.querySelectorAll("#svr326Root button[data-act]").forEach(b=>{if(b.__svr326)return;b.__svr326=true;b.addEventListener("pointerdown",e=>{e.preventDefault();action(b.dataset.act)},{passive:false})});const sl=document.getElementById("svr326RaiseSlider");if(sl&&!sl.__svr326){sl.__svr326=true;sl.addEventListener("input",()=>{raiseAmount=+sl.value;updateUI()})}document.querySelectorAll("#svr326Root button[data-small]").forEach(b=>{if(b.__svr326)return;b.__svr326=true;b.addEventListener("pointerdown",e=>{e.preventDefault();if(b.dataset.small==="up")raiseAmount=Math.min(10000,raiseAmount+500);if(b.dataset.small==="down")raiseAmount=Math.max(500,raiseAmount-500);if(b.dataset.small==="center")center();const s=document.getElementById("svr326RaiseSlider");if(s)s.value=raiseAmount;updateUI()},{passive:false})})}
function loop(){purge();move();enhanceLight();ensureFallbackTable();if(window.SVR_ANDROID_ALIGN_CARDS)try{window.SVR_ANDROID_ALIGN_CARDS()}catch{}updateUI();raf=requestAnimationFrame(loop)}
function install(){if(!active||installed)return;installed=true;css();document.body.classList.add("svr-phase326-android","svr-android-game-controls","boot-released","runtime-visible","overlay-released");document.getElementById("safeStage")?.remove();makeUI();bindStick(document.getElementById("svr326Move"),left);bindStick(document.getElementById("svr326Look"),right);bindButtons();enhanceLight();ensureFallbackTable();setCards("--","--");window.SVR_ANDROID_SIT_TO_TABLE=sit;window.SVR_ANDROID_LOBBY_MODE=lobby;window.SVR_ANDROID_CENTER_PLAYER=center;window.SVR_ANDROID_ACTION=action;window.SVR_PHASE326={build:BUILD,active:true,siteTouched:false,helpers:["SVR_ANDROID_SIT_TO_TABLE","SVR_ANDROID_ACTION","SVR_ANDROID_CENTER_PLAYER"]};status("ANDROID PLAY MODE READY");if(!raf)loop();}
setTimeout(install,160);setTimeout(install,900);setTimeout(install,2200);