import * as THREE from "three";
const BUILD="PHASE-251-PORTAL-FINAL-ROUTING-LOCK";
const COLORS={wellness:0xa77cff,pga:0x7ffcff,play:0xffd98a,store:0x8dffb4,scorpion:0xff5b8c};
const ROUTES={wellness:{label:"Wellness",target:"Private Reiki Room",scene:"reikiRoom"},pga:{label:"PGA",target:"Private Golf Range",scene:"pga"},play:{label:"Play",target:"Poker Table",scene:"seat"},store:{label:"Store",target:"SVR Web Store",url:"https://svrpoker.com/site/store.html"},scorpion:{label:"Scorpion",target:"Private Poker Room",scene:"scorpion"}};
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function glow(c,o=.45){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending})}
function tex(a,b,c){const cn=document.createElement("canvas");cn.width=900;cn.height=360;const g=cn.getContext("2d");g.fillStyle="#030711";g.fillRect(0,0,900,360);g.strokeStyle=c;g.lineWidth=10;g.strokeRect(20,20,860,320);g.textAlign="center";g.textBaseline="middle";g.fillStyle="#fff";g.font="900 52px system-ui,Arial";g.fillText(a.toUpperCase(),450,126);g.fillStyle=c;g.font="800 30px system-ui,Arial";g.fillText(b,450,232);const t=new THREE.CanvasTexture(cn);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
function sign(root,name,a,b,x,z,color){const p=new THREE.Mesh(new THREE.PlaneGeometry(2.45,.82),new THREE.MeshBasicMaterial({map:tex(a,b,"#"+color.toString(16).padStart(6,"0")),transparent:true,side:THREE.DoubleSide,depthWrite:false}));p.name=name;p.position.set(x,1.55,z);p.renderOrder=700;root.add(p);return p}
function pad(root,name,x,z,color){const r=new THREE.Mesh(new THREE.RingGeometry(.92,1.12,96),glow(color,.58));r.name=name;r.rotation.x=-Math.PI/2;r.position.set(x,.24,z);root.add(r);const beam=new THREE.Mesh(new THREE.CylinderGeometry(.54,.54,.05,64),glow(color,.18));beam.name=name+"_CORE";beam.position.set(x,.255,z);root.add(beam)}
function attachButtons(scene){window.SVR_PORTAL_ROUTES=ROUTES;window.SVR_OPEN_PORTAL=(key)=>{const r=ROUTES[key];if(!r)return false;if(r.url){window.open(r.url,"_blank","noopener");return true}window.dispatchEvent(new CustomEvent("svr:navigate",{detail:{scene:r.scene,source:"phase251",route:key}}));return true};return true}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE251_PORTAL_FINAL_ROUTING_ROOT"))return;const root=new THREE.Group();root.name="PHASE251_PORTAL_FINAL_ROUTING_ROOT";scene.add(root);const data=[[-12.8,-7.9,"wellness"],[-6.4,-7.9,"pga"],[0,-2.7,"play"],[6.4,-7.9,"store"],[12.8,-7.9,"scorpion"]];data.forEach(([x,z,k])=>{pad(root,"PHASE251_PORTAL_PAD_"+k.toUpperCase(),x,z,COLORS[k]);sign(root,"PHASE251_ROUTE_SIGN_"+k.toUpperCase(),ROUTES[k].label,ROUTES[k].target,x,z-.82,COLORS[k])});attachButtons(scene);window.SVR_PHASE251_PORTAL_FINAL_ROUTING={build:BUILD,active:true,siteTouched:false,routes:ROUTES,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 251 ACTIVE • PORTAL ROUTING LOCK";const s=document.getElementById("status");if(s)s.textContent="Phase 251 portal routing lock active"}
install();
