import * as THREE from "three";
const BUILD="PHASE-281-VISIBLE-HANDS-SKY-CLEANUP-LOCK";
function scene(){return window.__SVR_SCENE__||null}
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(scene())return r(scene());if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function simpleMat(color,op=.88){return new THREE.MeshBasicMaterial({color,transparent:true,opacity:op,depthWrite:false})}
function makeHand(side){const root=new THREE.Group();root.name="PHASE281_VISIBLE_"+side.toUpperCase()+"_HAND";const palm=new THREE.Mesh(new THREE.SphereGeometry(.055,14,10),simpleMat(0xbda08b,.86));palm.scale.set(1.08,.72,1.35);root.add(palm);const sx=side==="left"?-1:1;for(let i=0;i<5;i++){const f=new THREE.Mesh(new THREE.CapsuleGeometry(.012,.09,5,8),simpleMat(0xd2b29a,.9));f.position.set((i-2)*.024*sx,-.006,-.07-Math.abs(i-2)*.004);f.rotation.x=Math.PI*.5;root.add(f)}const ring=new THREE.Mesh(new THREE.TorusGeometry(.074,.004,16,48),simpleMat(0x7ffcff,.65));ring.name="PHASE281_GRAB_RING";ring.rotation.x=Math.PI*.5;ring.visible=false;root.add(ring);return root}
function bindHands(){const sc=scene();if(!sc)return null;let left=sc.getObjectByName("PHASE281_VISIBLE_LEFT_HAND");let right=sc.getObjectByName("PHASE281_VISIBLE_RIGHT_HAND");if(!left){left=makeHand("left");sc.add(left)}if(!right){right=makeHand("right");sc.add(right)}function place(){const renderer=window.__SVR_RENDERER__;const cam=window.__SVR_CAMERA__||window.camera||null;const xr=renderer?.xr;if(xr){for(let i=0;i<2;i++){const c=xr.getController(i);if(!c)continue;c.updateWorldMatrix(true,false);const h=i===0?left:right;c.getWorldPosition(h.position);c.getWorldQuaternion(h.quaternion);h.visible=true;const gp=c.inputSource?.gamepad;const press=Math.max(gp?.buttons?.[0]?.value||0,gp?.buttons?.[1]?.value||0);h.scale.setScalar(press>.15?.88:1);const ring=h.getObjectByName("PHASE281_GRAB_RING");if(ring)ring.visible=press>.15;}}else if(cam){const v=new THREE.Vector3();cam.getWorldPosition(v);left.position.set(v.x-.18,v.y-.18,v.z-.55);right.position.set(v.x+.18,v.y-.18,v.z-.55);left.visible=right.visible=true;}}window.SVR_UPDATE_VISIBLE_HANDS=place;setInterval(place,60);place();return {left,right}}
function sphereTexture(kind){const c=document.createElement("canvas");c.width=c.height=512;const g=c.getContext("2d");g.fillStyle=kind==="mars"?"#5e2718":"#777";g.fillRect(0,0,512,512);for(let i=0;i<150;i++){const x=Math.random()*512,y=Math.random()*512,r=kind==="mars"?Math.random()*12+3:Math.random()*18+4;g.beginPath();g.fillStyle=kind==="mars"?"rgba(170,70,35,.55)":"rgba(170,170,170,.55)";g.arc(x,y,r,0,Math.PI*2);g.fill()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function installSky(){const sc=scene();if(!sc||sc.getObjectByName("PHASE281_ORBIT_SKY_ROOT"))return null;const root=new THREE.Group();root.name="PHASE281_ORBIT_SKY_ROOT";root.position.set(0,6.8,-1.2);sc.add(root);const moonPivot=new THREE.Group();const marsPivot=new THREE.Group();root.add(moonPivot,marsPivot);const moon=new THREE.Mesh(new THREE.SphereGeometry(.42,48,24),new THREE.MeshStandardMaterial({map:sphereTexture("moon"),roughness:.95,metalness:0}));moon.name="PHASE281_CLOSE_DETAILED_MOON";moon.position.set(-4.2,1.1,-4.4);moonPivot.add(moon);const mars=new THREE.Mesh(new THREE.SphereGeometry(.5,48,24),new THREE.MeshStandardMaterial({map:sphereTexture("mars"),roughness:.9,metalness:0}));mars.name="PHASE281_CLOSE_DETAILED_MARS";mars.position.set(4.8,1.4,-5.2);marsPivot.add(mars);const light=new THREE.PointLight(0xffffff,.75,18);light.position.set(0,2,-2);root.add(light);function tick(){moonPivot.rotation.y+=.0016;marsPivot.rotation.y-=.0011;moon.rotation.y+=.004;mars.rotation.y+=.003}window.SVR_UPDATE_ORBIT_SKY=tick;setInterval(tick,33);return root}
function removeFaceBox(){const sc=scene();const removed=[];for(const el of Array.from(document.querySelectorAll("body > div"))){const css=getComputedStyle(el);const dark=(css.backgroundColor||"").includes("0, 0, 0")||/rgba\(0, 0, 0/.test(css.backgroundColor||"");if(css.position==="fixed"&&dark&&el.id!=="bootFallback"){removed.push(el.id||"fixed-dark");el.remove()}}if(sc)sc.traverse(o=>{if(/DARK|BLACK|OVERLAY|SCREEN|FACE|PANEL/.test(o.name||"")&&/PHASE27|OVERLAY|SCREEN|FACE/.test(o.name||"")){o.visible=false;removed.push(o.name)}});window.SVR_FACE_BOX_CLEANUP_STATE={build:BUILD,removed,updatedAt:new Date().toISOString()};return window.SVR_FACE_BOX_CLEANUP_STATE}
async function install(){await waitScene();bindHands();installSky();removeFaceBox();setInterval(removeFaceBox,5000);window.SVR_PHASE281={build:BUILD,active:true,siteTouched:false,helpers:["SVR_UPDATE_VISIBLE_HANDS","SVR_UPDATE_ORBIT_SKY","SVR_CLEAN_FACE_BOX"]};window.SVR_CLEAN_FACE_BOX=removeFaceBox;window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 281 ACTIVE HANDS SKY CLEANUP";const s=document.getElementById("status");if(s)s.textContent="Phase 281 visible hands, orbit sky, cleanup active"}
install();
