import * as THREE from "three";

const LABEL = "PHASE-258-ROMAN-CANOPY-SMOOTH-LOBBY-LOCK";
const ROOT = "PHASE258_ROMAN_CANOPY_SMOOTH_ROOT";
const OLD_ROOT = "PHASE257_ROMAN_CANOPY_ROOT";
const GOLD = 0xffd98a;
const CYAN = 0x7ffcff;
const PURPLE = 0xb55cff;
const STONE = 0xd8d0bc;
const DARK = 0x070914;

function m(c,a=1,metal=.06,rough=.5){return new THREE.MeshStandardMaterial({color:c,transparent:a<1,opacity:a,metalness:metal,roughness:rough,side:THREE.DoubleSide});}
function g(c,a=.4){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:a,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending});}
function cyl(root,n,r,h,x,y,z,mat,seg=40){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),mat);o.name=n;o.position.set(x,y,z);root.add(o);return o;}
function box(root,n,sx,sy,sz,x,y,z,mat){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat);o.name=n;o.position.set(x,y,z);root.add(o);return o;}
function arch(root,n,rad,tube,x,y,z,mat,ry=0,sx=1,sy=1){const o=new THREE.Mesh(new THREE.TorusGeometry(rad,tube,14,72,Math.PI),mat);o.name=n;o.position.set(x,y,z);o.rotation.y=ry;o.scale.set(sx,sy,1);root.add(o);return o;}
function flutedColumn(root,name,x,z,h=3.35,r=.16){const stone=m(STONE,.96,.02,.42);const gold=m(GOLD,.94,.24,.36);cyl(root,`${name}_CORE`,r,h,x,h/2,z,stone,48);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const fx=x+Math.cos(a)*(r+.026);const fz=z+Math.sin(a)*(r+.026);const flute=cyl(root,`${name}_FLUTE_${i}`,.014,h*.92,fx,h/2,fz,m(0xf1ead8,.78,.02,.5),12);flute.rotation.z=0;}cyl(root,`${name}_BASE_WIDE`,r*1.95,.12,x,.11,z,gold,48);cyl(root,`${name}_BASE_STONE`,r*1.45,.14,x,.24,z,stone,48);cyl(root,`${name}_CAP_STONE`,r*1.35,.16,x,h+.02,z,stone,48);cyl(root,`${name}_CAP_GOLD`,r*1.95,.12,x,h+.18,z,gold,48);}
function canvasSign(text,sub){const c=document.createElement("canvas");c.width=1024;c.height=256;const ctx=c.getContext("2d");ctx.fillStyle="rgba(4,6,16,.88)";ctx.fillRect(0,0,1024,256);ctx.strokeStyle="#ffd98a";ctx.lineWidth=8;ctx.strokeRect(12,12,1000,232);ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="#ffd98a";ctx.font="900 46px system-ui,Arial";ctx.fillText(text,512,94);ctx.fillStyle="#7ffcff";ctx.font="800 24px system-ui,Arial";ctx.fillText(sub,512,158);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function addSign(root){const p=new THREE.Mesh(new THREE.PlaneGeometry(4.6,1.15),new THREE.MeshBasicMaterial({map:canvasSign("ROMAN CANOPY LOCK","central chuppah-style arches • smooth pillar rhythm"),transparent:true,side:THREE.DoubleSide,depthWrite:false}));p.name="PHASE258_CANOPY_SIGN";p.position.set(0,4.35,1.15);p.rotation.y=Math.PI;root.add(p);}
function stamp(){window.SVR_PHASE258={build:LABEL,active:true,romanCanopy:true,chuppahStyle:true,smoothCornerPillars:true,lobbyArchRhythm:true,siteTouched:false,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=LABEL;try{document.title=`SVR Poker • ${LABEL}`}catch{};const label=document.getElementById("svr-phase-label");if(label)label.textContent="PHASE 258 ACTIVE • SMOOTH ROMAN CANOPY";const status=document.getElementById("status");if(status)status.textContent="Phase 258 smooth Roman canopy and lobby pillar rhythm loaded";}
function removeOld(scene){const old=scene.getObjectByName(OLD_ROOT);if(old){old.visible=false;old.parent?.remove(old);}const existing=scene.getObjectByName(ROOT);if(existing)existing.parent?.remove(existing);}
function build(scene){removeOld(scene);const root=new THREE.Group();root.name=ROOT;scene.add(root);const gold=m(GOLD,.96,.26,.34),stone=m(STONE,.96,.02,.40),dark=m(DARK,.78,.02,.66),cyan=g(CYAN,.38),purple=g(PURPLE,.24);const bx=3.25,bz=2.35,cz=-1.35,top=3.62;[[-bx,-bz],[bx,-bz],[-bx,bz],[bx,bz]].forEach(([x,z],i)=>flutedColumn(root,`PHASE258_CENTER_PILLAR_${i}`,x,cz+z,3.45,.17));box(root,"PHASE258_CANOPY_FRONT_GOLD_BEAM",6.95,.14,.18,0,top,cz+bz,gold);box(root,"PHASE258_CANOPY_BACK_GOLD_BEAM",6.95,.14,.18,0,top,cz-bz,gold);box(root,"PHASE258_CANOPY_LEFT_GOLD_BEAM",.18,.14,5.05,-bx,top,cz,gold);box(root,"PHASE258_CANOPY_RIGHT_GOLD_BEAM",.18,.14,5.05,bx,top,cz,gold);box(root,"PHASE258_CANOPY_SOFT_DARK_TOP",6.45,.04,4.45,0,3.84,cz,dark);box(root,"PHASE258_CANOPY_CYAN_UNDERLIGHT",6.15,.02,4.10,0,3.50,cz,cyan);box(root,"PHASE258_CANOPY_PURPLE_CENTER_DRAPE",1.65,.025,4.25,0,3.89,cz,purple);arch(root,"PHASE258_FRONT_ROMAN_CANOPY_ARCH",3.2,.042,0,3.25,cz+bz+.08,gold,0,1,1.06);arch(root,"PHASE258_BACK_ROMAN_CANOPY_ARCH",3.2,.042,0,3.25,cz-bz-.08,gold,Math.PI,1,1.06);arch(root,"PHASE258_LEFT_ROMAN_CANOPY_ARCH",2.35,.04,-bx-.08,3.22,cz,gold,Math.PI/2,1.36,1.02);arch(root,"PHASE258_RIGHT_ROMAN_CANOPY_ARCH",2.35,.04,bx+.08,3.22,cz,gold,-Math.PI/2,1.36,1.02);
[[-12.8,-9.8],[12.8,-9.8],[-12.8,6.4],[12.8,6.4]].forEach(([x,z],i)=>flutedColumn(root,`PHASE258_CORNER_PILLAR_${i}`,x,z,3.65,.22));
for(let i=0;i<9;i++){const x=-12+i*3;flutedColumn(root,`PHASE258_REAR_LOBBY_PILLAR_${i}`,x,-11.55,2.85,.105);box(root,`PHASE258_REAR_GOLD_RAIL_${i}`,2.28,.075,.07,x,2.97,-11.48,gold);arch(root,`PHASE258_REAR_REPEAT_ARCH_${i}`,1.08,.025,x,2.88,-11.40,gold,0,1.02,1.03);}[-1,1].forEach(side=>{for(let i=0;i<5;i++){const z=-8.8+i*3.35;flutedColumn(root,`PHASE258_SIDE_${side}_PILLAR_${i}`,side*13.35,z,2.65,.10);box(root,`PHASE258_SIDE_${side}_CYAN_TRIM_${i}`,.055,.045,2.35,side*13.18,2.93,z,cyan);}});addSign(root);window.SVR_PHASE258_GEOMETRY={build:LABEL,centerCanopy:"chuppah-style",cornerPillars:4,rearArches:9,sidePillars:10,checkedAt:new Date().toISOString()};}
function install(){stamp();const scene=window.__SVR_SCENE__;if(!scene)return false;build(scene);return true;}
stamp();let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>220)clearInterval(timer)},180);[1200,2600,5200,9000].forEach(t=>setTimeout(install,t));
