import * as THREE from "three";
const BUILD="PHASE-257-FIRST-HAND-VISUAL-PREP-LOCK";
function waitScene(){return new Promise(r=>{let n=0;const t=()=>{if(window.__SVR_SCENE__)return r(window.__SVR_SCENE__);if(++n>360)return r(null);requestAnimationFrame(t)};t()})}
function mat(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.35})}
function glow(c,o=.45){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending})}
function card(root,n,x,z,label){const back=new THREE.Mesh(new THREE.PlaneGeometry(.42,.62),mat(0xffffff,.92));back.name=n;back.rotation.x=-Math.PI/2;back.position.set(x,.43,z);root.add(back);const line=new THREE.Mesh(new THREE.PlaneGeometry(.34,.03),glow(0x7ffcff,.55));line.name=n+"_MARK";line.rotation.x=-Math.PI/2;line.position.set(x,.435,z);root.add(line);return back}
function chip(root,n,x,z,c){const m=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.08,32),mat(c,.9));m.name=n;m.position.set(x,.43,z);root.add(m);return m}
async function install(){const scene=await waitScene();if(!scene||scene.getObjectByName("PHASE257_FIRST_HAND_VISUAL_PREP_ROOT"))return;const root=new THREE.Group();root.name="PHASE257_FIRST_HAND_VISUAL_PREP_ROOT";scene.add(root);[-.96,-.48,0,.48,.96].forEach((x,i)=>card(root,"PHASE257_COMMUNITY_CARD_SLOT_"+(i+1),x,.02,i));[-.32,.32].forEach((x,i)=>card(root,"PHASE257_PLAYER_CARD_SLOT_"+(i+1),x,2.72,i));chip(root,"PHASE257_DEALER_BUTTON_MARKER",2.05,1.72,0xffd98a);chip(root,"PHASE257_SMALL_BLIND_MARKER",-2.15,1.72,0x7ffcff);chip(root,"PHASE257_BIG_BLIND_MARKER",-2.45,.25,0xff5b8c);const ready=new THREE.Mesh(new THREE.RingGeometry(1.82,1.92,120),glow(0x8dffb4,.38));ready.name="PHASE257_READY_TO_DEAL_TABLE_RING";ready.rotation.x=-Math.PI/2;ready.position.set(0,.46,.25);root.add(ready);window.SVR_FIRST_HAND_VISUAL_STATE={build:BUILD,active:true,communitySlots:5,playerSlots:2,dealerButton:"bot-right-front-dealer",smallBlind:"bot-left-front",bigBlind:"bot-left-mid",dealDirection:window.SVR_DEAL_ORDER_LOCK?.direction||"left-to-right",status:"ready-to-deal",checkedAt:new Date().toISOString()};window.SVR_READY_TO_DEAL=()=>{window.SVR_FIRST_HAND_VISUAL_STATE.status="ready-to-deal-confirmed";window.dispatchEvent(new CustomEvent("svr:ready-to-deal",{detail:window.SVR_FIRST_HAND_VISUAL_STATE}));const s=document.getElementById("status");if(s)s.textContent="Ready to Deal: left-to-right locked";return true};window.SVR_LOCKED_FINAL_BUILD=BUILD;const l=document.getElementById("svr-phase-label");if(l)l.textContent="PHASE 257 ACTIVE • FIRST HAND VISUAL PREP";const s=document.getElementById("status");if(s)s.textContent="Phase 257 first hand visual prep active"}
install();
