import * as THREE from 'three';
const BUILD='PHASE-339-ANDROID-SINGLE-AUTHORITY-TABLE-CAMERA3-LOCK';
const isAndroid=/Android/i.test(navigator.userAgent||'')&&!/Quest|Oculus|Meta Quest/i.test(navigator.userAgent||'')||/\/game\/android\.html$/i.test(location.pathname);
const LEGACY=['#svrAndroidGamePad','#svrTapMovePanel','#svrAndroidSafeBadge153','#svrAndroidLiteHud','#svrAndroidRecoverView','#svr329Info','#svr329QA','#svr329Toast','#svr327ReleaseBadge'];
let observer,logoRoot,lastTableId='';
const scene=()=>window.__SVR_SCENE__||null;
const root=()=>scene()?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene();
function tableCandidates(){const r=root();if(!r)return[];const names=['PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED','PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT','PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED','PHASE326_ANDROID_TABLE_FALLBACK'];return names.map(n=>r.getObjectByName?.(n)).filter(Boolean)}
function isAncestor(a,b){let p=b.parent;while(p){if(p===a)return true;p=p.parent}return false}
function authority(){const c=tableCandidates();if(!c.length)return null;const top=c.filter(x=>!c.some(y=>y!==x&&x.parent&&isAncestor(y,x)));const a=top[0]||c[0];(top.length?top:c).forEach(x=>{x.visible=x===a;x.userData={...x.userData,svr339Authority:x===a,svr339Suppressed:x!==a}});return a}
function purgeControls(){LEGACY.forEach(s=>document.querySelectorAll(s).forEach(e=>e.remove()));const roots=[...document.querySelectorAll('#svr326Root')];roots.slice(1).forEach(e=>e.remove());document.querySelectorAll('.svr-stick').forEach(e=>{if(e.id!=='svr326Move'&&e.id!=='svr326Look')e.remove()});const one=document.querySelector('#svr326Root');if(one){one.style.zIndex='2147483000';one.style.pointerEvents='none';one.querySelectorAll('button,input,#svr326Move,#svr326Look').forEach(e=>e.style.pointerEvents='auto')}}
function logoTexture(){const c=document.createElement('canvas');c.width=1024;c.height=512;const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.fillStyle='rgba(0,0,0,.02)';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#d9b45c';g.lineWidth=16;g.strokeRect(24,24,c.width-48,c.height-48);g.fillStyle='#fff';g.textAlign='center';g.textBaseline='middle';g.font='900 150px system-ui';g.fillText('SVR',512,210);g.fillStyle='#d9b45c';g.font='900 64px system-ui';g.fillText('POKER',512,340);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function tableInfo(){const t=authority();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{t,b,s,c,top:b.max.y}}
function installLogo(){const r=root(),i=tableInfo();if(!r||!i)return false;if(logoRoot&&logoRoot.parent)logoRoot.parent.remove(logoRoot);logoRoot=new THREE.Group();logoRoot.name='PHASE339_ANDROID_TABLE_LOGO_ROOT';const w=Math.max(.55,Math.min(1.25,i.s.x*.22)),h=w*.5;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:logoTexture(),transparent:true,depthWrite:false,side:THREE.DoubleSide,toneMapped:false}));m.name='PHASE339_ANDROID_TABLE_LOGO';m.position.set(i.c.x,i.top+.012,i.c.z);m.rotation.x=-Math.PI/2;m.renderOrder=9339;logoRoot.add(m);r.add(logoRoot);lastTableId=i.t.uuid;return true}
function normalizeTable(){const i=tableInfo();if(!i)return false;i.t.visible=true;i.t.traverse?.(o=>{if(o.isMesh){o.frustumCulled=true;o.castShadow=false;o.receiveShadow=false}});if(i.t.uuid!==lastTableId)installLogo();return true}
function suppressUpdatePrompts(){window.SVR_ANDROID_APK_RELEASE_POLICY={...(window.SVR_ANDROID_APK_RELEASE_POLICY||{}),apkVersionName:'0.1.0-rc1',apkVersionCode:1,forceUpdate:false,showUpdatePrompt:false,manualUpdateOnly:true,build:BUILD};window.SVR_APK_UPDATE_POLICY=window.SVR_ANDROID_APK_RELEASE_POLICY;try{localStorage.setItem('SVR_ANDROID_MANUAL_UPDATE_ONLY_V1','1')}catch{}document.querySelectorAll('[id*="update" i],[class*="update" i]').forEach(e=>{const text=(e.textContent||'').toLowerCase();if(/update app|new version|apk update|update available/.test(text))e.remove()})}
function installStyle(){if(document.getElementById('svr339-style'))return;const s=document.createElement('style');s.id='svr339-style';s.textContent=`body.svr339-android #svr326Root{display:block!important}body.svr339-android #svr326Move,body.svr339-android #svr326Look{width:112px!important;height:112px!important;bottom:max(18px,env(safe-area-inset-bottom))!important;background:rgba(0,5,14,.52)!important;border:1px solid rgba(127,252,255,.75)!important}body.svr339-android #svr326Move{left:14px!important}body.svr339-android #svr326Look{right:14px!important}body.svr339-android .svr326Actions{right:14px!important;bottom:148px!important;grid-template-columns:repeat(2,78px)!important;gap:7px!important}body.svr339-android #svr326Cards{right:14px!important;left:auto!important;bottom:318px!important;transform:none!important;background:rgba(0,0,0,.72)!important}body.svr339-android #svr326Raise{bottom:82px!important;width:min(56vw,300px)!important}body.svr339-android #svr326Status{bottom:142px!important;max-width:45vw!important}`;document.head.appendChild(s)}
function qa(){const controls={roots:document.querySelectorAll('#svr326Root').length,move:document.querySelectorAll('#svr326Move').length,look:document.querySelectorAll('#svr326Look').length};const tables=tableCandidates().filter(x=>x.visible).length;const result={build:BUILD,active:isAndroid,controls,tables,oneControlSet:controls.roots===1&&controls.move===1&&controls.look===1,oneTable:tables<=1,logo:!!root()?.getObjectByName?.('PHASE339_ANDROID_TABLE_LOGO'),manualUpdateOnly:true,checkedAt:new Date().toISOString()};result.pass=result.oneControlSet&&result.oneTable&&result.logo;window.SVR_PHASE339_ANDROID_QA_STATE=result;return result}
function enforce(){if(!isAndroid)return;purgeControls();suppressUpdatePrompts();normalizeTable()}
function boot(){if(!isAndroid)return;document.body.classList.add('svr339-android');installStyle();enforce();observer=new MutationObserver(()=>enforce());observer.observe(document.documentElement,{subtree:true,childList:true});[200,600,1200,2400,5000].forEach(ms=>setTimeout(enforce,ms));setInterval(enforce,1200);window.SVR_PHASE339_ANDROID_QA=qa;window.SVR_PHASE339_REBUILD_TABLE=()=>{lastTableId='';return normalizeTable()};window.SVR_PHASE339_MANUAL_APP_UPDATE=()=>{try{localStorage.removeItem('SVR_ANDROID_MANUAL_UPDATE_ONLY_V1')}catch{}location.reload()};window.SVR_PHASE339_STATE={build:BUILD,active:true,manualUpdateOnly:true,startedAt:new Date().toISOString()}}
boot();
