const PHASE384_PREDECESSOR='phase384-eric-quest-android-polish';
const PHASE385_ANDROID_PREDECESSOR='phase385-android-original-tabletop-gyro';
const PHASE386_QUEST_PREDECESSOR='phase386-quest-table-environment';
const PHASE387_QUEST_PREDECESSOR='phase387-quest-direct-seat-recovery';
const SVR_PWA_CACHE='svr-poker-pwa-phase388-quest-table-player-eric-v2';
const CORE=['/offline.html','/logo.png','/manifest.webmanifest?v=phase388','/site-public-hooks.js?v=phase388','/site/phase383-home-restore.css?v=phase383','/site/js/phase388-eric-upright-material-lock.js?v=phase388','/game/quest.html?v=phase388','/game/index.html?platform=quest&v=phase388&direct=1&autoseat=1&questfix=1&clean=1','/game/modules/phase388_front_south_seat_authority.js?v=phase388','/game/modules/phase388_quest_table_player_eric_authority.js?v=phase388','/game/modules/phase388_quest_view_dealer_guard.js?v=phase388','/game/android-tabletop.html?v=phase385','/game/styles/phase385_android_tabletop.css?v=phase385','/game/modules/phase385_android_tabletop_3d.js?v=phase385'];
self.addEventListener('install',event=>event.waitUntil(caches.open(SVR_PWA_CACHE).then(cache=>cache.addAll(CORE.map(url=>new Request(url,{cache:'reload'}))).catch(()=>undefined)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==SVR_PWA_CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event?.data?.type==='SKIP_WAITING'||event?.data?.type==='PHASE384_CLEAR'||event?.data?.type==='PHASE385_CLEAR'||event?.data?.type==='PHASE386_CLEAR'||event?.data?.type==='PHASE387_CLEAR'||event?.data?.type==='PHASE388_CLEAR'){event.waitUntil(caches.keys().then(keys=>Promise.all(keys.map(key=>caches.delete(key)))).then(()=>self.skipWaiting()));}});
const freshPath=url=>url.pathname==='/'||url.pathname==='/index.html'||url.pathname.startsWith('/site/')||url.pathname==='/downloads/'||url.pathname==='/downloads/index.html'||url.pathname==='/game/android.html'||url.pathname==='/game/android-play.html'||url.pathname==='/game/android-stable.html'||url.pathname==='/game/android-tabletop.html'||url.pathname==='/game/quest.html'||url.pathname==='/game/index.html'||url.pathname.startsWith('/game/modules/phase384_')||url.pathname.startsWith('/game/modules/phase385_')||url.pathname.startsWith('/game/modules/phase386_')||url.pathname.startsWith('/game/modules/phase387_')||url.pathname.startsWith('/game/modules/phase388_')||url.pathname.startsWith('/game/styles/phase385_')||url.pathname==='/game/android-release.json'||url.pathname==='/manifest.webmanifest'||url.pathname==='/site-public-hooks.js'||url.pathname==='/update/app-version.json'||url.pathname.endsWith('/deploy-health.json');
async function networkOnly(request){return fetch(new Request(request,{cache:'no-store',headers:request.headers}));}
async function networkFirst(request){const cache=await caches.open(SVR_PWA_CACHE);try{const response=await fetch(new Request(request,{cache:'no-store'}));if(response?.ok)cache.put(request,response.clone()).catch(()=>undefined);return response;}catch(error){const cached=await cache.match(request,{ignoreSearch:true})||await caches.match('/offline.html');if(cached)return cached;throw error;}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response?.ok)caches.open(SVR_PWA_CACHE).then(cache=>cache.put(request,response.clone())).catch(()=>undefined);return response;}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(freshPath(url)||url.pathname.endsWith('.apk')){event.respondWith(networkOnly(request));return;}if(request.mode==='navigate'||url.pathname.startsWith('/game/')||url.pathname.startsWith('/site/')||url.pathname.startsWith('/downloads/')||url.pathname.startsWith('/update/')){event.respondWith(networkFirst(request));return;}if(/\.(png|webp|svg|ico|css)$/i.test(url.pathname)){event.respondWith(cacheFirst(request));return;}event.respondWith(networkFirst(request));});
