const SVR_PWA_CACHE='svr-poker-pwa-phase380-clean-routes-v1';
const CORE=['/offline.html','/logo.png','/manifest.webmanifest?v=phase380'];
self.addEventListener('install',event=>event.waitUntil(caches.open(SVR_PWA_CACHE).then(cache=>cache.addAll(CORE.map(url=>new Request(url,{cache:'reload'}))).catch(()=>undefined)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==SVR_PWA_CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event?.data?.type==='SKIP_WAITING')self.skipWaiting();});
const freshPath=url=>url.pathname==='/'||url.pathname==='/index.html'||url.pathname==='/site/index.html'||url.pathname==='/downloads/'||url.pathname==='/downloads/index.html'||url.pathname==='/game/android.html'||url.pathname==='/game/android-play.html'||url.pathname==='/game/android-stable.html'||url.pathname==='/game/index.html'||url.pathname==='/game/android-release.json'||url.pathname==='/update/app-version.json'||url.pathname.endsWith('/deploy-health.json');
async function networkOnly(request){return fetch(new Request(request,{cache:'no-store',headers:request.headers}));}
async function networkFirst(request){const cache=await caches.open(SVR_PWA_CACHE);try{const response=await fetch(new Request(request,{cache:'no-store'}));if(response?.ok)cache.put(request,response.clone()).catch(()=>undefined);return response;}catch(error){const cached=await cache.match(request,{ignoreSearch:true})||await caches.match('/offline.html');if(cached)return cached;throw error;}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response?.ok)caches.open(SVR_PWA_CACHE).then(cache=>cache.put(request,response.clone())).catch(()=>undefined);return response;}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(freshPath(url)||url.pathname.endsWith('.apk')){event.respondWith(networkOnly(request));return;}if(request.mode==='navigate'||url.pathname.startsWith('/game/')||url.pathname.startsWith('/downloads/')||url.pathname.startsWith('/update/')){event.respondWith(networkFirst(request));return;}if(/\.(png|webp|svg|ico|css)$/i.test(url.pathname)){event.respondWith(cacheFirst(request));return;}event.respondWith(networkFirst(request));});
