const PHASE384_PREDECESSOR='phase384-eric-quest-android-polish';
const SVR_CACHE='svr-poker-phase385-android-original-tabletop-gyro-v1';
const CORE=['/offline.html','/logo.png','/site-public-hooks.js?v=phase384','/site/phase383-home-restore.css?v=phase383','/site/js/phase384-avatar-site-lock.js?v=phase384','/game/modules/phase384_quest_quickplay_polish.js?v=phase384','/game/android-tabletop.html?v=phase385','/game/styles/phase385_android_tabletop.css?v=phase385','/game/modules/phase385_android_tabletop_3d.js?v=phase385'];
self.addEventListener('install',event=>event.waitUntil(caches.open(SVR_CACHE).then(cache=>cache.addAll(CORE.map(url=>new Request(url,{cache:'reload'}))).catch(()=>undefined)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==SVR_CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event?.data?.type==='SKIP_WAITING'||event?.data?.type==='PHASE384_CLEAR'||event?.data?.type==='PHASE385_CLEAR'){event.waitUntil(caches.keys().then(keys=>Promise.all(keys.map(key=>caches.delete(key)))).then(()=>self.skipWaiting()));}});
const fresh=url=>url.pathname==='/'||url.pathname==='/index.html'||url.pathname.startsWith('/site/')||url.pathname==='/downloads/'||url.pathname==='/downloads/index.html'||url.pathname==='/game/android.html'||url.pathname==='/game/android-play.html'||url.pathname==='/game/android-stable.html'||url.pathname==='/game/android-tabletop.html'||url.pathname==='/game/index.html'||url.pathname.startsWith('/game/modules/phase384_')||url.pathname.startsWith('/game/modules/phase385_')||url.pathname.startsWith('/game/styles/phase385_')||url.pathname==='/game/android-release.json'||url.pathname==='/manifest.webmanifest'||url.pathname==='/site-public-hooks.js'||url.pathname==='/update/app-version.json'||url.pathname.endsWith('/deploy-health.json')||url.pathname.endsWith('.apk');
async function networkOnly(request){return fetch(new Request(request,{cache:'no-store',headers:request.headers}));}
async function networkFirst(request){try{return await fetch(new Request(request,{cache:'no-store'}));}catch(error){const cached=await caches.match(request,{ignoreSearch:true})||await caches.match('/offline.html');if(cached)return cached;throw error;}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(fresh(url)){event.respondWith(networkOnly(request));return;}if(request.mode==='navigate'||url.pathname.startsWith('/game/')||url.pathname.startsWith('/site/')||url.pathname.startsWith('/downloads/')||url.pathname.startsWith('/update/')){event.respondWith(networkFirst(request));return;}event.respondWith(caches.match(request).then(cached=>cached||networkFirst(request)));});