const SVR_CACHE='svr-poker-phase382-live-route-recovery-v1';
const CORE=['/offline.html','/logo.png','/site-public-hooks.js?v=phase382'];
self.addEventListener('install',event=>event.waitUntil(caches.open(SVR_CACHE).then(cache=>cache.addAll(CORE.map(url=>new Request(url,{cache:'reload'}))).catch(()=>undefined)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==SVR_CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event?.data?.type==='SKIP_WAITING'||event?.data?.type==='PHASE382_CLEAR'){event.waitUntil(caches.keys().then(keys=>Promise.all(keys.map(key=>caches.delete(key)))).then(()=>self.skipWaiting()));}});
const fresh=url=>url.pathname==='/'||url.pathname==='/index.html'||url.pathname==='/site/index.html'||url.pathname==='/site/profile.html'||url.pathname==='/site/avatar.html'||url.pathname==='/downloads/'||url.pathname==='/downloads/index.html'||url.pathname==='/game/android.html'||url.pathname==='/game/android-play.html'||url.pathname==='/game/android-stable.html'||url.pathname==='/game/index.html'||url.pathname==='/game/android-release.json'||url.pathname==='/manifest.webmanifest'||url.pathname==='/site-public-hooks.js'||url.pathname==='/update/app-version.json'||url.pathname.endsWith('/deploy-health.json')||url.pathname.endsWith('.apk');
async function networkOnly(request){return fetch(new Request(request,{cache:'no-store',headers:request.headers}));}
async function networkFirst(request){try{return await fetch(new Request(request,{cache:'no-store'}));}catch(error){const cached=await caches.match(request,{ignoreSearch:true})||await caches.match('/offline.html');if(cached)return cached;throw error;}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(fresh(url)){event.respondWith(networkOnly(request));return;}if(request.mode==='navigate'||url.pathname.startsWith('/game/')||url.pathname.startsWith('/site/')||url.pathname.startsWith('/downloads/')||url.pathname.startsWith('/update/')){event.respondWith(networkFirst(request));return;}event.respondWith(caches.match(request).then(cached=>cached||networkFirst(request)));});
