import { CognitoIdentityProviderClient, SignUpCommand, ConfirmSignUpCommand, ResendConfirmationCodeCommand, InitiateAuthCommand, GetUserCommand, GlobalSignOutCommand } from '@aws-sdk/client-cognito-identity-provider';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand, PutCommand, UpdateCommand, QueryCommand } from '@aws-sdk/lib-dynamodb';
import crypto from 'node:crypto';

const BUILD='PHASE-423-PLAYER-TOURNAMENT-API-READINESS-LOCK';
const REGION=process.env.AWS_REGION;
const USER_POOL_ID=process.env.USER_POOL_ID||'';
const CLIENT_ID=process.env.CLIENT_ID||'';
const PROFILES_TABLE=process.env.PROFILES_TABLE||'';
const SESSIONS_TABLE=process.env.SESSIONS_TABLE||'';
const REGISTRATIONS_TABLE=process.env.REGISTRATIONS_TABLE||'';
const ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||'https://svrpoker.com';
const REWARD_CHIPS=Number(process.env.DAILY_REWARD_CHIPS||5000);
const MIN_ACTIVITY_SECONDS=Number(process.env.MINIMUM_ACTIVITY_SECONDS||300);
const SESSION_COOKIE='svr_player_session';
const cognito=new CognitoIdentityProviderClient({region:REGION});
const ddb=DynamoDBDocumentClient.from(new DynamoDBClient({region:REGION}),{marshallOptions:{removeUndefinedValues:true}});

const json=(statusCode,body,cookies=[])=>({statusCode,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'},cookies,body:JSON.stringify(body)});
const safeText=(v,max=120)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,max);
const safeName=v=>safeText(v,40);
const email=v=>safeText(v,254).toLowerCase();
const iso=()=>new Date().toISOString();
const parseBody=event=>{try{return event?.body?JSON.parse(event.body):{}}catch{return{}}};
const cookieMap=event=>Object.fromEntries(String(event?.headers?.cookie||event?.headers?.Cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const sessionCookie=token=>`${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=3600`;
const clearCookie=()=>`${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=0`;
const routeOf=event=>String(event?.rawPath||event?.requestContext?.http?.path||'/');
const methodOf=event=>String(event?.requestContext?.http?.method||event?.httpMethod||'GET').toUpperCase();

function assertConfig(){for(const [key,val] of Object.entries({USER_POOL_ID,CLIENT_ID,PROFILES_TABLE,SESSIONS_TABLE,REGISTRATIONS_TABLE}))if(!val)throw Object.assign(new Error(`missing_${key.toLowerCase()}`),{statusCode:503})}
function publicProfile(p){if(!p)return null;return{playerId:p.playerId,displayName:p.displayName||'Player',email:p.email||'',role:p.role||'player',playMoney:Number(p.playMoney||0),dailyStreak:Number(p.dailyStreak||0),lastRewardClaim:p.lastRewardClaim||null,avatarUrl:p.avatarUrl||null,equippedOutfit:p.equippedOutfit||{},inventory:Array.isArray(p.inventory)?p.inventory:[],createdAt:p.createdAt||null,lastLoginAt:p.lastLoginAt||null,updatedAt:p.updatedAt||null}}
async function getProfile(playerId){const out=await ddb.send(new GetCommand({TableName:PROFILES_TABLE,Key:{playerId},ConsistentRead:true}));return out.Item||null}
async function putBaseProfile({playerId,normalizedEmail,displayName}){const now=iso(),existing=await getProfile(playerId);if(existing)return existing;const p={playerId,normalizedEmail,email:normalizedEmail,displayName:safeName(displayName)||'Player',role:'player',playMoney:50000,dailyStreak:0,lastRewardClaim:null,avatarUrl:null,equippedOutfit:{},inventory:[],createdAt:now,lastLoginAt:now,updatedAt:now};await ddb.send(new PutCommand({TableName:PROFILES_TABLE,Item:p,ConditionExpression:'attribute_not_exists(playerId)'})).catch(e=>{if(e?.name!=='ConditionalCheckFailedException')throw e});return(await getProfile(playerId))||p}
async function identity(event){const token=cookieMap(event)[SESSION_COOKIE];if(!token)throw Object.assign(new Error('not_authenticated'),{statusCode:401});let user;try{user=await cognito.send(new GetUserCommand({AccessToken:token}))}catch{throw Object.assign(new Error('session_invalid'),{statusCode:401})}const attrs=Object.fromEntries((user.UserAttributes||[]).map(x=>[x.Name,x.Value]));const playerId=attrs.sub;const normalizedEmail=email(attrs.email||user.Username||'');if(!playerId)throw Object.assign(new Error('identity_missing'),{statusCode:401});let profile=await getProfile(playerId);if(!profile)profile=await putBaseProfile({playerId,normalizedEmail,displayName:attrs.preferred_username||normalizedEmail.split('@')[0]||'Player'});return{token,playerId,normalizedEmail,profile}}
async function registration(event){const b=parseBody(event),displayName=safeName(b.displayName),normalizedEmail=email(b.email),password=String(b.password||'');if(displayName.length<2||!normalizedEmail||password.length<10)return json(400,{ok:false,error:'invalid_registration'});try{const out=await cognito.send(new SignUpCommand({ClientId:CLIENT_ID,Username:normalizedEmail,Password:password,UserAttributes:[{Name:'email',Value:normalizedEmail},{Name:'preferred_username',Value:displayName}]}));const profile=await putBaseProfile({playerId:out.UserSub,normalizedEmail,displayName});return json(201,{ok:true,requiresConfirmation:!out.UserConfirmed,email:normalizedEmail,profile:publicProfile(profile)})}catch(e){const known={UsernameExistsException:'account_exists',InvalidPasswordException:'invalid_password',InvalidParameterException:'invalid_registration'};return json(e?.name==='TooManyRequestsException'?429:400,{ok:false,error:known[e?.name]||'registration_failed'})}}
async function confirm(event){const b=parseBody(event),normalizedEmail=email(b.email),code=safeText(b.code,16);if(!normalizedEmail||!code)return json(400,{ok:false,error:'email_and_code_required'});try{await cognito.send(new ConfirmSignUpCommand({ClientId:CLIENT_ID,Username:normalizedEmail,ConfirmationCode:code}));return json(200,{ok:true,confirmed:true})}catch(e){return json(400,{ok:false,error:e?.name==='CodeMismatchException'?'invalid_confirmation_code':e?.name==='ExpiredCodeException'?'confirmation_code_expired':'confirmation_failed'})}}
async function resend(event){const normalizedEmail=email(parseBody(event).email);if(!normalizedEmail)return json(400,{ok:false,error:'email_required'});try{await cognito.send(new ResendConfirmationCodeCommand({ClientId:CLIENT_ID,Username:normalizedEmail}));return json(200,{ok:true,sent:true})}catch{return json(400,{ok:false,error:'resend_failed'})}}
async function login(event){const b=parseBody(event),normalizedEmail=email(b.email),password=String(b.password||'');if(!normalizedEmail||!password)return json(400,{ok:false,error:'email_and_password_required'});try{const out=await cognito.send(new InitiateAuthCommand({ClientId:CLIENT_ID,AuthFlow:'USER_PASSWORD_AUTH',AuthParameters:{USERNAME:normalizedEmail,PASSWORD:password}}));if(out.ChallengeName)return json(409,{ok:false,error:'auth_challenge_required',challenge:out.ChallengeName});const token=out.AuthenticationResult?.AccessToken;if(!token)return json(401,{ok:false,error:'login_failed'});const user=await cognito.send(new GetUserCommand({AccessToken:token}));const attrs=Object.fromEntries((user.UserAttributes||[]).map(x=>[x.Name,x.Value]));let profile=await putBaseProfile({playerId:attrs.sub,normalizedEmail:email(attrs.email||normalizedEmail),displayName:attrs.preferred_username||normalizedEmail.split('@')[0]});const now=iso();await ddb.send(new UpdateCommand({TableName:PROFILES_TABLE,Key:{playerId:profile.playerId},UpdateExpression:'SET lastLoginAt=:n, updatedAt=:n',ExpressionAttributeValues:{':n':now}}));profile={...profile,lastLoginAt:now,updatedAt:now};return json(200,{ok:true,profile:publicProfile(profile)},[sessionCookie(token)])}catch(e){if(e?.name==='UserNotConfirmedException')return json(403,{ok:false,error:'account_not_confirmed',email:normalizedEmail});return json(e?.name==='TooManyRequestsException'?429:401,{ok:false,error:'invalid_login'})}}
async function logout(event){const token=cookieMap(event)[SESSION_COOKIE];if(token)await cognito.send(new GlobalSignOutCommand({AccessToken:token})).catch(()=>{});return json(200,{ok:true},[clearCookie()])}
async function profileGet(event){const id=await identity(event);return json(200,{ok:true,profile:publicProfile(id.profile)})}
async function profilePut(event){const id=await identity(event),b=parseBody(event),name=safeName(b.displayName||id.profile.displayName),avatar=safeText(b.avatarUrl,500)||null,outfit=b.equippedOutfit&&typeof b.equippedOutfit==='object'?b.equippedOutfit:{};if(name.length<2)return json(400,{ok:false,error:'invalid_display_name'});const now=iso();await ddb.send(new UpdateCommand({TableName:PROFILES_TABLE,Key:{playerId:id.playerId},UpdateExpression:'SET displayName=:d, avatarUrl=:a, equippedOutfit=:o, updatedAt=:u',ExpressionAttributeValues:{':d':name,':a':avatar,':o':outfit,':u':now}}));return json(200,{ok:true,profile:publicProfile({...id.profile,displayName:name,avatarUrl:avatar,equippedOutfit:outfit,updatedAt:now})})}
async function startSession(event){const id=await identity(event),b=parseBody(event),now=iso(),sessionId=crypto.randomUUID(),expiresAt=Math.floor(Date.now()/1000)+86400;const item={sessionId,playerId:id.playerId,platform:safeText(b.platform||'web',40),startedAt:now,lastHeartbeatAt:now,activeSeconds:0,heartbeatCount:0,expiresAt,metadata:b.metadata&&typeof b.metadata==='object'?b.metadata:{}};await ddb.send(new PutCommand({TableName:SESSIONS_TABLE,Item:item}));return json(201,{ok:true,session:item})}
async function sessionById(id,sessionId){const out=await ddb.send(new GetCommand({TableName:SESSIONS_TABLE,Key:{sessionId}}));if(!out.Item||out.Item.playerId!==id.playerId)throw Object.assign(new Error('session_not_found'),{statusCode:404});return out.Item}
async function heartbeat(event,end=false){const id=await identity(event),b=parseBody(event),session=await sessionById(id,safeText(b.sessionId,80)),nowMs=Date.now(),last=Date.parse(session.lastHeartbeatAt||session.startedAt||iso()),delta=Math.max(0,Math.min(75,Math.round((nowMs-last)/1000))),nowIso=new Date(nowMs).toISOString(),active=Number(session.activeSeconds||0)+delta,count=Number(session.heartbeatCount||0)+1;await ddb.send(new UpdateCommand({TableName:SESSIONS_TABLE,Key:{sessionId:session.sessionId},UpdateExpression:'SET lastHeartbeatAt=:h, activeSeconds=:a, heartbeatCount=:c, metadata=:m'+(end?', endedAt=:e':''),ExpressionAttributeValues:{':h':nowIso,':a':active,':c':count,':m':b.metadata&&typeof b.metadata==='object'?b.metadata:(session.metadata||{}),...(end?{':e':nowIso}:{})}}));return json(200,{ok:true,session:{...session,lastHeartbeatAt:nowIso,activeSeconds:active,heartbeatCount:count,...(end?{endedAt:nowIso}:{})}})}
async function activitySeconds(playerId){const today=new Date();today.setUTCHours(0,0,0,0);const out=await ddb.send(new QueryCommand({TableName:SESSIONS_TABLE,IndexName:'player-started-at',KeyConditionExpression:'playerId=:p AND startedAt>=:s',ExpressionAttributeValues:{':p':playerId,':s':today.toISOString()}}));return(out.Items||[]).reduce((n,x)=>n+Number(x.activeSeconds||0),0)}
async function rewardStatus(event){const id=await identity(event),active=await activitySeconds(id.playerId),today=iso().slice(0,10),claimed=String(id.profile.lastRewardClaim||'').slice(0,10)===today;return json(200,{ok:true,eligible:!claimed&&active>=MIN_ACTIVITY_SECONDS,claimed,activeSeconds:active,requiredSeconds:MIN_ACTIVITY_SECONDS,rewardChips:REWARD_CHIPS})}
async function rewardClaim(event){const id=await identity(event),active=await activitySeconds(id.playerId),today=iso().slice(0,10),claimed=String(id.profile.lastRewardClaim||'').slice(0,10)===today;if(claimed)return json(409,{ok:false,error:'reward_already_claimed'});if(active<MIN_ACTIVITY_SECONDS)return json(409,{ok:false,error:'more_activity_required',activeSeconds:active,requiredSeconds:MIN_ACTIVITY_SECONDS});const now=iso(),playMoney=Number(id.profile.playMoney||0)+REWARD_CHIPS,streak=Number(id.profile.dailyStreak||0)+1;await ddb.send(new UpdateCommand({TableName:PROFILES_TABLE,Key:{playerId:id.playerId},UpdateExpression:'SET playMoney=:m, dailyStreak=:s, lastRewardClaim=:r, updatedAt=:u',ExpressionAttributeValues:{':m':playMoney,':s':streak,':r':now,':u':now},ConditionExpression:'attribute_not_exists(lastRewardClaim) OR lastRewardClaim < :today',ExpressionAttributeValues:{':m':playMoney,':s':streak,':r':now,':u':now,':today':today}})).catch(e=>{if(e?.name==='ConditionalCheckFailedException')throw Object.assign(new Error('reward_already_claimed'),{statusCode:409});throw e});const profile={...id.profile,playMoney,dailyStreak:streak,lastRewardClaim:now,updatedAt:now};return json(200,{ok:true,claimed:true,rewardChips:REWARD_CHIPS,profile:publicProfile(profile)})}
async function tournamentRoster(slotId){const out=await ddb.send(new QueryCommand({TableName:REGISTRATIONS_TABLE,KeyConditionExpression:'slotId=:s',ExpressionAttributeValues:{':s':String(slotId)},Limit:100}));const registrations=(out.Items||[]).sort((a,b)=>String(a.registeredAt).localeCompare(String(b.registeredAt))).map(x=>({playerId:x.playerId,displayName:x.displayName,source:x.source||'shared-registration',registeredAt:x.registeredAt,slotId:x.slotId}));return json(200,{ok:true,registrations})}
async function tournamentRegister(event,slotId){const id=await identity(event),b=parseBody(event),displayName=safeName(b.displayName||id.profile.displayName)||'Player',registeredAt=iso(),item={slotId:String(slotId),playerId:id.playerId,displayName,source:'shared-registration',registeredAt};try{await ddb.send(new PutCommand({TableName:REGISTRATIONS_TABLE,Item:item,ConditionExpression:'attribute_not_exists(slotId) AND attribute_not_exists(playerId)'}))}catch(e){if(e?.name!=='ConditionalCheckFailedException')throw e;await ddb.send(new UpdateCommand({TableName:REGISTRATIONS_TABLE,Key:{slotId:String(slotId),playerId:id.playerId},UpdateExpression:'SET displayName=:d, registeredAt=:r',ExpressionAttributeValues:{':d':displayName,':r':registeredAt}}))}return json(200,{ok:true,registration:item})}

export const handler=async event=>{try{assertConfig();const method=methodOf(event),route=routeOf(event);if(method==='GET'&&(route==='/health'||route==='/api/health'))return json(200,{status:'ok',build:BUILD,accounts:true,tournaments:true,serverAuthoritativePoker:false,time:iso()});if(method==='POST'&&route==='/auth/register')return registration(event);if(method==='POST'&&route==='/auth/confirm')return confirm(event);if(method==='POST'&&route==='/auth/resend-confirmation')return resend(event);if(method==='POST'&&route==='/auth/login')return login(event);if(method==='POST'&&route==='/auth/logout')return logout(event);if(method==='GET'&&route==='/player/profile')return profileGet(event);if(method==='PUT'&&route==='/player/profile')return profilePut(event);if(method==='GET'&&route==='/rewards/daily/status')return rewardStatus(event);if(method==='POST'&&route==='/rewards/daily/claim')return rewardClaim(event);if(method==='POST'&&route==='/game/session/start')return startSession(event);if(method==='POST'&&route==='/game/session/heartbeat')return heartbeat(event,false);if(method==='POST'&&route==='/game/session/end')return heartbeat(event,true);const m=route.match(/^\/api\/tournaments\/([^/]+)\/(registrations|register)$/);if(m&&method==='GET'&&m[2]==='registrations')return tournamentRoster(m[1]);if(m&&method==='POST'&&m[2]==='register')return tournamentRegister(event,m[1]);return json(404,{ok:false,error:'not_found'})}catch(e){const status=Number(e?.statusCode||500);console.error(JSON.stringify({build:BUILD,event:'api_error',status,error:String(e?.message||e)}));return json(status,{ok:false,error:status>=500?'service_error':String(e?.message||'request_failed')})}};
