// PHASE-84O-HIGH-PLANETS-FILLED-SKYLINE-LOCK
// Runtime player-POV ad grid lock lives in world_skyline.js buildOuterCity().
// This registry documents modular building ad slots for future swaps.
export const BUILDING_AD_GRID_LOCK = {
  build: "PHASE-84O-HIGH-PLANETS-FILLED-SKYLINE-LOCK",
  siteTouched: false,
  approvalLock: "No UNAPPROVED_SPONSOR_BLOCKED/UNAPPROVED_SPONSOR_BLOCKED/UNAPPROVED_SPONSOR_BLOCKED/UNAPPROVED_SPONSOR_BLOCKED/UNAPPROVED_SPONSOR_BLOCKED content until explicit approval.",
  slots: [
    "AD_CENTER_PREMIUM_ESPRESSO_FRONT_VISIBLE",
    "AD_LEFT_TOWER_VISIBLE",
    "AD_RIGHT_TOWER_VISIBLE",
    "AD_FILLED_SKYLINE_GAP_LEFT",
    "AD_FILLED_SKYLINE_GAP_RIGHT",
    "AD_LOWER_BANNER_01",
    "AD_LOWER_BANNER_02",
    "AD_LOWER_BANNER_03",
    "AD_INTERCARDINAL_TIER3_WIN_CASH"
  ]
};
