const REAL_ESPRESSO_AD_URL = "./assets/ads/espresso_lobby_wall_ad_1080x1600.png?v=phase109-real-espresso-banner";
const painted = new WeakSet();
function loadImage(url){return new Promise((resolve)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=url;setTimeout(()=>resolve(img.complete&&img.naturalWidth?img:null),2200);});}
const espressoImage = await loadImage(REAL_ESPRESSO_AD_URL);
function cover(ctx,img,x,y,w,h){if(!img||!img.naturalWidth||!img.naturalHeight)return false;const ir=img.naturalWidth/img.naturalHeight;const br=w/h;let sw=img.naturalWidth,sh=img.naturalHeight,sx=0,sy=0;if(ir>br){sw=img.naturalHeight*br;sx=(img.naturalWidth-sw)*0.5;}else{sh=img.naturalWidth/br;sy=(img.naturalHeight-sh)*0.5;}ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h);return true;}
function fallback(ctx,w,h){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#090104");g.addColorStop(1,"#1d0d05");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="#fff5df";ctx.font="900 116px system-ui, Arial";ctx.fillText("ESPRESSO",w/2,h*.57);ctx.fillStyle="#ffd36b";ctx.font="900 88px system-ui, Arial";ctx.fillText("WITH CREAM",w/2,h*.65);ctx.fillStyle="#fff9ed";ctx.font="700 42px system-ui, Arial";ctx.fillText("REAL PHOTO AD",w/2,h*.78);}
function paint(ctx){const c=ctx.canvas;if(painted.has(c))return;c.width=1024;c.height=1536;const w=c.width,h=c.height;ctx.clearRect(0,0,w,h);if(!cover(ctx,espressoImage,0,0,w,h))fallback(ctx,w,h);painted.add(c);}
const originalFillText = CanvasRenderingContext2D.prototype.fillText;
CanvasRenderingContext2D.prototype.fillText = function(text,...args){const label=String(text||"").toUpperCase();const c=this.canvas;const target=c&&c.width===1024&&(c.height===512||c.height===1536)&&(label==="ESPRESSO"||label==="WITH CREAM"||label.includes("SVR LOUNGE PARTNER")||label.includes("CITY AD BANNER RESTORED")||label.includes("COFFEE")||label.includes("CREAM"));if(target){paint(this);return;}if(painted.has(c)&&(label.includes("WITH CREAM")||label.includes("SVR LOUNGE")||label.includes("COFFEE")||label.includes("ESPRESSO")||label.includes("CREAM")))return;return originalFillText.call(this,text,...args);};
window.SVR_REAL_ESPRESSO_AD_PATCH={enabled:true,phase:"PHASE-109-REAL-ESPRESSO-PNG-BANNER-LOCK",imageUrl:REAL_ESPRESSO_AD_URL,imageLoaded:Boolean(espressoImage&&espressoImage.naturalWidth),correctPhoto:true,repoHosted:true};
