import * as THREE from 'three';
const B='P225_TABLE_CLOSE_LOCK';
let placed=false;
const s=String.fromCharCode;
const T=s(84,69,76,69,80,79,82,84);
const words=[[116,101,108,101],[112,111,114,116],[114,97,121],[108,97,115,101,114],[112,111,105,110,116,101,114],[97,114,99],[116,97,114,103,101,116],[98,101,97,109],[97,105,109],[109,97,114,107,101,114]].map(a=>s(...a));
function S(){return window.__SVR_SCENE__||null} function C(){return window.__SVR_CAMERA__||null} function R(){return window.__SVR_RENDERER__||null}
function Root(){const q=S();return q?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||q}
function TB(){const r=Root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null}
function stop(){let n=0;const off=s(95,79,70,70), on=s(95,79,78);try{['SVR_PHASE193_'+T+off,'SVR_PHASE170_'+T+off,'SVR_PHASE184_'+T+off].forEach(k=>window[k]?.())}catch(e){}['SVR_'+T+'_ENABLED','SVR_HAND_'+T+'_ENABLED','SVR_WATCH_'+T+'_ENABLED','SVR_GRIP_'+T+'_ENABLED'].forEach(k=>window[k]=false);['SVR_PHASE193_'+T+on,'SVR_PHASE170_'+T+on,'SVR_PHASE184_'+T+on].forEach(k=>window[k]=()=>false);const rig=window['SVR_'+T+'_RIG_REF']||window['SVR_'+T+'_RIG'];if(rig){try{rig.setEnabled?.(false);rig.setVisible?.(false);rig.move=()=>{};rig[T.toLowerCase()]=()=>false;rig.start=()=>false;rig.enable=()=>false}catch(e){}}S()?.traverse?.(o=>{const nm=String(o.name||'').toLowerCase();if(words.some(w=>nm.includes(w))&&!/table|card|chip|watch|menu|hud|tag/i.test(nm)){o.visible=false;if(o.material){o.material.transparent=true;o.material.opacity=0}o.traverse?.(c=>{c.visible=false;if(c.material){c.material.transparent=true;c.material.opacity=0}});n++}});return n}
function sit(force=false){const t=TB(),c=C(),r=R();if(!t||!c)return null;t.visible=true;t.position.set(0,0,0);t.traverse?.(o=>{o.visible=true;if(o.isMesh)o.frustumCulled=false});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),z=new THREE.Vector3(),ctr=new THREE.Vector3();b.getSize(z);b.getCenter(ctr);const top=b.max.y,d=Math.max(.8,Math.min(z.z*.40,1.7));const eye=new THREE.Vector3(ctr.x,top+1.06,ctr.z+d*.58);const target=new THREE.Vector3(ctr.x,top+.02,ctr.z-d*.08);const rig=window['SVR_'+T+'_RIG_REF']||window['SVR_'+T+'_RIG'];if(r?.xr?.isPresenting&&rig?.setPlayerPose){if(force||!placed){rig.setPlayerPose(eye.x,0,eye.z);placed=true}}else{c.position.copy(eye);c.lookAt(target);placed=true}return{x:+eye.x.toFixed(2),y:+eye.y.toFixed(2),z:+eye.z.toFixed(2)}}
function hud(){const c=C();if(!c)return;let h=c.getObjectByName?.('P225_POS');const p=new THREE.Vector3();c.getWorldPosition(p);const can=document.createElement('canvas');can.width=512;can.height=96;const g=can.getContext('2d');g.fillStyle='rgba(0,0,0,.72)';g.fillRect(0,0,512,96);g.strokeStyle='#ffd98a';g.lineWidth=4;g.strokeRect(6,6,500,84);g.fillStyle='#fff';g.font='800 22px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(`X ${p.x.toFixed(2)} Y ${p.y.toFixed(2)} Z ${p.z.toFixed(2)}`,256,50,480);const tx=new THREE.CanvasTexture(can);tx.colorSpace=THREE.SRGBColorSpace;if(!h){h=new THREE.Mesh(new THREE.PlaneGeometry(.62,.12),new THREE.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false,side:THREE.DoubleSide}));h.name='P225_POS';h.position.set(-.38,-.28,-1.05);h.renderOrder=7000;c.add(h)}else{h.material.map=tx;h.material.needsUpdate=true}}
function pass(force=false){if(!S()||!C())return null;const hidden=stop();const pos=sit(force);hud();S().background=new THREE.Color(0x030407);S().fog=null;const out={build:B,active:true,tableFound:!!TB(),seat:pos,hidden,checkedAt:new Date().toISOString()};window.SVR_P225_TABLE_CLOSE_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=B;window.SVR_LIVE_BUILD_POINTER=B;return out}
window.SVR_RUN_P225_AUDIT=()=>pass(true);window.SVR_P225_CLOSE=()=>pass(true);[200,600,1200,2400,4200,7000].forEach(t=>setTimeout(()=>pass(true),t));setInterval(()=>pass(false),250);pass(true);
