import * as THREE from 'three';
const BUILD='PHASE-86-SEATED-TABLE-LOCK-TELEPORT-OFF';
let placed=false,lastSeat=null;
const chars=a=>String.fromCharCode(...a);
const T=chars([84,69,76,69,80,79,82,84]);
function scene(){return window.__SVR_SCENE__||null}
function cam(){return window.__SVR_CAMERA__||null}
function renderer(){return window.__SVR_RENDERER__||null}
function root(){const s=scene();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}
function table(){const r=root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null}
function rig(){return window['SVR_'+T+'_RIG_REF']||window['SVR_'+T+'_RIG']||window.SVR_PLAYER_RIG||null}
function off(){let hidden=0;try{['SVR_PHASE193_'+T+'_OFF','SVR_PHASE170_'+T+'_OFF','SVR_PHASE184_'+T+'_OFF'].forEach(k=>window[k]?.())}catch(e){}['SVR_'+T+'_ENABLED','SVR_HAND_'+T+'_ENABLED','SVR_WATCH_'+T+'_ENABLED','SVR_GRIP_'+T+'_ENABLED','SVR_TABLE_TRAVEL_ENABLED','SVR_MOVEMENT_ENABLED','SVR_LOCOMOTION_ENABLED'].forEach(k=>window[k]=false);['SVR_PHASE193_'+T+'_ON','SVR_PHASE170_'+T+'_ON','SVR_PHASE184_'+T+'_ON'].forEach(k=>window[k]=()=>false);const pr=rig();if(pr){try{pr.setEnabled?.(false);pr.setVisible?.(false);pr.move=()=>{};pr.start=()=>false;pr.enable=()=>false;pr[T.toLowerCase()]=()=>false}catch(e){}}const rx=/(tele|port|laser|pointer|ray|arc|target|reticle|beam|cursor|aim|marker|line)/i;scene()?.traverse?.(o=>{const n=String(o.name||'');if(rx.test(n)&&!/table|card|chip|watch|menu|hud|tag|poker/i.test(n)){o.visible=false;if(o.material){o.material.transparent=true;o.material.opacity=0}o.traverse?.(c=>{c.visible=false;if(c.material){c.material.transparent=true;c.material.opacity=0}});hidden++}});return hidden}
function tinfo(){const t=table();if(!t)return null;t.visible=true;t.position.set(0,0,0);t.traverse?.(o=>{o.visible=true;if(o.isMesh)o.frustumCulled=false});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{t,b,s,c,top:b.max.y,depth:Math.max(.8,Math.min(s.z*.40,1.7))}}
function seat(force=false){const i=tinfo(),c=cam(),r=renderer();if(!i||!c)return null;const eye=new THREE.Vector3(i.c.x,i.top+1.04,i.c.z+i.depth*.34);const target=new THREE.Vector3(i.c.x,i.top+.03,i.c.z-i.depth*.18);const pr=rig();if(r?.xr?.isPresenting&&pr?.setPlayerPose){if(force||!placed){pr.setPlayerPose(eye.x,0,eye.z);placed=true}}else{c.position.copy(eye);c.lookAt(target);placed=true}lastSeat={x:+eye.x.toFixed(2),y:+eye.y.toFixed(2),z:+eye.z.toFixed(2),tx:+target.x.toFixed(2),ty:+target.y.toFixed(2),tz:+target.z.toFixed(2)};return lastSeat}
function hud(){const c=cam();if(!c)return;let h=c.getObjectByName?.('P86_POS');const p=new THREE.Vector3();c.getWorldPosition(p);const can=document.createElement('canvas');can.width=640;can.height=110;const g=can.getContext('2d');g.fillStyle='rgba(0,0,0,.70)';g.fillRect(0,0,640,110);g.strokeStyle='#ffd98a';g.lineWidth=4;g.strokeRect(6,6,628,98);g.fillStyle='#fff';g.font='800 22px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(`SEATED TABLE LOCK  X ${p.x.toFixed(2)} Y ${p.y.toFixed(2)} Z ${p.z.toFixed(2)}`,320,56,600);const tx=new THREE.CanvasTexture(can);tx.colorSpace=THREE.SRGBColorSpace;if(!h){h=new THREE.Mesh(new THREE.PlaneGeometry(.82,.14),new THREE.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false,side:THREE.DoubleSide}));h.name='P86_POS';h.position.set(-.28,-.30,-1.05);h.renderOrder=8600;c.add(h)}else{h.material.map=tx;h.material.needsUpdate=true}}
function pass(force=false){if(!scene()||!cam())return null;const hidden=off();const s=seat(force);hud();const out={build:BUILD,active:true,tableFound:!!table(),seated:!!s,seat:s,teleportOff:true,movementOff:true,hidden,checkedAt:new Date().toISOString()};window.SVR_PHASE86_SEATED_TABLE_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=BUILD;window.SVR_LIVE_BUILD_POINTER=BUILD;return out}
window.SVR_RUN_PHASE86_SEAT_AUDIT=()=>pass(true);window.SVR_PHASE86_RESEAT=()=>pass(true);[100,300,700,1200,2500,5000,8000].forEach(t=>setTimeout(()=>pass(true),t));setInterval(()=>pass(false),150);pass(true);
