import * as THREE from 'three';
const BUILD='PHASE-87-SCORPION-SEAT-AUTHORITY-LOCK';
let placed=false,last=null,holder=null;
const tword=String.fromCharCode(84,69,76,69,80,79,82,84);
function sc(){return window.__SVR_SCENE__||null}function cam(){return window.__SVR_CAMERA__||null}function ren(){return window.__SVR_RENDERER__||null}
function root(){const s=sc();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}
function tbl(){const r=root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null}
function playerRig(){return window['SVR_'+tword+'_RIG_REF']||window['SVR_'+tword+'_RIG']||window.SVR_PLAYER_RIG||window.__SVR_PLAYER_RIG||null}
function off(){let n=0;try{['SVR_PHASE193_'+tword+'_OFF','SVR_PHASE170_'+tword+'_OFF','SVR_PHASE184_'+tword+'_OFF'].forEach(k=>window[k]?.())}catch(e){}['SVR_'+tword+'_ENABLED','SVR_HAND_'+tword+'_ENABLED','SVR_WATCH_'+tword+'_ENABLED','SVR_GRIP_'+tword+'_ENABLED','SVR_TABLE_TRAVEL_ENABLED','SVR_MOVEMENT_ENABLED','SVR_LOCOMOTION_ENABLED','SVR_HAND_RAY_ENABLED','SVR_POINTER_ENABLED'].forEach(k=>window[k]=false);['SVR_PHASE193_'+tword+'_ON','SVR_PHASE170_'+tword+'_ON','SVR_PHASE184_'+tword+'_ON'].forEach(k=>window[k]=()=>false);const pr=playerRig();if(pr){try{pr.setEnabled?.(false);pr.setVisible?.(false);pr.move=()=>{};pr.start=()=>false;pr.enable=()=>false;pr[tword.toLowerCase()]=()=>false}catch(e){}}const rx=/(tele|port|laser|pointer|ray|arc|target|reticle|beam|cursor|aim|marker|line|parabola|cone)/i;sc()?.traverse?.(o=>{const name=String(o.name||'');if(rx.test(name)&&!/table|card|chip|watch|menu|hud|tag|poker|pot|player/i.test(name)){o.visible=false;if(o.material){o.material.transparent=true;o.material.opacity=0}o.traverse?.(c=>{c.visible=false;if(c.material){c.material.transparent=true;c.material.opacity=0}});n++}});return n}
function info(){const t=tbl();if(!t)return null;t.visible=true;t.position.set(0,0,0);t.traverse?.(o=>{o.visible=true;if(o.isMesh)o.frustumCulled=false});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{t,b,s,c,top:b.max.y,halfZ:Math.max(.9,s.z*.5),halfX:Math.max(1.2,s.x*.5)}}
function setRigPosition(obj,eye){if(!obj)return false;try{if(obj.position){obj.position.x=eye.x;obj.position.z=eye.z;return true}}catch(e){}return false}
function seat(force=false){const i=info(),c=cam(),r=ren();if(!i||!c)return null;const frontZ=i.c.z+i.halfZ*.62;const eye=new THREE.Vector3(i.c.x,i.top+1.05,frontZ);const target=new THREE.Vector3(i.c.x,i.top+.03,i.c.z-i.halfZ*.18);const pr=playerRig();let used='camera';if(r?.xr?.isPresenting){if(pr?.setPlayerPose){pr.setPlayerPose(eye.x,0,eye.z);used='setPlayerPose';placed=true}else if(setRigPosition(pr,eye)){used='rig.position';placed=true}}
if(!r?.xr?.isPresenting||!placed){c.position.copy(eye);c.lookAt(target);placed=true;used='camera.position'}last={x:+eye.x.toFixed(2),y:+eye.y.toFixed(2),z:+eye.z.toFixed(2),tx:+target.x.toFixed(2),ty:+target.y.toFixed(2),tz:+target.z.toFixed(2),used};return last}
function textMap(line){const can=document.createElement('canvas');can.width=768;can.height=112;const g=can.getContext('2d');g.fillStyle='rgba(0,0,0,.72)';g.fillRect(0,0,768,112);g.strokeStyle='#ff3d66';g.lineWidth=4;g.strokeRect(6,6,756,100);g.fillStyle='#fff';g.font='800 23px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(line,384,58,720);const tx=new THREE.CanvasTexture(can);tx.colorSpace=THREE.SRGBColorSpace;return tx}
function hud(){const c=cam();if(!c)return;let h=c.getObjectByName?.('P87_SEAT_HUD');const p=new THREE.Vector3();c.getWorldPosition(p);const line=`SCORPION TABLE SEAT  X ${p.x.toFixed(2)} Y ${p.y.toFixed(2)} Z ${p.z.toFixed(2)}`;const tx=textMap(line);if(!h){h=new THREE.Mesh(new THREE.PlaneGeometry(.92,.14),new THREE.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false,side:THREE.DoubleSide}));h.name='P87_SEAT_HUD';h.position.set(-.18,-.33,-1.05);h.renderOrder=8700;c.add(h)}else{h.material.map=tx;h.material.needsUpdate=true}}
function markRoom(){const r=root();if(!r||holder)return;holder=new THREE.Group();holder.name='P87_SCORPION_TABLE_AUTHORITY_MARKERS';r.add(holder);const i=info();if(!i)return;const m=new THREE.Mesh(new THREE.PlaneGeometry(1.4,.25),new THREE.MeshBasicMaterial({map:textMap('SCORPION TABLE MODE'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name='P87_SCORPION_LABEL';m.position.set(i.c.x,i.top+1.5,i.c.z-i.halfZ*.72);m.rotation.x=-.22;m.renderOrder=8701;holder.add(m)}
function pass(force=true){if(!sc()||!cam())return null;const hidden=off();markRoom();const s=seat(force);hud();sc().background=new THREE.Color(0x030407);sc().fog=null;const out={build:BUILD,active:true,scorpionTableMode:true,tableFound:!!tbl(),seated:!!s,seat:s,handTeleportOff:true,movementOff:true,hidden,checkedAt:new Date().toISOString()};window.SVR_PHASE87_SCORPION_SEAT_AUTHORITY=out;window.SVR_LOCKED_FINAL_BUILD=BUILD;window.SVR_LIVE_BUILD_POINTER=BUILD;return out}
window.SVR_RUN_PHASE87_SCORPION_AUDIT=()=>pass(true);window.SVR_PHASE87_RESEAT=()=>pass(true);[50,150,350,800,1500,3000,5500,8500].forEach(t=>setTimeout(()=>pass(true),t));setInterval(()=>pass(true),120);pass(true);
