import * as THREE from 'three';
const BUILD='PHASE-89-TABLE-SURFACE-GRAB-LOCK';
let scene,camera,renderer,root,group,built=false,last=performance.now();
const items=[];const movers=[];const grabs=new Map();const ctrlState=new Map();
function S(){return window.__SVR_SCENE__||null}function C(){return window.__SVR_CAMERA__||null}function R(){return window.__SVR_RENDERER__||null}
function Root(){const s=S();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}
function T(){const r=Root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null}
function info(){const t=T();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{t,b,s,c,top:b.max.y,playY:b.max.y-.152,halfX:Math.max(1.2,s.x*.5),halfZ:Math.max(.75,s.z*.5)}}
function hideFloaters(){Root()?.traverse?.(o=>{const n=String(o.name||'');if(/^P85_|PHASE85_POKER_TRUTH_TABLE_LAYER/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false)}})}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.48,metalness:.14})}
function cardTex(a,b){const can=document.createElement('canvas');can.width=180;can.height=250;const g=can.getContext('2d');g.fillStyle='#f6f0df';g.fillRect(0,0,180,250);g.strokeStyle='#111';g.lineWidth=7;g.strokeRect(7,7,166,236);g.fillStyle=(b==='H'||b==='D')?'#b5142b':'#111';g.font='900 45px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(a,90,92);g.font='900 50px system-ui';g.fillText({S:'♠',H:'♥',D:'♦',C:'♣'}[b]||b,90,158);const t=new THREE.CanvasTexture(can);t.colorSpace=THREE.SRGBColorSpace;return t}
function addCard(n,x,y,z,a,b){const o=new THREE.Mesh(new THREE.BoxGeometry(.22,.006,.31),new THREE.MeshStandardMaterial({map:cardTex(a,b),roughness:.7,metalness:0}));o.name=n;o.position.set(x,y+.006,z);o.userData.grab=true;o.userData.kind='card';o.userData.v=new THREE.Vector3();group.add(o);items.push(o);return o}
function addChip(n,x,y,z,c){const o=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.01,32),mat(c));o.name=n;o.position.set(x,y+.012,z);o.userData.grab=true;o.userData.kind='chip';o.userData.v=new THREE.Vector3();group.add(o);items.push(o);return o}
function addStack(n,x,y,z,c,count=5){for(let i=0;i<count;i++)addChip(n+'_'+i,x,y+i*.011,z,c)}
function build(){scene=S();camera=C();renderer=R();root=Root();if(!scene||!root||!renderer)return false;hideFloaters();if(group)group.parent?.remove(group);items.length=0;movers.length=0;group=new THREE.Group();group.name='PHASE89_TABLE_SURFACE_GRAB_ROOT';root.add(group);const inf=info();if(!inf)return false;const c=inf.c,y=inf.playY,ix=inf.halfX*.70,iz=inf.halfZ*.62;const seats=[['YOU',0,iz*.62,0x18d8ff],['B1',-ix*.55,iz*.32,0xff5b8c],['B2',-ix*.55,-iz*.18,0xffd98a],['B3',0,-iz*.58,0x8eff8e],['B4',ix*.55,-iz*.18,0xa78bfa],['B5',ix*.55,iz*.32,0xff8bd1]];const deck=[['A','S'],['K','H'],['7','D'],['3','C'],['Q','S'],['J','H'],['8','D'],['8','C'],['5','S'],['5','H'],['10','D'],['2','C']];seats.forEach(([nm,x,z,col],i)=>{const px=c.x+x,pz=c.z+z;addStack('P89_CHIP_'+i,px,y,pz,col,5);const a=deck[i*2],b=deck[i*2+1];addCard('P89_CARD_'+i+'_A',px-.13,y,pz-.08,a[0],a[1]);addCard('P89_CARD_'+i+'_B',px+.13,y,pz-.08,b[0],b[1])});[['A','D'],['K','S'],['Q','H'],['J','D'],['10','C']].forEach(([a,b],i)=>addCard('P89_COMM_'+i,c.x+(i-2)*.25,y,c.z-iz*.14,a,b));wireControllers();built=true;window.SVR_PHASE89_TABLE_SURFACE={build:BUILD,playY:+y.toFixed(3),items:items.length,tableTop:+inf.top.toFixed(3)};return true}
function controllerPos(ctrl){const p=new THREE.Vector3();ctrl.getWorldPosition(p);return p}
function nearest(p,rad=.22){let best=null,bd=rad;for(const o of items){if(!o.visible||o.parent!==group&&!(o.parent&&o.parent.name?.startsWith('controller')))continue;const wp=new THREE.Vector3();o.getWorldPosition(wp);const d=wp.distanceTo(p);if(d<bd){bd=d;best=o}}return best}
function startGrab(ctrl){const p=controllerPos(ctrl);const obj=nearest(p);if(!obj)return;const st=ctrlState.get(ctrl)||{};st.last=p.clone();st.prev=p.clone();ctrlState.set(ctrl,st);ctrl.attach(obj);grabs.set(ctrl,obj);obj.userData.v.set(0,0,0)}
function endGrab(ctrl){const obj=grabs.get(ctrl);if(!obj)return;group.attach(obj);const st=ctrlState.get(ctrl)||{};if(st.last&&st.prev)obj.userData.v.copy(st.last).sub(st.prev).multiplyScalar(8);movers.push(obj);grabs.delete(ctrl)}
function wireControllers(){if(!renderer?.xr||wireControllers.done)return;wireControllers.done=true;for(let i=0;i<2;i++){const ctrl=renderer.xr.getController(i);ctrl.name='P89_GRAB_CONTROLLER_'+i;scene.add(ctrl);ctrl.addEventListener('selectstart',()=>startGrab(ctrl));ctrl.addEventListener('selectend',()=>endGrab(ctrl));ctrl.addEventListener('squeezestart',()=>startGrab(ctrl));ctrl.addEventListener('squeezeend',()=>endGrab(ctrl));ctrlState.set(ctrl,{prev:new THREE.Vector3(),last:new THREE.Vector3()})}}
function update(dt){hideFloaters();if(!built)build();if(!group)return;for(const [ctrl] of grabs){const st=ctrlState.get(ctrl);if(st){st.prev.copy(st.last);ctrl.getWorldPosition(st.last)}}const inf=info();if(!inf)return;const y=inf.playY;for(let i=movers.length-1;i>=0;i--){const o=movers[i];if(grabs.has(o))continue;o.position.addScaledVector(o.userData.v,dt);o.userData.v.multiplyScalar(.94);const minY=y+(o.userData.kind==='chip'?0.012:0.006);if(o.position.y<minY){o.position.y=minY;o.userData.v.y=0}o.position.x=Math.max(inf.c.x-inf.halfX*.72,Math.min(inf.c.x+inf.halfX*.72,o.position.x));o.position.z=Math.max(inf.c.z-inf.halfZ*.72,Math.min(inf.c.z+inf.halfZ*.72,o.position.z));if(o.userData.v.length()<.005)movers.splice(i,1)}}
function loop(){const now=performance.now();const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);requestAnimationFrame(loop)}
function install(){scene=S();camera=C();renderer=R();root=Root();if(!scene||!renderer)return setTimeout(install,300);build();window.SVR_RUN_PHASE89_SURFACE_AUDIT=()=>({build:BUILD,active:true,items:items.length,grabs:grabs.size,table:info(),checkedAt:new Date().toISOString()});loop()}
install();
