import * as THREE from 'three';
const BUILD='PHASE-90-SCORPION-TABLE-PRODUCTION-SURFACE-LOCK';
let installed=false,root,scene,group;
function S(){return window.__SVR_SCENE__||null}
function R(){const s=S();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}
function T(){const r=R();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null}
function makeNoise(base='#150026',accent='#bd00ff',size=256,dots=9000){const c=document.createElement('canvas');c.width=c.height=size;const g=c.getContext('2d');g.fillStyle=base;g.fillRect(0,0,size,size);for(let i=0;i<dots;i++){const a=Math.random();g.fillStyle=a>.5?'rgba(255,255,255,.035)':'rgba(0,0,0,.055)';g.fillRect(Math.random()*size,Math.random()*size,1,1)}g.strokeStyle=accent;g.globalAlpha=.035;for(let y=0;y<size;y+=8){g.beginPath();g.moveTo(0,y);g.lineTo(size,y);g.stroke()}for(let x=0;x<size;x+=11){g.beginPath();g.moveTo(x,0);g.lineTo(x,size);g.stroke()}g.globalAlpha=1;const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;tx.wrapS=tx.wrapT=THREE.RepeatWrapping;tx.repeat.set(18,18);return tx}
function brickTexture(){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#07070b';g.fillRect(0,0,256,256);for(let y=0;y<256;y+=32){for(let x=(y/32)%2? -32:0;x<256;x+=64){g.fillStyle='rgba(80,12,35,.42)';g.fillRect(x+2,y+2,60,28);g.strokeStyle='rgba(255,61,102,.12)';g.strokeRect(x+2,y+2,60,28)}}for(let i=0;i<3000;i++){g.fillStyle=Math.random()>.5?'rgba(255,255,255,.025)':'rgba(0,0,0,.05)';g.fillRect(Math.random()*256,Math.random()*256,1,1)}const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;tx.wrapS=tx.wrapT=THREE.RepeatWrapping;tx.repeat.set(8,4);return tx}
function materialFor(name){const n=String(name||'').toLowerCase();if(n.includes('felt')||n.includes('zone')||n.includes('table_top')||n.includes('play')){const noise=makeNoise('#120022','#7ffcff');return new THREE.MeshStandardMaterial({color:0x150026,map:noise,bumpMap:noise,bumpScale:.006,roughness:.88,metalness:.05,side:THREE.DoubleSide})}if(n.includes('wall')||n.includes('panel')){const tx=brickTexture();return new THREE.MeshStandardMaterial({color:0x13050a,map:tx,bumpMap:tx,bumpScale:.012,roughness:.9,metalness:.03,side:THREE.DoubleSide})}if(n.includes('floor')){const tx=makeNoise('#10040a','#ff3d66',256,5000);tx.repeat.set(10,8);return new THREE.MeshStandardMaterial({color:0x10040a,map:tx,bumpMap:tx,bumpScale:.004,roughness:.82,metalness:.08,side:THREE.DoubleSide})}return null}
function polishRoom(){let count=0;R()?.traverse?.(o=>{if(o.isMesh){const m=materialFor(o.name);if(m){o.material=m;count++}}});return count}
function info(){const t=T();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{t,b,s,c,top:b.max.y,playY:b.max.y-.152,halfX:Math.max(1.2,s.x*.5),halfZ:Math.max(.75,s.z*.5)}}
function addPlaySurface(){const i=info();if(!i)return false;if(group)group.parent?.remove(group);group=new THREE.Group();group.name='PHASE90_SURFACE_POLISH_ROOT';R().add(group);const tx=makeNoise('#140021','#00ffff');tx.repeat.set(22,12);const felt=new THREE.Mesh(new THREE.BoxGeometry(i.halfX*1.32,.012,i.halfZ*1.12),new THREE.MeshStandardMaterial({color:0x140021,map:tx,bumpMap:tx,bumpScale:.005,roughness:.9,metalness:.04,side:THREE.DoubleSide}));felt.name='PHASE90_LOWER_PLAY_FELT_SURFACE';felt.position.set(i.c.x,i.playY-.006,i.c.z);felt.renderOrder=3000;group.add(felt);const rail=new THREE.Mesh(new THREE.TorusGeometry(Math.max(i.halfX*.68,i.halfZ*.58),.01,10,96),new THREE.MeshStandardMaterial({color:0xb88a35,roughness:.45,metalness:.45}));rail.name='PHASE90_GOLD_TABLE_LINE';rail.scale.z=i.halfZ/i.halfX*.82;rail.rotation.x=Math.PI/2;rail.position.set(i.c.x,i.playY+.012,i.c.z);group.add(rail);const light=new THREE.PointLight(0x7ffcff,.55,4,2);light.name='PHASE90_LOW_TABLE_GLOW';light.position.set(i.c.x,i.playY+.45,i.c.z+.2);group.add(light);return true}
function snapObjects(){const i=info();if(!i)return 0;let n=0;R()?.traverse?.(o=>{const nm=String(o.name||'');if(/^P89_(CARD|CHIP|COMM)/.test(nm)){o.userData.surfaceY=i.playY;if(o.userData.kind==='chip'){o.scale.setScalar(.85);if(o.position.y<i.playY+.01)o.position.y=i.playY+.012}else if(o.userData.kind==='card'){if(o.position.y<i.playY+.006)o.position.y=i.playY+.006;o.rotation.x=0;o.rotation.z=o.rotation.z||0}n++}});return n}
function install(){scene=S();root=R();if(!scene||!root)return setTimeout(install,300);const polished=polishRoom();const surface=addPlaySurface();const snapped=snapObjects();scene.background=new THREE.Color(0x020206);window.SVR_PHASE90_SURFACE_POLISH={build:BUILD,active:true,polished,surface,snapped,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;window.SVR_LIVE_BUILD_POINTER=BUILD;installed=true}
window.SVR_RUN_PHASE90_SURFACE_AUDIT=()=>{install();return window.SVR_PHASE90_SURFACE_POLISH};setTimeout(install,500);setTimeout(install,1500);setInterval(()=>{if(installed)snapObjects()},500);install();
