import * as THREE from 'three';
const BUILD='PHASE-91-SCORPION-TABLE-INTERACTION-ACCURACY-LOCK';
let scene,renderer,root,group,raycaster,hoverRing,last=performance.now();
const controllers=[],held=new Map(),state={build:BUILD,active:true,hover:null,held:null,lastRelease:null,lastSnap:null,zones:0,items:0};
function S(){return window.__SVR_SCENE__||null}function REND(){return window.__SVR_RENDERER__||null}function Root(){const s=S();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}
function T(){const r=Root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null}
function info(){const t=T();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{t,b,s,c,top:b.max.y,playY:b.max.y-.152,halfX:Math.max(1.2,s.x*.5),halfZ:Math.max(.75,s.z*.5)}}
function items(){const arr=[];Root()?.traverse?.(o=>{const n=String(o.name||'');if(/^P89_(CARD|CHIP|COMM)/.test(n)||o.userData?.grab){if(o.isMesh&&o.visible)arr.push(o)}});state.items=arr.length;return arr}
function makeText(txt){const c=document.createElement('canvas');c.width=420;c.height=90;const g=c.getContext('2d');g.fillStyle='rgba(0,0,0,.55)';g.fillRect(0,0,420,90);g.strokeStyle='#7ffcff';g.lineWidth=3;g.strokeRect(4,4,412,82);g.fillStyle='#fff';g.font='800 22px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(txt,210,45,390);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function buildZones(){const i=info();if(!i||group)return;group=new THREE.Group();group.name='PHASE91_INTERACTION_ACCURACY_ROOT';Root().add(group);const zmat=new THREE.MeshBasicMaterial({color:0x7ffcff,transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false});const cmat=new THREE.MeshBasicMaterial({color:0xffd98a,transparent:true,opacity:.18,side:THREE.DoubleSide,depthWrite:false});const cx=i.c.x,cz=i.c.z,y=i.playY+.018;const chipPts=[[0,i.halfZ*.55],[-i.halfX*.42,i.halfZ*.25],[-i.halfX*.42,-i.halfZ*.18],[0,-i.halfZ*.48],[i.halfX*.42,-i.halfZ*.18],[i.halfX*.42,i.halfZ*.25]];chipPts.forEach((p,idx)=>{const m=new THREE.Mesh(new THREE.RingGeometry(.08,.105,32),zmat.clone());m.name='P91_CHIP_STACK_ZONE_'+idx;m.userData.snap='chip';m.position.set(cx+p[0],y,cz+p[1]);m.rotation.x=-Math.PI/2;group.add(m)});for(let k=0;k<5;k++){const m=new THREE.Mesh(new THREE.PlaneGeometry(.26,.36),cmat.clone());m.name='P91_CARD_BOARD_ZONE_'+k;m.userData.snap='card';m.position.set(cx+(k-2)*.28,y+.006,cz-i.halfZ*.12);m.rotation.x=-Math.PI/2;group.add(m)}const pz=cz+i.halfZ*.42;for(let k=0;k<2;k++){const m=new THREE.Mesh(new THREE.PlaneGeometry(.26,.36),cmat.clone());m.name='P91_PLAYER_CARD_ZONE_'+k;m.userData.snap='card';m.position.set(cx+(k-.5)*.30,y+.006,pz);m.rotation.x=-Math.PI/2;group.add(m)}const label=new THREE.Mesh(new THREE.PlaneGeometry(1.35,.28),new THREE.MeshBasicMaterial({map:makeText('GRAB / RELEASE / SNAP TEST'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));label.name='P91_TABLE_LABEL';label.position.set(cx,i.top+.22,cz-i.halfZ*.72);label.rotation.x=-.22;group.add(label);state.zones=13}
function nearestZone(obj){let best=null,bd=Infinity;const p=new THREE.Vector3();obj.getWorldPosition(p);group?.traverse?.(z=>{if(!z.userData?.snap)return;if((obj.userData.kind==='chip'&&z.userData.snap!=='chip')||(obj.userData.kind==='card'&&z.userData.snap!=='card'))return;const zp=new THREE.Vector3();z.getWorldPosition(zp);const d=zp.distanceTo(p);if(d<bd){bd=d;best=z}});return{zone:best,d:bd}}
function snap(obj){const i=info();if(!i||!obj)return;const nz=nearestZone(obj);const kind=obj.userData.kind||(/CHIP/i.test(obj.name)?'chip':'card');const baseY=i.playY+(kind==='chip'?.012:.008);if(nz.zone&&nz.d<(kind==='chip'?.38:.42)){const p=new THREE.Vector3();nz.zone.getWorldPosition(p);obj.position.set(p.x,baseY,p.z);state.lastSnap=nz.zone.name}else{obj.position.y=baseY;obj.position.x=Math.max(i.c.x-i.halfX*.74,Math.min(i.c.x+i.halfX*.74,obj.position.x));obj.position.z=Math.max(i.c.z-i.halfZ*.74,Math.min(i.c.z+i.halfZ*.74,obj.position.z));state.lastSnap='surface'}if(kind==='card'){obj.rotation.x=0;obj.rotation.z=Math.round(obj.rotation.z/(Math.PI/2))*(Math.PI/2)}if(kind==='chip'){obj.scale.setScalar(.82)}obj.userData.v?.set?.(0,0,0)}
function ensureHover(){if(hoverRing)return;hoverRing=new THREE.Mesh(new THREE.SphereGeometry(.085,16,10),new THREE.MeshBasicMaterial({color:0x7ffcff,transparent:true,opacity:.38,wireframe:true,depthWrite:false}));hoverRing.name='P91_GRAB_HIGHLIGHT';hoverRing.visible=false;Root()?.add(hoverRing)}
function rayPick(ctrl){raycaster=raycaster||new THREE.Raycaster();const tempMatrix=new THREE.Matrix4();tempMatrix.identity().extractRotation(ctrl.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(ctrl.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(tempMatrix);raycaster.far=.65;const hits=raycaster.intersectObjects(items(),true);return hits[0]?.object||null}
function nearPick(ctrl){const p=new THREE.Vector3();ctrl.getWorldPosition(p);let best=null,bd=.26;for(const o of items()){const q=new THREE.Vector3();o.getWorldPosition(q);const d=p.distanceTo(q);if(d<bd){bd=d;best=o}}return best}
function pick(ctrl){return rayPick(ctrl)||nearPick(ctrl)}
function start(ctrl){const obj=pick(ctrl);if(!obj)return;Root().attach(obj);ctrl.attach(obj);obj.userData.grabbed=true;obj.userData.v=new THREE.Vector3();held.set(ctrl,{obj,last:new THREE.Vector3(),prev:new THREE.Vector3()});ctrl.getWorldPosition(held.get(ctrl).last);held.get(ctrl).prev.copy(held.get(ctrl).last);state.held=obj.name;state.hover=obj.name}
function end(ctrl){const h=held.get(ctrl);if(!h)return;Root().attach(h.obj);h.obj.userData.grabbed=false;const vel=h.last.clone().sub(h.prev).multiplyScalar(4.5);h.obj.userData.v=vel;snap(h.obj);state.lastRelease=h.obj.name;state.held=null;held.delete(ctrl)}
function setupControllers(){if(!renderer?.xr||controllers.length)return;for(let i=0;i<2;i++){const c=renderer.xr.getController(i);c.name='P91_PRECISION_CONTROLLER_'+i;scene.add(c);c.addEventListener('selectstart',()=>start(c));c.addEventListener('selectend',()=>end(c));c.addEventListener('squeezestart',()=>start(c));c.addEventListener('squeezeend',()=>end(c));controllers.push(c)}}
function hover(){ensureHover();let obj=null;for(const c of controllers){if(held.has(c))continue;obj=pick(c);if(obj)break}if(obj){const p=new THREE.Vector3();obj.getWorldPosition(p);hoverRing.position.copy(p);hoverRing.visible=true;state.hover=obj.name}else{hoverRing.visible=false;state.hover=null}}
function update(dt){buildZones();setupControllers();for(const h of held.values()){h.prev.copy(h.last);h.obj.parent?.getWorldPosition?.(h.last)}hover();for(const o of items()){if(o.userData.grabbed)continue;if(o.userData.v&&o.userData.v.lengthSq()>.00001){o.position.addScaledVector(o.userData.v,dt);o.userData.v.multiplyScalar(.88);if(o.userData.v.length()<.015)snap(o)}else{const i=info();if(i){const base=i.playY+(o.userData.kind==='chip'?.012:.008);if(Math.abs(o.position.y-base)>.02)o.position.y=base}}}window.SVR_PHASE91_INTERACTION=state;window.SVR_LOCKED_FINAL_BUILD=BUILD;window.SVR_LIVE_BUILD_POINTER=BUILD}
function loop(){const now=performance.now();const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);requestAnimationFrame(loop)}
function install(){scene=S();renderer=REND();root=Root();if(!scene||!renderer||!root)return setTimeout(install,300);buildZones();setupControllers();ensureHover();window.SVR_RUN_PHASE91_INTERACTION_AUDIT=()=>({...state,items:items().map(o=>({name:o.name,kind:o.userData.kind,pos:o.position.toArray().map(v=>+v.toFixed(3))})),checkedAt:new Date().toISOString()});loop()}
install();
