import * as THREE from 'three';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
const BUILD='PHASE-92-TABLE-SCALE-NPC-CALIBRATION-LOCK';
let scene,root,table,group,cal={surfaceOffset:.152,seatEye:1.18,mode:'SITTING'},ericTried=false;
function S(){return window.__SVR_SCENE__||null}function Root(){const s=S();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}
function T(){const r=Root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null}
function info(){const t=T();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{t,b,s,c,top:b.max.y,playY:b.max.y-cal.surfaceOffset,halfX:Math.max(1.2,s.x*.5),halfZ:Math.max(.75,s.z*.5)}}
function mat(c,r=.72,m=.08){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m,side:THREE.DoubleSide})}
function box(n,w,h,d,c){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));o.name=n;return o}
function cyl(n,r,h,c){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,32),mat(c));o.name=n;return o}
function chair(name,x,z,rot=0){const g=new THREE.Group();g.name=name;g.position.set(x,0,z);g.rotation.y=rot;const seat=box(name+'_SEAT',.46,.08,.42,0x1b0a10);seat.position.y=.42;g.add(seat);const back=box(name+'_BACK',.46,.58,.08,0x1b0a10);back.position.set(0,.75,.18);g.add(back);const cushion=box(name+'_CUSHION',.38,.035,.34,0x3b0712);cushion.position.y=.48;g.add(cushion);for(const sx of[-.17,.17])for(const sz of[-.15,.15]){const leg=cyl(name+'_LEG',.025,.42,0x0b0708);leg.position.set(sx,.21,sz);g.add(leg)}group.add(g);return g}
function npc(name,x,z,rot=0,color=0x2e8cff){const g=new THREE.Group();g.name=name;g.position.set(x,0,z);g.rotation.y=rot;const pelvis=box(name+'_BODY',.34,.55,.22,color);pelvis.position.y=.82;g.add(pelvis);const head=new THREE.Mesh(new THREE.SphereGeometry(.13,24,16),mat(0xc48b6a,.65,.02));head.name=name+'_HEAD';head.position.y=1.2;g.add(head);const neck=cyl(name+'_NECK',.055,.08,0xc48b6a);neck.position.y=1.06;g.add(neck);for(const sx of[-.23,.23]){const arm=cyl(name+'_ARM',.035,.42,0xc48b6a);arm.rotation.z=Math.PI/2;arm.position.set(sx,.93,-.03);g.add(arm);const hand=new THREE.Mesh(new THREE.SphereGeometry(.045,16,10),mat(0xc48b6a,.65,.02));hand.position.set(sx*1.52,.93,-.03);g.add(hand)}for(const sx of[-.08,.08]){const leg=cyl(name+'_LEG',.045,.45,0x101019);leg.position.set(sx,.45,.04);g.add(leg)}group.add(g);return g}
function makeText(text,w=512,h=160){const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');g.fillStyle='rgba(0,0,0,.65)';g.fillRect(0,0,w,h);g.strokeStyle='#7ffcff';g.lineWidth=4;g.strokeRect(6,6,w-12,h-12);g.fillStyle='#fff';g.font='800 28px system-ui';g.textAlign='center';g.textBaseline='middle';const lines=String(text).split('\n');lines.forEach((l,i)=>g.fillText(l,w/2,h/2+(i-(lines.length-1)/2)*34,w-40));const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;return tx}
function panel(){const i=info();if(!i)return;const p=new THREE.Mesh(new THREE.PlaneGeometry(1.35,.42),new THREE.MeshBasicMaterial({map:makeText(`TABLE CALIBRATION\nSurface ${i.playY.toFixed(3)}  Top ${i.top.toFixed(3)}\nOffset ${(cal.surfaceOffset*39.37).toFixed(1)} in`),transparent:true,depthWrite:false,side:THREE.DoubleSide}));p.name='P92_CALIBRATION_PANEL';p.position.set(i.c.x,i.top+.65,i.c.z+i.halfZ*.95);p.rotation.x=-.2;group.add(p)}
function ruler(){const i=info();if(!i)return;const x=i.c.x-i.halfX*.88,z=i.c.z+i.halfZ*.88;const line=new THREE.Mesh(new THREE.BoxGeometry(.018,1.5,.018),mat(0x7ffcff,.45,.2));line.name='P92_VERTICAL_RULER';line.position.set(x,.75,z);group.add(line);for(let k=0;k<=6;k++){const y=k*.25;const tick=new THREE.Mesh(new THREE.BoxGeometry(.18,.012,.012),mat(0xffd98a,.4,.3));tick.name='P92_RULER_TICK_'+k;tick.position.set(x,y,z);group.add(tick);const lab=new THREE.Mesh(new THREE.PlaneGeometry(.28,.08),new THREE.MeshBasicMaterial({map:makeText(`${y.toFixed(2)}m`,256,90),transparent:true,depthWrite:false,side:THREE.DoubleSide}));lab.name='P92_RULER_LABEL_'+k;lab.position.set(x+.28,y,z);lab.rotation.y=-.35;group.add(lab)}const surf=new THREE.Mesh(new THREE.BoxGeometry(i.halfX*1.5,.012,i.halfZ*1.18),new THREE.MeshBasicMaterial({color:0x00ffff,transparent:true,opacity:.18,depthWrite:false,side:THREE.DoubleSide}));surf.name='P92_MEASURED_INNER_PLAY_SURFACE';surf.position.set(i.c.x,i.playY,i.c.z);group.add(surf)}
function leatherRail(){const i=info();if(!i)return;const rail=new THREE.Mesh(new THREE.TorusGeometry(Math.max(i.halfX*.74,i.halfZ*.65),.055,18,128),mat(0x26070d,.68,.22));rail.name='P92_DARK_LEATHER_HAND_REST_REFERENCE';rail.scale.z=i.halfZ/i.halfX*.82;rail.rotation.x=Math.PI/2;rail.position.set(i.c.x,i.top+.012,i.c.z);group.add(rail)}
async function tryEric(){if(ericTried)return;ericTried=true;const i=info();if(!i)return;try{const fbx=await new Promise((res,rej)=>new FBXLoader().load('./assets/eric.fbx',res,undefined,rej));fbx.name='ERIC_NPC_FBX_FAR_SIDE';fbx.scale.setScalar(.01);fbx.position.set(i.c.x,0,i.c.z-i.halfZ*.98);fbx.rotation.y=Math.PI;group.add(fbx)}catch(e){npc('ERIC_NPC_FALLBACK_FAR_SIDE',i.c.x,i.c.z-i.halfZ*.98,0,0x2e8cff)}}
function build(){scene=S();root=Root();table=T();if(!scene||!root||!table)return false;if(group)group.parent?.remove(group);group=new THREE.Group();group.name='PHASE92_SCALE_NPC_CALIBRATION_ROOT';root.add(group);const i=info();if(!i)return false;table.position.set(0,0,0);table.updateMatrixWorld(true);table.userData.worldLocked=true;leatherRail();ruler();panel();const cx=i.c.x,cz=i.c.z;chair('P92_PLAYER_CHAIR',cx,cz+i.halfZ*1.08,Math.PI);chair('P92_FAR_CHAIR',cx,cz-i.halfZ*1.08,0);chair('P92_LEFT_CHAIR',cx-i.halfX*1.05,cz,Math.PI/2);chair('P92_RIGHT_CHAIR',cx+i.halfX*1.05,cz,-Math.PI/2);npc('NPC_LEFT_PLAYER',cx-i.halfX*.92,cz,Math.PI/2,0x7a39ff);npc('NPC_RIGHT_PLAYER',cx+i.halfX*.92,cz,-Math.PI/2,0xff3d66);tryEric();window.SVR_PHASE92_CALIBRATION={build:BUILD,active:true,mode:cal.mode,surfaceOffset:cal.surfaceOffset,tableTop:i.top,playY:i.playY,worldLocked:true,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;window.SVR_LIVE_BUILD_POINTER=BUILD;return true}
function setSurface(v){cal.surfaceOffset=Math.max(.03,Math.min(.38,v));build();snap()}
function snap(){const i=info();if(!i)return;root?.traverse?.(o=>{const n=String(o.name||'');if(/^P89_(CARD|CHIP|COMM)/.test(n)){o.position.y=i.playY+(o.userData.kind==='chip'?.012:.008);o.userData.surfaceY=i.playY}})}
function install(){if(!build())return setTimeout(install,300);window.SVR_P92_SURFACE_UP=()=>setSurface(cal.surfaceOffset-.025);window.SVR_P92_SURFACE_DOWN=()=>setSurface(cal.surfaceOffset+.025);window.SVR_P92_SET_SURFACE_OFFSET_INCHES=(v)=>setSurface(Number(v)/39.37);window.SVR_RUN_PHASE92_CALIBRATION_AUDIT=()=>{build();return window.SVR_PHASE92_CALIBRATION};setInterval(snap,500)}
install();
