import * as THREE from 'three';
const BUILD='PHASE-93-HARD-VISIBLE-CALIBRATION-LOCK';
let scene,root,table,group,offset=.152;
function S(){return window.__SVR_SCENE__||null}function Root(){const s=S();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}function T(){const r=Root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('P93_WORLD_LOCKED_TABLE')||null}
function info(){const t=T();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c,top:b.max.y,playY:b.max.y-offset,halfX:Math.max(1.25,s.x*.5),halfZ:Math.max(.75,s.z*.5)}}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.7,metalness:.08,side:THREE.DoubleSide})}
function makeLabel(text){const c=document.createElement('canvas');c.width=768;c.height=180;const g=c.getContext('2d');g.fillStyle='rgba(0,0,0,.8)';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#00ffff';g.lineWidth=8;g.strokeRect(8,8,c.width-16,c.height-16);g.fillStyle='#fff';g.font='900 40px system-ui';g.textAlign='center';g.textBaseline='middle';String(text).split('\n').forEach((l,i,a)=>g.fillText(l,c.width/2,c.height/2+(i-(a.length-1)/2)*48,c.width-40));const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;return tx}
function label(name,text,x,y,z,w=1.6,h=.38){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:makeLabel(text),transparent:true,depthWrite:false,side:THREE.DoubleSide}));p.name=name;p.position.set(x,y,z);p.rotation.x=-.16;group.add(p);return p}
function box(name,x,y,z,w,h,d,color,op=.65){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshBasicMaterial({color,transparent:true,opacity:op,depthWrite:false,side:THREE.DoubleSide}));m.name=name;m.position.set(x,y,z);group.add(m);return m}
function solidBox(name,x,y,z,w,h,d,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.name=name;m.position.set(x,y,z);group.add(m);return m}
function cyl(name,x,y,z,r,h,color){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,32),mat(color));m.name=name;m.position.set(x,y,z);group.add(m);return m}
function chair(name,x,z,rot,color){const g=new THREE.Group();g.name=name;g.position.set(x,0,z);g.rotation.y=rot;group.add(g);const s=new THREE.Mesh(new THREE.BoxGeometry(.5,.08,.42),mat(color));s.position.y=.42;g.add(s);const b=new THREE.Mesh(new THREE.BoxGeometry(.5,.55,.08),mat(color));b.position.set(0,.72,.18);g.add(b);return g}
function npc(name,x,z,rot,color){const g=new THREE.Group();g.name=name;g.position.set(x,0,z);g.rotation.y=rot;group.add(g);const body=new THREE.Mesh(new THREE.BoxGeometry(.36,.56,.24),mat(color));body.position.y=.82;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.14,24,16),mat(0xc28b6b));head.position.y=1.22;g.add(head);return g}
function rebuild(){scene=S();root=Root();table=T();if(!scene||!root||!table)return false;if(group)group.parent?.remove(group);group=new THREE.Group();group.name='PHASE93_HARD_VISIBLE_MARKERS';root.add(group);const i=info();if(!i)return false;table.position.set(0,0,0);table.userData.worldLocked=true;box('P93_BRIGHT_CYAN_MEASURED_FELT',i.c.x,i.playY,i.c.z,i.halfX*1.35,.02,i.halfZ*1.16,0x00ffff,.48);box('P93_RED_HANDREST_TOP_REFERENCE',i.c.x,i.top+.018,i.c.z,i.halfX*1.72,.04,i.halfZ*1.42,0xff0033,.28);label('P93_ACTIVE_LABEL','PHASE 93 ACTIVE\nYOU MUST SEE NPCS / CHAIRS / RULER',i.c.x,i.top+.9,i.c.z-i.halfZ*.95,2.2,.48);label('P93_LOCK_LABEL','TABLE WORLD LOCKED\nCYAN = MEASURED FELT',i.c.x,i.top+.52,i.c.z+i.halfZ*1.02,1.8,.38);chair('P93_PLAYER_BLUE_CHAIR',i.c.x,i.c.z+i.halfZ*1.12,Math.PI,0x123a68);chair('P93_FAR_RED_CHAIR',i.c.x,i.c.z-i.halfZ*1.12,0,0x651323);chair('P93_LEFT_PURPLE_CHAIR',i.c.x-i.halfX*1.08,i.c.z,Math.PI/2,0x301465);chair('P93_RIGHT_GREEN_CHAIR',i.c.x+i.halfX*1.08,i.c.z,-Math.PI/2,0x144f34);npc('ERIC_FALLBACK_BIG_BLUE_NPC',i.c.x,i.c.z-i.halfZ*1.0,0,0x2f8cff);npc('LEFT_NPC_PURPLE',i.c.x-i.halfX*.92,i.c.z,Math.PI/2,0x7a39ff);npc('RIGHT_NPC_RED',i.c.x+i.halfX*.92,i.c.z,-Math.PI/2,0xff3d66);const rx=i.c.x-i.halfX*.98,rz=i.c.z+i.halfZ*.94;box('P93_TALL_BLUE_RULER',rx,.75,rz,.025,1.5,.025,0x00ffff,1);for(let k=0;k<=6;k++){box('P93_RULER_TICK_'+k,rx,k*.25,rz,.25,.015,.015,0xffd98a,1)}for(let k=0;k<5;k++){solidBox('P93_CARD_ON_CYAN_FELT_'+k,i.c.x+(k-2)*.25,i.playY+.018,i.c.z-.12,.2,.012,.3,0xffffff)}for(let s=0;s<6;s++){const a=s/6*Math.PI*2+Math.PI/2,x=i.c.x+Math.cos(a)*i.halfX*.46,z=i.c.z+Math.sin(a)*i.halfZ*.46;for(let k=0;k<5;k++)cyl('P93_SMALL_CHIP_'+s+'_'+k,x,i.playY+.018+k*.012,z,.032,.01,[0xff3d66,0x00ffff,0xffd98a,0x7a39ff,0xffffff,0x33ff99][s])}window.SVR_PHASE93_CALIBRATION={build:BUILD,active:true,tableTop:+i.top.toFixed(3),feltY:+i.playY.toFixed(3),offsetInches:+(offset*39.37).toFixed(2),worldLocked:true,markers:group.children.length,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=BUILD;window.SVR_LIVE_BUILD_POINTER=BUILD;return true}
function setOffsetInches(v){offset=Number(v)/39.37;rebuild();return window.SVR_PHASE93_CALIBRATION}
function install(){if(!rebuild())return setTimeout(install,350);window.SVR_RUN_PHASE93_AUDIT=()=>{rebuild();return window.SVR_PHASE93_CALIBRATION};window.SVR_P93_FELT_UP=()=>setOffsetInches((offset*39.37)-1);window.SVR_P93_FELT_DOWN=()=>setOffsetInches((offset*39.37)+1);window.SVR_P93_SET_FELT_OFFSET_INCHES=setOffsetInches}
install();
