import * as THREE from "three";
const BUILD="PHASE-328-DIRECTOR-PREVIEW-TABLE-SHOWCASE-LOCK";
const params=new URLSearchParams(location.search);
const isDirector=window.self!==window.top||params.has("preview")||params.has("embed")||params.get("cam")==="director"||params.has("autocam");
const ua=navigator.userAgent||"";
const isQuest=/Quest|Oculus|Meta Quest/i.test(ua);
const isAndroid=(/Android/i.test(ua)&&!isQuest)||/\/game\/android\.html$/i.test(location.pathname)||params.get("channel")==="stable";
let installed=false,logoRoot=null,orbitOn=false;
function scene(){return window.__SVR_SCENE__||null}
function camera(){return window.__SVR_CAMERA__||null}
function renderer(){return window.__SVR_RENDERER__||null}
function root(){const s=scene();return s?.getObjectByName?.("PHASE200_ORDERED_GRAND_LOBBY_ROOT")||s}
function table(){const r=root();if(!r)return null;return r.getObjectByName?.("PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED")||r.getObjectByName?.("PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT")||r.getObjectByName?.("PHASE326_ANDROID_TABLE_FALLBACK")||null}
function tableBox(){const t=table();if(!t)return null;t.visible=true;t.traverse?.(o=>{o.visible=true});t.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(t);const center=new THREE.Vector3(),size=new THREE.Vector3();box.getCenter(center);box.getSize(size);return{obj:t,box,center,size,top:box.max.y}}
function cleanDom(){if(document.getElementById("svr-phase328-style"))return;const st=document.createElement("style");st.id="svr-phase328-style";st.textContent=`body.svr-phase328-director #hud,body.svr-phase328-director #sceneNav,body.svr-phase328-director #log,body.svr-phase328-director #err,body.svr-phase328-director #safeStage,body.svr-phase328-director #bootFallback,body.svr-phase328-director #svrPhaseBadge,body.svr-phase328-director .phase-label,body.svr-phase328-director #svr326Root,body.svr-phase328-director #svrAndroidGamePad,body.svr-phase328-director #svr327ReleaseBadge{display:none!important;opacity:0!important;visibility:hidden!important;pointer-events:none!important}body.svr-phase328-director canvas{display:block!important;visibility:visible!important;opacity:1!important;background:#02040b!important}#svr328PreviewBadge{position:fixed;left:12px;bottom:12px;z-index:999999;border:1px solid rgba(255,217,138,.52);border-radius:999px;background:rgba(0,0,0,.42);color:#fff;padding:7px 11px;font:900 11px system-ui;letter-spacing:.08em;pointer-events:none}`;document.head.appendChild(st)}
function hideSceneOverlays(){const s=scene();let hidden=0;if(!s)return hidden;const block=/(HUD|STATUS|BADGE|HITBOX|RAYCAST|FEEDBACK|TIMER|PANEL|MARKER|ANDROID.*ROOT|CONTROL)/i;s.traverse(o=>{if(o===logoRoot)return;const n=String(o.name||"");if(block.test(n)&&!/PHASE328/i.test(n)&&!/TABLE|CARD|CHIP|POT|FELT|LOGO/i.test(n)){o.visible=false;hidden++;}});return hidden}
function logoTexture(){const c=document.createElement("canvas");c.width=1024;c.height=1024;const x=c.getContext("2d");x.clearRect(0,0,1024,1024);const g=x.createRadialGradient(512,512,90,512,512,500);g.addColorStop(0,"rgba(255,217,138,.94)");g.addColorStop(.32,"rgba(127,252,255,.34)");g.addColorStop(.78,"rgba(0,0,0,.08)");g.addColorStop(1,"rgba(0,0,0,0)");x.fillStyle=g;x.beginPath();x.arc(512,512,500,0,Math.PI*2);x.fill();x.strokeStyle="rgba(255,217,138,.94)";x.lineWidth=24;x.beginPath();x.arc(512,512,392,0,Math.PI*2);x.stroke();x.strokeStyle="rgba(127,252,255,.76)";x.lineWidth=12;x.beginPath();x.arc(512,512,286,0,Math.PI*2);x.stroke();x.fillStyle="#fff6ce";x.textAlign="center";x.textBaseline="middle";x.font="900 138px system-ui,Arial";x.fillText("SVR",512,460);x.font="900 62px system-ui,Arial";x.fillText("POKER",512,570);x.fillStyle="rgba(255,255,255,.86)";x.font="800 30px system-ui,Arial";x.fillText("TABLE PREVIEW",512,638);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=1;return t}
function placeLogo(){const r=tableBox(),b=root();if(!r||!b)return false;if(logoRoot)logoRoot.parent?.remove(logoRoot);logoRoot=new THREE.Group();logoRoot.name="PHASE328_DIRECTOR_TABLE_LOGO_ROOT";b.add(logoRoot);const w=Math.max(1.25,Math.min(r.size.x*.46,2.15));const h=Math.max(.72,Math.min(r.size.z*.32,1.24));const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:logoTexture(),transparent:true,side:THREE.DoubleSide,depthWrite:false,depthTest:true}));m.name="PHASE328_SURFACE_SVR_TABLE_LOGO";m.position.set(r.center.x,r.top+.034,r.center.z);m.rotation.x=-Math.PI/2;m.renderOrder=3280;logoRoot.add(m);return true}
function lights(){const s=scene();if(!s||s.getObjectByName("PHASE328_PREVIEW_LIGHTS"))return;const g=new THREE.Group();g.name="PHASE328_PREVIEW_LIGHTS";s.add(g);const h=new THREE.HemisphereLight(0xe7f7ff,0x090912,1.05);g.add(h);[[0,6,4,0xffd98a,1.25],[-4,5,-3,0x7ffcff,.82],[4,5,-3,0xa77cff,.78],[0,5,-7,0xffffff,.68]].forEach((v,i)=>{const l=new THREE.PointLight(v[3],v[4],24,2);l.name="PHASE328_PREVIEW_LIGHT_"+i;l.position.set(v[0],v[1],v[2]);g.add(l)});}
function orbit(){if(!isDirector||orbitOn)return;orbitOn=true;const loop=(now)=>{const c=camera(),r=tableBox();if(c&&r){const a=now*.00016,rad=Math.max(3.2,Math.min(5.2,Math.max(r.size.x,r.size.z)*1.28));const y=r.top+1.55+Math.sin(now*.00023)*.16;c.position.set(r.center.x+Math.sin(a)*rad,y,r.center.z+Math.cos(a)*rad);c.lookAt(r.center.x,r.top+.25,r.center.z);c.updateProjectionMatrix?.();}requestAnimationFrame(loop)};requestAnimationFrame(loop)}
function publish(action="ready"){window.SVR_PHASE328_PREVIEW={build:BUILD,active:true,director:isDirector,android:isAndroid,tableLogo:!!logoRoot,apkUpdatePolicy:{forceUpdate:false,showUpdatePrompt:false,webEntry:"/game/android.html?channel=stable"},action,checkedAt:new Date().toISOString()};return window.SVR_PHASE328_PREVIEW}
function install(){if(installed)return;installed=true;if(isDirector){document.body.classList.add("svr-phase328-director");cleanDom();let b=document.getElementById("svr328PreviewBadge");if(!b){b=document.createElement("div");b.id="svr328PreviewBadge";document.body.appendChild(b)}b.textContent="SVR DIRECTOR PREVIEW • CLEAN TABLE VIEW";}if(isAndroid){window.SVR_ANDROID_APK_RELEASE_POLICY={forceUpdate:false,showUpdatePrompt:false,stableWebEntry:"/game/android.html?channel=stable",nextApkDrop:"after approved Android playtest batch"};}const tick=()=>{lights();placeLogo();const hidden=isDirector?hideSceneOverlays():0;publish("tick hidden="+hidden);};setTimeout(tick,700);setTimeout(tick,1600);setInterval(tick,5200);orbit();publish("installed")}
window.SVR_RUN_DIRECTOR_PREVIEW_POLISH=()=>{installed=false;install();return publish("manual")};setTimeout(install,650);setTimeout(install,2200);