import * as THREE from 'three';

export const BUILD = 'PHASE-342-ADAPTIVE-PERFORMANCE-ASSET-PIPELINE-LOCK';

const BUDGETS = Object.freeze({
  android: Object.freeze({ targetFps: 45, minRatio: 0.68, startRatio: 0.92, maxRatio: 1.05, drawCalls: 260, triangles: 360000, geometries: 950, textures: 96, programs: 64, anisotropy: 2, sampleFrames: 90 }),
  quest: Object.freeze({ targetFps: 72, minRatio: 0.72, startRatio: 0.92, maxRatio: 1.15, drawCalls: 230, triangles: 320000, geometries: 850, textures: 88, programs: 60, anisotropy: 2, sampleFrames: 120 }),
  desktop: Object.freeze({ targetFps: 60, minRatio: 1.0, startRatio: 1.25, maxRatio: 1.75, drawCalls: 560, triangles: 950000, geometries: 1600, textures: 180, programs: 110, anisotropy: 6, sampleFrames: 120 }),
  camera3: Object.freeze({ targetFps: 30, minRatio: 0.65, startRatio: 0.82, maxRatio: 1.0, drawCalls: 150, triangles: 200000, geometries: 650, textures: 72, programs: 48, anisotropy: 1, sampleFrames: 75 })
});

const OPTIONAL_NOISE = /(DEBUG|HELPER|JOINT|HITBOX|RAYCAST|FEEDBACK|DIAGNOSTIC|CALIBRATION|BOUNDS|WIREFRAME)/i;
const CAMERA3_NOISE = /(PORTAL|STOREFRONT|BUILDING|SKY|MOON|MARS|WATCH|HUD|PANEL|BADGE|CONTROL|TELEPORT)/i;
const state = { build: BUILD, active: false, platform: null, budget: null, ratio: null, quality: 'balanced', frames: [], samples: [], overBudgetStrikes: 0, healthyWindows: 0, hiddenOptional: new Set(), materialCount: 0, textureCount: 0, startedAt: null, lastAdjustAt: 0, lastFrameAt: 0, raf: 0, paused: false };

function platform(){ return String(window.SVR_PLATFORM || document.body?.dataset?.platform || 'desktop').toLowerCase(); }
function renderer(){ return window.__SVR_RENDERER__ || null; }
function scene(){ return window.__SVR_SCENE__ || null; }
function budgetFor(value = platform()){ return BUDGETS[value] || BUDGETS.desktop; }
function clamp(value, min, max){ return Math.max(min, Math.min(max, value)); }
function round(value, places = 2){ const p = 10 ** places; return Math.round(value * p) / p; }
function rendererInfo(){ const info = renderer()?.info; return info ? { calls:Number(info.render?.calls||0), triangles:Number(info.render?.triangles||0), lines:Number(info.render?.lines||0), points:Number(info.render?.points||0), geometries:Number(info.memory?.geometries||0), textures:Number(info.memory?.textures||0), programs:Number(info.programs?.length||0) } : null; }

function applyRatio(next, reason='manual'){
  const r=renderer(); if(!r||!state.budget)return false;
  const value=round(clamp(Number(next)||state.budget.startRatio,state.budget.minRatio,state.budget.maxRatio),2);
  if(Math.abs(value-Number(state.ratio||0))<.009)return false;
  try{
    if(!(r.xr?.isPresenting&&state.platform==='quest'))r.setPixelRatio(Math.min(window.devicePixelRatio||1,value));
    state.ratio=value; state.lastAdjustAt=performance.now(); state.lastAdjustReason=reason; document.body.dataset.svrQualityRatio=String(value);
    window.dispatchEvent(new CustomEvent('svr:quality-change',{detail:{build:BUILD,platform:state.platform,ratio:value,reason}}));
    return true;
  }catch(error){state.lastAdjustError=String(error?.message||error);return false;}
}
function tuneTexture(texture,anisotropy){if(!texture||texture.userData?.svr342Tuned)return false;texture.userData={...(texture.userData||{}),svr342Tuned:true};try{texture.anisotropy=Math.min(anisotropy,renderer()?.capabilities?.getMaxAnisotropy?.()||anisotropy);if('generateMipmaps'in texture)texture.generateMipmaps=true;texture.needsUpdate=true;}catch{}state.textureCount+=1;return true;}
function tuneMaterial(material,value){if(!material||material.userData?.svr342Tuned)return false;material.userData={...(material.userData||{}),svr342Tuned:true};if(['android','quest','camera3'].includes(value)&&'precision'in material)material.precision='mediump';if(value!=='desktop'){if('dithering'in material)material.dithering=false;if('fog'in material&&value==='camera3')material.fog=false;}for(const key of ['map','normalMap','roughnessMap','metalnessMap','emissiveMap','aoMap','alphaMap','lightMap'])tuneTexture(material[key],state.budget.anisotropy);material.needsUpdate=true;state.materialCount+=1;return true;}
function tuneScene(){const s=scene();if(!s||!state.budget)return{meshes:0,lights:0,hidden:0};let meshes=0,lights=0,hidden=0;s.traverse(object=>{const name=object?.name||'';if(object?.isMesh){meshes+=1;object.frustumCulled=true;object.castShadow=false;if(state.platform!=='desktop')object.receiveShadow=false;const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(material=>tuneMaterial(material,state.platform));if(OPTIONAL_NOISE.test(name)||(state.platform==='camera3'&&CAMERA3_NOISE.test(name))){if(object.visible)hidden+=1;object.visible=false;state.hiddenOptional.add(name||object.uuid);}}if(object?.isLight){lights+=1;object.castShadow=false;if(state.platform==='camera3'&&object.intensity>1.2)object.intensity=1.2;}});const r=renderer();if(r?.shadowMap&&state.platform!=='desktop')r.shadowMap.enabled=false;if(r)r.info.autoReset=true;return{meshes,lights,hidden};}
function applyQuestSessionSettings(){const r=renderer();if(!r?.xr||state.platform!=='quest')return false;try{if(!r.xr.isPresenting&&typeof r.xr.setFramebufferScaleFactor==='function')r.xr.setFramebufferScaleFactor(.82);if(typeof r.xr.setFoveation==='function')r.xr.setFoveation(1);return true;}catch(error){state.xrError=String(error?.message||error);return false;}}
async function prewarm(){const r=renderer(),s=scene(),camera=window.__SVR_CAMERA__;if(!r||!s||!camera)return{available:false,textures:0,compiled:false,method:'none'};let textures=0;try{s.traverse(object=>{const materials=Array.isArray(object?.material)?object.material:[object?.material];materials.filter(Boolean).forEach(material=>{for(const key of ['map','normalMap','roughnessMap','metalnessMap','emissiveMap','aoMap','alphaMap','lightMap']){const texture=material[key];if(texture&&textures<96){try{r.initTexture?.(texture);textures+=1;}catch{}}}});});}catch{}let compiled=false,method='none';try{if(typeof r.compileAsync==='function'){method='compileAsync';await Promise.race([r.compileAsync(s,camera),new Promise(resolve=>setTimeout(resolve,2200))]);compiled=true;}else if(typeof r.compile==='function'){method='compile';r.compile(s,camera);compiled=true;}}catch(error){state.prewarmError=String(error?.message||error);}state.prewarm={available:true,textures,compiled,method,at:new Date().toISOString()};return state.prewarm;}
function currentWindow(){const frames=state.frames;if(!frames.length)return{fps:0,avgMs:0,p95Ms:0};const sorted=[...frames].sort((a,b)=>a-b),avgMs=frames.reduce((sum,value)=>sum+value,0)/frames.length,p95Ms=sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))];return{fps:round(1000/Math.max(1,avgMs),1),avgMs:round(avgMs,1),p95Ms:round(p95Ms,1)};}
function evaluateWindow(){const stats=currentWindow(),info=rendererInfo(),b=state.budget;if(!b||!info)return;const frameFloor=b.targetFps*.86,rendererOver=info.calls>b.drawCalls||info.triangles>b.triangles||info.geometries>b.geometries||info.textures>b.textures||info.programs>b.programs,slow=stats.fps>0&&stats.fps<frameFloor,severe=stats.fps>0&&stats.fps<b.targetFps*.68;state.samples.push({at:new Date().toISOString(),...stats,renderer:info,ratio:state.ratio,over:rendererOver||slow});if(state.samples.length>24)state.samples.shift();if(rendererOver||slow){state.overBudgetStrikes+=severe?2:1;state.healthyWindows=0;}else{state.overBudgetStrikes=Math.max(0,state.overBudgetStrikes-1);state.healthyWindows+=1;}const now=performance.now();if(state.overBudgetStrikes>=2&&now-state.lastAdjustAt>2200){const drop=severe?.12:.08;if(applyRatio(state.ratio-drop,severe?'severe-frame-pressure':rendererOver?'renderer-budget':'frame-pressure'))state.quality=state.ratio<=b.minRatio+.05?'low':'adaptive';state.overBudgetStrikes=0;}else if(state.healthyWindows>=8&&now-state.lastAdjustAt>10000&&state.ratio<b.maxRatio){if(applyRatio(state.ratio+.05,'sustained-headroom'))state.quality='balanced';state.healthyWindows=0;}state.frames.length=0;}
function monitorFrame(now){if(!state.active)return;if(!state.paused&&state.lastFrameAt){const dt=Math.min(250,Math.max(1,now-state.lastFrameAt));state.frames.push(dt);if(state.frames.length>=state.budget.sampleFrames)evaluateWindow();}state.lastFrameAt=now;state.raf=requestAnimationFrame(monitorFrame);}
function setQuality(level='balanced'){const b=state.budget||budgetFor(),normalized=String(level).toLowerCase(),ratio=normalized==='low'?b.minRatio:normalized==='high'?b.maxRatio:b.startRatio;state.quality=['low','high'].includes(normalized)?normalized:'balanced';applyRatio(ratio,`quality-${state.quality}`);return audit();}
function audit(){const info=rendererInfo(),recent=state.samples[state.samples.length-1]||currentWindow(),b=state.budget||budgetFor(),result={build:BUILD,active:state.active,platform:state.platform,quality:state.quality,ratio:state.ratio,budget:{...b},frame:{fps:recent.fps||0,avgMs:recent.avgMs||0,p95Ms:recent.p95Ms||0},renderer:info,withinBudget:info?info.calls<=b.drawCalls&&info.triangles<=b.triangles&&info.geometries<=b.geometries&&info.textures<=b.textures&&info.programs<=b.programs:false,hiddenOptional:state.hiddenOptional.size,tunedMaterials:state.materialCount,tunedTextures:state.textureCount,prewarm:state.prewarm||null,recentSamples:state.samples.slice(-6),checkedAt:new Date().toISOString()};result.pass=result.active&&result.withinBudget;window.SVR_PHASE342_PERFORMANCE_STATE=result;return result;}
async function boot(){if(state.active)return state;state.active=true;state.platform=platform();state.budget=budgetFor(state.platform);state.ratio=state.budget.startRatio;state.startedAt=new Date().toISOString();tuneScene();applyRatio(state.budget.startRatio,'phase342-start');applyQuestSessionSettings();const existingPrewarm=window.SVR_PHASE340_PLATFORM_STATE?.prewarm;if(existingPrewarm?.available)state.prewarm={...existingPrewarm,reused:true};else await prewarm();window.__SVR_RENDERER__?.xr?.addEventListener?.('sessionstart',applyQuestSessionSettings);document.addEventListener('visibilitychange',()=>{state.paused=document.hidden;state.lastFrameAt=performance.now();});state.raf=requestAnimationFrame(monitorFrame);window.SVR_PHASE342_AUDIT=audit;window.SVR_PHASE342_SET_QUALITY=setQuality;window.SVR_PHASE342_LOW_MODE=()=>setQuality('low');window.SVR_PHASE342_HIGH_MODE=()=>setQuality('high');window.SVR_PHASE342_REPREWARM=prewarm;window.SVR_PHASE342_BUDGETS=BUDGETS;window.dispatchEvent(new CustomEvent('svr:phase342-ready',{detail:audit()}));return state;}
window.addEventListener('svr:platform-ready',()=>setTimeout(boot,0),{once:true});
[450,1100,2200].forEach(ms=>setTimeout(()=>{if(!state.active&&renderer()&&scene())boot();else if(state.active)tuneScene();},ms));
