/* PHASE-462-QUEST-PROFESSIONAL-TABLE-ROOM */
import * as THREE from 'three';
export const BUILD='PHASE-462-QUEST-PROFESSIONAL-TABLE-ROOM';
const q=new URLSearchParams(location.search),ACTIVE=q.get('platform')==='quest'||q.get('tableonly')==='1'||/Quest|Oculus|Meta Quest/i.test(navigator.userAgent||'');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const state={build:BUILD,active:ACTIVE,installed:false,environmentReady:false,seatReady:false,openPlayerSide:false,singleTable:false,singleEric:false,cardsAligned:0,exposure:0,lastError:null,checkedAt:null};
const box=new THREE.Box3(),center=new THREE.Vector3(),size=new THREE.Vector3(),dealerPosition=new THREE.Vector3(),dealerDirection=new THREE.Vector3(),playerDirection=new THREE.Vector3(),sideDirection=new THREE.Vector3();
let scene,renderer,camera,runtime,environment,timer=0,seated=false;
function visible(o){if(!o?.parent)return false;for(let p=o;p;p=p.parent)if(p.visible===false)return false;return true}
function metrics(){const table=runtime?.table?.table,dealer=runtime?.dealer?.group;if(!table||!dealer)return null;table.updateWorldMatrix?.(true,true);dealer.updateWorldMatrix?.(true,true);box.setFromObject(table,true);if(box.isEmpty())return null;box.getCenter(center);box.getSize(size);dealer.getWorldPosition(dealerPosition);dealerDirection.copy(dealerPosition).sub(center).setY(0);if(dealerDirection.lengthSq()<.0001)dealerDirection.set(0,0,1);dealerDirection.normalize();playerDirection.copy(dealerDirection).multiplyScalar(-1);sideDirection.set(dealerDirection.z,0,-dealerDirection.x).normalize();return{center:center.clone(),size:size.clone(),top:box.max.y,dealer:dealerDirection.clone(),player:playerDirection.clone(),side:sideDirection.clone()}}
function mat(color,{emissive=0,intensity=0,roughness=.78,metalness=.04}={}){return new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:intensity,roughness,metalness,side:THREE.DoubleSide})}
function cube(name,d,p,m,yaw=0){const mesh=new THREE.Mesh(new THREE.BoxGeometry(d.x,d.y,d.z),m);mesh.name=name;mesh.position.copy(p);mesh.rotation.y=yaw;mesh.castShadow=false;mesh.receiveShadow=false;environment.add(mesh);return mesh}
function hideOldShell(){const old=scene?.getObjectByName?.('PHASE453_DIRECT_TABLE_ROOM');if(!old)return 0;let n=0;for(const child of old.children||[])if(/FLOOR|WALL|ACCENT|AMBIENT|FILL/i.test(String(child.name||''))){child.visible=false;n++}return n}
function buildEnvironment(){const m=metrics();if(!m||environment?.parent)return environment;hideOldShell();environment=new THREE.Group();environment.name='PHASE462_PROFESSIONAL_TABLE_ROOM';environment.userData={svrPhase462Environment:true,build:BUILD};const yaw=Math.atan2(m.dealer.x,m.dealer.z),floor=mat(0x0c0d13,{roughness:.72,metalness:.14}),wall=mat(0x302b3b,{roughness:.82}),trim=mat(0x2a1839,{emissive:0x2b0b48,intensity:.32,roughness:.46,metalness:.22}),gold=mat(0x8e6b2e,{emissive:0x3c2406,intensity:.24,roughness:.38,metalness:.62}),neon=mat(0x8d58ff,{emissive:0x7135dc,intensity:.65,roughness:.28,metalness:.15});
 cube('PHASE462_FLOOR',new THREE.Vector3(8.4,.10,7),new THREE.Vector3(m.center.x,-.07,m.center.z),floor,yaw);const back=m.center.clone().addScaledVector(m.dealer,3.15).setY(1.65);cube('PHASE462_DEALER_BACKGROUND',new THREE.Vector3(8.4,3.3,.12),back,wall,yaw);cube('PHASE462_DEALER_HEADER',new THREE.Vector3(4.8,.42,.08),back.clone().addScaledVector(m.player,.08).setY(2.55),trim,yaw);cube('PHASE462_GOLD_TRIM',new THREE.Vector3(4.2,.045,.045),back.clone().addScaledVector(m.player,.135).setY(2.55),gold,yaw);
 for(const s of[-1,1]){const p=m.center.clone().addScaledVector(m.side,s*4.15).addScaledVector(m.dealer,.2).setY(1.55);cube(`PHASE462_SIDE_WALL_${s}`,new THREE.Vector3(.12,3.1,6.25),p,wall,yaw);cube(`PHASE462_SIDE_NEON_${s}`,new THREE.Vector3(.045,.035,4.4),p.clone().addScaledVector(m.side,-s*.075).setY(1.72),neon,yaw)}
 const halo=new THREE.Mesh(new THREE.TorusGeometry(1.18,.025,10,64),neon);halo.name='PHASE462_DEALER_BACKGROUND_HALO';halo.position.copy(back).addScaledVector(m.player,.1).setY(1.62);halo.rotation.set(0,yaw,0);environment.add(halo);
 const hemi=new THREE.HemisphereLight(0xffffff,0x37303d,1.35);hemi.name='PHASE462_SOFT_AMBIENT';const key=new THREE.SpotLight(0xfff1d6,3.2,9.5,Math.PI/4.3,.62,1.25);key.name='PHASE462_TABLE_KEY';key.position.copy(m.center).addScaledVector(m.side,2.25).addScaledVector(m.player,1.25).setY(3.25);key.target.position.copy(m.center).setY(m.top);const fill=new THREE.SpotLight(0xc9e8ff,1.8,8.5,Math.PI/4,.7,1.35);fill.name='PHASE462_TABLE_FILL';fill.position.copy(m.center).addScaledVector(m.side,-2).addScaledVector(m.player,.3).setY(2.65);fill.target.position.copy(m.center).setY(m.top+.1);const rim=new THREE.PointLight(0x9e68ff,.8,6.5,1.5);rim.name='PHASE462_DEALER_RIM';rim.position.copy(m.center).addScaledVector(m.dealer,1.55).setY(2.15);environment.add(hemi,key,key.target,fill,fill.target,rim);scene.add(environment);
 for (const name of ['QUEST_STARTUP_LIGHTING', 'PHASE438_APPROVED_DEALER_TABLE_LIGHT_RIG', 'PHASE460_QUEST_BRIGHT_PLAY_LIGHT_RIG']) {
   const previous = scene.getObjectByName(name);
   if (previous) previous.visible = false;
 }
 scene.background=new THREE.Color(0x100d17);state.environmentReady=true;state.openPlayerSide=true;return environment}
function seat(reason = 'guard') {
  window.SVR_PHASE446_SWEEP?.(reason);
  const result = window.SVR_PHASE446_QA?.();
  state.seatReady = Boolean(result?.seated && result?.pass);
  state.lastSeatReason = reason;
  return state.seatReady;
}
function count(rx){let n=0;scene?.traverse?.(o=>{if(visible(o)&&rx.test(String(o.name||'')))n++});return n}
// Card heights and movement belong to the calibrated surface and deal runtime.
// Never periodically reposition held cards or interrupt a dealing animation.
function qa(){return{...state,roomVisible:Boolean(environment?.parent&&environment.visible),pass:Boolean(state.installed&&state.openPlayerSide&&state.singleTable&&state.singleEric&&!state.lastError),checkedAt:new Date().toISOString()}}
function sweep(reason='guard'){if(!ACTIVE)return false;try{scene=window.__SVR_SCENE__||scene;renderer=window.__SVR_RENDERER__||renderer;camera=window.__SVR_CAMERA__||camera;runtime=window.SVR_LOBBY_DEALER_MODULE||window.SVR_APPROVED_DEALER_TABLE_MODULE||runtime;if(!scene||!runtime?.table?.table||!runtime?.dealer?.loaded)return false;hideOldShell();buildEnvironment();if(environment)environment.visible=true;if(renderer){renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.setClearColor?.(0x100d17,1);state.exposure=renderer.toneMappingExposure}runtime.table.group.visible=true;runtime.table.table.visible=true;runtime.dealer.group.visible=true;if(runtime.dealer.model)runtime.dealer.model.visible=true;runtime.dealer.groundToFloor?.(0);window.SVR_PHASE460_SWEEP?.(`phase462-${reason}`);state.singleTable=count(/PHASE438_APPROVED_LAB_TABLE_GLB/)===1;state.singleEric=count(/PHASE438_APPROVED_DEALER_CHARACTER_ROOT/)===1;state.installed=Boolean(state.environmentReady&&state.seatReady&&state.singleTable&&state.singleEric);state.lastError=null;state.checkedAt=new Date().toISOString();window.SVR_PHASE462_STATE={...state,reason};return qa()}catch(e){state.lastError=String(e?.stack||e?.message||e);state.checkedAt=new Date().toISOString();return false}}
async function install(){if(!ACTIVE)return false;const started=performance.now();while(performance.now()-started<30000){scene=window.__SVR_SCENE__;renderer=window.__SVR_RENDERER__;camera=window.__SVR_CAMERA__;runtime=window.SVR_LOBBY_DEALER_MODULE||window.SVR_APPROVED_DEALER_TABLE_MODULE;if(scene&&renderer&&camera&&runtime?.table?.table&&runtime?.dealer?.loaded)break;await wait(80)}buildEnvironment();seat('install',true);sweep('install');renderer?.xr?.addEventListener?.('sessionstart',()=>{seated=false;setTimeout(()=>{seat('xr-sessionstart',true);sweep('xr-sessionstart')},240)});renderer?.xr?.addEventListener?.('sessionend',()=>{seated=false;seat('xr-sessionend',true)});for(const d of[120,420,900,1800,3600])setTimeout(()=>{seat(`settle-${d}`,d<1000);sweep(`settle-${d}`)},d);if(!timer)timer=window.setInterval(()=>sweep('guard'),650);return qa()}
window.SVR_PHASE462_SWEEP=sweep;window.SVR_PHASE462_QA=qa;window.SVR_PHASE462_READY_PROMISE=install();addEventListener('beforeunload',()=>{if(timer)clearInterval(timer)},{once:true});
