/* PHASE-412-MOBILE-PROFESSIONAL-POLISH-LOCK */
const BUILD='PHASE-412-MOBILE-PROFESSIONAL-POLISH-LOCK';
const state={build:BUILD,installed:false,online:navigator.onLine,userDecision:false,actionFeedback:false,reducedMotion:matchMedia?.('(prefers-reduced-motion: reduce)')?.matches||false,lastAction:null,lastWinner:null,lastError:null};
const $=s=>document.querySelector(s);
function ensureConnection(){let el=$('#phase412Connection');if(!el){el=document.createElement('div');el.id='phase412Connection';el.innerHTML='<i></i><span></span>';document.body.appendChild(el)}state.online=navigator.onLine;el.classList.toggle('offline',!state.online);const match=window.SVR_PHASE399_MATCH_STATE;const live=Boolean(match?.authoritativeGame&&match?.matched);el.querySelector('span').textContent=state.online?(live?'LIVE PEER • CONNECTED':'PLAY-MONEY TEST • DEVICE ONLINE'):'OFFLINE • LOCAL TEST ONLY';return true}
function ensureDecisionLabel(){const strip=$('.turn-strip');if(!strip)return false;let el=$('#phase412DecisionLabel');if(!el){el=document.createElement('span');el.id='phase412DecisionLabel';strip.appendChild(el)}const game=window.SVR_PHASE393_ANDROID_STATE,user=Boolean(game&&game.activePlayer===0&&!game.handOver);state.userDecision=user;document.body.classList.toggle('phase412-user-decision',user);document.body.classList.toggle('phase412-bot-decision',Boolean(game&&game.activePlayer!==0&&!game.handOver));if(game?.handOver)el.textContent='HAND COMPLETE';else if(user)el.textContent='YOUR DECISION';else if(Number.isInteger(game?.activePlayer))el.textContent='OPPONENT THINKING';else el.textContent='TABLE READY';return true}
function polishActions(){const buttons=[...document.querySelectorAll('.actions button[data-a]')];if(!buttons.length)return false;for(const button of buttons){if(button.dataset.phase412)return true;button.dataset.phase412='1';button.setAttribute('aria-live','off');button.addEventListener('pointerdown',()=>{if(button.disabled)return;state.lastAction=button.dataset.a||button.textContent;navigator.vibrate?.(8);button.classList.add('phase412-table-settle');setTimeout(()=>button.classList.remove('phase412-table-settle'),340)},{passive:true})}state.actionFeedback=true;return true}
function polishWinner(){const banner=$('#winnerBanner');if(!banner)return false;const text=(banner.textContent||'').trim();if(text&&text!==state.lastWinner){state.lastWinner=text;banner.classList.remove('phase412-win-polish');requestAnimationFrame(()=>banner.classList.add('phase412-win-polish'));if(/YOU|WIN|CHAMPION/i.test(text))navigator.vibrate?.([24,36,24])}return true}
function polishGate(){const badge=$('.platform-badge');if(badge&&!badge.dataset.phase412){badge.dataset.phase412='1';badge.textContent='MOBILE • PHASE 412 PROFESSIONAL POLISH'}const gateStatus=$('#gateStatus');if(gateStatus&&!gateStatus.dataset.phase412){gateStatus.dataset.phase412='1';gateStatus.textContent='Protected poker rules remain authoritative. Phase 412 adds account-gated tournament entry, consistent mobile feedback, connectivity status, accessibility focus and production-style interaction polish.'}return true}
function polishTournamentPortal(){if(!/\/game\/tournaments\.html$/i.test(location.pathname))return true;document.body.dataset.professionalPolish='phase412';const status=$('#tournamentStatus');if(status)status.setAttribute('aria-live','polite');return true}
function poll(){try{ensureConnection();ensureDecisionLabel();polishActions();polishWinner();polishGate();polishTournamentPortal();state.installed=true;state.lastError=null}catch(error){state.lastError=String(error?.message||error)}}
addEventListener('online',poll);addEventListener('offline',poll);addEventListener('svr:poker-state',poll);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{poll();setInterval(poll,300)},{once:true});else{poll();setInterval(poll,300)}
window.SVR_PHASE412_PROFESSIONAL_QA=()=>({build:BUILD,...state,actionButtons:document.querySelectorAll('.actions button[data-a]').length,connectionPill:Boolean($('#phase412Connection')),decisionLabel:Boolean($('#phase412DecisionLabel')),focusVisibleCss:Boolean([...document.styleSheets].some(s=>String(s.href||'').includes('phase412_professional_polish.css'))),pass:Boolean(state.installed&&!state.lastError),checkedAt:new Date().toISOString()});
