import * as THREE from 'three';
import { state, players, resetTable } from './phase336_authoritative_engine.js';

export const BUILD='PHASE-368-ANDROID-SPECTATOR-TOURNAMENT-VOICE-LOCK';
const ACTIVE=(window.SVR_PLATFORM||'').toLowerCase()==='android'||/\/game\/android\.html$/i.test(location.pathname)||(/Android/i.test(navigator.userAgent||'')&&!/Quest|Oculus|Meta Quest/i.test(navigator.userAgent||''));
const NAMES=['NOVA','ROOK','ACE','VEGA','IVY'],WORDS={check:'check',call:'call',raise:'raise',bet:'bet',fold:'fold',allin:'all in','all-in':'all in'};
const runtime={build:BUILD,active:ACTIVE,installed:false,spectatorTags:0,spectatorCardsVisible:false,voiceAnnouncements:0,tournamentResets:0,crownedWinner:null,humanBusted:false,lastError:null,installedAt:null,checkedAt:null};
let root=null,lastAction='',lastTournament='',timer=0,frame=0;
const $=(s,r=document)=>r.querySelector(s), joined=()=>Boolean(window.SVR_PHASE363_JOINED_IMMEDIATE??window.SVR_PHASE363_STATE?.joined??window.SVR_PHASE347_STATE?.seated), human=()=>players.find(p=>p?.human)||players[0], world=()=>window.__SVR_SCENE__?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||window.__SVR_SCENE__||null;
function rank(v){v=String(v??'?').toUpperCase();return v==='T'?'10':v}function glyph(v){return({S:'♠',H:'♥',D:'♦',C:'♣'})[String(v||'').toUpperCase()]||''}function card(c){if(!c)return'';const raw=String(c.id||`${c.r||c.rank||''}${c.s||c.suit||''}`).toUpperCase(),s=String(c.s||c.suit||raw.slice(-1));return`${rank(c.r||c.rank||raw.slice(0,-1))}${glyph(s)}`}
function css(){if($('#svr368-tournament-style'))return;const s=document.createElement('style');s.id='svr368-tournament-style';s.textContent=`#svr368TournamentPanel{position:fixed;inset:0;z-index:2147483638;display:grid;place-items:center;padding:20px;background:rgba(0,0,0,.42);pointer-events:none}#svr368TournamentPanel[hidden]{display:none!important}#svr368TournamentPanel>div{width:min(92vw,470px);padding:22px;border:1px solid rgba(255,217,138,.75);border-radius:24px;background:rgba(2,5,13,.94);box-shadow:0 28px 90px rgba(0,0,0,.72);text-align:center;pointer-events:auto}#svr368TournamentPanel b{display:block;font-size:54px}#svr368TournamentPanel h2{margin:4px 0 8px;font:900 clamp(22px,5vw,36px) Orbitron,system-ui;color:#ffd98a}#svr368TournamentPanel p{margin:6px 0 14px;color:#dffcff;font:800 15px/1.35 system-ui}#svr368TournamentPanel button{min-width:150px;min-height:48px;border:1px solid rgba(127,252,255,.7);border-radius:999px;background:linear-gradient(135deg,#7ffcff,#9b4dff);color:#05060b;font-weight:950}`;document.head.appendChild(s)}
function panel(){let p=$('#svr368TournamentPanel');if(!p){p=document.createElement('aside');p.id='svr368TournamentPanel';p.hidden=true;p.innerHTML='<div><b>♛</b><h2></h2><p></p><button type="button">LEAVE TABLE</button></div>';p.querySelector('button').onclick=()=>window.SVR_PHASE363_LEAVE_TABLE?.('phase368-panel');document.body.appendChild(p)}return p}function show(title,message,crown=true){const p=panel();p.querySelector('b').textContent=crown?'♛':'TABLE';p.querySelector('h2').textContent=title;p.querySelector('p').textContent=message;p.hidden=false}function hide(){const p=$('#svr368TournamentPanel');if(p)p.hidden=true}
function texture(player,reveal){const c=document.createElement('canvas');c.width=512;c.height=210;const g=c.getContext('2d');g.clearRect(0,0,512,210);g.fillStyle='rgba(0,4,12,.88)';g.strokeStyle='#7ffcff';g.lineWidth=6;if(g.roundRect){g.beginPath();g.roundRect(6,6,500,198,22);g.fill();g.stroke()}else{g.fillRect(6,6,500,198);g.strokeRect(6,6,500,198)}g.textAlign='center';g.fillStyle='#fff';g.font='900 52px system-ui';g.fillText(String(player?.name||'PLAYER').toUpperCase(),256,66);g.fillStyle='#ffd98a';g.font='900 34px system-ui';g.fillText(`$${Number(player?.stack||0).toLocaleString()}`,256,111);g.fillStyle='#dffcff';g.font='900 42px Georgia';g.fillText(reveal?(player?.hand||[]).map(card).join('  ')||'WAITING':'CARDS HIDDEN',256,166);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function spectators(){const avatars=world()?.getObjectByName?.('PHASE356_ANDROID_LIGHTWEIGHT_TABLE_AVATARS');if(!avatars)return 0;if(!root){root=new THREE.Group();root.name='PHASE368_SPECTATOR_CARD_TAGS';avatars.add(root)}while(root.children.length<5){const s=new THREE.Sprite(new THREE.SpriteMaterial({transparent:true,depthTest:false,depthWrite:false}));s.name=`PHASE368_SPECTATOR_TAG_${root.children.length+1}`;s.scale.set(1.25,.52,1);root.add(s)}const reveal=!joined();root.visible=reveal;NAMES.forEach((name,i)=>{const p=players[i+1],a=avatars.getObjectByName?.(`PHASE356_BOT_AVATAR_${i+1}`)||avatars.children[i],s=root.children[i];if(!p||!a||!s)return;const sig=`${p.stack}|${(p.hand||[]).map(x=>x?.id).join(',')}|${reveal}`;if(s.userData.signature!==sig){s.material.map?.dispose?.();s.material.map=texture({...p,name},reveal);s.material.needsUpdate=true;s.userData.signature=sig}a.updateWorldMatrix?.(true,false);const pos=new THREE.Vector3();a.getWorldPosition(pos);avatars.worldToLocal(pos);s.position.set(pos.x,pos.y+1.75,pos.z)});runtime.spectatorTags=root.children.length;runtime.spectatorCardsVisible=reveal;return runtime.spectatorTags}
function announce(){const entry=String(state.actionLog?.at(-1)||state.lastAction||'').trim();if(!entry||entry===lastAction)return;lastAction=entry;const lower=entry.toLowerCase(),word=Object.entries(WORDS).find(([k])=>lower.includes(k))?.[1];if(!word||!('speechSynthesis'in window)||localStorage.getItem('svr_android_voice_actions')==='off')return;try{const u=new SpeechSynthesisUtterance(entry.length<70?entry:word);u.rate=1.05;u.pitch=.92;u.volume=.55;speechSynthesis.speak(u);runtime.voiceAnnouncements++}catch{}}
function funded(){return players.filter(p=>Number(p?.stack||0)>0)}
function restart(reason='winner'){clearTimeout(timer);timer=setTimeout(()=>{try{hide();window.SVR_RESET_POKER_TABLE?.(15000);if(Number(state.handNo||0)===0)resetTable(15000);window.SVR_PHASE341_REBUILD?.();runtime.tournamentResets++;runtime.crownedWinner=null;runtime.humanBusted=false;lastTournament=''}catch(e){runtime.lastError=String(e?.message||e)}},8500);window.SVR_PHASE368_LAST_TOURNAMENT_RESET_REASON=reason}
function tournament(){if(!joined()){hide();return}const live=funded(),h=human(),complete=String(state.phase||'').toLowerCase()==='showdown'||Boolean(state.winner||state.winners?.length),sig=`${state.handNo}|${state.phase}|${live.map(p=>`${p.id}:${p.stack}`).join(',')}`;if(!complete||sig===lastTournament)return;lastTournament=sig;if(Number(h?.stack||0)<=0&&live.length>1){runtime.humanBusted=true;window.SVR_PHASE359_TOGGLE_CONTINUOUS?.(false);show('YOU ARE OUT','Your stack is empty. Leave the table to watch or join a new tournament.',false);return}if(live.length<=1){const winner=live[0]||players.reduce((best,p)=>Number(p.stack||0)>Number(best?.stack||-1)?p:best,null);runtime.crownedWinner=winner?.name||'WINNER';show(`${runtime.crownedWinner} WINS`,'Tournament champion. A fresh 15,000-chip table will begin after the crown presentation.',true);restart('single-funded-player');return}setTimeout(()=>{if(joined()&&String(state.phase||'').toLowerCase()==='showdown')window.SVR_POKER_NEXT_HAND?.()},7000)}
function sync(){if(!ACTIVE)return;try{spectators();announce();tournament();runtime.checkedAt=new Date().toISOString();window.SVR_PHASE368_SPECTATOR_TOURNAMENT_STATE={...runtime}}catch(e){runtime.lastError=String(e?.message||e)}}
function qa(){sync();const r={...runtime,joined:joined(),fundedPlayers:funded().length,serverAuthoritativeMultiplayer:false,checkedAt:new Date().toISOString()};r.pass=ACTIVE&&runtime.spectatorTags===5&&runtime.serverAuthoritativeMultiplayer!==true;return window.SVR_PHASE368_SPECTATOR_TOURNAMENT_QA_STATE=r}
function install(){if(!ACTIVE||runtime.installed)return;runtime.installed=true;runtime.installedAt=new Date().toISOString();css();panel();['svr:poker-state','svr:phase363-state','svr:phase363-immediate-join-state'].forEach(n=>window.addEventListener(n,()=>setTimeout(sync,0)));const loop=()=>{if(++frame%24===0)sync();requestAnimationFrame(loop)};requestAnimationFrame(loop);[0,300,900,1500].forEach(d=>setTimeout(sync,d));window.SVR_PHASE368_SPECTATOR_TOURNAMENT_QA=qa;window.SVR_PHASE368_SET_VOICE_ACTIONS=enabled=>{localStorage.setItem('svr_android_voice_actions',enabled?'on':'off');return enabled};window.SVR_PHASE368_RESTART_TOURNAMENT=()=>restart('manual');window.SVR_PHASE368_SPECTATOR_TOURNAMENT_STATE={...runtime};window.dispatchEvent(new CustomEvent('svr:phase368-spectator-tournament-ready',{detail:{build:BUILD}}))}
install();
