/* PHASE-466-ANDROID-PRODUCTION-INTEGRATION-LOCK */
const BUILD='PHASE-466-ANDROID-PRODUCTION-INTEGRATION-LOCK';
const API='https://api.svrpoker.com';
const state={build:BUILD,installed:false,online:navigator.onLine,apiReachable:false,playerApiReady:false,tournamentApiReady:false,matchmakingReady:false,engineReady:false,humanTurnReady:false,humanSeatReady:false,actionsReady:false,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s);
function ensureBadge(){let badge=$('#phase466Status');if(badge)return badge;const footer=$('.footer');if(!footer)return null;badge=document.createElement('span');badge.id='phase466Status';badge.style.cssText='display:inline-flex;align-items:center;min-height:30px;padding:5px 9px;border:1px solid #7ffcff55;border-radius:999px;color:#dffcff;font:800 9px system-ui;background:#07101a';badge.textContent='API CHECK';footer.appendChild(badge);return badge}
function paint(){const badge=ensureBadge();if(!badge)return;badge.textContent=state.apiReachable?'API ONLINE':state.online?'API FALLBACK':'OFFLINE • LOCAL PLAY';badge.style.borderColor=state.apiReachable?'#8dffb488':'#ffd98a88'}
async function probeApi(){state.online=navigator.onLine;if(!state.online){state.apiReachable=false;paint();return false}try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3200);const response=await fetch(API+'/api/health',{cache:'no-store',signal:controller.signal,headers:{Accept:'application/json'}});clearTimeout(timer);const data=await response.json().catch(()=>({}));state.apiReachable=Boolean(response.ok&&data.status==='ok');state.playerApiReady=Boolean(data.playerApiReady);state.tournamentApiReady=Boolean(data.tournamentApiReady);state.matchmakingReady=Boolean(data.matchmakingReady);state.lastError=null}catch(error){state.apiReachable=false;state.playerApiReady=false;state.tournamentApiReady=false;state.lastError=String(error?.message||error)}paint();return state.apiReachable}
function sweep(){state.engineReady=Boolean(window.SVR_PHASE403_ANDROID_ENGINE_QA);state.humanTurnReady=Boolean(window.SVR_PHASE414_HUMAN_TURN_QA);state.humanSeatReady=Boolean(window.SVR_PHASE416_HUMAN_SEAT_QA);state.actionsReady=document.querySelectorAll('.actions button[data-a]').length===4&&Boolean($('#join'));state.installed=Boolean(state.engineReady&&state.humanTurnReady&&state.humanSeatReady&&state.actionsReady);state.checkedAt=new Date().toISOString();window.SVR_PHASE466_ANDROID_STATE={...state};return state.installed}
async function boot(){ensureBadge();[100,300,700,1400,2600].forEach(delay=>setTimeout(sweep,delay));await probeApi();window.addEventListener('online',()=>{state.online=true;probeApi()});window.addEventListener('offline',()=>{state.online=false;state.apiReachable=false;paint();sweep()});setInterval(()=>{sweep();if(document.visibilityState==='visible')probeApi()},30000)}
window.SVR_PHASE466_ANDROID_QA=()=>{sweep();return{...state,localFallbackReady:true,publicMatrixUntouched:true,pass:Boolean(state.installed),checkedAt:new Date().toISOString()}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
