import * as THREE from 'three';
const LABEL='PHASE-190-HIDDEN-UPSTAIRS-TABLE-LOGO-TELEPORT-AUTHORITY-LOCK';
const ROOT='PHASE190_HIDDEN_UPSTAIRS_TABLE_LOGO_TELEPORT_ROOT';
const LOGO='PHASE190_MAX_CENTER_LOGO_CARPET';
const SECOND=3.15,EYE=1.62;
const ROOM={minX:-13.35,maxX:13.35,minZ:-10.45,maxZ:9.25};
const UP={x:-8.8,z:7.35};
const DOWN={x:-8.8,z:7.35};
const PORTALS=[{id:'upstairs',title:'UPSTAIRS',sub:'Teleport to concealed upper level',x:-10.2,z:6.9,color:0x7ffcff,kind:'up'},{id:'downstairs',title:'LOBBY',sub:'Teleport back down',x:-10.2,z:6.9,color:0xffd98a,kind:'down'},{id:'vibes',title:'VIBES THEATER',sub:'Shows • Music • Stage',x:-4.2,z:ROOM.maxZ-.14,color:0xb86cff},{id:'smokers',title:'SMOKERS LOUNGE',sub:'Relax • Social • Lounge',x:4.2,z:ROOM.maxZ-.14,color:0x7ffcff}];
let scene,camera,renderer,root,currentFloor=0,started=false,raycaster=new THREE.Raycaster(),hovered=null,lastPortal=null,logoPromise=null;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.68,metalness:.04,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.2});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.95});}
function add(parent,n,p,s,m,rot=0){const x=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);x.name=n;x.position.set(p.x,p.y,p.z);x.rotation.y=rot;x.receiveShadow=true;parent.add(x);return x;}
function loadImg(u){return new Promise(r=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=()=>r(null);i.src=u;});}
async function logoAsset(){if(logoPromise)return logoPromise;logoPromise=(async()=>{for(const u of ['/logo.png','/logo.webp','./ui/logo.png','./assets/ui/logo.png']){const img=await loadImg(u);if(img)return {img,url:u};}return null;})();return logoPromise;}
function logoTex(l){const c=document.createElement('canvas');c.width=c.height=1536;const x=c.getContext('2d'),cx=768,cy=768;x.clearRect(0,0,1536,1536);const g=x.createRadialGradient(cx,cy,80,cx,cy,750);g.addColorStop(0,'rgba(127,252,255,.34)');g.addColorStop(.62,'rgba(70,18,150,.24)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,1536,1536);x.strokeStyle='rgba(127,252,255,.92)';x.lineWidth=24;x.beginPath();x.arc(cx,cy,690,0,Math.PI*2);x.stroke();x.strokeStyle='rgba(238,191,92,.78)';x.lineWidth=10;x.beginPath();x.arc(cx,cy,615,0,Math.PI*2);x.stroke();if(l?.img){const s=910;x.drawImage(l.img,cx-s/2,cy-s/2,s,s);}else{x.fillStyle='#7ffcff';x.font='900 280px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText('SVR',cx,cy-70);x.fillStyle='#eebf5c';x.font='900 110px system-ui';x.fillText('POKER',cx,cy+145);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}
function sign(title,sub,color){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#050610';x.fillRect(0,0,1024,512);x.strokeStyle='#'+color.toString(16).padStart(6,'0');x.lineWidth=14;x.strokeRect(24,24,976,464);x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff';x.font='900 76px system-ui';x.fillText(title,512,188,930);x.fillStyle='#ffd98a';x.font='700 34px system-ui';x.fillText(sub,512,292,910);x.fillStyle='#bffcff';x.font='700 25px system-ui';x.fillText('Soft magnetic portal',512,382,910);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function tableRec(rootObj){const t=rootObj.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||rootObj.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED');if(!t)return null;t.visible=true;t.traverse?.(o=>{o.visible=true;});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),c=new THREE.Vector3(),s=new THREE.Vector3();b.getCenter(c);b.getSize(s);return {obj:t,center:c,size:s,box:b};}
function purge(rootObj){let n=0;const roots=['PHASE178_NEW_UPPER_STRUCTURE_ROOT','PHASE180_WALKABLE_COLLISION_ROOT','PHASE185_WALL_CURVED_STAIR_PERIMETER_BALCONY_ROOT','PHASE186_BALCONY_SAFETY_TELEPORT_ROOT','PHASE187_CLEANUP_WALL_PORTAL_MAGNET_ROOT','PHASE188_CONSOLIDATED_ARCHITECTURE_AUTHORITY_ROOT',ROOT];for(const nm of roots){const o=rootObj.getObjectByName?.(nm);if(o){o.parent?.remove(o);n++;}}const kill=[];rootObj.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|felt|card|chip|pot|watch|hand|teleport|moon|mars|star|camera|light|phase16[0-9]/i.test(nm))return;if(/stair|step|upper|second|balcony|mezzanine|catwalk|glass|rail|rope|stanchion|barrier|banister|handrail|portal|vibes|smokers/i.test(nm))kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
function removeMiddleRails(rootObj,center){let n=0;const kill=[];rootObj.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|button|watch|hand|teleport/i.test(nm))return;if(!/rail|rope|stanchion|barrier|banister|handrail/i.test(nm))return;const p=new THREE.Vector3();o.getWorldPosition(p);if(Math.hypot(p.x-center.x,p.z-center.z)<8.5)kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
async function installLogo(rootObj,rec){const old=rootObj.getObjectByName?.(LOGO);if(old)old.parent?.remove(old);const l=await logoAsset();const g=new THREE.Group();g.name=LOGO;g.position.set(rec?.center?.x||0,.024,rec?.center?.z||0);const size=11.4;const m=new THREE.Mesh(new THREE.PlaneGeometry(size,size),new THREE.MeshBasicMaterial({map:logoTex(l),transparent:true,side:THREE.DoubleSide,depthWrite:false,alphaTest:.02}));m.name='PHASE190_MAXIMUM_CENTER_SVR_LOGO_CARPET';m.rotation.x=-Math.PI/2;m.renderOrder=1900;g.add(m);rootObj.add(g);return {size,url:l?.url||'fallback',x:+g.position.x.toFixed(3),z:+g.position.z.toFixed(3)};}
function buildPad(id,title,sub,x,z,color,y=0){const g=new THREE.Group();g.name='PHASE190_PORTAL_'+id.toUpperCase();g.position.set(x,EYE+y,z);root.add(g);const ring=new THREE.Mesh(new THREE.RingGeometry(.62,.88,72),basic(color,.62));ring.name='PHASE190_PORTAL_RING_'+id.toUpperCase();ring.rotation.x=-Math.PI/2;ring.position.y=-EYE+.035;g.add(ring);const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.2,1.45),new THREE.MeshBasicMaterial({map:sign(title,sub,color),transparent:true,side:THREE.DoubleSide}));panel.name='PHASE190_INTERACTIVE_PORTAL_'+id.toUpperCase();panel.position.set(0,.15,-.42);panel.userData.svrPortal={id,title,kind:id};g.add(panel);const hit=new THREE.Mesh(new THREE.PlaneGeometry(4.2,2.35),basic(0xffffff,.001));hit.name='PHASE190_MAGNET_HITBOX_'+id.toUpperCase();hit.position.copy(panel.position);hit.position.z-=.03;hit.userData.svrPortal={id,title,kind:id};g.add(hit);return g;}
function build(rootObj){const removed=purge(rootObj);root=new THREE.Group();root.name=ROOT;rootObj.add(root);const wall=mat(0x111722),trim=mat(0x070a10),hidden=basic(0x0a0f18,.015);add(root,'PHASE190_REAL_SOUTH_STORE_WALL',{x:0,y:1.75,z:ROOM.maxZ+.04},{x:ROOM.maxX-ROOM.minX+.4,y:3.5,z:.2},wall);add(root,'PHASE190_SOUTH_WALL_BASE_TRIM',{x:0,y:.13,z:ROOM.maxZ-.09},{x:ROOM.maxX-ROOM.minX+.4,y:.26,z:.30},trim);add(root,'PHASE190_CONCEALED_UPSTAIRS_FLOOR',{x:0,y:SECOND-.06,z:0},{x:ROOM.maxX-ROOM.minX,y:.12,z:ROOM.maxZ-ROOM.minZ},hidden);for(const p of PORTALS.filter(p=>!['upstairs','downstairs'].includes(p.id))){const g=new THREE.Group();g.name='PHASE190_STOREFRONT_'+p.id.toUpperCase();g.position.set(p.x,1.62,p.z-.06);root.add(g);const halo=new THREE.Mesh(new THREE.PlaneGeometry(3.55,2.3),basic(p.color,.16));halo.name='PHASE190_PORTAL_HALO_'+p.id.toUpperCase();g.add(halo);const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.15,1.86),new THREE.MeshBasicMaterial({map:sign(p.title,p.sub,p.color),transparent:true,side:THREE.DoubleSide}));panel.name='PHASE190_INTERACTIVE_PORTAL_'+p.id.toUpperCase();panel.userData.svrPortal={id:p.id,title:p.title};panel.position.z=-.03;g.add(panel);const hit=new THREE.Mesh(new THREE.PlaneGeometry(4.15,2.75),basic(0xffffff,.001));hit.name='PHASE190_MAGNET_HITBOX_'+p.id.toUpperCase();hit.userData.svrPortal={id:p.id,title:p.title};hit.position.z=-.055;g.add(hit);}buildPad('upstairs','UPSTAIRS','Teleport up',UP.x,UP.z,0x7ffcff,0);buildPad('downstairs','LOBBY','Teleport down',DOWN.x,DOWN.z,0xffd98a,SECOND);return removed;}
function setPose(x,y,z){currentFloor=y>2?SECOND:0;const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;if(renderer?.xr?.isPresenting&&rig?.setPlayerPose)rig.setPlayerPose(x,currentFloor,z);else{camera.position.set(x,currentFloor+EYE,z);camera.lookAt(0,currentFloor+1.45,0);}}
function activatePortal(p){if(!p)return;if(p.id==='upstairs')setPose(UP.x,SECOND,UP.z);else if(p.id==='downstairs')setPose(0,0,7.2);window.SVR_PHASE190_LAST_PORTAL_ACTIVATE={build:LABEL,portal:p,floor:currentFloor,checkedAt:iso()};window.dispatchEvent(new CustomEvent('svr-portal-activate',{detail:{build:LABEL,portal:p}}));}
function camPos(){const p=new THREE.Vector3();if(renderer?.xr?.isPresenting)renderer.xr.getCamera(camera).getWorldPosition(p);else camera?.getWorldPosition(p);return p;}
function tickHeight(){if(!camera)return;const p=camPos();const want=currentFloor+EYE;if(!renderer?.xr?.isPresenting&&Math.abs(camera.position.y-want)>.035)camera.position.y+=(want-camera.position.y)*.10;window.SVR_PHASE190_HEIGHT_STATUS={build:LABEL,currentFloor,x:+p.x.toFixed(3),z:+p.z.toFixed(3),floorY:currentFloor,stairsRemoved:true,balconyConcealed:true,checkedAt:iso()};}
function ray(){const c=renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;const p=new THREE.Vector3(),d=new THREE.Vector3();c.getWorldPosition(p);c.getWorldDirection(d);return {p,d};}
function setHover(o,on){if(!o)return;o.scale.setScalar(on?1.045:1);const h=o.parent?.children?.find(x=>/HALO|RING/.test(x.name));if(h&&h.material)h.material.opacity=on?.34:.16;}
function tickPortal(){if(!root||!camera)return;const hits=[];root.traverse(o=>{if(o.userData?.svrPortal)hits.push(o);});const r=ray();raycaster.set(r.p,r.d);const direct=raycaster.intersectObjects(hits,false)[0];let best=direct?.object||null,score=direct?0:99;if(!best){for(const o of hits){const p=new THREE.Vector3();o.getWorldPosition(p);const to=p.sub(r.p);const dist=to.length();if(dist<.1||dist>10)continue;const ang=r.d.angleTo(to.normalize());const s=ang*2+dist*.015;if(s<score&&ang<.20){best=o;score=s;}}}if(best!==hovered){setHover(hovered,false);hovered=best;setHover(hovered,true);}lastPortal=hovered?.userData?.svrPortal||null;window.SVR_PHASE190_PORTAL_STATUS={build:LABEL,hover:lastPortal,balancedMagnet:true,checkedAt:iso()};}
async function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const rootObj=sr(scene);const removed=build(rootObj);const table=tableRec(rootObj);const rails=removeMiddleRails(rootObj,table?.center||new THREE.Vector3());const logo=await installLogo(rootObj,table||{center:new THREE.Vector3(),size:new THREE.Vector3()});window.SVR_PHASE190_HIDDEN_UPSTAIRS_TABLE_LOGO_TELEPORT_AUTHORITY_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,stairsRemoved:true,balconyConcealed:true,upDownTeleport:true,tableVisible:!!table,centerLogo:logo,middleRailsRemoved:rails,oldRootsRemoved:removed,checkedAt:iso()};window.SVR_RUN_PHASE190_ARCHITECTURE_AUDIT=()=>window.SVR_PHASE190_HIDDEN_UPSTAIRS_TABLE_LOGO_TELEPORT_AUTHORITY_LOCK;window.SVR_ACTIVATE_PHASE190_PORTAL=()=>activatePortal(lastPortal);window.SVR_PHASE190_TELEPORT_UPSTAIRS=()=>setPose(UP.x,SECOND,UP.z);window.SVR_PHASE190_TELEPORT_LOBBY=()=>setPose(0,0,7.2);window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;window.addEventListener('keydown',e=>{if(e.code==='Enter'||e.code==='KeyE')activatePortal(lastPortal);if(e.code==='KeyU')setPose(UP.x,SECOND,UP.z);if(e.code==='KeyD')setPose(0,0,7.2);});setInterval(()=>{tickHeight();tickPortal();},90);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
