/* PHASE-401-ANDROID-SPONSOR-TOURNAMENT-DIRECTOR-LOCK | PHASE-402 visual seat order | PHASE-403 pot-aware */
const BUILD='PHASE-401-ANDROID-SPONSOR-TOURNAMENT-DIRECTOR-LOCK';
const SEAT_ORDER_BUILD='PHASE-402-ANDROID-VISUAL-LEFT-SEAT-ORDER-LOCK';
const VISUAL_LEFT_SEAT_ORDER=Object.freeze([0,5,1,2,3,4]);
const params=new URLSearchParams(location.search);
const MODE=String(params.get('mode')||'regular').toLowerCase();
const ACTIVE=MODE==='tournament';
const STORAGE='svr401_reiki_first50_tournament';
const RESULTS='svr401_reiki_first50_results';
const CONFIG={
  id:'reiki-first-50',name:'REIKI FIRST 50',sponsor:'REIKI',registrationCap:50,testFieldSize:10,
  visibleTableSeats:6,startingStack:10000,prizePlayChips:100000,roundsPerLevel:2,
  levels:[
    {smallBlind:50,bigBlind:100,ante:0},{smallBlind:75,bigBlind:150,ante:25},
    {smallBlind:100,bigBlind:200,ante:25},{smallBlind:150,bigBlind:300,ante:50},
    {smallBlind:200,bigBlind:400,ante:50},{smallBlind:300,bigBlind:600,ante:100},
    {smallBlind:400,bigBlind:800,ante:100},{smallBlind:500,bigBlind:1000,ante:150},
    {smallBlind:750,bigBlind:1500,ante:200},{smallBlind:1000,bigBlind:2000,ante:300}
  ]
};
const BOT_NAMES=['Claudia','Eric','Maya','Darius','Nova','Kai','Lena','Marcus','Zoe'];
const runtime={build:BUILD,seatOrderBuild:SEAT_ORDER_BUILD,phase403PotAware:true,active:ACTIVE,mode:MODE,lastPatchedHand:0,lastProcessedHand:0,lastStreet:-1,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s);
const now=()=>new Date().toISOString();
const regularStack=()=>Math.max(0,Number(localStorage.getItem('svr393stack')||15000));
function userName(){try{const raw=JSON.parse(localStorage.getItem('svr_demo_account')||'{}');return raw?.profile?.displayName||raw?.displayName||'YOU'}catch{return'YOU'}}
function blank(){return{version:3,id:CONFIG.id,name:CONFIG.name,sponsor:CONFIG.sponsor,status:'available',registrationCap:CONFIG.registrationCap,testFieldSize:CONFIG.testFieldSize,round:0,startedAt:null,completedAt:null,champion:null,prizePlayChips:CONFIG.prizePlayChips,prizeAwarded:false,regularStackBefore:null,entrants:[],eliminations:[],lastHand:null,updatedAt:now()}}
function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE)||'null');if(parsed?.id===CONFIG.id)return parsed}catch{}return blank()}
function save(t){t.updatedAt=now();localStorage.setItem(STORAGE,JSON.stringify(t));window.SVR_PHASE401_TOURNAMENT_STATE=t;return t}
function activeEntrants(t){return(t.entrants||[]).filter(x=>x.status==='active'&&x.stack>0)}
function createField(){const t=blank();t.status='in_progress';t.startedAt=now();t.regularStackBefore=regularStack();t.entrants=[{id:'user',name:userName(),isUser:true,stack:CONFIG.startingStack,status:'active',place:null,seat:0}];BOT_NAMES.slice(0,CONFIG.testFieldSize-1).forEach((name,i)=>t.entrants.push({id:`bot-${i+1}`,name,isUser:false,stack:CONFIG.startingStack,status:'active',place:null,seat:null}));return save(t)}
function ensureRunning(){let t=load();if(t.status!=='in_progress'||!(t.entrants||[]).length)t=createField();if(t.regularStackBefore==null)t.regularStackBefore=regularStack();return save(t)}
function levelFor(t){const index=Math.min(CONFIG.levels.length-1,Math.floor(Math.max(0,t.round||0)/CONFIG.roundsPerLevel));return{index,...CONFIG.levels[index]}}
function markEliminated(t,entrant){if(!entrant||entrant.status!=='active'||entrant.stack>0)return;const remaining=activeEntrants(t).filter(x=>x.id!==entrant.id).length;entrant.status='eliminated';entrant.place=Math.max(2,remaining+1);entrant.eliminatedAtRound=t.round;t.eliminations.push({id:entrant.id,name:entrant.name,place:entrant.place,round:t.round,at:now()})}
function simulateOffTable(t,seatedIds){const off=activeEntrants(t).filter(e=>!seatedIds.has(e.id)&&!e.isUser);if(!off.length)return;for(let i=0;i<off.length;i+=2){const a=off[i],b=off[i+1];if(!b)break;const swing=Math.max(100,Math.min(1200,Math.round(Math.min(a.stack,b.stack)*(.08+Math.random()*.12)/50)*50));if(Math.random()<.5){a.stack=Math.max(0,a.stack-swing);b.stack+=swing}else{b.stack=Math.max(0,b.stack-swing);a.stack+=swing}markEliminated(t,a);markEliminated(t,b)}if((t.round+1)%2===0&&activeEntrants(t).length>6){const survivors=off.filter(e=>e.status==='active').sort((a,b)=>a.stack-b.stack),victim=survivors[0],receiver=activeEntrants(t).filter(e=>e.id!==victim?.id).sort((a,b)=>b.stack-a.stack)[0];if(victim&&receiver){receiver.stack+=victim.stack;victim.stack=0;markEliminated(t,victim)}}}
function writeResults(t){const results={id:t.id,name:t.name,sponsor:t.sponsor,completedAt:t.completedAt,champion:t.champion,prizePlayChips:CONFIG.prizePlayChips,prizeAwarded:t.prizeAwarded,placements:[...t.entrants].sort((a,b)=>(a.place??999)-(b.place??999)||b.stack-a.stack).map(e=>({name:e.name,isUser:e.isUser,place:e.place,stack:e.stack,status:e.status}))};localStorage.setItem(RESULTS,JSON.stringify(results));return results}
function restoreRegular(t){if(t?.regularStackBefore!=null)localStorage.setItem('svr393stack',String(Math.max(0,Number(t.regularStackBefore))))}
function completeTournament(t,champion){if(t.status==='completed')return;t.status='completed';t.completedAt=now();t.champion={id:champion.id,name:champion.name,isUser:champion.isUser,stack:champion.stack};champion.place=1;champion.status='champion';const base=Math.max(0,Number(t.regularStackBefore??regularStack()));if(champion.isUser){localStorage.setItem('svr393stack',String(base+CONFIG.prizePlayChips));t.prizeAwarded=true}else{localStorage.setItem('svr393stack',String(base));t.prizeAwarded=false}writeResults(t);save(t)}
function finishBotsIfUserOut(t){const user=t.entrants.find(e=>e.isUser);if(user?.status==='active')return false;const survivors=activeEntrants(t);if(!survivors.length)return true;const champion=[...survivors].sort((a,b)=>b.stack-a.stack)[0];survivors.forEach(e=>{if(e.id!==champion.id){champion.stack+=e.stack;e.stack=0;markEliminated(t,e)}});completeTournament(t,champion);return true}
function ensureModeUi(){document.body.dataset.gameMode=MODE;const badge=$('.platform-badge'),join=$('#join'),status=$('#gateStatus');if(MODE==='practice'){if(badge)badge.textContent='ANDROID • PRACTICE';if(join)join.textContent='START PRACTICE';if(status)status.textContent='Practice mode uses the approved poker table, hand guide, Smart Hand Coach, and leftward seat order.'}else if(ACTIVE){if(badge)badge.textContent='REIKI • TOURNAMENT';if(join)join.textContent='ENTER TOURNAMENT';if(status)status.textContent='REIKI FIRST 50 • 10-player test field • 10,000 starting tournament chips • 100,000 play-chip prize • levels change every 2 rounds.'}else{if(badge)badge.textContent='ANDROID • REGULAR';if(join)join.textContent='JOIN REGULAR TABLE'}}
function sponsorUi(){if(!ACTIVE)return;const strong=$('#featuredSponsor strong'),small=$('#featuredSponsor small');if(strong)strong.textContent='REIKI FIRST 50';if(small)small.textContent='SPONSOR TOURNAMENT';document.body.classList.add('phase401-tournament-mode')}
function ensureHud(){if(!ACTIVE||$('#phase401TournamentHud'))return;const turn=$('.turn-strip');if(!turn)return;turn.insertAdjacentHTML('afterend','<section id="phase401TournamentHud" class="phase401-tournament-hud"><strong>REIKI FIRST 50</strong><span data-field>10 LEFT</span><span data-round>ROUND 1</span><span data-level>LEVEL 1 • 50/100</span><span data-prize>PRIZE 100,000</span><a href="/game/tournament-results.html?v=phase403">RESULTS</a></section>')}
function updateHud(t=load()){if(!ACTIVE)return;ensureHud();const hud=$('#phase401TournamentHud');if(!hud)return;const level=levelFor(t),left=activeEntrants(t).length;hud.querySelector('[data-field]').textContent=`${left} LEFT / ${CONFIG.testFieldSize}`;hud.querySelector('[data-round]').textContent=`ROUND ${(t.round||0)+1}`;hud.querySelector('[data-level]').textContent=`LEVEL ${level.index+1} • ${level.smallBlind}/${level.bigBlind}${level.ante?` • ANTE ${level.ante}`:''}`;hud.querySelector('[data-prize]').textContent=`PRIZE ${CONFIG.prizePlayChips.toLocaleString()}`}
function visualSeatsAfter(from){const pos=VISUAL_LEFT_SEAT_ORDER.indexOf(from);if(pos<0)return[...VISUAL_LEFT_SEAT_ORDER];return Array.from({length:VISUAL_LEFT_SEAT_ORDER.length},(_,step)=>VISUAL_LEFT_SEAT_ORDER[(pos+step+1)%VISUAL_LEFT_SEAT_ORDER.length])}
function liveSeatIndexes(game){return(game.players||[]).filter(p=>p.tournamentId&&p.stack>0&&!p.folded).map(p=>p.index)}
function nextSeat(game,from,{actionable=false}={}){for(const i of visualSeatsAfter(from)){const p=game.players[i];if(p&&p.tournamentId&&p.stack>0&&!p.folded&&(!actionable||!p.allIn))return i}return null}
function orderAfter(game,from){const out=[];for(const i of visualSeatsAfter(from)){const p=game.players[i];if(p&&p.tournamentId&&p.stack>0&&!p.folded&&!p.allIn)out.push(i)}return out}
function payForced(game,player,amount,label,{street=true}={}){if(!player||player.stack<=0||amount<=0)return 0;const pay=Math.min(player.stack,Math.round(amount));player.stack-=pay;if(street)player.streetBet=(player.streetBet||0)+pay;player.handContribution=(player.handContribution||0)+pay;game.pot+=pay;if(player.stack===0)player.allIn=true;player.lastAction=`${label} $${pay.toLocaleString()}`;if(player.index===0)game.stack=player.stack;return pay}
function mapEntrantsToSeats(game,t){const user=t.entrants.find(e=>e.isUser),bots=activeEntrants(t).filter(e=>!e.isUser),used=new Set();for(const p of game.players||[]){p.streetBet=0;p.handContribution=0;p.acted=false;p.active=false;p.raiseLocked=false;p.lastAction='WAITING';p.folded=false;p.allIn=false;p.tournamentId=null}const p0=game.players?.[0];if(p0&&user?.status==='active'){p0.name=user.name;p0.stack=user.stack;p0.tournamentId=user.id;p0.rank='TOURNAMENT';used.add(user.id);game.stack=user.stack}else if(p0){p0.name=user?.name||'YOU';p0.stack=0;p0.folded=true;p0.allIn=true;p0.rank='OUT'}for(let seat=1;seat<(game.players||[]).length;seat++){const oldId=game.players[seat]?.tournamentId;let entrant=oldId?bots.find(e=>e.id===oldId&&!used.has(e.id)):null;if(!entrant)entrant=bots.find(e=>!used.has(e.id));const p=game.players[seat];if(entrant){p.name=entrant.name;p.stack=entrant.stack;p.tournamentId=entrant.id;p.rank='TOURNAMENT';used.add(entrant.id)}else{p.name=`OPEN ${seat}`;p.stack=0;p.folded=true;p.allIn=true;p.rank='OUT'}}}
function patchHand(game){if(!ACTIVE||!game?.joined||!game.players?.length)return false;const t=ensureRunning(),level=levelFor(t);mapEntrantsToSeats(game,t);game.pot=0;game.currentBet=level.bigBlind;game.lastFullRaiseSize=level.bigBlind;game.tableSmallBlind=level.smallBlind;game.tableBigBlind=level.bigBlind;game.tableAnte=level.ante;game.lastFullRaiser=null;game.phase403ForcedContributionHand=0;const live=liveSeatIndexes(game);if(live.length<2)return false;let dealer=live.includes(game.dealer)?game.dealer:nextSeat(game,game.dealer);if(dealer==null)dealer=live[0];game.dealer=dealer;game.players.forEach(p=>p.button=p.index===dealer);for(const p of game.players){if(p.tournamentId&&p.stack>0&&level.ante>0)payForced(game,p,level.ante,'ANTE',{street:false})}let small,big,first;if(liveSeatIndexes(game).length===2){small=dealer;big=nextSeat(game,dealer);first=dealer}else{small=nextSeat(game,dealer);big=nextSeat(game,small);first=nextSeat(game,big,{actionable:true})}game.smallBlind=small;game.bigBlind=big;if(small!=null)payForced(game,game.players[small],level.smallBlind,'SMALL BLIND');if(big!=null)payForced(game,game.players[big],level.bigBlind,'BIG BLIND');game.currentBet=level.bigBlind;game.expectedActor=first;game.roundAnchor=big;game.roundOrder=orderAfter(game,big??dealer);game.raiseTarget=Math.max(game.currentBet+game.lastFullRaiseSize,game.raiseTarget||0);t.currentLevel=level.index+1;t.currentSmallBlind=level.smallBlind;t.currentBigBlind=level.bigBlind;t.currentAnte=level.ante;save(t);sponsorUi();updateHud(t);const msg=$('#tableMessage');if(msg)msg.textContent=`${CONFIG.name} • LEFT ORDER • ROUND ${(t.round||0)+1} • LEVEL ${level.index+1} • ${level.smallBlind}/${level.bigBlind}${level.ante?` • ANTE ${level.ante}`:''}`;runtime.lastPatchedHand=game.hand;runtime.lastStreet=game.street;runtime.checkedAt=now();return true}
function keepStreetMinimum(game){if(!ACTIVE||!game?.joined||game.handOver)return;if(game.street>0&&game.street<4&&game.currentBet===0&&game.lastActor==null){const t=load(),level=levelFor(t);game.lastFullRaiseSize=level.bigBlind;game.tableBigBlind=level.bigBlind;game.tableSmallBlind=level.smallBlind;game.tableAnte=level.ante}}
function syncHandResult(game){const t=ensureRunning(),seated=new Set();for(const p of game.players||[]){const entrant=t.entrants.find(e=>e.id===p.tournamentId);if(!entrant)continue;entrant.stack=Math.max(0,Math.round(p.stack||0));entrant.seat=p.index;seated.add(entrant.id);markEliminated(t,entrant)}simulateOffTable(t,seated);t.round=(t.round||0)+1;const mainPotWinners=Array.isArray(game.lastMainPotWinners)?game.lastMainPotWinners:[],userWonMainPot=mainPotWinners.includes(0),userWonAnyPot=(game.lastPotBreakdown||[]).some(pot=>pot.type==='pot'&&(pot.winnerIndexes||[]).includes(0));t.lastHand={round:t.round,winner:game.lastWinner!=null?game.players?.[game.lastWinner]?.name:null,userWon:userWonAnyPot||game.lastWinner===0,userWonMainPot,userWonAnyPot,potCount:(game.lastPotBreakdown||[]).filter(pot=>pot.type==='pot').length,at:now()};const survivors=activeEntrants(t);if(survivors.length===1)completeTournament(t,survivors[0]);else if(finishBotsIfUserOut(t)){}else{restoreRegular(t);save(t)}updateHud(t);return t}
function ensureCompletionOverlay(t){let overlay=$('#phase401TournamentComplete');if(!overlay){overlay=document.createElement('div');overlay.id='phase401TournamentComplete';overlay.className='overlay';overlay.innerHTML='<div class="overlay-card"><h2 data-title>TOURNAMENT COMPLETE</h2><p data-copy></p><a class="btn primary" href="/game/tournament-results.html?v=phase403">VIEW RESULTS</a><a class="btn" href="/game/tournaments.html?v=phase403">TOURNAMENTS</a></div>';document.body.appendChild(overlay)}const user=t.entrants.find(e=>e.isUser),won=user?.place===1;overlay.querySelector('[data-title]').textContent=won?'REIKI FIRST 50 CHAMPION':'REIKI FIRST 50 COMPLETE';overlay.querySelector('[data-copy]').textContent=won?`You won ${CONFIG.prizePlayChips.toLocaleString()} regular play chips.`:`${t.champion?.name||'Tournament winner'} finished first. You placed ${user?.place||'-'}.`;overlay.classList.remove('hide')}
function afterHand(game){if(!ACTIVE||runtime.lastProcessedHand===game.hand)return null;runtime.lastProcessedHand=game.hand;const t=syncHandResult(game);if(t.status==='completed'){clearTimeout(game.autoTimer);game.autoTimer=0;$('#outOverlay')?.classList.add('hide');const status=$('#status');if(status)status.textContent=t.champion?.isUser?`TOURNAMENT CHAMPION • +${CONFIG.prizePlayChips.toLocaleString()} PLAY CHIPS`:`TOURNAMENT COMPLETE • ${t.champion?.name||'WINNER'} WON`;ensureCompletionOverlay(t);return{stop:true}}const user=t.entrants.find(e=>e.isUser);if(user?.status!=='active'){clearTimeout(game.autoTimer);game.autoTimer=0;$('#outOverlay')?.classList.add('hide');ensureCompletionOverlay(t);return{stop:true}}return{stop:false}}
function onJoin(){if(!ACTIVE)return null;const t=ensureRunning();sponsorUi();updateHud(t);return t}
function onLeave(){if(!ACTIVE)return;restoreRegular(load());updateHud(load())}
function reset(){localStorage.removeItem(STORAGE);return createField()}
function getState(){const t=load();return{...t,config:CONFIG,currentLevel:levelFor(t),playersLeft:activeEntrants(t).length}}
function qa(){const t=getState(),level=t.currentLevel;return{build:BUILD,seatOrderBuild:SEAT_ORDER_BUILD,phase403PotAware:true,active:ACTIVE,mode:MODE,registrationCap:CONFIG.registrationCap,testFieldSize:CONFIG.testFieldSize,visibleTableSeats:CONFIG.visibleTableSeats,startingStack:CONFIG.startingStack,prizePlayChips:CONFIG.prizePlayChips,roundsPerLevel:CONFIG.roundsPerLevel,currentSmallBlind:level.smallBlind,currentBigBlind:level.bigBlind,currentAnte:level.ante,visualLeftSeatOrder:[...VISUAL_LEFT_SEAT_ORDER],dariusGoesToUser:visualSeatsAfter(4)[0]===0,userGoesToNova:visualSeatsAfter(0)[0]===5,botFill:true,regularBankrollIsolated:true,resultsStorage:RESULTS,handsGuidePreserved:Boolean(window.SVR_PHASE399_ANDROID_LEARNING_QA),landscapePolish:document.styleSheets?true:false,pass:Boolean((!ACTIVE||CONFIG.registrationCap===50&&CONFIG.testFieldSize===10&&CONFIG.prizePlayChips===100000&&CONFIG.roundsPerLevel===2)&&visualSeatsAfter(4)[0]===0&&visualSeatsAfter(0)[0]===5),checkedAt:now()}}
function poll(){try{ensureModeUi();if(!ACTIVE)return;const game=window.SVR_PHASE393_ANDROID_STATE;if(game?.joined){if(runtime.lastPatchedHand!==game.hand)patchHand(game);keepStreetMinimum(game);if(game.handOver&&runtime.lastProcessedHand!==game.hand)setTimeout(()=>afterHand(game),30)}runtime.checkedAt=now()}catch(error){runtime.lastError=String(error?.message||error)}}
window.SVR_PHASE401_TOURNAMENT_DIRECTOR={build:BUILD,seatOrderBuild:SEAT_ORDER_BUILD,phase403PotAware:true,config:CONFIG,visualLeftSeatOrder:[...VISUAL_LEFT_SEAT_ORDER],active:()=>ACTIVE,onJoin,afterHand,reset,getState,updateHud,patchHand,tableLabel:()=>CONFIG.name};
window.SVR_PHASE401_TOURNAMENT_QA=qa;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensureModeUi();if(ACTIVE){sponsorUi();ensureHud();updateHud(load())}setInterval(poll,16)},{once:true});else{ensureModeUi();if(ACTIVE){sponsorUi();ensureHud();updateHud(load())}setInterval(poll,16)}
