import * as THREE from 'three';
const LABEL='PHASE-197-SINGLE-AUTHORITY-CLEANUP-LOCK';
const ROOT='PHASE197_SINGLE_AUTHORITY_CLEANUP_ROOT';
let scene,camera,renderer,root,started=false;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.75,metalness:.04,side:THREE.DoubleSide});}
function addBox(p,n,pos,s,m){const x=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);x.name=n;x.position.set(pos.x,pos.y,pos.z);p.add(x);return x;}
function suppressHud(){const keys=['update','available','manager','patch','install'];document.querySelectorAll('div,section,aside,pre').forEach(el=>{const txt=(el.textContent||'').toLowerCase();if(keys.every(k=>txt.includes(k))||/svr update available/i.test(txt)){el.style.display='none';el.dataset.phase197Hidden='true';}});}
function removeCenterRails(){let n=0;const r=sr(scene),kill=[];r?.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|watch|hand|teleport|moon|mars|star|camera|light|phase196/i.test(nm))return;if(!/rail|rope|stanchion|barrier|banister|handrail|guard|pole|post|fence/i.test(nm))return;const p=new THREE.Vector3();o.getWorldPosition(p);if(Math.hypot(p.x,p.z)<13)kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
function cleanupPlanets(){let keptMoon=null,keptMars=null,removed=0;scene?.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE196_ROTATING_MOON/.test(nm))keptMoon=o;if(/PHASE196_MARS_ORBITS_MOON/.test(nm))keptMars=o;});const kill=[];scene?.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/PHASE196_SKY|PHASE196_ROTATING_MOON|PHASE196_MARS|PHASE196_MORE_STARS|PHASE196_MOON_ATMOSPHERE/i.test(nm))return;if(/moon|mars|planet/i.test(nm))kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);removed++;});return {keptMoon:!!keptMoon,keptMars:!!keptMars,removed};}
function findTable(){const r=sr(scene);let found=null;const names=[];r?.traverse?.(o=>{const nm=String(o.name||'');if(/table/i.test(nm))names.push(nm);if(found)return;if(/PHASE159_FBX_TABLE|ACTUAL_UPLOADED_TABLE|FBX.*TABLE|TABLE.*FBX|poker.*table/i.test(nm))found=o;});if(found){found.visible=true;found.traverse?.(o=>{o.visible=true;if(o.isMesh){const n=String(o.name||'').toLowerCase();if(/leather|hand|rest|rail|rim|edge|cushion/.test(n))o.material=mat(0x24120c);else if(/felt|cloth|top|surface/.test(n))o.material=mat(0x064426);else if(!o.material)o.material=mat(0x2a211c);}});found.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(found),c=new THREE.Vector3(),s=new THREE.Vector3();b.getCenter(c);b.getSize(s);return {found:true,obj:found,center:c,size:s,names};}
return {found:false,names};}
function emergencyTableMarker(center){const old=root.getObjectByName?.('PHASE197_TABLE_MISSING_MARKER');if(old)old.parent?.remove(old);const g=new THREE.Group();g.name='PHASE197_TABLE_MISSING_MARKER';g.position.set(center.x,.08,center.z);root.add(g);const ring=new THREE.Mesh(new THREE.RingGeometry(2.2,2.55,96),basic(0xff4444,.75));ring.rotation.x=-Math.PI/2;g.add(ring);const c=document.createElement('canvas');c.width=1024;c.height=256;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.74)';x.fillRect(0,0,1024,256);x.strokeStyle='#ff4444';x.lineWidth=10;x.strokeRect(8,8,1008,240);x.fillStyle='#fff';x.font='900 54px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText('REAL FBX TABLE NOT FOUND',512,92);x.fillStyle='#ffd98a';x.font='700 30px system-ui';x.fillText('No fake table added. Check FBX root/load path.',512,164);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const p=new THREE.Mesh(new THREE.PlaneGeometry(5.2,1.3),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide}));p.position.set(0,1.4,-2.2);g.add(p);}
function enforceLogo(center){const logos=[];scene?.traverse?.(o=>{const nm=String(o.name||'');if(/LOGO|logo/i.test(nm)&&/floor|circle|carpet|lobby|center|PHASE19/i.test(nm))logos.push(o);});let kept=false;for(const o of logos){if(/PHASE196_ORIGINAL_LOBBY_LOGO|PHASE192_CENTER_LOGO_FILL/.test(o.name)){o.visible=true;kept=true;}else if(!/PHASE196/.test(o.name)){o.visible=false;}}
return {logosFound:logos.length,keptOriginal:kept};}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);suppressHud();const rails=removeCenterRails();const planets=cleanupPlanets();const table=findTable();const center=table.center||new THREE.Vector3(0,0,0);const logo=enforceLogo(center);if(!table.found)emergencyTableMarker(center);window.SVR_PHASE197_SINGLE_AUTHORITY_CLEANUP_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,railsRemoved:rails,planets,table:{found:table.found,names:table.names?.slice?.(0,20)||[],size:table.size?{x:+table.size.x.toFixed(2),y:+table.size.y.toFixed(2),z:+table.size.z.toFixed(2)}:null},logo,updateOverlaySuppressed:true,checkedAt:iso()};window.SVR_RUN_PHASE197_AUDIT=()=>window.SVR_PHASE197_SINGLE_AUTHORITY_CLEANUP_LOCK;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(()=>{suppressHud();removeCenterRails();cleanupPlanets();},1400);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
