import * as THREE from 'three';
const LABEL='PHASE-208-SKY-HARD-RESET-ONE-PLANET-LOCK';
const ROOT='PHASE208_SINGLE_SKY_ROOT';
let scene,root,started=false;
function rootScene(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function material(color){return new THREE.MeshStandardMaterial({color,roughness:.88,metalness:0,transparent:false,opacity:1,side:THREE.FrontSide});}
function killOldSky(){let removed=0;const kill=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(!o.parent||n.includes('PHASE208'))return;if(/moon|mars|planet/i.test(n))kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);removed++;});return removed;}
function quietGlow(){let changed=0;scene?.traverse?.(o=>{const n=String(o.name||'');if(/sprite|sparkle|pulse|strobe|blink|glow/i.test(n)){if(!/PHASE208|PHASE195_PORTAL/i.test(n)){o.visible=false;changed++;}}});return changed;}
function makeCraterTexture(base,spot){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle=base;x.fillRect(0,0,512,512);for(let i=0;i<70;i++){x.fillStyle=spot;x.globalAlpha=.08+Math.random()*.14;x.beginPath();x.arc(Math.random()*512,Math.random()*512,Math.random()*22+4,0,Math.PI*2);x.fill();}x.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function buildSky(){const old=scene.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;scene.add(root);const moon=new THREE.Mesh(new THREE.SphereGeometry(2.2,64,32),new THREE.MeshStandardMaterial({map:makeCraterTexture('#cfd2d4','rgba(40,40,45,1)'),roughness:.9,metalness:0,emissive:0x111111,emissiveIntensity:.08}));moon.name='PHASE208_ONE_STABLE_MOON';moon.position.set(-7,15.5,-28);root.add(moon);const mars=new THREE.Mesh(new THREE.SphereGeometry(.78,48,24),new THREE.MeshStandardMaterial({map:makeCraterTexture('#b95a36','rgba(70,20,5,1)'),roughness:.9,metalness:0,emissive:0x120400,emissiveIntensity:.05}));mars.name='PHASE208_ONE_STABLE_MARS';mars.position.set(-2.5,15.2,-26.5);root.add(mars);const stars=[];for(let i=0;i<180;i++)stars.push((Math.random()-.5)*80,Math.random()*24+8,(Math.random()-.5)*80);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));const pts=new THREE.Points(g,new THREE.PointsMaterial({color:0xddeeff,size:.055,transparent:false}));pts.name='PHASE208_STABLE_STAR_FIELD';root.add(pts);return true;}
function pass(){scene=window.__SVR_SCENE__;if(!scene)return null;const removed=killOldSky();if(!scene.getObjectByName?.(ROOT))buildSky();const quieted=quietGlow();window.SVR_PHASE208_SKY_HARD_RESET_ONE_PLANET_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,oldSkyRemoved:removed,extraGlowHidden:quieted,oneMoon:true,oneMars:true,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return window.SVR_PHASE208_SKY_HARD_RESET_ONE_PLANET_LOCK;}
function install(){const out=pass();window.SVR_RUN_PHASE208_SKY_AUDIT=()=>pass();if(!started){started=true;setInterval(pass,1500);}return !!out;}
[500,1200,2600,5000,9000,14000].forEach(ms=>setTimeout(install,ms));install();
