/* PHASE-388-FRONT-SOUTH-SEAT-AUTHORITY */
import * as THREE from 'three';
export const BUILD='PHASE-388-FRONT-SOUTH-SEAT-AUTHORITY';
const p=new URLSearchParams(location.search),ACTIVE=p.get('platform')==='quest'||p.get('direct')==='1'||/Quest|Oculus|Meta Quest/i.test(navigator.userAgent||'');
const GAP=.12,EYE_ABOVE=.54,FLAGS=['SVR_MOVEMENT_ENABLED','SVR_LOCOMOTION_ENABLED','SVR_TABLE_TRAVEL_ENABLED','SVR_TELEPORT_ENABLED','SVR_HAND_TELEPORT_ENABLED','SVR_WATCH_TELEPORT_ENABLED','SVR_GRIP_TELEPORT_ENABLED','SVR_POINTER_ENABLED','SVR_HAND_RAY_ENABLED','SVR_SNAP_TURN_ENABLED','SVR_STICK_MOVE_ENABLED'];
const state={build:BUILD,active:ACTIVE,installed:false,frontSeatReady:false,applications:0,corrections:0,blockedMoves:0,tableEdgeGap:GAP,lastError:null,checkedAt:null};
let scene,camera,renderer,table,seat,rigRef,raf=0,timer=0,last=0,internal=false,originalSet=null,originalCopy=null,wrapped=false;
const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),q=new THREE.Quaternion(),ray=new THREE.Raycaster();
function box(o){o?.updateWorldMatrix?.(true,true);const v=new THREE.Box3().setFromObject(o,true);return{box:v,size:v.getSize(new THREE.Vector3()),center:v.getCenter(new THREE.Vector3())}}
function valid(v){return !!v&&!v.box.isEmpty()&&v.size.x>1.2&&v.size.z>.65}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||window.SVR_PLAYER_RIG||window.__SVR_PLAYER_RIG||null}
function cam(){const v=renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;return v?.cameras?.[0]||v||camera}
function findTable(){for(const o of [window.SVR_TABLE_AUTHORITY,window.SVR_PHASE380_ORIGINAL_TABLE,scene?.getObjectByName?.('PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY'),scene?.getObjectByName?.('PHASE373_VISIBLE_TABLE_GLB_AUTHORITY'),table]){if(!o?.isObject3D)continue;try{if(valid(box(o)))return o}catch{}}return null}
function compute(){table=findTable()||table;if(!table)return null;const info=box(table);if(!valid(info))return null;table.updateWorldMatrix?.(true,false);const dir=new THREE.Vector3(0,0,1).transformDirection(table.matrixWorld);dir.y=0;if(dir.lengthSq()<1e-5)dir.set(0,0,1);dir.normalize();const origin=info.center.clone().addScaledVector(dir,Math.max(info.size.x,info.size.z)*3+4);origin.y=info.center.y;ray.set(origin,dir.clone().negate());let edge=null;try{edge=ray.intersectObject(table,true).find(hit=>hit.object?.isMesh)?.point?.clone()||null}catch{}if(!edge){const hx=Math.max(.4,info.size.x/2),hz=Math.max(.3,info.size.z/2),d=1/Math.sqrt(dir.x*dir.x/(hx*hx)+dir.z*dir.z/(hz*hz));edge=info.center.clone().addScaledVector(dir,d)}const head=edge.clone().addScaledVector(dir,GAP);head.y=info.box.max.y+EYE_ABOVE;const look=info.center.clone();look.y=info.box.max.y+.05;return{info,dir,edge,head,look}}
function wrapMovement(){const r=rig();if(!r?.position||wrapped)return false;rigRef=r;originalSet=r.position.set.bind(r.position);originalCopy=r.position.copy.bind(r.position);r.position.set=function(x,y,z){if(!internal){state.blockedMoves++;return this}return originalSet(x,y,z)};r.position.copy=function(v){if(!internal){state.blockedMoves++;return this}return originalCopy(v)};for(const name of ['teleport','teleportTo','moveTo','setTeleportPosition','setPosition','setPlayerPose']){const old=r[name];if(typeof old!=='function')continue;r[name]=function(...args){if(!internal){state.blockedMoves++;return false}return old.apply(this,args)}}wrapped=true;return true}
function lock(){for(const key of FLAGS)window[key]=false;window.SVR_TABLE_MOVEMENT_LOCKED=true;window.SVR_PHASE388_FRONT_SOUTH_LOCK=true}
function neutralize(){if(window.SVR_PHASE361_STATE){window.SVR_PHASE361_STATE.seated=false;window.SVR_PHASE361_STATE.mode='phase388-front-south'}document.body.classList.remove('svr361-seated','svr363-seated','svr365-seated','svr381-seated-lock');document.body.classList.add('svr388-direct-seated','svr388-front-south');document.body.dataset.svrSeated='false'}
function face(target){const r=rig(),head=cam();if(!r?.rotation||!head)return;head.getWorldQuaternion(q);a.set(0,0,-1).applyQuaternion(q);a.y=0;if(a.lengthSq()<1e-5)return;a.normalize();head.getWorldPosition(b);c.set(target.x-b.x,0,target.z-b.z);if(c.lengthSq()<1e-5)return;c.normalize();let delta=Math.atan2(c.x,c.z)-Math.atan2(a.x,a.z);delta=Math.atan2(Math.sin(delta),Math.cos(delta));r.rotation.y+=delta}
function move(reason='manual',turn=false){seat=compute();const r=rig(),head=cam();if(!seat||!r?.position||!head)return false;head.getWorldPosition(a);r.getWorldPosition(b);c.copy(b).add(seat.head).sub(a);let local=c.clone();if(r.parent){r.parent.updateWorldMatrix?.(true,false);local=r.parent.worldToLocal(local)}internal=true;try{originalSet?originalSet(local.x,local.y,local.z):r.position.set(local.x,local.y,local.z)}finally{internal=false}if(turn)face(seat.look);neutralize();lock();state.frontSeatReady=true;state.applications++;state.lastReason=reason;return true}
function patchApis(){for(const name of ['SVR_PHASE361_LOBBY_SPAWN','SVR_PHASE361_PLAY_GAME','SVR_PHASE361_RESEAT','SVR_PHASE373_STABLE_LOBBY','SVR_PHASE373_STABLE_SEAT','SVR_PHASE364_LOBBY_SPAWN','SVR_PHASE364_SEAT','SVR_PHASE387_DIRECT_SEAT','SVR_PHASE388_DIRECT_SEAT']){const f=(...args)=>move(`${name}:${args[0]||'api'}`,true);f.__p388=true;window[name]=f}}
function correct(t=0){if(!seat||t-last<70)return;last=t;const head=cam();if(!head)return;head.getWorldPosition(a);if(Math.hypot(a.x-seat.head.x,a.z-seat.head.z)>.032||Math.abs(a.y-seat.head.y)>.075){if(move('continuous-front-south',false))state.corrections++}}
function burst(reason){for(const delay of [0,50,120,240,450,800,1300,2200,3800,6500])setTimeout(()=>move(`${reason}-${delay}`,delay<500),delay)}
function frame(t=0){if(!ACTIVE||!state.installed)return;neutralize();lock();patchApis();correct(t);raf=requestAnimationFrame(frame)}
async function install(){if(!ACTIVE||state.installed)return;const start=performance.now();while(performance.now()-start<30000){scene=window.__SVR_SCENE__||scene;camera=window.__SVR_CAMERA__||camera;renderer=window.__SVR_RENDERER__||renderer;table=findTable()||table;if(scene&&camera&&renderer&&rig()&&table)break;await new Promise(r=>setTimeout(r,80))}if(!scene||!camera||!renderer||!rig()||!table){state.lastError='FRONT_SOUTH_RUNTIME_NOT_READY';return}wrapMovement();patchApis();state.installed=true;renderer.xr?.addEventListener?.('sessionstart',()=>burst('xr-session-start'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)burst('visibility-return')});burst('install');timer=setInterval(()=>{neutralize();lock();patchApis();move('interval',false)},500);raf=requestAnimationFrame(frame);window.addEventListener('beforeunload',()=>{clearInterval(timer);cancelAnimationFrame(raf);if(wrapped&&rigRef?.position){rigRef.position.set=originalSet;rigRef.position.copy=originalCopy}},{once:true})}
function qa(){state.checkedAt=new Date().toISOString();const head=cam();const pos=new THREE.Vector3();head?.getWorldPosition?.(pos);return{...state,head:{x:+pos.x.toFixed(3),y:+pos.y.toFixed(3),z:+pos.z.toFixed(3)},target:seat?{x:+seat.head.x.toFixed(3),y:+seat.head.y.toFixed(3),z:+seat.head.z.toFixed(3)}:null,pass:state.installed&&state.frontSeatReady}}
if(ACTIVE)install().catch(e=>state.lastError=String(e?.stack||e));
window.SVR_PHASE388_FRONT_SOUTH_SEAT=move;window.SVR_PHASE388_FRONT_SOUTH_QA=qa;window.SVR_PHASE388_FRONT_SOUTH_STATE=state;
