/* PHASE-419-TOURNAMENT-REGISTRATION-NOTIFICATION-LOCK */
const BUILD='PHASE-419-TOURNAMENT-REGISTRATION-NOTIFICATION-LOCK';
const SLOT_MS=5*60*60*1000,ANCHOR=Date.UTC(2026,0,1,0,0,0),CAP=100;
const LOCAL_KEY='svr419_tournament_registrations_v1',PLAYER_KEY='svr419_local_player_id',NOTIFY_KEY='svr419_tournament_notify_v1';
const runtime={build:BUILD,installed:false,apiBase:'',sharedBackend:false,backgroundPushLive:false,targetSlot:null,roster:[],registered:false,notificationPermission:typeof Notification==='undefined'?'unsupported':Notification.permission,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s),now=()=>Date.now(),slotId=t=>Math.floor((t-ANCHOR)/SLOT_MS),slot=id=>({id,start:ANCHOR+id*SLOT_MS,end:ANCHOR+(id+1)*SLOT_MS});
const targetSlot=()=>slot(slotId(now())+1);
const safeName=value=>String(value||'').trim().replace(/\s+/g,' ').slice(0,40);
const initials=name=>safeName(name).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'G';
function localPlayerId(){let id='';try{id=localStorage.getItem(PLAYER_KEY)||''}catch{}if(id)return id;id=`local-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;try{localStorage.setItem(PLAYER_KEY,id)}catch{}return id}
function accountIdentity(){try{const a=window.SVR_PLAYER_ACCOUNT?.snapshot?.()||window.SVR_PLAYER_ACCOUNT_STATE||null;if(a?.profile)return{playerId:String(a.profile.playerId||a.profile.id||localPlayerId()),displayName:safeName(a.profile.displayName||a.profile.name||'Player'),source:a.mode==='api'?'account':'local-account'}}catch{}try{const a=JSON.parse(localStorage.getItem('svr_demo_account')||'null');if(a?.profile)return{playerId:String(a.profile.playerId||localPlayerId()),displayName:safeName(a.profile.displayName||'Player'),source:'local-account'}}catch{}return{playerId:localPlayerId(),displayName:safeName(localStorage.getItem('svr405_guest_name')||'Guest 1'),source:'guest-test'}}
function readLocal(){try{const v=JSON.parse(localStorage.getItem(LOCAL_KEY)||'{}');return v&&typeof v==='object'?v:{}}catch{return{}}}
function writeLocal(v){try{localStorage.setItem(LOCAL_KEY,JSON.stringify(v))}catch{}return v}
function localRoster(id){const all=readLocal(),rows=Array.isArray(all[id])?all[id]:[];return rows.slice().sort((a,b)=>Date.parse(a.registeredAt||0)-Date.parse(b.registeredAt||0))}
function saveLocalRegistration(id,row){const all=readLocal(),rows=Array.isArray(all[id])?all[id]:[],idx=rows.findIndex(x=>x.playerId===row.playerId);if(idx>=0)rows[idx]={...rows[idx],displayName:row.displayName,source:row.source};else rows.push(row);all[id]=rows.slice(0,CAP);writeLocal(all);return localRoster(id)}
async function loadConfig(){try{const response=await fetch('./config/tournament-api.json?v=phase419',{cache:'no-store'});if(!response.ok)return;const cfg=await response.json();runtime.apiBase=String(window.SVR_TOURNAMENT_API_BASE||cfg.apiBase||'').replace(/\/$/,'');runtime.sharedBackend=Boolean(runtime.apiBase&&cfg.sharedRegistrationBackendLive);runtime.backgroundPushLive=Boolean(cfg.backgroundPushLive)}catch(error){runtime.lastError=`config: ${error.message}`}}
async function remoteRoster(id){if(!runtime.sharedBackend||!runtime.apiBase)return null;const response=await fetch(`${runtime.apiBase}/api/tournaments/${encodeURIComponent(id)}/registrations`,{cache:'no-store',headers:{Accept:'application/json'}});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP ${response.status}`);return Array.isArray(data.registrations)?data.registrations:[]}
async function remoteRegister(id,row){if(!runtime.sharedBackend||!runtime.apiBase)return null;const response=await fetch(`${runtime.apiBase}/api/tournaments/${encodeURIComponent(id)}/register`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({playerId:row.playerId,displayName:row.displayName,source:'mobile-play-money-test'})});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP ${response.status}`);return data}
function fmtDate(t){try{return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(t))}catch{return new Date(t).toLocaleString()}}
function fmtTime(t){try{return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit',second:'2-digit'}).format(new Date(t))}catch{return new Date(t).toLocaleTimeString()}}
function countdown(ms){const total=Math.max(0,Math.floor(ms/1000)),h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return`${h}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`}
function paintRoster(rows){runtime.roster=rows.slice(0,CAP);const list=$('#phase419Roster'),count=$('#phase419RosterCount'),portal=$('#phase419SignupCount');if(count)count.textContent=`${runtime.roster.length} / ${CAP} SIGNED UP`;if(portal)portal.textContent=`${runtime.roster.length} signed up for next slot`;if(!list)return;if(!runtime.roster.length){list.innerHTML='<div class="p419-empty">No human test players signed up yet. Open seats will still be bot-filled for the prototype.</div>';return}list.innerHTML=runtime.roster.map((r,i)=>`<article class="p419-person"><div class="p419-avatar">${initials(r.displayName)}</div><div><strong>${escapeHtml(r.displayName||`Player ${i+1}`)}</strong><span>${escapeHtml(String(r.source||'test signup').replace(/-/g,' '))}</span></div><span class="p419-time">${escapeHtml(fmtDate(r.registeredAt||Date.now()))}</span></article>`).join('')}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function setStatus(text,type=''){const el=$('#phase419Status');if(!el)return;el.textContent=text;el.className=`p419-status ${type}`}
async function refreshRoster(){const t=runtime.targetSlot||targetSlot();let rows=localRoster(t.id);try{const remote=await remoteRoster(t.id);if(remote)rows=remote}catch(error){runtime.lastError=`roster: ${error.message}`;setStatus('Shared roster is unavailable; showing this device’s signups.','warn')}paintRoster(rows);const me=accountIdentity();runtime.registered=rows.some(r=>String(r.playerId)===String(me.playerId));const submit=$('#phase419Signup');if(submit)submit.textContent=runtime.registered?'SIGNED UP':'SIGN UP FOR NEXT TOURNAMENT';return rows}
async function register(){const t=runtime.targetSlot||targetSlot(),input=$('#phase419DisplayName'),me=accountIdentity(),displayName=safeName(input?.value||me.displayName);if(displayName.length<2){setStatus('Enter a player name with at least 2 characters.','error');return}const row={playerId:me.playerId,displayName,source:runtime.sharedBackend?'shared-registration':me.source,registeredAt:new Date().toISOString(),slotId:t.id};let remoteOk=false;try{const result=await remoteRegister(t.id,row);remoteOk=Boolean(result);if(result?.registration)Object.assign(row,result.registration)}catch(error){runtime.lastError=`register: ${error.message}`}saveLocalRegistration(t.id,row);try{localStorage.setItem('svr405_guest_name',displayName)}catch{}await refreshRoster();setStatus(remoteOk?'Registration saved to the shared test roster.':'Registration saved on this device. Shared roster will activate when the tournament API is deployed.','ok');const form=$('#phase419Form');if(form)form.dataset.registered='1'}
function readNotify(){try{return JSON.parse(localStorage.getItem(NOTIFY_KEY)||'{}')}catch{return{}}}
function writeNotify(v){try{localStorage.setItem(NOTIFY_KEY,JSON.stringify(v))}catch{}return v}
async function enableNotification(){if(typeof Notification==='undefined'){setStatus('System notifications are not supported in this browser. The in-app start banner still works.','warn');return false}let permission=Notification.permission;if(permission==='default')permission=await Notification.requestPermission();runtime.notificationPermission=permission;if(permission!=='granted'){setStatus('Notification permission was not granted. The tournament page will still show the start banner.','warn');return false}const t=runtime.targetSlot||targetSlot(),n=readNotify();n.slotId=t.id;n.enabled=true;n.delivered=false;n.enabledAt=new Date().toISOString();writeNotify(n);paintNotifyButton();setStatus(runtime.backgroundPushLive?'Tournament start notification enabled.':'Start notification enabled for this device while the app/browser remains active. Background push still requires the live push backend.','ok');return true}
function paintNotifyButton(){const b=$('#phase419Notify'),n=readNotify(),t=runtime.targetSlot||targetSlot();if(!b)return;const on=Boolean(n.enabled&&Number(n.slotId)===Number(t.id));b.textContent=on?'START ALERT ON':'ENABLE START NOTIFICATION';b.classList.toggle('enabled',on)}
async function fireNotification(t){const n=readNotify();if(!n.enabled||Number(n.slotId)!==Number(t.id)||n.delivered)return false;n.delivered=true;n.deliveredAt=new Date().toISOString();writeNotify(n);const title='SVR Poker Tournament Started';const body='Your play-money tournament test slot has started. Tap to open the tournament lobby.';try{if(typeof Notification!=='undefined'&&Notification.permission==='granted'){if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:'/logo.png',badge:'/logo.png',tag:`svr-tournament-${t.id}`,data:{url:'/game/tournaments.html?v=phase419'}})}else new Notification(title,{body,icon:'/logo.png'})}}catch(error){runtime.lastError=`notify: ${error.message}`}const banner=$('#phase419StartBanner');if(banner){banner.classList.add('show');setTimeout(()=>banner.classList.remove('show'),7000)}return true}
function updateClock(){const t=runtime.targetSlot||targetSlot(),ms=t.start-now(),count=$('#phase419Countdown'),start=$('#phase419StartTime'),slotEl=$('#phase419SlotId');if(count)count.textContent=ms>0?countdown(ms):'STARTED';if(start)start.textContent=fmtDate(t.start);if(slotEl)slotEl.textContent=`#${t.id}`;if(ms<=0)fireNotification(t);const currentTarget=targetSlot();if(currentTarget.id!==t.id&&ms<-60000){runtime.targetSlot=currentTarget;paintNotifyButton();refreshRoster()}}
function installPage(){const form=$('#phase419Form');if(!form)return false;const me=accountIdentity(),input=$('#phase419DisplayName');if(input&&!input.value)input.value=me.displayName||'Guest 1';form.addEventListener('submit',event=>{event.preventDefault();register()});$('#phase419Notify')?.addEventListener('click',enableNotification);runtime.installed=true;return true}
async function boot(){await loadConfig();runtime.targetSlot=targetSlot();installPage();paintNotifyButton();await refreshRoster();updateClock();setInterval(updateClock,1000);setInterval(refreshRoster,15000);runtime.checkedAt=new Date().toISOString();window.SVR_PHASE419_TOURNAMENT_REGISTRATION_READY=true}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.SVR_PHASE419_TOURNAMENT_REGISTRATION_QA=()=>({build:BUILD,targetSlot:runtime.targetSlot,rosterCount:runtime.roster.length,registered:runtime.registered,apiBaseConfigured:Boolean(runtime.apiBase),sharedBackend:runtime.sharedBackend,backgroundPushLive:runtime.backgroundPushLive,notificationPermission:runtime.notificationPermission,localFallback:true,scheduleEveryHours:5,registrationCap:CAP,lastError:runtime.lastError,pass:Boolean(runtime.targetSlot&&CAP===100&&SLOT_MS===18000000),checkedAt:new Date().toISOString()});
