import * as THREE from 'three';
const LABEL='PHASE-220-STATIC-TABLE-HUD-NO-BOUNCE-LOCK';
const ROOT='PHASE220_STATIC_TABLE_HUD_NO_BOUNCE_ROOT';
let scene,camera,renderer,rootGroup,started=false,lastPosText='';
function sr(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function viewCam(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function camPos(){const p=new THREE.Vector3();viewCam()?.getWorldPosition(p);return p;}
function table(){const r=sr();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function rec(){const t=table();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{obj:t,b,s,c,top:b.max.y,innerW:Math.max(1.4,Math.min(s.x*.52,3.4)),innerD:Math.max(.8,Math.min(s.z*.40,1.7))};}
function makeTex(a,b=''){const c=document.createElement('canvas');c.width=1024;c.height=256;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.80)';x.fillRect(0,0,1024,256);x.strokeStyle='#7ffcff';x.lineWidth=8;x.strokeRect(10,10,1004,236);x.fillStyle='#fff';x.font='900 54px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(a,512,88,960);x.fillStyle='#ffd98a';x.font='800 34px system-ui';x.fillText(b,512,164,960);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function smallTex(s){const c=document.createElement('canvas');c.width=1024;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.72)';x.fillRect(0,0,1024,128);x.strokeStyle='#ffd98a';x.lineWidth=5;x.strokeRect(8,8,1008,112);x.fillStyle='#fff';x.font='800 34px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(s,512,66,960);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function hideBouncy(){let n=0;sr()?.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE218_TABLE_PLAY_PANEL|PHASE218_VISIBLE_PLAY_WATCH|PHASE218_WATCH|PHASE219_SMALL_POSITION_DISPLAY|PHASE219_OPTIONS_PANEL|PHASE217_TABLE_FIRST_STATUS_TAG|PHASE217_HIGH_TAG|PHASE215_HIGH|PHASE214_TABLE_STATUS/i.test(nm)){o.visible=false;o.traverse?.(c=>c.visible=false);n++;}});return n;}
function pauseTravel(){try{window.SVR_PHASE193_TELEPORT_OFF?.();window.SVR_PHASE170_TELEPORT_OFF?.();window.SVR_PHASE184_TELEPORT_OFF?.();}catch(e){}const r=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;if(r){try{r.setEnabled?.(false);r.setVisible?.(false);}catch(e){}}scene?.traverse?.(o=>{const n=String(o.name||'');if(/laser|pointer|ray|arc|target_ring|logo_target/i.test(n)){o.visible=false;if(o.material){o.material.opacity=0;o.material.transparent=true;}}});}
function build(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene)return null;const r=sr(),tr=rec();if(!tr)return null;const old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;r.add(rootGroup);const c=tr.c,iz=tr.innerD;
const panel=new THREE.Mesh(new THREE.PlaneGeometry(1.65,.42),new THREE.MeshBasicMaterial({map:makeTex('TABLE MODE','stable HUD • no camera follow'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));panel.name='PHASE220_STATIC_TABLE_MODE_HUD';panel.position.set(c.x,tr.top+1.42,c.z-iz*.72);panel.rotation.x=-.22;panel.renderOrder=2200;rootGroup.add(panel);
const pos=new THREE.Mesh(new THREE.PlaneGeometry(.9,.14),new THREE.MeshBasicMaterial({map:smallTex('POS WAITING'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));pos.name='PHASE220_STATIC_POSITION_READOUT';pos.position.set(c.x,tr.top+1.08,c.z+iz*.72);pos.rotation.x=-.25;pos.renderOrder=2201;rootGroup.add(pos);
return {table:tr.obj.name,top:+tr.top.toFixed(3)};}
function updateReadout(){if(!rootGroup)return;const p=camPos();const txt=`POS X ${p.x.toFixed(2)} Y ${p.y.toFixed(2)} Z ${p.z.toFixed(2)}`;if(txt===lastPosText)return;lastPosText=txt;const m=rootGroup.getObjectByName('PHASE220_STATIC_POSITION_READOUT');if(m?.material){m.material.map=smallTex(txt);m.material.needsUpdate=true;}}
function pass(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene)return null;const hidden=hideBouncy();pauseTravel();if(!rootGroup)build();updateReadout();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,noBounceHud:true,staticHudAnchoredToTable:true,hiddenBouncyPanels:hidden,travelPausedAtTable:true,checkedAt:new Date().toISOString()};window.SVR_PHASE220_STATIC_TABLE_HUD_NO_BOUNCE_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){const out=pass();window.SVR_RUN_PHASE220_NO_BOUNCE_AUDIT=()=>pass();if(!started){started=true;setInterval(pass,650);}return !!out;}
[400,1000,2200,4200,7000].forEach(ms=>setTimeout(install,ms));install();
