/* PHASE-422-QUEST-TABLE-GEOMETRY-THEME-LOCK */
import * as THREE from 'three';
export const BUILD='PHASE-422-QUEST-TABLE-GEOMETRY-THEME-LOCK';
export const FELT_RECESS_METERS=.0254;
const p=new URLSearchParams(location.search),ua=navigator.userAgent||'';
const ACTIVE=p.get('platform')==='quest'||p.get('direct')==='1'||p.get('questfix')==='1'||/Quest|Oculus|Meta Quest/i.test(ua);
const state={build:BUILD,active:ACTIVE,installed:false,tableFound:false,sourceSurfaceFound:false,sourceSurfaceName:null,sourceGeometryCloned:false,feltReady:false,recessMeters:null,railMaterials:0,bodyMaterials:0,lightingReady:false,proceduralShapeDisabled:true,fanTriangulationRiskRemoved:true,lastError:null,checkedAt:null};
const v=new THREE.Vector3(),v2=new THREE.Vector3(),q=new THREE.Quaternion();
let scene=null,renderer=null,table=null,source=null,surface=null,lights=null,texture=null;
function bounds(o){o?.updateWorldMatrix?.(true,true);const box=new THREE.Box3().setFromObject(o,true);return{box,size:box.getSize(new THREE.Vector3()),center:box.getCenter(new THREE.Vector3())}}
function tableRef(){return window.SVR_TABLE_AUTHORITY||window.SVR_PHASE380_ORIGINAL_TABLE||scene?.getObjectByName?.('PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY')||table||null}
function sourceFelt(){const candidates=[window.SVR_PHASE390_PLAY_SURFACE,window.SVR_PHASE421_PLAY_SURFACE,table?.getObjectByName?.('PHASE390_RECESSED_BRANDED_PLAYING_SURFACE'),table?.getObjectByName?.('PHASE421_FINAL_POLISHED_PLAYING_SURFACE'),scene?.getObjectByName?.('PHASE390_RECESSED_BRANDED_PLAYING_SURFACE'),scene?.getObjectByName?.('PHASE421_FINAL_POLISHED_PLAYING_SURFACE')];for(const candidate of candidates){if(candidate?.isMesh&&candidate.geometry){source=candidate;state.sourceSurfaceFound=true;state.sourceSurfaceName=candidate.name||'(unnamed)';return candidate}}return null}
function makeTexture(){if(texture)return texture;const c=document.createElement('canvas');c.width=2048;c.height=1024;const x=c.getContext('2d'),g=x.createRadialGradient(1024,480,60,1024,520,1180);g.addColorStop(0,'#211329');g.addColorStop(.42,'#09070d');g.addColorStop(1,'#010102');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.globalAlpha=.08;x.strokeStyle='#7b3a91';x.lineWidth=2;for(let i=-900;i<2900;i+=96){x.beginPath();x.moveTo(i,0);x.lineTo(i-520,1024);x.stroke()}x.globalAlpha=.045;x.strokeStyle='#27c8e8';for(let i=-900;i<2900;i+=150){x.beginPath();x.moveTo(i,0);x.lineTo(i+430,1024);x.stroke()}x.globalAlpha=1;x.strokeStyle='rgba(216,184,92,.78)';x.lineWidth=10;x.beginPath();x.ellipse(1024,512,900,400,0,0,Math.PI*2);x.stroke();x.strokeStyle='rgba(127,252,255,.90)';x.lineWidth=7;x.beginPath();x.ellipse(1024,512,815,340,0,0,Math.PI*2);x.stroke();x.fillStyle='rgba(255,255,255,.78)';x.font='800 32px system-ui';x.textAlign='center';x.fillText('PASS / BET LINE',1024,865);const image=new Image();image.crossOrigin='anonymous';image.onload=()=>{const s=Math.min(400/image.naturalWidth,285/image.naturalHeight),w=image.naturalWidth*s,h=image.naturalHeight*s;x.drawImage(image,1024-w/2,512-h/2,w,h);texture.needsUpdate=true};image.src='/logo.png?v=phase423';texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.ClampToEdgeWrapping;texture.anisotropy=Math.min(4,renderer?.capabilities?.getMaxAnisotropy?.()||2);texture.needsUpdate=true;return texture}
function makeFeltMaterial(){return new THREE.MeshStandardMaterial({map:makeTexture(),color:0xffffff,roughness:.97,metalness:0,emissive:0x08040b,emissiveIntensity:.035,side:THREE.DoubleSide,depthTest:true,depthWrite:true})}
function worldDeltaY(object,delta){if(!object)return false;if(!object.parent){object.position.y+=delta;return true}object.parent.updateWorldMatrix?.(true,false);object.parent.getWorldQuaternion(q).invert();object.parent.getWorldScale(v2);v.set(0,delta,0).applyQuaternion(q);v.x/=Math.abs(v2.x)>1e-6?v2.x:1;v.y/=Math.abs(v2.y)>1e-6?v2.y:1;v.z/=Math.abs(v2.z)>1e-6?v2.z:1;object.position.add(v);return true}
function ensureExactSurface(){if(surface?.parent)return true;const src=sourceFelt();if(!src)return false;src.updateWorldMatrix?.(true,false);surface=new THREE.Mesh(src.geometry.clone(),makeFeltMaterial());surface.name='PHASE422_TRUE_INNER_PLAYING_SURFACE';surface.userData={svrPhase422InnerSurface:true,recessMeters:FELT_RECESS_METERS,sourceSurface:src.name||null,sourceGeometryCloned:true,proceduralShape:false};src.matrixWorld.decompose(surface.position,surface.quaternion,surface.scale);scene.add(surface);table.attach(surface);surface.receiveShadow=true;surface.frustumCulled=false;surface.renderOrder=4220;window.SVR_PHASE422_PLAY_SURFACE=surface;state.sourceGeometryCloned=true;return true}
function hideLegacy(){scene?.traverse?.(o=>{if(!o?.isMesh||o===surface)return;const n=String(o.name||'');if(/PHASE390_RECESSED_BRANDED_PLAYING_SURFACE|PHASE393_VISIBLE_RECESSED_INNER_FELT|PHASE421_FINAL_POLISHED_PLAYING_SURFACE|PHASE38(?:4|6|8)_.*FELT|OFFICIAL_SITE_LOGO_FELT/i.test(n)||o.userData?.svrPhase421FinalFelt||o.userData?.svrPhase390BrandedSurface){o.visible=false;const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(m){m.colorWrite=false;m.needsUpdate=true}})}})}
function label(o){const ms=Array.isArray(o?.material)?o.material:[o?.material];return `${o?.name||''} ${ms.map(m=>m?.name||'').join(' ')}`.toLowerCase()}
function polish(){let rails=0,bodies=0;table?.traverse?.(o=>{if(!o?.isMesh||!o.material||o===source||o===surface)return;const text=label(o);if(/felt|cloth|baize|playing|tabletop|surface/.test(text))return;const rail=/armrest|handrest|rail|leather|padding|circle02|object001/.test(text),trim=/silver|chrome|metal|trim/.test(text),body=!rail&&!trim&&/base|body|frame|table|wood|object/.test(text);if(!rail&&!trim&&!body)return;const src=Array.isArray(o.material)?o.material:[o.material],next=src.map(e=>{if(e?.userData?.svr422)return e;const m=e?.clone?.()||new THREE.MeshStandardMaterial();m.userData={...(m.userData||{}),svr422:true,role:rail?'rail':trim?'trim':'body'};m.visible=true;m.transparent=false;m.opacity=1;m.depthTest=true;m.depthWrite=true;if(m.color&&!m.map)m.color.setHex(rail?0x120c17:trim?0x6d6f7c:0x251714);if('roughness'in m)m.roughness=rail?.38:trim?.26:.52;if('metalness'in m)m.metalness=rail?.04:trim?.68:.10;m.needsUpdate=true;return m});o.material=Array.isArray(o.material)?next:next[0];o.visible=true;o.receiveShadow=true;if(rail)rails+=next.length;else if(body)bodies+=next.length});state.railMaterials=rails;state.bodyMaterials=bodies}
function lighting(){if(lights?.parent)return true;const info=bounds(table);table.getWorldQuaternion(q);const right=v.set(1,0,0).applyQuaternion(q).setY(0).normalize();lights=new THREE.Group();lights.name='PHASE422_TABLE_LIGHTING';const key=new THREE.PointLight(0xae77d8,1.15,6.5,2),fill=new THREE.PointLight(0x63dff2,.65,5.0,2),gold=new THREE.PointLight(0xd8b85c,.42,4.2,2),hemi=new THREE.HemisphereLight(0xc2d9ef,0x120716,.48);key.position.copy(info.center).add(new THREE.Vector3(0,1.55,.1));fill.position.copy(info.center).addScaledVector(right,-1.2).add(new THREE.Vector3(0,.95,0));gold.position.copy(info.center).addScaledVector(right,1.18).add(new THREE.Vector3(0,.78,-.35));lights.add(key,fill,gold,hemi);scene.add(lights);state.lightingReady=true;return true}
function placeExactSurface(){if(!ensureExactSurface())return false;const whole=bounds(table),live=bounds(surface),targetTop=whole.box.max.y-FELT_RECESS_METERS;const delta=targetTop-live.box.max.y;if(Math.abs(delta)>.0005)worldDeltaY(surface,delta);const after=bounds(surface);state.recessMeters=+(whole.box.max.y-after.box.max.y).toFixed(4);state.feltReady=Math.abs(state.recessMeters-FELT_RECESS_METERS)<=.006;surface.visible=true;return state.feltReady}
export function topY(){return surface?bounds(surface).box.max.y:null}
export async function sweep(reason='manual'){if(!ACTIVE)return false;try{scene=window.__SVR_SCENE__||scene;renderer=window.__SVR_RENDERER__||renderer;table=tableRef()||table;if(!scene||!table)return false;state.tableFound=true;if(!sourceFelt())return false;if(!placeExactSurface())return false;hideLegacy();polish();lighting();state.installed=Boolean(state.feltReady&&state.sourceGeometryCloned&&state.lightingReady);state.lastError=null;state.checkedAt=new Date().toISOString();window.SVR_PHASE422_TABLE_THEME_STATE={...state,reason};return state.installed}catch(e){state.lastError=String(e?.stack||e?.message||e);state.checkedAt=new Date().toISOString();window.SVR_PHASE422_TABLE_THEME_STATE={...state,reason};return false}}
export function qa(){return{...state,targetRecessMeters:FELT_RECESS_METERS,targetRecessInches:1,innerSurfaceOnly:true,exactSourceGeometry:true,proceduralShape:false,curvedLeatherRailPreserved:true,pass:Boolean(state.installed&&state.feltReady&&state.sourceGeometryCloned&&!state.lastError),checkedAt:new Date().toISOString()}}
window.SVR_PHASE422_TABLE_THEME_SWEEP=sweep;window.SVR_PHASE422_TABLE_THEME_QA=qa;window.SVR_PHASE422_TABLE_ACTIVE=true;
if(ACTIVE){window.addEventListener('svr:phase396-core-ready',()=>setTimeout(()=>void sweep('core-ready'),260),{once:true});window.addEventListener('svr:hand-start',()=>setTimeout(()=>void sweep('hand-start'),90));window.addEventListener('svr:poker-state',()=>setTimeout(hideLegacy,45));[900,2600,5200].forEach(delay=>setTimeout(()=>void sweep(`settle-${delay}`),delay))}
