/* PHASE-412-TOURNAMENT-ACCOUNT-GATE-LOCK */
import { account } from '../../site/js/phase345-demo-activity-persistence.js?v=phase412';

const BUILD='PHASE-412-TOURNAMENT-ACCOUNT-GATE-LOCK';
const TEST_ACCOUNT_KEY='svr_phase412_tournament_test_account_v1';
const qs=new URLSearchParams(location.search);
const isTournamentPortal=/\/game\/tournaments\.html$/i.test(location.pathname);
const isTournamentGame=String(qs.get('mode')||'').toLowerCase()==='tournament';
const TOURNAMENT_TARGET='/game/android-tabletop.html?v=phase414&mode=tournament&tournament=reiki-open-100';
const RETURN_TARGET=isTournamentPortal?'/game/tournaments.html?v=phase414':'/game/android.html?channel=stable&v=phase414&mode=tournament';
const LOGIN_URL=`/site/tournament-account.html?next=${encodeURIComponent(RETURN_TARGET)}&source=tournament-gate&v=phase412`;
const state={build:BUILD,ready:false,required:Boolean(isTournamentPortal||isTournamentGame),eligible:false,mode:'loading',apiConfigured:false,apiHealthy:false,localTestAccount:false,productionAccount:false,blocked:false,lastError:null};

function safeJson(value){try{return JSON.parse(value||'null')}catch{return null}}
function snapshot(){return account.snapshot?.()||window.SVR_PLAYER_ACCOUNT_STATE||null}
function entitlement(snap=snapshot()){
  const profile=snap?.profile||null,mode=snap?.mode||'loading';
  const apiConfigured=Boolean(snap?.apiConfigured||account.state?.config?.apiBase),apiHealthy=Boolean(snap?.apiHealthy||account.state?.apiHealthy);
  const productionAccount=Boolean(profile&&mode==='api'&&!profile.demoMode);
  const testRegistration=safeJson(localStorage.getItem(TEST_ACCOUNT_KEY));
  const localTestAccount=Boolean(profile&&mode==='demo'&&testRegistration?.playerId&&testRegistration.playerId===profile.playerId);
  // Guest/demo play by itself is NOT tournament eligibility. Before the approved AWS account
  // backend is live, the player must explicitly create a named local tournament test account.
  // Once production auth is configured and healthy, only the API/Cognito account path passes.
  const eligible=apiConfigured&&apiHealthy?productionAccount:Boolean(productionAccount||localTestAccount);
  return{profile,mode,apiConfigured,apiHealthy,productionAccount,localTestAccount,eligible}
}
function updateState(info){Object.assign(state,{ready:true,eligible:info.eligible,mode:info.mode,apiConfigured:info.apiConfigured,apiHealthy:info.apiHealthy,localTestAccount:info.localTestAccount,productionAccount:info.productionAccount,blocked:state.required&&!info.eligible});window.SVR_PHASE412_TOURNAMENT_ACCOUNT_STATE={...state,checkedAt:new Date().toISOString()};return info}
function ensureStyle(){if(document.getElementById('phase412TournamentGateStyle'))return;const style=document.createElement('style');style.id='phase412TournamentGateStyle';style.textContent=`#phase412TournamentGate{position:fixed;inset:0;z-index:2147483600;display:grid;place-items:center;padding:max(18px,env(safe-area-inset-top)) max(14px,env(safe-area-inset-right)) max(18px,env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));background:rgba(1,4,11,.92);backdrop-filter:blur(12px)}#phase412TournamentGate[hidden]{display:none}.phase412-gate-card{width:min(520px,100%);border:1px solid rgba(141,255,180,.7);border-radius:24px;background:linear-gradient(180deg,rgba(10,20,31,.98),rgba(5,9,18,.98));padding:22px;text-align:center;box-shadow:0 28px 90px rgba(0,0,0,.55)}.phase412-gate-card img{width:78px;height:78px;object-fit:contain}.phase412-gate-kicker{margin:7px 0;color:#8dffb4;font:900 11px system-ui;letter-spacing:.12em}.phase412-gate-card h2{margin:7px 0 6px;font-size:26px}.phase412-gate-card p{color:#bfd4e7;line-height:1.45}.phase412-gate-actions{display:grid;gap:9px;margin-top:16px}.phase412-gate-actions a{display:flex;min-height:48px;align-items:center;justify-content:center;border-radius:14px;text-decoration:none;font-weight:950}.phase412-gate-primary{background:linear-gradient(135deg,#7ffcff,#9b4dff);color:#02040a}.phase412-gate-secondary{border:1px solid rgba(255,217,138,.7);color:#fff}.phase412-account-note{font-size:11px!important;color:#ffd98a!important}.phase412-account-chip{display:inline-flex;margin:8px 0;padding:6px 10px;border:1px solid rgba(255,255,255,.18);border-radius:999px;font:900 10px system-ui;letter-spacing:.08em}`;document.head.appendChild(style)}
function ensureOverlay(info){if(!state.required)return;ensureStyle();let overlay=document.getElementById('phase412TournamentGate');if(!overlay){overlay=document.createElement('section');overlay.id='phase412TournamentGate';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');document.body.appendChild(overlay)}if(info.eligible){overlay.hidden=true;return}const backend=info.apiConfigured?(info.apiHealthy?'PRODUCTION ACCOUNT REQUIRED':'ACCOUNT SERVICE TEMPORARILY OFFLINE'):'TOURNAMENT TEST ACCOUNT REQUIRED';const note=info.apiConfigured?'Sign in or create your SVR Poker account before entering a tournament. Practice mode remains available without tournament registration.':'Tournament entry requires a player identity. While AWS account setup is still in test configuration, use the account page to explicitly create a named LOCAL TOURNAMENT TEST ACCOUNT. Ordinary Guest 1 or generic Demo Player sessions are not tournament-eligible.';overlay.innerHTML=`<div class="phase412-gate-card"><img src="/logo.png" alt="SVR Poker"><div class="phase412-gate-kicker">PLAY-MONEY TOURNAMENT ACCESS</div><h2>Account Required</h2><div class="phase412-account-chip">${backend}</div><p>${note}</p><div class="phase412-gate-actions"><a class="phase412-gate-primary" href="${LOGIN_URL}">SIGN IN / CREATE ACCOUNT</a><a class="phase412-gate-secondary" href="/game/android.html?channel=stable&v=phase414&mode=practice">PLAY PRACTICE INSTEAD</a></div><p class="phase412-account-note">Fake-money testing only. No purchase is required to create a player identity.</p></div>`;overlay.hidden=false}
function updatePortal(info){const enter=document.getElementById('enterTournament');if(!enter)return;if(info.eligible){enter.href=TOURNAMENT_TARGET;enter.dataset.accountGate='passed';enter.classList.remove('phase412-account-required');if(!/RESUME|START CURRENT/i.test(enter.textContent||''))enter.textContent='ENTER TOURNAMENT'}else{enter.href=LOGIN_URL;enter.dataset.accountGate='required';enter.classList.add('phase412-account-required');enter.textContent='LOGIN / CREATE ACCOUNT TO ENTER'}let chip=document.getElementById('phase412AccountStatus');if(!chip){chip=document.createElement('div');chip.id='phase412AccountStatus';chip.className='phase412-account-chip';enter.closest('.tournament-actions')?.insertAdjacentElement('beforebegin',chip)}chip.textContent=info.eligible?`${info.productionAccount?'ACCOUNT VERIFIED':'LOCAL TOURNAMENT TEST ACCOUNT'} • READY`:'ACCOUNT REQUIRED • PRACTICE STAYS OPEN'}
async function refresh(){try{await account.bootstrap();const info=updateState(entitlement());if(isTournamentPortal)updatePortal(info);if(isTournamentGame)ensureOverlay(info);state.lastError=null}catch(error){state.lastError=String(error?.message||error);state.ready=true;state.blocked=state.required;ensureOverlay({eligible:false,apiConfigured:false,apiHealthy:false});window.SVR_PHASE412_TOURNAMENT_ACCOUNT_STATE={...state,checkedAt:new Date().toISOString()}}}

window.addEventListener('svr:account-change',refresh);
window.addEventListener('svr:account-ready',refresh);
refresh();
window.SVR_PHASE412_TOURNAMENT_ACCOUNT_QA=()=>({build:BUILD,...state,portal:isTournamentPortal,tournamentGame:isTournamentGame,enterTarget:document.getElementById('enterTournament')?.getAttribute('href')||null,guestOneTournamentEligible:false,genericDemoTournamentEligible:false,practiceGuestAllowed:true,productionRequirementWhenApiLive:true,explicitLocalTestAccountRequiredBeforeApiLive:true,phase414HumanTurnRoute:true,pass:Boolean(state.ready&&(!state.required||state.eligible||state.blocked)),checkedAt:new Date().toISOString()});
