/* PHASE-401-ANDROID-24H-TOURNAMENT-CHAMPION-CROWN-LOCK */
const BUILD='PHASE-401-ANDROID-24H-TOURNAMENT-CHAMPION-CROWN-LOCK';
const KEY='svr401_tournament_crown';
const RESULTS='svr401_reiki_first50_results';
const DURATION_MS=24*60*60*1000;
const $=s=>document.querySelector(s);
const state={build:BUILD,active:false,expiresAt:null,remainingMs:0,tableBadges:0,lastError:null,checkedAt:null};
function maybeAwardFromResults(){try{const result=JSON.parse(localStorage.getItem(RESULTS)||'null');if(!result?.champion?.isUser||!result.completedAt)return;const awardId=`${result.id||'reiki-first-50'}:${result.completedAt}`,existing=JSON.parse(localStorage.getItem(KEY)||'null');if(existing?.awardId===awardId)return;const completedAt=Date.parse(result.completedAt)||Date.now(),crown={awardId,type:'reiki-tournament-champion',sponsor:result.sponsor||'REIKI',tournamentId:result.id||'reiki-first-50',awardedAt:completedAt,expiresAt:completedAt+DURATION_MS};if(crown.expiresAt>Date.now())localStorage.setItem(KEY,JSON.stringify(crown))}catch{}}
function read(){try{maybeAwardFromResults();const value=JSON.parse(localStorage.getItem(KEY)||'null');if(value?.expiresAt&&Number(value.expiresAt)>Date.now())return value;if(value)localStorage.removeItem(KEY)}catch{}return null}
function labelRemaining(ms){const hours=Math.floor(ms/3600000),mins=Math.floor((ms%3600000)/60000);return`${Math.max(0,hours)}h ${Math.max(0,mins)}m`}
function ensureProfileBadge(crown){const profile=$('.profile-pill');if(!profile)return;let badge=$('#phase401ChampionCrown');if(!crown){badge?.remove();return}if(!badge){badge=document.createElement('div');badge.id='phase401ChampionCrown';badge.className='phase401-champion-crown';profile.appendChild(badge)}badge.innerHTML=`<span class="phase401-crown-icon">👑</span><span><strong>REIKI CHAMPION</strong><small>${labelRemaining(crown.expiresAt-Date.now())} LEFT</small></span>`}
function syncSeatBadges(crown){document.querySelectorAll('.phase401-seat-crown').forEach(el=>el.remove());document.querySelectorAll('.player-box[data-champion="true"]').forEach(el=>delete el.dataset.champion);let count=0;const game=window.SVR_PHASE393_ANDROID_STATE;for(const player of game?.players||[]){const expires=player.championCrownExpiresAt||(player.index===0?crown?.expiresAt:null);if(!expires||Number(expires)<=Date.now())continue;const seat=$(`[data-player="${player.index}"]`);if(!seat)continue;const badge=document.createElement('span');badge.className='phase401-seat-crown';badge.title='Reiki Tournament Champion — 24 hour badge';badge.textContent='👑';seat.appendChild(badge);seat.dataset.champion='true';count++}state.tableBadges=count}
function sync(){try{const crown=read();state.active=Boolean(crown);state.expiresAt=crown?.expiresAt||null;state.remainingMs=crown?Math.max(0,crown.expiresAt-Date.now()):0;ensureProfileBadge(crown);const game=window.SVR_PHASE393_ANDROID_STATE;if(game?.players?.[0]){game.players[0].championCrownExpiresAt=crown?.expiresAt||null;game.players[0].championBadge=crown?'REIKI CHAMPION':null}syncSeatBadges(crown);document.body.classList.toggle('phase401-champion-active',Boolean(crown));state.checkedAt=new Date().toISOString();window.SVR_PHASE401_CHAMPION_BADGE_METADATA=crown?{type:crown.type,expiresAt:crown.expiresAt,sponsor:crown.sponsor,tournamentId:crown.tournamentId,awardId:crown.awardId}:null}catch(error){state.lastError=String(error?.message||error)}}
function qa(){sync();return{...state,durationHours:24,persistentExpiry:true,resultsTriggered:true,multiplayerMetadataReady:true,pass:!state.lastError,checkedAt:new Date().toISOString()}}
setInterval(sync,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync();window.SVR_PHASE401_CHAMPION_CROWN_QA=qa;
