/* PHASE-406-TOURNAMENT-24H-RESULTS-BOARD-LOCK */
const BUILD='PHASE-406-TOURNAMENT-24H-RESULTS-BOARD-LOCK',ARCHIVE='svr405_tournament_archive',RESULTS='svr401_reiki_first50_results',DAY=24*60*60*1000;
const $=s=>document.querySelector(s);const parse=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
function ts(row){const value=row?.completedAt||row?.startedAt||0,t=Date.parse(value);return Number.isFinite(t)?t:0}
function rows(){try{window.SVR_PHASE405_TOURNAMENT_SCHEDULE?.()}catch{}const cutoff=Date.now()-DAY,out=parse(ARCHIVE,[]).filter(Boolean);const current=parse(RESULTS,null);if(current?.completedAt)out.push({slotId:`played-${current.completedAt}`,source:'local-play',name:current.name||'REIKI FIRST 50',completedAt:current.completedAt,champion:current.champion?.name||current.champion||'Winner',prizePlayChips:Number(current.prizePlayChips||100000)});const seen=new Set();return out.filter(row=>ts(row)>=cutoff).sort((a,b)=>ts(b)-ts(a)).filter(row=>{const key=`${row.slotId||''}|${row.completedAt||''}|${row.champion||''}`;if(seen.has(key))return false;seen.add(key);return true}).slice(0,16)}
function markup(){const data=rows();return`<section id="phase406Tournament24h" class="results-card" style="margin-top:18px"><div class="tournament-kicker">ROLLING LOCAL RESULTS</div><h2>Last 24 Hours • Tournament Winners</h2><p class="note">Play-money test results saved on this browser/device. Unattended schedule rows are labeled BOT TEST. Shared cross-device results require the secure tournament backend.</p>${data.length?`<div style="display:grid;gap:7px">${data.map(row=>`<div style="display:grid;grid-template-columns:70px minmax(0,1fr) auto;gap:8px;align-items:center;padding:9px;border:1px solid #ffffff22;border-radius:12px;background:#07121c"><small style="color:#9fb6c9">${new Date(ts(row)).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}<br>${row.source==='local-play'?'PLAYED':'BOT TEST'}</small><div><strong style="display:block;color:#ffd98a">${row.champion||'Winner'}</strong><span style="color:#bfd4e7;font-size:10px">${row.name||'REIKI FIVE-HOUR TEST'}</span></div><strong style="color:#8dffb4;text-align:right">${Number(row.prizePlayChips||100000).toLocaleString()}<br><small>PLAY CHIPS</small></strong></div>`).join('')}</div>`:'<div class="empty">No completed tournament result has been saved in the last 24 hours on this device.</div>'}<p class="note" style="color:#8dffb4">Prototype placement payouts: 1st 100,000 • 2nd 50,000 • 3rd 25,000 play chips • NO CASH VALUE.</p></section>`}
function install(){if($('#phase406Tournament24h'))return;const target=$('.hands-card')||$('.footer-note');if(target)target.insertAdjacentHTML('beforebegin',markup());else document.querySelector('main')?.insertAdjacentHTML('beforeend',markup())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.SVR_PHASE406_TOURNAMENT_24H_QA=()=>({build:BUILD,rows:rows().length,board:Boolean($('#phase406Tournament24h')),rollingHours:24,playMoneyOnly:true,noCashValue:true,pass:Boolean($('#phase406Tournament24h')),checkedAt:new Date().toISOString()});
