import * as THREE from 'three';
const LABEL='PHASE-196-TABLE-SKY-LOGO-AUTHORITY-LOCK';
const ROOT='PHASE196_TABLE_SKY_LOGO_AUTHORITY_ROOT';
const SKY='PHASE196_SKY_AUTHORITY_ROOT';
const LOGO='PHASE196_ORIGINAL_LOBBY_LOGO_LOCK';
let scene,camera,renderer,root,skyRoot,logoPromise=null,started=false,moon,mars,stars=[];
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.76,metalness:.04,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.95});}
function img(u){return new Promise(r=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=()=>r(null);i.src=u;});}
async function logoAsset(){if(logoPromise)return logoPromise;logoPromise=(async()=>{for(const u of ['/logo.png','/logo.webp','./logo.png','./assets/logo.png','./ui/logo.png','./assets/ui/logo.png']){const im=await img(u);if(im)return {img:im,url:u};}return null;})();return logoPromise;}
function tableInfo(){const r=sr(scene);let t=r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('FBX_TABLE_ROOT');if(!t){let found=null;r?.traverse?.(o=>{if(found)return;const n=String(o.name||'').toLowerCase();if(/fbx.*table|table.*fbx|actual.*table/.test(n))found=o;});t=found;}if(!t)return null;t.visible=true;t.traverse?.(o=>{o.visible=true;if(o.isMesh){const n=String(o.name||'').toLowerCase();if(/leather|hand|rest|rail|rim|edge|cushion/.test(n))o.material=mat(0x23120c);else if(/felt|cloth|top|surface/.test(n))o.material=mat(0x064126);else if(!o.material)o.material=mat(0x2a211c);o.castShadow=true;o.receiveShadow=true;}});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),c=new THREE.Vector3(),s=new THREE.Vector3();b.getCenter(c);b.getSize(s);return {obj:t,center:c,size:s};}
function makeLogoTexture(asset){const c=document.createElement('canvas');c.width=c.height=1536;const x=c.getContext('2d'),cx=768,cy=768;x.clearRect(0,0,1536,1536);const g=x.createRadialGradient(cx,cy,80,cx,cy,760);g.addColorStop(0,'rgba(127,252,255,.36)');g.addColorStop(.62,'rgba(68,20,150,.26)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,1536,1536);x.strokeStyle='rgba(127,252,255,.96)';x.lineWidth=22;x.beginPath();x.arc(cx,cy,745,0,Math.PI*2);x.stroke();x.strokeStyle='rgba(238,191,92,.86)';x.lineWidth=12;x.beginPath();x.arc(cx,cy,675,0,Math.PI*2);x.stroke();if(asset?.img){const s=1120;x.drawImage(asset.img,cx-s/2,cy-s/2,s,s);}else{x.textAlign='center';x.textBaseline='middle';x.fillStyle='#7ffcff';x.font='900 310px system-ui';x.fillText('SVR',cx,cy-70);x.fillStyle='#eebf5c';x.font='900 112px system-ui';x.fillText('POKER',cx,cy+158);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;}
async function installLogo(center){const r=sr(scene);[LOGO,'PHASE192_CENTER_LOGO_FILL','PHASE191_CENTER_LOGO_CARPET_FULL_CIRCLE','PHASE190_MAX_CENTER_LOGO_CARPET'].forEach(n=>{const o=r?.getObjectByName?.(n);if(o)o.parent?.remove(o);});const asset=await logoAsset();const g=new THREE.Group();g.name=LOGO;g.position.set(center.x,.029,center.z);const m=new THREE.Mesh(new THREE.PlaneGeometry(13.9,13.9),new THREE.MeshBasicMaterial({map:makeLogoTexture(asset),transparent:true,side:THREE.DoubleSide,depthWrite:false,alphaTest:.01}));m.name='PHASE196_ORIGINAL_LOBBY_LOGO_FULL_CIRCLE';m.rotation.x=-Math.PI/2;m.renderOrder=1960;g.add(m);r?.add(g);return {url:asset?.url||'fallback',size:13.9,x:+center.x.toFixed(3),z:+center.z.toFixed(3)};}
function sphereTex(kind){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');const bg=kind==='moon'?'#cfd3d6':'#b95431';x.fillStyle=bg;x.fillRect(0,0,512,512);for(let i=0;i<90;i++){const px=Math.random()*512,py=Math.random()*512,r=kind==='moon'?Math.random()*24+3:Math.random()*18+2;x.fillStyle=kind==='moon'?`rgba(70,70,70,${.08+Math.random()*.16})`:`rgba(80,20,8,${.12+Math.random()*.2})`;x.beginPath();x.arc(px,py,r,0,Math.PI*2);x.fill();}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function buildSky(){const old=scene.getObjectByName?.(SKY);if(old)old.parent?.remove(old);skyRoot=new THREE.Group();skyRoot.name=SKY;scene.add(skyRoot);const moonMat=new THREE.MeshStandardMaterial({map:sphereTex('moon'),emissive:0x556677,emissiveIntensity:.18,roughness:.82});moon=new THREE.Mesh(new THREE.SphereGeometry(2.25,64,32),moonMat);moon.name='PHASE196_ROTATING_MOON_VISIBLE_NORTH_SKY';skyRoot.add(moon);const glow=new THREE.Mesh(new THREE.SphereGeometry(2.55,48,24),basic(0xbfdcff,.18));glow.name='PHASE196_MOON_ATMOSPHERE_GLOW';moon.add(glow);const marsMat=new THREE.MeshStandardMaterial({map:sphereTex('mars'),emissive:0x551800,emissiveIntensity:.15,roughness:.78});mars=new THREE.Mesh(new THREE.SphereGeometry(.72,48,24),marsMat);mars.name='PHASE196_MARS_ORBITS_MOON';skyRoot.add(mars);const starGeo=new THREE.BufferGeometry();const pts=[];for(let i=0;i<360;i++){pts.push((Math.random()-.5)*90,Math.random()*32+10,(Math.random()-.5)*90);}starGeo.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));const starMat=new THREE.PointsMaterial({color:0xddeeff,size:.08,transparent:true,opacity:.82});const st=new THREE.Points(starGeo,starMat);st.name='PHASE196_MORE_STARS_SKY_FIELD';skyRoot.add(st);stars.push(st);}
function updateSky(){if(!moon||!mars)return;const t=performance.now()/1000;moon.position.set(Math.sin(t*.045)*4,16.5, -27+Math.cos(t*.045)*2);moon.rotation.y+=.0025;moon.rotation.x+=.0007;const r=4.3,a=t*.18;mars.position.set(moon.position.x+Math.cos(a)*r,moon.position.y+Math.sin(a*.7)*.7,moon.position.z+Math.sin(a)*r);mars.rotation.y+=.0045;window.SVR_PHASE196_SKY_STATUS={build:LABEL,moonVisible:true,marsVisible:true,moonRotating:true,marsOrbitingMoon:true,checkedAt:iso()};}
function removeFakePlanets(){let n=0;const kill=[];scene?.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/PHASE196/.test(nm))return;if(/fake.*moon|duplicate.*moon|geometry.*moon|fake.*mars|duplicate.*mars|geometry.*mars/i.test(nm))kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
async function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);const table=tableInfo();const logo=await installLogo(table?.center||new THREE.Vector3(0,0,0));const removedPlanets=removeFakePlanets();buildSky();window.SVR_PHASE196_TABLE_SKY_LOGO_AUTHORITY_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,fbxTableFound:!!table,fbxTableVisible:!!table,originalLobbyLogo:logo,moonAuthority:true,marsAuthority:true,removedFakePlanets:removedPlanets,checkedAt:iso()};window.SVR_RUN_PHASE196_AUDIT=()=>({lock:window.SVR_PHASE196_TABLE_SKY_LOGO_AUTHORITY_LOCK,sky:window.SVR_PHASE196_SKY_STATUS});window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(updateSky,33);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
