/* PHASE-422-QUEST-TABLE-GEOMETRY-THEME-LOCK */
import * as THREE from 'three';
export const BUILD='PHASE-422-QUEST-TABLE-GEOMETRY-THEME-LOCK';
export const FELT_RECESS_METERS=.0254;
const p=new URLSearchParams(location.search),ua=navigator.userAgent||'';
const ACTIVE=p.get('platform')==='quest'||p.get('direct')==='1'||p.get('questfix')==='1'||/Quest|Oculus|Meta Quest/i.test(ua);
const state={build:BUILD,active:ACTIVE,installed:false,tableFound:false,feltReady:false,recessMeters:null,railMaterials:0,bodyMaterials:0,lightingReady:false,lastError:null,checkedAt:null};
const v=new THREE.Vector3(),q=new THREE.Quaternion();
let scene=null,renderer=null,table=null,surface=null,lights=null,texture=null;
function bounds(o){o?.updateWorldMatrix?.(true,true);const box=new THREE.Box3().setFromObject(o,true);return{box,size:box.getSize(new THREE.Vector3()),center:box.getCenter(new THREE.Vector3())}}
function tableRef(){return window.SVR_TABLE_AUTHORITY||window.SVR_PHASE380_ORIGINAL_TABLE||scene?.getObjectByName?.('PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY')||table||null}
function capsule(w,d){const r=d/2,s=Math.max(.01,w/2-r),shape=new THREE.Shape();shape.moveTo(-s,-r);shape.lineTo(s,-r);shape.absarc(s,0,r,-Math.PI/2,Math.PI/2,false);shape.lineTo(-s,r);shape.absarc(-s,0,r,Math.PI/2,Math.PI*1.5,false);shape.closePath();return shape}
function capsulePath(ctx,cx,cy,w,h){const r=h/2,s=Math.max(0,w/2-r);ctx.beginPath();ctx.moveTo(cx-s,cy-r);ctx.lineTo(cx+s,cy-r);ctx.arc(cx+s,cy,r,-Math.PI/2,Math.PI/2);ctx.lineTo(cx-s,cy+r);ctx.arc(cx-s,cy,r,Math.PI/2,Math.PI*1.5);ctx.closePath()}
function makeTexture(){if(texture)return texture;const c=document.createElement('canvas');c.width=2048;c.height=1024;const x=c.getContext('2d'),g=x.createRadialGradient(1024,500,40,1024,520,1150);g.addColorStop(0,'#1e1229');g.addColorStop(.42,'#09070e');g.addColorStop(1,'#010103');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.globalAlpha=.20;x.strokeStyle='#6c2a8c';x.lineWidth=2;for(let i=-700;i<2700;i+=76){x.beginPath();x.moveTo(i,0);x.lineTo(i-620,1024);x.stroke()}x.globalAlpha=.08;x.strokeStyle='#17d9ff';for(let i=-700;i<2700;i+=120){x.beginPath();x.moveTo(i,0);x.lineTo(i+520,1024);x.stroke()}x.globalAlpha=1;capsulePath(x,1024,512,1780,760);x.strokeStyle='rgba(216,184,92,.72)';x.lineWidth=10;x.stroke();capsulePath(x,1024,512,1540,640);x.strokeStyle='rgba(127,252,255,.92)';x.lineWidth=7;x.stroke();x.fillStyle='rgba(255,255,255,.82)';x.font='800 34px system-ui';x.textAlign='center';x.fillText('PASS / BET LINE',1024,850);const image=new Image();image.crossOrigin='anonymous';image.onload=()=>{const s=Math.min(420/image.naturalWidth,300/image.naturalHeight),w=image.naturalWidth*s,h=image.naturalHeight*s;x.drawImage(image,1024-w/2,512-h/2,w,h);texture.needsUpdate=true};image.src='/logo.png?v=phase422';texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(4,renderer?.capabilities?.getMaxAnisotropy?.()||2);return texture}
function hideLegacy(){scene?.traverse?.(o=>{if(!o?.isMesh||o===surface)return;const n=String(o.name||'');if(/PHASE390_RECESSED_BRANDED_PLAYING_SURFACE|PHASE393_VISIBLE_RECESSED_INNER_FELT|PHASE421_FINAL_POLISHED_PLAYING_SURFACE|PHASE38(?:4|6|8)_.*FELT|OFFICIAL_SITE_LOGO_FELT/i.test(n)||o.userData?.svrPhase421FinalFelt||o.userData?.svrPhase390BrandedSurface){o.visible=false;const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(m){m.colorWrite=false;m.needsUpdate=true}})}})}
function label(o){const ms=Array.isArray(o?.material)?o.material:[o?.material];return `${o?.name||''} ${ms.map(m=>m?.name||'').join(' ')}`.toLowerCase()}
function polish(){let rails=0,bodies=0;table?.traverse?.(o=>{if(!o?.isMesh||!o.material)return;const text=label(o);if(/felt|cloth|baize|playing|tabletop|surface/.test(text))return;const rail=/armrest|handrest|rail|leather|padding|circle02|object001/.test(text),trim=/silver|chrome|metal|trim/.test(text),body=!rail&&!trim&&/base|body|frame|table|wood|object/.test(text);if(!rail&&!trim&&!body)return;const src=Array.isArray(o.material)?o.material:[o.material],next=src.map(e=>{if(e?.userData?.svr422)return e;const m=e?.clone?.()||new THREE.MeshStandardMaterial();m.userData={...(m.userData||{}),svr422:true,role:rail?'rail':trim?'trim':'body'};m.visible=true;m.transparent=false;m.opacity=1;m.depthTest=true;m.depthWrite=true;if(m.color&&!m.map)m.color.setHex(rail?0x120c17:trim?0x696b79:0x241713);if('roughness'in m)m.roughness=rail?.36:trim?.24:.50;if('metalness'in m)m.metalness=rail?.04:trim?.72:.12;m.needsUpdate=true;return m});o.material=Array.isArray(o.material)?next:next[0];o.visible=true;o.receiveShadow=true;if(rail)rails+=next.length;else if(body)bodies+=next.length});state.railMaterials=rails;state.bodyMaterials=bodies}
function lighting(){if(lights?.parent)return true;const info=bounds(table);table.getWorldQuaternion(q);const right=v.set(1,0,0).applyQuaternion(q).setY(0).normalize();lights=new THREE.Group();lights.name='PHASE422_TABLE_LIGHTING';const key=new THREE.PointLight(0xb57cff,2.25,7,2),fill=new THREE.PointLight(0x62e7ff,1.45,5.5,2),gold=new THREE.PointLight(0xd8b85c,1.0,4.8,2),hemi=new THREE.HemisphereLight(0xbad7ff,0x16071e,.60);key.position.copy(info.center).add(new THREE.Vector3(0,1.7,.15));fill.position.copy(info.center).addScaledVector(right,-1.3).add(new THREE.Vector3(0,1.0,0));gold.position.copy(info.center).addScaledVector(right,1.25).add(new THREE.Vector3(0,.85,-.45));lights.add(key,fill,gold,hemi);scene.add(lights);if(renderer&&Number.isFinite(renderer.toneMappingExposure))renderer.toneMappingExposure=Math.max(renderer.toneMappingExposure,1.1);state.lightingReady=true;return true}
export function topY(){return surface?bounds(surface).box.max.y:null}
export async function sweep(reason='manual'){if(!ACTIVE)return false;try{scene=window.__SVR_SCENE__||scene;renderer=window.__SVR_RENDERER__||renderer;table=tableRef()||table;if(!scene||!table)return false;state.tableFound=true;const info=bounds(table),w=Math.max(info.size.x,info.size.z)*.78,d=Math.min(info.size.x,info.size.z)*.68;if(!surface?.parent){const geo=new THREE.ShapeGeometry(capsule(w,d),48);geo.rotateX(-Math.PI/2);surface=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({map:makeTexture(),color:0xffffff,roughness:.96,metalness:0,bumpMap:makeTexture(),bumpScale:.0008,side:THREE.DoubleSide}));surface.name='PHASE422_TRUE_INNER_PLAYING_SURFACE';surface.userData={svrPhase422InnerSurface:true,recessMeters:FELT_RECESS_METERS};surface.receiveShadow=true;surface.frustumCulled=false;surface.renderOrder=4220;scene.add(surface);window.SVR_PHASE422_PLAY_SURFACE=surface}table.getWorldQuaternion(q);surface.quaternion.copy(q);surface.position.copy(info.center);surface.position.y=info.box.max.y-FELT_RECESS_METERS;surface.visible=true;surface.updateWorldMatrix?.(true,true);const live=bounds(surface);state.recessMeters=+(info.box.max.y-live.box.max.y).toFixed(4);state.feltReady=Math.abs(state.recessMeters-FELT_RECESS_METERS)<=.006;hideLegacy();polish();lighting();state.installed=Boolean(state.feltReady&&state.lightingReady);state.lastError=null;state.checkedAt=new Date().toISOString();window.SVR_PHASE422_TABLE_THEME_STATE={...state,reason};return state.installed}catch(e){state.lastError=String(e?.stack||e?.message||e);return false}}
export function qa(){return{...state,targetRecessMeters:FELT_RECESS_METERS,targetRecessInches:1,innerSurfaceOnly:true,curvedLeatherRailPreserved:true,pass:Boolean(state.installed&&state.feltReady&&!state.lastError),checkedAt:new Date().toISOString()}}
window.SVR_PHASE422_TABLE_THEME_SWEEP=sweep;window.SVR_PHASE422_TABLE_THEME_QA=qa;window.SVR_PHASE422_TABLE_ACTIVE=true;
if(ACTIVE){window.addEventListener('svr:phase396-core-ready',()=>setTimeout(()=>void sweep('core-ready'),260),{once:true});setTimeout(()=>void sweep('delayed'),3000);setInterval(hideLegacy,1200)}
