import * as THREE from 'three';
const LABEL='PHASE-200-CLEAN-RUNTIME-AUTHORITY-LOCK';
const ROOT='PHASE200_CLEAN_RUNTIME_AUTHORITY_ROOT';
let scene,camera,renderer,root,started=false;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function setVisible(o,v){o.visible=v;o.traverse?.(c=>{c.visible=v;if(c.material){c.material.transparent=true;c.material.opacity=v?(c.material.opacity||1):0;c.material.needsUpdate=true;}});}
function keepSingleLogo(){const arr=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(/logo/i.test(n)&&/floor|circle|carpet|center|lobby|PHASE19/i.test(n))arr.push(o);});const keep=arr.find(o=>/PHASE196_ORIGINAL_LOBBY_LOGO/i.test(o.name))||arr.find(o=>/PHASE192_CENTER_LOGO_FILL/i.test(o.name))||arr[0];arr.forEach(o=>setVisible(o,o===keep||keep?.parent===o));return {count:arr.length,kept:keep?.name||null,hidden:Math.max(0,arr.length-(keep?1:0))};}
function keepSingleMoon(){const moons=[],mars=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon/i.test(n)&&!/mars/i.test(n))moons.push(o);if(/mars/i.test(n))mars.push(o);});const keep=moons.find(o=>/PHASE196_ROTATING_MOON/i.test(o.name))||moons[0];moons.forEach(o=>setVisible(o,o===keep||keep?.parent===o));mars.forEach(o=>setVisible(o,true));return {moons:moons.length,kept:keep?.name||null,mars:mars.length};}
function rails(){let removed=0;const kill=[];sr(scene)?.traverse?.(o=>{const n=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|watch|hand|teleport|moon|mars|star|camera|light|logo/i.test(n))return;if(!/rail|rope|stanchion|barrier|banister|handrail|guard|pole|post|fence/i.test(n))return;const p=new THREE.Vector3();o.getWorldPosition(p);if(Math.hypot(p.x,p.z)<14)kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);removed++;});return removed;}
function table(){let found=null,names=[];sr(scene)?.traverse?.(o=>{const n=String(o.name||'');if(/table/i.test(n))names.push(n);if(found)return;if(/PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED|PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT|fbx.*table|table.*fbx/i.test(n))found=o;});if(found){found.visible=true;found.frustumCulled=false;found.traverse?.(c=>{c.visible=true;c.frustumCulled=false;if(c.isMesh){c.castShadow=false;c.receiveShadow=true;}});}return {found:!!found,name:found?.name||null,names:names.slice(0,20)};}
function suppress(){let count=0;document.querySelectorAll('div,section,aside,pre').forEach(el=>{const t=(el.textContent||'').toLowerCase();if(/svr update available|update now|available site|reload|build:/i.test(t)&&/update|available/.test(t)){el.style.display='none';count++;}});return count;}
function pass(){const logo=keepSingleLogo();const moon=keepSingleMoon();const tableState=table();const railRemoved=rails();const suppressed=suppress();window.SVR_PHASE200_CLEAN_RUNTIME_AUTHORITY_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,logo,moon,table:tableState,railsRemoved:railRemoved,overlaysSuppressed:suppressed,checkedAt:iso()};return window.SVR_PHASE200_CLEAN_RUNTIME_AUTHORITY_LOCK;}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);pass();window.SVR_RUN_PHASE200_AUDIT=()=>pass();window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(pass,1000);}return true;}
[250,700,1400,2600,5000,8500,12000].forEach(ms=>setTimeout(install,ms));install();
