import * as THREE from "three";

const LABEL="PHASE-178-STRUCTURE-WATCH-LOGO-LOCK";
const ROOT="PHASE178_NEW_UPPER_STRUCTURE_ROOT";
const LOGO="PHASE178_TABLE_LOGO_CARPET_ROOT";
const SECOND_Y=3.15;
const STAIR={x:-6.8,w:2.25,z0:3.4,z1:-6.05,n:18};
const BAL={x:0,z:-7.35,w:12.6,d:2.85};
let scene,camera,renderer,started=false,logoPromise=null,lastRigY=null;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.("PHASE200_ORDERED_GRAND_LOBBY_ROOT")||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.03,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function add(parent,name,p,s,m){const x=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m); x.name=name; x.position.set(p.x,p.y,p.z); x.receiveShadow=true; parent.add(x); return x;}
function findTable(root){return root?.getObjectByName?.("PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT")||root?.getObjectByName?.("PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED")||null;}
function tableRec(root){const t=findTable(root); if(!t)return null; t.updateMatrixWorld(true); const b=new THREE.Box3().setFromObject(t),c=new THREE.Vector3(),s=new THREE.Vector3(); b.getCenter(c); b.getSize(s); return {center:c,size:s};}
function clearOld(root){let n=0; const a=root.getObjectByName?.(ROOT); if(a){a.parent?.remove(a); n++;} const b=root.getObjectByName?.(LOGO); if(b){b.parent?.remove(b); n++;} const list=[]; root.traverse?.(o=>{const name=String(o.name||""); if(!o.parent||/table|felt|card|chip|pot|watch|hand|teleport|moon|mars|star|camera|light|phase17[0-9]/i.test(name))return; if(/stair|step|upper|second|balcony|mezzanine|catwalk|glass|rail|rope|pole|post/i.test(name))list.push(o);}); [...new Set(list)].forEach(o=>{o.parent?.remove(o); n++;}); return n;}
function loadImage(u){return new Promise(r=>{const i=new Image(); i.crossOrigin="anonymous"; i.onload=()=>r(i); i.onerror=()=>r(null); i.src=u;});}
async function logoAsset(){if(logoPromise)return logoPromise; logoPromise=(async()=>{for(const u of ["/logo.png","/logo.webp","./ui/logo.png","./assets/ui/logo.png"]){const img=await loadImage(u); if(img)return {img,url:u};} return null;})(); return logoPromise;}
function logoTex(l){const c=document.createElement("canvas"); c.width=c.height=1536; const x=c.getContext("2d"),cx=768,cy=768; x.clearRect(0,0,1536,1536); const g=x.createRadialGradient(cx,cy,60,cx,cy,740); g.addColorStop(0,"rgba(127,252,255,.30)"); g.addColorStop(.62,"rgba(70,18,150,.22)"); g.addColorStop(1,"rgba(0,0,0,0)"); x.fillStyle=g; x.fillRect(0,0,1536,1536); x.strokeStyle="rgba(127,252,255,.86)"; x.lineWidth=22; x.beginPath(); x.arc(cx,cy,675,0,Math.PI*2); x.stroke(); if(l?.img){const s=860; x.drawImage(l.img,cx-s/2,cy-s/2,s,s);} else {x.fillStyle="#7ffcff"; x.font="900 260px system-ui"; x.textAlign="center"; x.textBaseline="middle"; x.fillText("SVR",cx,cy-60); x.fillStyle="#eebf5c"; x.font="900 100px system-ui"; x.fillText("POKER",cx,cy+130);} const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; t.anisotropy=4; return t;}
async function installCarpet(root,t){if(!t)return null; const l=await logoAsset(); const g=new THREE.Group(); g.name=LOGO; g.position.set(t.center.x,.021,t.center.z); const size=Math.max(7.2,Math.min(9.6,Math.max(t.size.x,t.size.z)*1.9)); const m=new THREE.Mesh(new THREE.PlaneGeometry(size,size),new THREE.MeshBasicMaterial({map:logoTex(l),transparent:true,side:THREE.DoubleSide,depthWrite:false,alphaTest:.02})); m.name="PHASE178_FULL_TABLE_LOGO_CARPET"; m.rotation.x=-Math.PI/2; m.renderOrder=1200; g.add(m); root.add(g); return {x:+g.position.x.toFixed(3),y:+g.position.y.toFixed(3),z:+g.position.z.toFixed(3),size:+size.toFixed(3),url:l?.url||"fallback"};}
function build(root){const g=new THREE.Group(); g.name=ROOT; root.add(g); const floor=mat(0x1f2430), trim=mat(0x0b0f18), step=mat(0x303541), glass=mat(0x7ffcff,.24); add(g,"PHASE178_SOLID_SECOND_FLOOR",{x:BAL.x,y:SECOND_Y-.1,z:BAL.z},{x:BAL.w,y:.22,z:BAL.d},floor); add(g,"PHASE178_BACK_EDGE_TIGHT",{x:BAL.x,y:SECOND_Y+.07,z:BAL.z-BAL.d/2-.08},{x:BAL.w+.2,y:.28,z:.14},trim); add(g,"PHASE178_FRONT_EDGE_TIGHT",{x:BAL.x,y:SECOND_Y+.07,z:BAL.z+BAL.d/2+.08},{x:BAL.w+.2,y:.28,z:.14},trim); add(g,"PHASE178_GLASS_FRONT_EDGE",{x:BAL.x,y:SECOND_Y+.74,z:BAL.z+BAL.d/2+.12},{x:BAL.w-.8,y:1.12,z:.055},glass); add(g,"PHASE178_GLASS_LEFT_EDGE",{x:-BAL.w/2-.08,y:SECOND_Y+.74,z:BAL.z},{x:.055,y:1.12,z:BAL.d-.25},glass); add(g,"PHASE178_GLASS_RIGHT_EDGE",{x:BAL.w/2+.08,y:SECOND_Y+.74,z:BAL.z},{x:.055,y:1.12,z:BAL.d-.25},glass); const dz=(STAIR.z1-STAIR.z0)/STAIR.n, dy=SECOND_Y/STAIR.n; for(let i=0;i<STAIR.n;i++){add(g,`PHASE178_WALKABLE_STEP_${i+1}`,{x:STAIR.x,y:dy*(i+.5),z:STAIR.z0+dz*(i+.5)},{x:STAIR.w,y:dy*.88,z:Math.abs(dz)*1.06},step);} add(g,"PHASE178_TOP_LANDING_FLUSH",{x:STAIR.x,y:SECOND_Y-.08,z:STAIR.z1-.45},{x:STAIR.w,y:.18,z:.95},floor); add(g,"PHASE178_LEFT_STAIR_GLASS",{x:STAIR.x-STAIR.w/2-.06,y:SECOND_Y/2+.45,z:(STAIR.z0+STAIR.z1)/2},{x:.055,y:1.1,z:Math.abs(STAIR.z1-STAIR.z0)},glass); add(g,"PHASE178_RIGHT_STAIR_GLASS",{x:STAIR.x+STAIR.w/2+.06,y:SECOND_Y/2+.45,z:(STAIR.z0+STAIR.z1)/2},{x:.055,y:1.1,z:Math.abs(STAIR.z1-STAIR.z0)},glass); return true;}
function hAt(x,z){if(Math.abs(x-STAIR.x)<STAIR.w/2+.18&&z<=Math.max(STAIR.z0,STAIR.z1)&&z>=Math.min(STAIR.z0,STAIR.z1)){const p=(STAIR.z0-z)/(STAIR.z0-STAIR.z1); return THREE.MathUtils.clamp(p,0,1)*SECOND_Y;} if(Math.abs(x-BAL.x)<BAL.w/2&&Math.abs(z-BAL.z)<BAL.d/2+.25)return SECOND_Y; return 0;}
function camPos(){const p=new THREE.Vector3(); if(renderer?.xr?.isPresenting)renderer.xr.getCamera(camera).getWorldPosition(p); else camera?.getWorldPosition(p); return p;}
function applyHeight(){if(!camera||!renderer)return; const p=camPos(), h=hAt(p.x,p.z); if(renderer.xr?.isPresenting){const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG; const guess=p.y-1.62; if(rig?.setPlayerPose&&Math.abs(guess-h)>.18&&lastRigY!==h){lastRigY=h; rig.setPlayerPose(p.x,h,p.z);}}else{const want=h+1.62; camera.position.y+=(want-camera.position.y)*.18;} window.SVR_PHASE178_NAV_HEIGHT={build:LABEL,x:+p.x.toFixed(3),z:+p.z.toFixed(3),floorY:+h.toFixed(3),checkedAt:iso()};}
function hideOverlay(){let n=0; for(const s of ["#bootFallback","#svrPhaseBadge",".black-overlay",".square-overlay",".face-overlay",".vignette",".iris",".fade",".oculus-overlay","[data-overlay]","[data-svr-overlay]"])document.querySelectorAll(s).forEach(e=>{e.style.display="none";e.style.opacity="0";e.style.visibility="hidden";e.style.pointerEvents="none";n++;}); return n;}
async function install(){scene=window.__SVR_SCENE__; camera=window.__SVR_CAMERA__; renderer=window.__SVR_RENDERER__; if(!scene||!camera||!renderer)return false; const r=sr(scene), table=tableRec(r), old=clearOld(r); build(r); const carpet=await installCarpet(r,table); const overlays=hideOverlay(); window.SVR_PHASE178_STRUCTURE_WATCH_LOGO_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,oldStructureRemoved:old,newStairs:true,newUpperFloor:true,glassAligned:true,desktopAndroidVrHeightPatch:true,watchEnabled:true,carpetLogo:carpet,overlayHidden:overlays,checkedAt:iso()}; window.SVR_RUN_PHASE178_STRUCTURE_AUDIT=()=>window.SVR_PHASE178_STRUCTURE_WATCH_LOGO_LOCK; window.SVR_LOCKED_FINAL_BUILD=LABEL; window.SVR_LIVE_BUILD_POINTER=LABEL; if(!started){started=true; setInterval(()=>{applyHeight();hideOverlay();},70);} return true;}
[300,900,1600,3000,6000,10000].forEach(ms=>setTimeout(install,ms)); install();
