import * as THREE from 'three';
const LABEL='PHASE-199-FBX-TABLE-RUNTIME-DIAGNOSTIC-LOCK';
const ROOT='PHASE199_FBX_TABLE_RUNTIME_DIAGNOSTIC_ROOT';
let scene,camera,renderer,root,started=false;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.78,metalness:.04,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function bounds(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return {box:b,size:s,center:c};}
function candidates(){const r=sr(scene),list=[];r?.traverse?.(o=>{const n=String(o.name||'');const nl=n.toLowerCase();let score=0;if(/phase159/.test(nl))score+=8;if(/fbx/.test(nl))score+=7;if(/actual/.test(nl))score+=5;if(/uploaded/.test(nl))score+=5;if(/table/.test(nl))score+=6;if(/poker/.test(nl))score+=2;if(/fallback|geometry|marker|logo|chair|stool|seat|card|chip|pot|panel|hud/.test(nl))score-=7;if(score>0){let info={name:n||'(unnamed)',score,type:o.type,visible:o.visible,mesh:!!o.isMesh};try{const b=bounds(o);info.size={x:+b.size.x.toFixed(3),y:+b.size.y.toFixed(3),z:+b.size.z.toFixed(3)};info.center={x:+b.center.x.toFixed(3),y:+b.center.y.toFixed(3),z:+b.center.z.toFixed(3)};info.volume=+(b.size.x*b.size.y*b.size.z).toFixed(3);score+=Math.min(8,Math.max(0,b.size.x+b.size.z));info.score=+score.toFixed(3);}catch(e){}list.push({obj:o,info});}});list.sort((a,b)=>(b.info.score||0)-(a.info.score||0));return list;}
function applyTable(o){if(!o)return null;o.visible=true;o.frustumCulled=false;o.traverse?.(x=>{x.visible=true;x.frustumCulled=false;if(x.isMesh){const n=String(x.name||'').toLowerCase();if(/leather|hand|rest|rail|rim|edge|cushion/.test(n))x.material=mat(0x25120c);else if(/felt|cloth|top|surface/.test(n))x.material=mat(0x064126);else if(!x.material)x.material=mat(0x2b211c);x.castShadow=false;x.receiveShadow=true;}});const b=bounds(o);const dy=.02-b.box.min.y;if(Number.isFinite(dy)&&Math.abs(dy)>.003){o.position.y+=dy;o.updateMatrixWorld(true);}return bounds(o);}
function marker(found,center){const old=root.getObjectByName?.('PHASE199_TABLE_STATUS_MARKER');if(old)old.parent?.remove(old);const g=new THREE.Group();g.name='PHASE199_TABLE_STATUS_MARKER';g.position.set(center.x,.06,center.z);root.add(g);const color=found?0x00ff99:0xff4444;const ring=new THREE.Mesh(new THREE.RingGeometry(2.35,2.7,96),basic(color,.42));ring.rotation.x=-Math.PI/2;g.add(ring);if(!found){const c=document.createElement('canvas');c.width=1024;c.height=256;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.72)';x.fillRect(0,0,1024,256);x.strokeStyle='#ff4444';x.lineWidth=10;x.strokeRect(8,8,1008,240);x.fillStyle='#fff';x.font='900 50px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText('FBX TABLE NOT FOUND IN RUNTIME',512,92);x.fillStyle='#ffd98a';x.font='700 28px system-ui';x.fillText('Audit will list detected table object names.',512,164);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const p=new THREE.Mesh(new THREE.PlaneGeometry(5.8,1.45),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide}));p.position.set(0,1.5,-2.4);g.add(p);}return true;}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);const cand=candidates();let chosen=cand.find(x=>/PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED|PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT/i.test(x.info.name))||cand.find(x=>x.info.score>10&&/table/i.test(x.info.name));let b=chosen?applyTable(chosen.obj):null;marker(!!chosen,b?.center||new THREE.Vector3(0,0,0));window.SVR_PHASE199_FBX_TABLE_RUNTIME_DIAGNOSTIC_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,fbxFound:!!chosen,chosen:chosen?chosen.info:null,topCandidates:cand.slice(0,25).map(x=>x.info),visibleForced:!!chosen,bounds:b?{center:{x:+b.center.x.toFixed(3),y:+b.center.y.toFixed(3),z:+b.center.z.toFixed(3)},size:{x:+b.size.x.toFixed(3),y:+b.size.y.toFixed(3),z:+b.size.z.toFixed(3)}}:null,checkedAt:iso()};window.SVR_RUN_PHASE199_TABLE_AUDIT=()=>window.SVR_PHASE199_FBX_TABLE_RUNTIME_DIAGNOSTIC_LOCK;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(()=>{const c=candidates();const pick=c.find(x=>/PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED|PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT/i.test(x.info.name))||c.find(x=>x.info.score>10&&/table/i.test(x.info.name));const bb=pick?applyTable(pick.obj):null;window.SVR_PHASE199_FBX_TABLE_RUNTIME_DIAGNOSTIC_LOCK.fbxFound=!!pick;window.SVR_PHASE199_FBX_TABLE_RUNTIME_DIAGNOSTIC_LOCK.chosen=pick?pick.info:null;window.SVR_PHASE199_FBX_TABLE_RUNTIME_DIAGNOSTIC_LOCK.topCandidates=c.slice(0,25).map(x=>x.info);window.SVR_PHASE199_FBX_TABLE_RUNTIME_DIAGNOSTIC_LOCK.checkedAt=iso();},1200);}return true;}
[250,700,1400,2600,5000,8500,12000].forEach(ms=>setTimeout(install,ms));install();
