/* PHASE-388-QUEST-TABLE-PLAYER-ERIC-AUTHORITY-LOCK */
import * as THREE from 'three';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
export const BUILD='PHASE-388-QUEST-TABLE-PLAYER-ERIC-AUTHORITY-LOCK';
const q=new URLSearchParams(location.search),ua=navigator.userAgent||'',ACTIVE=(q.get('platform')==='quest'||q.get('direct')==='1'||/Quest|Oculus|Meta Quest/i.test(ua));
const FLAGS=['SVR_MOVEMENT_ENABLED','SVR_LOCOMOTION_ENABLED','SVR_TABLE_TRAVEL_ENABLED','SVR_TELEPORT_ENABLED','SVR_HAND_TELEPORT_ENABLED','SVR_WATCH_TELEPORT_ENABLED','SVR_GRIP_TELEPORT_ENABLED','SVR_POINTER_ENABLED','SVR_HAND_RAY_ENABLED','SVR_SNAP_TURN_ENABLED','SVR_STICK_MOVE_ENABLED'];
const state={build:BUILD,active:ACTIVE,installed:false,seatReady:false,seatApplications:0,seatCorrections:0,movementLocked:false,ericLoaded:false,ericUpright:false,ericGrounded:false,ericHeight:null,ericColoredMeshes:0,oldEricsDetached:0,logoLoaded:false,feltInstalled:false,lightingInstalled:false,legacyOverlaysRemoved:0,lastError:null,checkedAt:null};
let scene,camera,renderer,table,eric,felt,lights,seat,raf=0,timer=0,lastFix=0,lastSweep=0,loading=null,internal=false,targetRigLocal=null,guarded=false,oldCopy=null;
const v1=new THREE.Vector3(),v2=new THREE.Vector3(),v3=new THREE.Vector3(),quat=new THREE.Quaternion(),ray=new THREE.Raycaster();
function walk(root,fn,limit=26000){const stack=root?[root]:[],seen=new Set();while(stack.length&&seen.size<limit){const o=stack.pop();if(!o||seen.has(o))continue;seen.add(o);try{fn(o)}catch{}for(const c of o.children||[])if(c&&!seen.has(c))stack.push(c)}}
function inside(o,r){for(let p=o;p;p=p.parent)if(p===r)return true;return false}
function box(o){o?.updateWorldMatrix?.(true,true);const b=new THREE.Box3().setFromObject(o,true);return{box:b,size:b.getSize(new THREE.Vector3()),center:b.getCenter(new THREE.Vector3())}}
function valid(b){return !!b&&!b.box.isEmpty()&&b.size.x>.03&&b.size.y>.03&&b.size.z>.03}
function meshes(o){let n=0;walk(o,x=>{if(x?.isMesh&&x.geometry?.attributes?.position)n++},10000);return n}
function cam(){const c=renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;return c?.cameras?.[0]||c||camera}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||window.SVR_PLAYER_RIG||window.__SVR_PLAYER_RIG||null}
function findTable(){for(const o of [window.SVR_TABLE_AUTHORITY,window.SVR_PHASE380_ORIGINAL_TABLE,scene?.getObjectByName?.('PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY'),scene?.getObjectByName?.('PHASE373_VISIBLE_TABLE_GLB_AUTHORITY'),table]){if(!o?.isObject3D)continue;try{const b=box(o);if(valid(b)&&b.size.x>1.2&&b.size.z>.65)return o}catch{}}return null}
function edge(info,dir){const origin=info.center.clone().addScaledVector(dir,Math.max(info.size.x,info.size.z)*3+3);origin.y=info.center.y;ray.set(origin,dir.clone().negate());try{const hit=ray.intersectObject(table,true).find(h=>h.object?.isMesh);if(hit)return hit.point.clone()}catch{}const hx=Math.max(.4,info.size.x/2),hz=Math.max(.3,info.size.z/2),d=1/Math.sqrt(dir.x*dir.x/(hx*hx)+dir.z*dir.z/(hz*hz));return info.center.clone().addScaledVector(dir,d)}
function computeSeat(){table=findTable()||table;if(!table)return null;const info=box(table);if(!valid(info))return null;cam()?.getWorldPosition?.(v1);const dir=new THREE.Vector3(v1.x-info.center.x,0,v1.z-info.center.z);if(dir.lengthSq()<.16)dir.set(0,0,1);dir.normalize();const e=edge(info,dir),head=e.clone().addScaledVector(dir,.14);head.y=info.box.max.y+.54;const look=info.center.clone();look.y=info.box.max.y+.06;return{info,dir,head,look,dealerDir:dir.clone().negate()}}
function originalMethods(r=rig()){return r?.userData?.svrPhase373OriginalMethods||{}}
function setLocal(r,p){const orig=originalMethods(r);internal=true;try{if(typeof orig.positionSet==='function'){orig.positionSet.call(r.position,p.x,p.y,p.z);return true}r.position.set(p.x,p.y,p.z);return true}finally{internal=false}}
function guard(){const r=rig();if(guarded||!r?.position)return;oldCopy=r.position.copy.bind(r.position);r.position.copy=function(p){if(!internal&&targetRigLocal&&p?.distanceTo?.(targetRigLocal)>.04){state.seatCorrections++;return this}return oldCopy(p)};guarded=true}
function face(target){const r=rig(),c=cam();if(!r?.rotation||!c)return;c.getWorldQuaternion(quat);v1.set(0,0,-1).applyQuaternion(quat);v1.y=0;if(v1.lengthSq()<1e-5)return;v1.normalize();c.getWorldPosition(v2);v3.set(target.x-v2.x,0,target.z-v2.z);if(v3.lengthSq()<1e-5)return;v3.normalize();let d=Math.atan2(v3.x,v3.z)-Math.atan2(v1.x,v1.z);d=Math.atan2(Math.sin(d),Math.cos(d));r.rotation.y+=d}
function moveHead(target,look,turn=false){const r=rig(),c=cam();if(!r?.position||!c)return false;c.getWorldPosition(v1);r.getWorldPosition(v2);v3.copy(v2).add(target).sub(v1);let local=v3.clone();if(r.parent){r.parent.updateWorldMatrix?.(true,false);local=r.parent.worldToLocal(local)}targetRigLocal=local.clone();guard();const ok=setLocal(r,local);if(ok&&turn)face(look);return ok}
function neutralize(){try{window.SVR_PHASE359_TOGGLE_CONTINUOUS?.(true);window.SVR_PHASE360_JOIN_TABLE?.()}catch{}if(window.SVR_PHASE361_STATE){window.SVR_PHASE361_STATE.seated=false;window.SVR_PHASE361_STATE.mode='phase388-direct'}document.body.classList.remove('svr361-seated','svr363-seated','svr365-seated','svr381-seated-lock');document.body.classList.add('svr388-direct-seated');document.body.dataset.svrSeated='false'}
function lock(){for(const k of FLAGS)window[k]=false;window.SVR_TABLE_MOVEMENT_LOCKED=true;window.SVR_PHASE388_DIRECT_TABLE_LOCK=true;state.movementLocked=true}
function hideTeleport(){walk(scene,o=>{const n=String(o?.name||'');if(/(teleport|landing|reticle|marker|arc|raycast|ray[_ -]?line)/i.test(n)&&!/(table|card|logo|button|watch|controller|hand)/i.test(n))o.visible=false},18000)}
function place(reason='manual',turn=true){seat=computeSeat();if(!seat)return false;neutralize();const ok=moveHead(seat.head,seat.look,turn);if(ok){state.seatReady=true;state.seatApplications++;state.lastReason=reason}lock();hideTeleport();return ok}
function patchApis(){for(const n of ['SVR_PHASE361_LOBBY_SPAWN','SVR_PHASE361_PLAY_GAME','SVR_PHASE361_RESEAT','SVR_PHASE373_STABLE_LOBBY','SVR_PHASE373_STABLE_SEAT','SVR_PHASE364_LOBBY_SPAWN','SVR_PHASE364_SEAT']){if(window[n]?.__p388)continue;const f=(...a)=>place(`${n}:${a[0]||'api'}`);f.__p388=true;window[n]=f}}
function correct(t){if(!seat||t-lastFix<90)return;lastFix=t;cam()?.getWorldPosition?.(v1);if(Math.hypot(v1.x-seat.head.x,v1.z-seat.head.z)>.045||Math.abs(v1.y-seat.head.y)>.1){if(moveHead(seat.head,seat.look,false))state.seatCorrections++}}
function detachOld(){let n=0;const roots=[];walk(scene,o=>{if(!o?.isObject3D||o===eric||inside(o,eric))return;const label=`${o.name||''} ${o.userData?.sourceAsset||''}`;if(o.isSkeletonHelper||/(external[_ -]?skeleton|debug[_ -]?skeleton|PHASE368_CARD_DEALER_ROOT)/i.test(label)){o.visible=false;return}if((o.userData?.svrPhase381Approved||o.userData?.svrPhase386Approved||o.userData?.svrPhase387Approved||/(approvedDealer|eric[_ -]?(dealer|avatar|rig)|card[_ -]?dealer[_ -]?rig)/i.test(label))&&meshes(o)>0)roots.push(o)},22000);for(const r of roots){if(r.parent){r.parent.remove(r);r.visible=false;n++}}state.oldEricsDetached+=n}
function clean(n=''){return String(n).replace(/^[^:]+:/,'').replace(/[^a-z0-9]/ig,'').toLowerCase()}
function bone(root,list){let found=null;walk(root,o=>{if(found||!o?.isBone)return;const n=clean(o.name);if(list.some(rx=>rx.test(n)))found=o},10000);return found}
function upright(wrapper,model){const h=bone(model,[/^head$/, /head/]),lf=bone(model,[/leftfoot/,/footl$/, /anklel/, /toel/]),rf=bone(model,[/rightfoot/,/footr$/, /ankler/, /toer/]);let best=null;for(const r of [[0,0,0],[0,0,-Math.PI/2],[0,0,Math.PI/2],[-Math.PI/2,0,0],[Math.PI/2,0,0],[Math.PI,0,0],[0,0,Math.PI]]){wrapper.rotation.set(...r);wrapper.updateWorldMatrix?.(true,true);const b=box(wrapper);if(!valid(b))continue;let anatomy=0;if(h){h.getWorldPosition(v1);const feet=[];if(lf){lf.getWorldPosition(v2);feet.push(v2.y)}if(rf){rf.getWorldPosition(v3);feet.push(v3.y)}if(feet.length)anatomy=v1.y>Math.min(...feet)?4:-4}const score=anatomy+b.size.y/Math.max(b.size.x,b.size.z,.001);if(!best||score>best.score)best={score,rot:wrapper.rotation.clone()}}if(best)wrapper.rotation.copy(best.rot)}
function colorEric(model){let count=0;walk(model,o=>{if(!o?.isMesh||!o.geometry?.attributes?.position)return;const g=o.geometry.clone(),p=g.attributes.position,b=new THREE.Box3().setFromBufferAttribute(p),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),hx=Math.max(s.x/2,.001),hz=Math.max(s.z/2,.001),arr=new Float32Array(p.count*3),col=new THREE.Color();for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),t=THREE.MathUtils.clamp((y-b.min.y)/Math.max(s.y,.001),0,1),side=Math.abs(x-c.x)/hx,front=Math.abs(z-c.z)/hz;if(t>.965)col.setHex(0x20120d);else if(t>.805)col.setHex(0xb97a5e);else if(t>.49){if(side>.64)col.setHex(0xb97a5e);else if(side<.19&&t>.57&&front<.78)col.setHex(0xe9eef3);else col.setHex(0x20283a)}else if(t>.15)col.setHex(0x111827);else col.setHex(0x09090c);arr[i*3]=col.r;arr[i*3+1]=col.g;arr[i*3+2]=col.b}g.setAttribute('color',new THREE.BufferAttribute(arr,3));o.geometry=g;o.material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.64,metalness:.03,side:THREE.DoubleSide,emissive:0x07090d,emissiveIntensity:.18});o.material.userData.svrPhase388EricMaterial=true;o.visible=true;o.frustumCulled=false;count++},12000);state.ericColoredMeshes=count}
function normalizeEric(model){const root=new THREE.Group(),orient=new THREE.Group();root.name='PHASE388_AUTHORITATIVE_DEALER_MODEL';orient.name='PHASE388_ERIC_UPRIGHT_WRAPPER';orient.add(model);root.add(orient);upright(orient,model);let b=box(root);orient.scale.multiplyScalar(1.78/Math.max(b.size.y,.001));b=box(root);orient.position.x-=b.center.x;orient.position.z-=b.center.z;orient.position.y-=b.box.min.y;root.userData={svrPhase388Authority:true,svrPhase386Textured:true,svrPhase387Textured:true,sourceAsset:'phase388-authoritative-dealer',build:BUILD};colorEric(model);return root}
async function ensureEric(){if(eric?.parent)return eric;if(loading)return loading;loading=(async()=>{try{detachOld();const model=await new FBXLoader().loadAsync(new URL('../assets/models/eric/eric.fbx',import.meta.url).href);eric=normalizeEric(model);scene.add(eric);window.SVR_PHASE388_ERIC_AUTHORITY=eric;state.ericLoaded=true;state.ericUpright=true;return eric}catch(e){state.lastError=`ERIC:${e?.message||e}`;return null}})();return loading}
function alignEric(){if(!eric||!seat)return false;const e=edge(seat.info,seat.dealerDir).addScaledVector(seat.dealerDir,.52);eric.position.set(e.x,0,e.z);eric.lookAt(seat.head.x,.95,seat.head.z);eric.updateWorldMatrix?.(true,true);let b=box(eric);if(valid(b))eric.position.y-=b.box.min.y;b=box(eric);state.ericGrounded=valid(b)&&Math.abs(b.box.min.y)<.04;state.ericHeight=valid(b)?+b.size.y.toFixed(3):null;eric.visible=true;return true}
function image(url){return new Promise(r=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=()=>r(null);i.src=`${url}?v=phase388`})}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));}
async function feltMap(){const c=document.createElement('canvas');c.width=2048;c.height=1024;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);round(x,44,56,1960,912,320);x.save();x.clip();const g=x.createRadialGradient(1024,470,60,1024,520,1200);g.addColorStop(0,'#5a176f');g.addColorStop(.55,'#35104f');g.addColorStop(1,'#160821');x.fillStyle=g;x.fillRect(0,0,2048,1024);x.globalAlpha=.17;x.font='58px serif';const suits=['♠','♥','♣','♦'];for(let r=0;r<10;r++)for(let col=0;col<20;col++){x.fillStyle=col%3===0?'#9c69df':'#6b3a9e';x.fillText(suits[(r+col)%4],col*112-22,r*110+70)}x.globalAlpha=1;x.strokeStyle='rgba(255,255,255,.92)';x.lineWidth=14;round(x,105,125,1838,774,270);x.stroke();const logo=await image('/logo.png');if(logo){const s=Math.min(410/logo.naturalWidth,410/logo.naturalHeight),w=logo.naturalWidth*s,h=logo.naturalHeight*s;x.drawImage(logo,1024-w/2,512-h/2,w,h);state.logoLoaded=true}x.restore();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(4,renderer?.capabilities?.getMaxAnisotropy?.()||2);return t}
function removeOldFelt(){let n=0;const remove=[];walk(scene,o=>{if(o===felt||inside(o,felt))return;if(/(PHASE167_.*(FELT|LOGO)|PHASE384_.*(FELT|LOGO)|PHASE386_.*(FELT|LOGO)|PASSLINE.*LOGO)/i.test(String(o?.name||'')))remove.push(o)},18000);for(const o of remove){o.parent?.remove(o);o.visible=false;n++}state.legacyOverlaysRemoved+=n}
async function installFelt(){if(!table)return false;removeOldFelt();const b=box(table);if(!valid(b))return false;if(!felt){felt=new THREE.Mesh(new THREE.PlaneGeometry(b.size.x*.88,b.size.z*.82),new THREE.MeshBasicMaterial({map:await feltMap(),transparent:true,depthWrite:false,side:THREE.DoubleSide,toneMapped:false}));felt.name='PHASE388_OFFICIAL_SITE_LOGO_FELT';felt.rotation.x=-Math.PI/2;felt.renderOrder=9388;scene.add(felt)}felt.position.set(b.center.x,b.box.max.y+.028,b.center.z);felt.visible=true;state.feltInstalled=true;return true}
function installLights(){if(lights?.parent)return true;const b=box(table);lights=new THREE.Group();lights.name='PHASE388_QUEST_PROFESSIONAL_LIGHTS';const a=new THREE.AmbientLight(0xffffff,2.3),h=new THREE.HemisphereLight(0xd8f5ff,0x2a1034,3),k=new THREE.DirectionalLight(0xfff3dc,4.8),f=new THREE.DirectionalLight(0xaad8ff,3.6),s=new THREE.SpotLight(0xffffff,16,11,Math.PI/4.2,.62,1);k.position.set(b.center.x+3.2,b.box.max.y+5.2,b.center.z+3.6);f.position.set(b.center.x-3.4,b.box.max.y+3,b.center.z-2.8);s.position.set(b.center.x,b.box.max.y+4,b.center.z+.4);k.target.position.copy(b.center);f.target.position.copy(b.center);s.target.position.set(b.center.x,b.box.max.y,b.center.z);lights.add(a,h,k,k.target,f,f.target,s,s.target);scene.add(lights);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.72;renderer.shadowMap.enabled=false;state.lightingInstalled=true;return true}
async function sweep(){table=findTable()||table;if(!table)return false;seat=computeSeat()||seat;await installFelt();installLights();await ensureEric();alignEric();detachOld();removeOldFelt();try{window.SVR_PHASE386_OVERLAY_SWEEP?.();window.SVR_PHASE381_OVERLAY_SWEEP?.()}catch{}return true}
function burst(reason){for(const d of [0,80,180,360,700,1200,2200,3800,6500])setTimeout(()=>place(`${reason}-${d}`,d<900),d)}
function frame(t=0){if(!ACTIVE||!state.installed)return;neutralize();lock();patchApis();correct(t);if(t-lastSweep>900){lastSweep=t;void sweep()}raf=requestAnimationFrame(frame)}
function qa(){state.checkedAt=new Date().toISOString();return{...state,pass:!!(state.installed&&state.seatReady&&state.movementLocked&&state.ericLoaded&&state.ericUpright&&state.ericGrounded&&state.logoLoaded&&state.feltInstalled&&state.lightingInstalled)}}
async function install(){if(!ACTIVE||state.installed)return;const start=performance.now();while(performance.now()-start<30000){scene=window.__SVR_SCENE__||scene;camera=window.__SVR_CAMERA__||camera;renderer=window.__SVR_RENDERER__||renderer;table=findTable()||table;if(scene&&camera&&renderer&&rig()&&table)break;await new Promise(r=>setTimeout(r,100))}if(!scene||!camera||!renderer||!rig()||!table){state.lastError='PHASE388_RUNTIME_NOT_READY';return}state.installed=true;guard();patchApis();renderer.xr?.addEventListener?.('sessionstart',()=>burst('xr-start'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)burst('visible')});burst('install');await sweep();timer=setInterval(()=>{neutralize();lock();patchApis();hideTeleport();void sweep()},1000);raf=requestAnimationFrame(frame);window.addEventListener('beforeunload',()=>{clearInterval(timer);cancelAnimationFrame(raf);if(guarded&&rig()?.position&&oldCopy)rig().position.copy=oldCopy},{once:true})}
if(ACTIVE)install().catch(e=>state.lastError=String(e?.stack||e));
window.SVR_PHASE388_DIRECT_SEAT=(r)=>place(r||'api');window.SVR_PHASE388_ENSURE_ERIC=ensureEric;window.SVR_PHASE388_SWEEP=sweep;window.SVR_PHASE388_QA=qa;window.SVR_PHASE388_STATE=state;
