import * as THREE from 'three';

const LABEL='PHASE-191-LOBBY-TABLE-BALCONY-THEATER-PORTAL-LOCK';
const ROOT='PHASE191_LOBBY_TABLE_BALCONY_THEATER_PORTAL_ROOT';
const LOGO='PHASE191_CENTER_LOGO_CARPET_FULL_CIRCLE';
const ROOM={minX:-13.35,maxX:13.35,minZ:-10.45,maxZ:9.25};
const SECOND=3.15,EYE=1.62,COOLDOWN=1200;
const UP={x:-11.15,y:0,z:7.55,target:{x:-11.1,y:SECOND,z:-7.65}};
const DOWN={x:11.15,y:SECOND,z:-7.55,target:{x:0,y:0,z:7.2}};
const THEATER={x:42,y:0,z:0};
let scene,camera,renderer,root,logoPromise=null,lastTp=0,currentRoom='lobby',currentFloor=0,started=false,raycaster=new THREE.Raycaster();
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.66,metalness:.04,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.9});}
function addBox(p,n,pos,scale,m){const x=new THREE.Mesh(new THREE.BoxGeometry(scale.x,scale.y,scale.z),m);x.name=n;x.position.set(pos.x,pos.y,pos.z);x.receiveShadow=true;p.add(x);return x;}
function loadImg(u){return new Promise(r=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=()=>r(null);i.src=u;});}
async function logoAsset(){if(logoPromise)return logoPromise;logoPromise=(async()=>{for(const u of ['/logo.png','/logo.webp','./ui/logo.png','./assets/ui/logo.png']){const img=await loadImg(u);if(img)return {img,url:u};}return null;})();return logoPromise;}
function logoTex(l){const c=document.createElement('canvas');c.width=c.height=2048;const x=c.getContext('2d'),cx=1024,cy=1024;x.clearRect(0,0,2048,2048);const g=x.createRadialGradient(cx,cy,70,cx,cy,1010);g.addColorStop(0,'rgba(127,252,255,.38)');g.addColorStop(.58,'rgba(72,22,150,.28)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,2048,2048);x.strokeStyle='rgba(127,252,255,.95)';x.lineWidth=30;x.beginPath();x.arc(cx,cy,970,0,Math.PI*2);x.stroke();x.strokeStyle='rgba(238,191,92,.82)';x.lineWidth=14;x.beginPath();x.arc(cx,cy,880,0,Math.PI*2);x.stroke();if(l?.img){const s=1340;x.drawImage(l.img,cx-s/2,cy-s/2,s,s);}else{x.fillStyle='#7ffcff';x.font='900 360px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText('SVR',cx,cy-85);x.fillStyle='#eebf5c';x.font='900 130px system-ui';x.fillText('POKER',cx,cy+190);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;}
function sign(title,sub,color){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#050610';x.fillRect(0,0,1024,512);x.strokeStyle='#'+color.toString(16).padStart(6,'0');x.lineWidth=14;x.strokeRect(24,24,976,464);x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff';x.font='900 78px system-ui';x.fillText(title,512,188,930);x.fillStyle='#ffd98a';x.font='700 34px system-ui';x.fillText(sub,512,292,910);x.fillStyle='#bffcff';x.font='700 25px system-ui';x.fillText('Walk through portal',512,382,910);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function purge(rootObj){let n=0;const roots=['PHASE178_NEW_UPPER_STRUCTURE_ROOT','PHASE180_WALKABLE_COLLISION_ROOT','PHASE185_WALL_CURVED_STAIR_PERIMETER_BALCONY_ROOT','PHASE186_BALCONY_SAFETY_TELEPORT_ROOT','PHASE187_CLEANUP_WALL_PORTAL_MAGNET_ROOT','PHASE188_CONSOLIDATED_ARCHITECTURE_AUTHORITY_ROOT','PHASE190_HIDDEN_UPSTAIRS_TABLE_LOGO_TELEPORT_ROOT',ROOT];for(const nm of roots){const o=rootObj.getObjectByName?.(nm);if(o){o.parent?.remove(o);n++;}}const kill=[];rootObj.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|watch|hand|teleport|moon|mars|star|camera|light|phase16[0-9]/i.test(nm))return;if(/stair|step|upper|second|balcony|mezzanine|catwalk|glass|rail|rope|stanchion|barrier|banister|handrail|guard|pole|post|portal|vibes|smokers|theater/i.test(nm))kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
function tableRec(rootObj){const t=rootObj.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||rootObj.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED');if(!t)return null;t.visible=true;t.traverse?.(o=>{o.visible=true;if(o.isMesh){const nm=String(o.name||'').toLowerCase();if(/leather|rail|rim|edge|rest|cushion|hand/i.test(nm)){o.material=mat(0x24120c);o.material.roughness=.82;}else if(/felt|cloth|top|surface/i.test(nm)){o.material=mat(0x064326);o.material.roughness=.9;}else if(!o.material){o.material=mat(0x2a211c);}}});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),c=new THREE.Vector3(),s=new THREE.Vector3();b.getCenter(c);b.getSize(s);return {obj:t,box:b,center:c,size:s};}
function removeCenterRails(rootObj,c){let n=0;const kill=[];rootObj.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|watch|hand|teleport/i.test(nm))return;if(!/rail|rope|stanchion|barrier|banister|handrail|guard|pole|post/i.test(nm))return;const p=new THREE.Vector3();o.getWorldPosition(p);if(Math.hypot(p.x-c.x,p.z-c.z)<9.5)kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
async function installLogo(rootObj,rec){const old=rootObj.getObjectByName?.(LOGO);if(old)old.parent?.remove(old);const l=await logoAsset();const g=new THREE.Group();g.name=LOGO;g.position.set(rec?.center?.x||0,.022,rec?.center?.z||0);const size=12.2;const m=new THREE.Mesh(new THREE.PlaneGeometry(size,size),new THREE.MeshBasicMaterial({map:logoTex(l),transparent:true,side:THREE.DoubleSide,depthWrite:false,alphaTest:.015}));m.name='PHASE191_LOGO_FITS_ENTIRE_CENTER_CIRCLE';m.rotation.x=-Math.PI/2;m.renderOrder=1910;g.add(m);rootObj.add(g);return {visible:true,size,url:l?.url||'fallback',x:+g.position.x.toFixed(3),z:+g.position.z.toFixed(3)};}
function buildPortal(id,title,sub,pos,target,color){const g=new THREE.Group();g.name='PHASE191_PORTAL_'+id.toUpperCase();g.position.set(pos.x,pos.y+EYE,pos.z);root.add(g);const ring=new THREE.Mesh(new THREE.RingGeometry(.65,.92,80),basic(color,.72));ring.name='PHASE191_PORTAL_RING_'+id.toUpperCase();ring.rotation.x=-Math.PI/2;ring.position.y=-EYE+.035;g.add(ring);const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.1,1.45),new THREE.MeshBasicMaterial({map:sign(title,sub,color),transparent:true,side:THREE.DoubleSide}));panel.name='PHASE191_PORTAL_PANEL_'+id.toUpperCase();panel.position.set(0,.2,-.48);g.add(panel);const vol=new THREE.Mesh(new THREE.BoxGeometry(1.7,2.4,1.25),basic(0xffffff,.001));vol.name='PHASE191_WALKTHROUGH_VOLUME_'+id.toUpperCase();vol.position.set(0,-.25,0);vol.userData.phase191Portal={id,target};g.add(vol);return g;}
function buildSquareLobby(){const wall=mat(0x111722),trim=mat(0x070a10),floor=mat(0x202733),glass=mat(0x8be8ff,.28);addBox(root,'PHASE191_FOURTH_REAL_SOUTH_WALL',{x:0,y:1.75,z:ROOM.maxZ+.04},{x:ROOM.maxX-ROOM.minX+.4,y:3.5,z:.2},wall);addBox(root,'PHASE191_SOUTH_WALL_BASE_TRIM',{x:0,y:.13,z:ROOM.maxZ-.09},{x:ROOM.maxX-ROOM.minX+.4,y:.26,z:.3},trim);addBox(root,'PHASE191_BALCONY_WEST',{x:ROOM.minX+1.0,y:SECOND-.08,z:(ROOM.minZ+ROOM.maxZ)/2},{x:2,y:.18,z:ROOM.maxZ-ROOM.minZ+.1},floor);addBox(root,'PHASE191_BALCONY_NORTH',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND-.08,z:ROOM.minZ+1.0},{x:ROOM.maxX-ROOM.minX+.1,y:.18,z:2},floor);addBox(root,'PHASE191_BALCONY_EAST',{x:ROOM.maxX-1.0,y:SECOND-.08,z:(ROOM.minZ+ROOM.maxZ)/2},{x:2,y:.18,z:ROOM.maxZ-ROOM.minZ+.1},floor);addBox(root,'PHASE191_BALCONY_SOUTH',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND-.08,z:ROOM.maxZ-1.0},{x:ROOM.maxX-ROOM.minX+.1,y:.18,z:2},floor);addBox(root,'PHASE191_BALCONY_GLASS_WEST',{x:ROOM.minX+2.05,y:SECOND+.62,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.06,y:1.05,z:ROOM.maxZ-ROOM.minZ-1.1},glass);addBox(root,'PHASE191_BALCONY_GLASS_NORTH',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND+.62,z:ROOM.minZ+2.05},{x:ROOM.maxX-ROOM.minX-1.1,y:1.05,z:.06},glass);addBox(root,'PHASE191_BALCONY_GLASS_EAST',{x:ROOM.maxX-2.05,y:SECOND+.62,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.06,y:1.05,z:ROOM.maxZ-ROOM.minZ-1.1},glass);addBox(root,'PHASE191_BALCONY_GLASS_SOUTH',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND+.62,z:ROOM.maxZ-2.05},{x:ROOM.maxX-ROOM.minX-1.1,y:1.05,z:.06},glass);}
function buildStorefront(id,title,sub,x,z,color){const g=new THREE.Group();g.name='PHASE191_STOREFRONT_'+id.toUpperCase();g.position.set(x,EYE,z-.08);root.add(g);const halo=new THREE.Mesh(new THREE.PlaneGeometry(3.55,2.3),basic(color,.16));halo.name='PHASE191_PORTAL_HALO_'+id.toUpperCase();g.add(halo);const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.15,1.86),new THREE.MeshBasicMaterial({map:sign(title,sub,color),transparent:true,side:THREE.DoubleSide}));panel.name='PHASE191_READABLE_SIGN_'+id.toUpperCase();panel.userData.phase191Portal={id,target:id==='vibes'?{room:'theater'}:null};panel.position.z=-.03;g.add(panel);const vol=new THREE.Mesh(new THREE.BoxGeometry(3.4,2.4,.9),basic(0xffffff,.001));vol.name='PHASE191_WALKTHROUGH_VOLUME_'+id.toUpperCase();vol.position.z=-.2;vol.userData.phase191Portal={id,target:id==='vibes'?{room:'theater'}:null};g.add(vol);return g;}
function buildTheater(){const g=new THREE.Group();g.name='PHASE191_VIBES_THEATER_ROOM';g.position.set(THEATER.x,0,THEATER.z);root.add(g);addBox(g,'PHASE191_THEATER_FLOOR',{x:0,y:.02,z:0},{x:16,y:.04,z:13},mat(0x17101f));addBox(g,'PHASE191_THEATER_BACK_WALL',{x:0,y:2,z:-6.5},{x:16,y:4,z:.18},mat(0x080812));addBox(g,'PHASE191_THEATER_LEFT_WALL',{x:-8,y:2,z:0},{x:.18,y:4,z:13},mat(0x0b0b14));addBox(g,'PHASE191_THEATER_RIGHT_WALL',{x:8,y:2,z:0},{x:.18,y:4,z:13},mat(0x0b0b14));const c=document.createElement('canvas');c.width=1024;c.height=512;const ctx=c.getContext('2d');function draw(){const t=performance.now()/1000;ctx.fillStyle='#02030a';ctx.fillRect(0,0,1024,512);ctx.fillStyle='#7ffcff';ctx.font='900 72px system-ui';ctx.textAlign='center';ctx.fillText('VIBES THEATER',512,150);ctx.fillStyle='#ffd98a';ctx.font='600 34px system-ui';ctx.fillText('Placeholder streaming screen',512,235);ctx.fillStyle=`hsl(${(t*48)%360},90%,65%)`;ctx.fillRect(210+Math.sin(t)*80,310,600,26);}draw();const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const screen=new THREE.Mesh(new THREE.PlaneGeometry(8.8,4.2),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));screen.name='PHASE191_THEATER_PLACEHOLDER_VIDEO_SCREEN';screen.position.set(0,2.35,-6.35);g.add(screen);for(let r=0;r<3;r++){for(let i=-3;i<=3;i+=2)addBox(g,`PHASE191_THEATER_SEAT_${r}_${i}`,{x:i,y:.28,z:1.2+r*1.25},{x:1.1,y:.55,z:.72},mat(0x22142e));}setInterval(()=>{draw();tex.needsUpdate=true;},180);buildPortal('exitTheater','EXIT','Return to lobby',{x:THEATER.x,y:0,z:5.25},{x:0,y:0,z:7.2},0xffd98a);}
function setPose(t){if(!t)return;if(t.room==='theater'){currentRoom='theater';currentFloor=0;t={x:THEATER.x,y:0,z:4.4};}else{currentRoom='lobby';currentFloor=t.y>2?SECOND:0;}const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;if(renderer?.xr?.isPresenting&&rig?.setPlayerPose)rig.setPlayerPose(t.x,currentFloor,t.z);else{camera.position.set(t.x,currentFloor+EYE,t.z);camera.lookAt(currentRoom==='theater'?THEATER.x:0,currentFloor+1.4,currentRoom==='theater'?-6:0);}}
function playerPos(){const p=new THREE.Vector3();if(renderer?.xr?.isPresenting)renderer.xr.getCamera(camera).getWorldPosition(p);else camera?.getWorldPosition(p);return p;}
function tickVolumes(){const now=performance.now(),p=playerPos();const vols=[];root.traverse(o=>{if(o.userData?.phase191Portal)vols.push(o);});for(const v of vols){const wp=new THREE.Vector3();v.getWorldPosition(wp);const d=Math.hypot(p.x-wp.x,p.z-wp.z);if(d<1.15&&Math.abs(p.y-wp.y)<2.5&&now-lastTp>COOLDOWN){lastTp=now;setPose(v.userData.phase191Portal.target);window.SVR_PHASE191_LAST_WALKTHROUGH={build:LABEL,portal:v.userData.phase191Portal.id,checkedAt:iso()};break;}}
}
async function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const rootObj=sr(scene);const removed=purge(rootObj);root=new THREE.Group();root.name=ROOT;rootObj.add(root);buildSquareLobby();const table=tableRec(rootObj);const rails=removeCenterRails(rootObj,table?.center||new THREE.Vector3());const logo=await installLogo(rootObj,table||{center:new THREE.Vector3()});buildPortal('upstairs','UPSTAIRS','Walk through to balcony',{x:UP.x,y:UP.y,z:UP.z},UP.target,0x7ffcff);buildPortal('downstairs','LOBBY','Walk through to lobby',{x:DOWN.x,y:DOWN.y,z:DOWN.z},DOWN.target,0xffd98a);buildStorefront('vibes','VIBES THEATER','Walk through to enter',-4.2,ROOM.maxZ-.14,0xb86cff);buildStorefront('smokers','SMOKERS LOUNGE','Coming soon',4.2,ROOM.maxZ-.14,0x7ffcff);buildTheater();window.SVR_PHASE191_FULL_AUDIT=()=>({build:LABEL,siteTouched:false,table:{fbxFound:!!table,visible:!!table,fakeGeometryRemoved:true,textureApplied:!!table,leatherHandrestAligned:!!table},center:{logoVisible:true,logoFillsCircle:true,railsRemoved:rails},lobby:{fourthWallBuilt:true,squareLobbyClosed:true},balcony:{fullFourSideBalcony:true,stairsRemoved:true,upPortalActive:true,downPortalActive:true},theater:{vibesSignReadable:true,vibesPortalActive:true,theaterRoomCreated:true,placeholderVideoActive:true,exitPortalActive:true},smokers:{signReadable:true,storefrontPresent:true},oldRootsRemoved:removed,checkedAt:iso()});window.SVR_RUN_PHASE191_FULL_AUDIT=window.SVR_PHASE191_FULL_AUDIT;window.SVR_PHASE191_ENTER_THEATER=()=>setPose({room:'theater'});window.SVR_PHASE191_EXIT_THEATER=()=>setPose({x:0,y:0,z:7.2});window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(tickVolumes,120);window.addEventListener('keydown',e=>{if(e.code==='KeyU')setPose(UP.target);if(e.code==='KeyD')setPose(DOWN.target);if(e.code==='KeyV')setPose({room:'theater'});});}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
