import * as THREE from'three';
import{state,players}from'./phase336_authoritative_engine.js';
import{assetUrls,loadFirstTexture}from'./asset_base.js';
import{BUILD,buildTableLayout,dealOrder,validateLayout,selfTest}from'./phase341_table_coordinate_model.js';
const ROOT='PHASE341_CANONICAL_TABLE_PRESENTATION_ROOT',CARD_RX=/^(P85_(?:COMM|HAND)_|PHASE334_.*CARD|PHASE326_ANDROID_PLAYER_CARD_FACE_ROOT)/i;
let scene,root,table,layout,group,passRoot,logoRoot,raf=0,lastHand=-1,lastCommunity=0,lastBurn=0,installed=false;
const records={holes:Array.from({length:6},()=>[null,null]),community:Array(5).fill(null),burn:[]},animations=[],folded=Array(6).fill(false),textures=new Map();
const V=()=>window.__SVR_SCENE__||null,R=()=>V()?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||V();
function authority(){return window.SVR_TABLE_AUTHORITY||R()?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||R()?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||R()?.getObjectByName?.('PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED')||R()?.getObjectByName?.('PHASE326_ANDROID_TABLE_FALLBACK')||null}
function bounds(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c}}
function materialName(o){return(Array.isArray(o.material)?o.material:[o.material]).map(m=>m?.name||'').join(' ').toLowerCase()}
function detect(){table=authority();if(!table)return false;const full=bounds(table);let felt=null,score=-1e9;table.traverse(o=>{if(!o.isMesh)return;let z;try{z=bounds(o)}catch{return}const n=`${o.name} ${materialName(o)}`.toLowerCase(),flat=Math.max(z.s.x,z.s.z)/Math.max(.001,z.s.y),x=(/polotno|felt|cloth|baize|surface|play/.test(n)?180:0)+z.s.x*z.s.z*2+(flat>20?35:0);if(x>score){score=x;felt={o,...z}}});const src=felt||{o:null,...full};layout=buildTableLayout({center:src.c,size:src.s,top:src.b.max.y,seatCount:6});polish(table,felt?.o);window.SVR_PHASE341_TABLE_LAYOUT=layout;return true}
function polish(t,felt){t.visible=true;t.traverse(o=>{if(!o.isMesh||!o.material)return;const n=`${o.name} ${materialName(o)}`.toLowerCase(),arr=Array.isArray(o.material)?o.material:[o.material],out=arr.map(m=>{const x=m.clone?.()||m;if(o===felt||/polotno|felt|cloth|baize/.test(n)){x.color?.setHex(0x062d16);if('roughness'in x)x.roughness=.78;if('metalness'in x)x.metalness=.02}else if(/rail|leather|armrest|pad/.test(n)){x.color?.setHex(0x090a0f);if('roughness'in x)x.roughness=.46}else if(/silver|chrome|metal|trim/.test(n)){x.color?.setHex(0xb8bec8);if('roughness'in x)x.roughness=.24;if('metalness'in x)x.metalness=.82}x.needsUpdate=true;return x});o.material=Array.isArray(o.material)?out:out[0];o.frustumCulled=true})}
function canvasTexture(draw,w=512,h=720){const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');draw(g,c);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function backTex(){if(textures.has('back'))return textures.get('back');const t=canvasTexture((g,c)=>{g.fillStyle='#17133f';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#7ffcff';g.lineWidth=20;g.strokeRect(16,16,c.width-32,c.height-32);g.fillStyle='#fff';g.textAlign='center';g.font='900 86px system-ui';g.fillText('SVR',c.width/2,c.height*.49);g.fillStyle='#ffd98a';g.font='900 38px system-ui';g.fillText('POKER',c.width/2,c.height*.59)});textures.set('back',t);return t}
function faceTex(card){const id=card?.id||`${card?.r||'?'}${card?.s||'?'}`;if(textures.has(id))return textures.get(id);const t=canvasTexture((g,c)=>{g.fillStyle='#f8f4e9';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#171717';g.lineWidth=16;g.strokeRect(12,12,c.width-24,c.height-24);const suit={S:'♠',H:'♥',D:'♦',C:'♣'}[card?.s]||'',red=/H|D/.test(card?.s||'');g.fillStyle=red?'#b51632':'#111';g.textAlign='center';g.textBaseline='middle';g.font='900 190px serif';g.fillText(card?.r||'?',c.width/2,c.height*.34);g.font='900 220px serif';g.fillText(suit,c.width/2,c.height*.68)});textures.set(id,t);return t}
function record(name){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(layout.card.w,layout.card.h),new THREE.MeshBasicMaterial({map:backTex(),transparent:true,depthWrite:false,side:THREE.DoubleSide,toneMapped:false}));mesh.name=name;mesh.rotation.x=-Math.PI/2;mesh.renderOrder=9341;mesh.visible=false;group.add(mesh);return{mesh,faceUp:false,card:null}}
function lp(p){const v=new THREE.Vector3(p.x,p.y,p.z);root.worldToLocal(v);return v}
function setPose(rec,p){rec.mesh.position.copy(lp(p));rec.mesh.rotation.set(-Math.PI/2,0,p.rot||0)}
function setFace(rec,card,up){rec.card=card||null;rec.faceUp=!!up;rec.mesh.material.map=up&&card?faceTex(card):backTex();rec.mesh.material.needsUpdate=true}
function flip(rec,up){if(rec.faceUp===up)return;animations.push({kind:'flip',rec,start:performance.now(),duration:260,swapped:false,up,card:rec.card});startLoop()}
function move(rec,from,to,delay=0,duration=520,done){rec.mesh.visible=true;setPose(rec,from);animations.push({kind:'move',rec,from:lp(from),to:lp(to),start:performance.now()+delay,duration,done});startLoop()}
function startLoop(){if(!raf)raf=requestAnimationFrame(tick)}
function tick(now){for(let i=animations.length-1;i>=0;i--){const a=animations[i],raw=(now-a.start)/a.duration;if(raw<0)continue;const t=Math.min(1,raw),e=1-Math.pow(1-t,3);if(a.kind==='move'){a.rec.mesh.position.lerpVectors(a.from,a.to,e);a.rec.mesh.position.y+=Math.sin(Math.PI*t)*.16;if(t>=1){a.rec.mesh.position.copy(a.to);a.done?.();animations.splice(i,1)}}else{const s=t<.5?1-t*2:(t-.5)*2;if(t>=.5&&!a.swapped){a.swapped=true;setFace(a.rec,a.card,a.up)}a.rec.mesh.scale.x=Math.max(.02,s);if(t>=1){a.rec.mesh.scale.x=1;animations.splice(i,1)}}}if(animations.length)raf=requestAnimationFrame(tick);else raf=0}
function capsulePoints(w,d,y,n=72){const r=Math.min(d,w*.48),straight=Math.max(.02,w-r),pts=[];for(let i=0;i<=n;i++){const a=-Math.PI/2+i/n*Math.PI;pts.push(new THREE.Vector3(layout.center.x+straight+Math.cos(a)*r,y,layout.center.z+Math.sin(a)*r))}for(let i=0;i<=n;i++){const a=Math.PI/2+i/n*Math.PI;pts.push(new THREE.Vector3(layout.center.x-straight+Math.cos(a)*r,y,layout.center.z+Math.sin(a)*r))}return pts}
function tube(pts,color,r,name){const curve=new THREE.CatmullRomCurve3(pts.map(lp),true,'centripetal',.5),m=new THREE.Mesh(new THREE.TubeGeometry(curve,144,r,8,true),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.95,depthWrite:false,toneMapped:false}));m.name=name;m.renderOrder=9338;return m}
function buildPass(){['PHASE332_PASS_LINE_ROOT','PHASE334_PROFESSIONAL_PASS_LINE_ROOT'].forEach(n=>scene.getObjectByName(n)?.traverse(o=>o.visible=false));passRoot=new THREE.Group();passRoot.name='PHASE341_CANONICAL_PASS_LINE_ROOT';group.add(passRoot);const p=layout.passLine,y=layout.top+.016;passRoot.add(tube(capsulePoints(p.outerW,p.outerD,y),0xffffff,.0062,'PHASE341_PASS_WHITE'));passRoot.add(tube(capsulePoints(p.outerW-p.inset,p.outerD-p.inset,y+.002),0xd5a940,.0042,'PHASE341_PASS_GOLD'))}
async function buildLogo(){scene.traverse(o=>{if(/TABLE.*LOGO|CENTER_LOGO|PHASE339_ANDROID_TABLE_LOGO/i.test(o.name||''))o.visible=false});let tex=null;try{tex=await loadFirstTexture(assetUrls('ui/logo.png','logo.png'),{colorSpace:THREE.SRGBColorSpace})}catch{}if(!tex)tex=canvasTexture((g,c)=>{g.fillStyle='rgba(0,0,0,.02)';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#d9b45c';g.lineWidth=16;g.strokeRect(20,20,c.width-40,c.height-40);g.fillStyle='#fff';g.textAlign='center';g.font='900 150px system-ui';g.fillText('SVR',c.width/2,c.height*.45);g.fillStyle='#d9b45c';g.font='900 60px system-ui';g.fillText('POKER',c.width/2,c.height*.61)},1024,512);const aspect=tex.image?.width&&tex.image?.height?tex.image.width/tex.image.height:2;logoRoot=new THREE.Group();logoRoot.name='PHASE341_CANONICAL_CENTER_LOGO_ROOT';const m=new THREE.Mesh(new THREE.PlaneGeometry(layout.logo.w,layout.logo.w/aspect),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide,toneMapped:false,polygonOffset:true,polygonOffsetFactor:-4}));m.name='PHASE341_CANONICAL_CENTER_LOGO';m.position.copy(lp(layout.logo));m.rotation.x=-Math.PI/2;m.renderOrder=9340;logoRoot.add(m);group.add(logoRoot)}
function buildCards(){for(let s=0;s<6;s++)for(let k=0;k<2;k++)records.holes[s][k]=record(`PHASE341_HOLE_${s}_${k}`);for(let i=0;i<5;i++)records.community[i]=record(`PHASE341_COMMUNITY_${i}`);for(let i=0;i<3;i++){const r=record(`PHASE341_BURN_${i}`);setPose(r,{...layout.burn,x:layout.burn.x+i*.012,z:layout.burn.z-i*.008});records.burn.push(r)}}
function suppressOld(){scene?.traverse(o=>{if(CARD_RX.test(o.name||''))o.visible=false});const old=document.getElementById('svr326Cards');if(old)old.dataset.phase341Authority='true'}
function cardText(c){return c?`${c.r}${{S:'♠',H:'♥',D:'♦',C:'♣'}[c.s]||''}`:'--'}
function syncAndroid(){if((window.SVR_PLATFORM||'')!=='android')return;const rootEl=document.getElementById('svr326Root');if(!rootEl)return;const cards=[...rootEl.querySelectorAll('#svr326Cards .svr326Card')],hand=players[0]?.hand||[];cards.forEach((e,i)=>{const t=cardText(hand[i]);e.textContent=t;e.classList.toggle('red',/[♥♦]/.test(t))});const audit=window.SVR_RUN_PHASE336_POKER_AUDIT?.(),you=audit?.players?.[0],need=Math.max(0,(audit?.currentBet||0)-(you?.bet||0)),legal=new Set(audit?.legalActions||[]);const buttons=[...rootEl.querySelectorAll('[data-act]')],primary=buttons.find(b=>b.dataset.act==='deal'||b.dataset.phase341Primary==='1'),clean=buttons.find(b=>b.dataset.act==='clean'||b.dataset.act==='allin');if(primary){primary.dataset.phase341Primary='1';primary.dataset.act=['showdown','idle'].includes(audit?.phase)?'next':'fold';primary.textContent=['showdown','idle'].includes(audit?.phase)?'NEXT HAND':'FOLD';primary.disabled=!['showdown','idle'].includes(audit?.phase)&&!legal.has('fold')}if(clean){clean.dataset.act='allin';clean.textContent='ALL IN';clean.disabled=!legal.has('allin')}const check=buttons.find(b=>b.dataset.act==='check'),call=buttons.find(b=>b.dataset.act==='call'),raise=buttons.find(b=>b.dataset.act==='raise');if(check)check.disabled=!legal.has('check');if(call){call.textContent=need?`CALL $${need}`:'CALL';call.disabled=!legal.has('call')}if(raise)raise.disabled=!(legal.has('raise')||legal.has('bet'))}
function bindAndroid(){if((window.SVR_PLATFORM||'')!=='android'||document.__svr341Buttons)return;document.__svr341Buttons=true;document.addEventListener('click',e=>{const b=e.target.closest?.('#svr326Root [data-act]');if(!b)return;const a=b.dataset.act;if(!['check','call','raise','fold','allin','next'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();if(a==='raise'){const n=Number(document.getElementById('svr326RaiseSlider')?.value||window.SVR_ANDROID_RAISE_AMOUNT||0);window.SVR_POKER_RAISE_TO?.(n)}else if(a==='next')window.SVR_POKER_NEXT_HAND?.();else window.SVR_POKER_ACTION?.(a)},true)}
function queueDeal(){animations.splice(0);for(const row of records.holes)for(const r of row){r.mesh.visible=false;r.mesh.scale.x=1}for(const r of records.community){r.mesh.visible=false;r.mesh.scale.x=1}for(const r of records.burn)r.mesh.visible=false;const order=dealOrder(state.dealer,6);let n=0;for(let round=0;round<2;round++)for(const seat of order){const c=players[seat]?.hand?.[round];if(!c)continue;const r=records.holes[seat][round];setFace(r,c,seat===0);move(r,layout.dealerSource,layout.holes[seat][round],n++*95,500)}lastCommunity=0;lastBurn=0;folded.fill(false)}
function addStreet(){while(lastBurn<(state.burn?.length||0)&&lastBurn<3){const r=records.burn[lastBurn],c=state.burn[lastBurn];setFace(r,c,false);move(r,layout.dealerSource,{...layout.burn,x:layout.burn.x+lastBurn*.012,z:layout.burn.z-lastBurn*.008},lastBurn*35,350);lastBurn++}while(lastCommunity<(state.community?.length||0)&&lastCommunity<5){const i=lastCommunity++,r=records.community[i],c=state.community[i];setFace(r,c,true);move(r,layout.dealerSource,layout.community[i],120+i%3*90,470)}}
function sync(){if(!layout)return;suppressOld();if(state.handNo!==lastHand){lastHand=state.handNo;queueDeal()}addStreet();players.forEach((p,i)=>{if(p.folded&&!folded[i]){folded[i]=true;records.holes[i].forEach((r,k)=>{if(!r.mesh.visible)return;move(r,layout.holes[i][k],{...layout.muck,x:layout.muck.x+k*.03},k*55,420,()=>r.mesh.visible=false)})}if(state.phase==='showdown'&&!p.folded)records.holes[i].forEach(r=>{if(r.card)flip(r,true)})});syncAndroid();window.SVR_PHASE341_STATE={build:BUILD,handNo:state.handNo,phase:state.phase,community:state.community.length,burn:state.burn.length,animations:animations.length,checkedAt:new Date().toISOString()}}
async function rebuild(){scene=V();root=R();if(!scene||!root||!detect())return false;scene.getObjectByName(ROOT)?.removeFromParent?.();group=new THREE.Group();group.name=ROOT;root.add(group);buildPass();await buildLogo();buildCards();lastHand=-1;sync();bindAndroid();window.SVR_AUTHORITY_CLAIM?.('table-presentation',BUILD,group,341);return true}
function qa(){const old=[];scene?.traverse(o=>{if(o.visible&&CARD_RX.test(o.name||''))old.push(o.name)});const l=validateLayout(layout),logos=[];scene?.traverse(o=>{if(o.visible&&/TABLE.*LOGO|CENTER_LOGO/i.test(o.name||''))logos.push(o.name)});const result={build:BUILD,active:!!group,platform:window.SVR_PLATFORM||'desktop',table:table?.name||null,layout:l,canonicalCards:records.holes.flat().filter(r=>r?.mesh).length+records.community.filter(Boolean).length,burnCards:records.burn.length,oldVisibleCards:old,visibleLogos:logos,animationQueue:animations.length,modelSelfTest:selfTest(),androidButtons:(window.SVR_PLATFORM||'')==='android'?{root:document.querySelectorAll('#svr326Root').length,move:document.querySelectorAll('#svr326Move').length,look:document.querySelectorAll('#svr326Look').length}:null,checkedAt:new Date().toISOString()};result.pass=result.active&&l.pass&&old.length===0&&logos.length<=1&&result.modelSelfTest.pass;window.SVR_PHASE341_QA_STATE=result;return result}
function boot(){if(installed)return;installed=true;window.addEventListener('svr:poker-state',()=>setTimeout(sync,0));window.addEventListener('svr:platform-ready',()=>setTimeout(rebuild,0));[350,900,1800,3200].forEach(ms=>setTimeout(()=>{if(!group)rebuild();else sync()},ms));setInterval(()=>{suppressOld();syncAndroid()},650);window.SVR_PHASE341_QA=qa;window.SVR_PHASE341_REBUILD=rebuild;window.SVR_PHASE341_DEMO_DEAL=queueDeal;window.SVR_PHASE341_MODEL_SELF_TEST=selfTest}
boot();
