import * as THREE from 'three';
const LABEL='PHASE-219-TABLE-POSITION-OPTIONS-CONTROL-LOCK';
const ROOT='PHASE219_TABLE_POSITION_OPTIONS_CONTROL_ROOT';
let scene,camera,renderer,rootGroup,started=false,menuOpen=false,lastMenu=false;
let offset={forward:0,height:0,lean:0};
function sr(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function wc(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function camPos(){const p=new THREE.Vector3();wc()?.getWorldPosition(p);return p;}
function camDir(){const d=new THREE.Vector3();wc()?.getWorldDirection(d);d.y=0;if(d.lengthSq()<.001)d.set(0,0,-1);return d.normalize();}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null;}
function table(){const r=sr();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function tableRec(){const t=table();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{obj:t,b,s,c,top:b.max.y,innerW:Math.max(1.4,Math.min(s.x*.52,3.4)),innerD:Math.max(.8,Math.min(s.z*.40,1.7))};}
function pauseTravel(){let n=0;try{window.SVR_PHASE193_TELEPORT_OFF?.();window.SVR_PHASE170_TELEPORT_OFF?.();window.SVR_PHASE184_TELEPORT_OFF?.();}catch(e){}const r=rig();if(r){try{r.setEnabled?.(false);r.setMode?.('table');r.setVisible?.(false);}catch(e){}}
scene?.traverse?.(o=>{const nm=String(o.name||'');if(/laser|pointer|ray|arc|target_ring|logo_target|teleport/i.test(nm)&&!/watch|table|card|chip|portal/i.test(nm)){o.visible=false;if(o.material){o.material.opacity=0;o.material.transparent=true;}n++;}});window.SVR_TABLE_TELEPORT_LOCKED_OFF=true;return n;}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.1,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function box(p,n,pos,s,m){const o=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);o.name=n;o.position.set(pos.x,pos.y,pos.z);o.frustumCulled=false;p.add(o);return o;}
function labelTex(a,b=''){const c=document.createElement('canvas');c.width=768;c.height=256;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.84)';x.fillRect(0,0,768,256);x.strokeStyle='#7ffcff';x.lineWidth=7;x.strokeRect(10,10,748,236);x.fillStyle='#fff';x.font='900 52px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(a,384,86,720);x.fillStyle='#ffd98a';x.font='800 32px system-ui';x.fillText(b,384,160,720);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function cardTex(r,s){const c=document.createElement('canvas');c.width=256;c.height=360;const x=c.getContext('2d');x.fillStyle='#f6f0df';x.fillRect(0,0,256,360);x.strokeStyle='#111';x.lineWidth=10;x.strokeRect(10,10,236,340);x.fillStyle=(s==='H'||s==='D')?'#b5142b':'#101015';x.font='900 62px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(r,128,130);x.font='900 70px system-ui';x.fillText({S:'♠',H:'♥',D:'♦',C:'♣'}[s]||s,128,225);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function makeLabel(p,n,pos,a,b,scale=1){const m=new THREE.Mesh(new THREE.PlaneGeometry(1.12*scale,.36*scale),new THREE.MeshBasicMaterial({map:labelTex(a,b),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name=n;m.position.copy(pos);m.rotation.x=-.2;m.renderOrder=2190;p.add(m);return m;}
function card(p,n,pos,r,s,scale=.34){const m=new THREE.Mesh(new THREE.PlaneGeometry(.27*scale/.34,.38*scale/.34),new THREE.MeshBasicMaterial({map:cardTex(r,s),side:THREE.DoubleSide,depthWrite:false}));m.name=n;m.position.copy(pos);m.rotation.x=-Math.PI/2;m.renderOrder=2191;p.add(m);return m;}
function chip(p,n,pos,color,count=6){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,.016,28),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.14}));m.name=`${n}_${i}`;m.position.set(pos.x,pos.y+i*.017,pos.z);m.renderOrder=2191;p.add(m);}}
function hideOldPlayItems(){let h=0;sr()?.traverse?.(o=>{const n=String(o.name||'');if(/PHASE168_DEMO_CARD|PHASE168_.*CHIP|ACTION_LABEL|OPEN_PLAYER_SEAT_LABEL|TABLE_STATUS_FLOATING|PHASE212_STABLE|PHASE214_|PHASE215_|PHASE217_/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);h++;}});return h;}
function buildTable(){const tr=tableRec();if(!tr)return null;hideOldPlayItems();const r=sr();const old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;r.add(rootGroup);const c=tr.c,cardY=tr.top-0.045,chipY=tr.top+0.004,labelY=tr.top+1.35;const ix=tr.innerW,iz=tr.innerD;const cx=x=>Math.max(c.x-ix*.48,Math.min(c.x+ix*.48,x));const cz=z=>Math.max(c.z-iz*.48,Math.min(c.z+iz*.48,z));
// Six-player deal: two cards per player, inside table boundary.
const seats=[['YOU',0,iz*.56,0x7ffcff],['BOT 1',-ix*.44,iz*.34,0xff5b8c],['BOT 2',-ix*.48,-iz*.08,0xffd98a],['BOT 3',0,-iz*.52,0x8eff8e],['BOT 4',ix*.48,-iz*.08,0xa78bfa],['BOT 5',ix*.44,iz*.34,0xff8bd1]];
const deck=[['A','S'],['K','H'],['7','D'],['3','C'],['Q','S'],['J','H'],['8','D'],['8','C'],['5','S'],['5','H'],['10','D'],['2','C']];
seats.forEach(([name,x,z,color],i)=>{const px=cx(c.x+x),pz=cz(c.z+z);makeLabel(rootGroup,`PHASE219_HIGH_TAG_${i}`,new THREE.Vector3(px,labelY,pz),name,i===0?'PLAYER':'BOT',1);chip(rootGroup,`PHASE219_SIDE_CHIPS_${i}`,new THREE.Vector3(px,chipY,pz),color,5);const [a,b]=[deck[i*2],deck[i*2+1]];card(rootGroup,`PHASE219_DEALT_CARD_${i}_A`,new THREE.Vector3(cx(px-.11),cardY,cz(pz-.08)),a[0],a[1],.36);card(rootGroup,`PHASE219_DEALT_CARD_${i}_B`,new THREE.Vector3(cx(px+.11),cardY,cz(pz-.08)),b[0],b[1],.36);});
[['BURN',''],['A','D'],['K','S'],['Q','H'],['J','D'],['10','C']].forEach(([ra,su],i)=>{if(i===0){makeLabel(rootGroup,'PHASE219_BURN_TURN_FLOATING_LABEL',new THREE.Vector3(c.x-0.72,tr.top+.58,c.z-iz*.06),'BURN','TURN',.55);}else card(rootGroup,`PHASE219_FLOATING_COMMUNITY_${i}`,new THREE.Vector3(c.x+(i-3)*.23,tr.top+.48,c.z-iz*.1),ra,su,.30);});
chip(rootGroup,'PHASE219_SIDE_PLAYER_CHIPS_LEFT',new THREE.Vector3(cx(c.x-.62),chipY,cz(c.z+iz*.46)),0x7ffcff,8);chip(rootGroup,'PHASE219_SIDE_PLAYER_CHIPS_RIGHT',new THREE.Vector3(cx(c.x+.62),chipY,cz(c.z+iz*.46)),0xffd98a,8);
makeLabel(rootGroup,'PHASE219_TABLE_TAG_HIGH',new THREE.Vector3(c.x,labelY+.45,c.z-iz*.65),'TABLE DEMO','POSITION MODE',.9);
return{table:tr.obj.name,top:+tr.top.toFixed(3),cardY:+cardY.toFixed(3),chipY:+chipY.toFixed(3),labelY:+labelY.toFixed(3),sixPlayers:true};}
function positionDisplay(){if(!rootGroup)return;const old=rootGroup.getObjectByName('PHASE219_SMALL_POSITION_DISPLAY');if(old)old.parent?.remove(old);const p=camPos(),d=camDir();const pos=p.clone().add(d.clone().multiplyScalar(1.05));pos.y+=.18;const tr=tableRec();let dist='NO TABLE';if(tr)dist=`X ${p.x.toFixed(2)} Y ${p.y.toFixed(2)} Z ${p.z.toFixed(2)} | F ${offset.forward.toFixed(2)} H ${offset.height.toFixed(2)}`;const m=new THREE.Mesh(new THREE.PlaneGeometry(.78,.16),new THREE.MeshBasicMaterial({map:labelTex('POS',dist),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name='PHASE219_SMALL_POSITION_DISPLAY';m.position.copy(pos);m.lookAt(p);m.scale.set(.55,.55,.55);rootGroup.add(m);}
function applySeat(){const tr=tableRec();if(!tr||!camera)return null;const innerD=tr.innerD;const eye=new THREE.Vector3(tr.c.x,tr.top+1.08+offset.height,tr.c.z+innerD*(1.28-offset.forward));const target=new THREE.Vector3(tr.c.x,tr.top+.02,tr.c.z-innerD*(.04+offset.lean));const r=rig();if(renderer?.xr?.isPresenting&&r?.setPlayerPose)r.setPlayerPose(eye.x,0,eye.z);else{camera.position.copy(eye);camera.lookAt(target);}return{eye:{x:+eye.x.toFixed(2),y:+eye.y.toFixed(2),z:+eye.z.toFixed(2)},target:{x:+target.x.toFixed(2),y:+target.y.toFixed(2),z:+target.z.toFixed(2)}};}
function input(){const pads=navigator.getGamepads?navigator.getGamepads():[];let menu=false,up=false,down=false,left=false,right=false;for(const g of pads){if(!g)continue;const id=(g.id||'').toLowerCase();const b=g.buttons||[];if(b[4]?.pressed||b[5]?.pressed||b[8]?.pressed||b[9]?.pressed||/menu/.test(id))menu=menu||!!(b[4]?.pressed||b[5]?.pressed||b[8]?.pressed||b[9]?.pressed);const a=g.axes||[];if((a[1]||0)<-.55)up=true;if((a[1]||0)>.55)down=true;if((a[0]||0)<-.55)left=true;if((a[0]||0)>.55)right=true;}const hand=window.SVR_HAND_INPUT||window.SVR_PHASE170_HAND_INPUT||window.SVR_ACTIVE_HAND_INPUT||{};if(hand.leftPinch||hand.leftMenu||hand.menu||hand.hamburger)menu=true;return{menu,up,down,left,right};}
function optionsPanel(){if(!rootGroup)return;const old=rootGroup.getObjectByName('PHASE219_OPTIONS_PANEL');if(old)old.parent?.remove(old);if(!menuOpen)return;const p=camPos(),d=camDir();const pos=p.clone().add(d.clone().multiplyScalar(1.25));pos.y-=.08;const m=new THREE.Mesh(new THREE.PlaneGeometry(1.55,.62),new THREE.MeshBasicMaterial({map:labelTex('TABLE OPTIONS','Menu: open/close | Stick: distance/height'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name='PHASE219_OPTIONS_PANEL';m.position.copy(pos);m.lookAt(p);rootGroup.add(m);}
function controlTick(){const i=input();if(i.menu&&!lastMenu)menuOpen=!menuOpen;lastMenu=i.menu;if(menuOpen){if(i.up)offset.forward=Math.min(.45,offset.forward+.01);if(i.down)offset.forward=Math.max(-.35,offset.forward-.01);if(i.right)offset.height=Math.min(.35,offset.height+.008);if(i.left)offset.height=Math.max(-.25,offset.height-.008);} }
function hideSky(){scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon|mars|planet|star|sky|sprite|sparkle|blink|pulse/i.test(n)&&!/teleport|portal|watch|hand|table|card|chip/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);}});scene.background=new THREE.Color(0x030407);scene.fog=null;}
function pass(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera)return null;pauseTravel();hideSky();controlTick();if(!rootGroup)buildTable();positionDisplay();optionsPanel();const seat=applySeat();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,positionDisplay:true,menuOpen,tableOptions:true,teleportOffAtTable:true,sixPlayerDeal:true,tagsRaised:true,playerCardsLowered:true,offset,seat,checkedAt:new Date().toISOString()};window.SVR_PHASE219_TABLE_POSITION_OPTIONS_CONTROL_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){const b=buildTable();window.SVR_RUN_PHASE219_TABLE_OPTIONS_AUDIT=()=>pass();window.SVR_PHASE219_OPTIONS_OPEN=()=>{menuOpen=true;return pass();};window.SVR_PHASE219_OPTIONS_CLOSE=()=>{menuOpen=false;return pass();};window.SVR_PHASE219_NUDGE_FORWARD=()=>{offset.forward=Math.min(.45,offset.forward+.05);return pass();};window.SVR_PHASE219_NUDGE_BACK=()=>{offset.forward=Math.max(-.35,offset.forward-.05);return pass();};window.SVR_PHASE219_NUDGE_UP=()=>{offset.height=Math.min(.35,offset.height+.04);return pass();};window.SVR_PHASE219_NUDGE_DOWN=()=>{offset.height=Math.max(-.25,offset.height-.04);return pass();};if(!started){started=true;setInterval(pass,260);}return !!b;}
[400,1000,2200,4200,7000].forEach(ms=>setTimeout(install,ms));install();
