/* PHASE-421-VR-TABLE-FINAL-POLISH-LOCK */
import * as THREE from 'three';
const BUILD='PHASE-421-VR-TABLE-FINAL-POLISH-LOCK';
const TARGET_RECESS_METERS=0.026;
const RECESS_TOLERANCE=0.012;
const state={build:BUILD,installed:false,tableFound:false,sourceFeltFound:false,polishedFeltReady:false,feltRecessMeters:null,feltMaterials:0,railMaterials:0,oldOverlaysHidden:0,lastError:null,checkedAt:null};
const v1=new THREE.Vector3(),v2=new THREE.Vector3(),q1=new THREE.Quaternion();
let polishedFelt=null,microTexture=null;
function scene(){return window.__SVR_SCENE__||null}
function table(){return window.SVR_TABLE_AUTHORITY||window.SVR_PHASE380_ORIGINAL_TABLE||scene()?.getObjectByName?.('PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY')||null}
function bounds(object){object?.updateWorldMatrix?.(true,true);const box=new THREE.Box3().setFromObject(object,true);return{box,size:box.getSize(new THREE.Vector3()),center:box.getCenter(new THREE.Vector3())}}
function worldDeltaY(object,delta){if(!object)return false;if(!object.parent){object.position.y+=delta;return true}object.parent.updateWorldMatrix?.(true,false);object.parent.getWorldQuaternion(q1).invert();object.parent.getWorldScale(v2);v1.set(0,delta,0).applyQuaternion(q1);v1.x/=Math.abs(v2.x)>1e-6?v2.x:1;v1.y/=Math.abs(v2.y)>1e-6?v2.y:1;v1.z/=Math.abs(v2.z)>1e-6?v2.z:1;object.position.add(v1);return true}
function makeMicroTexture(){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d'),image=ctx.createImageData(256,256);for(let i=0;i<image.data.length;i+=4){const n=105+Math.floor(Math.random()*46);image.data[i]=n;image.data[i+1]=n;image.data[i+2]=n;image.data[i+3]=255}ctx.putImageData(image,0,0);const texture=new THREE.CanvasTexture(canvas);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(12,7);texture.needsUpdate=true;return texture}
function sourceFelt(t){return window.SVR_PHASE390_PLAY_SURFACE||t?.getObjectByName?.('PHASE390_RECESSED_BRANDED_PLAYING_SURFACE')||null}
function hideOldOverlays(root,source){let hidden=0;root?.traverse?.(object=>{if(!object||object===source||object===polishedFelt)return;const name=String(object.name||'');if(/PHASE38(?:4|6|8)_.*FELT|OFFICIAL_SITE_LOGO_FELT/i.test(name)){object.visible=false;hidden++}});state.oldOverlaysHidden=hidden;return hidden}
function cloneMaterial(entry){const material=entry?.clone?.()||new THREE.MeshStandardMaterial();material.userData={...(material.userData||{}),svrPhase421Felt:true};material.visible=true;material.transparent=false;material.opacity=1;material.depthTest=true;material.depthWrite=true;material.side=THREE.DoubleSide;if(material.color)material.color.setHex(0xffffff);if('roughness'in material)material.roughness=.96;if('metalness'in material)material.metalness=0;microTexture=microTexture||makeMicroTexture();if('bumpMap'in material){material.bumpMap=microTexture;material.bumpScale=.0013}material.polygonOffset=true;material.polygonOffsetFactor=-.35;material.polygonOffsetUnits=-.35;material.needsUpdate=true;return material}
function ensurePolishedFelt(t,source){if(polishedFelt?.parent)return polishedFelt;const sourceMaterials=Array.isArray(source.material)?source.material:[source.material],materials=sourceMaterials.map(cloneMaterial);polishedFelt=new THREE.Mesh(source.geometry.clone(),Array.isArray(source.material)?materials:materials[0]);polishedFelt.name='PHASE421_FINAL_POLISHED_PLAYING_SURFACE';polishedFelt.userData={svrPhase421FinalFelt:true,build:BUILD,sourceSurface:source.name||null,targetRecessMeters:TARGET_RECESS_METERS};source.updateWorldMatrix?.(true,false);source.matrixWorld.decompose(polishedFelt.position,polishedFelt.quaternion,polishedFelt.scale);scene().add(polishedFelt);t.attach(polishedFelt);polishedFelt.frustumCulled=false;polishedFelt.receiveShadow=true;polishedFelt.renderOrder=4210;state.feltMaterials=materials.length;window.SVR_PHASE421_PLAY_SURFACE=polishedFelt;return polishedFelt}
function placePolishedFelt(t,source){const felt=ensurePolishedFelt(t,source),whole=bounds(t),current=bounds(felt),targetTop=whole.box.max.y-TARGET_RECESS_METERS,delta=targetTop-current.box.max.y;if(Math.abs(delta)>.0007)worldDeltaY(felt,delta);const after=bounds(felt);state.feltRecessMeters=+(whole.box.max.y-after.box.max.y).toFixed(4);felt.visible=true;const materials=Array.isArray(felt.material)?felt.material:[felt.material];materials.forEach(material=>{if(!material)return;material.colorWrite=true;material.depthWrite=true;material.depthTest=true;material.needsUpdate=true});state.polishedFeltReady=true;window.SVR_PHASE421_PLAY_SURFACE_INFO={topY:after.box.max.y,center:after.center.clone(),size:after.size.clone(),recessMeters:whole.box.max.y-after.box.max.y};return felt}
function suppressDeepSource(source){const list=Array.isArray(source.material)?source.material:[source.material];for(const material of list){if(!material)continue;material.colorWrite=false;material.needsUpdate=true}source.userData={...(source.userData||{}),svrPhase421DeepSourceSuppressed:true};return true}
function polishRails(t,felt,source){let count=0;t?.traverse?.(object=>{if(!object?.isMesh||object===felt||object===source)return;const label=`${object.name||''} ${(Array.isArray(object.material)?object.material:[object.material]).map(m=>m?.name||'').join(' ')}`.toLowerCase();if(!/armrest|handrest|rail|leather|padding|circle02|object001/.test(label))return;const metal=/silver|chrome|metal|trim/.test(label),sourceMaterials=Array.isArray(object.material)?object.material:[object.material],next=sourceMaterials.map(entry=>{const m=entry?.userData?.svrPhase421Rail?entry:(entry?.clone?.()||new THREE.MeshStandardMaterial());m.userData={...(m.userData||{}),svrPhase421Rail:true};m.visible=true;m.transparent=false;m.opacity=1;m.depthTest=true;m.depthWrite=true;if(m.color&&!m.map)m.color.setHex(metal?0x716b7b:0x161019);if('roughness'in m)m.roughness=metal?.26:.44;if('metalness'in m)m.metalness=metal?.70:.06;m.needsUpdate=true;return m});object.material=Array.isArray(object.material)?next:next[0];object.visible=true;object.receiveShadow=true;count+=next.length});state.railMaterials=count;return count}
function sweep(reason='manual'){try{const t=table();if(!t)return false;const source=sourceFelt(t);state.tableFound=Boolean(t);state.sourceFeltFound=Boolean(source);if(!source)throw new Error('PHASE421_SOURCE_FELT_NOT_FOUND');hideOldOverlays(scene(),source);const felt=placePolishedFelt(t,source);suppressDeepSource(source);polishRails(t,felt,source);state.installed=true;state.lastError=null;state.checkedAt=new Date().toISOString();window.SVR_PHASE421_VR_TABLE_STATE={...state,reason};return window.SVR_PHASE421_VR_TABLE_STATE}catch(error){state.lastError=String(error?.message||error);state.checkedAt=new Date().toISOString();return{...state,reason}}}
function watchdog(){const source=sourceFelt(table());if(source)suppressDeepSource(source);if(polishedFelt?.parent)polishedFelt.visible=true}
window.SVR_PHASE421_VR_TABLE_SWEEP=sweep;
window.SVR_PHASE421_VR_TABLE_QA=()=>({build:BUILD,...state,targetRecessMeters:TARGET_RECESS_METERS,recessTolerance:RECESS_TOLERANCE,recessWithinTolerance:Number.isFinite(state.feltRecessMeters)&&Math.abs(state.feltRecessMeters-TARGET_RECESS_METERS)<=RECESS_TOLERANCE,stableSuccessorSurface:Boolean(polishedFelt?.parent),deepPhase390SurfaceColorSuppressed:Boolean(sourceFelt(table())?.userData?.svrPhase421DeepSourceSuppressed),tableOnlyPolish:true,lobbyGeometryUntouched:true,locomotionUntouched:true,pass:Boolean(state.installed&&state.tableFound&&state.sourceFeltFound&&state.polishedFeltReady&&Math.abs(state.feltRecessMeters-TARGET_RECESS_METERS)<=RECESS_TOLERANCE&&!state.lastError),checkedAt:new Date().toISOString()});
window.addEventListener('svr:phase396-core-ready',()=>setTimeout(()=>sweep('phase396-core-ready'),280),{once:true});
window.addEventListener('svr:hand-start',()=>setTimeout(()=>{watchdog();sweep('hand-start')},80));
setTimeout(()=>sweep('phase421-delayed'),3200);
setInterval(watchdog,800);
