/* PHASE-420-TOURNAMENT-START-AUTHORITY-LOCK */
const BUILD='PHASE-420-TOURNAMENT-START-AUTHORITY-LOCK';
const SLOT_MS=5*60*60*1000,ANCHOR=Date.UTC(2026,0,1,0,0,0);
const state={build:BUILD,installed:false,currentSlot:null,nextRegistrationSlot:null,eligible:false,entryTarget:null,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s),slotId=t=>Math.floor((t-ANCHOR)/SLOT_MS),slot=id=>({id,start:ANCHOR+id*SLOT_MS,end:ANCHOR+(id+1)*SLOT_MS});
function accountGate(){return window.SVR_PHASE412_TOURNAMENT_ACCOUNT_STATE||null}
function currentSlot(){return slot(slotId(Date.now()))}
function nextSlot(){return slot(slotId(Date.now())+1)}
function entryUrl(id){return `/game/android-tabletop.html?v=phase420&mode=tournament&tournament=reiki-open-100&slot=${encodeURIComponent(id)}`}
function sync(){try{const current=currentSlot(),next=nextSlot(),gate=accountGate(),enter=$('#enterTournament');state.currentSlot=current;state.nextRegistrationSlot=next;state.eligible=Boolean(gate?.eligible);if(enter&&state.eligible){state.entryTarget=entryUrl(current.id);enter.href=state.entryTarget;enter.dataset.phase420Slot=String(current.id);enter.dataset.accountGate='passed';enter.textContent='ENTER CURRENT TOURNAMENT'}else if(enter){state.entryTarget=enter.getAttribute('href')||null;enter.dataset.phase420Slot=String(current.id)}const nextLabel=$('#phase411NextTournament');if(nextLabel){nextLabel.dataset.phase420CurrentSlot=String(current.id);nextLabel.title=`Current slot #${current.id} runs until ${new Date(current.end).toLocaleString()}. Sign-up is for slot #${next.id}.`}document.querySelectorAll('a[href*="tournament-signup.html"]').forEach(a=>{try{const u=new URL(a.href,location.href);u.searchParams.set('v','phase420');u.searchParams.set('slot',String(next.id));a.href=u.pathname+u.search}catch{}});document.body.dataset.phase420CurrentTournament=String(current.id);document.body.dataset.phase420NextRegistration=String(next.id);state.installed=true;state.lastError=null;state.checkedAt=new Date().toISOString();return true}catch(error){state.lastError=String(error?.message||error);state.checkedAt=new Date().toISOString();return false}}
function boot(){sync();window.addEventListener('svr:account-ready',sync);window.addEventListener('svr:account-change',sync);setTimeout(sync,500);setTimeout(sync,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.SVR_PHASE420_TOURNAMENT_START_QA=()=>({build:BUILD,...state,slotMilliseconds:SLOT_MS,exactFiveHourCadence:SLOT_MS===18000000,currentEntryUsesCurrentSlot:Boolean(state.eligible&&state.entryTarget?.includes(`slot=${state.currentSlot?.id}`))||!state.eligible,registrationUsesNextSlot:Boolean(state.nextRegistrationSlot&&state.currentSlot&&state.nextRegistrationSlot.id===state.currentSlot.id+1),productionSharedRegistrationLive:Boolean(window.SVR_PHASE419_TOURNAMENT_REGISTRATION_QA?.()?.sharedBackend),pass:Boolean(state.installed&&SLOT_MS===18000000&&!state.lastError),checkedAt:new Date().toISOString()});
