import * as THREE from 'three';
const LABEL='PHASE-214-STATIC-CARDS-CHIPS-LIGHTS-LOCK';
const ROOT='PHASE214_STATIC_CARDS_CHIPS_LIGHTS_ROOT';
let scene,rootGroup,started=false;
function base(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function table(){const r=base();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function bounds(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c};}
function hideOld(){let h=0;base()?.traverse?.(o=>{const n=String(o.name||'');if(/PHASE168_DEMO_CARD|PHASE168_.*CHIP|PHASE168_CENTER_POT|ACTION_LABEL|OPEN_PLAYER_SEAT_LABEL|TABLE_STATUS_FLOATING|PHASE212_STABLE/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);h++;}});return h;}
function cardTex(rank,suit){const c=document.createElement('canvas');c.width=256;c.height=360;const x=c.getContext('2d');x.fillStyle='#f7f7f0';x.fillRect(0,0,256,360);x.strokeStyle='#111';x.lineWidth=10;x.strokeRect(8,8,240,344);x.fillStyle=(suit==='♥'||suit==='♦')?'#b3001b':'#111';x.font='900 58px serif';x.fillText(rank,28,74);x.font='900 72px serif';x.textAlign='center';x.textBaseline='middle';x.fillText(suit,128,190);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function labelTex(a,b){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.86)';x.fillRect(0,0,512,160);x.strokeStyle='#7ffcff';x.lineWidth=5;x.strokeRect(8,8,496,144);x.fillStyle='#fff';x.font='900 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(a,256,58,470);x.fillStyle='#ffd98a';x.font='800 24px system-ui';x.fillText(b,256,108,470);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function makeLabel(p,n,pos,a,b){const m=new THREE.Mesh(new THREE.PlaneGeometry(1.12,.35),new THREE.MeshBasicMaterial({map:labelTex(a,b),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name=n;m.position.copy(pos);m.rotation.x=-.25;m.renderOrder=2140;p.add(m);return m;}
function makeChip(p,n,pos,color,count){for(let i=0;i<count;i++){const chip=new THREE.Mesh(new THREE.CylinderGeometry(.075,.075,.018,28),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.18}));chip.name=`${n}_${i}`;chip.position.set(pos.x,pos.y+i*.02,pos.z);chip.renderOrder=2140;p.add(chip);}}
function makeCard(p,n,pos,rank,suit){const m=new THREE.Mesh(new THREE.PlaneGeometry(.28,.39),new THREE.MeshBasicMaterial({map:cardTex(rank,suit),side:THREE.DoubleSide,depthWrite:false}));m.name=n;m.position.copy(pos);m.rotation.x=-Math.PI/2;m.renderOrder=2141;p.add(m);return m;}
function addLight(p,n,pos,color,intensity=1.3){const l=new THREE.PointLight(color,intensity,18,2);l.name=n;l.position.set(pos.x,pos.y,pos.z);p.add(l);return l;}
function build(){scene=window.__SVR_SCENE__;if(!scene)return null;const r=base(),t=table();if(!t)return null;hideOld();const old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;r.add(rootGroup);const bb=bounds(t),c=bb.c,w=Math.max(bb.s.x,4.2),d=Math.max(bb.s.z,2.3),y=bb.b.max.y+.035;
const seats=[['YOU',0,d*.86,0x7ffcff],['NOVA',-w*.45,d*.55,0xff5b8c],['ROOK',-w*.56,-d*.04,0xffd98a],['ACE',0,-d*.76,0x8eff8e],['VEGA',w*.56,-d*.04,0xa78bfa],['IVY',w*.45,d*.55,0xff8bd1]];
seats.forEach(([name,x,z,color],i)=>{const px=c.x+x,pz=c.z+z;const toward=new THREE.Vector3(c.x-px,0,c.z-pz).normalize();makeLabel(rootGroup,`PHASE214_LABEL_${name}`,new THREE.Vector3(px,y+.48,pz),name,i===0?'OPEN SEAT':'BOT READY');makeChip(rootGroup,`PHASE214_CHIPS_${name}`,new THREE.Vector3(px+toward.x*.42,y,pz+toward.z*.42),color,5);});
[['A','♠',-.32,.05],['K','♥',-.11,.05],['Q','♦',.11,.05],['J','♣',.32,.05],['10','♠',.53,.05]].forEach(([rank,suit,x,z],i)=>makeCard(rootGroup,`PHASE214_COMMUNITY_CARD_${i}`,new THREE.Vector3(c.x+x,y+.012,c.z+z),rank,suit));
makeCard(rootGroup,'PHASE214_PLAYER_CARD_A',new THREE.Vector3(c.x-.14,y+.012,c.z+d*.42),'9','♥');makeCard(rootGroup,'PHASE214_PLAYER_CARD_B',new THREE.Vector3(c.x+.14,y+.012,c.z+d*.42),'9','♣');
makeLabel(rootGroup,'PHASE214_TABLE_STATUS',new THREE.Vector3(c.x,y+.62,c.z-d*.5),'POT 75','TABLE READY');makeChip(rootGroup,'PHASE214_CENTER_POT',new THREE.Vector3(c.x,y,c.z+d*.12),0xffd98a,8);
addLight(rootGroup,'PHASE214_TABLE_WARM_KEY_LIGHT',{x:c.x,y:4.8,z:c.z+1.5},0xffd9aa,1.45);addLight(rootGroup,'PHASE214_TABLE_CYAN_FILL_LIGHT',{x:c.x-3.8,y:3.4,z:c.z-2.5},0x7ffcff,1.05);addLight(rootGroup,'PHASE214_TABLE_PURPLE_FILL_LIGHT',{x:c.x+3.8,y:3.4,z:c.z-2.5},0xb68cff,.9);const amb=new THREE.HemisphereLight(0xcfefff,0x080810,.55);amb.name='PHASE214_SOFT_LOBBY_HEMISPHERE_LIGHT';rootGroup.add(amb);
return {table:t.name,labels:7,chipStacks:7,cards:7,lights:4,y:+y.toFixed(3)};}
function pass(){const hidden=hideOld();if(!rootGroup)build();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,dynamicHidden:hidden,staticRoot:!!rootGroup,checkedAt:new Date().toISOString()};window.SVR_PHASE214_STATIC_CARDS_CHIPS_LIGHTS_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){const b=build();window.SVR_RUN_PHASE214_STATIC_AUDIT=()=>pass();if(!started){started=true;setInterval(pass,300);}return !!b;}
[600,1300,2600,5200,9000].forEach(ms=>setTimeout(install,ms));install();
