import { state, players } from './phase336_authoritative_engine.js';

export const BUILD = 'PHASE-368-ANDROID-JOIN-CARD-GYRO-UX-LOCK';
const ACTIVE=(window.SVR_PLATFORM||'').toLowerCase()==='android'||/\/game\/android\.html$/i.test(location.pathname)||(/Android/i.test(navigator.userAgent||'')&&!/Quest|Oculus|Meta Quest/i.test(navigator.userAgent||''));
const runtime={build:BUILD,active:ACTIVE,installed:false,joined:false,singleJoinControl:false,hiddenLegacySeatControls:0,sticksHiddenWhileSeated:false,cardTenNormalized:true,cardFacesEnhanced:0,gyroPreserved:false,repairs:0,syncs:0,lastError:null,installedAt:null,checkedAt:null};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const joined=()=>Boolean(window.SVR_PHASE363_JOINED_IMMEDIATE??window.SVR_PHASE363_STATE?.joined??window.SVR_PHASE347_STATE?.seated);
let observer=null,syncTimer=0;
function visible(e){if(!e)return false;const c=getComputedStyle(e),r=e.getBoundingClientRect();return c.display!=='none'&&c.visibility!=='hidden'&&Number(c.opacity||1)>.02&&r.width>2&&r.height>2}
function rank(v){v=String(v??'?').toUpperCase();return v==='T'?'10':v}
function suit(v){return({S:'♠',H:'♥',D:'♦',C:'♣'})[String(v||'').toUpperCase()]||''}
function parts(card){if(!card)return{rank:'',suit:'',red:false};const raw=String(card.id||`${card.r||card.rank||''}${card.s||card.suit||''}`).toUpperCase(),code=String(card.s||card.suit||raw.slice(-1)).toUpperCase();return{rank:rank(card.r||card.rank||raw.slice(0,-1)),suit:suit(code),red:/H|D/.test(code)}}
function css(){if($('#svr368-style'))return;const s=document.createElement('style');s.id='svr368-style';s.textContent=`
body.svr368-android .svr347-card{position:relative;display:block!important;overflow:hidden;background:linear-gradient(145deg,#fffdf7,#dfd6c6)!important;border:1px solid #151515!important;color:#111!important;font-family:Georgia,'Times New Roman',serif!important}
body.svr368-android .svr347-card.red{color:#b30f2d!important}body.svr368-android .svr347-card.empty{display:grid!important;place-items:center;background:linear-gradient(145deg,#24184f,#040c1c)!important;border-color:rgba(127,252,255,.48)!important;color:rgba(255,255,255,.28)!important}
.svr368-corner{position:absolute;display:grid;line-height:.78;text-align:center;font-weight:900}.svr368-corner span{font-size:.68em;line-height:1}.svr368-corner.top{left:4px;top:4px}.svr368-corner.bottom{right:4px;bottom:4px;transform:rotate(180deg)}.svr368-pip{position:absolute;inset:0;display:grid;place-items:center;font-size:1.7em;line-height:1}
body.svr368-android .svr347-community-card{width:48px!important;height:68px!important;font-size:16px!important;border-radius:8px!important}body.svr368-android .svr347-hole-card{width:58px!important;height:82px!important;font-size:20px!important;border-radius:10px!important}
body.svr368-android.svr368-seated #svr347Move,body.svr368-android.svr368-seated #svr347Look,body.svr368-android.svr368-seated [data-svr368-nav-hidden="1"]{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
body.svr368-android.svr368-lobby #svr347Actions{display:grid!important;grid-template-columns:1fr!important;width:min(42vw,270px)!important;right:18px!important;left:auto!important;top:50%!important;bottom:auto!important;transform:translateY(-50%)!important}body.svr368-android.svr368-lobby #svr347Actions button:not([data-ui="seat"]){display:none!important}body.svr368-android.svr368-lobby #svr347Actions [data-ui="seat"]{display:block!important;visibility:visible!important;opacity:1!important;min-height:66px!important;font-size:17px!important}
body.svr368-android.svr368-seated #svr347Actions{right:max(12px,env(safe-area-inset-right))!important;left:auto!important;top:52%!important;bottom:auto!important;transform:translateY(-50%)!important;width:min(34vw,290px)!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}body.svr368-android.svr368-seated #svr347Actions button{height:50px!important}
body.svr368-android.svr368-seated #svr347Community{top:max(10px,env(safe-area-inset-top))!important;left:50%!important;transform:translateX(-50%)!important;padding:7px 9px!important;background:rgba(0,0,0,.54)!important}body.svr368-android.svr368-seated #svr347Hole{left:max(12px,env(safe-area-inset-left))!important;bottom:max(18px,env(safe-area-inset-bottom))!important;transform:none!important;background:rgba(0,0,0,.50)!important}
body.svr368-android.svr368-seated #svr357TurnPanel{left:max(12px,env(safe-area-inset-left))!important;top:max(12px,calc(env(safe-area-inset-top) + 4px))!important;width:min(38vw,390px)!important;padding:6px 9px!important;background:rgba(0,0,0,.46)!important;box-shadow:none!important}body.svr368-android.svr368-seated #svr363Bankroll{right:max(12px,env(safe-area-inset-right))!important;top:max(10px,env(safe-area-inset-top))!important;transform:scale(.9)!important;transform-origin:top right!important}body.svr368-android.svr368-seated #svr365BrandSlot{left:50%!important;top:auto!important;bottom:max(8px,env(safe-area-inset-bottom))!important;transform:translateX(-50%) scale(.88)!important;transform-origin:bottom center!important}
@media(max-width:640px),(orientation:portrait){body.svr368-android.svr368-seated #svr347Community{top:max(54px,calc(env(safe-area-inset-top) + 46px))!important}body.svr368-android.svr368-seated #svr347Actions{right:8px!important;width:min(46vw,260px)!important}body.svr368-android .svr347-community-card{width:42px!important;height:60px!important}body.svr368-android .svr347-hole-card{width:52px!important;height:74px!important}}
`;document.head.appendChild(s)}
function nav(){const seated=joined();for(const e of $$('button,a')){const t=String(e.textContent||'').trim().toUpperCase();if(!['LOBBY','CENTER','CENTER VIEW'].includes(t))continue;if(e.dataset.svr368NavHidden!=='1')e.dataset.svr368NavHidden='1';if(e.hidden!==seated)e.hidden=seated;const aria=String(seated);if(e.getAttribute('aria-hidden')!==aria)e.setAttribute('aria-hidden',aria);try{if(e.inert!==seated)e.inert=seated}catch{}}}
function oneJoin(){const a=$('#svr347Actions [data-ui="seat"]'),seated=joined();let hidden=0;for(const b of $$('button')){if(b===a||b.closest('#runtimeRecovery')||b.id==='startRuntimeBtn')continue;const t=String(b.textContent||'').trim().toUpperCase();if(!['SIT','SEAT','SIT DOWN','SIT AT TABLE','PLAY GAME','JOIN TABLE','LEAVE','LEAVE TABLE'].includes(t))continue;if(!b.hidden)b.hidden=true;if(b.getAttribute('aria-hidden')!=='true')b.setAttribute('aria-hidden','true');try{if(!b.inert)b.inert=true}catch{}hidden++}runtime.hiddenLegacySeatControls=Math.max(runtime.hiddenLegacySeatControls,hidden);if(a){if(a.hidden)a.hidden=false;if(a.hasAttribute('aria-hidden'))a.removeAttribute('aria-hidden');try{if(a.inert)a.inert=false}catch{}const label=seated?'LEAVE TABLE':'JOIN TABLE';if(a.textContent!==label)a.textContent=label;const aria=seated?'Leave poker table':'Join poker table';if(a.getAttribute('aria-label')!==aria)a.setAttribute('aria-label',aria)}runtime.singleJoinControl=Boolean(a)&&$$('button').filter(b=>visible(b)&&/^(JOIN TABLE|LEAVE TABLE|SIT|SEAT|PLAY GAME|LEAVE)$/i.test(b.textContent.trim())).length===1}
function face(e,card){if(!e)return;if(!card){if(e.dataset.svr368Signature==='empty')return;e.dataset.svr368Signature='empty';e.classList.add('empty');e.classList.remove('red');e.textContent='•';delete e.dataset.rank;delete e.dataset.suit;return}const p=parts(card),signature=`${p.rank}|${p.suit}`;if(e.dataset.svr368Signature===signature)return;e.dataset.svr368Signature=signature;e.classList.remove('empty');e.classList.toggle('red',p.red);e.innerHTML=`<span class="svr368-corner top">${p.rank}<span>${p.suit}</span></span><span class="svr368-pip">${p.suit}</span><span class="svr368-corner bottom">${p.rank}<span>${p.suit}</span></span>`;e.dataset.rank=p.rank;e.dataset.suit=p.suit;runtime.cardFacesEnhanced++}
function cards(){const h=players.find(p=>p?.human)?.hand||players[0]?.hand||[],c=state.community||[];$$('#svr347Hole [data-hole]').forEach((e,i)=>face(e,h[i]));$$('#svr347Community [data-community]').forEach((e,i)=>face(e,c[i]))}
function repair(){const seated=joined();runtime.joined=seated;document.body.classList.add('svr368-android');document.body.classList.toggle('svr368-seated',seated);document.body.classList.toggle('svr368-lobby',!seated);oneJoin();nav();const m=$('#svr347Move'),l=$('#svr347Look');if(!seated&&(!visible(m)||!visible(l))){[m,l].filter(Boolean).forEach(e=>{if(e.hidden)e.hidden=false;e.style.removeProperty('display');e.style.removeProperty('visibility');e.style.removeProperty('opacity');e.style.removeProperty('pointer-events')});runtime.repairs++}runtime.sticksHiddenWhileSeated=!seated||(!visible(m)&&!visible(l));runtime.gyroPreserved=Boolean(window.SVR_PHASE365_STATE?.gyroAvailable??('DeviceOrientationEvent'in window))}
function sync(){if(!ACTIVE)return;try{runtime.syncs++;repair();cards();runtime.checkedAt=new Date().toISOString();window.SVR_PHASE368_JOIN_CARD_STATE={...runtime}}catch(e){runtime.lastError=String(e?.message||e)}}
function scheduleSync(delay=40){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{syncTimer=0;sync()},delay)}
function qa(){sync();const seated=joined(),buttons=$$('button').filter(b=>visible(b)&&/^(JOIN TABLE|LEAVE TABLE|SIT|SEAT|PLAY GAME|LEAVE)$/i.test(b.textContent.trim())),text=$$('.svr347-card').map(e=>e.textContent).join(' ');const r={...runtime,seated,visibleJoinControls:buttons.length,joinLabels:buttons.map(b=>b.textContent.trim()),moveVisible:visible($('#svr347Move')),lookVisible:visible($('#svr347Look')),cardTenUsesNumber:!/(^|\s)T[♠♥♦♣]/.test(text),communityCards:$$('#svr347Community [data-community]').length,holeCards:$$('#svr347Hole [data-hole]').length,checkedAt:new Date().toISOString()};r.pass=ACTIVE&&buttons.length===1&&(!seated||(!r.moveVisible&&!r.lookVisible))&&r.cardTenUsesNumber&&r.communityCards===5&&r.holeCards===2;return window.SVR_PHASE368_JOIN_CARD_QA_STATE=r}
function install(){if(!ACTIVE||runtime.installed)return;runtime.installed=true;runtime.installedAt=new Date().toISOString();css();observer=new MutationObserver(records=>{if(records.some(record=>record.type==='childList'&&record.addedNodes.length))scheduleSync(55)});observer.observe(document.body,{childList:true,subtree:true});['svr:poker-state','svr:phase363-state','svr:phase363-immediate-join-state'].forEach(n=>window.addEventListener(n,()=>scheduleSync(0)));[0,250,700,1400].forEach(d=>setTimeout(sync,d));window.SVR_PHASE368_JOIN_CARD_QA=qa;window.SVR_PHASE368_SYNC=sync;window.SVR_PHASE368_JOIN_CARD_STATE={...runtime};window.dispatchEvent(new CustomEvent('svr:phase368-join-card-ready',{detail:{build:BUILD}}))}
install();
