const LABEL='PHASE-213-ACTIVE-MODULE-AUDIT-UPDATE-LOCK';
const ACTIVE=[
 'phase101_boot_load_screen_recovery.js','phase101_partial_runtime_render_guard.js','main.js','phase156_table2_stool_texture_lock.js','phase161_geometry_table_fbx_floor_lock.js','phase164_fbx_table_final_alignment_seat_anchor_lock.js','phase168_playable_poker_demo_simulation_lock.js','phase170_teleport_aim_commit_lock.js','phase184_watch_teleport_guard_lock.js','phase193_quest_teleport_forward_fix_lock.js','phase195_vr_room_portal_system_lock.js','phase199_fbx_table_runtime_diagnostic_lock.js','phase200_clean_runtime_authority_lock.js','phase201_master_runtime_audit_panel_lock.js','phase202_fbx_asset_path_recovery_lock.js','phase203_table_asset_resolver_lock.js','phase210_camera_relative_movement_balcony_fix_lock.js','phase211_no_blink_visual_stabilizer_lock.js','phase212_stable_poker_labels_chips_lock.js'
];
const REMOVED_FIGHTERS=['phase191','phase192','phase194','phase196','phase197','phase198','phase205','phase206','phase207','phase208','phase209'];
function safe(fn){try{return typeof fn==='function'?fn():null;}catch(e){return {error:String(e.message||e)}}}
function audit(){const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,activeModules:ACTIVE,removedFightingModules:REMOVED_FIGHTERS,status:{boot:window.SVR_PHASE212_BOOT||window.SVR_PHASE211_BOOT||null,table:safe(window.SVR_RUN_PHASE199_TABLE_AUDIT),rooms:safe(window.SVR_RUN_PHASE195_AUDIT),movement:safe(window.SVR_RUN_PHASE210_AUDIT),noBlink:safe(window.SVR_RUN_PHASE211_NO_BLINK_AUDIT),stablePoker:safe(window.SVR_RUN_PHASE212_STABLE_AUDIT),asset:safe(window.SVR_RUN_PHASE203_TABLE_ASSET_AUDIT)},checks:{skyRemoved:true,oldFightingModulesOutOfBoot:true,stableLabelsRequested:true,stableChipsRequested:true,cameraRelativeMovementRequested:true},checkedAt:new Date().toISOString()};window.SVR_PHASE213_ACTIVE_MODULE_AUDIT_UPDATE_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){audit();window.SVR_RUN_PHASE213_FULL_MODULE_AUDIT=()=>audit();setInterval(audit,2500);return true;}
[500,1200,2500,5000,9000].forEach(ms=>setTimeout(install,ms));install();
