/* PHASE-405-MOBILE-HANDS-GUEST-PROFILE-BURN-LOCK */
const BUILD='PHASE-405-MOBILE-HANDS-GUEST-PROFILE-BURN-LOCK';
const HANDS=[['Royal Flush','A-K-Q-J-10, same suit'],['Straight Flush','Five consecutive, same suit'],['Four of a Kind','Four cards same rank'],['Full House','Three of a kind + pair'],['Flush','Five cards same suit'],['Straight','Five consecutive ranks'],['Three of a Kind','Three cards same rank'],['Two Pair','Two different pairs'],['Pair','Two cards same rank'],['High Card','Highest five cards play']];
const STYLE={Claudia:'TIGHT',Eric:'BALANCED',Maya:'AGGRESSIVE',Darius:'LOOSE AGGRESSIVE',Nova:'TRICKY'};
const state={build:BUILD,installed:false,burnZoneCount:0,lastWinHand:0,lastRound:-1,lastComplete:null,lastError:null};
const $=s=>document.querySelector(s),game=()=>window.SVR_PHASE393_ANDROID_STATE;
function account(){try{return JSON.parse(localStorage.getItem('svr_demo_account')||'{}')?.profile||null}catch{return null}}
function portrait(){return localStorage.getItem('svr405_profile_portrait')||''}
function identity(){const p=account(),name=(p?.displayName||localStorage.getItem('svr405_guest_name')||'Guest 1').trim();return{name,rank:p?.rank||'GUEST PLAYER',signedIn:Boolean(p),portrait:portrait()}}
function enforceBurn(){const burns=[...document.querySelectorAll('.burn-zone')],keep=burns.find(x=>x.id==='burnZone')||burns[0];burns.forEach(x=>{if(x!==keep)x.remove()});if(keep){keep.id='burnZone';keep.classList.add('phase405-burn-lock')}const label=$('#burnLabel');if(label&&/burn/i.test(label.textContent||''))label.textContent='DECK';state.burnZoneCount=document.querySelectorAll('.burn-zone').length;return state.burnZoneCount===1}
function applyIdentity(){const id=identity(),g=game(),name=$('#userName'),avatar=$('#userAvatar');if(name)name.textContent=id.name;if(g?.players?.[0]&&/^(YOU|Guest 1)$/i.test(g.players[0].name||''))g.players[0].name=id.name;if(avatar){avatar.textContent=id.portrait?'':id.name[0]?.toUpperCase()||'G';avatar.style.backgroundImage=id.portrait?`url(${id.portrait})`:'';avatar.style.backgroundSize='cover';avatar.style.backgroundPosition='center'}return id}
function close(){document.querySelectorAll('.phase405-sheet').forEach(x=>x.classList.add('hide'))}
function guestState(){const m=window.SVR_PHASE399_MATCH_STATE||{},id=identity(),live=Boolean(m.authoritativeGame&&m.matched);return{guest1:id.name,guest2:live?(m.peerName||'Guest 2'):'Guest 2',guest2Status:live?'LIVE PEER':'OPEN • BOT STANDBY',serverConfigured:Boolean(m.configured),live}}
function profileData(index){const g=game(),p=g?.players?.[index],id=identity();if(index===0)return{name:id.name,rank:p?.rank||id.rank,stack:p?.stack||g?.stack||0,status:id.signedIn?'SIGNED PROFILE':'GUEST PROFILE',style:'PLAYER',image:id.portrait};const name=p?.name||`Seat ${index+1}`;return{name,rank:p?.rank||'TABLE PLAYER',stack:p?.stack||0,status:p?.folded?'FOLDED':p?.allIn?'ALL IN':'IN HAND',style:STYLE[name]||'PLAYER',image:''}}
function openProfile(index=0){ensureUi();const d=profileData(index),sheet=$('#phase405ProfileSheet'),photo=sheet?.querySelector('.phase405-profile-photo');if(!sheet||!photo)return;photo.textContent=d.image?'':d.name[0]?.toUpperCase()||'P';photo.style.backgroundImage=d.image?`url(${d.image})`:'';photo.style.backgroundSize='cover';photo.style.backgroundPosition='center';sheet.querySelector('[data-name]').textContent=d.name;sheet.querySelector('[data-rank]').textContent=d.rank;sheet.querySelector('[data-stack]').textContent=`STACK $${Number(d.stack||0).toLocaleString()}`;sheet.querySelector('[data-status]').textContent=`${d.status} • ${d.style}`;sheet.classList.remove('hide')}
function renderGuests(){const g=guestState(),sheet=$('#phase405GuestSheet');if(!sheet)return;sheet.querySelector('[data-g1]').textContent=g.guest1;sheet.querySelector('[data-g2]').textContent=g.guest2;sheet.querySelector('[data-g2s]').textContent=g.guest2Status;sheet.querySelector('[data-g2card]').classList.toggle('live',g.live);sheet.querySelector('[data-note]').textContent=g.live?'Guest 2 is connected through live game sync.':'Guest 2 is reserved for a future live peer. Until a secure match server is configured, the bot stays in that seat.'}
function transition(title,copy,confetti=false){const el=$('#phase405Transition');if(!el)return;el.querySelector('strong').textContent=title;el.querySelector('span').textContent=copy;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');if(confetti)for(let i=0;i<24;i++){const c=document.createElement('i');c.className='phase405-confetti';c.style.left=`${42+Math.random()*16}%`;c.style.top='45%';c.style.setProperty('--x',`${(Math.random()-.5)*480}px`);c.style.setProperty('--y',`${100+Math.random()*300}px`);c.style.setProperty('--c',['#7ffcff','#ffd98a','#8dffb4','#c99cff'][i%4]);document.body.appendChild(c);setTimeout(()=>c.remove(),1700)}}
function tournamentFx(){let t=null;try{t=JSON.parse(localStorage.getItem('svr401_reiki_first50_tournament')||'null')}catch{}if(!t)return;const active=new URLSearchParams(location.search).get('mode')==='tournament';if(!active)return;const round=Number(t.round||0);if(round!==state.lastRound){const prior=state.lastRound;state.lastRound=round;if(prior>=0&&t.status==='in_progress'&&round>0&&round%2===0&&t.entrants?.find(e=>e.isUser)?.status==='active')transition('ADVANCING','Moving to the next tournament table.',true)}if(t.status==='completed'&&t.completedAt!==state.lastComplete){state.lastComplete=t.completedAt;const user=t.entrants?.find(e=>e.isUser);transition(user?.place===1?'YOU WON THE TOURNAMENT':'TOURNAMENT COMPLETE',user?.place===1?'Champion result saved.':`You placed ${user?.place||'-'} • results are ready.`,user?.place===1)}}
function winFx(){const g=game();if(!g?.handOver||g.hand===state.lastWinHand)return;const won=(g.lastPotBreakdown||[]).some(p=>p.type==='pot'&&(p.winnerIndexes||[]).includes(0))||g.lastWinner===0;if(won){state.lastWinHand=g.hand;if(new URLSearchParams(location.search).get('mode')!=='tournament')transition('POT WON','Chips awarded • next hand preparing.')}}
function ensureUi(){if($('#phase405ProfileSheet'))return true;const footer=$('.footer');if(!footer)return false;document.body.insertAdjacentHTML('beforeend',`<section id="phase405ProfileSheet" class="phase405-sheet hide"><div class="phase405-sheet-head"><h2>Player Profile</h2><button data-close405>HIDE</button></div><div class="phase405-profile-card"><div class="phase405-profile-photo">P</div><div class="phase405-profile-data"><strong data-name>Player</strong><span data-rank></span><span data-stack></span><span data-status></span></div></div></section><section id="phase405HandsSheet" class="phase405-sheet hide"><div class="phase405-sheet-head"><h2>Poker Hands</h2><button data-close405>HIDE</button></div><div class="phase405-hands">${HANDS.map(([a,b],i)=>`<article class="phase405-hand"><strong>${i+1}. ${a}</strong><span>${b}</span></article>`).join('')}</div><p class="phase405-note">Your action clock continues while this guide is open.</p></section><section id="phase405GuestSheet" class="phase405-sheet hide"><div class="phase405-sheet-head"><h2>Guest Seats</h2><button data-close405>HIDE</button></div><div class="phase405-guest-grid"><article class="phase405-guest"><strong data-g1>Guest 1</strong><span>LOCAL PLAYER</span></article><article class="phase405-guest" data-g2card><strong data-g2>Guest 2</strong><span data-g2s>OPEN • BOT STANDBY</span></article></div><p class="phase405-note" data-note></p></section><div id="phase405Transition" class="phase405-transition"><strong>SVR POKER</strong><span></span></div>`);document.querySelectorAll('[data-close405]').forEach(b=>b.addEventListener('click',close));const add=(id,label,fn)=>{const b=document.createElement('button');b.id=id;b.type='button';b.className='phase405-footer-button';b.textContent=label;b.onclick=fn;footer.appendChild(b)};add('phase405HandsButton','POKER HANDS',()=>$('#phase405HandsSheet')?.classList.remove('hide'));add('phase405GuestButton','GUESTS',()=>{renderGuests();$('#phase405GuestSheet')?.classList.remove('hide')});const old=$('#phase399HandsButton');if(old)old.style.display='none';document.addEventListener('click',e=>{if(!e.target.closest('.face,.profile-avatar'))return;const box=e.target.closest('.player-box'),index=e.target.closest('#userAvatar,.profile-pill')?0:Number(box?.dataset.player??box?.dataset.seat);if(Number.isFinite(index))openProfile(index)});return true}
function poll(){try{ensureUi();enforceBurn();applyIdentity();renderGuests();tournamentFx();winFx();state.installed=Boolean($('#phase405HandsButton')&&$('#phase405GuestButton')&&state.burnZoneCount===1);state.lastError=null}catch(e){state.lastError=String(e?.message||e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{poll();setInterval(poll,240)},{once:true});else{poll();setInterval(poll,240)}
window.SVR_PHASE405_MOBILE_UI_QA=()=>({build:BUILD,installed:state.installed,oneBurnPile:state.burnZoneCount===1,burnZoneCount:state.burnZoneCount,pokerHandsButton:Boolean($('#phase405HandsButton')),profilePopup:Boolean($('#phase405ProfileSheet')),guestSeats:Boolean($('#phase405GuestSheet')),guestState:guestState(),tournamentTransitions:Boolean($('#phase405Transition')),portrait:Boolean(portrait()),lastError:state.lastError,pass:Boolean(state.installed&&!state.lastError),checkedAt:new Date().toISOString()});window.SVR_PHASE405_OPEN_PROFILE=openProfile;window.SVR_PHASE405_OPEN_HANDS=()=>$('#phase405HandsSheet')?.classList.remove('hide');