import * as THREE from 'three';
const LABEL='PHASE-217-SEATED-TABLE-FIRST-DEMO-LOCK';
const ROOT='PHASE217_SEATED_TABLE_FIRST_DEMO_ROOT';
let scene,camera,renderer,rootGroup,started=false,seated=true;
function sr(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function table(){const r=sr();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function rec(){const t=table();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{obj:t,b,s,c,top:b.max.y};}
function wc(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function pose(x,y,z){const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null;if(renderer?.xr?.isPresenting&&rig?.setPlayerPose)rig.setPlayerPose(x,y,z);else camera.position.set(x,y,z);}
function aimAt(target){if(!camera)return;camera.lookAt(target);}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.08,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.95});}
function box(p,n,pos,s,m){const o=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);o.name=n;o.position.set(pos.x,pos.y,pos.z);o.frustumCulled=false;p.add(o);return o;}
function hideOld(){let h=0;sr()?.traverse?.(o=>{const n=String(o.name||'');if(/PHASE168_DEMO_CARD|PHASE168_.*CHIP|ACTION_LABEL|OPEN_PLAYER_SEAT_LABEL|TABLE_STATUS_FLOATING|PHASE212_STABLE|PHASE214_|PHASE215_HIGH|PHASE215_TABLE_GEOMETRY|PHASE215_PLAYER_CARD|PHASE215_CENTER_CHIPS|PHASE215_INNER_CHIPS/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);h++;}});return h;}
function tex(text,sub=''){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.88)';x.fillRect(0,0,512,160);x.strokeStyle='#7ffcff';x.lineWidth=5;x.strokeRect(8,8,496,144);x.fillStyle='#fff';x.font='900 36px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,58,470);x.fillStyle='#ffd98a';x.font='800 23px system-ui';x.fillText(sub,256,108,470);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function cardTex(r,s){const c=document.createElement('canvas');c.width=256;c.height=360;const x=c.getContext('2d');x.fillStyle='#f7f3e6';x.fillRect(0,0,256,360);x.strokeStyle='#111';x.lineWidth=10;x.strokeRect(10,10,236,340);x.fillStyle=(s==='H'||s==='D')?'#b5142b':'#101015';x.font='900 64px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(r,128,130);x.font='900 72px system-ui';x.fillText({S:'♠',H:'♥',D:'♦',C:'♣'}[s]||s,128,225);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function label(p,n,pos,a,b){const m=new THREE.Mesh(new THREE.PlaneGeometry(1.1,.34),new THREE.MeshBasicMaterial({map:tex(a,b),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name=n;m.position.copy(pos);m.rotation.x=-.22;m.renderOrder=2170;p.add(m);return m;}
function chip(p,n,pos,color,count=5){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,.016,28),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.14}));m.name=`${n}_${i}`;m.position.set(pos.x,pos.y+i*.017,pos.z);m.renderOrder=2171;p.add(m);}}
function card(p,n,pos,r,s){const m=new THREE.Mesh(new THREE.PlaneGeometry(.27,.38),new THREE.MeshBasicMaterial({map:cardTex(r,s),side:THREE.DoubleSide,depthWrite:false}));m.name=n;m.position.copy(pos);m.rotation.x=-Math.PI/2;m.renderOrder=2171;p.add(m);}
function light(p,n,pos,color,intensity,dist=22){const l=new THREE.PointLight(color,intensity,dist,2);l.name=n;l.position.set(pos.x,pos.y,pos.z);p.add(l);return l;}
function buildDemo(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera)return null;const r=sr(),tb=rec();if(!tb)return null;hideOld();const old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;r.add(rootGroup);const c=tb.c,innerW=Math.max(1.4,Math.min(tb.s.x*.52,3.4)),innerD=Math.max(.8,Math.min(tb.s.z*.40,1.7)),cardY=tb.top+.004,chipY=tb.top+.012,labelY=tb.top+.98;const clampX=x=>Math.max(c.x-innerW*.47,Math.min(c.x+innerW*.47,x));const clampZ=z=>Math.max(c.z-innerD*.47,Math.min(c.z+innerD*.47,z));
[['A','S',-.48,0],['K','H',-.24,0],['Q','D',0,0],['J','C',.24,0],['10','S',.48,0]].forEach(([ra,su,x,z],i)=>card(rootGroup,`PHASE217_TABLE_FIRST_COMMUNITY_CARD_${i}`,new THREE.Vector3(clampX(c.x+x),cardY,clampZ(c.z+z)),ra,su));card(rootGroup,'PHASE217_CLOSE_PLAYER_CARD_1',new THREE.Vector3(clampX(c.x-.16),cardY,clampZ(c.z+innerD*.36)),'9','H');card(rootGroup,'PHASE217_CLOSE_PLAYER_CARD_2',new THREE.Vector3(clampX(c.x+.16),cardY,clampZ(c.z+innerD*.36)),'9','C');chip(rootGroup,'PHASE217_CENTER_POT_CHIPS',new THREE.Vector3(c.x,chipY,clampZ(c.z+innerD*.16)),0xffd98a,8);
const seats=[['YOU',0,innerD*.56,0x7ffcff],['NOVA',-innerW*.44,innerD*.34,0xff5b8c],['ROOK',-innerW*.48,-innerD*.08,0xffd98a],['ACE',0,-innerD*.52,0x8eff8e],['VEGA',innerW*.48,-innerD*.08,0xa78bfa],['IVY',innerW*.44,innerD*.34,0xff8bd1]];seats.forEach(([name,x,z,color],i)=>{const px=clampX(c.x+x),pz=clampZ(c.z+z);label(rootGroup,`PHASE217_HIGH_TAG_${name}`,new THREE.Vector3(px,labelY,pz),name,i===0?'SEATED VIEW':'BOT READY');chip(rootGroup,`PHASE217_INSIDE_TABLE_CHIPS_${name}`,new THREE.Vector3(px,chipY,pz),color,4);});label(rootGroup,'PHASE217_TABLE_FIRST_STATUS_TAG',new THREE.Vector3(c.x,labelY+.38,c.z-innerD*.62),'TABLE DEMO','SEATED CLOSE VIEW');
box(rootGroup,'PHASE217_SEAT_VIEW_ANCHOR_MARKER',{x:c.x,y:tb.top+.015,z:c.z+innerD*.7},{x:.35,y:.025,z:.12},basic(0x7ffcff,.55));light(rootGroup,'PHASE217_CLOSE_TABLE_KEY_LIGHT',{x:c.x,y:4.4,z:c.z+1.2},0xffd9aa,1.5,20);light(rootGroup,'PHASE217_CLOSE_TABLE_CYAN_FILL',{x:c.x-2.8,y:3.2,z:c.z-.9},0x7ffcff,.95,18);light(rootGroup,'PHASE217_CLOSE_TABLE_PURPLE_FILL',{x:c.x+2.8,y:3.2,z:c.z-.9},0xb68cff,.85,18);
return{table:tb.obj.name,top:+tb.top.toFixed(3),cardY:+cardY.toFixed(3),chipY:+chipY.toFixed(3),labelY:+labelY.toFixed(3),innerW:+innerW.toFixed(3),innerD:+innerD.toFixed(3)};}
function seatCamera(){const tb=rec();if(!tb||!camera)return null;const c=tb.c,innerD=Math.max(.8,Math.min(tb.s.z*.40,1.7));const eye=new THREE.Vector3(c.x,tb.top+1.18,c.z+innerD*1.42);const target=new THREE.Vector3(c.x,tb.top+.08,c.z-innerD*.04);pose(eye.x,eye.y,eye.z);aimAt(target);return{eye:{x:+eye.x.toFixed(3),y:+eye.y.toFixed(3),z:+eye.z.toFixed(3)},target:{x:+target.x.toFixed(3),y:+target.y.toFixed(3),z:+target.z.toFixed(3)}};}
function hideSky(){scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon|mars|planet|star|sky|sprite|sparkle|blink|pulse/i.test(n)&&!/teleport|portal|watch|hand|table|card|chip/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);}});scene.background=new THREE.Color(0x030407);scene.fog=null;}
function pass(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene)return null;hideOld();hideSky();if(!rootGroup)buildDemo();const cam=seated?seatCamera():null;const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,seatedTableFirst:true,closeTableView:true,scorpionRoomReadyToDuplicate:true,camera:cam,checkedAt:new Date().toISOString()};window.SVR_PHASE217_SEATED_TABLE_FIRST_DEMO_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){buildDemo();window.SVR_RUN_PHASE217_TABLE_FIRST_AUDIT=()=>({lock:pass(),layout:buildDemo()});window.SVR_PHASE217_SEAT_TABLE_VIEW=()=>{seated=true;return pass();};window.SVR_PHASE217_RELEASE_SEAT_VIEW=()=>{seated=false;return pass();};if(!started){started=true;setInterval(pass,1000);}return true;}
[500,1200,2400,4500,8000].forEach(ms=>setTimeout(install,ms));install();
