import * as THREE from 'three';
const LABEL='PHASE-207-LOBBY-RECOVERY-VISUAL-STABILITY-LOCK';
const ROOT='PHASE207_LOBBY_RECOVERY_VISUAL_STABILITY_ROOT';
let scene,rootGroup,started=false;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.78,metalness:.06,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.95});}
function box(parent,name,pos,scale,material){const m=new THREE.Mesh(new THREE.BoxGeometry(scale.x,scale.y,scale.z),material);m.name=name;m.position.set(pos.x,pos.y,pos.z);m.receiveShadow=true;parent.add(m);return m;}
function rebuildShell(){const r=sr(scene);const old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;r.add(rootGroup);const wall=mat(0x0b0f18),gold=mat(0xb88a35),trim=mat(0x111827),glow=basic(0x7ffcff,.36);const minX=-15.5,maxX=15.5,minZ=-12.0,maxZ=11.2;box(rootGroup,'PHASE207_NORTH_CLEAN_WALL',{x:0,y:1.8,z:minZ},{x:31,y:3.6,z:.16},wall);box(rootGroup,'PHASE207_SOUTH_CLEAN_WALL',{x:0,y:1.8,z:maxZ},{x:31,y:3.6,z:.16},wall);box(rootGroup,'PHASE207_WEST_CLEAN_WALL',{x:minX,y:1.8,z:-.4},{x:.16,y:3.6,z:23.2},wall);box(rootGroup,'PHASE207_EAST_CLEAN_WALL',{x:maxX,y:1.8,z:-.4},{x:.16,y:3.6,z:23.2},wall);for(const z of [minZ,maxZ]){box(rootGroup,'PHASE207_GOLD_BASE_TRIM',{x:0,y:.18,z},{x:31.2,y:.12,z:.18},gold);box(rootGroup,'PHASE207_CYAN_TOP_LIGHT',{x:0,y:3.65,z},{x:31.2,y:.08,z:.1},glow);}for(const x of [minX,maxX]){box(rootGroup,'PHASE207_GOLD_SIDE_TRIM',{x,y:.18,z:-.4},{x:.18,y:.12,z:23.2},gold);box(rootGroup,'PHASE207_CYAN_SIDE_LIGHT',{x,y:3.65,z:-.4},{x:.1,y:.08,z:23.2},glow);}for(const x of [-12,12])for(const z of [-9,8.5]){box(rootGroup,'PHASE207_SQUARE_LUXURY_COLUMN',{x,y:1.85,z},{x:.55,y:3.7,z:.55},trim);box(rootGroup,'PHASE207_GOLD_COLUMN_CAP',{x,y:3.72,z},{x:.72,y:.16,z:.72},gold);box(rootGroup,'PHASE207_GOLD_COLUMN_BASE',{x,y:.12,z},{x:.72,y:.18,z:.72},gold);}box(rootGroup,'PHASE207_CEILING_SOFT_CANOPY',{x:0,y:3.92,z:-.3},{x:20,y:.05,z:14},basic(0x7ffcff,.08));return true;}
function suppressOldClutter(){let hidden=0;const r=sr(scene);r?.traverse?.(o=>{const n=String(o.name||'');if(/PHASE191|PHASE192|PHASE197/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);hidden++;}if(/rail|rope|stanchion|banister|handrail|guard|fence/i.test(n)&&!/PHASE195_PORTAL/i.test(n)){const p=new THREE.Vector3();try{o.getWorldPosition(p);if(Math.hypot(p.x,p.z)<14){o.visible=false;o.traverse?.(c=>c.visible=false);hidden++;}}catch(e){}}});return hidden;}
function tableSafe(){const r=sr(scene);const t=r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT');if(t){t.visible=true;t.traverse?.(o=>{o.visible=true;if(o.isMesh)o.frustumCulled=false;});}return !!t;}
function planets(){const moons=[],mars=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon/i.test(n)&&!/mars/i.test(n))moons.push(o);if(/mars/i.test(n))mars.push(o);});const km=moons.find(o=>/PHASE196_ROTATING_MOON/i.test(o.name))||moons[0];const kr=mars.find(o=>/PHASE196_MARS/i.test(o.name))||mars[0];moons.forEach(o=>{const v=o===km||km?.parent===o;o.visible=v;o.traverse?.(c=>c.visible=v);});mars.forEach(o=>{const v=o===kr||kr?.parent===o;o.visible=v;o.traverse?.(c=>c.visible=v);});return {moons:moons.length,mars:mars.length,keptMoon:km?.name||null,keptMars:kr?.name||null};}
function rooms(){let n=0;sr(scene)?.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE195_PORTAL|PHASE195_ROOM/i.test(nm)){o.visible=true;n++;}});return n;}
function pass(){scene=window.__SVR_SCENE__;if(!scene)return null;if(!rootGroup)rebuildShell();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,tableVisible:tableSafe(),hiddenClutter:suppressOldClutter(),planets:planets(),roomPiecesVisible:rooms(),checkedAt:iso()};window.SVR_PHASE207_LOBBY_RECOVERY_VISUAL_STABILITY_LOCK=out;return out;}
function install(){scene=window.__SVR_SCENE__;if(!scene)return false;rebuildShell();pass();window.SVR_RUN_PHASE207_LOBBY_AUDIT=()=>pass();window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(pass,1600);}return true;}
[700,1600,3200,6000,10000,15000].forEach(ms=>setTimeout(install,ms));install();
