/* PHASE-419-TOURNAMENT-REGISTRATION-NOTIFICATION-LOCK */
/* PHASE-423-TOURNAMENT-AUTHENTICATED-REGISTRATION-LOCK */
const BUILD='PHASE-419-TOURNAMENT-REGISTRATION-NOTIFICATION-LOCK',SUCCESSOR='PHASE-423-TOURNAMENT-AUTHENTICATED-REGISTRATION-LOCK';
const SLOT_MS=5*60*60*1000,ANCHOR=Date.UTC(2026,0,1,0,0,0),CAP=100;
const LOCAL_KEY='svr419_tournament_registrations_v1',PLAYER_KEY='svr419_local_player_id',NOTIFY_KEY='svr419_tournament_notify_v1';
const runtime={build:BUILD,successorBuild:SUCCESSOR,installed:false,apiBase:'',sharedBackend:false,backgroundPushLive:false,targetSlot:null,roster:[],registered:false,accountMode:'unknown',notificationPermission:typeof Notification==='undefined'?'unsupported':Notification.permission,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s),now=()=>Date.now(),slotId=t=>Math.floor((t-ANCHOR)/SLOT_MS),slot=id=>({id,start:ANCHOR+id*SLOT_MS,end:ANCHOR+(id+1)*SLOT_MS}),targetSlot=()=>slot(slotId(now())+1),safeName=v=>String(v||'').trim().replace(/\s+/g,' ').slice(0,40),escapeHtml=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])),initials=n=>safeName(n).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'G';
function localPlayerId(){let id='';try{id=localStorage.getItem(PLAYER_KEY)||''}catch{}if(id)return id;id=`local-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;try{localStorage.setItem(PLAYER_KEY,id)}catch{}return id}
function accountIdentity(){try{const a=window.SVR_PLAYER_ACCOUNT?.snapshot?.()||window.SVR_PLAYER_ACCOUNT_STATE||null;runtime.accountMode=String(a?.mode||'unknown');if(a?.profile)return{playerId:String(a.profile.playerId||a.profile.id||localPlayerId()),displayName:safeName(a.profile.displayName||a.profile.name||'Player'),source:a.mode==='api'?'account':'local-account',authenticated:a.mode==='api'}}catch{}try{const p=JSON.parse(localStorage.getItem('svr_phase345_demo_player_v1')||'null');if(p?.playerId)return{playerId:String(p.playerId),displayName:safeName(p.displayName||'Player'),source:'local-account',authenticated:false}}catch{}let guest='Guest 1';try{guest=localStorage.getItem('svr405_guest_name')||guest}catch{}return{playerId:localPlayerId(),displayName:safeName(guest),source:'guest-test',authenticated:false}}
const readLocal=()=>{try{const v=JSON.parse(localStorage.getItem(LOCAL_KEY)||'{}');return v&&typeof v==='object'?v:{}}catch{return{}}},writeLocal=v=>{try{localStorage.setItem(LOCAL_KEY,JSON.stringify(v))}catch{}return v};
function localRoster(id){const all=readLocal(),rows=Array.isArray(all[id])?all[id]:[];return rows.slice().sort((a,b)=>Date.parse(a.registeredAt||0)-Date.parse(b.registeredAt||0))}
function saveLocalRegistration(id,row){const all=readLocal(),rows=Array.isArray(all[id])?all[id]:[],idx=rows.findIndex(x=>String(x.playerId)===String(row.playerId));if(idx>=0)rows[idx]={...rows[idx],...row};else if(rows.length<CAP)rows.push(row);all[id]=rows.slice(0,CAP);writeLocal(all);return localRoster(id)}
async function loadAccount(){try{const m=await import('/site/js/phase345-player-account-client.js?v=phase423');await m.account.bootstrap();runtime.accountMode=m.account.snapshot()?.mode||'unknown'}catch(e){runtime.lastError=`account: ${e.message}`}}
async function loadConfig(){try{const r=await fetch('./config/tournament-api.json?v=phase423',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const c=await r.json();runtime.apiBase=String(window.SVR_TOURNAMENT_API_BASE||c.apiBase||'').replace(/\/$/,'');runtime.sharedBackend=Boolean(runtime.apiBase&&c.sharedRegistrationBackendLive);runtime.backgroundPushLive=Boolean(c.backgroundPushLive)}catch(e){runtime.lastError=`config: ${e.message}`}}
async function remoteRoster(id){if(!runtime.sharedBackend||!runtime.apiBase)return null;const r=await fetch(`${runtime.apiBase}/api/tournaments/${encodeURIComponent(id)}/registrations`,{cache:'no-store',credentials:'include',headers:{Accept:'application/json','X-SVR-Client':SUCCESSOR}}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Object.assign(new Error(d.error||`HTTP ${r.status}`),{status:r.status});return Array.isArray(d.registrations)?d.registrations:[]}
async function remoteRegister(id,row){if(!runtime.sharedBackend||!runtime.apiBase)return null;const r=await fetch(`${runtime.apiBase}/api/tournaments/${encodeURIComponent(id)}/register`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json','X-SVR-Client':SUCCESSOR},body:JSON.stringify({displayName:row.displayName,source:'mobile-play-money-test'})}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Object.assign(new Error(d.error||`HTTP ${r.status}`),{status:r.status});return d}
const fmtDate=t=>{try{return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(t))}catch{return new Date(t).toLocaleString()}},countdown=ms=>{const t=Math.max(0,Math.floor(ms/1000)),h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return`${h}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`};
function setStatus(text,type=''){const e=$('#phase419Status');if(e){e.textContent=text;e.className=`p419-status ${type}`}}
function paintRoster(rows){runtime.roster=rows.slice(0,CAP);const list=$('#phase419Roster'),count=$('#phase419RosterCount'),portal=$('#phase419SignupCount');if(count)count.textContent=`${runtime.roster.length} / ${CAP} SIGNED UP`;if(portal)portal.textContent=`${runtime.roster.length} signed up for next slot`;if(!list)return;if(!runtime.roster.length){list.innerHTML='<div class="p419-empty">No human test players signed up yet. Open seats will still be bot-filled for the prototype.</div>';return}list.innerHTML=runtime.roster.map((r,i)=>`<article class="p419-person"><div class="p419-avatar">${initials(r.displayName)}</div><div><strong>${escapeHtml(r.displayName||`Player ${i+1}`)}</strong><span>${escapeHtml(String(r.source||'test signup').replace(/-/g,' '))}</span></div><span class="p419-time">${escapeHtml(fmtDate(r.registeredAt||Date.now()))}</span></article>`).join('')}
async function refreshRoster(){const t=runtime.targetSlot||targetSlot();let rows=localRoster(t.id);if(runtime.sharedBackend)try{rows=await remoteRoster(t.id);for(const r of rows)saveLocalRegistration(t.id,r)}catch(e){runtime.lastError=`roster: ${e.message}`;setStatus('Shared roster is temporarily unavailable; showing the last roster cached on this device.','warn')}paintRoster(rows);const me=accountIdentity();runtime.registered=rows.some(r=>String(r.playerId)===String(me.playerId));const b=$('#phase419Signup');if(b)b.textContent=runtime.registered?'SIGNED UP':'SIGN UP FOR NEXT TOURNAMENT';return rows}
async function register(){const t=runtime.targetSlot||targetSlot(),me=accountIdentity(),input=$('#phase419DisplayName'),displayName=safeName(input?.value||me.displayName);if(displayName.length<2)return setStatus('Enter a player name with at least 2 characters.','error');const row={playerId:me.playerId,displayName,source:me.source,registeredAt:new Date().toISOString(),slotId:t.id};if(runtime.sharedBackend){if(!me.authenticated){setStatus('Sign in to your verified SVR player account before joining the shared tournament roster.','error');location.href=`/site/tournament-account.html?next=${encodeURIComponent(location.pathname+location.search)}`;return}try{const result=await remoteRegister(t.id,row);Object.assign(row,result?.registration||{}, {source:'shared-registration'});saveLocalRegistration(t.id,row);await refreshRoster();setStatus('Registration saved to the shared tournament roster.','ok')}catch(e){runtime.lastError=`register: ${e.message}`;setStatus(e.status===401?'Your player session expired. Sign in again before registering.':'Shared registration is unavailable. No local-only registration was substituted because the production roster is authoritative.','error')}return}saveLocalRegistration(t.id,row);try{localStorage.setItem('svr405_guest_name',displayName)}catch{}await refreshRoster();setStatus('Registration saved on this device. Shared roster will activate when the tournament API is deployed.','ok')}
const readNotify=()=>{try{return JSON.parse(localStorage.getItem(NOTIFY_KEY)||'{}')}catch{return{}}},writeNotify=v=>{try{localStorage.setItem(NOTIFY_KEY,JSON.stringify(v))}catch{}return v};
async function enableNotification(){if(typeof Notification==='undefined'){setStatus('System notifications are not supported in this browser. The in-app start banner still works.','warn');return false}let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();runtime.notificationPermission=p;if(p!=='granted'){setStatus('Notification permission was not granted. The tournament page will still show the start banner.','warn');return false}const t=runtime.targetSlot||targetSlot(),n=readNotify();Object.assign(n,{slotId:t.id,enabled:true,delivered:false,enabledAt:new Date().toISOString()});writeNotify(n);paintNotifyButton();setStatus(runtime.backgroundPushLive?'Tournament start notification enabled.':'Start notification enabled for this device while the app/browser remains active. Background push still requires the live push backend.','ok');return true}
function paintNotifyButton(){const b=$('#phase419Notify'),n=readNotify(),t=runtime.targetSlot||targetSlot();if(!b)return;const on=Boolean(n.enabled&&Number(n.slotId)===Number(t.id));b.textContent=on?'START ALERT ON':'ENABLE START NOTIFICATION';b.classList.toggle('enabled',on)}
async function fireNotification(t){const n=readNotify();if(!n.enabled||Number(n.slotId)!==Number(t.id)||n.delivered)return false;n.delivered=true;n.deliveredAt=new Date().toISOString();writeNotify(n);try{if(typeof Notification!=='undefined'&&Notification.permission==='granted'){if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification('SVR Poker Tournament Started',{body:'Your play-money tournament test slot has started. Tap to open the tournament lobby.',icon:'/logo.png',badge:'/logo.png',tag:`svr-tournament-${t.id}`,data:{url:'/game/tournaments.html?v=phase420'}})}else new Notification('SVR Poker Tournament Started',{body:'Your play-money tournament test slot has started.',icon:'/logo.png'})}}catch(e){runtime.lastError=`notify: ${e.message}`}const b=$('#phase419StartBanner');if(b){b.classList.add('show');setTimeout(()=>b.classList.remove('show'),7000)}return true}
function updateClock(){const t=runtime.targetSlot||targetSlot(),ms=t.start-now(),c=$('#phase419Countdown'),s=$('#phase419StartTime'),id=$('#phase419SlotId');if(c)c.textContent=ms>0?countdown(ms):'STARTED';if(s)s.textContent=fmtDate(t.start);if(id)id.textContent=`#${t.id}`;if(ms<=0)fireNotification(t);const next=targetSlot();if(next.id!==t.id&&ms<-60000){runtime.targetSlot=next;paintNotifyButton();refreshRoster()}}
function installPage(){const f=$('#phase419Form');if(!f)return false;const me=accountIdentity(),input=$('#phase419DisplayName');if(input&&!input.value)input.value=me.displayName||'Guest 1';f.addEventListener('submit',e=>{e.preventDefault();register()});$('#phase419Notify')?.addEventListener('click',enableNotification);runtime.installed=true;return true}
async function boot(){await Promise.all([loadAccount(),loadConfig()]);runtime.targetSlot=targetSlot();installPage();paintNotifyButton();await refreshRoster();updateClock();setInterval(updateClock,1000);setInterval(refreshRoster,15000);runtime.checkedAt=new Date().toISOString();window.SVR_PHASE419_TOURNAMENT_REGISTRATION_READY=true}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.SVR_PHASE419_TOURNAMENT_REGISTRATION_QA=()=>({build:BUILD,successorBuild:SUCCESSOR,targetSlot:runtime.targetSlot,rosterCount:runtime.roster.length,registered:runtime.registered,accountMode:runtime.accountMode,apiBaseConfigured:Boolean(runtime.apiBase),sharedBackend:runtime.sharedBackend,authenticatedRemoteRegistration:true,credentialsIncluded:true,backgroundPushLive:runtime.backgroundPushLive,notificationPermission:runtime.notificationPermission,localFallback:!runtime.sharedBackend,scheduleEveryHours:5,registrationCap:CAP,lastError:runtime.lastError,pass:Boolean(runtime.targetSlot&&CAP===100&&SLOT_MS===18000000),checkedAt:new Date().toISOString()});
