import{settlePots,handName,best7}from'./phase336_poker_evaluator.js';
export const BUILD='PHASE-336-AUTHORITATIVE-POKER-RULES-POT-SETTLEMENT-LOCK';
const SAVE='SVR_PHASE336_POKER_SNAPSHOT_V1',SUITS=['S','H','D','C'],RANKS=['2','3','4','5','6','7','8','9','T','J','Q','K','A'],V=Object.fromEntries(RANKS.map((r,i)=>[r,i+2]));
export const players=['YOU','NOVA','ROOK','ACE','VEGA','IVY'].map((name,id)=>({id,name,human:id===0,stack:1000,folded:false,allIn:false,bet:0,contributed:0,acted:false,raiseClosed:false,hand:[],lastAction:'Ready'}));
export const state={build:BUILD,handNo:0,dealer:-1,smallBlind:10,bigBlind:20,phase:'idle',deck:[],burn:[],community:[],pot:0,pots:[],currentBet:0,minRaise:20,lastAggressor:null,current:0,waitingHuman:false,winner:null,winners:[],actionLog:[],actionSeq:0,settledPot:0,lastAction:'Ready',restored:false};
let timer=null,physical={amount:0,at:0};
const card=(r,s)=>({r,s,v:V[r],id:r+s});
function deck(){const d=[];for(const s of SUITS)for(const r of RANKS)d.push(card(r,s));for(let i=d.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
const funded=()=>players.filter(p=>p.stack>0),live=()=>players.filter(p=>!p.folded&&p.hand.length===2),actors=()=>live().filter(p=>!p.allIn&&p.stack>0);
function next(from,pred=()=>true){for(let n=1;n<=players.length;n++){const i=(from+n+players.length)%players.length;if(pred(players[i]))return i}return-1}
const nextFunded=i=>next(i,p=>p.stack>0),nextActor=i=>next(i,p=>!p.folded&&!p.allIn&&p.stack>0&&(!p.acted||p.bet<state.currentBet));
const total=()=>players.reduce((s,p)=>s+p.contributed,0);function log(x){state.lastAction=x;state.actionLog.unshift(x);state.actionLog=state.actionLog.slice(0,12);state.actionSeq++}
function save(){try{localStorage.setItem(SAVE,JSON.stringify({build:BUILD,savedAt:Date.now(),state,players}))}catch{}}
function emit(){state.pot=total();window.SVR_PHASE85_POKER_STATE=state;window.SVR_PHASE336_POKER_STATE=state;window.dispatchEvent(new CustomEvent('svr:poker-state',{detail:audit()}));window.dispatchEvent(new CustomEvent('svr:turn-changed',{detail:{build:BUILD,handNo:state.handNo,phase:state.phase,current:players[state.current]?.name||null,waitingHuman:state.waitingHuman,currentBet:state.currentBet,pot:state.pot}}));save()}
function commit(p,a){const n=Math.max(0,Math.min(p.stack,Math.floor(Number(a)||0)));p.stack-=n;p.bet+=n;p.contributed+=n;if(p.stack===0)p.allIn=true;state.pot=total();return n}
function resetHand(p){p.folded=p.stack<=0;p.allIn=false;p.bet=0;p.contributed=0;p.acted=false;p.raiseClosed=false;p.hand=[];p.lastAction=p.stack>0?'Ready':'Out'}
function take(){return state.deck.pop()||null}function burn(){const c=take();if(c)state.burn.push(c)}function street(name){if(name==='flop'){burn();state.community.push(take(),take(),take())}else{burn();state.community.push(take())}state.community=state.community.filter(Boolean)}
function roundReset(){for(const p of players){p.bet=0;p.acted=p.folded||p.allIn||p.stack<=0;p.raiseClosed=false}state.currentBet=0;state.minRaise=state.bigBlind;state.lastAggressor=null}
function post(p,a,label){const n=commit(p,a);p.lastAction=`${label} ${n}`;log(`${p.name} posts ${label} ${n}`);return n}
export function startHand(){clearTimeout(timer);if(funded().length<2){state.phase='idle';state.waitingHuman=false;log('Table requires two funded players');emit();return false}state.handNo++;state.dealer=nextFunded(state.dealer);Object.assign(state,{phase:'preflop',deck:deck(),burn:[],community:[],pots:[],currentBet:0,minRaise:state.bigBlind,lastAggressor:null,waitingHuman:false,winner:null,winners:[],actionLog:[],settledPot:0});players.forEach(resetHand);const active=funded();for(let r=0;r<2;r++)for(let o=1;o<=players.length;o++){const p=players[(state.dealer+o)%players.length];if(active.includes(p))p.hand.push(take())}
 let sb,bb;if(active.length===2){sb=state.dealer;bb=nextFunded(sb)}else{sb=nextFunded(state.dealer);bb=nextFunded(sb)}post(players[sb],state.smallBlind,'SB');post(players[bb],state.bigBlind,'BB');state.currentBet=Math.max(players[sb].bet,players[bb].bet);state.lastAggressor=bb;active.forEach(p=>p.acted=p.allIn);state.current=active.length===2?sb:nextActor(bb);log(`Hand ${state.handNo} — dealer ${players[state.dealer].name}`);emit();step();return true}
const roundDone=()=>actors().every(p=>p.acted&&p.bet===state.currentBet);function runout(){while(state.community.length<5){if(!state.community.length){state.phase='flop';street('flop')}else if(state.community.length===3){state.phase='turn';street('turn')}else if(state.community.length===4){state.phase='river';street('river')}else break}showdown()}
function advanceStreet(){if(live().length<=1)return uncontested();if(!actors().length)return runout();if(state.phase==='preflop')state.phase='flop';else if(state.phase==='flop')state.phase='turn';else if(state.phase==='turn')state.phase='river';else return showdown();roundReset();street(state.phase);log(`${state.phase.toUpperCase()} dealt`);state.current=nextActor(state.dealer);emit();if(state.current<0)return runout();step()}
function after(){if(live().length<=1)return uncontested();if(roundDone())return advanceStreet();const n=nextActor(state.current);if(n<0)return advanceStreet();state.current=n;emit();step()}
export function legal(p=players[state.current]){if(!p||p.folded||p.allIn||p.stack<=0)return[];const need=Math.max(0,state.currentBet-p.bet),a=['fold',need?'call':'check'];if(p.stack>need&&!p.raiseClosed)a.push(state.currentBet?'raise':'bet');a.push('allin');return a}
function raise(p,target,source='raise'){const old=state.currentBet,max=p.bet+p.stack,min=old?old+state.minRaise:Math.max(state.bigBlind,state.minRaise),previouslyActed=actors().filter(x=>x.id!==p.id&&x.acted);let desired=Math.min(max,Math.max(p.bet,Math.floor(Number(target)||0)));if(desired<=old){const paid=commit(p,old-p.bet);p.acted=true;p.lastAction=`Call ${paid}`;log(`${p.name} calls ${paid}`);return}if(desired<min&&desired!==max)desired=Math.min(min,max);const before=p.bet;commit(p,desired-p.bet);const size=p.bet-old,full=p.bet>old&&size>=state.minRaise;if(p.bet>old){state.currentBet=p.bet;state.lastAggressor=p.id;if(full){state.minRaise=size;actors().forEach(x=>{x.acted=x.id===p.id;x.raiseClosed=false})}else if(p.allIn){previouslyActed.forEach(x=>x.raiseClosed=true)}}p.acted=true;const word=p.allIn?'all in':old?'raises to':'bets';p.lastAction=`${word} ${p.bet}`;log(`${p.name} ${word} ${p.bet}${source==='physical'?' (physical chips)':''}`);if(!full&&p.bet>old&&p.allIn)log(`Short all-in raise ${size}; betting not reopened`);if(before===p.bet)log(`${p.name} moved no chips`)}
function normalize(input,p){let a=typeof input==='string'?{type:input}:{...(input||{})};a.type=String(a.type||'').toLowerCase();if(a.type==='checkcall')a.type=p.bet<state.currentBet?'call':'check';if(performance.now()-physical.at<1800&&physical.amount>0&&['call','raise','physical-bet'].includes(a.type)){a={type:'physical-bet',amount:physical.amount};physical={amount:0,at:0}}return a}
function apply(p,input){const a=normalize(input,p),need=Math.max(0,state.currentBet-p.bet);if(a.type==='next')return['showdown','idle'].includes(state.phase)?startHand():false;if(!legal(p).includes(a.type)&&!['physical-bet','bet'].includes(a.type))return false;if(a.type==='fold'){p.folded=true;p.acted=true;p.lastAction='Fold';log(`${p.name} folds`)}else if(a.type==='check'){if(need)return apply(p,'call');p.acted=true;p.lastAction='Check';log(`${p.name} checks`)}else if(a.type==='call'){const paid=commit(p,need);p.acted=true;p.lastAction=p.allIn&&paid<need?`All-in ${p.bet}`:`Call ${paid}`;log(`${p.name} ${p.allIn&&paid<need?'is all in for':'calls'} ${paid}`)}else if(a.type==='allin')raise(p,p.bet+p.stack,'allin');else if(a.type==='physical-bet'){let amount=Math.max(0,Math.floor(Number(a.amount)||0));if(amount<need&&p.stack>amount){log(`Physical bet auto-completed ${amount} to call ${need}`);amount=need}const target=p.bet+Math.min(p.stack,amount);if(target<=state.currentBet){const paid=commit(p,need);p.acted=true;p.lastAction=`Call ${paid}`;log(`${p.name} calls ${paid} with physical chips`)}else raise(p,target,'physical')}else{const explicit=Number(a.raiseTo??a.target??0),by=Number(a.amount??0),fallback=state.currentBet?state.currentBet+Math.max(state.minRaise,state.bigBlind):Math.max(state.bigBlind,state.minRaise);raise(p,explicit>0?explicit:by>0?p.bet+by:fallback)}state.waitingHuman=false;emit();after();return true}
export function action(input){if(['showdown','idle'].includes(state.phase)){if((typeof input==='string'?input:input?.type)==='next')return startHand();return false}const p=players[state.current];if(!p?.human)return false;return apply(p,input)}
function strength(p){if(state.community.length<3){const[a,b]=p.hand;let s=(a.v+b.v)/28;if(a.r===b.r)s+=.3+a.v/45;if(a.s===b.s)s+=.08;if(Math.abs(a.v-b.v)<=2)s+=.06;return Math.min(1,s)}const r=best7([...p.hand,...state.community]);return Math.min(1,r[0]/8*.72+(r[1]||0)/14*.28)}
function bot(p){const need=Math.max(0,state.currentBet-p.bet),odds=need/Math.max(1,state.pot+need),s=strength(p),pressure=need/Math.max(1,p.stack+need),pos=((p.id-state.dealer+players.length)%players.length)/players.length,agg=s+pos*.08+(Math.random()-.5)*.14;if(need&&s+.08<odds&&pressure>.12)return'fold';if(p.stack<=need)return'call';if(agg>.78)return{type:'raise',raiseTo:Math.min(p.bet+p.stack,state.currentBet+Math.max(state.minRaise,Math.round(state.pot*.55),state.bigBlind))};if(!need&&agg>.62)return{type:'bet',raiseTo:Math.min(p.bet+p.stack,Math.max(state.bigBlind,Math.round(state.pot*.42)))};return need?'call':'check'}
function step(){clearTimeout(timer);if(['showdown','idle'].includes(state.phase))return;if(live().length<=1)return uncontested();if(roundDone())return advanceStreet();const p=players[state.current];if(!p||p.folded||p.allIn||p.stack<=0||(p.acted&&p.bet===state.currentBet)){const n=nextActor(state.current);if(n<0)return advanceStreet();state.current=n;return step()}if(p.human){state.waitingHuman=true;log('Your turn');emit();return}state.waitingHuman=false;emit();timer=setTimeout(()=>{if(players[state.current]===p&&state.phase!=='showdown')apply(p,bot(p))},700+Math.random()*750)}
function showdown(){clearTimeout(timer);state.phase='showdown';state.waitingHuman=false;while(state.community.length<5&&live().length>1){if(!state.community.length)street('flop');else if(state.community.length===3)street('turn');else if(state.community.length===4)street('river');else break}const result=settlePots(players,state.community,state.dealer),settledTotal=total();for(const[id,amount]of result.payouts)players[id].stack+=amount;state.pots=result.pots;state.settledPot=settledTotal;state.winners=[...result.payouts].map(([id,amount])=>({id,name:players[id].name,amount,score:result.scores.get(id),label:handName(result.scores.get(id))})).sort((a,b)=>b.amount-a.amount);const w=state.winners[0];state.winner=w?{name:w.name,pot:w.amount,label:w.label,score:w.score}:null;log(state.winners.map(x=>`${x.name} wins ${x.amount} with ${x.label}`).join(' • ')||'No eligible winner');emit()}
function uncontested(){clearTimeout(timer);const w=live()[0],total=players.reduce((s,p)=>s+p.contributed,0);if(w)w.stack+=total;state.phase='showdown';state.waitingHuman=false;state.settledPot=total;state.pots=[{amount:total,eligible:w?[w.id]:[],winners:w?[w.id]:[],hand:'Uncontested'}];state.winners=w?[{id:w.id,name:w.name,amount:total,score:[0],label:'Uncontested'}]:[];state.winner=w?{name:w.name,pot:total,label:'Uncontested',score:[0]}:null;log(w?`${w.name} wins ${total} uncontested`:'No winner');emit()}
export function audit(){return{build:BUILD,active:true,authoritative:true,handNo:state.handNo,phase:state.phase,pot:state.pot,pots:state.pots,current:players[state.current]?.name||null,currentBet:state.currentBet,minRaise:state.minRaise,community:state.community.map(c=>c.id),burnCount:state.burn.length,legalActions:legal(),players:players.map(p=>({id:p.id,name:p.name,human:p.human,stack:p.stack,bet:p.bet,contributed:p.contributed,folded:p.folded,allIn:p.allIn,acted:p.acted,raiseClosed:p.raiseClosed,hand:p.human||state.phase==='showdown'?p.hand.map(c=>c.id):['??','??'],lastAction:p.lastAction})),winner:state.winner,winners:state.winners,restored:state.restored,checkedAt:new Date().toISOString()}}
function restore(){try{const x=JSON.parse(localStorage.getItem(SAVE)||'null');if(!x||x.build!==BUILD||Date.now()-x.savedAt>1800000)return false;Object.assign(state,x.state,{build:BUILD,restored:true});x.players.forEach(s=>Object.assign(players[s.id],s));log('Recovered interrupted hand');return true}catch{return false}}
export function resetTable(stack=1000){clearTimeout(timer);players.forEach(p=>p.stack=Math.max(0,Number(stack)||1000));state.dealer=-1;state.handNo=0;try{localStorage.removeItem(SAVE)}catch{}return startHand()}
export function boot(){window.SVR_POKER_ACTION=action;window.SVR_POKER_NEXT_HAND=startHand;window.SVR_POKER_RAISE_TO=n=>action({type:'raise',raiseTo:n});window.SVR_POKER_COMMIT_PHYSICAL_BET=n=>action({type:'physical-bet',amount:n});window.SVR_POKER_LEGAL_ACTIONS=()=>legal().slice();window.SVR_RUN_PHASE85_POKER_AUDIT=audit;window.SVR_RUN_PHASE336_POKER_AUDIT=audit;window.SVR_RESET_POKER_TABLE=resetTable;window.SVR_PHASE85_POKER_STATE=state;window.SVR_PHASE336_POKER_STATE=state;window.addEventListener('svr:physical-bet-committed',e=>{const n=Number(e.detail?.total??e.detail?.value??0);if(n>0)physical={amount:n,at:performance.now()}});document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='f')action('fold');if(k==='c')action('call');if(k==='k')action('check');if(k==='r')action('raise');if(k==='a')action('allin');if(k==='h')startHand()});if(restore()){emit();step()}else startHand();return state}
