import * as THREE from 'three';
const LABEL='PHASE-221-SINGLE-TABLE-CONTROL-AUTHORITY-LOCK';
const ROOT='PHASE221_SINGLE_TABLE_CONTROL_AUTHORITY_ROOT';
let scene,camera,renderer,rootGroup,started=false,seatApplied=false,menuOpen=false,lastMenu=false,offset={forward:0,height:0};
function sr(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function vc(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function cp(){const p=new THREE.Vector3();vc()?.getWorldPosition(p);return p;}
function cd(){const d=new THREE.Vector3();vc()?.getWorldDirection(d);d.y=0;if(d.lengthSq()<.001)d.set(0,0,-1);return d.normalize();}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null;}
function table(){const r=sr();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function tr(){const t=table();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{obj:t,b,s,c,top:b.max.y,innerW:Math.max(1.4,Math.min(s.x*.52,3.4)),innerD:Math.max(.8,Math.min(s.z*.40,1.7))};}
function killTravel(){let n=0;try{window.SVR_PHASE193_TELEPORT_OFF?.();window.SVR_PHASE170_TELEPORT_OFF?.();window.SVR_PHASE184_TELEPORT_OFF?.();}catch(e){}const r=rig();if(r){try{r.setEnabled?.(false);r.setMode?.('off');r.setVisible?.(false);r.move=()=>{};}catch(e){}}scene?.traverse?.(o=>{const name=String(o.name||'');if(/teleport|laser|pointer|ray|arc|target_ring|logo_target|PHASE193|PHASE170|PHASE184/i.test(name)&&!/watch|table|card|chip|portal/i.test(name)){o.visible=false;if(o.material){o.material.opacity=0;o.material.transparent=true;}n++;}});window.SVR_TABLE_TELEPORT_RULE='OFF_WHILE_SEATED';return n;}
function tex(a,b=''){const c=document.createElement('canvas');c.width=768;c.height=192;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.78)';x.fillRect(0,0,768,192);x.strokeStyle='#7ffcff';x.lineWidth=6;x.strokeRect(8,8,752,176);x.fillStyle='#fff';x.font='900 42px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(a,384,68,720);x.fillStyle='#ffd98a';x.font='800 26px system-ui';x.fillText(b,384,124,720);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function smallTex(s){const c=document.createElement('canvas');c.width=512;c.height=96;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.72)';x.fillRect(0,0,512,96);x.strokeStyle='#ffd98a';x.lineWidth=4;x.strokeRect(6,6,500,84);x.fillStyle='#fff';x.font='800 23px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(s,256,50,480);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function hideConflicts(){let h=0;sr()?.traverse?.(o=>{const n=String(o.name||'');if(/PHASE217_SEATED_TABLE_FIRST_DEMO_ROOT|PHASE218_TABLE_PLAY_MODE_WATCH_ROOT|PHASE219_TABLE_POSITION_OPTIONS_CONTROL_ROOT|PHASE220_STATIC_TABLE_HUD_NO_BOUNCE_ROOT|PHASE218_TABLE_PLAY_PANEL|PHASE219_SMALL_POSITION_DISPLAY|PHASE219_OPTIONS_PANEL|PHASE220_STATIC_TABLE_MODE_HUD|PHASE220_STATIC_POSITION_READOUT/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);h++;}});return h;}
function buildHud(){const rec=tr();if(!rec||!camera)return null;const old=sr().getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;sr().add(rootGroup);
const c=rec.c;
const tablePanel=new THREE.Mesh(new THREE.PlaneGeometry(1.2,.3),new THREE.MeshBasicMaterial({map:tex('TABLE CONTROL','teleport off • menu button adjusts'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));tablePanel.name='PHASE221_TABLE_ANCHORED_CONTROL_PANEL';tablePanel.position.set(c.x,rec.top+1.55,c.z-rec.innerD*.82);tablePanel.rotation.x=-.25;tablePanel.renderOrder=2210;rootGroup.add(tablePanel);
const hud=new THREE.Mesh(new THREE.PlaneGeometry(.62,.12),new THREE.MeshBasicMaterial({map:smallTex('POS READY'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));hud.name='PHASE221_CAMERA_ATTACHED_POSITION_HUD';hud.position.set(-.38,-.28,-1.05);hud.renderOrder=2211;camera.add(hud);
const menu=new THREE.Mesh(new THREE.PlaneGeometry(.95,.34),new THREE.MeshBasicMaterial({map:tex('OPTIONS CLOSED','press menu / hamburger'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));menu.name='PHASE221_CAMERA_ATTACHED_OPTIONS_PANEL';menu.position.set(.05,-.48,-1.08);menu.visible=false;menu.renderOrder=2212;camera.add(menu);
return true;}
function updateHud(){if(!camera)return;const p=cp();const hud=camera.getObjectByName?.('PHASE221_CAMERA_ATTACHED_POSITION_HUD');if(hud?.material){hud.material.map=smallTex(`X ${p.x.toFixed(2)} Y ${p.y.toFixed(2)} Z ${p.z.toFixed(2)}  F ${offset.forward.toFixed(2)} H ${offset.height.toFixed(2)}`);hud.material.needsUpdate=true;}const panel=camera.getObjectByName?.('PHASE221_CAMERA_ATTACHED_OPTIONS_PANEL');if(panel){panel.visible=menuOpen;if(panel.material){panel.material.map=tex(menuOpen?'OPTIONS OPEN':'OPTIONS CLOSED','stick: forward/back height | menu closes');panel.material.needsUpdate=true;}}}
function input(){const pads=navigator.getGamepads?navigator.getGamepads():[];let menu=false,ax=0,ay=0;for(const g of pads){if(!g)continue;const b=g.buttons||[];if(b[4]?.pressed||b[5]?.pressed||b[8]?.pressed||b[9]?.pressed)menu=true;const a=g.axes||[];if(Math.abs(a[0]||0)>Math.abs(ax))ax=a[0]||0;if(Math.abs(a[1]||0)>Math.abs(ay))ay=a[1]||0;}const hand=window.SVR_HAND_INPUT||window.SVR_PHASE170_HAND_INPUT||window.SVR_ACTIVE_HAND_INPUT||{};if(hand.leftPinch||hand.leftMenu||hand.menu||hand.hamburger)menu=true;return{menu,ax,ay};}
function control(){const i=input();if(i.menu&&!lastMenu)menuOpen=!menuOpen;lastMenu=i.menu;if(menuOpen){if(i.ay<-.55)offset.forward=Math.min(.42,offset.forward+.01);if(i.ay>.55)offset.forward=Math.max(-.32,offset.forward-.01);if(i.ax>.55)offset.height=Math.min(.3,offset.height+.008);if(i.ax<-.55)offset.height=Math.max(-.22,offset.height-.008);}}
function seatOnceOrAdjust(){const rec=tr();if(!rec||!camera)return null;const eye=new THREE.Vector3(rec.c.x,rec.top+1.08+offset.height,rec.c.z+rec.innerD*(1.26-offset.forward));const target=new THREE.Vector3(rec.c.x,rec.top+.02,rec.c.z-rec.innerD*.04);const r=rig();if(renderer?.xr?.isPresenting&&r?.setPlayerPose){if(!seatApplied){r.setPlayerPose(eye.x,0,eye.z);seatApplied=true;}}else{camera.position.copy(eye);camera.lookAt(target);seatApplied=true;}return{eye:{x:+eye.x.toFixed(2),y:+eye.y.toFixed(2),z:+eye.z.toFixed(2)},target:{x:+target.x.toFixed(2),y:+target.y.toFixed(2),z:+target.z.toFixed(2)}};}
function pass(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera)return null;const hidden=hideConflicts();const travel=killTravel();if(!rootGroup)buildHud();control();const seat=seatOnceOrAdjust();updateHud();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,singleSeatAuthority:true,noBlinkSeat:true,teleportOff:true,positionHud:true,menuOpen,offset,hiddenConflicts:hidden,hiddenTravel:travel,seat,checkedAt:new Date().toISOString()};window.SVR_PHASE221_SINGLE_TABLE_CONTROL_AUTHORITY_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){const out=pass();window.SVR_RUN_PHASE221_TABLE_CONTROL_AUDIT=()=>pass();window.SVR_PHASE221_OPTIONS_OPEN=()=>{menuOpen=true;return pass();};window.SVR_PHASE221_OPTIONS_CLOSE=()=>{menuOpen=false;return pass();};window.SVR_PHASE221_NUDGE_FORWARD=()=>{offset.forward=Math.min(.42,offset.forward+.05);seatApplied=false;return pass();};window.SVR_PHASE221_NUDGE_BACK=()=>{offset.forward=Math.max(-.32,offset.forward-.05);seatApplied=false;return pass();};window.SVR_PHASE221_NUDGE_UP=()=>{offset.height=Math.min(.3,offset.height+.04);seatApplied=false;return pass();};window.SVR_PHASE221_NUDGE_DOWN=()=>{offset.height=Math.max(-.22,offset.height-.04);seatApplied=false;return pass();};if(!started){started=true;setInterval(pass,350);}return !!out;}
[300,800,1600,3200,6000].forEach(ms=>setTimeout(install,ms));install();
