/* PHASE-420-MOBILE-RELEASE-TRUTH-LOCK */
const BUILD='PHASE-420-MOBILE-RELEASE-TRUTH-LOCK';
const SLOT_MS=5*60*60*1000;
const ANCHOR=Date.UTC(2026,0,1,0,0,0);
const state={build:BUILD,installed:false,platform:'mobile',accountMode:'loading',accountReady:false,productionAuthLive:false,currentSlotId:null,nextSlotId:null,navigationNormalized:0,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s);
const slotId=t=>Math.floor((t-ANCHOR)/SLOT_MS);
function platform(){const ua=navigator.userAgent||'',ipad=navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;if(/iPhone|iPad|iPod/i.test(ua)||ipad)return'ios';if(/Android/i.test(ua))return'android';return'mobile'}
function accountSnapshot(){try{return window.SVR_PLAYER_ACCOUNT?.snapshot?.()||window.SVR_PLAYER_ACCOUNT_STATE||window.SVR_PHASE345_ACCOUNT_QA?.()?.account||null}catch{return null}}
function phaseNumber(value){const match=String(value||'').match(/phase(?:-|_)?(\d+)/i);return match?Number(match[1]):0}
function setMinimumVersion(url,min=420){try{const u=new URL(url,location.href),current=phaseNumber(u.searchParams.get('v'));if(current<min)u.searchParams.set('v',`phase${min}`);return `${u.pathname}${u.search}${u.hash}`}catch{return url}}
function normalizeNavigation(){let changed=0;document.querySelectorAll('a[href*="/game/tournaments.html"],a[href*="/game/tournament-signup.html"],a[href*="/game/android.html"],a[href*="/game/iphone.html"]').forEach(link=>{const next=setMinimumVersion(link.getAttribute('href')||link.href,420);if(next&&next!==link.getAttribute('href')){link.setAttribute('href',next);changed++}});state.navigationNormalized+=changed;return changed}
function paintBuild(){document.body.dataset.mobileReleaseBuild=BUILD;document.documentElement.dataset.svrMobileRelease='phase420';const badge=$('.platform-badge');if(badge&&!/PHASE 420/.test(badge.textContent||''))badge.textContent='MOBILE • PHASE 420 RELEASE';const brand=$('.brand-pill span');if(brand)brand.textContent='MOBILE TABLE • P420'}
function paintAccount(){const snap=accountSnapshot(),profile=snap?.profile||null;state.accountReady=Boolean(snap?.ready||profile);state.accountMode=snap?.mode||'loading';state.productionAuthLive=Boolean(snap?.apiConfigured&&snap?.apiHealthy&&snap?.mode==='api');const button=$('#phase407LoginButton');if(button){button.dataset.phase420Auth=state.productionAuthLive?'production':profile?'local-test':'not-live';if(profile&&button.textContent&&!/ACCOUNT/.test(button.textContent))button.textContent=`ACCOUNT • ${(profile.displayName||profile.name||'PLAYER').toUpperCase()}`;if(!profile&&!state.productionAuthLive&&/SIGN IN$/.test(button.textContent||''))button.textContent='SIGN IN • LOCAL TEST'}}
function paintTournamentTruth(){const current=slotId(Date.now());state.currentSlotId=current;state.nextSlotId=current+1;document.body.dataset.currentTournamentSlot=String(current);document.body.dataset.nextTournamentSlot=String(current+1)}
function sweep(reason='manual'){try{state.platform=platform();paintBuild();paintAccount();paintTournamentTruth();normalizeNavigation();state.installed=true;state.lastError=null;state.checkedAt=new Date().toISOString();window.SVR_PHASE420_MOBILE_RELEASE_STATE={...state,reason};return window.SVR_PHASE420_MOBILE_RELEASE_STATE}catch(error){state.lastError=String(error?.message||error);state.checkedAt=new Date().toISOString();return{...state,reason}}}
function boot(){sweep('boot');window.addEventListener('svr:account-ready',()=>sweep('account-ready'));window.addEventListener('svr:account-change',()=>sweep('account-change'));window.addEventListener('pageshow',()=>sweep('pageshow'));setTimeout(()=>sweep('settle-1'),650);setTimeout(()=>sweep('settle-2'),2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.SVR_PHASE420_MOBILE_RELEASE_SWEEP=sweep;
window.SVR_PHASE420_MOBILE_RELEASE_QA=()=>({build:BUILD,...state,exactFiveHourSlots:SLOT_MS===18000000,sharedPokerEngine:Boolean(window.SVR_PHASE403_ANDROID_ENGINE_QA),humanTurnAuthority:Boolean(window.SVR_PHASE414_HUMAN_TURN_QA),humanSeatGuard:Boolean(window.SVR_PHASE416_HUMAN_SEAT_QA),loginSourceReady:Boolean(window.SVR_PLAYER_ACCOUNT_STATE||window.SVR_PHASE345_ACCOUNT_QA),productionAuthTruthful:state.productionAuthLive||state.accountMode!=='api',pass:Boolean(state.installed&&SLOT_MS===18000000&&!state.lastError),checkedAt:new Date().toISOString()});
