import * as THREE from 'three';
const BUILD='PHASE-95-ANDROID-LOBBY-BEAUTY-PREVIEW-UPGRADE';
let scene,camera,root,group,stars,ready=false;
const qs=new URLSearchParams(location.search);
const mobile=/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent||'');
const run=mobile||qs.has('preview')||qs.has('beauty')||String(location.search).includes('phase95')||String(location.search).includes('phase96');
function S(){return window.__SVR_SCENE__||window.scene||null}
function C(){return window.__SVR_CAMERA__||window.camera||null}
function Root(){const s=S();return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s}
function std(c,e=0){return new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:e,roughness:.62,metalness:.08,side:THREE.DoubleSide})}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>=1})}
function add(o){group.add(o);return o}
function box(n,x,y,z,w,h,d,c,e=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),std(c,e));m.name=n;m.position.set(x,y,z);return add(m)}
function glow(n,x,y,z,w,h,d,c,o=.28){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),basic(c,o));m.name=n;m.position.set(x,y,z);return add(m)}
function tex(text,color='#bd00ff'){const can=document.createElement('canvas');can.width=512;can.height=160;const g=can.getContext('2d');const gr=g.createLinearGradient(0,0,512,160);gr.addColorStop(0,'rgba(15,0,35,.9)');gr.addColorStop(1,'rgba(0,26,36,.9)');g.fillStyle=gr;g.fillRect(0,0,512,160);g.strokeStyle=color;g.lineWidth=7;g.strokeRect(8,8,496,144);g.shadowColor=color;g.shadowBlur=14;g.fillStyle='#fff';g.font='900 33px system-ui';g.textAlign='center';g.textBaseline='middle';String(text).split('\n').forEach((line,i,a)=>g.fillText(line,256,80+(i-(a.length-1)/2)*42,470));const t=new THREE.CanvasTexture(can);t.colorSpace=THREE.SRGBColorSpace;return t}
function sign(n,text,x,z,color){const p=new THREE.Mesh(new THREE.PlaneGeometry(1.55,.5),new THREE.MeshBasicMaterial({map:tex(text,color),transparent:true,side:THREE.DoubleSide,depthWrite:false}));p.name=n;p.position.set(x,1.65,z);p.rotation.y=Math.atan2(x,z);add(p);glow(n+'_GLOW',x,1.35,z,.12,1.25,1.5,Number('0x'+color.slice(1)),.2)}
function tableCenter(){let best=null;Root()?.traverse?.(o=>{const n=String(o.name||'').toLowerCase();if(!best&&n.includes('table'))best=o});if(best){try{best.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(best),c=new THREE.Vector3();b.getCenter(c);return{x:c.x,y:b.max.y+.045,z:c.z}}catch(e){}}return{x:0,y:.9,z:0}}
function logoTexture(){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d');g.fillStyle='#030307';g.fillRect(0,0,512,512);const gr=g.createRadialGradient(256,256,10,256,256,245);gr.addColorStop(0,'#7ffcff');gr.addColorStop(.42,'#bd00ff');gr.addColorStop(1,'#080014');g.fillStyle=gr;g.beginPath();g.arc(256,256,238,0,Math.PI*2);g.fill();g.strokeStyle='#ffd98a';g.lineWidth=18;g.stroke();g.fillStyle='#fff';g.font='900 92px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText('SVR',256,222);g.font='900 48px system-ui';g.fillText('POKER',256,310);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function build(){if(group)group.parent?.remove(group);group=new THREE.Group();group.name='PHASE95_ANDROID_BEAUTY_PREVIEW_ROOT';Root().add(group);scene.fog=new THREE.FogExp2(0x060013,.045);scene.background=new THREE.Color(0x03010a);scene.add(new THREE.AmbientLight(0x6b4cff,.22));const key=new THREE.PointLight(0xffd08a,1.4,12,2);key.position.set(0,4,2);scene.add(key);const cyan=new THREE.PointLight(0x7ffcff,.9,9,2);cyan.position.set(-3,2.3,-2.6);scene.add(cyan);const purple=new THREE.PointLight(0xbd00ff,.9,9,2);purple.position.set(3,2.3,2.5);scene.add(purple);box('PHASE95_PREVIEW_RUNWAY',0,.012,0,2.2,.025,6.5,0x210027,.12);glow('PHASE95_RUNWAY_GLOW',0,.03,0,2.34,.025,6.65,0xbd00ff,.18);sign('PHASE95_REIKI_SIGN','REIKI HUB\nPREVIEW',-3.15,-2.75,'#ff4fd8');sign('PHASE95_PGA_SIGN','PGA GOLF\nPREVIEW',3.15,-2.75,'#7ffcff');sign('PHASE95_LOUNGE_SIGN','SVR LOUNGE\nPREVIEW',-3.15,2.1,'#bd00ff');sign('PHASE95_STORE_SIGN','SVR STORE\nPREVIEW',3.15,2.1,'#ffd98a');for(let i=0;i<14;i++){const x=-5.2+i*.8,h=.8+((i*37)%100)/55;box('PHASE95_SKYLINE_'+i,x,h/2,-6.4,.42,h,.25,0x070812,.05);glow('PHASE95_SKYLINE_LIGHT_'+i,x,h*.58,-6.22,.22,h*.65,.02,i%2?0x7ffcff:0xbd00ff,.2)}const moon=new THREE.Mesh(new THREE.SphereGeometry(.62,32,16),std(0xdde8ff,.25));moon.name='PHASE95_BEAUTY_MOON';moon.position.set(-3.9,5.6,-8.2);add(moon);const mars=new THREE.Mesh(new THREE.SphereGeometry(.28,24,12),std(0xff6a3d,.18));mars.name='PHASE95_BEAUTY_MARS';mars.position.set(-2.55,5.15,-8.9);add(mars);const tc=tableCenter();const logo=new THREE.Mesh(new THREE.CircleGeometry(.48,64),new THREE.MeshBasicMaterial({map:logoTexture(),transparent:true,side:THREE.DoubleSide,depthWrite:false}));logo.name='PHASE95_TABLE_LOGO_BEAUTY_SPOT';logo.position.set(tc.x,tc.y,tc.z);logo.rotation.x=-Math.PI/2;add(logo);const spot=new THREE.PointLight(0xffd98a,1.25,4,2);spot.name='PHASE95_TABLE_SPOTLIGHT';spot.position.set(tc.x,tc.y+1.5,tc.z+.15);add(spot);const starGeo=new THREE.BufferGeometry(),pts=[];for(let i=0;i<180;i++)pts.push((Math.random()-.5)*12,3.2+Math.random()*4,-6-Math.random()*5);starGeo.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xcfe8ff,size:.035,transparent:true,opacity:.9}));stars.name='PHASE95_SOFT_STARFIELD';add(stars);window.SVR_PHASE95_BEAUTY={build:BUILD,active:true,phone:mobile,objects:group.children.length,checkedAt:new Date().toISOString()};ready=true}
function hud(){let h=document.getElementById('phase95BeautyHud');if(!h){h=document.createElement('div');h.id='phase95BeautyHud';h.style.cssText='position:fixed;left:10px;bottom:10px;z-index:9999;padding:10px 12px;border:1px solid #bd00ff;border-radius:12px;background:rgba(0,0,0,.68);color:#fff;font:800 12px system-ui';document.body.appendChild(h)}h.innerHTML='PHASE 95 BEAUTY PREVIEW<br>Lobby cinematic polish active'}
function tick(t){if(stars)stars.rotation.y=t*.000035;if(ready)requestAnimationFrame(tick)}
function loadCleanPreview(){if(qs.has('preview')||qs.get('cam')==='director'||qs.has('cam3')||qs.has('autocam')||String(location.search).includes('phase96')){import('./phase96_clean_website_third_camera_preview_lock.js?v=phase96').catch(()=>{})}}
function install(){scene=S();camera=C();root=Root();if(!scene||!root)return setTimeout(install,350);build();hud();window.SVR_LOCKED_FINAL_BUILD=BUILD;window.SVR_LIVE_BUILD_POINTER=BUILD;window.SVR_RUN_PHASE95_BEAUTY_AUDIT=()=>window.SVR_PHASE95_BEAUTY;requestAnimationFrame(tick);setTimeout(loadCleanPreview,350)}
if(run)install();else window.SVR_PHASE95_BEAUTY_ON=install;
