import * as THREE from 'three';
const LABEL='PHASE-205-TABLE-SURFACE-CARDS-AVATAR-ALIGNMENT-LOCK';
const ROOT='PHASE205_TABLE_SURFACE_CARDS_AVATAR_ALIGNMENT_ROOT';
let scene,root,started=false;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function tableObj(){const r=sr(scene);return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function bounds(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return {box:b,size:s,center:c};}
function feltMaterial(){return new THREE.MeshStandardMaterial({color:0x064126,roughness:.92,metalness:0.0,side:THREE.DoubleSide,transparent:false,opacity:1});}
function feltTex(){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d'),cx=512,cy=256;x.fillStyle='#052916';x.fillRect(0,0,1024,512);const g=x.createRadialGradient(cx,cy,20,cx,cy,480);g.addColorStop(0,'#0f5a33');g.addColorStop(.7,'#063b22');g.addColorStop(1,'#02140b');x.fillStyle=g;x.fillRect(0,0,1024,512);x.globalAlpha=.09;for(let i=0;i<3600;i++){x.fillStyle=Math.random()>.5?'#caffdc':'#00170a';x.fillRect(Math.random()*1024,Math.random()*512,Math.random()*2+.2,1);}x.globalAlpha=1;x.strokeStyle='rgba(255,217,138,.95)';x.lineWidth=10;x.beginPath();x.ellipse(cx,cy,430,190,0,0,Math.PI*2);x.stroke();x.strokeStyle='rgba(255,255,255,.58)';x.lineWidth=4;x.beginPath();x.ellipse(cx,cy,350,150,0,0,Math.PI*2);x.stroke();x.fillStyle='rgba(127,252,255,.75)';x.font='900 58px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText('SVR',cx,cy-18);x.fillStyle='rgba(255,217,138,.9)';x.font='900 26px system-ui';x.fillText('POKER',cx,cy+42);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;}
function removeDuplicateSurfaces(r){let hidden=0;const keepNames=new Set(['PHASE205_SINGLE_LOW_FELT_SURFACE']);r.traverse?.(o=>{const n=String(o.name||'');if(/PHASE168_TABLE_SURFACE_FELT|PHASE168_GREEN_FELT|PHASE167_FBX_TABLE_FELT|FELT_PASS_LINE|TABLE_SURFACE/i.test(n)&&!keepNames.has(n)){o.visible=false;o.traverse?.(c=>{c.visible=false;if(c.material){c.material.transparent=true;c.material.opacity=0;c.material.needsUpdate=true;}});hidden++;}});return hidden;}
function makeSurface(r,b){const old=r.getObjectByName?.('PHASE205_SINGLE_LOW_FELT_SURFACE_ROOT');if(old)old.parent?.remove(old);const g=new THREE.Group();g.name='PHASE205_SINGLE_LOW_FELT_SURFACE_ROOT';g.position.set(b.center.x,b.box.max.y+0.008,b.center.z);r.add(g);const w=Math.max(1.65,Math.min(b.size.x*.68,4.15));const d=Math.max(0.95,Math.min(b.size.z*.58,2.25));const felt=new THREE.Mesh(new THREE.PlaneGeometry(w,d),new THREE.MeshStandardMaterial({map:feltTex(),roughness:.9,metalness:0,side:THREE.DoubleSide}));felt.name='PHASE205_SINGLE_LOW_FELT_SURFACE';felt.rotation.x=-Math.PI/2;felt.renderOrder=2050;felt.frustumCulled=false;g.add(felt);return {surfaceY:+g.position.y.toFixed(3),w:+w.toFixed(3),d:+d.toFixed(3)};}
function alignCardsAndChips(r,b){let cards=0,chips=0,buttons=0;const cardY=b.box.max.y+0.026,chipBase=b.box.max.y+0.024;const center=b.center,size=b.size;r.traverse?.(o=>{const n=String(o.name||'');if(/PHASE168_DEMO_CARD/i.test(n)){o.position.y=cardY;o.rotation.x=-Math.PI/2;o.frustumCulled=false;cards++;}else if(/PHASE168_.*_CHIP_|PHASE168_CENTER_POT_CHIP/i.test(n)){o.position.y=Math.min(o.position.y,chipBase+0.35);chips++;}else if(/PHASE168_ACTION_BUTTON_/i.test(n)){o.position.y=b.box.max.y+0.055;buttons++;}});return {cards,chips,buttons,cardY:+cardY.toFixed(3)};}
function alignBots(r,b){let bots=0,hands=0;const y=b.box.min.y+0.24;r.traverse?.(o=>{const n=String(o.name||'');if(/PHASE168_BOT_PILL_AVATAR_/i.test(n)){o.position.y=y;bots++;o.children?.forEach(c=>{const cn=String(c.name||'');if(/FLOATING_HAND/.test(cn)){c.position.y=.54;c.position.z=-.30;c.position.x=c.position.x<0?-.14:.14;c.scale.set(.92,.38,1.35);hands++;}});}});return {bots,hands};}
function singleMoonMars(){const moons=[],mars=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon/i.test(n)&&!/mars/i.test(n))moons.push(o);if(/mars/i.test(n))mars.push(o);});const keepMoon=moons.find(o=>/PHASE196_ROTATING_MOON/i.test(o.name))||moons[0];const keepMars=mars.find(o=>/PHASE196_MARS/i.test(o.name))||mars[0];moons.forEach(o=>{const v=o===keepMoon||keepMoon?.parent===o;o.visible=v;o.traverse?.(c=>c.visible=v);});mars.forEach(o=>{const v=o===keepMars||keepMars?.parent===o;o.visible=v;o.traverse?.(c=>c.visible=v);});return {moons:moons.length,keptMoon:keepMoon?.name||null,mars:mars.length,keptMars:keepMars?.name||null};}
function stabilizeLobby(r){let panels=0;r.traverse?.(o=>{const n=String(o.name||'');if(/PHASE194_EXPANDED|PHASE195_PORTAL|PHASE195_ROOM/i.test(n)){o.visible=true;panels++;}});return {visiblePieces:panels};}
function pass(){scene=window.__SVR_SCENE__;if(!scene)return null;const r=sr(scene),t=tableObj();if(!t){window.SVR_PHASE205_TABLE_SURFACE_CARDS_AVATAR_ALIGNMENT_LOCK={build:LABEL,active:false,reason:'table-not-found',checkedAt:iso()};return window.SVR_PHASE205_TABLE_SURFACE_CARDS_AVATAR_ALIGNMENT_LOCK;}const b=bounds(t);const hiddenSurfaces=removeDuplicateSurfaces(r);const surface=makeSurface(r,b);const cards=alignCardsAndChips(r,b);const bots=alignBots(r,b);const planets=singleMoonMars();const lobby=stabilizeLobby(r);window.SVR_PHASE205_TABLE_SURFACE_CARDS_AVATAR_ALIGNMENT_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,table:t.name,tableTop:+b.box.max.y.toFixed(3),hiddenDuplicateSurfaces:hiddenSurfaces,surface,cards,bots,planets,lobby,checkedAt:iso()};return window.SVR_PHASE205_TABLE_SURFACE_CARDS_AVATAR_ALIGNMENT_LOCK;}
function install(){const out=pass();window.SVR_RUN_PHASE205_ALIGNMENT_AUDIT=()=>pass();window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(pass,1300);}return !!out;}
[700,1600,3200,6000,10000,15000].forEach(ms=>setTimeout(install,ms));install();
