import * as THREE from 'three';
const LABEL='PHASE-211-NO-BLINK-VISUAL-STABILIZER-LOCK';
let scene,camera,renderer,started=false,cache=new Map();
function root(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function table(){const r=root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function box(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c};}
function freezeObject(o){if(!o)return;const k=o.uuid;if(!cache.has(k)){cache.set(k,{y:o.position.y,visible:o.visible});}else{o.position.y=cache.get(k).y;o.visible=cache.get(k).visible;}if(o.material){o.material.transparent=o.material.opacity<1;o.material.needsUpdate=false;}o.frustumCulled=false;}
function stabilizeTableBits(bb){let cards=0,chips=0,tags=0,glass=0,surfaces=0;const r=root();const cardY=bb.b.max.y+0.014;const chipTop=bb.b.max.y+0.22;r?.traverse?.(o=>{const n=String(o.name||'');if(/PHASE168_DEMO_CARD/i.test(n)){o.position.y=cardY;o.rotation.x=-Math.PI/2;o.renderOrder=2110;freezeObject(o);cards++;}else if(/PHASE168_.*CHIP|CENTER_POT/i.test(n)){o.position.y=Math.min(o.position.y,chipTop);freezeObject(o);chips++;}else if(/ACTION_LABEL|OPEN_PLAYER_SEAT_LABEL|TABLE_STATUS_FLOATING/i.test(n)){freezeObject(o);tags++;}else if(/PHASE210_.*GLASS|PHASE210_.*RAIL|PHASE210_.*BALCONY/i.test(n)){o.visible=true;freezeObject(o);glass++;}else if(/PHASE168_TABLE_SURFACE|PHASE168_GREEN_FELT|PHASE167_FBX_TABLE_FELT|PHASE205_SINGLE|PHASE206_ONE_TABLE/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);surfaces++;}});return{cards,chips,tags,glass,surfacesHidden:surfaces};}
function hardNoSky(){let n=0;scene?.traverse?.(o=>{const name=String(o.name||'');if(/moon|mars|planet|star|sky|sprite|sparkle|strobe|blink|pulse/i.test(name)&&!/teleport|portal|watch|hand|table|card|chip/i.test(name)){o.visible=false;o.traverse?.(c=>c.visible=false);n++;}});scene.background=new THREE.Color(0x030407);scene.fog=null;return n;}
function pass(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene)return null;const t=table();let bits=null;if(t)bits=stabilizeTableBits(box(t));const sky=hardNoSky();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,tableFound:!!t,bits,skyHidden:sky,cacheSize:cache.size,checkedAt:new Date().toISOString()};window.SVR_PHASE211_NO_BLINK_VISUAL_STABILIZER_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){const out=pass();window.SVR_RUN_PHASE211_NO_BLINK_AUDIT=()=>pass();if(!started){started=true;setInterval(pass,120);}return !!out;}
[400,900,1800,3200,6000,10000].forEach(ms=>setTimeout(install,ms));install();
