import * as THREE from 'three';
const LABEL='PHASE-215-TABLE-GEOMETRY-CONTROLLER-WATCH-PANEL-LOCK';
const ROOT='PHASE215_TABLE_GEOMETRY_CONTROLLER_WATCH_PANEL_ROOT';
let scene,camera,renderer,rootGroup,started=false,keys={},watchOpen=false,lastBtn=false;
function sr(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function wc(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function cp(){const p=new THREE.Vector3();wc()?.getWorldPosition(p);return p;}
function cd(){const d=new THREE.Vector3();wc()?.getWorldDirection(d);d.y=0;if(d.lengthSq()<.001)d.set(0,0,-1);return d.normalize();}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null;}
function pose(x,y,z){const r=rig();if(renderer?.xr?.isPresenting&&r?.setPlayerPose)r.setPlayerPose(x,y,z);else camera.position.set(x,y+1.62,z);}
function floorY(){const p=cp();return Math.max(0,Math.round((p.y-1.62)/3.15)*3.15);}
function table(){const r=sr();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function tb(){const t=table();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{obj:t,b,s,c,top:b.max.y,center:c,innerW:Math.max(1.4,Math.min(s.x*.54,3.5)),innerD:Math.max(.8,Math.min(s.z*.42,1.8))};}
function tex(text,sub=''){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.88)';x.fillRect(0,0,512,160);x.strokeStyle='#ffd98a';x.lineWidth=5;x.strokeRect(8,8,496,144);x.fillStyle='#fff';x.font='900 36px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,58,470);x.fillStyle='#7ffcff';x.font='800 23px system-ui';x.fillText(sub,256,108,470);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function cardTex(r,s){const c=document.createElement('canvas');c.width=256;c.height=360;const x=c.getContext('2d');x.fillStyle='#f7f3e6';x.fillRect(0,0,256,360);x.strokeStyle='#111';x.lineWidth=10;x.strokeRect(10,10,236,340);x.fillStyle=(s==='H'||s==='D')?'#b5142b':'#101015';x.font='900 64px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(r,128,130);x.font='900 70px system-ui';x.fillText({S:'♠',H:'♥',D:'♦',C:'♣'}[s]||s,128,225);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function hideOld(){let n=0;sr()?.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE168_DEMO_CARD|PHASE168_.*CHIP|PHASE168_CENTER_POT|ACTION_LABEL|OPEN_PLAYER_SEAT_LABEL|TABLE_STATUS_FLOATING|PHASE212_STABLE|PHASE214_/i.test(nm)){o.visible=false;o.traverse?.(c=>c.visible=false);n++;}});return n;}
function makeLabel(p,n,pos,a,b){const m=new THREE.Mesh(new THREE.PlaneGeometry(1.15,.36),new THREE.MeshBasicMaterial({map:tex(a,b),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name=n;m.position.copy(pos);m.rotation.x=-.18;m.renderOrder=2150;p.add(m);return m;}
function chip(p,n,pos,color,count=5){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,.016,28),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.14}));m.name=`${n}_${i}`;m.position.set(pos.x,pos.y+i*.017,pos.z);m.renderOrder=2151;p.add(m);}}
function card(p,n,pos,r,s){const m=new THREE.Mesh(new THREE.PlaneGeometry(.27,.38),new THREE.MeshBasicMaterial({map:cardTex(r,s),side:THREE.DoubleSide,depthWrite:false}));m.name=n;m.position.copy(pos);m.rotation.x=-Math.PI/2;m.renderOrder=2151;p.add(m);}
function buildTableUI(){const rec=tb();if(!rec)return null;const r=sr();hideOld();const old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;r.add(rootGroup);const c=rec.c,cardY=rec.top+0.006,chipY=rec.top+0.012,labelY=rec.top+0.95;const clampX=x=>Math.max(c.x-rec.innerW*.46,Math.min(c.x+rec.innerW*.46,x));const clampZ=z=>Math.max(c.z-rec.innerD*.46,Math.min(c.z+rec.innerD*.46,z));[['A','S',-.48,0],['K','H',-.24,0],['Q','D',0,0],['J','C',.24,0],['10','S',.48,0]].forEach(([ra,su,x,z],i)=>card(rootGroup,`PHASE215_TABLE_GEOMETRY_COMMUNITY_CARD_${i}`,new THREE.Vector3(clampX(c.x+x),cardY,clampZ(c.z+z)),ra,su));card(rootGroup,'PHASE215_PLAYER_CARD_1',new THREE.Vector3(clampX(c.x-.16),cardY,clampZ(c.z+rec.innerD*.34)),'9','H');card(rootGroup,'PHASE215_PLAYER_CARD_2',new THREE.Vector3(clampX(c.x+.16),cardY,clampZ(c.z+rec.innerD*.34)),'9','C');chip(rootGroup,'PHASE215_CENTER_CHIPS',new THREE.Vector3(c.x,chipY,clampZ(c.z+rec.innerD*.18)),0xffd98a,8);const seats=[['YOU',0,rec.innerD*.56,0x7ffcff],['NOVA',-rec.innerW*.44,rec.innerD*.35,0xff5b8c],['ROOK',-rec.innerW*.48,-rec.innerD*.08,0xffd98a],['ACE',0,-rec.innerD*.52,0x8eff8e],['VEGA',rec.innerW*.48,-rec.innerD*.08,0xa78bfa],['IVY',rec.innerW*.44,rec.innerD*.35,0xff8bd1]];seats.forEach(([name,x,z,color],i)=>{const px=clampX(c.x+x),pz=clampZ(c.z+z);makeLabel(rootGroup,`PHASE215_HIGH_BOT_TAG_${name}`,new THREE.Vector3(px,labelY,pz),name,i===0?'OPEN SEAT':'BOT READY');chip(rootGroup,`PHASE215_INNER_CHIPS_${name}`,new THREE.Vector3(px,chipY,pz),color,4);});makeLabel(rootGroup,'PHASE215_HIGH_TABLE_TAG',new THREE.Vector3(c.x,labelY+.35,c.z-rec.innerD*.62),'TABLE READY','GEOMETRY LOCKED');return{table:rec.obj.name,top:+rec.top.toFixed(3),cardY:+cardY.toFixed(3),chipY:+chipY.toFixed(3),labelY:+labelY.toFixed(3),innerW:+rec.innerW.toFixed(3),innerD:+rec.innerD.toFixed(3)};}
function gamepad(){let f=0,s=0;const pads=navigator.getGamepads?navigator.getGamepads():[];for(const g of pads){if(!g)continue;const a=g.axes||[];for(let i=0;i<a.length;i+=2){const x=a[i]||0,y=a[i+1]||0;if(Math.abs(y)>Math.abs(f))f=-y;if(Math.abs(x)>Math.abs(s))s=x;}}return{f:Math.abs(f)>.22?f:0,s:Math.abs(s)>.22?s:0};}
function moveTick(){let f=0,s=0;if(keys.KeyW||keys.ArrowUp)f+=1;if(keys.KeyS||keys.ArrowDown)f-=1;if(keys.KeyA||keys.ArrowLeft)s-=1;if(keys.KeyD||keys.ArrowRight)s+=1;const gp=gamepad();f+=gp.f;s+=gp.s;if(Math.abs(f)<.01&&Math.abs(s)<.01)return;const d=cd(),right=new THREE.Vector3().crossVectors(d,new THREE.Vector3(0,1,0)).normalize(),p=cp(),sp=.05;pose(p.x+(d.x*f+right.x*s)*sp,floorY(),p.z+(d.z*f+right.z*s)*sp);window.SVR_PHASE215_LAST_CAMERA_RELATIVE_MOVE={f:+f.toFixed(3),s:+s.toFixed(3),dir:{x:+d.x.toFixed(3),z:+d.z.toFixed(3)},checkedAt:new Date().toISOString()};}
function patchRig(){const r=rig();if(!r||r.__phase215)return;try{if(r.move){r.move=(f=0,s=0)=>{const d=cd(),right=new THREE.Vector3().crossVectors(d,new THREE.Vector3(0,1,0)).normalize(),p=cp();pose(p.x+d.x*f+right.x*s,floorY(),p.z+d.z*f+right.z*s);};}r.__phase215=true;}catch(e){}}
function hideSky(){scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon|mars|planet|star|sky|sprite|sparkle|blink|pulse/i.test(n)&&!/teleport|portal|watch|hand|table|card|chip/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);}});}
function pass(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene)return null;hideOld();hideSky();patchRig();if(!rootGroup)buildTableUI();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,tableGeometry:tb()?true:false,staticTableUI:!!rootGroup,cameraRelativeController:true,highBotTags:true,highTableTag:true,checkedAt:new Date().toISOString()};window.SVR_PHASE215_TABLE_GEOMETRY_CONTROLLER_WATCH_PANEL_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){const out=pass();buildTableUI();window.SVR_RUN_PHASE215_TABLE_GEOMETRY_AUDIT=()=>({lock:pass(),layout:buildTableUI(),move:window.SVR_PHASE215_LAST_CAMERA_RELATIVE_MOVE||null});if(!started){started=true;window.addEventListener('keydown',e=>keys[e.code]=true);window.addEventListener('keyup',e=>keys[e.code]=false);setInterval(()=>{moveTick();pass();},60);}return !!out;}
[400,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
