import * as THREE from "three";
import { assetUrls, loadFirstTexture } from "./asset_base.js";

const BUILD="PHASE-332-PRO-TABLE-CHIP-PHYSICS-PASS-LINE-LOCK";
const ROOT="PHASE332_PRO_TABLE_ROOT", R=.036, H=.0085, G=7.2;
const DENOMS=[
  {v:1,c:"#eaf7ff",a:"#25bdf2"},{v:5,c:"#b51632",a:"#fff"},
  {v:25,c:"#127646",a:"#fff"},{v:100,c:"#171923",a:"#b86cff"}
];
let scene,camera,renderer,root,info,passRoot,bankRoot,panel,panelCanvas,panelTex,xrSession,lastT=0,installed=false;
let feltTex,microTex,finalizeTimer,handNo=-1;
const chips=[],held={left:null,right:null},down={left:false,right:false},history={left:[],right:[]};
const bet={pending:0,committed:0,last:"READY",names:[]};
const v1=new THREE.Vector3(),v2=new THREE.Vector3(),v3=new THREE.Vector3(),q1=new THREE.Quaternion();

function SR(){return scene?.getObjectByName?.("PHASE200_ORDERED_GRAND_LOBBY_ROOT")||scene}
function table(){const r=SR();return r?.getObjectByName?.("PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED")||r?.getObjectByName?.("PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT")||r?.getObjectByName?.("PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED")||null}
function box(o){o.updateWorldMatrix(true,true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c}}
function matName(o){return(Array.isArray(o.material)?o.material:[o.material]).map(m=>m?.name||"").join(" ").toLowerCase()}
function detect(){const t=table();if(!t)return null;const full=box(t);let felt=null,score=-1;t.traverse(o=>{if(!o.isMesh)return;let z;try{z=box(o)}catch{return}const n=`${o.name} ${matName(o)}`.toLowerCase();let s=(/polotno|felt|cloth|baize|surface|play/.test(n)?100:0)+(z.s.x*z.s.z)*2+(Math.max(z.s.x,z.s.z)/Math.max(.001,z.s.y)>25?25:0);if(s>score){score=s;felt={o,...z}}});const z=felt||full;info={t,full,felt:felt?.o||null,c:z.c.clone(),y:z.b.max.y+.006,w:Math.max(2.2,Math.min(z.s.x*.92,full.s.x*.72,4)),d:Math.max(1.15,Math.min(z.s.z*.9,full.s.z*.68,2.15))};info.rx=info.w*.40;info.rz=info.d*.36;return info}
function micro(){if(microTex)return microTex;const c=document.createElement("canvas");c.width=c.height=96;const g=c.getContext("2d"),im=g.createImageData(96,96);for(let i=0;i<im.data.length;i+=4){const n=95+Math.random()*70;im.data[i]=im.data[i+1]=im.data[i+2]=n;im.data[i+3]=255}g.putImageData(im,0,0);microTex=new THREE.CanvasTexture(c);microTex.wrapS=microTex.wrapT=THREE.RepeatWrapping;microTex.repeat.set(20,10);return microTex}
async function polish(){if(!info)return;feltTex=await loadFirstTexture(assetUrls("texture/tablefelt.png"),{colorSpace:THREE.SRGBColorSpace});const m=micro(),counts={felt:0,rail:0,trim:0};info.t.traverse(o=>{if(!o.isMesh||!o.material)return;const n=`${o.name} ${matName(o)}`.toLowerCase(),arr=Array.isArray(o.material)?o.material:[o.material];const out=arr.map(x=>{const a=x.clone?.()||x;if(o===info.felt||/polotno|felt|cloth|baize/.test(n)){if(feltTex)a.map=feltTex;a.color?.setHex(0xffffff);a.roughness=.78;a.metalness=.02;a.bumpMap=m;a.bumpScale=.006;counts.felt++}else if(/4carpaintblack|leather|rail|armrest|pad/.test(n)){a.color?.setHex(0x090a0f);a.roughness=.46;a.metalness=.08;a.bumpMap=m;a.bumpScale=.012;counts.rail++}else if(/1carpaintsilver|silver|chrome|metal|trim/.test(n)){a.color?.setHex(0xb8bec8);a.roughness=.24;a.metalness=.82;counts.trim++}a.needsUpdate=true;return a});o.material=Array.isArray(o.material)?out:out[0]});window.SVR_PHASE332_TABLE_MATERIALS={...counts,feltTexture:!!feltTex}}
function canvasTex(draw,w=512,h=512){const c=document.createElement("canvas");c.width=w;c.height=h;draw(c.getContext("2d"),c);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function face(d){return canvasTex((g)=>{g.translate(256,256);g.fillStyle=d.c;g.beginPath();g.arc(0,0,244,0,7);g.fill();g.strokeStyle=d.a;g.lineWidth=18;g.beginPath();g.arc(0,0,214,0,7);g.stroke();for(let i=0;i<12;i++){const a=i*Math.PI/6;g.beginPath();g.arc(0,0,232,a-.08,a+.08);g.stroke()}g.fillStyle="rgba(4,6,14,.86)";g.beginPath();g.arc(0,0,145,0,7);g.fill();g.strokeStyle="#fff";g.lineWidth=9;g.stroke();g.fillStyle="#fff";g.textAlign="center";g.textBaseline="middle";g.font="900 108px system-ui";g.fillText(`$${d.v}`,0,-18);g.fillStyle=d.a;g.font="900 38px system-ui";g.fillText("SVR POKER",0,82)})}
function edge(d){const t=canvasTex((g,c)=>{g.fillStyle=d.c;g.fillRect(0,0,c.width,c.height);for(let i=0;i<16;i+=2){g.fillStyle=d.a;g.fillRect(i*c.width/16+10,0,c.width/32,c.height)}},1024,128);t.wrapS=THREE.RepeatWrapping;return t}
const assets=new Map();function asset(d){if(assets.has(d.v))return assets.get(d.v);const a={g:new THREE.CylinderGeometry(R,R,H,40),m:[new THREE.MeshStandardMaterial({map:edge(d),roughness:.42,metalness:.12}),new THREE.MeshStandardMaterial({map:face(d),roughness:.36,metalness:.08}),new THREE.MeshStandardMaterial({map:face(d),roughness:.36,metalness:.08})]};assets.set(d.v,a);return a}
function chip(d,name,p,interactive=true){const a=asset(d),o=new THREE.Mesh(a.g,a.m);o.name=name;o.position.copy(p);o.userData={...o.userData,svr332:true,value:d.v,interactive,locked:false,held:null,dynamic:false,vel:new THREE.Vector3(),ang:new THREE.Vector3(),settled:0};chips.push(o);return o}
function labelTex(a,b=""){return canvasTex((g,c)=>{g.fillStyle="rgba(3,6,14,.38)";g.fillRect(8,8,c.width-16,c.height-16);g.strokeStyle="#fff";g.lineWidth=6;g.strokeRect(12,12,c.width-24,c.height-24);g.fillStyle="#fff";g.textAlign="center";g.textBaseline="middle";g.font="900 70px system-ui";g.fillText(a,c.width/2,76,c.width-60);g.fillStyle="#ffd98a";g.font="800 32px system-ui";g.fillText(b,c.width/2,142,c.width-60)},768,192)}
function hideOld(){SR()?.traverse(o=>{if(o.userData?.svr332)return;const n=o.name||"";if(/P85_STACK_|P85_POT_CHIP|PHASE331_POT_CHIP|PHASE323_SURFACE_.*CHIP|PHASE214_.*CHIP|PHASE215_.*CHIP|PHASE212_STABLE_CHIPS/i.test(n))o.visible=false})}
function tube(points,color,r,name){const c=new THREE.CatmullRomCurve3(points,true,"centripetal",.5),o=new THREE.Mesh(new THREE.TubeGeometry(c,128,r,8,true),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.94,depthWrite:false}));o.name=name;o.renderOrder=3320;return o}
function buildPass(){passRoot?.parent?.remove(passRoot);passRoot=new THREE.Group();passRoot.name="PHASE332_PASS_LINE_ROOT";const oval=(rx,rz,y)=>Array.from({length:96},(_,i)=>{const a=i/96*Math.PI*2;return new THREE.Vector3(info.c.x+Math.cos(a)*rx,y,info.c.z+Math.sin(a)*rz)});passRoot.add(tube(oval(info.rx+.018,info.rz+.018,info.y+.010),0xffffff,.0065,"PHASE332_PASS_WHITE"));passRoot.add(tube(oval(info.rx-.010,info.rz-.010,info.y+.012),0xd5a940,.0045,"PHASE332_PASS_GOLD"));const l=new THREE.Mesh(new THREE.PlaneGeometry(.76,.16),new THREE.MeshBasicMaterial({map:labelTex("PASS LINE","BET IS FINAL PAST LINE"),transparent:true,opacity:.86,depthWrite:false,side:THREE.DoubleSide}));l.position.set(info.c.x,info.y+.014,info.c.z+info.d*.43);l.rotation.x=-Math.PI/2;l.name="PHASE332_PASS_LABEL";passRoot.add(l);root.add(passRoot)}
function clearChips(){chips.splice(0).forEach(o=>o.parent?.remove(o));bankRoot?.parent?.remove(bankRoot);bankRoot=new THREE.Group();bankRoot.name="PHASE332_PLAYER_BANK";root.add(bankRoot)}
function buildBank(){clearChips();const z=info.c.z+info.d*.445,x=info.c.x-info.w*.29,gap=.105;DENOMS.forEach((d,s)=>{for(let i=0;i<8;i++){const p=new THREE.Vector3(x+s*gap,info.y+H*.52+i*H*1.02,z);bankRoot.add(chip(d,`PHASE332_YOU_${d.v}_${i}`,p,true))}});const left=new THREE.Mesh(new THREE.PlaneGeometry(.62,.13),new THREE.MeshBasicMaterial({map:labelTex("YOUR CHIPS","$1  $5  $25  $100"),transparent:true,opacity:.72,depthWrite:false,side:THREE.DoubleSide}));left.position.set(x+gap*1.5,info.y+.010,z+.12);left.rotation.x=-Math.PI/2;bankRoot.add(left);const right=left.clone();right.material=new THREE.MeshBasicMaterial({map:labelTex("BET AREA","RELEASE PAST PASS LINE"),transparent:true,opacity:.68,depthWrite:false,side:THREE.DoubleSide});right.position.x=info.c.x+info.w*.27;bankRoot.add(right);bet.pending=bet.committed=0;bet.names=[];bet.last="READY";paintPanel()}
function insidePass(p){const x=(p.x-info.c.x)/info.rx,z=(p.z-info.c.z)/info.rz;return x*x+z*z<=1}
function insideTable(p,m=1){const x=(p.x-info.c.x)/(info.w*.49*m),z=(p.z-info.c.z)/(info.d*.49*m);return x*x+z*z<=1}
function source(side,kind){const fn=kind==="hand"?"getHand":"getController";for(let i=0;i<2;i++){const s=renderer?.xr?.[fn]?.(i),h=s?.userData?.handedness||s?.inputSource?.handedness||s?.userData?.inputSource?.handedness;if(h===side)return s}return renderer?.xr?.[fn]?.(side==="left"?0:1)||null}
function pose(side){const h=source(side,"hand"),active=window.SVR_HAND_INPUT_STATE?.[side]?.native||h?.joints?.wrist||h?.joints?.["index-finger-tip"];if(active&&h?.joints){const a=h.joints["thumb-tip"],b=h.joints["index-finger-tip"];if(!a||!b)return null;a.getWorldPosition(v1);b.getWorldPosition(v2);return{down:v1.distanceTo(v2)<.038,p:v1.clone().add(v2).multiplyScalar(.5),r:.12}}const c=source(side,"controller");if(!c)return null;c.updateWorldMatrix(true,false);c.getWorldPosition(v1);c.getWorldQuaternion(q1);const p=v1.clone().add(new THREE.Vector3(0,-.014,-.07).applyQuaternion(q1)),gp=c.inputSource?.gamepad||c.userData?.inputSource?.gamepad;return{down:(gp?.buttons?.[0]?.value||0)>.55,p,r:.18}}
function nearest(p,r){let hit=null,d=r;for(const c of chips){if(!c.userData.interactive||c.userData.locked||c.userData.held||!c.visible)continue;c.getWorldPosition(v3);const x=v3.distanceTo(p);if(x<d){d=x;hit=c}}return hit}
function hist(side,p){history[side].push({p:p.clone(),t:performance.now()});while(history[side].length>6)history[side].shift()}
function grab(side,p){const c=nearest(p.p,p.r);if(!c)return;scene.attach(c);c.userData.held=side;c.userData.dynamic=false;c.userData.vel.set(0,0,0);held[side]=c;history[side]=[];hist(side,p.p)}
function throwVel(side){const h=history[side];if(h.length<2)return new THREE.Vector3();const b=h[h.length-1],a=h.find(x=>b.t-x.t>=45)||h[0],dt=Math.max(.018,(b.t-a.t)/1000),v=b.p.clone().sub(a.p).divideScalar(dt).multiplyScalar(.78);if(v.length()>3.2)v.setLength(3.2);return v}
function release(side){const c=held[side];if(!c)return;c.userData.held=null;c.userData.vel.copy(throwVel(side));c.userData.ang.set(c.userData.vel.z*4.2,(Math.random()-.5)*7,-c.userData.vel.x*4.2);c.userData.dynamic=true;c.userData.settled=0;held[side]=null;history[side]=[]}
function input(side){const p=pose(side);if(!p){if(held[side])release(side);down[side]=false;return}if(p.down&&!down[side]&&!held[side])grab(side,p);if(p.down&&held[side]){held[side].position.copy(p.p);held[side].rotation.x=Math.PI*.5;hist(side,p.p)}if(!p.down&&down[side]&&held[side])release(side);down[side]=p.down}
function commit(c){if(c.userData.locked)return;c.userData.locked=true;c.userData.interactive=false;c.userData.dynamic=false;bet.pending+=c.userData.value;bet.committed+=c.userData.value;bet.names.push(c.name);bet.last=`COMMITTED $${c.userData.value}`;paintPanel();clearTimeout(finalizeTimer);finalizeTimer=setTimeout(finalize,800);window.dispatchEvent(new CustomEvent("svr:physical-bet-committed",{detail:{value:c.userData.value,total:bet.pending}}))}
function finalize(){if(!bet.pending)return false;const amount=bet.pending,s=window.SVR_PHASE85_POKER_STATE;let action="physical-bet";if(s?.waitingHuman&&window.SVR_POKER_ACTION){let a;try{a=window.SVR_RUN_PHASE85_POKER_AUDIT?.()}catch{}const you=a?.players?.find(p=>p.name==="YOU")||a?.players?.[0],need=Math.max(0,(s.currentBet||0)-(you?.bet||0));action=need>0&&amount<=need?"call":"raise";window.SVR_POKER_ACTION(action)}bet.last=`${action.toUpperCase()} $${amount}`;bet.pending=0;paintPanel();return true}
function settle(c){let hit=null,d=.082;for(const o of chips){if(o===c||o.userData.held||o.userData.dynamic||!o.visible)continue;const x=Math.hypot(o.position.x-c.position.x,o.position.z-c.position.z);if(x<d){d=x;hit=o}}if(hit){c.position.x=hit.position.x;c.position.z=hit.position.z;c.position.y=Math.max(info.y+H*.52,hit.position.y+H*1.02)}else c.position.y=info.y+H*.52;c.rotation.x=c.rotation.z=0;c.userData.vel.set(0,0,0);c.userData.ang.set(0,0,0);c.userData.dynamic=false;c.userData.settled=0;if(insidePass(c.position))commit(c)}
function physics(dt){for(const c of chips){if(!c.userData.dynamic||c.userData.held||c.userData.locked)continue;const v=c.userData.vel,a=c.userData.ang;v.y-=G*dt;c.position.addScaledVector(v,dt);c.rotation.x+=a.x*dt;c.rotation.y+=a.y*dt;c.rotation.z+=a.z*dt;a.multiplyScalar(Math.pow(.988,dt*60));const y=info.y+H*.52;if(insideTable(c.position,1.06)&&c.position.y<=y&&v.y<=0){c.position.y=y;v.y=Math.abs(v.y)>.35?-v.y*.18:0;v.x*=.82;v.z*=.82;a.multiplyScalar(.8);const nx=(c.position.x-info.c.x)/(info.w*.485),nz=(c.position.z-info.c.z)/(info.d*.485),d2=nx*nx+nz*nz;if(d2>1){const l=Math.sqrt(d2),n=new THREE.Vector3(nx/(info.w*.485),0,nz/(info.d*.485)).normalize();c.position.x=info.c.x+nx/l*info.w*.485*.985;c.position.z=info.c.z+nz/l*info.d*.485*.985;const dot=v.dot(n);if(dot>0)v.addScaledVector(n,-1.55*dot);v.multiplyScalar(.72)}const speed=Math.hypot(v.x,v.z)+Math.abs(v.y);c.userData.settled=speed<.07?c.userData.settled+1:0;if(c.userData.settled>12)settle(c)}}}
function ensurePanel(){if(panel)return;panelCanvas=document.createElement("canvas");panelCanvas.width=768;panelCanvas.height=192;panelTex=new THREE.CanvasTexture(panelCanvas);panelTex.colorSpace=THREE.SRGBColorSpace;panel=new THREE.Mesh(new THREE.PlaneGeometry(.78,.22),new THREE.MeshBasicMaterial({map:panelTex,transparent:true,opacity:.8,depthWrite:false,side:THREE.DoubleSide}));panel.name="PHASE332_BET_STATUS";root.add(panel)}
function paintPanel(){if(!info||!root)return;ensurePanel();const g=panelCanvas.getContext("2d");g.clearRect(0,0,768,192);g.fillStyle="rgba(3,6,14,.42)";g.fillRect(8,8,752,176);g.strokeStyle="#7ffcff";g.lineWidth=6;g.strokeRect(12,12,744,168);g.fillStyle="#fff";g.textAlign="center";g.textBaseline="middle";g.font="900 70px system-ui";g.fillText(`BET $${bet.pending}`,384,76,700);g.fillStyle="#ffd98a";g.font="800 34px system-ui";g.fillText(bet.last,384,142,700);panelTex.needsUpdate=true;panel.position.set(info.c.x+info.w*.27,info.y+.26,info.c.z+info.d*.36)}
function facePanel(){if(!panel)return;const c=renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;c?.getWorldPosition(v1);panel.lookAt(v1.x,panel.position.y,v1.z)}
function xrTick(){const s=renderer?.xr?.getSession?.();if(!s||s!==xrSession)return;const n=performance.now(),dt=Math.min(.033,Math.max(.001,(n-lastT)/1000));lastT=n;input("left");input("right");physics(dt);facePanel();s.requestAnimationFrame(xrTick)}
function startXR(){const s=renderer?.xr?.getSession?.();if(!s||s===xrSession)return;xrSession=s;lastT=performance.now();s.requestAnimationFrame(xrTick)}
function qa(){return{build:BUILD,active:installed,table:info?.t?.name||null,felt:info?.felt?.name||null,surfaceY:info?+info.y.toFixed(4):null,chipDiameter:+(R*2).toFixed(3),chipThickness:+H.toFixed(4),denominations:Object.fromEntries(DENOMS.map(d=>[d.v,chips.filter(c=>c.userData.value===d.v).length])),dynamic:chips.filter(c=>c.userData.dynamic).length,held:{left:held.left?.name||null,right:held.right?.name||null},passLine:!!passRoot,pendingBet:bet.pending,committedBet:bet.committed,materials:window.SVR_PHASE332_TABLE_MATERIALS||null,siteTouched:false,checkedAt:new Date().toISOString()}}
async function install(){if(installed)return;scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer){setTimeout(install,250);return}info=detect();if(!info){setTimeout(install,350);return}installed=true;root=SR().getObjectByName?.(ROOT)||new THREE.Group();if(!root.parent){root.name=ROOT;SR().add(root)}await polish();buildPass();buildBank();hideOld();handNo=window.SVR_PHASE85_POKER_STATE?.handNo||0;window.SVR_PHASE332_TABLE_SYSTEM={build:BUILD,qa,finalizeBet:finalize,rebuild:()=>{info=detect();buildPass();buildBank();hideOld();return qa()},siteTouched:false};window.SVR_PHASE332_TABLE_QA=qa;window.SVR_FINALIZE_PHYSICAL_BET=finalize;window.SVR_RESET_PLAYER_CHIPS=buildBank;window.SVR_LOCKED_FINAL_BUILD=BUILD;renderer.xr.addEventListener("sessionstart",()=>setTimeout(startXR,120));renderer.xr.addEventListener("sessionend",()=>xrSession=null);if(renderer.xr.isPresenting)startXR();setInterval(()=>{hideOld();window.SVR_PHASE331_QUEST_TABLE_INTERACTION?.align?.();facePanel();const h=window.SVR_PHASE85_POKER_STATE?.handNo||0;if(h!==handNo){handNo=h;buildBank()}},650)}
install();
