/* PHASE-420-TOURNAMENT-START-AUTHORITY-LOCK */
/* PHASE-423-TOURNAMENT-CURRENT-SLOT-REGISTRATION-GATE-LOCK */
const BUILD='PHASE-420-TOURNAMENT-START-AUTHORITY-LOCK',SUCCESSOR='PHASE-423-TOURNAMENT-CURRENT-SLOT-REGISTRATION-GATE-LOCK';
const SLOT_MS=5*60*60*1000,ANCHOR=Date.UTC(2026,0,1,0,0,0),LOCAL_REG_KEY='svr419_tournament_registrations_v1',LOCAL_TEST_KEY='svr_phase412_tournament_test_account_v1';
const state={build:BUILD,successorBuild:SUCCESSOR,installed:false,currentSlot:null,nextRegistrationSlot:null,accountEligible:false,registeredCurrent:false,eligible:false,sharedBackend:false,entryTarget:null,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s),slotId=t=>Math.floor((t-ANCHOR)/SLOT_MS),slot=id=>({id,start:ANCHOR+id*SLOT_MS,end:ANCHOR+(id+1)*SLOT_MS}),currentSlot=()=>slot(slotId(Date.now())),nextSlot=()=>slot(slotId(Date.now())+1),entryUrl=id=>`/game/android-tabletop.html?v=phase420&mode=tournament&tournament=reiki-open-100&slot=${encodeURIComponent(id)}`;
async function accountState(){try{const m=await import('/site/js/phase345-player-account-client.js?v=phase423');await m.account.bootstrap();return m.account.snapshot()}catch{return window.SVR_PLAYER_ACCOUNT?.snapshot?.()||window.SVR_PLAYER_ACCOUNT_STATE||null}}
function localTest(){try{return JSON.parse(localStorage.getItem(LOCAL_TEST_KEY)||'null')}catch{return null}}
function localRows(id){try{const all=JSON.parse(localStorage.getItem(LOCAL_REG_KEY)||'{}');return Array.isArray(all?.[id])?all[id]:[]}catch{return[]}}
function accountEligible(a){const production=Boolean(a?.profile&&a.mode==='api'&&!a.profile.demoMode),test=localTest(),local=Boolean(a?.profile&&a.mode==='demo'&&test?.playerId===a.profile.playerId);return a?.apiConfigured&&a?.apiHealthy?production:Boolean(production||local)}
async function tournamentConfig(){try{const r=await fetch('/game/config/tournament-api.json?v=phase423',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const c=await r.json();return{...c,apiBase:String(window.SVR_TOURNAMENT_API_BASE||c.apiBase||'').replace(/\/$/,'')}}catch{return{apiBase:'',sharedRegistrationBackendLive:false}}}
async function isRegistered(id,a,cfg){const playerId=String(a?.profile?.playerId||'');if(!playerId)return false;if(cfg.apiBase&&cfg.sharedRegistrationBackendLive){state.sharedBackend=true;const r=await fetch(`${cfg.apiBase}/api/tournaments/${encodeURIComponent(id)}/registrations`,{cache:'no-store',credentials:'include',headers:{Accept:'application/json','X-SVR-Client':SUCCESSOR}}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||`Tournament roster HTTP ${r.status}`);return(Array.isArray(d.registrations)?d.registrations:[]).some(x=>String(x.playerId)===playerId)}state.sharedBackend=false;return localRows(id).some(x=>String(x.playerId)===playerId)}
function routeUnregistered(enter,current,next,a){if(!enter)return;if(!state.accountEligible){const requested=encodeURIComponent(`/game/tournaments.html?v=phase420`);enter.href=`/site/tournament-account.html?v=phase423&next=${requested}`;enter.textContent='LOGIN / CREATE ACCOUNT TO ENTER';enter.dataset.accountGate='required';return}enter.href=`/game/tournament-signup.html?v=phase420&slot=${encodeURIComponent(next.id)}`;enter.textContent=state.sharedBackend?'NOT REGISTERED • SIGN UP NEXT':'SIGN UP FOR NEXT TOURNAMENT';enter.dataset.accountGate='registered-current-required';enter.dataset.phase420Slot=String(current.id);if(a?.profile?.displayName)enter.title=`${a.profile.displayName} is not registered for current slot #${current.id}. Registration is open for slot #${next.id}.`}
async function sync(){try{const current=currentSlot(),next=nextSlot(),a=await accountState(),cfg=await tournamentConfig(),enter=$('#enterTournament');state.currentSlot=current;state.nextRegistrationSlot=next;state.accountEligible=accountEligible(a);state.registeredCurrent=state.accountEligible?await isRegistered(current.id,a,cfg):false;state.eligible=Boolean(state.accountEligible&&state.registeredCurrent);if(enter&&state.eligible){state.entryTarget=entryUrl(current.id);enter.href=state.entryTarget;enter.dataset.phase420Slot=String(current.id);enter.dataset.accountGate='passed';enter.textContent='ENTER CURRENT TOURNAMENT';enter.title=`Registered for current slot #${current.id}.`}else if(enter){state.entryTarget=null;routeUnregistered(enter,current,next,a)}const label=$('#phase411NextTournament');if(label){label.dataset.phase420CurrentSlot=String(current.id);label.title=`Current slot #${current.id} runs until ${new Date(current.end).toLocaleString()}. Sign-up is for slot #${next.id}.`}document.querySelectorAll('a[href*="tournament-signup.html"]').forEach(link=>{try{const u=new URL(link.href,location.href);u.searchParams.set('v','phase420');u.searchParams.set('slot',String(next.id));link.href=u.pathname+u.search}catch{}});document.body.dataset.phase420CurrentTournament=String(current.id);document.body.dataset.phase420NextRegistration=String(next.id);document.body.dataset.phase423CurrentRegistration=state.registeredCurrent?'yes':'no';state.installed=true;state.lastError=null;state.checkedAt=new Date().toISOString();return true}catch(e){state.lastError=String(e?.message||e);state.eligible=false;state.registeredCurrent=false;state.checkedAt=new Date().toISOString();const enter=$('#enterTournament');if(enter){enter.textContent='TOURNAMENT ROSTER UNAVAILABLE';enter.removeAttribute('href')}return false}}
function boot(){sync();window.addEventListener('svr:account-ready',sync);window.addEventListener('svr:account-change',sync);window.addEventListener('svr:account-confirmed',sync);setTimeout(sync,600);setTimeout(sync,1800);setInterval(sync,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.SVR_PHASE420_TOURNAMENT_START_QA=()=>({build:BUILD,successorBuild:SUCCESSOR,...state,slotMilliseconds:SLOT_MS,exactFiveHourCadence:SLOT_MS===18000000,currentEntryUsesCurrentSlot:Boolean(state.eligible&&state.entryTarget?.includes(`slot=${state.currentSlot?.id}`))||!state.eligible,registrationUsesNextSlot:Boolean(state.nextRegistrationSlot&&state.currentSlot&&state.nextRegistrationSlot.id===state.currentSlot.id+1),currentRegistrationRequired:true,productionSharedRegistrationLive:state.sharedBackend,pass:Boolean(state.installed&&SLOT_MS===18000000&&!state.lastError),checkedAt:new Date().toISOString()});
