import * as THREE from 'three';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { DEALER_MOTION } from './phase368_card_dealer_motion.js';

export const BUILD = 'PHASE-381-VR-SEAT-ERIC-AUDIO-OVERLAY-LOCK';
const params = new URLSearchParams(location.search);
const ua = navigator.userAgent || '';
const platform = String(window.SVR_PLATFORM || params.get('platform') || document.body?.dataset?.platform || (/Quest|Oculus|Meta Quest/i.test(ua) ? 'quest' : /Android/i.test(ua) ? 'android' : 'desktop')).toLowerCase();
const FLAGS = ['SVR_MOVEMENT_ENABLED','SVR_LOCOMOTION_ENABLED','SVR_TABLE_TRAVEL_ENABLED','SVR_TELEPORT_ENABLED','SVR_HAND_TELEPORT_ENABLED','SVR_WATCH_TELEPORT_ENABLED','SVR_GRIP_TELEPORT_ENABLED','SVR_POINTER_ENABLED','SVR_HAND_RAY_ENABLED','SVR_SNAP_TURN_ENABLED','SVR_STICK_MOVE_ENABLED'];
const MOVE_METHODS = ['teleport','teleportTo','moveTo','setTeleportPosition','setPosition','setPlayerPose'];
const TELEPORT_RX = /(teleport|ray|arc|landing|marker|reticle)/i;
const BAD_OVERLAY_RX = /(head[_ -]?overlay|camera[_ -]?overlay|screen[_ -]?overlay|vignette|debug[_ -]?(screen|panel|quad)|comfort[_ -]?mask|fade[_ -]?plane|visor[_ -]?screen)/i;
const KEEP_RX = /(watch|forearm|hand|controller|poker|card|table|logo|action|button|safeStage|avatar|dealer)/i;
const state = {build:BUILD,platform,installed:false,seated:false,flagsLocked:false,blockedMoves:0,anchorCorrections:0,teleportVisualsHidden:0,overlaysHidden:0,ericLoaded:false,ericVisible:false,ericMappedBones:0,ericMotionPlays:0,ericLastReason:null,oldSkeletonsHidden:0,audioEnabled:localStorage.getItem('svrAudioEnabled')!=='false',audioUnlocked:false,audioEvents:0,lastError:null,installedAt:null,checkedAt:null};
const savedFlags = new Map(), savedVisibility = new Map(), wrappedRigs = new WeakSet();
const tmp = new THREE.Vector3(), tmp2 = new THREE.Vector3();
let scene=null,camera=null,renderer=null,seatAnchor=null,internalMove=false,raf=0,timer=0,lastSweep=0;
let eric=null,rotationData=null,translationData=null,playing=false,playStarted=0,lastPlay=-Infinity,lastHand=-1,lastCommunity=-1;
const bones=new Map(),rests=new Map();
let audioContext=null,ambience=null,ambienceGain=null,lastAudioSignature='';

function walk(root,visitor,limit=18000){const stack=root?[root]:[],seen=new Set();while(stack.length&&seen.size<limit){const o=stack.pop();if(!o||seen.has(o))continue;seen.add(o);try{visitor(o)}catch{}for(const c of o.children||[])if(c&&c!==o)stack.push(c)}}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||window.SVR_PLAYER_RIG||window.__SVR_PLAYER_RIG||null}
function activeCamera(){const v=renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;return v?.cameras?.[0]||v||camera}
function seatedNow(){return Boolean(window.SVR_PHASE361_STATE?.seated||window.SVR_PHASE363_STATE?.joined||window.SVR_PHASE365_STATE?.joined||document.body.classList.contains('svr361-seated')||document.body.classList.contains('svr363-seated')||document.body.classList.contains('svr365-seated')||document.body.dataset.svrSeated==='true')}
function captureSeat(){const r=rig();if(r?.position)seatAnchor=r.position.clone();else activeCamera()?.getWorldPosition?.(seatAnchor=new THREE.Vector3());return seatAnchor}
function lockFlags(){for(const key of FLAGS){if(!savedFlags.has(key))savedFlags.set(key,window[key]);window[key]=false}window.SVR_TABLE_MOVEMENT_LOCKED=true;window.SVR_PHASE381_SEATED_LOCK=true;state.flagsLocked=true}
function restoreFlags(){for(const key of FLAGS){const old=savedFlags.get(key);window[key]=typeof old==='boolean'?old:true}window.SVR_TABLE_MOVEMENT_LOCKED=false;window.SVR_PHASE381_SEATED_LOCK=false;state.flagsLocked=false}
function wrapRig(){const r=rig();if(!r||wrappedRigs.has(r))return;for(const name of MOVE_METHODS){const original=r[name];if(typeof original!=='function')continue;r[name]=function(...args){if(state.seated&&!internalMove){state.blockedMoves++;return false}return original.apply(this,args)}}wrappedRigs.add(r)}
function hideTeleport(){let count=0;walk(scene,o=>{const name=String(o?.name||'');if(!TELEPORT_RX.test(name)||KEEP_RX.test(name))return;if(state.seated){if(!savedVisibility.has(o))savedVisibility.set(o,o.visible);o.visible=false;count++}else if(savedVisibility.has(o)){o.visible=savedVisibility.get(o);savedVisibility.delete(o)}});state.teleportVisualsHidden=state.seated?count:0}
function cleanupOverlays(){const head=activeCamera();if(!head||!scene)return 0;head.getWorldPosition(tmp);let hidden=0;walk(scene,o=>{if(!o?.isObject3D||o===head)return;const name=String(o.name||'');if(!BAD_OVERLAY_RX.test(name)||KEEP_RX.test(name))return;let p=o.parent,attached=false;while(p){if(p===head||p===camera){attached=true;break}p=p.parent}o.getWorldPosition?.(tmp2);const near=tmp2.distanceTo(tmp)<0.9;const mats=o.isMesh?(Array.isArray(o.material)?o.material:[o.material]):[];const screen=mats.some(m=>m&&(m.depthTest===false||m.transparent||Number(m.opacity)<0.98));if(attached||(near&&screen)){o.visible=false;o.userData={...(o.userData||{}),svrPhase381OverlayRemoved:true};hidden++}});state.overlaysHidden=Math.max(state.overlaysHidden,hidden);return hidden}
function correctSeat(){const r=rig();if(!state.seated||!seatAnchor||!r?.position||r.position.distanceTo(seatAnchor)<=0.025)return;internalMove=true;r.position.copy(seatAnchor);internalMove=false;state.anchorCorrections++}
function seatLock(source='detected'){if(state.seated)return true;state.seated=true;document.body.dataset.svrSeated='true';document.body.classList.add('svr381-seated-lock');wrapRig();captureSeat();lockFlags();hideTeleport();window.dispatchEvent(new CustomEvent('svr:phase381-seat-lock',{detail:{source}}));return true}
function seatUnlock(source='detected'){if(!state.seated)return true;state.seated=false;document.body.dataset.svrSeated='false';document.body.classList.remove('svr381-seated-lock');seatAnchor=null;restoreFlags();hideTeleport();window.dispatchEvent(new CustomEvent('svr:phase381-seat-unlock',{detail:{source}}));return true}
function syncSeat(source='poll'){const next=seatedNow();if(next&&!state.seated)seatLock(source);if(!next&&state.seated)seatUnlock(source);if(state.seated){lockFlags();correctSeat();hideTeleport()}return state.seated}

function decode16(base64){const b=atob(base64),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new Int16Array(u.buffer)}
function cleanName(v=''){return String(v).replace(/^[^:]+:/,'').replace(/mixamorig/ig,'').replace(/cc_base_/ig,'').replace(/bip0?1/ig,'').replace(/[^a-z0-9]/ig,'').toLowerCase()}
const aliases={Hips:['hips','hip','pelvis'],Spine:['spine','spine01','waist'],Spine1:['spine1','spine02','chest'],Spine2:['spine2','spine03','upperchest'],Neck:['neck','neck01'],Head:['head'],LeftShoulder:['leftshoulder','lshoulder','leftclavicle','lclavicle'],LeftArm:['leftarm','leftupperarm','lupperarm'],LeftForeArm:['leftforearm','leftlowerarm','lforearm','llowerarm'],LeftHand:['lefthand','lhand'],RightShoulder:['rightshoulder','rshoulder','rightclavicle','rclavicle'],RightArm:['rightarm','rightupperarm','rupperarm'],RightForeArm:['rightforearm','rightlowerarm','rforearm','rlowerarm'],RightHand:['righthand','rhand']};
function bounds(o){o.updateWorldMatrix?.(true,true);const box=new THREE.Box3().setFromObject(o,true);return{box,size:box.getSize(new THREE.Vector3()),center:box.getCenter(new THREE.Vector3())}}
function normalizeEric(o){const rotations=[[0,0,0],[-Math.PI/2,0,0],[Math.PI/2,0,0],[0,0,Math.PI/2],[0,0,-Math.PI/2],[0,Math.PI,0]];let best=null;for(const r of rotations){o.rotation.set(...r);const b=bounds(o),score=b.size.y/Math.max(b.size.x,b.size.z,.001);if(!best||score>best.score)best={score,rotation:o.rotation.clone()}}if(best)o.rotation.copy(best.rotation);let b=bounds(o);o.scale.multiplyScalar(1.72/Math.max(b.size.y,.001));b=bounds(o);o.position.x-=b.center.x;o.position.z-=b.center.z;o.position.y-=b.box.min.y;o.name='PHASE381_APPROVED_CARD_DEALER_RIG';o.userData={...(o.userData||{}),svrApprovedDealerRig:true,svrPhase381Approved:true,sourceAsset:'game/assets/models/eric/eric.fbx',build:BUILD};walk(o,x=>{if(/eric/i.test(String(x.name||'')))x.name=String(x.name||'approvedDealer').replace(/eric/ig,'approvedDealer');x.userData={...(x.userData||{}),svrPhase381Approved:true};if(x.isMesh){x.frustumCulled=false;x.castShadow=false;x.receiveShadow=true}})}
function tableInfo(){const t=window.SVR_TABLE_AUTHORITY;if(!t?.isObject3D)return null;const b=bounds(t);if(b.box.isEmpty())return null;return{box:b.box,size:b.size,center:b.center,topY:b.box.max.y}}
function alignEric(){if(!eric||!scene)return false;const t=tableInfo();if(!t)return false;eric.position.set(t.center.x,0,t.box.min.z-.42);eric.rotation.y=Math.PI;eric.visible=true;state.ericVisible=true;return true}
function mapBones(){bones.clear();rests.clear();for(const target of DEALER_MOTION.bones){const wants=(aliases[target]||[target]).map(cleanName);let found=null;walk(eric,o=>{if(found||!o?.isBone)return;const n=cleanName(o.name);if(wants.includes(n))found=o});if(!found)walk(eric,o=>{if(found||!o?.isBone)return;const n=cleanName(o.name);if(wants.some(w=>n.endsWith(w)||n.includes(w)))found=o});if(found){bones.set(target,found);rests.set(target,found.rotation.clone())}}state.ericMappedBones=bones.size;return bones.size}
function hideOldSkeletons(){if(!scene)return 0;let count=0;walk(scene,o=>{if(o===eric||eric?.getObjectById?.(o.id))return;const n=String(o.name||'');if(!/(PHASE368_CARD_DEALER_ROOT|dealer[_ -]?skeleton|skeleton[_ -]?helper|armature[_ -]?debug|debug[_ -]?skeleton)/i.test(n))return;o.visible=false;o.userData={...(o.userData||{}),svrPhase381ReplacedByApprovedRig:true};count++});state.oldSkeletonsHidden=Math.max(state.oldSkeletonsHidden,count);return count}
function applyMotion(frameFloat,amp=1,armsOnly=false){if(!eric||!rotationData)return;const f0=Math.floor(frameFloat)%DEALER_MOTION.frames,f1=(f0+1)%DEALER_MOTION.frames,a=frameFloat-Math.floor(frameFloat),stride=DEALER_MOTION.bones.length*3;for(let i=0;i<DEALER_MOTION.bones.length;i++){const name=DEALER_MOTION.bones[i],bone=bones.get(name),rest=rests.get(name);if(!bone||!rest||(armsOnly&&!/(Shoulder|Arm|ForeArm|Hand|Spine2)/.test(name)))continue;const o0=f0*stride+i*3,o1=f1*stride+i*3;const x=THREE.MathUtils.lerp(rotationData[o0],rotationData[o1],a)/DEALER_MOTION.scale*amp;const y=THREE.MathUtils.lerp(rotationData[o0+1],rotationData[o1+1],a)/DEALER_MOTION.scale*amp;const z=THREE.MathUtils.lerp(rotationData[o0+2],rotationData[o1+2],a)/DEALER_MOTION.scale*amp;bone.rotation.set(rest.x+x*Math.PI/180,rest.y+y*Math.PI/180,rest.z+z*Math.PI/180,'XYZ')}if(!armsOnly&&translationData){const hips=bones.get('Hips'),t0=f0*3,t1=f1*3;if(hips){hips.position.x=THREE.MathUtils.lerp(translationData[t0],translationData[t1],a)/DEALER_MOTION.scale*.006;hips.position.z=THREE.MathUtils.lerp(translationData[t0+2],translationData[t1+2],a)/DEALER_MOTION.scale*.004}}}
function playEric(reason='manual'){if(!eric||performance.now()-lastPlay<650)return false;lastPlay=performance.now();playStarted=lastPlay;playing=true;state.ericMotionPlays++;state.ericLastReason=reason;playDealAudio();return true}
function updateEric(){if(!eric)return;alignEric();hideOldSkeletons();if(playing){const elapsed=(performance.now()-playStarted)/1000*2.15;applyMotion(Math.min(DEALER_MOTION.duration,elapsed)*DEALER_MOTION.fps,1,false);if(elapsed>=DEALER_MOTION.duration){playing=false;applyMotion(0)}}else{const f=(performance.now()/1000*.85*DEALER_MOTION.fps)%DEALER_MOTION.frames;applyMotion(f,.18,true)}}
async function loadEric(){if(eric)return eric;try{scene=window.__SVR_SCENE__||scene;if(!scene||!tableInfo())return null;const loaded=await new FBXLoader().loadAsync(new URL('../assets/models/eric/eric.fbx',import.meta.url).href);normalizeEric(loaded);eric=loaded;scene.add(eric);rotationData=decode16(DEALER_MOTION.rotationBase64);translationData=decode16(DEALER_MOTION.translationBase64);mapBones();alignEric();hideOldSkeletons();state.ericLoaded=true;return eric}catch(error){state.lastError=String(error?.message||error);return null}}
function inspectPoker(){const p=window.SVR_RUN_PHASE336_POKER_AUDIT?.()||window.SVR_PHASE359_STATE||window.SVR_PHASE360_STATE||{};const hand=Number(p.handNo??p.handNumber??p.hand??-1),community=Number(p.communityCount??p.communityCards??p.boardCount??-1);if(hand>=0&&hand!==lastHand){lastHand=hand;playEric('new-hand');playShuffleAudio()}else if(community>=0&&community!==lastCommunity){lastCommunity=community;playEric('community-card')}}

function ensureAudio(){if(audioContext)return audioContext;const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audioContext=new C();state.audioUnlocked=true;return audioContext}
function tone(freq,duration=.08,type='sine',gain=.06,delay=0){if(!state.audioEnabled)return false;const c=ensureAudio();if(!c)return false;const o=c.createOscillator(),g=c.createGain(),now=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.008);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(c.destination);o.start(now);o.stop(now+duration+.02);state.audioEvents++;return true}
function noise(duration=.06,gain=.035,delay=0){if(!state.audioEnabled)return false;const c=ensureAudio();if(!c)return false;const length=Math.max(1,Math.floor(c.sampleRate*duration)),buffer=c.createBuffer(1,length,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const src=c.createBufferSource(),g=c.createGain(),now=c.currentTime+delay;src.buffer=buffer;g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);src.connect(g).connect(c.destination);src.start(now);state.audioEvents++;return true}
function playShuffleAudio(){noise(.16,.025);tone(160,.08,'triangle',.025,.02);tone(205,.07,'triangle',.02,.09)}
function playDealAudio(){noise(.045,.025);tone(520,.035,'triangle',.018,.01)}
function playChipAudio(amount=20){const n=amount>=500?4:amount>=100?3:2;for(let i=0;i<n;i++){tone(850+i*120,.035,'square',.018,i*.035);noise(.025,.012,i*.035)}}
function playWinnerAudio(){tone(523,.12,'sine',.045);tone(659,.12,'sine',.045,.1);tone(784,.2,'sine',.05,.2)}
function startAmbience(){if(!state.audioEnabled||ambience)return;const c=ensureAudio();if(!c)return;ambience=c.createOscillator();ambienceGain=c.createGain();ambience.type='sine';ambience.frequency.value=46;ambienceGain.gain.value=.008;ambience.connect(ambienceGain).connect(c.destination);ambience.start()}
function stopAmbience(){try{ambience?.stop()}catch{}ambience=null;ambienceGain=null}
function toggleAudio(force){state.audioEnabled=typeof force==='boolean'?force:!state.audioEnabled;localStorage.setItem('svrAudioEnabled',String(state.audioEnabled));window.SVR_AUDIO_ENABLED=state.audioEnabled;if(state.audioEnabled){ensureAudio()?.resume?.();startAmbience()}else stopAmbience();return state.audioEnabled}
function bindAudio(){const unlock=()=>{if(!state.audioEnabled)return;ensureAudio()?.resume?.();startAmbience()};for(const name of ['pointerdown','touchstart','keydown'])window.addEventListener(name,unlock,{once:true,passive:true});window.addEventListener('keydown',e=>{if(e.code==='KeyM')toggleAudio()});document.addEventListener('click',e=>{const action=e.target?.dataset?.a||e.target?.dataset?.action||'';if(/fold|check|call|raise|allin/i.test(action))playChipAudio(/allin/i.test(action)?1000:/raise/i.test(action)?100:20);if(e.target?.id==='join'||e.target?.id==='next')playShuffleAudio()})}

function inspectRuntime(){inspectPoker();const text=String(document.body?.innerText||'').slice(0,4000);const signature=[/WINS/i.test(text),/YOUR TURN/i.test(text),/POT\s*\$?([\d,]+)/i.exec(text)?.[1]||''].join('|');if(signature!==lastAudioSignature){if(signature.startsWith('true'))playWinnerAudio();lastAudioSignature=signature}}
function tick(time=0){scene=window.__SVR_SCENE__||scene;camera=window.__SVR_CAMERA__||camera;renderer=window.__SVR_RENDERER__||renderer;wrapRig();syncSeat('frame');updateEric();if(time-lastSweep>1000){lastSweep=time;cleanupOverlays();hideOldSkeletons()}raf=requestAnimationFrame(tick)}
function qa(){state.checkedAt=new Date().toISOString();return{...state,movementFlags:Object.fromEntries(FLAGS.map(k=>[k,window[k]])),pass:state.installed&&(!state.seated||(state.flagsLocked&&FLAGS.every(k=>window[k]===false)))&&(!state.ericLoaded||state.ericMappedBones>=8)}}
function install(){if(state.installed)return;state.installed=true;state.installedAt=new Date().toISOString();for(const e of ['svr:phase361-table-joined','svr:phase363-table-joined','svr:phase365-table-joined'])window.addEventListener(e,()=>seatLock(e));for(const e of ['svr:phase361-table-left','svr:phase363-table-left','svr:phase365-table-left'])window.addEventListener(e,()=>seatUnlock(e));for(const e of ['svr:poker-state','svr:phase359-hand-start','svr:phase360-hand-start'])window.addEventListener(e,()=>playEric(e));bindAudio();timer=setInterval(()=>{syncSeat('interval');inspectRuntime();if(!eric)loadEric()},420);raf=requestAnimationFrame(tick);window.addEventListener('beforeunload',()=>{clearInterval(timer);cancelAnimationFrame(raf);stopAmbience();audioContext?.close?.()},{once:true})}
install();
window.SVR_PHASE381_SEAT_LOCK=seatLock;window.SVR_PHASE381_SEAT_UNLOCK=seatUnlock;window.SVR_PHASE381_OVERLAY_SWEEP=cleanupOverlays;window.SVR_PHASE381_ALIGN_ERIC=alignEric;window.SVR_PHASE381_PLAY_ERIC=playEric;window.SVR_PHASE381_AUDIO_TOGGLE=toggleAudio;window.SVR_AUDIO_TOGGLE=toggleAudio;window.SVR_TOGGLE_MUSIC=toggleAudio;window.SVR_PHASE381_QA=qa;window.SVR_PHASE381_STATE=state;
