/* PHASE-406-QUEST-SIDE-BURN-CHIP-POLISH-LOCK */
import * as THREE from 'three';
const BUILD='PHASE-406-QUEST-SIDE-BURN-CHIP-POLISH-LOCK';
const state={build:BUILD,sweeps:0,burnRoot:null,burnCards:0,duplicateBurnRootsHidden:0,chipMeshes:0,tableFound:false,lastError:null,checkedAt:null};
const COLORS=new Map([[1,0xf5f5f5],[5,0xc92d3d],[25,0x23854a],[50,0x258dc1],[100,0x15181e],[500,0x7837a8],[1000,0xd5a425],[5000,0xb72645]]);
const tmp=new THREE.Vector3();
function scene(){return window.__SVR_SCENE__||null}
function table(){return window.SVR_TABLE_AUTHORITY||window.SVR_PHASE380_ORIGINAL_TABLE||scene()?.getObjectByName?.('PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED')||null}
function boxFor(object){object?.updateWorldMatrix?.(true,true);return object?new THREE.Box3().setFromObject(object):null}
function worldSet(object,world){if(!object?.parent)return false;const local=world.clone();object.parent.worldToLocal(local);object.position.copy(local);return true}
function burnRoots(){const out=[];scene()?.traverse?.(object=>{const n=String(object.name||'');if(/PHASE334_BURN_AND_TURN_PILE|BURN(?:_AND_TURN)?_(?:PILE|ROOT)|BURN_PILE/i.test(n)&&!/BURN_CARD_/i.test(n))out.push(object)});return out}
function burnCards(root){const out=[];root?.traverse?.(object=>{if(object.isMesh&&/BURN_CARD|BURN.*CARD/i.test(String(object.name||'')))out.push(object)});return out}
function relocateBurn(){const t=table(),roots=burnRoots();if(!t||!roots.length)return false;const box=boxFor(t),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);const preferred=roots.find(x=>x.name==='PHASE334_BURN_AND_TURN_PILE')||roots[0];roots.forEach(root=>{if(root!==preferred){root.visible=false;state.duplicateBurnRootsHidden++}});preferred.visible=true;const cards=burnCards(preferred);const sideX=center.x+Math.max(.62,Math.min(size.x*.31,1.18)),sideZ=center.z-0.07;cards.forEach((card,index)=>{worldSet(card,new THREE.Vector3(sideX,box.max.y+.018+index*.006,sideZ));card.rotation.x=-Math.PI/2;card.rotation.z=index*.045;card.visible=true;card.renderOrder=Math.max(card.renderOrder||0,4060)});state.burnRoot=preferred.name||'burn-root';state.burnCards=cards.length;state.tableFound=true;return true}
function polishChips(){let count=0;scene()?.traverse?.(object=>{if(!object.isMesh)return;const value=Number(object.userData?.value);if(!Number.isFinite(value)||!COLORS.has(value))return;const materials=Array.isArray(object.material)?object.material:[object.material];const next=materials.map(material=>{if(!material)return material;const m=material.userData?.svr406Chip?material:material.clone();m.userData={...(m.userData||{}),svr406Chip:true,denomination:value};if(m.color)m.color.setHex(COLORS.get(value));if('roughness'in m)m.roughness=.43;if('metalness'in m)m.metalness=.12;if(m.emissive)m.emissive.setHex(0x000000);m.needsUpdate=true;return m});object.material=Array.isArray(object.material)?next:next[0];object.userData.phase406ChipColor=true;count++});state.chipMeshes=count;return count}
function sweep(reason='manual'){try{state.duplicateBurnRootsHidden=0;relocateBurn();polishChips();state.sweeps++;state.lastError=null;state.checkedAt=new Date().toISOString();window.SVR_PHASE406_QUEST_TABLE_STATE={...state,reason};return window.SVR_PHASE406_QUEST_TABLE_STATE}catch(e){state.lastError=String(e?.message||e);state.checkedAt=new Date().toISOString();return{...state,reason}}}
window.SVR_PHASE406_QUEST_TABLE_SWEEP=sweep;
window.SVR_PHASE406_QUEST_TABLE_QA=()=>({build:BUILD,...state,onePhysicalBurnRoot:burnRoots().filter(x=>x.visible!==false).length<=1,sideBurnReady:state.tableFound&&state.burnCards>=0,chipPaletteReady:state.chipMeshes>=0,phase396SeatingUntouched:true,phase396TeleportUntouched:true,pass:Boolean(state.tableFound&&!state.lastError),checkedAt:new Date().toISOString()});
window.addEventListener('svr:phase396-core-ready',()=>setTimeout(()=>sweep('phase396-core-ready'),180),{once:true});
setTimeout(()=>sweep('phase406-delayed'),2600);
