import * as THREE from 'three';
const LABEL='PHASE-198-DUPLICATE-LOGO-MOON-CLEANUP-LOCK';
const ROOT='PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_ROOT';
let scene,camera,renderer,root,started=false;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function keepOneLogo(){let logos=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(/logo/i.test(n)&&/floor|circle|carpet|center|lobby|PHASE19/i.test(n))logos.push(o);});let keep=logos.find(o=>/PHASE196_ORIGINAL_LOBBY_LOGO_FULL_CIRCLE|PHASE196_ORIGINAL_LOBBY_LOGO_LOCK/i.test(o.name))||logos.find(o=>/PHASE192_CENTER_LOGO_FILL|PHASE197/i.test(o.name))||logos[0]||null;let hidden=0;logos.forEach(o=>{if(!keep||o===keep||keep.parent===o){o.visible=true;o.traverse?.(c=>c.visible=true);}else{o.visible=false;o.traverse?.(c=>{c.visible=false;if(c.material){c.material.transparent=true;c.material.opacity=0;c.material.needsUpdate=true;}});hidden++;}});return {found:logos.length,kept:keep?.name||null,hidden};}
function keepOneMoon(){let moons=[],mars=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon/i.test(n)&&!/mars/i.test(n))moons.push(o);if(/mars/i.test(n))mars.push(o);});let keep=moons.find(o=>/PHASE196_ROTATING_MOON/i.test(o.name))||moons[0]||null;let hidden=0;moons.forEach(o=>{if(!keep||o===keep||keep.parent===o){o.visible=true;o.traverse?.(c=>c.visible=true);}else{o.visible=false;o.traverse?.(c=>{c.visible=false;if(c.material){c.material.transparent=true;c.material.opacity=0;c.material.needsUpdate=true;}});hidden++;}});mars.forEach(o=>{o.visible=true;o.traverse?.(c=>c.visible=true);});return {moonsFound:moons.length,moonKept:keep?.name||null,moonsHidden:hidden,marsFound:mars.length};}
function suppressUpdate(){let n=0;document.querySelectorAll('div,section,aside,pre').forEach(el=>{const t=(el.textContent||'').toLowerCase();if(/svr update available|update now|available site|reload|build:/i.test(t)&&/update|available/.test(t)){el.style.display='none';el.dataset.phase198Hidden='true';n++;}});return n;}
function removeCenterRails(){let n=0;const r=sr(scene),kill=[];r?.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|watch|hand|teleport|moon|mars|star|camera|light|logo/i.test(nm))return;if(!/rail|rope|stanchion|barrier|banister|handrail|guard|pole|post|fence/i.test(nm))return;const p=new THREE.Vector3();o.getWorldPosition(p);if(Math.hypot(p.x,p.z)<13.5)kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);const logo=keepOneLogo();const moon=keepOneMoon();const popup=suppressUpdate();const rails=removeCenterRails();window.SVR_PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,oneFloorLogo:true,oneMoon:true,logo,moon,popupSuppressed:popup,railsRemoved:rails,checkedAt:iso()};window.SVR_RUN_PHASE198_AUDIT=()=>window.SVR_PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_LOCK;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(()=>{window.SVR_PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_LOCK.logo=keepOneLogo();window.SVR_PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_LOCK.moon=keepOneMoon();window.SVR_PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_LOCK.popupSuppressed=suppressUpdate();window.SVR_PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_LOCK.railsRemoved+=removeCenterRails();window.SVR_PHASE198_DUPLICATE_LOGO_MOON_CLEANUP_LOCK.checkedAt=iso();},900);}return true;}
[250,700,1400,2600,5000,8500].forEach(ms=>setTimeout(install,ms));install();
