import * as THREE from 'three';
const LABEL='PHASE-218-TABLE-PLAY-MODE-WATCH-RESTORE-LOCK';
const ROOT='PHASE218_TABLE_PLAY_MODE_WATCH_ROOT';
let scene,camera,renderer,rootGroup,started=false;
function sr(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function viewCam(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function camPos(){const p=new THREE.Vector3();viewCam()?.getWorldPosition(p);return p;}
function camDir(){const d=new THREE.Vector3();viewCam()?.getWorldDirection(d);if(d.lengthSq()<.001)d.set(0,0,-1);return d.normalize();}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null;}
function table(){const r=sr();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function tableRec(){const t=table();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{obj:t,b,s,c,top:b.max.y};}
function quietTravel(){let n=0;try{window.SVR_PHASE193_TELEPORT_OFF?.();window.SVR_PHASE170_TELEPORT_OFF?.();window.SVR_PHASE184_TELEPORT_OFF?.();}catch(e){}const r=rig();if(r){try{r.setEnabled?.(false);r.setMode?.('table');r.setVisible?.(false);}catch(e){}}
scene?.traverse?.(o=>{const name=String(o.name||'');if(/laser|pointer|ray|arc|target_ring|logo_target|teleport/i.test(name)&&!/watch|table|card|chip|portal/i.test(name)){o.visible=false;if(o.material){o.material.opacity=0;o.material.transparent=true;}n++;}});window.SVR_TABLE_PLAY_TRAVEL_PAUSED=true;return n;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.08,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function box(p,n,pos,s,m){const o=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);o.name=n;o.position.set(pos.x,pos.y,pos.z);o.frustumCulled=false;p.add(o);return o;}
function labelTex(a,b=''){const c=document.createElement('canvas');c.width=768;c.height=256;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.86)';x.fillRect(0,0,768,256);x.strokeStyle='#7ffcff';x.lineWidth=8;x.strokeRect(10,10,748,236);x.fillStyle='#fff';x.font='900 54px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(a,384,90,710);x.fillStyle='#ffd98a';x.font='800 34px system-ui';x.fillText(b,384,165,710);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function makeWatch(){if(rootGroup)rootGroup.parent?.remove(rootGroup);rootGroup=new THREE.Group();rootGroup.name=ROOT;sr().add(rootGroup);const p=camPos(),d=camDir();const right=new THREE.Vector3().crossVectors(d,new THREE.Vector3(0,1,0)).normalize();const pos=p.clone().add(d.clone().multiplyScalar(.72)).add(right.clone().multiplyScalar(-.32));pos.y-=.25;const g=new THREE.Group();g.name='PHASE218_VISIBLE_PLAY_WATCH';g.position.copy(pos);g.lookAt(p);rootGroup.add(g);box(g,'PHASE218_WATCH_BODY',{x:0,y:0,z:0},{x:.42,y:.11,z:.08},mat(0x05070b));box(g,'PHASE218_WATCH_BUTTON_MENU',{x:0,y:.018,z:.046},{x:.34,y:.072,z:.024},basic(0x7ffcff,.86));const m=new THREE.Mesh(new THREE.PlaneGeometry(.5,.18),new THREE.MeshBasicMaterial({map:labelTex('PLAY','TABLE'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.name='PHASE218_WATCH_TEXT';m.position.set(0,.12,.02);m.scale.set(.5,.5,.5);g.add(m);return true;}
function frontPanel(){if(!rootGroup)return;const old=rootGroup.getObjectByName('PHASE218_TABLE_PLAY_PANEL');if(old)old.parent?.remove(old);const p=camPos(),d=camDir();const pos=p.clone().add(d.clone().multiplyScalar(1.35));pos.y-=.06;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1.6,.62),new THREE.MeshBasicMaterial({map:labelTex('TABLE PLAY MODE','travel paused • use hands at table'),transparent:true,depthWrite:false,side:THREE.DoubleSide}));mesh.name='PHASE218_TABLE_PLAY_PANEL';mesh.position.copy(pos);mesh.lookAt(p);rootGroup.add(mesh);}
function seat(){const tb=tableRec();if(!tb||!camera)return null;const innerD=Math.max(.8,Math.min(tb.s.z*.4,1.7));const eye=new THREE.Vector3(tb.c.x,tb.top+1.18,tb.c.z+innerD*1.42);const target=new THREE.Vector3(tb.c.x,tb.top+.08,tb.c.z-innerD*.04);const r=rig();if(renderer?.xr?.isPresenting&&r?.setPlayerPose)r.setPlayerPose(eye.x,0,eye.z);else{camera.position.copy(eye);camera.lookAt(target);}return{eye:{x:+eye.x.toFixed(2),y:+eye.y.toFixed(2),z:+eye.z.toFixed(2)},target:{x:+target.x.toFixed(2),y:+target.y.toFixed(2),z:+target.z.toFixed(2)}};}
function hideSky(){scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon|mars|planet|star|sky|sprite|sparkle|blink|pulse/i.test(n)&&!/teleport|portal|watch|hand|table|card|chip/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);}});scene.background=new THREE.Color(0x030407);scene.fog=null;}
function pass(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera)return null;const quieted=quietTravel();hideSky();makeWatch();frontPanel();const s=seat();const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,tablePlayMode:true,watchVisible:true,largePanelVisible:true,travelPaused:true,quietedTravelVisuals:quieted,seat:s,checkedAt:new Date().toISOString()};window.SVR_PHASE218_TABLE_PLAY_MODE_WATCH_RESTORE_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){const out=pass();window.SVR_RUN_PHASE218_TABLE_PLAY_AUDIT=()=>pass();window.SVR_PHASE218_TABLE_PLAY_MODE=()=>pass();if(!started){started=true;setInterval(pass,900);}return !!out;}
[300,800,1600,3000,6000,9000].forEach(ms=>setTimeout(install,ms));install();
