/* PHASE-393-ANDROID-COMMON-UI-AUDIO-LOCK */
export const BUILD='PHASE-393-ANDROID-PERIMETER-TURN-CLOCK-AUDIO-LOCK';
export const SUITS=['S','H','D','C'],RANKS=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
export const NAMES=['YOU','Claudia','Eric','Maya','Darius','Nova'];
export const FACES=['Y','👩','🧔','👩🏽','👨🏾','👩🏻'];
export const BOT_RANKS=['Bronze','Silver','Rookie II','Gold','Bronze'];
export const TURN_SECONDS=15,SMALL_BLIND=50,BIG_BLIND=100,MIN_RAISE=100;
export const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const initialStack=Number(localStorage.getItem('svr393stack')||localStorage.getItem('svr392stack')||15000);
const initialXp=Number(localStorage.getItem('svr393xp')||localStorage.getItem('svr392xp')||0);
export const state={build:BUILD,joined:false,hand:0,dealer:-1,street:0,pot:0,deck:[],burns:[],community:[],players:[],currentBet:0,handOver:false,activePlayer:null,turnSeconds:TURN_SECONDS,turnInterval:0,botTimer:0,autoTimer:0,xp:initialXp,stack:initialStack,raiseTarget:500,lastWinner:null,soundEnabled:localStorage.getItem('svr393sound')!=='off',audioReady:false,release:null,lastError:null,checkedAt:null};
const tiers=[{name:'ROOKIE I',min:0},{name:'ROOKIE II',min:250},{name:'BRONZE',min:600},{name:'SILVER',min:1200},{name:'GOLD',min:2200},{name:'PLATINUM',min:3600},{name:'DIAMOND',min:5500},{name:'SVR ELITE',min:8000}];
let audio=null,noiseBuffer=null;
export const money=n=>`$${Math.max(0,Math.round(n||0)).toLocaleString()}`;
export const streetName=()=>['PRE-FLOP','FLOP','TURN','RIVER','SHOWDOWN'][state.street]||'TABLE';
export const currentRank=()=>[...tiers].reverse().find(t=>state.xp>=t.min)||tiers[0];
const nextRank=()=>tiers.find(t=>t.min>state.xp)?.min||Math.max(10000,state.xp+2000);
const symbol=s=>({S:'♠',H:'♥',D:'♦',C:'♣'}[s]);
export function vibration(pattern){try{navigator.vibrate?.(pattern)}catch{}}
function unlock(){if(!state.soundEnabled)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio ||= new AC();if(audio.state==='suspended')audio.resume().catch(()=>{});if(!noiseBuffer){noiseBuffer=audio.createBuffer(1,Math.floor(audio.sampleRate*.18),audio.sampleRate);const d=noiseBuffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length)}state.audioReady=true}
function tone(f=440,d=.08,v=.035,type='sine',delay=0,end=null){if(!state.soundEnabled)return;unlock();if(!audio)return;const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+d+.02)}
function noise(d=.06,v=.025,delay=0){if(!state.soundEnabled)return;unlock();if(!audio||!noiseBuffer)return;const t=audio.currentTime+delay,s=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain();s.buffer=noiseBuffer;f.type='highpass';f.frequency.value=750;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);s.connect(f).connect(g).connect(audio.destination);s.start(t);s.stop(t+d+.02)}
export function sound(name){if(!state.soundEnabled)return;if(name==='deal'){noise(.055,.028);tone(860,.045,.018,'triangle',0,520)}else if(name==='chip'){tone(920,.06,.025);tone(1260,.045,.018,'triangle',.035)}else if(name==='raise'){tone(380,.08,.025,'square');tone(590,.1,.025,'triangle',.07)}else if(name==='fold'){noise(.12,.02);tone(170,.12,.018,'sawtooth',0,70)}else if(name==='check')tone(620,.045,.018,'triangle');else if(name==='turn')tone(760,.07,.026);else if(name==='timer')tone(980,.055,.025,'square');else if(name==='burn'){noise(.09,.022);tone(240,.08,.014,'triangle')}else if(name==='win')[523,659,784,1047].forEach((f,i)=>tone(f,.28,.035,'triangle',i*.09));else if(name==='lose')tone(280,.18,.025,'sine',0,150)}
export function updateSoundButtons(){const text=state.soundEnabled?'SOUND ON':'SOUND OFF';['#soundToggle','#soundGate'].forEach(s=>{const el=$(s);if(el)el.textContent=text})}
export function toggleSound(){state.soundEnabled=!state.soundEnabled;localStorage.setItem('svr393sound',state.soundEnabled?'on':'off');updateSoundButtons();if(state.soundEnabled){unlock();sound('turn')}}
export function profile(){try{const raw=JSON.parse(localStorage.getItem('svr_demo_account')||'{}'),name=raw?.profile?.displayName||raw?.displayName||'YOU';$('#userName').textContent=name;NAMES[0]=name;const initials=(name.match(/\b\w/g)||['Y']).slice(0,2).join('').toUpperCase();$('#userAvatar').textContent=initials;FACES[0]=initials}catch{}}
export function rankLabel(){const rank=currentRank(),next=nextRank(),span=Math.max(1,next-rank.min);$('#rankText').textContent=`${rank.name} • ${state.xp} XP`;$('#xpFill').style.width=`${Math.max(0,Math.min(100,(state.xp-rank.min)/span*100))}%`}
export function makeDeck(){return SUITS.flatMap(s=>RANKS.map((r,i)=>({r,s,v:i+2})))}
export function shuffle(cards){for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
function cardHtml(card,hidden=false,small=false){if(hidden)return `<span class="card back${small?' small':''}"><img src="/logo.png" alt="SVR card back"></span>`;const red=card.s==='H'||card.s==='D';return `<span class="card${red?' red':''}${small?' small':''}"><span class="rank">${card.r}</span><span class="suit">${symbol(card.s)}</span></span>`}
function renderCards(){if(!state.players[0])return;$('#hole').innerHTML=state.players[0].cards.map(c=>cardHtml(c)).join('');$('#community').innerHTML=[0,1,2,3,4].map(i=>state.community[i]?cardHtml(state.community[i]):'<span class="card back placeholder"><img src="/logo.png" alt=""></span>').join('')}
function renderPlayers(){const host=$('#players');host.textContent='';state.players.slice(1).forEach(p=>{const box=document.createElement('article');box.className=`player-box${p.folded?' folded':''}${p.button?' button':''}${p.active?' active':''}${state.lastWinner===p.index?' winner':''}`;box.dataset.player=String(p.index);box.dataset.seat=String(p.index);if(p.index===2)box.style.setProperty('--seat-transform','translateX(-50%)');const visible=state.handOver&&!p.folded;box.innerHTML=`<div class="face">${FACES[p.index]}</div><div class="player-meta"><strong>${p.name}${p.button?' • D':''}</strong><span>${p.rank} • ${money(p.stack)}</span></div>${p.active?`<span class="turn-badge">${state.turnSeconds}</span>`:''}<div class="player-action">${p.lastAction||'WAITING'}</div><div class="player-cards">${p.cards.map(c=>cardHtml(c,!visible,true)).join('')}</div>`;host.appendChild(box)})}
export function updateRaiseControls(){const p=state.players[0],slider=$('#raiseSlider'),panel=$('#raisePanel');if(!p||!slider)return;const max=Math.max(0,p.streetBet+p.stack),min=Math.min(max,Math.max(state.currentBet+MIN_RAISE,p.streetBet+MIN_RAISE));slider.min=String(Math.max(MIN_RAISE,min));slider.max=String(Math.max(min,max));slider.step='100';if(state.raiseTarget<min||state.raiseTarget>max)state.raiseTarget=Math.min(max,Math.max(min,state.currentBet+Math.max(MIN_RAISE,Math.floor(state.pot/2/100)*100)));slider.value=String(state.raiseTarget);$('#raiseAmount').textContent=money(state.raiseTarget);const active=state.activePlayer===0&&!state.handOver&&!p.folded&&p.stack>0;panel.classList.toggle('disabled',!active);slider.disabled=!active}
export function render(){const p=state.players[0];$('#stack').textContent=`STACK ${money(p?.stack??state.stack)}`;$('#pot').textContent=money(state.pot);$('#handCounter').textContent=`HAND ${state.hand}`;$('#turnClock').textContent=String(state.turnSeconds);$('#turnClock').classList.toggle('warning',state.turnSeconds<=5&&state.activePlayer!==null&&!state.handOver);rankLabel();renderCards();renderPlayers();updateRaiseControls();const call=Math.max(0,state.currentBet-(p?.streetBet||0));$('[data-a="call"]').textContent=call?`CALL ${money(call)}`:'CHECK';$('[data-a="raise"]').textContent=`RAISE ${money(state.raiseTarget)}`;const can=state.activePlayer===0&&!state.handOver&&!p?.folded&&p?.stack>0;all('.actions button').forEach(b=>{b.disabled=!can;b.classList.toggle('valid',can)})}
export function setStatus(text,win=false){$('#status').textContent=text;$('#status').style.color=win?'var(--green)':''}
export function tableMessage(text){$('#tableMessage').textContent=text}
export function clearTurnTimers(){clearInterval(state.turnInterval);clearTimeout(state.botTimer);state.turnInterval=0;state.botTimer=0}
export const elementForPlayer=index=>index===0?$('.profile-pill'):$(`[data-player="${index}"]`);
export function flyChips(from,to,count=7){if(!from||!to)return;const a=from.getBoundingClientRect(),b=to.getBoundingClientRect();for(let i=0;i<count;i++){const chip=document.createElement('i');chip.className='chip-flight';chip.style.left=`${a.left+a.width/2+(Math.random()-.5)*18}px`;chip.style.top=`${a.top+a.height/2+(Math.random()-.5)*14}px`;chip.style.setProperty('--tx',`${b.left+b.width/2+(Math.random()-.5)*20}px`);chip.style.setProperty('--ty',`${b.top+b.height/2+(Math.random()-.5)*14}px`);chip.style.animationDelay=`${i*35}ms`;$('#chipLayer').appendChild(chip);setTimeout(()=>chip.remove(),1000)}}
export function confetti(){const colors=['#7ffcff','#ffd98a','#9b4dff','#8dffb4','#ff6289'];for(let i=0;i<46;i++){const x=document.createElement('i');x.className='confetti';x.style.left=`${50+(Math.random()-.5)*18}%`;x.style.top=`${42+(Math.random()-.5)*10}%`;x.style.setProperty('--c',colors[i%colors.length]);x.style.setProperty('--dx',`${(Math.random()-.5)*540}px`);x.style.setProperty('--dy',`${120+Math.random()*440}px`);x.style.animationDelay=`${Math.random()*180}ms`;$('#fxLayer').appendChild(x);setTimeout(()=>x.remove(),1900)}}
export function awardXp(amount,reason){state.xp+=amount;localStorage.setItem('svr393xp',String(state.xp));rankLabel();$('#winnerBanner').innerHTML+=`<div style="margin-top:5px;color:#ffd98a">+${amount} XP • ${reason}</div>`}
export function post(p,amount,label='BET'){const pay=Math.max(0,Math.min(p.stack,Math.round(amount)));p.stack-=pay;p.streetBet=(p.streetBet||0)+pay;state.pot+=pay;if(p.stack===0)p.allIn=true;if(p.index===0)state.stack=p.stack;if(pay>0){p.lastAction=`${label} ${money(pay)}`;sound('chip');flyChips(elementForPlayer(p.index),$('#potTarget'),Math.min(10,4+Math.ceil(pay/300)))}return pay}
export function burn(label){const c=state.deck.pop();if(c)state.burns.push(c);$('#burnLabel').textContent=`BURN ${state.burns.length} • ${label}`;sound('burn');$('#deckCard').animate([{transform:'translateX(0)'},{transform:'translateX(-28px) rotate(-14deg)'},{transform:'translateX(0)'}],{duration:420})}
export function reveal(count,label){burn(label);for(let i=0;i<count;i++){const c=state.deck.pop();if(c)state.community.push(c)}render();all('#community .card').slice(-count).forEach((card,i)=>{card.animate([{transform:'translateY(-18px) rotateY(90deg)',opacity:.2},{transform:'translateY(0)',opacity:1}],{duration:420,delay:i*100});setTimeout(()=>sound('deal'),i*100)})}
export function configureSponsors(){const config=window.SVR_ANDROID_SPONSORS||[{name:'SVR POKER',logo:'/logo.png'},{name:'SPONSOR OPEN',logo:'/logo.png'}];[['#sponsorLeft',config[0]],['#sponsorRight',config[1]||config[0]]].forEach(([s,x])=>{const zone=$(s);if(!zone||!x)return;zone.querySelector('img').src=x.logo||'/logo.png';zone.querySelector('span').textContent=x.name||'SPONSOR';if(x.href){zone.style.cursor='pointer';zone.onclick=()=>window.open(x.href,'_blank','noopener')}})}
export async function checkRelease(){try{const response=await fetch(`/game/android-release.json?t=${Date.now()}`,{cache:'no-store'});state.release=await response.json();$('#gateStatus').textContent=`Web table ${state.release.currentGameBuild||BUILD}. APK ${state.release.apkVersionName||'RC2'} remains manual-update only.`}catch(error){state.lastError=String(error?.message||error)}}
export const audioAvailable=()=>Boolean(audio||state.soundEnabled);
