import * as THREE from 'three';
const LABEL='PHASE-186-BALCONY-SAFETY-TELEPORT-LOCK';
const ROOT='PHASE186_BALCONY_SAFETY_TELEPORT_ROOT';
const SECOND=3.15,EYE=1.62;
const ROOM={minX:-13.35,maxX:13.35,minZ:-10.45,maxZ:9.25};
const WALK=1.95;
const STAIR={cx:-10.95,cz:5.95,r:2.2,start:Math.PI,end:Math.PI*1.52,n:16,w:1.85};
let scene,camera,renderer,started=false,patched=false,lastY=null,lastMove=null;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=.18){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function add(parent,n,p,s,visible=false){const m=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),mat(0x7ffcff,visible?.16:.01));m.name=n;m.position.set(p.x,p.y,p.z);m.visible=!!visible;parent.add(m);return m;}
function build(root){const old=root.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);const g=new THREE.Group();g.name=ROOT;root.add(g);add(g,'PHASE186_WEST_WALKWAY_UNDERLAY_NO_GAP',{x:ROOM.minX+WALK/2,y:SECOND-.205,z:(ROOM.minZ+ROOM.maxZ)/2},{x:WALK+.42,y:.10,z:ROOM.maxZ-ROOM.minZ+.5});add(g,'PHASE186_NORTH_WALKWAY_UNDERLAY_NO_GAP',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND-.205,z:ROOM.minZ+WALK/2},{x:ROOM.maxX-ROOM.minX+.5,y:.10,z:WALK+.42});add(g,'PHASE186_EAST_WALKWAY_UNDERLAY_NO_GAP',{x:ROOM.maxX-WALK/2,y:SECOND-.205,z:(ROOM.minZ+ROOM.maxZ)/2},{x:WALK+.42,y:.10,z:ROOM.maxZ-ROOM.minZ+.5});add(g,'PHASE186_SOUTH_WALKWAY_UNDERLAY_NO_GAP',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND-.205,z:ROOM.maxZ-WALK/2},{x:ROOM.maxX-ROOM.minX+.5,y:.10,z:WALK+.42});for(let i=0;i<STAIR.n;i++){const p=i/(STAIR.n-1),a=STAIR.start+(STAIR.end-STAIR.start)*p,x=STAIR.cx+Math.cos(a)*STAIR.r,z=STAIR.cz+Math.sin(a)*STAIR.r,h=SECOND*p;const m=add(g,`PHASE186_CURVED_STAIR_SAFE_UNDERLAY_${i+1}`,{x,y:h-.06,z},{x:STAIR.w+.38,y:.08,z:.95});m.rotation.y=-a+Math.PI/2;}add(g,'PHASE186_WEST_BALCONY_INNER_EDGE_BLOCK',{x:ROOM.minX+WALK+.32,y:SECOND+.55,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.18,y:1.3,z:ROOM.maxZ-ROOM.minZ-1.0});add(g,'PHASE186_NORTH_BALCONY_INNER_EDGE_BLOCK',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND+.55,z:ROOM.minZ+WALK+.32},{x:ROOM.maxX-ROOM.minX-1.0,y:1.3,z:.18});add(g,'PHASE186_EAST_BALCONY_INNER_EDGE_BLOCK',{x:ROOM.maxX-WALK-.32,y:SECOND+.55,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.18,y:1.3,z:ROOM.maxZ-ROOM.minZ-1.0});add(g,'PHASE186_SOUTH_BALCONY_INNER_EDGE_BLOCK',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND+.55,z:ROOM.maxZ-WALK-.32},{x:ROOM.maxX-ROOM.minX-1.0,y:1.3,z:.18});return true;}
function stairHeight(x,z){let best=99,prog=0;for(let i=0;i<STAIR.n;i++){const p=i/(STAIR.n-1),a=STAIR.start+(STAIR.end-STAIR.start)*p,sx=STAIR.cx+Math.cos(a)*STAIR.r,sz=STAIR.cz+Math.sin(a)*STAIR.r,d=Math.hypot(x-sx,z-sz);if(d<best){best=d;prog=p;}}if(best<1.25)return SECOND*prog;return null;}
function walkHeight(x,z){const sh=stairHeight(x,z);if(sh!==null)return sh;const west=x>=ROOM.minX&&x<=ROOM.minX+WALK+.25&&z>=ROOM.minZ&&z<=ROOM.maxZ;const north=z>=ROOM.minZ&&z<=ROOM.minZ+WALK+.25&&x>=ROOM.minX&&x<=ROOM.maxX;const east=x<=ROOM.maxX&&x>=ROOM.maxX-WALK-.25&&z>=ROOM.minZ&&z<=ROOM.maxZ;const south=z<=ROOM.maxZ&&z>=ROOM.maxZ-WALK-.25&&x>=ROOM.minX&&x<=ROOM.maxX;if(west||north||east||south)return SECOND;return 0;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function nearestWalk(x,z){const choices=[];choices.push({x:ROOM.minX+WALK/2,z:clamp(z,ROOM.minZ,ROOM.maxZ),d:Math.abs(x-(ROOM.minX+WALK/2))});choices.push({x:ROOM.maxX-WALK/2,z:clamp(z,ROOM.minZ,ROOM.maxZ),d:Math.abs(x-(ROOM.maxX-WALK/2))});choices.push({x:clamp(x,ROOM.minX,ROOM.maxX),z:ROOM.minZ+WALK/2,d:Math.abs(z-(ROOM.minZ+WALK/2))});choices.push({x:clamp(x,ROOM.minX,ROOM.maxX),z:ROOM.maxZ-WALK/2,d:Math.abs(z-(ROOM.maxZ-WALK/2))});choices.sort((a,b)=>a.d-b.d);return choices[0];}
function patchRig(){const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;if(!rig||patched||typeof rig.setPlayerPose!=='function')return false;const base=rig.setPlayerPose.bind(rig);rig.setPlayerPose=(x,y,z)=>{let nx=clamp(Number(x)||0,ROOM.minX,ROOM.maxX),nz=clamp(Number(z)||0,ROOM.minZ,ROOM.maxZ),ny=Number(y)||0;if(ny>2.2){const h=walkHeight(nx,nz);if(h<2.2){const n=nearestWalk(nx,nz);nx=n.x;nz=n.z;ny=SECOND;}else ny=h;}else ny=walkHeight(nx,nz)>2.2?SECOND:0;lastMove={build:LABEL,approved:{x:+nx.toFixed(3),y:+ny.toFixed(3),z:+nz.toFixed(3)},checkedAt:iso()};window.SVR_PHASE186_LAST_SAFE_TELEPORT=lastMove;return base(nx,ny,nz);};patched=true;return true;}
function camPos(){const p=new THREE.Vector3();if(renderer?.xr?.isPresenting)renderer.xr.getCamera(camera).getWorldPosition(p);else camera?.getWorldPosition(p);return p;}
function tick(){if(!camera||!renderer)return;const p=camPos(),h=walkHeight(p.x,p.z);if(renderer.xr?.isPresenting){const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;const gy=p.y-EYE;if(rig?.setPlayerPose&&Math.abs(gy-h)>.18&&lastY!==h){lastY=h;rig.setPlayerPose(p.x,h,p.z);}}else{camera.position.y+=(h+EYE-camera.position.y)*.16;}window.SVR_PHASE186_BALCONY_SAFETY_TELEPORT_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,noGapUnderlay:true,edgeBlocks:true,teleportPatched:patched,currentFloorY:+h.toFixed(3),lastMove,checkedAt:iso()};}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;build(sr(scene));patchRig();window.SVR_RUN_PHASE186_SAFETY_AUDIT=()=>window.SVR_PHASE186_BALCONY_SAFETY_TELEPORT_LOCK;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(()=>{patchRig();tick();},70);}tick();return true;}
[300,900,1800,3500,7000,11000].forEach(ms=>setTimeout(install,ms));install();
