import * as THREE from 'three';
const LABEL='PHASE-323-TABLE-RESTING-POINT-ALIGNMENT-LOCK';
const ROOT='PHASE323_TABLE_RESTING_POINT_ROOT';
let scene,rootGroup,started=false,restOffset=.18;
function sr(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function table(){const r=sr();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||r?.getObjectByName?.('PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED')||null;}
function bounds(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c};}
function hideOld(){let n=0;sr()?.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE214_|PHASE215_TABLE_GEOMETRY|PHASE215_PLAYER_CARD|PHASE215_CENTER_CHIPS|PHASE215_INNER_CHIPS|PHASE215_HIGH_|PHASE168_DEMO_CARD|PHASE168_.*CHIP|TABLE_STATUS_FLOATING/i.test(nm)){o.visible=false;o.traverse?.(x=>x.visible=false);n++;}});return n;}
function detectRestY(t,bb){let best=null;t.traverse?.(o=>{if(!o.isMesh)return;const n=String(o.name||'').toLowerCase();if(!/(felt|cloth|surface|inner|top|tabletop|play)/.test(n))return;try{const q=bounds(o);if(q.s.x>.8&&q.s.z>.45){const y=q.b.max.y+.012;if(best===null||y<best)best=y;}}catch{}});if(best!==null&&Number.isFinite(best))return best;const off=window.SVR_TABLE_REST_OFFSET??restOffset;return Math.max(bb.b.min.y+bb.s.y*.45,bb.b.max.y-Math.min(.32,Math.max(.10,off)));}
function tex(r,s){const c=document.createElement('canvas');c.width=256;c.height=360;const x=c.getContext('2d');x.fillStyle='#f8f4e7';x.fillRect(0,0,256,360);x.strokeStyle='#151515';x.lineWidth=10;x.strokeRect(10,10,236,340);x.fillStyle=(s==='H'||s==='D')?'#b3142c':'#111';x.font='900 66px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(r,128,128);x.font='900 72px system-ui';x.fillText({S:'♠',H:'♥',D:'♦',C:'♣'}[s]||s,128,224);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function card(n,x,y,z,r,s){const m=new THREE.Mesh(new THREE.PlaneGeometry(.29,.40),new THREE.MeshBasicMaterial({map:tex(r,s),side:THREE.DoubleSide,depthWrite:false}));m.name=n;m.position.set(x,y+.018,z);m.rotation.x=-Math.PI/2;m.renderOrder=3230;rootGroup.add(m);return m;}
function chipStack(n,x,y,z,color,count=6){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.015,32),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.16}));m.name=`${n}_${i}`;m.position.set(x,y+.018+i*.016,z);m.renderOrder=3231;rootGroup.add(m);}}
function label(n,x,y,z,a){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');g.fillStyle='rgba(0,0,0,.62)';g.fillRect(0,0,512,128);g.strokeStyle='#7ffcff';g.lineWidth=4;g.strokeRect(8,8,496,112);g.fillStyle='#fff';g.font='900 34px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(a,256,64,470);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(.9,.22),new THREE.MeshBasicMaterial({map:t,transparent:true,side:THREE.DoubleSide,depthWrite:false}));m.name=n;m.position.set(x,y,z);m.rotation.x=-.18;m.renderOrder=3232;rootGroup.add(m);}
function build(){scene=window.__SVR_SCENE__;if(!scene)return null;const r=sr(),t=table();if(!t)return null;hideOld();const old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);rootGroup=new THREE.Group();rootGroup.name=ROOT;r.add(rootGroup);const bb=bounds(t),c=bb.c,restY=detectRestY(t,bb),w=Math.max(2.8,Math.min(bb.s.x*.54,3.75)),d=Math.max(1.35,Math.min(bb.s.z*.46,2.08));const clampX=x=>Math.max(c.x-w*.46,Math.min(c.x+w*.46,x));const clampZ=z=>Math.max(c.z-d*.46,Math.min(c.z+d*.46,z));[['A','S',-.52,-.08],['K','H',-.26,-.08],['Q','D',0,-.08],['J','C',.26,-.08],['10','S',.52,-.08]].forEach(([ra,su,x,z],i)=>card(`PHASE323_SURFACE_COMMUNITY_CARD_${i}`,clampX(c.x+x),restY,clampZ(c.z+z),ra,su));card('PHASE323_SURFACE_PLAYER_CARD_1',clampX(c.x-.16),restY,clampZ(c.z+d*.33),'9','H');card('PHASE323_SURFACE_PLAYER_CARD_2',clampX(c.x+.16),restY,clampZ(c.z+d*.33),'9','C');chipStack('PHASE323_SURFACE_CENTER_POT',c.x,restY,clampZ(c.z+d*.13),0xffd98a,8);const seats=[['YOU',0,d*.54,0x7ffcff],['NOVA',-w*.42,d*.33,0xff5b8c],['ROOK',-w*.45,-d*.12,0xffd98a],['ACE',0,-d*.50,0x8dffb4],['VEGA',w*.45,-d*.12,0xa77cff],['IVY',w*.42,d*.33,0xff8bd1]];seats.forEach(([name,x,z,color],i)=>{const px=clampX(c.x+x),pz=clampZ(c.z+z);chipStack(`PHASE323_SURFACE_CHIPS_${name}`,px,restY,pz,color,i?4:6);});label('PHASE323_RESTING_POINT_LABEL',c.x,restY+.34,clampZ(c.z-d*.54),'RESTING POINT LOCKED');const out={build:LABEL,active:true,table:t.name,restY:+restY.toFixed(3),tableBounds:{minY:+bb.b.min.y.toFixed(3),maxY:+bb.b.max.y.toFixed(3),height:+bb.s.y.toFixed(3)},innerW:+w.toFixed(3),innerD:+d.toFixed(3),oldHidden:hideOld(),siteTouched:false,checkedAt:new Date().toISOString()};window.SVR_TABLE_RESTING_POINT_STATE=out;window.SVR_PHASE323=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function run(){return build();}
function install(){scene=window.__SVR_SCENE__;if(!scene)return false;window.SVR_RUN_TABLE_RESTING_POINT_LOCK=run;window.SVR_SET_TABLE_REST_OFFSET=(v=.18)=>{window.SVR_TABLE_REST_OFFSET=Number(v)||.18;return build();};const out=build();if(!started){started=true;setInterval(()=>{hideOld();if(!rootGroup||!rootGroup.parent)build();},900);}const s=document.getElementById('status')||document.getElementById('safeStatus');if(s)s.textContent='Phase 323 table resting point aligned';return !!out;}
[300,800,1500,2600,4200,7000,11000].forEach(ms=>setTimeout(install,ms));install();