/* PHASE-405-MOBILE-VOX-VOICE-LOCK */
const BUILD='PHASE-405-MOBILE-VOX-VOICE-LOCK';
const state={build:BUILD,mode:localStorage.getItem('svr405_voice_mode')||'ptt',threshold:Number(localStorage.getItem('svr405_vox_threshold')||0.09),ready:false,active:false,talking:false,level:0,lastError:null};
const $=s=>document.querySelector(s);let stream=null,ctx=null,analyser=null,frame=0,below=0;
function signal(on){const mic=$('#phase399MicButton');if(!mic)return false;if(on&&!state.talking){state.talking=true;mic.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true}))}else if(!on&&state.talking){state.talking=false;mic.dispatchEvent(new PointerEvent('pointerup',{bubbles:true}))}return true}
function status(){const el=$('#phase405VoiceStatus'),match=window.SVR_PHASE399_MATCH_STATE||{};if(!el)return;if(state.mode==='vox')el.textContent=`VOX ${state.talking?'TRANSMITTING':'LISTENING'} • ${match.voiceConnected?'PEER CONNECTED':'NO LIVE PEER'}`;else if(state.mode==='mute')el.textContent='VOICE MUTED';else el.textContent=`PUSH TO TALK • ${match.voiceConnected?'PEER CONNECTED':'NO LIVE PEER'}`}
function buttons(){document.querySelectorAll('[data-voice405]').forEach(b=>b.classList.toggle('active',b.dataset.voice405===state.mode));status()}
async function stop(){cancelAnimationFrame(frame);frame=0;signal(false);try{stream?.getTracks()?.forEach(t=>t.stop())}catch{}try{await ctx?.close?.()}catch{}stream=null;ctx=null;analyser=null;state.active=false;state.level=0;buttons()}
async function startVox(){if(!navigator.mediaDevices?.getUserMedia){state.lastError='Microphone API unavailable';return false}try{await stop();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});const C=window.AudioContext||window.webkitAudioContext;ctx=new C();analyser=ctx.createAnalyser();analyser.fftSize=512;ctx.createMediaStreamSource(stream).connect(analyser);state.ready=true;state.active=true;state.mode='vox';localStorage.setItem('svr405_voice_mode','vox');const data=new Uint8Array(analyser.fftSize);const loop=()=>{if(!state.active)return;analyser.getByteTimeDomainData(data);let sum=0;for(const v of data){const x=(v-128)/128;sum+=x*x}state.level=Math.sqrt(sum/data.length);if(state.level>=state.threshold){below=0;signal(true)}else if(state.talking){below||=performance.now();if(performance.now()-below>260)signal(false)}const meter=$('#phase405VoiceMeter i');if(meter)meter.style.width=`${Math.min(100,state.level*520)}%`;status();frame=requestAnimationFrame(loop)};loop();buttons();return true}catch(e){state.lastError=String(e?.message||e);state.active=false;status();return false}}
async function setMode(mode){if(mode==='vox'){await startVox();return}await stop();state.mode=mode;localStorage.setItem('svr405_voice_mode',mode);buttons()}
function ensureUi(){const footer=$('.footer');if(!footer)return false;if(!$('#phase405VoiceSheet'))document.body.insertAdjacentHTML('beforeend',`<section id="phase405VoiceSheet" class="phase405-sheet hide"><div class="phase405-sheet-head"><h2>Voice / VOX</h2><button data-closevoice405>HIDE</button></div><div class="phase405-voice-row"><button data-voice405="ptt">PUSH TO TALK</button><button data-voice405="vox">VOX</button><button data-voice405="mute">MUTE</button></div><div id="phase405VoiceMeter" class="phase405-meter"><i></i></div><label class="phase405-note">VOX sensitivity<input id="phase405VoxThreshold" class="phase405-threshold" type="range" min="0.03" max="0.24" step="0.01" value="${state.threshold}"></label><p id="phase405VoiceStatus" class="phase405-note"></p><p class="phase405-note">VOX controls the existing WebRTC microphone button. It only transmits to another player after a real peer connection exists.</p></section>`);if(!$('#phase405VoiceButton')){const b=document.createElement('button');b.id='phase405VoiceButton';b.type='button';b.className='phase405-footer-button';b.textContent='VOICE';b.onclick=()=>{$('#phase405VoiceSheet')?.classList.remove('hide');buttons()};footer.appendChild(b)}document.querySelectorAll('[data-closevoice405]').forEach(b=>b.onclick=()=>$('#phase405VoiceSheet')?.classList.add('hide'));document.querySelectorAll('[data-voice405]').forEach(b=>b.onclick=()=>setMode(b.dataset.voice405));const r=$('#phase405VoxThreshold');if(r&&!r.dataset.wired){r.dataset.wired='1';r.oninput=()=>{state.threshold=Number(r.value);localStorage.setItem('svr405_vox_threshold',String(state.threshold))}}buttons();return true}
function poll(){ensureUi();status()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{poll();setInterval(poll,500)},{once:true});else{poll();setInterval(poll,500)}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.active)stop()});window.SVR_PHASE405_VOX_QA=()=>({build:BUILD,mode:state.mode,ready:state.ready,active:state.active,threshold:state.threshold,voiceButton:Boolean($('#phase405VoiceButton')),existingWebRtcClient:Boolean(window.SVR_PHASE399_MATCH_QA),livePeer:Boolean(window.SVR_PHASE399_MATCH_STATE?.voiceConnected),lastError:state.lastError,pass:Boolean($('#phase405VoiceButton')&&$('#phase399MicButton')),checkedAt:new Date().toISOString()});