/* PHASE-388-TABLE-MATERIAL-VISIBILITY-GUARD */
import * as THREE from 'three';
export const BUILD='PHASE-388-TABLE-MATERIAL-VISIBILITY-GUARD';
const p=new URLSearchParams(location.search),ACTIVE=p.get('platform')==='quest'||p.get('direct')==='1'||/Quest|Oculus|Meta Quest/i.test(navigator.userAgent||'');
const state={build:BUILD,active:ACTIVE,installed:false,tableFound:false,visibleMeshes:0,materialsCorrected:0,texturesPreserved:0,lastError:null,checkedAt:null};
let scene,table,timer=0;
function walk(root,fn,limit=16000){const stack=root?[root]:[],seen=new Set();while(stack.length&&seen.size<limit){const o=stack.pop();if(!o||seen.has(o))continue;seen.add(o);try{fn(o)}catch{}for(const c of o.children||[])if(c&&!seen.has(c))stack.push(c)}}
function box(o){o?.updateWorldMatrix?.(true,true);const b=new THREE.Box3().setFromObject(o,true);return{box:b,size:b.getSize(new THREE.Vector3()),center:b.getCenter(new THREE.Vector3())}}
function valid(v){return !!v&&!v.box.isEmpty()&&v.size.x>1.2&&v.size.z>.65}
function findTable(){for(const o of [window.SVR_TABLE_AUTHORITY,window.SVR_PHASE380_ORIGINAL_TABLE,scene?.getObjectByName?.('PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY'),scene?.getObjectByName?.('PHASE373_VISIBLE_TABLE_GLB_AUTHORITY'),table]){if(!o?.isObject3D)continue;try{if(valid(box(o)))return o}catch{}}return null}
function luminance(color){return color?.isColor ? .2126*color.r+.7152*color.g+.0722*color.b : 0}
function classify(label,yRatio){const n=String(label||'').toLowerCase();if(/felt|cloth|baize|surface|playing|tabletop|top/.test(n)||yRatio>.78)return'felt';if(/metal|chrome|steel|frame|leg|base/.test(n)||yRatio<.38)return'metal';return'rail'}
function materialFor(source,kind){const m=source?.clone?.()||new THREE.MeshStandardMaterial();m.userData={...(m.userData||{}),svrPhase388TableVisible:true};m.visible=true;m.transparent=false;m.opacity=1;m.depthTest=true;m.depthWrite=true;m.colorWrite=true;m.side=THREE.DoubleSide;if(m.map?.image){m.map.colorSpace=THREE.SRGBColorSpace;m.map.needsUpdate=true;m.color?.setHex?.(0xffffff);state.texturesPreserved++;}else{const current=luminance(m.color);if(kind==='felt')m.color?.setHex?.(0x35104f);else if(kind==='metal')m.color?.setHex?.(0x51465a);else if(current<.09)m.color?.setHex?.(0x34263f);else m.color?.lerp?.(new THREE.Color(0x4a3657),.28)}if('roughness'in m)m.roughness=kind==='felt' ? .88 : kind==='metal' ? .34 : .52;if('metalness'in m)m.metalness=kind==='felt' ? 0 : kind==='metal' ? .32 : .08;if('emissive'in m){m.emissive.setHex(kind==='felt'?0x10051a:0x08060b);m.emissiveIntensity=kind==='felt' ? .18 : .08}m.needsUpdate=true;state.materialsCorrected++;return m}
function polish(){scene=window.__SVR_SCENE__||scene;table=findTable()||table;if(!table)return false;const whole=box(table);if(!valid(whole))return false;let meshes=0;walk(table,o=>{o.visible=true;if(!o?.isMesh||!o.material)return;meshes++;o.frustumCulled=false;o.castShadow=false;o.receiveShadow=true;const local=box(o),ratio=whole.size.y>.001?(local.center.y-whole.box.min.y)/whole.size.y:.5,list=Array.isArray(o.material)?o.material:[o.material],next=list.map(src=>src?.userData?.svrPhase388TableVisible?src:materialFor(src,classify(`${o.name||''} ${src?.name||''}`,ratio)));o.material=Array.isArray(o.material)?next:next[0]},12000);state.tableFound=true;state.visibleMeshes=Math.max(state.visibleMeshes,meshes);state.checkedAt=new Date().toISOString();return true}
function install(){if(!ACTIVE||state.installed)return;state.installed=true;timer=setInterval(polish,900);window.addEventListener('beforeunload',()=>clearInterval(timer),{once:true});polish()}
install();
window.SVR_PHASE388_TABLE_MATERIAL_SWEEP=polish;window.SVR_PHASE388_TABLE_MATERIAL_QA=()=>({...state,pass:state.installed&&state.tableFound&&state.visibleMeshes>0&&state.materialsCorrected>0,checkedAt:new Date().toISOString()});window.SVR_PHASE388_TABLE_MATERIAL_STATE=state;
