/* PHASE-405-FIVE-HOUR-TOURNAMENT-SCHEDULE-LOCK */
const BUILD='PHASE-405-FIVE-HOUR-TOURNAMENT-SCHEDULE-LOCK',SLOT_MS=5*60*60*1000,ANCHOR=Date.UTC(2026,0,1,0,0,0),ARCHIVE='svr405_tournament_archive',LAST='svr405_tournament_last_slot',ACTIVE='svr405_active_tournament_slot';
const BOTS=['Claudia','Eric','Maya','Darius','Nova','Kai','Lena','Marcus','Zoe'];
const $=s=>document.querySelector(s),now=()=>Date.now(),slotId=t=>Math.floor((t-ANCHOR)/SLOT_MS),slot=id=>({id,start:ANCHOR+id*SLOT_MS,end:ANCHOR+(id+1)*SLOT_MS});
function load(){try{return JSON.parse(localStorage.getItem(ARCHIVE)||'[]')}catch{return[]}}
function save(rows){localStorage.setItem(ARCHIVE,JSON.stringify(rows.slice(-120)));return rows}
function seed(id){let x=(id*1664525+1013904223)>>>0;return()=>((x=(x*1664525+1013904223)>>>0)/4294967296)}
function botResult(id){const r=seed(id),order=[...BOTS].sort(()=>r()-.5);return{slotId:id,source:'bot-simulation',playMoneyOnly:true,name:'REIKI FIVE-HOUR TEST',startedAt:new Date(slot(id).start).toISOString(),completedAt:new Date(slot(id).end-1).toISOString(),champion:order[0],placements:order.slice(0,6).map((name,i)=>({place:i+1,name})),note:'Prototype result generated locally for an unattended five-hour slot.'}}
function phase401Result(){try{return JSON.parse(localStorage.getItem('svr401_reiki_first50_results')||'null')}catch{return null}}
function actualFor(id){const r=phase401Result();if(!r?.completedAt)return null;const t=Date.parse(r.completedAt);if(slotId(t)!==id)return null;return{slotId:id,source:'local-play',playMoneyOnly:true,name:r.name||'REIKI FIRST 50',startedAt:new Date(slot(id).start).toISOString(),completedAt:r.completedAt,champion:r.champion?.name||r.champion||'Winner',placements:(r.placements||[]).slice(0,10),prizePlayChips:r.prizePlayChips||100000}}
function reconcile(){const current=slotId(now()),rows=load(),known=new Set(rows.map(x=>x.slotId));let last=Number(localStorage.getItem(LAST));if(!Number.isFinite(last))last=current-1;for(let id=Math.max(last,current-10);id<current;id++)if(!known.has(id)){rows.push(actualFor(id)||botResult(id));known.add(id)}const currentActual=actualFor(current);if(currentActual&&!known.has(current)){rows.push(currentActual);known.add(current)}localStorage.setItem(LAST,String(current));save(rows);return rows}
const fmt=t=>new Intl.DateTimeFormat(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'}).format(new Date(t));
function sameLocalDay(a,b=now()){const x=new Date(a),y=new Date(b);return x.getFullYear()===y.getFullYear()&&x.getMonth()===y.getMonth()&&x.getDate()===y.getDate()}
function scheduleMarkup(){const current=slotId(now()),cur=slot(current),rows=reconcile().filter(r=>sameLocalDay(Date.parse(r.completedAt||r.startedAt))).sort((a,b)=>b.slotId-a.slotId);const next=Array.from({length:5},(_,i)=>slot(current+i));return`<section id="phase405TournamentSchedule" style="margin:18px 0;padding:18px;border:1px solid #7ffcff55;border-radius:22px;background:#06101bee"><div style="color:#8dffb4;font-weight:900;letter-spacing:.08em">PHASE 405 • 5-HOUR TEST SCHEDULE</div><h2 style="margin:6px 0">Tournament Rotation</h2><p style="color:#bfd4e7">A play-money test tournament slot runs every five hours. If nobody plays a slot, a local bot simulation creates a result the next time this page is opened so the daily board still has a basis to review.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:7px">${next.map((s,i)=>`<div style="padding:9px;border:1px solid ${i?'#ffffff22':'#8dffb4'};border-radius:12px;background:#08131e"><strong>${i?'UPCOMING':'CURRENT'}</strong><br><span style="color:#ffd98a">${fmt(s.start)}</span><br><small>${fmt(s.end)}</small></div>`).join('')}</div><h3>Today’s Results</h3><div id="phase405DailyResults">${rows.length?rows.map(r=>`<div style="display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-top:1px solid #ffffff18"><span>${fmt(slot(r.slotId).start)} • ${r.source==='local-play'?'PLAYED':'BOT TEST'}</span><strong style="color:#ffd98a">${r.champion}</strong></div>`).join(''):'<p style="color:#9fb6c9">No completed slot yet today.</p>'}</div><p style="color:#8aa7bc;font-size:10px">Current slot: ${fmt(cur.start)} → ${fmt(cur.end)} • local prototype only • no real-money value.</p></section>`}
function installPortal(){if($('#phase405TournamentSchedule'))return;const hands=$('.hands-card'),card=$('#reikiTournament');if(hands)hands.insertAdjacentHTML('beforebegin',scheduleMarkup());else card?.insertAdjacentHTML('afterend',scheduleMarkup());const enter=$('#enterTournament');if(enter&&!enter.dataset.phase405){enter.dataset.phase405='1';enter.addEventListener('click',()=>{const current=slotId(now());localStorage.setItem(ACTIVE,String(current));let t=null;try{t=JSON.parse(localStorage.getItem('svr401_reiki_first50_tournament')||'null')}catch{}const old=Number(t?.phase405SlotId);if(t?.status==='completed'||(Number.isFinite(old)&&old!==current&&t?.status!=='in_progress'))localStorage.removeItem('svr401_reiki_first50_tournament')})}}
function tagRunning(){const current=Number(localStorage.getItem(ACTIVE)||slotId(now()));let t=null;try{t=JSON.parse(localStorage.getItem('svr401_reiki_first50_tournament')||'null')}catch{}if(t?.status==='in_progress'&&!Number.isFinite(Number(t.phase405SlotId))){t.phase405SlotId=current;localStorage.setItem('svr401_reiki_first50_tournament',JSON.stringify(t))}}
function poll(){reconcile();tagRunning();installPortal()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{poll();setInterval(poll,3000)},{once:true});else{poll();setInterval(poll,3000)}
window.SVR_PHASE405_TOURNAMENT_SCHEDULE=()=>({build:BUILD,slotMilliseconds:SLOT_MS,currentSlot:slot(slotId(now())),nextSlots:Array.from({length:5},(_,i)=>slot(slotId(now())+i)),todayResults:reconcile().filter(r=>sameLocalDay(Date.parse(r.completedAt||r.startedAt))),playMoneyOnly:true,sharedBackend:false,pass:SLOT_MS===18000000,checkedAt:new Date().toISOString()});