import * as THREE from "three";
const LABEL="PHASE-322-FULL-LOBBY-VISUAL-FINISH-LOCK",ROOT="PHASE322_FULL_LOBBY_VISUAL_FINISH_ROOT";
const GOLD=0xffd98a,CYAN=0x7ffcff,PURPLE=0xa77cff,GREEN=0x8dffb4,RED=0xff5b8c;
const ANDROID=/Android/i.test(navigator.userAgent||"")&&!/Quest|Oculus|Meta Quest/i.test(navigator.userAgent||"");
let scene,renderer,root,ready=false,oldTick=null,moon,mars,stars;const anim=[],pulse=[];
const std=(c,e=0,i=.06,r=.76,m=.06)=>new THREE.MeshStandardMaterial({color:c,emissive:e,emissiveIntensity:i,roughness:r,metalness:m});
const glow=(c,o=.4)=>new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending});
function box(p,n,s,v,m,ry=0){const o=new THREE.Mesh(new THREE.BoxGeometry(s[0],s[1],s[2]),m);o.name=n;o.position.set(...v);o.rotation.y=ry;o.castShadow=o.receiveShadow=false;p.add(o);return o;}
function plane(p,n,w,h,v,m,ry=0,rx=0){const o=new THREE.Mesh(new THREE.PlaneGeometry(w,h),m);o.name=n;o.position.set(...v);o.rotation.set(rx,ry,0);o.renderOrder=322;p.add(o);return o;}
function texture(title,sub="",lines=[],footer="",color="#ffd98a",w=1100,h=520){const c=document.createElement("canvas"),x=c.getContext("2d");c.width=w;c.height=h;const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,"#02050d");g.addColorStop(.58,"#080b18");g.addColorStop(1,"#14051e");x.fillStyle=g;x.fillRect(0,0,w,h);x.strokeStyle=color;x.lineWidth=12;x.strokeRect(22,22,w-44,h-44);x.strokeStyle="rgba(255,255,255,.16)";x.lineWidth=3;x.strokeRect(50,50,w-100,h-100);x.textAlign="center";x.textBaseline="middle";x.fillStyle="#fff";x.font="900 66px system-ui,Arial";x.fillText(title,w/2,92,w-110);if(sub){x.fillStyle=color;x.font="800 31px system-ui,Arial";x.fillText(sub,w/2,170,w-120);}x.textAlign="left";x.fillStyle="#eaf6ff";x.font="700 28px system-ui,Arial";let y=252;lines.slice(0,4).forEach(t=>{x.fillText(`• ${t}`,84,y,w-168);y+=48;});if(footer){x.textAlign="center";x.fillStyle=color;x.font="900 29px system-ui,Arial";x.fillText(footer,w/2,h-64,w-120);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=true;return t;}
function panel(p,n,v,w,h,title,sub,lines,footer,color,ry=0){box(p,n+"_FRAME",[w+.26,h+.26,.14],v,std(0x10141f,0x040713,.16,.68,.1),ry);const tex=texture(title,sub,lines,footer,color);const nx=Math.sin(ry)*.09,nz=Math.cos(ry)*.09,q=plane(p,n,w,h,[v[0]+nx,v[1]+.02,v[2]+nz],new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide,depthWrite:false}),ry);q.userData.tex=tex;return q;}
function hide(o){if(!o)return;o.visible=false;o.traverse?.(c=>c.visible=false);}function show(o){if(!o)return;o.visible=true;o.traverse?.(c=>c.visible=true);}
function clean(){hide(scene.getObjectByName("PHASE216_PLANNED_LOBBY_LOOK_FINISH_ROOT"));hide(scene.getObjectByName("PHASE201_HUB_CONTENT_RESTORE_ROOT"));scene.traverse(o=>{const n=String(o.name||"").toUpperCase();if(n.startsWith("PHASE202_")&&(n.endsWith("_SIGN")||n.includes("VIDEO_SLIDE")||n.includes("PREVIEW_SIGN")||n.includes("DISPLAY_SIGN")||n.includes("DOOR_SIGN")))hide(o);if(n.includes("PHASE200_LEFT_JUMBOTRON_SLOT")||n.includes("PHASE200_RIGHT_JUMBOTRON_SLOT")||n.includes("PHASE215_HIGH_TABLE_TAG"))hide(o);});}
function sky(){moon||=scene.getObjectByName("PHASE200_SINGLE_VISIBLE_MOON_LOCKED");mars||=scene.getObjectByName("PHASE200_SINGLE_VISIBLE_MARS_LOCKED");stars||=scene.getObjectByName("PHASE200_STAR_FIELD_ONLY");if(moon){show(moon);moon.position.set(-10.4,18.6,-38);moon.scale.setScalar(.72);}if(mars){show(mars);mars.position.set(9.2,16.9,-41);mars.scale.setScalar(.70);}if(stars){show(stars);stars.material.size=ANDROID?.028:.036;stars.material.opacity=ANDROID?.56:.78;stars.material.needsUpdate=true;}show(scene.getObjectByName("PHASE278_MOON_SOFT_HALO"));show(scene.getObjectByName("PHASE278_MARS_SOFT_HALO"));}
function floor(){const c=document.createElement("canvas"),x=c.getContext("2d");c.width=c.height=768;x.fillStyle="#101521";x.fillRect(0,0,768,768);x.strokeStyle="rgba(165,195,235,.11)";x.lineWidth=3;for(let i=0;i<=768;i+=96){x.beginPath();x.moveTo(i,0);x.lineTo(i,768);x.stroke();x.beginPath();x.moveTo(0,i);x.lineTo(768,i);x.stroke();}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,2.5);const m=new THREE.MeshStandardMaterial({map:t,roughness:.82,metalness:.05,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});plane(root,"PHASE322_FINISHED_MARBLE_FLOOR",37,30.7,[0,.024,0],m,0,-Math.PI/2);plane(root,"PHASE322_CENTER_RED_CARPET",4.4,26,[0,.034,.5],std(0x620b22,0x21020a,.14,.84,.02),0,-Math.PI/2);box(root,"PHASE322_CARPET_LEFT_EDGE",[.045,.035,26],[-2.23,.055,.5],glow(GOLD,.48));box(root,"PHASE322_CARPET_RIGHT_EDGE",[.045,.035,26],[2.23,.055,.5],glow(GOLD,.48));const a=new THREE.Mesh(new THREE.RingGeometry(3.65,4.08,96),glow(GOLD,.3));a.name="PHASE322_TABLE_FLOOR_MEDALLION";a.rotation.x=-Math.PI/2;a.position.set(0,.058,.75);root.add(a);pulse.push(a.material);}
function skyline(){const c=document.createElement("canvas"),x=c.getContext("2d");c.width=384;c.height=768;x.fillStyle="#060913";x.fillRect(0,0,384,768);for(let y=28;y<740;y+=46)for(let z=18;z<370;z+=42){x.globalAlpha=((z+y)%7)? .55:.2;x.fillStyle=((z+y)%5===0)?"#b48cff":"#78dfff";x.fillRect(z,y,20,25);}x.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.MeshStandardMaterial({color:0x11182a,map:t,emissive:0x101c35,emissiveMap:t,emissiveIntensity:ANDROID?.35:.55,roughness:.86,metalness:.08});const count=ANDROID?18:26,g=new THREE.BoxGeometry(1,1,1),im=new THREE.InstancedMesh(g,m,count),d=new THREE.Object3D();im.name="PHASE322_LIGHTWEIGHT_CITY_SKYLINE";for(let i=0;i<count;i++){const q=i/Math.max(1,count-1),h=7.5+((i*11)%9)*1.25+(i%7===0?7:0);d.position.set(-32+q*64+Math.sin(i*2.2),h/2-.2,-24-(i%2)*5.5-Math.abs(Math.sin(i*.8))*2);d.scale.set(1.7+((i*7)%5)*.38,h,1.6+((i*3)%4)*.42);d.rotation.y=((i%3)-1)*.045;d.updateMatrix();im.setMatrixAt(i,d.matrix);}im.instanceMatrix.needsUpdate=true;root.add(im);[[ -7.5,-29,24,2.6],[12.5,-31,20,3],[0,-35,29,2.2]].forEach((v,i)=>{box(root,`PHASE322_SIGNATURE_TOWER_${i+1}`,[v[3],v[2],v[3]],[v[0],v[2]/2,v[1]],std(0x11172a,0x17284a,ANDROID?.32:.5,.82,.1));const s=new THREE.Mesh(new THREE.ConeGeometry(.18,3.5,10),glow(i===2?GOLD:CYAN,.58));s.position.set(v[0],v[2]+1.75,v[1]);root.add(s);});}
function architecture(){const dark=std(0x0b0f19,0x02040b,.1,.76,.08),gold=glow(GOLD,.42),cyan=glow(CYAN,.24);box(root,"PHASE322_REAR_CROWN",[37.4,.34,.42],[0,6.04,-16.18],dark);box(root,"PHASE322_REAR_CROWN_GOLD",[37,.055,.06],[0,5.86,-15.94],gold);[-15.4,-9,-3,3,9,15.4].forEach((v,i)=>{box(root,`PHASE322_REAR_DOORWAY_JAMB_${i+1}`,[.2,4.85,.38],[v,2.62,-15.86],dark);const s=box(root,`PHASE322_REAR_DOORWAY_SEAM_${i+1}`,[.035,4.5,.05],[v,2.62,-15.62],i%2?cyan:gold);pulse.push(s.material);});box(root,"PHASE322_WEST_WALL_GOLD_BASE",[.06,.06,30],[-19.3,.22,0],gold);box(root,"PHASE322_EAST_WALL_GOLD_BASE",[.06,.06,30],[19.3,.22,0],gold);}
function storefronts(){const s=[[-12,PURPLE,"REIKI HUB","RESTORE • RESET • RECHARGE",["Private meditation destination","Calm room portal","Sponsor presentation reserved"],"AWAITING APPROVAL"],[-6,CYAN,"PGA GOLF TRAINING","DRIVE • CHIP • PUTT",["Private training range","Stance and target practice","Short-game destination"],"ENTER TRAINING HUB"],[0,GOLD,"PLAY SVR POKER","6-SEAT TEXAS HOLD'EM",["Five computer players","Open south player seat","Play-money poker table"],"TAKE YOUR SEAT"],[6,GREEN,"SVR STORE","GEAR • MEMBERSHIPS • COSMETICS",["Official SVR store portal","Player gear showcase","Web store connection"],"OPEN THE STORE"],[12,RED,"SCORPION ROOM","PRIVATE CITY POKER",["City-overlook destination","Private poker atmosphere","VIP table route"],"ENTER SCORPION"]];s.forEach((v,i)=>{const col=`#${v[1].toString(16).padStart(6,"0")}`;panel(root,`PHASE322_STOREFRONT_PANEL_${i+1}`,[v[0],2.3,-12.58],4.18,2.18,v[2],v[3],v[4],v[5],col);const ht=texture(v[2],"",[],"",col,1000,250),h=plane(root,`PHASE322_STOREFRONT_HEADER_${i+1}`,4.25,.94,[v[0],5.18,-15.96],new THREE.MeshBasicMaterial({map:ht,transparent:true,side:THREE.DoubleSide,depthWrite:false}));h.userData.tex=ht;const l=box(root,`PHASE322_STOREFRONT_LEFT_GLOW_${i+1}`,[.045,3.1,.05],[v[0]-2.18,1.72,-12.48],glow(v[1],.52)),r=box(root,`PHASE322_STOREFRONT_RIGHT_GLOW_${i+1}`,[.045,3.1,.05],[v[0]+2.18,1.72,-12.48],glow(v[1],.52));pulse.push(l.material,r.material);const q=new THREE.Group();q.name=`PHASE322_STOREFRONT_HOLOGRAM_${i+1}`;q.position.set(v[0],1.18,-11.72);q.add(new THREE.Mesh(new THREE.OctahedronGeometry(.26,0),glow(v[1],.52)));const o=new THREE.Mesh(new THREE.TorusGeometry(.42,.018,8,48),glow(v[1],.38));o.rotation.x=Math.PI/2;q.add(o);root.add(q);anim.push({o:q,s:.24+i*.035,b:.045,y:q.position.y});});}
function table(){const t=texture("SVR POKER","THE SOCIAL VR POKER EXPERIENCE",[],"PLAY-MONEY DEMO TABLE","#ffd98a",1100,340);plane(root,"PHASE322_TABLE_HERO_SIGN",4.8,1.44,[0,3.72,.74],new THREE.MeshBasicMaterial({map:t,transparent:true,side:THREE.DoubleSide,depthWrite:false}),0);const q=new THREE.Group();q.name="PHASE322_TABLE_RING_CHANDELIER";q.position.set(0,5.88,.75);[2.2,1.55,.92].forEach((r,i)=>{const a=new THREE.Mesh(new THREE.TorusGeometry(r,.035,8,96),glow(i===1?CYAN:GOLD,i===1?.32:.44));a.rotation.x=Math.PI/2;a.position.y=i*.14;q.add(a);});for(let i=0;i<8;i++){const a=i/8*Math.PI*2,b=new THREE.Mesh(new THREE.SphereGeometry(.055,10,8),glow(i%2?CYAN:GOLD,.72));b.position.set(Math.cos(a)*2.18,-.05,Math.sin(a)*2.18);q.add(b);}root.add(q);anim.push({o:q,s:.016,b:0,y:q.position.y});const l=new THREE.PointLight(0xffe1b0,ANDROID?.7:1.1,18,2);l.position.set(0,5.25,.75);root.add(l);[[0,-1.85],[-2.55,-.45],[-2.55,1.75],[0,3.25],[2.55,-.45],[2.55,1.75]].forEach((v,i)=>{const a=new THREE.Mesh(new THREE.RingGeometry(.36,.46,48),glow(i===3?GREEN:CYAN,i===3?.54:.16));a.rotation.x=-Math.PI/2;a.position.set(v[0],.062,v[1]+.75);root.add(a);});}
function displays(){panel(root,"PHASE322_LEFT_MISSION_JUMBOTRON",[-19.08,2.72,-2],4.65,2.36,"SVR MISSION","POKER • COMMUNITY • IMPACT",["Immersive social poker","Sponsor-powered destinations","Community and charity vision"],"SCARLETT HOLDING LLC","#7ffcff",Math.PI/2);panel(root,"PHASE322_RIGHT_EVENTS_JUMBOTRON",[19.08,2.72,-2],4.65,2.36,"EVENTS & REPLAYS","WEEKEND • MONTHLY • HIGHLIGHTS",["Tournament schedule board","Featured hand replays","Sponsor and charity events"],"COMING TO THE SVR LOBBY","#a77cff",-Math.PI/2);[[-8.8,"EVENTS","WEEKEND & MONTHLY","#a77cff"],[0,"LEGENDS HALL","CHAMPIONS & TROPHIES","#ffd98a"],[8.8,"SPONSORS","FEATURED PARTNERS","#7ffcff"]].forEach((v,i)=>{const t=texture(v[1],v[2],[],"",v[3],900,260);plane(root,`PHASE322_UPPER_FASCIA_${i+1}`,3.7,1.02,[v[0],4.88,-12.94],new THREE.MeshBasicMaterial({map:t,transparent:true,side:THREE.DoubleSide,depthWrite:false}));});panel(root,"PHASE322_DAILY_BONUS_KIOSK",[-10.8,1.7,5],2.75,1.55,"DAILY BONUS","5,000 PLAY CHIPS",["Daily reward station","One claim per day","Play-money economy"],"BONUS KIOSK","#ffd98a",.2);panel(root,"PHASE322_SPONSOR_KIOSK",[10.8,1.7,5],2.75,1.55,"SPONSOR HUB","PARTNERS & COMMUNITY",["Featured destination spaces","Approved partner content","Community impact"],"PARTNER SHOWCASE","#7ffcff",-.2);}
function render(){renderer.shadowMap.enabled=false;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=ANDROID?.9:1.02;if(ANDROID)renderer.setPixelRatio(Math.min(.72,window.devicePixelRatio||1));}
function tick(){if(root?.userData.tick)return;oldTick=scene.userData._tickWorld||null;scene.userData._tickWorld=dt=>{oldTick?.(dt);sky();const t=performance.now()*.001;anim.forEach((a,i)=>{a.o.rotation.y+=a.s*Math.min(dt||.016,.033);if(a.b)a.o.position.y=a.y+Math.sin(t*1.25+i)*a.b;});pulse.forEach((m,i)=>m.opacity=.3+(Math.sin(t*1.15+i*.7)+1)*.08);};root.userData.tick=true;}
function publish(a="state"){window.SVR_PHASE322_FULL_LOBBY_VISUAL_FINISH_LOCK={build:LABEL,active:ready,gameOnly:true,siteTouched:false,plannedLobbyPreserved:true,finishedArchitecture:true,finishedStorefronts:true,finishedLighting:true,finishedTablePresentation:true,lightweightSkyline:true,moonVisible:true,marsVisible:true,androidSafe:ANDROID,action:a,checkedAt:new Date().toISOString()};window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;}
function build(){scene=window.__SVR_SCENE__;renderer=window.__SVR_RENDERER__;if(!scene||!renderer)return false;clean();scene.getObjectByName(ROOT)?.parent?.remove(scene.getObjectByName(ROOT));root=new THREE.Group();root.name=ROOT;scene.add(root);floor();skyline();architecture();storefronts();table();displays();sky();render();tick();ready=true;publish("build");return true;}
function enforce(){scene||=window.__SVR_SCENE__;renderer||=window.__SVR_RENDERER__;if(!scene||!renderer)return false;clean();sky();render();if(!root?.parent)return build();publish("enforce");return true;}
function boot(){if(!build())setTimeout(boot,250);}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();[500,1200,2400,4600,7600].forEach(t=>setTimeout(enforce,t));window.SVR_RUN_PHASE322_LOBBY_VISUAL_AUDIT=()=>window.SVR_PHASE322_FULL_LOBBY_VISUAL_FINISH_LOCK;publish("loaded");
