import * as THREE from 'three';
const LABEL='PHASE-192-TABLE-LOGO-PORTAL-AUDIT-LOCK';
const ROOT='PHASE192_TABLE_LOGO_PORTAL_AUDIT_ROOT';
let scene,camera,renderer,root,started=false,last=0;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function tableInfo(){const r=sr(scene);const t=r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED');if(!t)return null;t.visible=true;t.traverse?.(o=>{o.visible=true;if(o.isMesh&&o.material){o.material.needsUpdate=true;}});t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),c=new THREE.Vector3(),s=new THREE.Vector3();b.getCenter(c);b.getSize(s);return {obj:t,center:c,size:s};}
function cleanRails(c){const r=sr(scene),kill=[];r?.traverse?.(o=>{const n=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|watch|hand|teleport/i.test(n))return;if(!/rail|rope|stanchion|barrier|banister|handrail|guard|pole|post/i.test(n))return;const p=new THREE.Vector3();o.getWorldPosition(p);if(Math.hypot(p.x-c.x,p.z-c.z)<10.5)kill.push(o);});[...new Set(kill)].forEach(o=>o.parent?.remove(o));return kill.length;}
function makeLogo(c){const r=sr(scene);['PHASE192_CENTER_LOGO_FILL','PHASE191_CENTER_LOGO_CARPET_FULL_CIRCLE','PHASE190_MAX_CENTER_LOGO_CARPET'].forEach(n=>{const o=r?.getObjectByName?.(n);if(o)o.parent?.remove(o);});const g=new THREE.Group();g.name='PHASE192_CENTER_LOGO_FILL';g.position.set(c.x,.026,c.z);const canv=document.createElement('canvas');canv.width=canv.height=1024;const x=canv.getContext('2d'),cx=512,cy=512;x.clearRect(0,0,1024,1024);let gr=x.createRadialGradient(cx,cy,30,cx,cy,505);gr.addColorStop(0,'rgba(127,252,255,.38)');gr.addColorStop(.62,'rgba(90,20,170,.30)');gr.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=gr;x.fillRect(0,0,1024,1024);x.strokeStyle='rgba(127,252,255,.98)';x.lineWidth=16;x.beginPath();x.arc(cx,cy,500,0,Math.PI*2);x.stroke();x.strokeStyle='rgba(238,191,92,.9)';x.lineWidth=8;x.beginPath();x.arc(cx,cy,452,0,Math.PI*2);x.stroke();x.textAlign='center';x.textBaseline='middle';x.fillStyle='#7ffcff';x.font='900 220px system-ui';x.fillText('SVR',cx,cy-42);x.fillStyle='#eebf5c';x.font='900 84px system-ui';x.fillText('POKER',cx,cy+112);const tex=new THREE.CanvasTexture(canv);tex.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(13.6,13.6),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide,depthWrite:false}));mesh.name='PHASE192_LOGO_PLANE_MAX';mesh.rotation.x=-Math.PI/2;mesh.renderOrder=1920;g.add(mesh);r?.add(g);return true;}
function player(){const p=new THREE.Vector3();if(renderer?.xr?.isPresenting)renderer.xr.getCamera(camera).getWorldPosition(p);else camera?.getWorldPosition(p);return p;}
function setPose(x,y,z){const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;if(renderer?.xr?.isPresenting&&rig?.setPlayerPose)rig.setPlayerPose(x,y,z);else camera.position.set(x,y+1.62,z);}
function addZone(n,x,y,z,tx,ty,tz,col){const old=root.getObjectByName?.(n);if(old)old.parent?.remove(old);const g=new THREE.Group();g.name=n;g.position.set(x,y+1.62,z);g.userData.target={x:tx,y:ty,z:tz};root.add(g);const ring=new THREE.Mesh(new THREE.RingGeometry(.9,1.22,72),basic(col,.55));ring.rotation.x=-Math.PI/2;ring.position.y=-1.58;g.add(ring);return g;}
function tick(){const now=performance.now(),p=player();for(const g of root.children){if(!g.userData?.target)continue;const wp=new THREE.Vector3();g.getWorldPosition(wp);if(Math.hypot(p.x-wp.x,p.z-wp.z)<1.55&&Math.abs(p.y-wp.y)<3&&now-last>1200){last=now;const t=g.userData.target;setPose(t.x,t.y,t.z);window.SVR_PHASE192_LAST_PORTAL={build:LABEL,name:g.name,checkedAt:iso()};}}
}
async function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);const t=tableInfo(),c=t?.center||new THREE.Vector3(0,0,0),removed=cleanRails(c);makeLogo(c);addZone('PHASE192_UPSTAIRS_WALK_ZONE',-11.15,0,7.55,-11.1,3.15,-7.65,0x7ffcff);addZone('PHASE192_LOBBY_WALK_ZONE',11.15,3.15,-7.55,0,0,7.2,0xffd98a);window.SVR_PHASE192_TABLE_LOGO_PORTAL_AUDIT_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,tableVisible:!!t,logoMax:true,railsRemoved:removed,walkThroughZones:true,checkedAt:iso()};window.SVR_RUN_PHASE192_AUDIT=()=>window.SVR_PHASE192_TABLE_LOGO_PORTAL_AUDIT_LOCK;window.SVR_PHASE192_TELEPORT_UP=()=>setPose(-11.1,3.15,-7.65);window.SVR_PHASE192_TELEPORT_DOWN=()=>setPose(0,0,7.2);window.SVR_LOCKED_FINAL_BUILD=LABEL;if(!started){started=true;setInterval(tick,110);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
