import * as THREE from 'three';
const LABEL='PHASE-195-VR-ROOM-PORTAL-SYSTEM-LOCK';
const ROOT='PHASE195_VR_ROOM_PORTAL_SYSTEM_ROOT';
const EYE=1.62, COOLDOWN=1200;
const ROOMS={
  lobby:{x:0,y:0,z:7.2,look:{x:0,y:1.4,z:0}},
  vibes:{x:44,y:0,z:4.5,look:{x:44,y:1.6,z:-6}},
  smokers:{x:-44,y:0,z:4.5,look:{x:-44,y:1.6,z:-6}},
  storeA:{x:44,y:3.15,z:18,look:{x:44,y:4.5,z:8}},
  storeB:{x:-44,y:3.15,z:18,look:{x:-44,y:4.5,z:8}}
};
let scene,camera,renderer,root,started=false,lastTp=0,current='lobby';
function iso(){return new Date().toISOString();}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.04,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.95});}
function addBox(p,n,pos,s,m){const x=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);x.name=n;x.position.set(pos.x,pos.y,pos.z);x.receiveShadow=true;p.add(x);return x;}
function sign(title,sub,color){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#050610';x.fillRect(0,0,1024,512);x.strokeStyle='#'+color.toString(16).padStart(6,'0');x.lineWidth=14;x.strokeRect(24,24,976,464);x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff';x.font='900 74px system-ui';x.fillText(title,512,184,930);x.fillStyle='#ffd98a';x.font='700 34px system-ui';x.fillText(sub,512,284,910);x.fillStyle='#bffcff';x.font='700 25px system-ui';x.fillText('Walk through',512,382,910);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function setPose(room){const r=ROOMS[room]||ROOMS.lobby;current=room in ROOMS?room:'lobby';const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;if(renderer?.xr?.isPresenting&&rig?.setPlayerPose)rig.setPlayerPose(r.x,r.y,r.z);else{camera.position.set(r.x,r.y+EYE,r.z);camera.lookAt(r.look.x,r.look.y,r.look.z);}window.SVR_PHASE195_CURRENT_ROOM={build:LABEL,room:current,pose:r,checkedAt:iso()};}
function player(){const p=new THREE.Vector3();if(renderer?.xr?.isPresenting)renderer.xr.getCamera(camera).getWorldPosition(p);else camera?.getWorldPosition(p);return p;}
function portal(id,title,sub,pos,target,color){const g=new THREE.Group();g.name='PHASE195_PORTAL_'+id.toUpperCase();g.position.set(pos.x,pos.y+EYE,pos.z);g.userData.target=target;root.add(g);const ring=new THREE.Mesh(new THREE.RingGeometry(.92,1.25,80),basic(color,.62));ring.name='PHASE195_GLOW_RING_'+id.toUpperCase();ring.rotation.x=-Math.PI/2;ring.position.y=-EYE+.04;g.add(ring);const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.35,1.55),new THREE.MeshBasicMaterial({map:sign(title,sub,color),transparent:true,side:THREE.DoubleSide}));panel.name='PHASE195_READABLE_PORTAL_SIGN_'+id.toUpperCase();panel.position.set(0,.12,-.56);g.add(panel);const vol=new THREE.Mesh(new THREE.BoxGeometry(2.5,3.1,2.15),basic(0xffffff,.001));vol.name='PHASE195_WALKTHROUGH_VOLUME_'+id.toUpperCase();vol.position.y=-.25;vol.userData.target=target;g.add(vol);return g;}
function roomBox(id,base,title,color){const g=new THREE.Group();g.name='PHASE195_ROOM_'+id.toUpperCase();g.position.set(base.x,base.y,base.z);root.add(g);addBox(g,'PHASE195_'+id+'_FLOOR',{x:0,y:.02,z:0},{x:15,y:.04,z:12},mat(0x161a22));addBox(g,'PHASE195_'+id+'_BACK_WALL',{x:0,y:2,z:-6},{x:15,y:4,z:.16},mat(0x080b12));addBox(g,'PHASE195_'+id+'_LEFT_WALL',{x:-7.5,y:2,z:0},{x:.16,y:4,z:12},mat(0x0c1018));addBox(g,'PHASE195_'+id+'_RIGHT_WALL',{x:7.5,y:2,z:0},{x:.16,y:4,z:12},mat(0x0c1018));const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');let tick=0;function draw(){tick+=.02;x.fillStyle='#02030a';x.fillRect(0,0,1024,512);x.fillStyle='#fff';x.font='900 70px system-ui';x.textAlign='center';x.fillText(title,512,150);x.fillStyle='#ffd98a';x.font='700 34px system-ui';x.fillText('Sample VR room module',512,238);x.fillStyle=`hsl(${(tick*120)%360},90%,64%)`;x.fillRect(212+Math.sin(tick)*72,320,600,26);}draw();const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const screen=new THREE.Mesh(new THREE.PlaneGeometry(8.7,4.1),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));screen.name='PHASE195_'+id+'_SAMPLE_SCREEN';screen.position.set(0,2.35,-5.86);g.add(screen);setInterval(()=>{draw();tex.needsUpdate=true;},220);for(let r=0;r<3;r++)for(let i=-3;i<=3;i+=2)addBox(g,'PHASE195_'+id+'_SEAT',{x:i,y:.28,z:1+r*1.25},{x:1.1,y:.55,z:.72},mat(color));portal(id+'Exit','EXIT','Return to lobby',{x:base.x,y:base.y,z:base.z+5.2},'lobby',0xffd98a);return g;}
function tickPortals(){const now=performance.now(),p=player(),vols=[];root.traverse(o=>{if(o.userData?.target)vols.push(o);});for(const v of vols){const wp=new THREE.Vector3();v.getWorldPosition(wp);if(Math.hypot(p.x-wp.x,p.z-wp.z)<1.65&&Math.abs(p.y-wp.y)<3.25&&now-lastTp>COOLDOWN){lastTp=now;setPose(v.userData.target);window.SVR_PHASE195_LAST_ROOM_PORTAL={build:LABEL,portal:v.name,target:v.userData.target,checkedAt:iso()};break;}}
}
function build(){portal('vibes','VIBES THEATER','Enter sample theater',{x:-4.2,y:0,z:10.55},'vibes',0xb86cff);portal('smokers','SMOKERS LOUNGE','Enter sample lounge',{x:4.2,y:0,z:10.55},'smokers',0x7ffcff);portal('upperStoreA','UPPER STORE A','Future upstairs store',{x:-12.7,y:3.15,z:9.1},'storeA',0x7ffcff);portal('upperStoreB','UPPER STORE B','Future upstairs store',{x:12.7,y:3.15,z:9.1},'storeB',0xb86cff);roomBox('vibes',ROOMS.vibes,'VIBES THEATER',0x2a123d);roomBox('smokers',ROOMS.smokers,'SMOKERS LOUNGE',0x12343d);roomBox('storeA',ROOMS.storeA,'UPSTAIRS STORE A',0x193d2a);roomBox('storeB',ROOMS.storeB,'UPSTAIRS STORE B',0x2a193d);}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);build();window.SVR_PHASE195_VR_ROOM_PORTAL_SYSTEM_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,rooms:Object.keys(ROOMS),walkThroughPortals:true,roomExitSystem:true,upstairsStoreReady:true,checkedAt:iso()};window.SVR_RUN_PHASE195_AUDIT=()=>window.SVR_PHASE195_VR_ROOM_PORTAL_SYSTEM_LOCK;window.SVR_PHASE195_ENTER_VIBES=()=>setPose('vibes');window.SVR_PHASE195_ENTER_SMOKERS=()=>setPose('smokers');window.SVR_PHASE195_EXIT_ROOM=()=>setPose('lobby');window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(tickPortals,120);window.addEventListener('keydown',e=>{if(e.code==='KeyV')setPose('vibes');if(e.code==='KeyL')setPose('lobby');if(e.code==='KeyS')setPose('smokers');});}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
