import * as THREE from "three";

const BUILD="PHASE-335-OCULUS-ACCEPTANCE-GAMEPLAY-STABILITY-LOCK";
const TABLE_NAMES=["PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED","PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT","PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED"];
const OLD_DISPLAYS=["PHASE332_BET_STATUS","PHASE331_UPRIGHT_TRANSLUCENT_POT_DISPLAY","PHASE331_POT_DISPLAY","P85_POT_LABEL","PHASE215_HIGH_TABLE_TAG","PHASE214_TABLE_STATUS","PHASE201_MASTER_RUNTIME_AUDIT_PANEL","PHASE200_RUNTIME_AUDIT_PANEL"];
const QA_QUERY=new URLSearchParams(location.search).get("qa")==="1";
let scene,camera,renderer,tableInfo,root,qaPanel,qaCanvas,qaTexture,xrSession,installed=false,qaVisible=QA_QUERY;
let originalAction,wrappedAction,lastActionKey="",lastActionAt=0,lastStateKey="",lastStateAt=performance.now(),seatChecked=false;
let hiddenDisplays=0,recoveredChips=0,repairedCards=0,repairedBots=0,blockedActions=0,barRecoveries=0;
const A=new THREE.Vector3(),B=new THREE.Vector3();

function sceneRoot(){return scene?.getObjectByName?.("PHASE200_ORDERED_GRAND_LOBBY_ROOT")||scene}
function table(){const base=sceneRoot();for(const n of TABLE_NAMES){const o=base?.getObjectByName?.(n)||scene?.getObjectByName?.(n);if(o)return o}return null}
function boxInfo(o){o.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(o),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);return{box,size,center}}
function matNames(o){const m=Array.isArray(o?.material)?o.material:[o?.material];return m.map(x=>x?.name||"").join(" ").toLowerCase()}
function detectTable(){const t=table();if(!t)return null;const full=boxInfo(t);let felt=null,best=-Infinity;t.traverse(o=>{if(!o.isMesh)return;let r;try{r=boxInfo(o)}catch{return}const label=`${o.name||""} ${matNames(o)}`.toLowerCase(),flat=Math.max(r.size.x,r.size.z)/Math.max(.001,r.size.y),score=(/polotno|felt|cloth|baize|surface|play/.test(label)?180:0)+r.size.x*r.size.z*2+(flat>20?35:0);if(score>best){best=score;felt={object:o,...r}}});const s=felt||{object:null,...full};return{table:t,felt:felt?.object||null,full,center:s.center.clone(),surfaceY:s.box.max.y+.01,width:Math.max(2.2,Math.min(s.size.x*.94,full.size.x*.74,4.1)),depth:Math.max(1.18,Math.min(s.size.z*.92,full.size.z*.70,2.25))}}
function activeCamera(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera}
function cameraWorld(v=A){activeCamera()?.getWorldPosition?.(v);return v}
function sign(){return Math.sign(cameraWorld(A).z-tableInfo.center.z)||1}
function snapshot(){const state=window.SVR_PHASE85_POKER_STATE||{};let audit=null;try{audit=window.SVR_RUN_PHASE85_POKER_AUDIT?.()||null}catch{}const players=audit?.players||[],you=players.find(p=>p.name==="YOU")||players[0]||{stack:0,bet:0};return{state,audit,players,you,phase:state.phase||audit?.phase||"idle",waitingHuman:!!state.waitingHuman,pot:Number(state.pot??audit?.pot??0),currentBet:Number(state.currentBet||0),need:Math.max(0,Number(state.currentBet||0)-Number(you.bet||0)),current:audit?.current||state.current||"-",handNo:Number(state.handNo||0),lastAction:String(state.lastAction||"Ready")}}
function hideDom(){for(const id of["svr-p85-poker-ui","log","err"]){const e=document.getElementById(id);e?.style?.setProperty("display","none","important")}}
function hideOld(){let count=0;for(const n of OLD_DISPLAYS){const o=scene.getObjectByName?.(n);if(!o)continue;o.traverse?.(x=>x.visible=false);o.visible=false;count++}sceneRoot()?.traverse?.(o=>{const n=String(o.name||"");if(!/POT|BET|STATUS|AUDIT|POKER.*DISPLAY/i.test(n)||/PHASE333_GAMEPLAY_STATUS_GROUP|PHASE334_STACK_TOTAL_LABEL|PHASE334_BET_POT_LABEL|PHASE335/i.test(n))return;if(o.visible){o.visible=false;count++}});hiddenDisplays=Math.max(hiddenDisplays,count)}
function placePanels(){const s=snapshot(),sgn=sign(),cam=cameraWorld(A),hud=scene.getObjectByName("PHASE333_GAMEPLAY_STATUS_GROUP"),bar=scene.getObjectByName("PHASE333_XR_ACTION_BAR");if(hud){hud.position.set(tableInfo.center.x,tableInfo.surfaceY+1.02,tableInfo.center.z-sgn*tableInfo.depth*.46);hud.scale.setScalar(.62);hud.visible=s.waitingHuman||s.phase==="showdown";hud.lookAt(cam.x,hud.position.y,cam.z)}if(bar){bar.position.set(tableInfo.center.x,tableInfo.surfaceY+.205,tableInfo.center.z+sgn*tableInfo.depth*.555);bar.scale.setScalar(1.04);bar.visible=s.waitingHuman||["showdown","idle"].includes(s.phase);bar.lookAt(cam.x,bar.position.y,cam.z)}else if(s.waitingHuman&&barRecoveries<3){barRecoveries++;try{window.SVR_PHASE333_REPOLISH?.()}catch{}setTimeout(()=>{try{window.SVR_PHASE334_REAPPLY_LAYOUT?.()}catch{}},180)}}
function wrapAction(){const current=window.SVR_POKER_ACTION;if(typeof current!=="function"||current===wrappedAction)return;originalAction=current;wrappedAction=function(a){const s=snapshot(),key=`${s.handNo}:${s.phase}:${a}:${s.currentBet}:${s.you.bet||0}`,now=performance.now();if(key===lastActionKey&&now-lastActionAt<520){blockedActions++;return false}lastActionKey=key;lastActionAt=now;return originalAction(a)};wrappedAction.__svrPhase335=true;window.SVR_POKER_ACTION=wrappedAction}
function chips(){const out=[];sceneRoot()?.traverse?.(o=>{if(o.isMesh&&o.userData?.svr332&&/CHIP/i.test(o.name||""))out.push(o)});return out}
function invalidChip(c){const p=c.getWorldPosition(B);return![p.x,p.y,p.z].every(Number.isFinite)||p.y<tableInfo.surfaceY-.28||p.y>tableInfo.surfaceY+1.8||Math.abs(p.x-tableInfo.center.x)>tableInfo.width*.9||Math.abs(p.z-tableInfo.center.z)>tableInfo.depth*1.05}
function recoverChips(){const bad=chips().filter(c=>!c.userData?.held&&invalidChip(c));if(!bad.length)return;bad.forEach(c=>{c.userData.dynamic=false;c.userData.held=false;c.userData.phase334Home=true;c.userData.phase334BetPlaced=false});try{window.SVR_PHASE334_REAPPLY_LAYOUT?.()}catch{}recoveredChips+=bad.length}
function cards(){const out=[];sceneRoot()?.traverse?.(o=>{if(o.isMesh&&/PHASE334_.*CARD|P85_HAND_0_|P85_COMM_|PHASE323_SURFACE_.*CARD/i.test(String(o.name||"")))out.push(o)});return out}
function stabilizeCards(){const cam=cameraWorld(A);for(const c of cards()){c.visible=true;c.renderOrder=Math.max(c.renderOrder||0,3350);for(const m of(Array.isArray(c.material)?c.material:[c.material])){if(m){m.side=THREE.DoubleSide;m.depthWrite=false}}const p=c.getWorldPosition(B);if(!Number.isFinite(p.y)||p.y<tableInfo.surfaceY-.08){const t=new THREE.Vector3(Number.isFinite(p.x)?p.x:tableInfo.center.x,tableInfo.surfaceY+.035,Number.isFinite(p.z)?p.z:tableInfo.center.z);c.parent?.worldToLocal(t);c.position.copy(t);repairedCards++}if(/PHASE334_.*HOLE|P85_HAND_0_/i.test(c.name||""))c.lookAt(cam)}}
function bots(){const out=[];sceneRoot()?.traverse?.(o=>{if(o.type==="Group"&&/PHASE334_.*ERIC|PHASE334_.*BOT/i.test(String(o.name||"")))out.push(o)});return out}
function stabilizeBots(){const list=bots();list.forEach((b,i)=>{b.visible=i<5;if(i>=5)return;const p=b.getWorldPosition(B);if(!Number.isFinite(p.y)){b.position.y=tableInfo.full.box.min.y;repairedBots++}b.lookAt(tableInfo.center.x,p.y,tableInfo.center.z)})}
function seatCheck(){if(seatChecked||!renderer?.xr?.isPresenting)return;const p=cameraWorld(A),horizontal=Math.abs(p.z-tableInfo.center.z),height=p.y-tableInfo.surfaceY,min=tableInfo.depth*.53,adjust={backInches:0,upInches:0};if(horizontal<min)adjust.backInches=Math.min(2,Math.ceil((min-horizontal)/.0254));if(height<.57)adjust.upInches=Math.min(2,Math.ceil((.57-height)/.0254));if(adjust.backInches||adjust.upInches)try{window.SVR_PHASE334_SEAT_ADJUST?.(adjust)}catch{}seatChecked=true;window.SVR_PHASE335_SEAT_ACCEPTANCE={horizontalDistance:horizontal,heightAboveTable:height,adjustment:adjust,checkedAt:new Date().toISOString()}}
function rounded(g,x,y,w,h,r){g.beginPath();g.roundRect?.(x,y,w,h,r);if(!g.roundRect){g.rect(x,y,w,h)}g.closePath()}
function buildQa(){qaCanvas=document.createElement("canvas");qaCanvas.width=1024;qaCanvas.height=420;qaTexture=new THREE.CanvasTexture(qaCanvas);qaTexture.colorSpace=THREE.SRGBColorSpace;qaPanel=new THREE.Mesh(new THREE.PlaneGeometry(1.25,.51),new THREE.MeshBasicMaterial({map:qaTexture,transparent:true,opacity:.93,depthWrite:false,side:THREE.DoubleSide,toneMapped:false}));qaPanel.name="PHASE335_HEADSET_QA_PANEL";qaPanel.renderOrder=3358;qaPanel.visible=qaVisible;root.add(qaPanel);paintQa()}
function stateAge(){const s=snapshot(),key=`${s.handNo}:${s.phase}:${s.current}:${s.waitingHuman}:${s.pot}:${s.currentBet}:${s.lastAction}`;if(key!==lastStateKey){lastStateKey=key;lastStateAt=performance.now()}return{...s,stableForMs:performance.now()-lastStateAt}}
function paintQa(){if(!qaPanel)return;const s=stateAge(),g=qaCanvas.getContext("2d");g.clearRect(0,0,1024,420);g.fillStyle="rgba(2,7,15,.92)";rounded(g,12,12,1000,396,34);g.fill();g.strokeStyle="#7ffcff";g.lineWidth=9;g.stroke();g.textAlign="center";g.textBaseline="middle";g.fillStyle="#fff";g.font="900 52px system-ui";g.fillText("PHASE 335 HEADSET QA",512,66,930);g.fillStyle="#ffd98a";g.font="800 32px system-ui";g.fillText(`${s.phase.toUpperCase()} • HAND ${s.handNo} • POT $${s.pot}`,512,125,930);g.fillStyle="#dffeff";g.font="700 27px system-ui";[`VIEW ${hiddenDisplays} OLD DISPLAYS HIDDEN`,`CHIPS ${chips().length} ACTIVE • ${recoveredChips} RECOVERED`,`CARDS ${cards().length} VISIBLE • ${repairedCards} REPAIRED`,`BOTS ${Math.min(5,bots().length)} / 5 • ${repairedBots} REPAIRED`,`INPUT ${blockedActions} DUPLICATE ACTIONS BLOCKED`].forEach((x,i)=>g.fillText(x,512,188+i*42,940));qaTexture.needsUpdate=true;const sgn=sign(),cam=cameraWorld(A);qaPanel.position.set(tableInfo.center.x,tableInfo.surfaceY+1.35,tableInfo.center.z-sgn*tableInfo.depth*.56);qaPanel.lookAt(cam.x,qaPanel.position.y,cam.z)}
function qa(){const s=stateAge(),p=cameraWorld(new THREE.Vector3());return{build:BUILD,active:installed,xrPresenting:!!renderer?.xr?.isPresenting,table:tableInfo?.table?.name||null,camera:[p.x,p.y,p.z],phase:s.phase,handNo:s.handNo,waitingHuman:s.waitingHuman,pot:s.pot,actionBar:!!scene?.getObjectByName?.("PHASE333_XR_ACTION_BAR"),phase334Layout:!!window.SVR_PHASE334_STATE,chipCount:chips().length,recoveredChips,cardCount:cards().length,repairedCards,botCount:Math.min(5,bots().length),repairedBots,hiddenDisplays,blockedActions,barRecoveries,qaVisible,siteTouched:false,checkedAt:new Date().toISOString()}}
function tick(){if(!installed)return;tableInfo=detectTable()||tableInfo;wrapAction();hideDom();hideOld();placePanels();recoverChips();stabilizeCards();stabilizeBots();seatCheck();if(qaVisible)paintQa()}
function xrTick(t){const s=renderer?.xr?.getSession?.();if(!s||s!==xrSession)return;tick(t);s.requestAnimationFrame(xrTick)}
function startXR(){const s=renderer?.xr?.getSession?.();if(!s||s===xrSession)return;xrSession=s;seatChecked=false;s.requestAnimationFrame(xrTick)}
async function install(){if(installed)return;scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer){setTimeout(install,250);return}tableInfo=detectTable();if(!tableInfo){setTimeout(install,350);return}installed=true;root=new THREE.Group();root.name="PHASE335_OCULUS_ACCEPTANCE_ROOT";scene.add(root);buildQa();tick();renderer.xr.addEventListener("sessionstart",()=>setTimeout(startXR,100));renderer.xr.addEventListener("sessionend",()=>{xrSession=null;seatChecked=false});if(renderer.xr.isPresenting)startXR();setInterval(tick,220);window.SVR_PHASE335_TABLE_QA=qa;window.SVR_PHASE335_SHOW_QA=()=>{qaVisible=true;qaPanel.visible=true;paintQa();return true};window.SVR_PHASE335_HIDE_QA=()=>{qaVisible=false;qaPanel.visible=false;return false};window.SVR_PHASE335_RECENTER=()=>{seatChecked=false;try{window.SVR_PHASE334_REAPPLY_LAYOUT?.()}catch{}setTimeout(seatCheck,180);return qa()};window.SVR_PHASE335_RECOVER_TABLE=()=>{try{window.SVR_PHASE334_REAPPLY_LAYOUT?.()}catch{}tick();return qa()};window.SVR_PHASE335_STATE={build:BUILD,oculusAcceptance:true,fullHandStability:true,clearSightlineGovernor:true,seatedAutoCorrection:true,chipRecovery:true,cardVisibilityRepair:true,fiveBotGovernor:true,duplicateActionDebounce:true,qaHiddenByDefault:!QA_QUERY,phase334Preserved:true,siteTouched:false};window.SVR_LOCKED_FINAL_BUILD=BUILD}
install();[500,1200,2600,5200].forEach(t=>setTimeout(install,t));
