/* PHASE-389-CAMERA3-LIVE-PREVIEW-ROUTE-LOCK */
import * as THREE from 'three';
export const BUILD='PHASE-389-CAMERA3-LIVE-PREVIEW-ROUTE-LOCK';
const params=new URLSearchParams(location.search);
const ACTIVE=/\/game\/(?:camera3-live|camera3|cam3)\.html$/i.test(location.pathname)||params.get('cam')==='director'||params.has('director')||params.has('preview');
const state={build:BUILD,active:ACTIVE,installed:false,tableReady:false,lightingReady:false,cameraReady:false,tableName:null,visibleMeshes:0,materialRepairs:0,lightCount:0,shotIndex:0,frames:0,fps:0,lastError:null,checkedAt:null};
let scene=null,camera=null,renderer=null,table=null,lightRoot=null,raf=0,timer=0,lastFrame=performance.now(),fpsAt=performance.now(),fpsFrames=0,shotStarted=performance.now();
const center=new THREE.Vector3(),size=new THREE.Vector3(),target=new THREE.Vector3(),from=new THREE.Vector3(),to=new THREE.Vector3();
function walk(root,fn,limit=26000){const stack=root?[root]:[],seen=new Set();while(stack.length&&seen.size<limit){const object=stack.pop();if(!object||seen.has(object))continue;seen.add(object);try{fn(object)}catch{}for(const child of object.children||[])if(child&&!seen.has(child))stack.push(child)}}
function bounds(object){object?.updateWorldMatrix?.(true,true);const box=new THREE.Box3().setFromObject(object,true);return{box,size:box.getSize(new THREE.Vector3()),center:box.getCenter(new THREE.Vector3()),top:box.max.y}}
function validTable(object){try{const info=bounds(object);return !info.box.isEmpty()&&info.size.x>1.15&&info.size.z>.62&&info.size.y>.05}catch{return false}}
function scoreTable(object){const name=String(object?.name||'');let score=0;if(/PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY/i.test(name))score+=200;if(/PHASE373_VISIBLE_TABLE_GLB_AUTHORITY/i.test(name))score+=180;if(/PHASE159_ACTUAL_UPLOADED_TABLE/i.test(name))score+=160;if(/INTENDED_LOBBY_POKER_TABLE|TABLE_FBX|POKER_TABLE/i.test(name))score+=100;if(/fallback|procedural/i.test(name))score-=30;try{const info=bounds(object);score+=Math.min(80,(info.size.x+info.size.z)*8)}catch{}return score}
function findTable(){const direct=[window.SVR_TABLE_AUTHORITY,window.SVR_PHASE380_ORIGINAL_TABLE,scene?.getObjectByName?.('PHASE380_ORIGINAL_UPLOADED_TABLE_GLB_AUTHORITY'),scene?.getObjectByName?.('PHASE373_VISIBLE_TABLE_GLB_AUTHORITY'),scene?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED'),scene?.getObjectByName?.('PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED')].filter(Boolean);const candidates=[...direct];walk(scene,object=>{if(object?.isObject3D&&/table/i.test(String(object.name||''))&&validTable(object))candidates.push(object)});const unique=[...new Set(candidates)].filter(validTable);unique.sort((a,b)=>scoreTable(b)-scoreTable(a));return unique[0]||null}
function ensureVisible(root){let meshes=0;walk(root,object=>{object.visible=true;if(!object?.isMesh)return;object.frustumCulled=false;meshes++;const materials=Array.isArray(object.material)?object.material:[object.material];for(const material of materials.filter(Boolean)){material.visible=true;material.transparent=Boolean(material.transparent);if(material.map){material.map.colorSpace=THREE.SRGBColorSpace;material.map.needsUpdate=true;material.color?.set?.(0xffffff)}else if(material.color?.getHSL){const hsl={};material.color.getHSL(hsl);if(hsl.l<.045){material.color.set(0x211028);state.materialRepairs++}}if(material.emissive&&'emissiveIntensity'in material){if(material.emissive.getHex?.()===0)material.emissive.copy(material.color||new THREE.Color(0x111111)).multiplyScalar(.08);material.emissiveIntensity=Math.max(.08,Number(material.emissiveIntensity||0))}material.side=THREE.DoubleSide;material.needsUpdate=true}});state.visibleMeshes=meshes}
function makeLights(info){if(!scene)return null;if(lightRoot?.parent)lightRoot.removeFromParent();lightRoot=new THREE.Group();lightRoot.name='PHASE389_CAMERA3_PRODUCTION_LIGHTING';const hemi=new THREE.HemisphereLight(0xe8fbff,0x1d0929,3.3);const ambient=new THREE.AmbientLight(0xffffff,1.7);const key=new THREE.DirectionalLight(0xfff3df,5.2);const fill=new THREE.DirectionalLight(0x9cecff,3.8);const rim=new THREE.PointLight(0xa26cff,4.6,Math.max(12,info.size.length()*3),1.6);const gold=new THREE.PointLight(0xffd98a,3.2,Math.max(10,info.size.length()*2.5),1.7);const spot=new THREE.SpotLight(0xffffff,12,Math.max(14,info.size.length()*4),Math.PI/3.4,.55,1);hemi.name='PHASE389_CAMERA3_HEMISPHERE';ambient.name='PHASE389_CAMERA3_AMBIENT';key.name='PHASE389_CAMERA3_KEY';fill.name='PHASE389_CAMERA3_FILL';rim.name='PHASE389_CAMERA3_RIM';gold.name='PHASE389_CAMERA3_GOLD';spot.name='PHASE389_CAMERA3_TABLE_SPOT';key.position.set(info.center.x+info.size.x*1.3,info.top+5.5,info.center.z+info.size.z*1.1);fill.position.set(info.center.x-info.size.x*1.2,info.top+3.7,info.center.z+info.size.z*.5);rim.position.set(info.center.x,info.top+2.5,info.center.z-info.size.z*1.7);gold.position.set(info.center.x+info.size.x*.75,info.top+1.6,info.center.z+info.size.z*.65);spot.position.set(info.center.x,info.top+5.2,info.center.z+.15);for(const light of [key,fill,spot]){light.castShadow=false;light.target.position.set(info.center.x,info.top+.05,info.center.z)}lightRoot.add(hemi,ambient,key,key.target,fill,fill.target,rim,gold,spot,spot.target);scene.add(lightRoot);state.lightCount=7;state.lightingReady=true;return lightRoot}
function tuneRenderer(){if(!renderer)return false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.48;renderer.shadowMap.enabled=false;renderer.setPixelRatio(Math.min(1.35,window.devicePixelRatio||1));renderer.setClearColor?.(0x050814,1);return true}
function hideDomOverlays(){document.querySelectorAll('body>*').forEach(element=>{if(element.id==='app'||element.id==='camera3LiveStatus'||element.tagName==='SCRIPT')return;if(element.tagName==='CANVAS'&&element.id!=='binary-rain')return;if(element.id==='safeStage')return;element.style.display='none'});document.querySelectorAll('#app+*,.hud,.controls,.watch,.debug,.panel,.overlay').forEach(element=>{if(element.id!=='camera3LiveStatus')element.style.display='none'})}
function shotPositions(info){const radius=Math.max(3.2,Math.max(info.size.x,info.size.z)*1.25);const high=info.top+Math.max(2.25,info.size.z*.9);const low=info.top+Math.max(1.35,info.size.z*.55);return[
 new THREE.Vector3(info.center.x,high,info.center.z+radius),
 new THREE.Vector3(info.center.x+radius*.88,low,info.center.z+radius*.68),
 new THREE.Vector3(info.center.x-radius*.82,low+.35,info.center.z+radius*.72),
 new THREE.Vector3(info.center.x+radius*.62,high+.35,info.center.z-radius*.72),
 new THREE.Vector3(info.center.x-radius*.58,high*.98,info.center.z-radius*.66)
]}
function setShot(info,index,immediate=false){const shots=shotPositions(info);state.shotIndex=((index%shots.length)+shots.length)%shots.length;from.copy(camera.position);to.copy(shots[state.shotIndex]);target.set(info.center.x,info.top+.1,info.center.z);shotStarted=performance.now();if(immediate){camera.position.copy(to);camera.lookAt(target)}}
function frame(now){if(!state.installed)return;try{const info=table?bounds(table):null;if(info&&camera&&renderer){const elapsed=(now-shotStarted)/1000;if(elapsed>7.2)setShot(info,state.shotIndex+1);const t=Math.min(1,(now-shotStarted)/1400),smooth=t*t*(3-2*t);camera.position.lerpVectors(from,to,smooth);camera.lookAt(target);camera.updateProjectionMatrix?.();state.frames++;fpsFrames++;if(now-fpsAt>1000){state.fps=Math.round(fpsFrames*1000/Math.max(1,now-fpsAt));fpsFrames=0;fpsAt=now}lastFrame=now}}catch(error){state.lastError=String(error?.message||error)}raf=requestAnimationFrame(frame)}
async function enforce(reason='interval'){scene=window.__SVR_SCENE__||scene;camera=window.__SVR_CAMERA__||camera;renderer=window.__SVR_RENDERER__||renderer;if(!scene||!camera||!renderer)return false;try{window.SVR_PHASE380_ORIGINAL_TABLE_REASSERT?.(`camera3-${reason}`);window.SVR_PHASE379_FORCE_TABLE?.(`camera3-${reason}`)}catch{}table=findTable()||table;if(!table)return false;ensureVisible(table);const info=bounds(table);makeLights(info);tuneRenderer();scene.background=new THREE.Color(0x050814);scene.fog=null;target.set(info.center.x,info.top+.1,info.center.z);if(!state.cameraReady){setShot(info,0,true);state.cameraReady=true}table.visible=true;hideDomOverlays();document.body.classList.add('boot-released','phase389-camera3-live');document.getElementById('safeStage')?.remove();const status=document.getElementById('camera3LiveStatus');if(status){status.textContent='CAM 3 LIVE • TABLE FEED';status.dataset.ready='true'}state.tableReady=true;state.installed=true;state.lastReason=reason;state.checkedAt=new Date().toISOString();return true}
async function install(){if(!ACTIVE||state.installed)return;const started=performance.now();while(performance.now()-started<30000){if(await enforce('boot'))break;await new Promise(resolve=>setTimeout(resolve,120))}if(!state.tableReady){state.lastError='CAMERA3_TABLE_NOT_READY';return}for(const delay of [120,450,1100,2400,4800])setTimeout(()=>void enforce(`burst-${delay}`),delay);timer=setInterval(()=>void enforce('heartbeat'),3200);raf=requestAnimationFrame(frame);window.addEventListener('beforeunload',()=>{clearInterval(timer);cancelAnimationFrame(raf)},{once:true});window.addEventListener('svr:platform-ready',()=>void enforce('platform-ready'));window.addEventListener('svr:phase389-core-ready',()=>void enforce('phase389-ready'))}
function qa(){state.checkedAt=new Date().toISOString();const info=table?bounds(table):null;return{...state,tableSize:info?{x:+info.size.x.toFixed(3),y:+info.size.y.toFixed(3),z:+info.size.z.toFixed(3)}:null,exposure:renderer?.toneMappingExposure??null,drawCalls:renderer?.info?.render?.calls??null,triangles:renderer?.info?.render?.triangles??null,pass:Boolean(state.installed&&state.tableReady&&state.lightingReady&&state.cameraReady&&state.lightCount>=6&&Number(renderer?.toneMappingExposure||0)>=1.35),checkedAt:new Date().toISOString()}}
if(ACTIVE)install().catch(error=>state.lastError=String(error?.stack||error));
window.SVR_PHASE389_CAMERA3_ENFORCE=enforce;
window.SVR_PHASE389_CAMERA3_STATE=state;
window.SVR_PHASE389_CAMERA3_QA=qa;
