import * as THREE from 'three';
const LABEL='PHASE-212-STABLE-POKER-LABELS-CHIPS-LOCK';
let scene,started=false,stableRoot=null,lastBuild=0;
function root(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function table(){const r=root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function bounds(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c};}
function labelTex(a,b=''){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.82)';x.fillRect(0,0,512,160);x.strokeStyle='#ffd98a';x.lineWidth=6;x.strokeRect(10,10,492,140);x.fillStyle='#fff';x.font='900 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(a,256,58,470);x.fillStyle='#7ffcff';x.font='800 24px system-ui';x.fillText(b,256,108,470);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function makeLabel(parent,name,pos,text,sub){const m=new THREE.Mesh(new THREE.PlaneGeometry(1.05,.32),new THREE.MeshBasicMaterial({map:labelTex(text,sub),transparent:true,side:THREE.DoubleSide,depthWrite:false}));m.name=name;m.position.copy(pos);m.rotation.x=-Math.PI/8;m.renderOrder=2120;parent.add(m);return m;}
function makeChip(parent,name,pos,color=0xffd98a,count=5){for(let i=0;i<count;i++){const chip=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.018,24),new THREE.MeshStandardMaterial({color,roughness:.5,metalness:.12}));chip.name=`${name}_${i}`;chip.position.set(pos.x,pos.y+i*.019,pos.z);chip.renderOrder=2120;parent.add(chip);}}
function hideDynamic(){let hidden=0;root()?.traverse?.(o=>{const n=String(o.name||'');if(/ACTION_LABEL|OPEN_PLAYER_SEAT_LABEL|TABLE_STATUS_FLOATING|PHASE168_.*CHIP|PHASE168_CENTER_POT/i.test(n)){o.visible=false;o.traverse?.(c=>c.visible=false);hidden++;}});return hidden;}
function buildStable(){scene=window.__SVR_SCENE__;if(!scene)return null;const r=root(),t=table();if(!t)return null;hideDynamic();const old=r.getObjectByName?.('PHASE212_STABLE_POKER_LABELS_CHIPS_ROOT');if(old)old.parent?.remove(old);stableRoot=new THREE.Group();stableRoot.name='PHASE212_STABLE_POKER_LABELS_CHIPS_ROOT';r.add(stableRoot);const bb=bounds(t),c=bb.c,w=Math.max(bb.s.x,4),d=Math.max(bb.s.z,2.2),y=bb.b.max.y+.08;const seats=[['YOU',0,d*.88,0x7ffcff],['NOVA',-w*.47,d*.58,0xff5b8c],['ROOK',-w*.58,-d*.06,0xff5b8c],['ACE',0,-d*.78,0xff5b8c],['VEGA',w*.58,-d*.06,0xff5b8c],['IVY',w*.47,d*.58,0xff5b8c]];seats.forEach(([name,x,z,color],i)=>{const px=c.x+x,pz=c.z+z;makeLabel(stableRoot,`PHASE212_STABLE_LABEL_${name}`,new THREE.Vector3(px,y+.42,pz),name,i===0?'OPEN SEAT':'BOT READY');const toward=new THREE.Vector3(c.x-px,0,c.z-pz).normalize();makeChip(stableRoot,`PHASE212_STABLE_CHIPS_${name}`,new THREE.Vector3(px+toward.x*.45,y,pz+toward.z*.45),color,5);});makeLabel(stableRoot,'PHASE212_STABLE_TABLE_STATUS',new THREE.Vector3(c.x,y+.58,c.z-d*.55),'POT 75','TABLE READY');makeChip(stableRoot,'PHASE212_STABLE_POT',new THREE.Vector3(c.x,y,c.z+d*.12),0xffd98a,8);return {labels:7,chipStacks:7,table:t.name,y:+y.toFixed(3)};}
function pass(){const hidden=hideDynamic();let built=null;if(!stableRoot||performance.now()-lastBuild>3000){built=buildStable();lastBuild=performance.now();}const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,dynamicHidden:hidden,stableBuilt:!!(stableRoot),built,checkedAt:new Date().toISOString()};window.SVR_PHASE212_STABLE_POKER_LABELS_CHIPS_LOCK=out;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;return out;}
function install(){scene=window.__SVR_SCENE__;if(!scene)return false;buildStable();window.SVR_RUN_PHASE212_STABLE_AUDIT=()=>pass();if(!started){started=true;setInterval(pass,250);}return true;}
[500,1200,2400,4500,8000].forEach(ms=>setTimeout(install,ms));install();
