import * as THREE from'three';
import{state,players,BUILD}from'./phase336_authoritative_engine.js';
let timer=null;const S=()=>window.__SVR_SCENE__||null,R=()=>S()?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||S();
function table(){const r=R();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||r?.getObjectByName?.('PHASE200_INTENDED_LOBBY_POKER_TABLE_LOCKED')}
function info(){const t=table();if(!t)return null;t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c,top:b.max.y,w:Math.max(1.4,Math.min(s.x*.52,3.4)),d:Math.max(.8,Math.min(s.z*.4,1.7))}}
function tex(card,hidden=false){const c=document.createElement('canvas');c.width=512;c.height=720;const g=c.getContext('2d');g.fillStyle=hidden?'#17133f':'#f7f5ef';g.fillRect(0,0,512,720);g.strokeStyle=hidden?'#7ffcff':'#202020';g.lineWidth=18;g.strokeRect(12,12,488,696);if(hidden){g.fillStyle='#fff';g.font='900 72px system-ui';g.textAlign='center';g.fillText('SVR',256,382)}else{const suit={S:'♠',H:'♥',D:'♦',C:'♣'}[card?.s]||'',red=['H','D'].includes(card?.s);g.fillStyle=red?'#b51632':'#111';g.textAlign='center';g.textBaseline='middle';g.font='900 190px serif';g.fillText(card?.r||'?',256,250);g.font='900 210px serif';g.fillText(suit,256,495)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function label(lines,accent='#ffd98a'){const c=document.createElement('canvas');c.width=512;c.height=256;const g=c.getContext('2d');g.fillStyle='rgba(3,7,15,.9)';g.fillRect(0,0,512,256);g.strokeStyle=accent;g.lineWidth=7;g.strokeRect(8,8,496,240);g.fillStyle='#fff';g.textAlign='center';g.textBaseline='middle';lines.forEach((x,i)=>{g.font=i?'800 34px system-ui':'900 72px system-ui';g.fillText(x,256,82+i*72,470)});const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function plane(root,name,p,w,h,map){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map,transparent:true,depthWrite:false,side:THREE.DoubleSide,toneMapped:false}));m.name=name;m.position.copy(p);m.rotation.x=-Math.PI/2;m.renderOrder=8500;root.add(m);return m}
export function draw(){const scene=S(),root=R(),i=info();if(!scene||!root||!i)return false;root.getObjectByName?.('PHASE85_POKER_TRUTH_TABLE_LAYER')?.removeFromParent?.();const group=new THREE.Group();group.name='PHASE85_POKER_TRUTH_TABLE_LAYER';root.add(group);const y=i.top+.018;state.community.forEach((c,n)=>plane(group,`P85_COMM_${n}`,new THREE.Vector3(i.c.x+(n-2)*.245,y+.035,i.c.z),.21,.305,tex(c)));players.forEach((p,n)=>{const a=-Math.PI/2+n*Math.PI*2/players.length,x=i.c.x+Math.cos(a)*i.w*.57,z=i.c.z+Math.sin(a)*i.d*.76;const tag=plane(group,`P85_TAG_${n}`,new THREE.Vector3(x,y+1.05,z),.58,.16,label([p.name,p.folded?'FOLD':`$${p.stack}`],p.human?'#7ffcff':'#ffd98a'));tag.rotation.x=0;tag.lookAt(i.c.x,y+.82,i.c.z);p.hand.forEach((c,k)=>plane(group,`P85_HAND_${n}_${k}`,new THREE.Vector3(x+(k-.5)*.17,y+.025,z),.17,.245,tex(c,!(p.human||state.phase==='showdown'))))});const pot=plane(group,'P85_POT_LABEL',new THREE.Vector3(i.c.x,y+.028,i.c.z+i.d*.22),.64,.18,label([`POT $${state.pot}`]));pot.userData.phase336Pot=true;window.SVR_PHASE336_VISUAL={build:BUILD,cards:state.community.length,players:players.length,drawnAt:new Date().toISOString()};return true}
export function bootVisual(){window.addEventListener('svr:poker-state',()=>{clearTimeout(timer);timer=setTimeout(draw,0)});[300,900,1800,3200].forEach(ms=>setTimeout(draw,ms));window.SVR_PHASE336_REDRAW=draw}
