import * as THREE from 'three';
const LABEL='PHASE-182-TABLE-FIT-LOCK';
const ROOT='PHASE182_TABLE_FIT_ROOT';
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function getTable(root){const t=root?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||root?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED'); if(!t)return null; t.updateMatrixWorld(true); const b=new THREE.Box3().setFromObject(t),c=new THREE.Vector3(),sz=new THREE.Vector3(); b.getCenter(c); b.getSize(sz); return {box:b,center:c,size:sz};}
function material(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function makeBand(ox,oz,ix,iz){const s=new THREE.Shape(); s.absellipse(0,0,ox/2,oz/2,0,Math.PI*2,false,0); const h=new THREE.Path(); h.absellipse(0,0,ix/2,iz/2,0,Math.PI*2,true,0); s.holes.push(h); return new THREE.ShapeGeometry(s,128);}
function install(){const scene=window.__SVR_SCENE__; if(!scene)return false; const root=sr(scene),r=getTable(root); if(!r)return false; const old=root.getObjectByName?.(ROOT); if(old)old.parent?.remove(old); const g=new THREE.Group(); g.name=ROOT; g.position.set(r.center.x,r.box.max.y+.13,r.center.z); root.add(g); const long=Math.max(r.size.x,r.size.z),short=Math.min(r.size.x,r.size.z); const ow=Math.min(5.55,Math.max(3.0,long*.98)), od=Math.min(3.15,Math.max(1.4,short*.90)); const fw=ow*.66, fd=od*.54; const outer=new THREE.Mesh(makeBand(ow,od,fw*1.03,fd*1.03),material(0x1f120d,.92)); outer.name='PHASE182_TABLE_OUTER_FIT'; outer.rotation.x=-Math.PI/2; outer.renderOrder=1820; g.add(outer); const felt=new THREE.Mesh(new THREE.PlaneGeometry(fw,fd),material(0x064426,.95)); felt.name='PHASE182_TABLE_FELT_FIT'; felt.rotation.x=-Math.PI/2; felt.position.y=.018; felt.renderOrder=1821; g.add(felt); const mark=new THREE.Mesh(makeBand(fw*.88,fd*.82,fw*.82,fd*.76),material(0xeebf5c,.82)); mark.name='PHASE182_TABLE_LINE_FIT'; mark.rotation.x=-Math.PI/2; mark.position.y=.021; mark.renderOrder=1822; g.add(mark); window.SVR_PHASE182_TABLE_FIT_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,center:{x:+r.center.x.toFixed(3),z:+r.center.z.toFixed(3)},felt:{w:+fw.toFixed(3),d:+fd.toFixed(3)},outer:{w:+ow.toFixed(3),d:+od.toFixed(3)},checkedAt:new Date().toISOString()}; window.SVR_RUN_PHASE182_TABLE_AUDIT=()=>window.SVR_PHASE182_TABLE_FIT_LOCK; window.SVR_LOCKED_FINAL_BUILD=LABEL; window.SVR_LIVE_BUILD_POINTER=LABEL; return true;}
[500,1400,3000,6500].forEach(ms=>setTimeout(install,ms)); install();
