import * as THREE from 'three';
const LABEL='PHASE-206-VISUAL-ALIGNMENT-POLISH-LOCK';
let scene,started=false;
function root(){return scene?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||scene;}
function table(){const r=root();return r?.getObjectByName?.('PHASE159_ACTUAL_UPLOADED_TABLE_FBX_FLAT_SCALED')||r?.getObjectByName?.('PHASE159_FBX_TABLE_FLAT_SCALE_FIX_ROOT')||null;}
function box(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{b,s,c};}
function tex(){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');x.fillStyle='#052715';x.fillRect(0,0,512,256);x.strokeStyle='#ffd98a';x.lineWidth=5;x.beginPath();x.ellipse(256,128,215,92,0,0,Math.PI*2);x.stroke();x.fillStyle='#7ffcff';x.font='900 34px system-ui';x.textAlign='center';x.fillText('SVR',256,122);x.fillStyle='#ffd98a';x.font='900 16px system-ui';x.fillText('POKER',256,154);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function hideOld(r){let n=0;r.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE168_TABLE_SURFACE|PHASE168_GREEN_FELT|PHASE167_FBX_TABLE_FELT|PHASE205_SINGLE_LOW_FELT/i.test(nm)){o.visible=false;o.traverse?.(c=>c.visible=false);n++;}});return n;}
function surface(r,bb){const old=r.getObjectByName?.('PHASE206_ONE_TABLE_SURFACE_ROOT');if(old)old.parent?.remove(old);const g=new THREE.Group();g.name='PHASE206_ONE_TABLE_SURFACE_ROOT';g.position.set(bb.c.x,bb.b.max.y+0.003,bb.c.z);r.add(g);const w=Math.max(1.4,Math.min(bb.s.x*.58,3.8)),d=Math.max(.8,Math.min(bb.s.z*.48,2.0));const m=new THREE.Mesh(new THREE.PlaneGeometry(w,d),new THREE.MeshBasicMaterial({map:tex(),side:THREE.DoubleSide,depthWrite:false}));m.name='PHASE206_ONE_LOW_FELT';m.rotation.x=-Math.PI/2;m.renderOrder=2060;g.add(m);return{w:+w.toFixed(3),d:+d.toFixed(3),y:+g.position.y.toFixed(3)};}
function objects(r,bb){let cards=0,chips=0,bots=0;const y=bb.b.max.y+0.014;r.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE168_DEMO_CARD/i.test(nm)){o.position.y=y;o.rotation.x=-Math.PI/2;cards++;}else if(/PHASE168_.*CHIP/i.test(nm)){o.position.y=Math.min(o.position.y,bb.b.max.y+.2);chips++;}else if(/PHASE168_BOT_PILL_AVATAR_/i.test(nm)){o.position.y=bb.b.min.y+.18;bots++;}});return{cards,chips,bots,cardY:+y.toFixed(3)};}
function planets(){const moons=[],mars=[];scene?.traverse?.(o=>{const n=String(o.name||'');if(/moon/i.test(n)&&!/mars/i.test(n))moons.push(o);if(/mars/i.test(n))mars.push(o);});const km=moons.find(o=>/PHASE196_ROTATING_MOON/i.test(o.name))||moons[0];const kr=mars.find(o=>/PHASE196_MARS/i.test(o.name))||mars[0];moons.forEach(o=>{const v=o===km||km?.parent===o;o.visible=v;o.traverse?.(c=>c.visible=v);});mars.forEach(o=>{const v=o===kr||kr?.parent===o;o.visible=v;o.traverse?.(c=>c.visible=v);});return{moonCount:moons.length,marsCount:mars.length,keptMoon:km?.name||null,keptMars:kr?.name||null};}
function lobby(r){let n=0;r.traverse?.(o=>{const nm=String(o.name||'');if(/PHASE194_EXPANDED|PHASE195_PORTAL|PHASE195_ROOM|PHASE196_SKY/i.test(nm)){o.visible=true;n++;}});return{visible:n};}
function pass(){scene=window.__SVR_SCENE__;if(!scene)return null;const r=root(),t=table();if(!t){window.SVR_PHASE206_VISUAL_ALIGNMENT_POLISH_LOCK={build:LABEL,active:false,reason:'table-not-found',checkedAt:new Date().toISOString()};return window.SVR_PHASE206_VISUAL_ALIGNMENT_POLISH_LOCK;}const bb=box(t);const out={build:LABEL,active:true,gameOnly:true,siteTouched:false,table:t.name,tableTop:+bb.b.max.y.toFixed(3),hiddenOldSurfaces:hideOld(r),surface:surface(r,bb),objects:objects(r,bb),planets:planets(),lobby:lobby(r),checkedAt:new Date().toISOString()};window.SVR_PHASE206_VISUAL_ALIGNMENT_POLISH_LOCK=out;return out;}
function install(){const o=pass();window.SVR_RUN_PHASE206_POLISH_AUDIT=()=>pass();window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(pass,1200);}return !!o;}
[700,1600,3200,6000,10000,15000].forEach(ms=>setTimeout(install,ms));install();
