/* PHASE-411-TOURNAMENT-100-FIELD-ROTATION-LOCK */
const BUILD='PHASE-411-TOURNAMENT-100-FIELD-ROTATION-LOCK';
const STORAGE='svr401_reiki_first50_tournament',RESULTS='svr401_reiki_first50_results',ARCHIVE='svr405_tournament_archive';
const FIELD=Math.max(10,Math.min(199,Number(localStorage.getItem('svr411_tournament_field_size')||100)||100));
const SLOT_MS=5*60*60*1000,ANCHOR=Date.UTC(2026,0,1,0,0,0);
const params=new URLSearchParams(location.search),ACTIVE=String(params.get('mode')||'').toLowerCase()==='tournament';
const FIRST=['Alex','Jordan','Taylor','Morgan','Chris','Riley','Casey','Avery','Cameron','Skyler','Quinn','Parker','Dakota','Reese','Rowan','Jamie','Drew','Blake','Kendall','Reagan'];
const LAST=['Ace','River','Stone','King','Vale','Fox','Lane','Storm','Reed','Knight'];
const runtime={build:BUILD,fieldSize:FIELD,installed:false,lastSeatSignature:'',tableMoves:0,finalTableShown:false,lastLeft:null,lastError:null};
const $=s=>document.querySelector(s),now=()=>Date.now(),slotId=t=>Math.floor((t-ANCHOR)/SLOT_MS);
function playerName(){try{const p=JSON.parse(localStorage.getItem('svr_demo_account')||'{}')?.profile;return p?.displayName||localStorage.getItem('svr405_guest_name')||'Guest 1'}catch{return'Guest 1'}}
function botName(i){const a=FIRST[i%FIRST.length],b=LAST[Math.floor(i/FIRST.length)%LAST.length],n=Math.floor(i/(FIRST.length*LAST.length))+1;return n>1?`${a} ${b} ${n}`:`${a} ${b}`}
function makeBot(i){return{id:`phase411-bot-${String(i+1).padStart(3,'0')}`,name:botName(i),isUser:false,stack:10000,status:'active',place:null,seat:null,aiLevel:(i%5)+1}}
function read(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')}catch{return null}}
function write(t){t.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE,JSON.stringify(t));window.SVR_PHASE411_TOURNAMENT_STATE=t;return t}
function fresh(){const t={version:411,id:'reiki-first-50',name:'REIKI OPEN 100 TEST',sponsor:'REIKI',status:'in_progress',registrationCap:FIELD,testFieldSize:FIELD,phase411FieldSize:FIELD,phase411SlotId:slotId(now()),round:0,startedAt:new Date().toISOString(),completedAt:null,champion:null,prizePlayChips:100000,prizeAwarded:false,regularStackBefore:Math.max(0,Number(localStorage.getItem('svr393stack')||15000)),entrants:[{id:'user',name:playerName(),isUser:true,stack:10000,status:'active',place:null,seat:0,aiLevel:0}],eliminations:[],lastHand:null};for(let i=0;i<FIELD-1;i++)t.entrants.push(makeBot(i));return write(t)}
function normalize(){if(!ACTIVE)return read();let t=read();if(t?.status==='completed')return t;if(!t||!Array.isArray(t.entrants)||!t.entrants.length)t=fresh();const user=t.entrants.find(e=>e.isUser)||{id:'user',name:playerName(),isUser:true,stack:10000,status:'active',place:null,seat:0,aiLevel:0};user.name=user.name||playerName();const existingBots=t.entrants.filter(e=>!e.isUser);const used=new Set(t.entrants.map(e=>e.id));for(let i=0;t.entrants.length<FIELD;i++){const b=makeBot(i);if(used.has(b.id))continue;t.entrants.push(b);used.add(b.id)}if(t.entrants.length>FIELD)t.entrants=[user,...existingBots.slice(0,FIELD-1)];t.registrationCap=FIELD;t.testFieldSize=FIELD;t.phase411FieldSize=FIELD;t.phase411SlotId??=slotId(now());t.version=411;t.name='REIKI OPEN 100 TEST';return write(t)}
function active(t=read()){return(t?.entrants||[]).filter(e=>e.status==='active'&&Number(e.stack)>0)}
function ensureOverlay(){let el=$('#phase411TournamentMove');if(el)return el;el=document.createElement('div');el.id='phase411TournamentMove';el.className='phase411-tournament-move';el.innerHTML='<strong>GATHERING TABLE</strong><span>Preparing your next table…</span>';document.body.appendChild(el);return el}
function transition(title,copy){const el=ensureOverlay();el.querySelector('strong').textContent=title;el.querySelector('span').textContent=copy;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function seatSignature(){const g=window.SVR_PHASE393_ANDROID_STATE;return(g?.players||[]).map(p=>p.tournamentId||'-').join('|')}
function updateGame(){if(!ACTIVE)return;const t=normalize(),left=active(t).length,g=window.SVR_PHASE393_ANDROID_STATE;if(!t)return;const badge=$('.platform-badge'),gate=$('#gateStatus');if(badge)badge.textContent='REIKI • OPEN 100 TEST';if(gate)gate.textContent=`REIKI OPEN 100 • ${left||FIELD} players remaining • bot-filled local tournament test • live remote field requires secure backend.`;if(t.status==='completed'){if(!runtime.finalTableShown){runtime.finalTableShown=true;transition('TOURNAMENT COMPLETE','Results are ready. Start the next test field from the tournament page.')}return}if(!g)return;const hud=$('#phase401TournamentHud');if(hud){const f=hud.querySelector('[data-field]');if(f)f.textContent=`${left} LEFT / ${FIELD}`;const title=hud.querySelector('strong');if(title)title.textContent='REIKI OPEN 100'}const sig=seatSignature();if(runtime.lastSeatSignature&&sig&&sig!==runtime.lastSeatSignature&&g.hand>1&&left>6){runtime.tableMoves++;const table=Math.max(2,Math.floor((FIELD-left)/5)+1);transition('GATHERING TABLE',`Moving survivors to Table ${table} • ${left} players remain.`)}runtime.lastSeatSignature=sig||runtime.lastSeatSignature;if(left<=6&&left>1&&!runtime.finalTableShown){runtime.finalTableShown=true;transition('FINAL TABLE','Gathering the last players • final table seating now.')}runtime.lastLeft=left}
function readArchive(){try{return JSON.parse(localStorage.getItem(ARCHIVE)||'[]')}catch{return[]}}
function lastResult(){const archive=readArchive();if(archive.length){const r=[...archive].sort((a,b)=>(b.slotId||0)-(a.slotId||0))[0];return{champion:r.champion||'Bot Test Winner',completedAt:r.completedAt||r.startedAt,source:r.source||'bot-test'}}try{const r=JSON.parse(localStorage.getItem(RESULTS)||'null');if(r?.champion)return{champion:r.champion?.name||r.champion,completedAt:r.completedAt,source:'played'}}catch{}return null}
function nextSlot(){const current=slotId(now()),end=ANCHOR+(current+1)*SLOT_MS;return{at:end,ms:Math.max(0,end-now())}}
function countdown(ms){const total=Math.max(0,Math.floor(ms/1000)),h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return`${h}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`}
function updatePortal(){const next=$('#phase411NextTournament'),last=$('#phase411LastResult'),detail=$('#phase411LastDetail'),field=$('#phase411FieldCount');if(next){const n=nextSlot();next.textContent=countdown(n.ms);next.title=new Date(n.at).toLocaleString()}if(last){const r=lastResult();last.textContent=r?String(r.champion):'No result yet';if(detail)detail.textContent=r?`${String(r.source).toUpperCase()} • ${r.completedAt?new Date(r.completedAt).toLocaleString():'recent slot'}`:'The first completed five-hour slot will appear here.'}if(field)field.textContent=`${FIELD} PLAYER LOCAL TEST FIELD`}
function installShare(){const b=$('#phase411ShareTournament');if(!b||b.dataset.ready)return;b.dataset.ready='1';b.addEventListener('click',async()=>{const url=`${location.origin}/game/tournaments.html?v=phase411`,data={title:'SVR Poker Test Tournament',text:'SVR Poker play-money mobile tournament test',url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(url);b.textContent='LINK COPIED';setTimeout(()=>b.textContent='SHARE TEST TOURNAMENT',1500)}}catch{}})}
function poll(){try{if(ACTIVE)normalize();updateGame();updatePortal();installShare();runtime.installed=true;runtime.lastError=null}catch(e){runtime.lastError=String(e?.message||e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{poll();setInterval(poll,500)},{once:true});else{poll();setInterval(poll,500)}
window.SVR_PHASE411_TOURNAMENT_QA=()=>({build:BUILD,fieldSize:FIELD,activePlayers:active().length,tableMoves:runtime.tableMoves,finalTableShown:runtime.finalTableShown,nextSlot:nextSlot(),lastResult:lastResult(),localSimulationOnly:true,liveMultiplayer:false,sharedBackend:false,lastError:runtime.lastError,pass:Boolean(runtime.installed&&FIELD>=10&&FIELD<=199&&!runtime.lastError),checkedAt:new Date().toISOString()});
