/* PHASE-401-ANDROID-SPONSOR-TOURNAMENT-DIRECTOR-LOCK */
const BUILD='PHASE-401-ANDROID-SPONSOR-TOURNAMENT-DIRECTOR-LOCK';
const params=new URLSearchParams(location.search);
const MODE=String(params.get('mode')||'regular').toLowerCase();
const ACTIVE=MODE==='tournament';
const STORAGE='svr401_reiki_first50_tournament';
const RESULTS='svr401_reiki_first50_results';
const CONFIG={
  id:'reiki-first-50',name:'REIKI FIRST 50',sponsor:'REIKI',registrationCap:50,testFieldSize:10,
  visibleTableSeats:6,startingStack:10000,prizePlayChips:100000,roundsPerLevel:2,
  levels:[
    {smallBlind:50,bigBlind:100,ante:0},{smallBlind:75,bigBlind:150,ante:25},
    {smallBlind:100,bigBlind:200,ante:25},{smallBlind:150,bigBlind:300,ante:50},
    {smallBlind:200,bigBlind:400,ante:50},{smallBlind:300,bigBlind:600,ante:100},
    {smallBlind:400,bigBlind:800,ante:100},{smallBlind:500,bigBlind:1000,ante:150},
    {smallBlind:750,bigBlind:1500,ante:200},{smallBlind:1000,bigBlind:2000,ante:300}
  ]
};
const BOT_NAMES=['Claudia','Eric','Maya','Darius','Nova','Kai','Lena','Marcus','Zoe'];
const runtime={build:BUILD,active:ACTIVE,mode:MODE,lastError:null,checkedAt:null};
const $=s=>document.querySelector(s);
const now=()=>new Date().toISOString();
const money=n=>`$${Math.max(0,Math.round(Number(n||0))).toLocaleString()}`;
function userName(){try{const raw=JSON.parse(localStorage.getItem('svr_demo_account')||'{}');return raw?.profile?.displayName||raw?.displayName||'YOU'}catch{return'YOU'}}
function blank(){return{version:1,id:CONFIG.id,name:CONFIG.name,sponsor:CONFIG.sponsor,status:'available',registrationCap:CONFIG.registrationCap,testFieldSize:CONFIG.testFieldSize,round:0,level:0,startedAt:null,completedAt:null,champion:null,prizePlayChips:CONFIG.prizePlayChips,prizeAwarded:false,entrants:[],eliminations:[],lastHand:null,updatedAt:now()}}
function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE)||'null');if(parsed?.id===CONFIG.id)return parsed}catch{}return blank()}
function save(t){t.updatedAt=now();localStorage.setItem(STORAGE,JSON.stringify(t));window.SVR_PHASE401_TOURNAMENT_STATE=t;return t}
function activeEntrants(t){return(t.entrants||[]).filter(x=>x.status==='active'&&x.stack>0)}
function createField(){const t=blank(),you=userName();t.status='in_progress';t.startedAt=now();t.entrants=[{id:'user',name:you,isUser:true,stack:CONFIG.startingStack,status:'active',place:null,seat:0}];BOT_NAMES.slice(0,CONFIG.testFieldSize-1).forEach((name,i)=>t.entrants.push({id:`bot-${i+1}`,name,isUser:false,stack:CONFIG.startingStack,status:'active',place:null,seat:null}));return save(t)}
function ensureRunning(){let t=load();if(t.status!=='in_progress'||!(t.entrants||[]).length)t=createField();return t}
function levelFor(t){const index=Math.min(CONFIG.levels.length-1,Math.floor(Math.max(0,t.round||0)/CONFIG.roundsPerLevel));return{index,...CONFIG.levels[index]}}
function markEliminated(t,entrant){if(!entrant||entrant.status!=='active'||entrant.stack>0)return;const remaining=activeEntrants(t).length;entrant.status='eliminated';entrant.place=remaining+1;entrant.eliminatedAtRound=t.round;t.eliminations.push({id:entrant.id,name:entrant.name,place:entrant.place,round:t.round,at:now()})}
function simulateOffTable(t,seatedIds){const off=activeEntrants(t).filter(e=>!seatedIds.has(e.id)&&!e.isUser);if(!off.length)return;for(let i=0;i<off.length;i+=2){const a=off[i],b=off[i+1];if(!b)break;const swing=Math.max(100,Math.min(1200,Math.round(Math.min(a.stack,b.stack)*(.08+Math.random()*.12)/50)*50));if(Math.random()<.5){a.stack=Math.max(0,a.stack-swing);b.stack+=swing}else{b.stack=Math.max(0,b.stack-swing);a.stack+=swing}markEliminated(t,a);markEliminated(t,b)}if((t.round+1)%2===0){const survivors=off.filter(e=>e.status==='active');if(survivors.length&&activeEntrants(t).length>6){const victim=[...survivors].sort((a,b)=>a.stack-b.stack)[0],receiver=activeEntrants(t).filter(e=>e.id!==victim.id).sort((a,b)=>b.stack-a.stack)[0];if(victim&&receiver){receiver.stack+=victim.stack;victim.stack=0;markEliminated(t,victim)}}}}
function completeTournament(t,champion){if(t.status==='completed')return;t.status='completed';t.completedAt=now();t.champion={id:champion.id,name:champion.name,isUser:champion.isUser,stack:champion.stack};champion.place=1;activeEntrants(t).filter(e=>e.id!==champion.id).forEach(e=>{if(e.place==null)e.place=2});if(champion.isUser&&!t.prizeAwarded){const regular=Math.max(0,Number(localStorage.getItem('svr393stack')||15000));localStorage.setItem('svr393stack',String(regular+CONFIG.prizePlayChips));t.prizeAwarded=true}const results={id:t.id,name:t.name,sponsor:t.sponsor,completedAt:t.completedAt,champion:t.champion,prizePlayChips:CONFIG.prizePlayChips,prizeAwarded:t.prizeAwarded,placements:[...t.entrants].sort((a,b)=>(a.place??999)-(b.place??999)).map(e=>({name:e.name,isUser:e.isUser,place:e.place,stack:e.stack,status:e.status}))};localStorage.setItem(RESULTS,JSON.stringify(results));save(t)}
function finishBotsIfUserOut(t){const user=t.entrants.find(e=>e.isUser);if(user?.status==='active')return false;const survivors=activeEntrants(t);if(!survivors.length)return true;const champion=[...survivors].sort((a,b)=>b.stack-a.stack)[0];survivors.forEach(e=>{if(e.id!==champion.id){e.stack=0;markEliminated(t,e)}});completeTournament(t,champion);return true}
function sponsorUi(){const strong=$('#featuredSponsor strong'),small=$('#featuredSponsor small');if(strong)strong.textContent='REIKI FIRST 50';if(small)small.textContent='SPONSOR TOURNAMENT';document.body.classList.toggle('phase401-tournament-mode',ACTIVE)}
function ensureHud(){if(!ACTIVE||$('#phase401TournamentHud'))return;const turn=$('.turn-strip');if(!turn)return;turn.insertAdjacentHTML('afterend','<section id="phase401TournamentHud" class="phase401-tournament-hud"><strong>REIKI FIRST 50</strong><span data-field>10 LEFT</span><span data-round>ROUND 1</span><span data-level>LEVEL 1 • 50/100</span><span data-prize>PRIZE 100,000</span><a href="/game/tournament-results.html?v=phase401">RESULTS</a></section>')}
function updateHud(t=load()){if(!ACTIVE)return;ensureHud();const hud=$('#phase401TournamentHud');if(!hud)return;const level=levelFor(t),left=activeEntrants(t).length;hud.querySelector('[data-field]').textContent=`${left} LEFT / ${CONFIG.testFieldSize}`;hud.querySelector('[data-round]').textContent=`ROUND ${(t.round||0)+1}`;hud.querySelector('[data-level]').textContent=`LEVEL ${level.index+1} • ${level.smallBlind}/${level.bigBlind}${level.ante?` • ANTE ${level.ante}`:''}`;hud.querySelector('[data-prize]').textContent=`PRIZE ${CONFIG.prizePlayChips.toLocaleString()}`}
function onJoin(){if(!ACTIVE)return null;const t=ensureRunning();sponsorUi();updateHud(t);return t}
function beforeHand(){if(!ACTIVE)return null;const t=ensureRunning(),level=levelFor(t);runtime.checkedAt=now();updateHud(t);return{smallBlind:level.smallBlind,bigBlind:level.bigBlind,ante:level.ante,level:level.index+1,round:(t.round||0)+1,label:`${CONFIG.name} • LEVEL ${level.index+1}`}}
function preparePlayers(game,previous=[]){if(!ACTIVE)return;const t=ensureRunning(),user=t.entrants.find(e=>e.isUser),activeBots=activeEntrants(t).filter(e=>!e.isUser),used=new Set();if(user){game.players[0].name=user.name;game.players[0].stack=user.stack;game.players[0].tournamentId=user.id;game.players[0].rank='TOURNAMENT';used.add(user.id);game.stack=user.stack}for(let seat=1;seat<game.players.length;seat++){let entrant=null;const oldId=previous?.[seat]?.tournamentId;if(oldId)entrant=activeBots.find(e=>e.id===oldId&&!used.has(e.id));if(!entrant)entrant=activeBots.find(e=>!used.has(e.id));const player=game.players[seat];if(entrant){player.name=entrant.name;player.stack=entrant.stack;player.tournamentId=entrant.id;player.rank='TOURNAMENT';used.add(entrant.id)}else{player.name=`OPEN ${seat}`;player.stack=0;player.tournamentId=null;player.folded=true;player.allIn=true;player.rank='OUT'}}sponsorUi();updateHud(t);save(t)}
function afterHand(game,{names,userWon}={}){if(!ACTIVE)return null;const t=ensureRunning(),seated=new Set();for(const player of game.players||[]){const entrant=t.entrants.find(e=>e.id===player.tournamentId);if(!entrant)continue;entrant.stack=Math.max(0,Math.round(player.stack||0));entrant.seat=player.index;seated.add(entrant.id);markEliminated(t,entrant)}simulateOffTable(t,seated);t.round=(t.round||0)+1;t.lastHand={round:t.round,winner:names||null,userWon:Boolean(userWon),at:now()};const survivors=activeEntrants(t);if(survivors.length===1)completeTournament(t,survivors[0]);else if(finishBotsIfUserOut(t)){}save(t);updateHud(t);const user=t.entrants.find(e=>e.isUser);if(t.status==='completed')return{stop:true,status:user?.place===1?`TOURNAMENT CHAMPION • +${CONFIG.prizePlayChips.toLocaleString()} PLAY CHIPS`:`TOURNAMENT COMPLETE • ${t.champion?.name||'WINNER'} WON`,redirect:'/game/tournament-results.html?v=phase401'};if(user?.status!=='active')return{stop:true,status:`ELIMINATED • PLACE ${user?.place||'-'} • RESULTS READY`,redirect:'/game/tournament-results.html?v=phase401'};return{stop:false,status:`${activeEntrants(t).length} PLAYERS LEFT • NEXT ROUND ${(t.round||0)+1}`}}
function onLeave(){if(!ACTIVE)return;updateHud(load())}
function reset(){localStorage.removeItem(STORAGE);return createField()}
function getState(){const t=load();return{...t,config:CONFIG,currentLevel:levelFor(t),playersLeft:activeEntrants(t).length}}
function qa(){const t=getState(),level=t.currentLevel;return{build:BUILD,active:ACTIVE,mode:MODE,registrationCap:CONFIG.registrationCap,testFieldSize:CONFIG.testFieldSize,visibleTableSeats:CONFIG.visibleTableSeats,startingStack:CONFIG.startingStack,prizePlayChips:CONFIG.prizePlayChips,roundsPerLevel:CONFIG.roundsPerLevel,currentSmallBlind:level.smallBlind,currentBigBlind:level.bigBlind,currentAnte:level.ante,botFill:true,resultsStorage:RESULTS,handsGuidePreserved:Boolean(window.SVR_PHASE399_ANDROID_LEARNING_QA),pass:Boolean(!ACTIVE||CONFIG.registrationCap===50&&CONFIG.testFieldSize===10&&CONFIG.prizePlayChips===100000&&CONFIG.roundsPerLevel===2),checkedAt:now()}}
window.SVR_PHASE401_TOURNAMENT_DIRECTOR={build:BUILD,config:CONFIG,active:()=>ACTIVE,onJoin,beforeHand,preparePlayers,afterHand,onLeave,reset,getState,updateHud,tableLabel:()=>CONFIG.name};
window.SVR_PHASE401_TOURNAMENT_QA=qa;
if(ACTIVE){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{sponsorUi();ensureHud();updateHud(load())},{once:true});else{sponsorUi();ensureHud();updateHud(load())}}
