import * as THREE from 'three';
const LABEL='PHASE-187-CLEANUP-WALL-PORTAL-MAGNET-LOCK';
const ROOT='PHASE187_CLEANUP_WALL_PORTAL_MAGNET_ROOT';
const WALL='PHASE187_REAL_MISSING_WALL_STORE_PORTAL_WALL';
const ROOM={minX:-13.35,maxX:13.35,minZ:-10.45,maxZ:9.25};
const PORTALS=[{id:'vibes',title:'VIBES THEATER',sub:'Live Shows • Music • Stage',x:-4.2,z:ROOM.maxZ-.12,color:0xb86cff},{id:'smokers',title:'SMOKERS LOUNGE',sub:'Relax • Social • Lounge',x:4.2,z:ROOM.maxZ-.12,color:0x7ffcff}];
let scene,camera,renderer,root,started=false,raycaster=new THREE.Raycaster(),lastHit=null,hovered=null;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.6,metalness:.06,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.95});}
function add(parent,n,p,s,m){const x=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);x.name=n;x.position.set(p.x,p.y,p.z);x.receiveShadow=true;parent.add(x);return x;}
function txt(title,sub,color){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#050610';x.fillRect(0,0,1024,512);x.strokeStyle='#'+color.toString(16).padStart(6,'0');x.lineWidth=14;x.strokeRect(24,24,976,464);x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff';x.font='900 78px system-ui';x.fillText(title,512,190,920);x.fillStyle='#ffd98a';x.font='700 36px system-ui';x.fillText(sub,512,292,900);x.fillStyle='#bffcff';x.font='700 26px system-ui';x.fillText('Aim here • soft magnetic portal lock',512,380,900);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function clearDupes(rootObj){let n=0;const names=['PHASE178_NEW_UPPER_STRUCTURE_ROOT','PHASE180_WALKABLE_COLLISION_ROOT','PHASE186_BALCONY_SAFETY_TELEPORT_ROOT',ROOT];for(const nm of names){const o=rootObj.getObjectByName?.(nm);if(o){o.parent?.remove(o);n++;}}return n;}
function build(){const r=sr(scene);if(!r)return false;const old=clearDupes(r);root=new THREE.Group();root.name=ROOT;r.add(root);const wallMat=mat(0x111722);add(root,WALL,{x:0,y:1.75,z:ROOM.maxZ+.03},{x:ROOM.maxX-ROOM.minX+.4,y:3.5,z:.18},wallMat);add(root,'PHASE187_WALL_BASE_TRIM_TIGHT',{x:0,y:.13,z:ROOM.maxZ-.08},{x:ROOM.maxX-ROOM.minX+.4,y:.26,z:.28},mat(0x070a10));add(root,'PHASE187_WALL_TOP_TRIM_TIGHT',{x:0,y:3.48,z:ROOM.maxZ-.08},{x:ROOM.maxX-ROOM.minX+.4,y:.18,z:.28},mat(0x070a10));for(const p of PORTALS){const g=new THREE.Group();g.name='PHASE187_PORTAL_'+p.id.toUpperCase();g.position.set(p.x,1.62,p.z-.04);root.add(g);const halo=new THREE.Mesh(new THREE.PlaneGeometry(3.55,2.3),basic(p.color,.16));halo.name='PHASE187_PORTAL_HALO_'+p.id.toUpperCase();g.add(halo);const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.15,1.86),new THREE.MeshBasicMaterial({map:txt(p.title,p.sub,p.color),transparent:true,side:THREE.DoubleSide}));panel.name='PHASE187_INTERACTIVE_PORTAL_'+p.id.toUpperCase();panel.userData.svrPortal={id:p.id,title:p.title,magnet:true};panel.position.z=-.03;g.add(panel);const hit=new THREE.Mesh(new THREE.PlaneGeometry(4.15,2.75),basic(0xffffff,.001));hit.name='PHASE187_MAGNET_HITBOX_'+p.id.toUpperCase();hit.userData.svrPortal={id:p.id,title:p.title,magnet:true};hit.position.z=-.055;g.add(hit);}window.SVR_PHASE187_CLEANUP_WALL_PORTAL_MAGNET_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,duplicateRootsRemoved:old,realWall:true,portals:PORTALS.map(p=>p.id),magnetSoftness:'balanced',checkedAt:iso()};return true;}
function cam(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function pointerRay(){const c=cam();const pos=new THREE.Vector3(),dir=new THREE.Vector3();c.getWorldPosition(pos);c.getWorldDirection(dir);return {pos,dir};}
function setHover(obj,on){if(!obj)return;obj.scale.setScalar(on?1.045:1);const halo=obj.parent?.children?.find(x=>/HALO/.test(x.name));if(halo)halo.material.opacity=on?.28:.16;}
function tick(){if(!root||!camera)return;const hits=[];root.traverse(o=>{if(o.userData?.svrPortal)hits.push(o);});const r=pointerRay();raycaster.set(r.pos,r.dir);const direct=raycaster.intersectObjects(hits,false)[0];let best=direct?.object||null,bestScore=direct?0:99;if(!best){for(const o of hits){const p=new THREE.Vector3();o.getWorldPosition(p);const to=p.sub(r.pos);const dist=to.length();if(dist<.1||dist>10)continue;const angle=r.dir.angleTo(to.normalize());const score=angle*2+dist*.015;if(score<bestScore&&angle<0.20){best=o;bestScore=score;}}}if(best!==hovered){setHover(hovered,false);hovered=best;setHover(hovered,true);}lastHit=hovered?.userData?.svrPortal||null;window.SVR_PHASE187_PORTAL_MAGNET_STATUS={build:LABEL,hover:lastHit,balancedMagnet:true,checkedAt:iso()};}
function activate(){if(!lastHit)return;window.SVR_PHASE187_LAST_PORTAL_ACTIVATE={build:LABEL,portal:lastHit,checkedAt:iso()};window.dispatchEvent(new CustomEvent('svr-portal-activate',{detail:{build:LABEL,portal:lastHit}}));}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;build();window.SVR_RUN_PHASE187_CLEANUP_AUDIT=()=>window.SVR_PHASE187_CLEANUP_WALL_PORTAL_MAGNET_LOCK;window.SVR_ACTIVATE_PHASE187_PORTAL=activate;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;window.addEventListener('keydown',e=>{if(e.code==='Enter'||e.code==='KeyE')activate();});setInterval(tick,90);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
