import * as THREE from 'three';
const LABEL='PHASE-194-FOCUS-LOBBY-SCALE-ALIGNMENT-LOCK';
const ROOT='PHASE194_FOCUS_LOBBY_SCALE_ALIGNMENT_ROOT';
const ROOM={minX:-15.5,maxX:15.5,minZ:-12.2,maxZ:11.2};
const SECOND=3.15;
let scene,camera,renderer,root,started=false;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.7,metalness:.04,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function addBox(p,n,pos,scale,m){const x=new THREE.Mesh(new THREE.BoxGeometry(scale.x,scale.y,scale.z),m);x.name=n;x.position.set(pos.x,pos.y,pos.z);x.receiveShadow=true;p.add(x);return x;}
function addFocusCss(){let s=document.getElementById('phase194-focus-css');if(s)return; s=document.createElement('style');s.id='phase194-focus-css';s.textContent=`
html:before{content:"";position:fixed;inset:0;z-index:2147483000;pointer-events:none;background:radial-gradient(ellipse at center,rgba(0,0,0,.05) 0%,rgba(0,0,0,.10) 48%,rgba(0,0,0,.22) 100%);mix-blend-mode:multiply;}
#phase194FocusLayer{position:fixed;inset:0;z-index:2147482999;pointer-events:none;background:rgba(0,0,0,.10);backdrop-filter:contrast(1.08) brightness(.92);}
@media (display-mode: fullscreen){#phase194FocusLayer{background:rgba(0,0,0,.12)}}
`;document.head.appendChild(s);let d=document.getElementById('phase194FocusLayer');if(!d){d=document.createElement('div');d.id='phase194FocusLayer';document.body.appendChild(d);} }
function purgeCenterRails(){let n=0;const r=sr(scene),kill=[];r?.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|card|chip|pot|dealer|watch|hand|teleport|moon|mars|star|camera|light/i.test(nm))return;if(!/rail|rope|stanchion|barrier|banister|handrail|guard|pole|post/i.test(nm))return;const p=new THREE.Vector3();o.getWorldPosition(p);if(Math.hypot(p.x,p.z)<11.5)kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
function expandWalls(){const wall=mat(0x101620),trim=mat(0x080a0f),glass=mat(0x7ffcff,.22),floor=mat(0x1b2330);addBox(root,'PHASE194_EXPANDED_NORTH_WALL',{x:0,y:1.75,z:ROOM.minZ},{x:ROOM.maxX-ROOM.minX,y:3.5,z:.18},wall);addBox(root,'PHASE194_EXPANDED_SOUTH_WALL',{x:0,y:1.75,z:ROOM.maxZ},{x:ROOM.maxX-ROOM.minX,y:3.5,z:.18},wall);addBox(root,'PHASE194_EXPANDED_WEST_WALL',{x:ROOM.minX,y:1.75,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.18,y:3.5,z:ROOM.maxZ-ROOM.minZ},wall);addBox(root,'PHASE194_EXPANDED_EAST_WALL',{x:ROOM.maxX,y:1.75,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.18,y:3.5,z:ROOM.maxZ-ROOM.minZ},wall);addBox(root,'PHASE194_FLOOR_EXPANSION_GUIDE',{x:0,y:.006,z:0},{x:ROOM.maxX-ROOM.minX,y:.012,z:ROOM.maxZ-ROOM.minZ},mat(0x0c1118,.18));addBox(root,'PHASE194_NORTH_BALCONY_ATTACHED',{x:0,y:SECOND-.07,z:ROOM.minZ+1.05},{x:ROOM.maxX-ROOM.minX,y:.16,z:2.1},floor);addBox(root,'PHASE194_SOUTH_BALCONY_ATTACHED',{x:0,y:SECOND-.07,z:ROOM.maxZ-1.05},{x:ROOM.maxX-ROOM.minX,y:.16,z:2.1},floor);addBox(root,'PHASE194_WEST_BALCONY_ATTACHED',{x:ROOM.minX+1.05,y:SECOND-.07,z:(ROOM.minZ+ROOM.maxZ)/2},{x:2.1,y:.16,z:ROOM.maxZ-ROOM.minZ},floor);addBox(root,'PHASE194_EAST_BALCONY_ATTACHED',{x:ROOM.maxX-1.05,y:SECOND-.07,z:(ROOM.minZ+ROOM.maxZ)/2},{x:2.1,y:.16,z:ROOM.maxZ-ROOM.minZ},floor);addBox(root,'PHASE194_NORTH_BALCONY_GLASS',{x:0,y:SECOND+.6,z:ROOM.minZ+2.15},{x:ROOM.maxX-ROOM.minX-2,y:1.05,z:.06},glass);addBox(root,'PHASE194_SOUTH_BALCONY_GLASS',{x:0,y:SECOND+.6,z:ROOM.maxZ-2.15},{x:ROOM.maxX-ROOM.minX-2,y:1.05,z:.06},glass);addBox(root,'PHASE194_WEST_BALCONY_GLASS',{x:ROOM.minX+2.15,y:SECOND+.6,z:0},{x:.06,y:1.05,z:ROOM.maxZ-ROOM.minZ-2},glass);addBox(root,'PHASE194_EAST_BALCONY_GLASS',{x:ROOM.maxX-2.15,y:SECOND+.6,z:0},{x:.06,y:1.05,z:ROOM.maxZ-ROOM.minZ-2},glass);const pillar=mat(0x1c222c);for(const x of [ROOM.minX,ROOM.maxX])for(const z of [ROOM.minZ,ROOM.maxZ]){addBox(root,'PHASE194_CORNER_PILLAR_ATTACHED',{x,y:1.85,z},{x:.58,y:3.7,z:.58},pillar);addBox(root,'PHASE194_UPPER_CORNER_POST_ATTACHED',{x,y:SECOND+1.0,z},{x:.44,y:2,z:.44},pillar);}}
function hideOldEdgeSquares(){scene?.traverse?.(o=>{const nm=String(o.name||'');if(/focus|tint|overlay|square/i.test(nm)&&!/PHASE194/i.test(nm)){if(o.material){o.material.transparent=true;o.material.opacity=Math.min(o.material.opacity??1,.08);o.material.needsUpdate=true;}}});}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;const r=sr(scene),old=r.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;r.add(root);addFocusCss();const rails=purgeCenterRails();expandWalls();hideOldEdgeSquares();window.SVR_PHASE194_FOCUS_LOBBY_SCALE_ALIGNMENT_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,fullScreenFocusTint:true,noEdgeSquares:true,lobbyExpanded:true,secondFloorAttached:true,cornerPillarsAttached:true,centerRailsRemoved:rails,checkedAt:iso()};window.SVR_RUN_PHASE194_AUDIT=()=>window.SVR_PHASE194_FOCUS_LOBBY_SCALE_ALIGNMENT_LOCK;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(()=>{hideOldEdgeSquares();},1200);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
