import * as THREE from 'three';
const LABEL='PHASE-193-QUEST-TELEPORT-FORWARD-FIX-LOCK';
const ROOT='PHASE193_QUEST_TELEPORT_FORWARD_FIX_ROOT';
const EYE=1.62, COOLDOWN=850;
let scene,camera,renderer,root,started=false,teleportArmed=false,aiming=false,lastCommit=0,lastToggle=0,target=null,lastGrip=false,lastTrigger=false,lastPinch=false;
const raycaster=new THREE.Raycaster();
function iso(){return new Date().toISOString();}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:false});}
function worldCamera(){return renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;}
function camPos(){const p=new THREE.Vector3();worldCamera()?.getWorldPosition(p);return p;}
function camDir(){const d=new THREE.Vector3();worldCamera()?.getWorldDirection(d);d.y=0;if(d.lengthSq()<.001)d.set(0,0,-1);return d.normalize();}
function rig(){return window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG||null;}
function floorY(){const p=camPos();return Math.max(0,Math.round((p.y-EYE)/3.15)*3.15);}
function setPose(x,y,z){const r=rig();if(renderer?.xr?.isPresenting&&r?.setPlayerPose)r.setPlayerPose(x,y,z);else camera.position.set(x,y+EYE,z);}
function hideForeignLasers(){scene?.traverse?.(o=>{const n=String(o.name||'');if(!/laser|pointer|line|ray/i.test(n))return;if(/PHASE193|SVR|teleport|arc/i.test(n))return;if(o.material){o.visible=false;o.material.opacity=0;o.material.transparent=true;}});}
function input(){const pads=navigator.getGamepads?navigator.getGamepads():[];let grip=false,trigger=false;for(const g of pads){if(!g)continue;const hand=(g.hand||'').toLowerCase();if(!/right|left/.test(hand)&&!/oculus|quest|touch/i.test(g.id||''))continue;const b=g.buttons||[];if((b[1]?.pressed||b[2]?.pressed))grip=true;if((b[0]?.pressed||b[3]?.pressed))trigger=true;}
const hand=window.SVR_HAND_INPUT||window.SVR_PHASE170_HAND_INPUT||window.SVR_ACTIVE_HAND_INPUT||{};const pinch=!!(hand.pinch||hand.pinching||hand.indexThumbPinch||hand.rightPinch||hand.leftPinch);return {grip,trigger,pinch};}
function makeVisual(){const old=scene.getObjectByName?.(ROOT);if(old)old.parent?.remove(old);root=new THREE.Group();root.name=ROOT;scene.add(root);const lineGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-1)]);const line=new THREE.Line(lineGeo,new THREE.LineBasicMaterial({color:0x7ffcff,transparent:true,opacity:.0}));line.name='PHASE193_TELEPORT_ALIGNED_RAY';root.add(line);const ring=new THREE.Mesh(new THREE.RingGeometry(.22,.34,64),basic(0x7ffcff,0));ring.name='PHASE193_TELEPORT_TARGET_RING';ring.rotation.x=-Math.PI/2;root.add(ring);const logo=new THREE.Mesh(new THREE.CircleGeometry(.18,48),basic(0xeebf5c,0));logo.name='PHASE193_SVR_LOGO_TARGET_DOT';logo.rotation.x=-Math.PI/2;root.add(logo);}
function showVisual(on){if(!root)return;root.children.forEach(o=>{o.visible=on;if(o.material){o.material.opacity=on?(o.name.includes('RAY')?.72:.86):0;o.material.needsUpdate=true;}});}
function aimTarget(){const p=camPos(),d=camDir();const origin=p.clone();origin.y-=.35;const planeY=floorY()+.02;let t=(planeY-origin.y)/(d.y||-.0001);if(!isFinite(t)||t<1)t=4.2;if(t>12)t=12;const hit=origin.clone().add(d.multiplyScalar(t));hit.y=planeY;hit.x=Math.max(-12.6,Math.min(12.6,hit.x));hit.z=Math.max(-9.8,Math.min(8.8,hit.z));return hit;}
function updateVisual(){if(!root)return;target=aimTarget();const p=camPos();const line=root.getObjectByName('PHASE193_TELEPORT_ALIGNED_RAY');if(line){const pts=[new THREE.Vector3(p.x,p.y-.32,p.z),target.clone()];line.geometry.setFromPoints(pts);}const ring=root.getObjectByName('PHASE193_TELEPORT_TARGET_RING');const logo=root.getObjectByName('PHASE193_SVR_LOGO_TARGET_DOT');if(ring)ring.position.copy(target);if(logo){logo.position.copy(target);logo.position.y+=.012;}}
function toggle(on){teleportArmed=!!on;aiming=false;showVisual(false);const r=rig();if(r){try{if(r.setEnabled)r.setEnabled(teleportArmed);if(r.setMode)r.setMode(teleportArmed?'teleport':'off');if(r.setVisible)r.setVisible(false);}catch(e){}}
}
function commit(){if(!teleportArmed||!target||performance.now()-lastCommit<COOLDOWN)return;lastCommit=performance.now();const y=floorY();setPose(target.x,y,target.z);toggle(false);window.SVR_PHASE193_LAST_TELEPORT={build:LABEL,x:+target.x.toFixed(3),y,z:+target.z.toFixed(3),checkedAt:iso()};}
function forwardFix(){const r=rig();if(!r)return;try{if(!r.__phase193ForwardPatched&&r.move){const old=r.move.bind(r);r.move=(f=0,s=0)=>{const d=camDir();const right=new THREE.Vector3().crossVectors(d,new THREE.Vector3(0,1,0)).normalize();const p=camPos();setPose(p.x+d.x*f+right.x*s,floorY(),p.z+d.z*f+right.z*s);};r.__phase193ForwardPatched=true;}}catch(e){}
}
function tick(){hideForeignLasers();forwardFix();const i=input();const now=performance.now();const newGrip=i.grip&&!lastGrip,newTrigger=i.trigger&&!lastTrigger,newPinch=i.pinch&&!lastPinch,releaseTrigger=!i.trigger&&lastTrigger,releasePinch=!i.pinch&&lastPinch;lastGrip=i.grip;lastTrigger=i.trigger;lastPinch=i.pinch;if(newGrip&&now-lastToggle>450){lastToggle=now;toggle(!teleportArmed);}aiming=teleportArmed&&(i.trigger||i.pinch);if(aiming){showVisual(true);updateVisual();}else showVisual(false);if(teleportArmed&&(releaseTrigger||releasePinch||newTrigger)&&target)commit();window.SVR_PHASE193_INPUT_STATUS={build:LABEL,teleportArmed,aiming,grip:i.grip,trigger:i.trigger,pinch:i.pinch,target:target?{x:+target.x.toFixed(2),y:+target.y.toFixed(2),z:+target.z.toFixed(2)}:null,extraLaserHidden:true,forwardHeadLocked:true,checkedAt:iso()};}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;makeVisual();toggle(false);window.SVR_PHASE193_QUEST_TELEPORT_FORWARD_FIX_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,teleportStartsOff:true,gripTogglesArm:true,triggerOrPinchAimsAndCommits:true,autoDisarmAfterTeleport:true,extraLaserHidden:true,forwardUsesHeadDirection:true,checkedAt:iso()};window.SVR_RUN_PHASE193_INPUT_AUDIT=()=>({lock:window.SVR_PHASE193_QUEST_TELEPORT_FORWARD_FIX_LOCK,status:window.SVR_PHASE193_INPUT_STATUS});window.SVR_PHASE193_TELEPORT_OFF=()=>toggle(false);window.SVR_PHASE193_TELEPORT_ON=()=>toggle(true);window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;setInterval(tick,70);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
