import * as THREE from 'three';
const LABEL='PHASE-188-CONSOLIDATED-ARCHITECTURE-AUTHORITY-LOCK';
const ROOT='PHASE188_CONSOLIDATED_ARCHITECTURE_AUTHORITY_ROOT';
const SECOND=3.15,EYE=1.62;
const ROOM={minX:-13.35,maxX:13.35,minZ:-10.45,maxZ:9.25};
const WALK=1.9;
const STAIR={cx:-10.95,cz:5.95,r:2.15,start:Math.PI,end:Math.PI*1.52,n:16,w:1.85};
const PORTALS=[{id:'vibes',title:'VIBES THEATER',sub:'Shows • Music • Stage',x:-4.2,z:ROOM.maxZ-.14,color:0xb86cff},{id:'smokers',title:'SMOKERS LOUNGE',sub:'Relax • Social • Lounge',x:4.2,z:ROOM.maxZ-.14,color:0x7ffcff}];
let scene,camera,renderer,root,started=false,lastY=null,raycaster=new THREE.Raycaster(),hovered=null,lastPortal=null;
function iso(){return new Date().toISOString();}
function sr(s){return s?.getObjectByName?.('PHASE200_ORDERED_GRAND_LOBBY_ROOT')||s;}
function mat(c,o=1){return new THREE.MeshStandardMaterial({color:c,roughness:.66,metalness:.04,transparent:o<1,opacity:o,side:THREE.DoubleSide});}
function basic(c,o=1){return new THREE.MeshBasicMaterial({color:c,transparent:o<1,opacity:o,side:THREE.DoubleSide,depthWrite:o>.95});}
function add(parent,n,p,s,m,rot=0){const x=new THREE.Mesh(new THREE.BoxGeometry(s.x,s.y,s.z),m);x.name=n;x.position.set(p.x,p.y,p.z);x.rotation.y=rot;x.receiveShadow=true;parent.add(x);return x;}
function texture(c1,c2){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle=c1;x.fillRect(0,0,512,512);x.strokeStyle=c2;x.lineWidth=3;for(let i=0;i<512;i+=64){x.beginPath();x.moveTo(0,i);x.lineTo(512,i);x.stroke();x.beginPath();x.moveTo(i,0);x.lineTo(i,512);x.stroke();}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,3);return new THREE.MeshStandardMaterial({map:t,roughness:.78,metalness:.03,side:THREE.DoubleSide});}
function sign(title,sub,color){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#050610';x.fillRect(0,0,1024,512);x.strokeStyle='#'+color.toString(16).padStart(6,'0');x.lineWidth=14;x.strokeRect(24,24,976,464);x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff';x.font='900 80px system-ui';x.fillText(title,512,190,930);x.fillStyle='#ffd98a';x.font='700 38px system-ui';x.fillText(sub,512,292,910);x.fillStyle='#bffcff';x.font='700 25px system-ui';x.fillText('Soft magnetic portal',512,382,910);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function purge(rootObj){let n=0;const names=['PHASE178_NEW_UPPER_STRUCTURE_ROOT','PHASE180_WALKABLE_COLLISION_ROOT','PHASE185_WALL_CURVED_STAIR_PERIMETER_BALCONY_ROOT','PHASE186_BALCONY_SAFETY_TELEPORT_ROOT','PHASE187_CLEANUP_WALL_PORTAL_MAGNET_ROOT',ROOT];for(const nm of names){const o=rootObj.getObjectByName?.(nm);if(o){o.parent?.remove(o);n++;}}const kill=[];rootObj.traverse?.(o=>{const nm=String(o.name||'');if(!o.parent||/table|felt|card|chip|pot|watch|hand|teleport|moon|mars|star|camera|light|phase16[0-9]/i.test(nm))return;if(/stair|step|upper|second|balcony|mezzanine|catwalk|glass|portal|vibes|smokers|missing.wall/i.test(nm))kill.push(o);});[...new Set(kill)].forEach(o=>{o.parent?.remove(o);n++;});return n;}
function build(rootObj){const removed=purge(rootObj);root=new THREE.Group();root.name=ROOT;rootObj.add(root);const floor=texture('#242a35','#161b24'),step=texture('#343a46','#1d222c'),trim=mat(0x070a10),wall=mat(0x111722),glass=mat(0x8be8ff,.28);const y=SECOND-.09;
add(root,'PHASE188_REAL_SOUTH_STORE_WALL',{x:0,y:1.75,z:ROOM.maxZ+.04},{x:ROOM.maxX-ROOM.minX+.4,y:3.5,z:.2},wall);add(root,'PHASE188_SOUTH_WALL_BASE_TRIM',{x:0,y:.13,z:ROOM.maxZ-.09},{x:ROOM.maxX-ROOM.minX+.4,y:.26,z:.30},trim);add(root,'PHASE188_SOUTH_WALL_TOP_TRIM',{x:0,y:3.5,z:ROOM.maxZ-.09},{x:ROOM.maxX-ROOM.minX+.4,y:.18,z:.30},trim);
add(root,'PHASE188_WEST_PERIMETER_WALKWAY',{x:ROOM.minX+WALK/2,y,z:(ROOM.minZ+ROOM.maxZ)/2},{x:WALK,y:.2,z:ROOM.maxZ-ROOM.minZ+.1},floor);add(root,'PHASE188_NORTH_PERIMETER_WALKWAY',{x:(ROOM.minX+ROOM.maxX)/2,y,z:ROOM.minZ+WALK/2},{x:ROOM.maxX-ROOM.minX+.1,y:.2,z:WALK},floor);add(root,'PHASE188_EAST_PERIMETER_WALKWAY',{x:ROOM.maxX-WALK/2,y,z:(ROOM.minZ+ROOM.maxZ)/2},{x:WALK,y:.2,z:ROOM.maxZ-ROOM.minZ+.1},floor);add(root,'PHASE188_SOUTH_PERIMETER_WALKWAY',{x:(ROOM.minX+ROOM.maxX)/2,y,z:ROOM.maxZ-WALK/2},{x:ROOM.maxX-ROOM.minX+.1,y:.2,z:WALK},floor);
add(root,'PHASE188_WEST_WALL_CONNECTOR',{x:ROOM.minX-.08,y:SECOND+.58,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.16,y:1.45,z:ROOM.maxZ-ROOM.minZ+.2},wall);add(root,'PHASE188_SOUTH_WALL_BALCONY_CONNECTOR',{x:0,y:SECOND+.58,z:ROOM.maxZ+.02},{x:ROOM.maxX-ROOM.minX+.2,y:1.45,z:.16},wall);
add(root,'PHASE188_INNER_GLASS_WEST',{x:ROOM.minX+WALK+.04,y:SECOND+.68,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.055,y:1.05,z:ROOM.maxZ-ROOM.minZ-1.2},glass);add(root,'PHASE188_INNER_GLASS_NORTH',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND+.68,z:ROOM.minZ+WALK+.04},{x:ROOM.maxX-ROOM.minX-1.2,y:1.05,z:.055},glass);add(root,'PHASE188_INNER_GLASS_EAST',{x:ROOM.maxX-WALK-.04,y:SECOND+.68,z:(ROOM.minZ+ROOM.maxZ)/2},{x:.055,y:1.05,z:ROOM.maxZ-ROOM.minZ-1.2},glass);add(root,'PHASE188_INNER_GLASS_SOUTH',{x:(ROOM.minX+ROOM.maxX)/2,y:SECOND+.68,z:ROOM.maxZ-WALK-.04},{x:ROOM.maxX-ROOM.minX-1.2,y:1.05,z:.055},glass);
add(root,'PHASE188_STAIR_START_FLUSH_TO_WALL',{x:ROOM.minX+1.0,y:.04,z:8.01},{x:2.3,y:.08,z:1.1},step);for(let i=0;i<STAIR.n;i++){const p=i/(STAIR.n-1),a=STAIR.start+(STAIR.end-STAIR.start)*p,x=STAIR.cx+Math.cos(a)*STAIR.r,z=STAIR.cz+Math.sin(a)*STAIR.r,h=SECOND*p;add(root,`PHASE188_CURVED_STEP_${String(i+1).padStart(2,'0')}`,{x,y:h+.045,z},{x:STAIR.w,y:.09,z:.72},step,-a+Math.PI/2);}add(root,'PHASE188_TOP_LANDING_NO_GAP',{x:ROOM.minX+WALK/2,y:SECOND-.08,z:ROOM.maxZ-WALK/2},{x:WALK,y:.2,z:WALK},floor);add(root,'PHASE188_STAIR_OUTER_GLASS',{x:ROOM.minX+1.0,y:SECOND/2+.55,z:6.5},{x:.055,y:1.05,z:4.9},glass);add(root,'PHASE188_STAIR_INNER_GLASS',{x:ROOM.minX+2.55,y:SECOND/2+.55,z:6.0},{x:.055,y:1.05,z:4.2},glass);
for(const p of PORTALS){const g=new THREE.Group();g.name='PHASE188_PORTAL_'+p.id.toUpperCase();g.position.set(p.x,1.62,p.z-.06);root.add(g);const halo=new THREE.Mesh(new THREE.PlaneGeometry(3.55,2.3),basic(p.color,.16));halo.name='PHASE188_PORTAL_HALO_'+p.id.toUpperCase();g.add(halo);const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.15,1.86),new THREE.MeshBasicMaterial({map:sign(p.title,p.sub,p.color),transparent:true,side:THREE.DoubleSide}));panel.name='PHASE188_INTERACTIVE_PORTAL_'+p.id.toUpperCase();panel.userData.svrPortal={id:p.id,title:p.title};panel.position.z=-.03;g.add(panel);const hit=new THREE.Mesh(new THREE.PlaneGeometry(4.15,2.75),basic(0xffffff,.001));hit.name='PHASE188_MAGNET_HITBOX_'+p.id.toUpperCase();hit.userData.svrPortal={id:p.id,title:p.title};hit.position.z=-.055;g.add(hit);}
window.SVR_PHASE188_CONSOLIDATED_ARCHITECTURE_AUTHORITY_LOCK={build:LABEL,active:true,gameOnly:true,siteTouched:false,oldRootsRemoved:removed,wall:true,curvedStair:true,perimeterBalcony:true,portals:PORTALS.map(p=>p.id),singleHeightAuthority:true,checkedAt:iso()};return true;}
function stairH(x,z){let best=99,prog=0;for(let i=0;i<STAIR.n;i++){const p=i/(STAIR.n-1),a=STAIR.start+(STAIR.end-STAIR.start)*p,sx=STAIR.cx+Math.cos(a)*STAIR.r,sz=STAIR.cz+Math.sin(a)*STAIR.r,d=Math.hypot(x-sx,z-sz);if(d<best){best=d;prog=p;}}return best<1.22?SECOND*prog:null;}
function hAt(x,z){const sh=stairH(x,z);if(sh!==null)return sh;const west=x>=ROOM.minX&&x<=ROOM.minX+WALK+.25&&z>=ROOM.minZ&&z<=ROOM.maxZ;const north=z>=ROOM.minZ&&z<=ROOM.minZ+WALK+.25&&x>=ROOM.minX&&x<=ROOM.maxX;const east=x<=ROOM.maxX&&x>=ROOM.maxX-WALK-.25&&z>=ROOM.minZ&&z<=ROOM.maxZ;const south=z<=ROOM.maxZ&&z>=ROOM.maxZ-WALK-.25&&x>=ROOM.minX&&x<=ROOM.maxX;return (west||north||east||south)?SECOND:0;}
function camPos(){const p=new THREE.Vector3();if(renderer?.xr?.isPresenting)renderer.xr.getCamera(camera).getWorldPosition(p);else camera?.getWorldPosition(p);return p;}
function tickHeight(){if(!camera)return;const p=camPos(),h=hAt(p.x,p.z);if(renderer?.xr?.isPresenting){const rig=window.SVR_TELEPORT_RIG_REF||window.SVR_TELEPORT_RIG;const gy=p.y-EYE;if(rig?.setPlayerPose&&Math.abs(gy-h)>.24&&lastY!==h){lastY=h;rig.setPlayerPose(p.x,h,p.z);}}else{const want=h+EYE;if(Math.abs(camera.position.y-want)>.025)camera.position.y+=(want-camera.position.y)*.10;}window.SVR_PHASE188_HEIGHT_STATUS={build:LABEL,x:+p.x.toFixed(3),z:+p.z.toFixed(3),floorY:+h.toFixed(3),checkedAt:iso()};}
function ray(){const c=renderer?.xr?.isPresenting?renderer.xr.getCamera(camera):camera;const p=new THREE.Vector3(),d=new THREE.Vector3();c.getWorldPosition(p);c.getWorldDirection(d);return {p,d};}
function setHover(o,on){if(!o)return;o.scale.setScalar(on?1.04:1);const h=o.parent?.children?.find(x=>/HALO/.test(x.name));if(h)h.material.opacity=on?.28:.16;}
function tickPortal(){if(!root||!camera)return;const hits=[];root.traverse(o=>{if(o.userData?.svrPortal)hits.push(o);});const r=ray();raycaster.set(r.p,r.d);const direct=raycaster.intersectObjects(hits,false)[0];let best=direct?.object||null,score=direct?0:99;if(!best){for(const o of hits){const p=new THREE.Vector3();o.getWorldPosition(p);const to=p.sub(r.p);const dist=to.length();if(dist<.1||dist>10)continue;const ang=r.d.angleTo(to.normalize());const s=ang*2+dist*.015;if(s<score&&ang<.20){best=o;score=s;}}}if(best!==hovered){setHover(hovered,false);hovered=best;setHover(hovered,true);}lastPortal=hovered?.userData?.svrPortal||null;window.SVR_PHASE188_PORTAL_STATUS={build:LABEL,hover:lastPortal,balancedMagnet:true,checkedAt:iso()};}
function activate(){if(!lastPortal)return;window.SVR_PHASE188_LAST_PORTAL_ACTIVATE={build:LABEL,portal:lastPortal,checkedAt:iso()};window.dispatchEvent(new CustomEvent('svr-portal-activate',{detail:{build:LABEL,portal:lastPortal}}));}
function install(){scene=window.__SVR_SCENE__;camera=window.__SVR_CAMERA__;renderer=window.__SVR_RENDERER__;if(!scene||!camera||!renderer)return false;build(sr(scene));window.SVR_RUN_PHASE188_ARCHITECTURE_AUDIT=()=>window.SVR_PHASE188_CONSOLIDATED_ARCHITECTURE_AUTHORITY_LOCK;window.SVR_ACTIVATE_PHASE188_PORTAL=activate;window.SVR_LOCKED_FINAL_BUILD=LABEL;window.SVR_LIVE_BUILD_POINTER=LABEL;if(!started){started=true;window.addEventListener('keydown',e=>{if(e.code==='Enter'||e.code==='KeyE')activate();});setInterval(()=>{tickHeight();tickPortal();},90);}return true;}
[300,900,1800,3500,7000].forEach(ms=>setTimeout(install,ms));install();
