import './private_scene_runtime_phase162.js';
const PHASE='PHASE-163-SCORPION-WATCH-VR-ATTACH-ACTION-MIRROR-LOCK';
const p=new URLSearchParams(location.search);const sceneKey=(p.get('scene')||'private').toLowerCase();
window.SVR_PHASE163_SCORPION_WATCH_VR_ATTACH={phase:PHASE,scene:sceneKey,officialLogo:'../logo.png',noMusic:true,watchMode:'floating VR-style watch proxy and action mirror only',safety:{teleportChanged:false,movementChanged:false,handTrackingChanged:false,webXrDollyChanged:false,referenceSpaceChanged:false},nextBuild:'PHASE-164-SCORPION-ACTION-STATE-AND-HAND-HISTORY-STRIP'};
const statusEl=document.getElementById('status'),modeEl=document.getElementById('mode'),titleEl=document.getElementById('title');function st(t){if(statusEl)statusEl.textContent=t}function md(t){if(modeEl)modeEl.textContent=t}if(titleEl)titleEl.textContent='PHASE-163';
const s=document.createElement('style');s.textContent='#watch163{position:fixed;left:50%;bottom:185px;z-index:210;width:310px;min-height:176px;transform:translateX(-50%) perspective(800px) rotateX(12deg);border:2px solid rgba(180,140,255,.98);border-radius:28px;background:radial-gradient(circle at 50% 0,rgba(180,140,255,.42),rgba(0,0,0,.92) 58%);color:#e6d7ff;font:900 12px/1.35 system-ui,Arial;padding:14px;pointer-events:none;box-shadow:0 22px 60px rgba(0,0,0,.75),inset 0 0 28px rgba(180,140,255,.28)}#watch163:before,#watch163:after{content:"";position:absolute;left:50%;transform:translateX(-50%);width:96px;height:12px;border-radius:999px;background:#1d1030;border:1px solid #b48cff;box-shadow:0 0 12px rgba(180,140,255,.65)}#watch163:before{top:-14px}#watch163:after{bottom:-14px}.logo163{width:58px;height:58px;border-radius:50%;background:url(../logo.png) center/contain no-repeat;filter:drop-shadow(0 0 12px #b48cff);float:left;margin:0 12px 8px 0}.title163{color:#fff;font-size:16px;font-weight:1000}.line163{display:flex;justify-content:space-between;clear:both;margin-top:5px}.val163{color:#f6e27f}.bar163{height:9px;border-radius:999px;background:rgba(255,255,255,.14);overflow:hidden;margin-top:8px}.bar163 i{display:block;height:100%;width:var(--w,100%);background:linear-gradient(90deg,#ff5572,#f6e27f,#b48cff)}#mirror163{position:fixed;left:50%;bottom:20px;z-index:215;display:flex;gap:8px;flex-wrap:wrap;justify-content:center;transform:translateX(-50%);width:min(780px,calc(100vw - 24px))}.act163{pointer-events:auto;border:1px solid rgba(246,226,127,.95);border-radius:999px;background:rgba(0,0,0,.90);color:#f6e27f;font:1000 13px system-ui,Arial;padding:11px 15px;box-shadow:0 10px 30px rgba(0,0,0,.55);cursor:pointer}.act163.primary{border-color:#7ff5c7;color:#7ff5c7}.act163.danger{border-color:#ff5572;color:#ffb6c5}.note163{position:fixed;left:50%;bottom:155px;transform:translateX(-50%);z-index:212;padding:8px 12px;border-radius:999px;border:1px solid rgba(127,245,199,.7);background:rgba(0,0,0,.75);color:#7ff5c7;font:900 12px system-ui;pointer-events:none}';document.head.appendChild(s);
const old=document.getElementById('watch162');if(old)old.style.display='none';const note=document.createElement('div');note.className='note163';note.textContent='PHASE 163 WATCH ATTACHED AS SAFE FLOATING VR PROXY';document.body.appendChild(note);const watch=document.createElement('div');watch.id='watch163';document.body.appendChild(watch);const mirror=document.createElement('div');mirror.id='mirror163';document.body.appendChild(mirror);
let state={timer:20,street:'PREFLOP',pot:30,last:'READY'},lastKey='';function read(){const x=window.SVR_PHASE161_LAST_STATE;if(!x)return;const k=JSON.stringify({h:x.hand,st:x.street,t:x.timer,p:x.pot,l:x.last});if(k===lastKey)return;lastKey=k;state.timer=Number.isFinite(x.timer)?x.timer:state.timer;state.street=x.street||state.street;state.pot=Number.isFinite(x.pot)?x.pot:state.pot;state.last=x.last||state.last}
function press(a){window.SVR_PHASE163_LAST_WATCH_ACTION={action:a,at:new Date().toISOString(),scene:sceneKey,mirroredOnly:true};note.textContent='WATCH MIRROR: '+a.toUpperCase()+' selected';const ids={check:'c161',call:'ca161',raise:'r161',fold:'f161'};document.getElementById(ids[a])?.click()}
function render(){if(sceneKey!=='scorpion'){watch.innerHTML='<div class="logo163"></div><div class="title163">SVR WATCH</div><div>Private room preserved.</div><div style="clear:both;color:#b8a8d8;margin-top:8px">Action mirror active only in Scorpion.</div>';mirror.style.display='none';return}read();mirror.style.display='flex';const active=state.street!=='SHOWDOWN',pct=Math.max(0,Math.min(100,state.timer*5));watch.innerHTML='<div class="logo163"></div><div class="title163">SVR VR WATCH</div><div>Scorpion Action Mirror</div><div class="line163"><span>Street</span><span class="val163">'+state.street+'</span></div><div class="line163"><span>Timer</span><span class="val163">'+state.timer+'s</span></div><div class="line163"><span>Pot</span><span class="val163">'+state.pot+'</span></div><div class="line163"><span>Status</span><span class="val163">'+(active?'PLAYER':'SHOWDOWN')+'</span></div><div class="bar163" style="--w:'+pct+'%"><i></i></div><div style="margin-top:8px;color:#b8a8d8">Mirror only. Teleport untouched.</div>';mirror.innerHTML='<button class="act163 primary" data-a="check">WATCH CHECK</button><button class="act163 primary" data-a="call">WATCH CALL</button><button class="act163" data-a="raise">WATCH RAISE +25</button><button class="act163 danger" data-a="fold">WATCH FOLD</button>';mirror.querySelectorAll('[data-a]').forEach(b=>b.addEventListener('click',()=>press(b.dataset.a),{once:true}))}
setInterval(render,250);setTimeout(()=>{if(sceneKey==='scorpion'){st('Phase 163 VR watch proxy online');md('Watch action mirror safe')}else{st('Phase 163 room preserved');md('Watch mirror inactive here')}render()},900);
