import './private_scene_runtime_phase161.js';
const PHASE='PHASE-162-SCORPION-SEAT-TURN-INDICATORS-WATCH-REINTRO-LOCK';
const q=new URLSearchParams(location.search);const sceneKey=(q.get('scene')||'private').toLowerCase();
window.SVR_PHASE162_SCORPION_WATCH_TURN={phase:PHASE,scene:sceneKey,officialLogo:'../logo.png',noMusic:true,watchReintroduced:true,watchMode:'display only; no locomotion or teleport changes',nextBuild:'PHASE-163-SCORPION-WATCH-VR-ATTACH-AND-ACTION-MIRROR'};
const statusEl=document.getElementById('status'),modeEl=document.getElementById('mode'),titleEl=document.getElementById('title');
function st(t){if(statusEl)statusEl.textContent=t}function md(t){if(modeEl)modeEl.textContent=t}if(titleEl)titleEl.textContent='PHASE-162';
const style=document.createElement('style');style.textContent='#turn162{position:fixed;left:50%;top:132px;transform:translateX(-50%);z-index:180;min-width:min(560px,calc(100vw - 24px));padding:10px 14px;border:1px solid #f6e27f;border-radius:16px;background:rgba(0,0,0,.88);color:#fff;text-align:center;font:1000 14px system-ui;box-shadow:0 14px 40px rgba(0,0,0,.6);pointer-events:none}#watch162{position:fixed;left:12px;bottom:12px;z-index:185;width:230px;min-height:146px;border:2px solid rgba(180,140,255,.95);border-radius:24px;background:radial-gradient(circle at 50% 0,rgba(180,140,255,.32),rgba(0,0,0,.90) 55%);color:#e6d7ff;font:900 12px/1.35 system-ui;padding:12px;pointer-events:none;box-shadow:0 16px 46px rgba(0,0,0,.7)}.wlogo{width:52px;height:52px;border-radius:50%;background:url(../logo.png) center/contain no-repeat;filter:drop-shadow(0 0 10px #b48cff);float:left;margin:0 10px 8px 0}.wline{display:flex;justify-content:space-between;clear:both;margin-top:5px}.wv{color:#f6e27f}.bar{height:8px;border-radius:999px;background:rgba(255,255,255,.14);overflow:hidden;margin-top:8px}.bar i{display:block;height:100%;width:var(--w,100%);background:linear-gradient(90deg,#ff5572,#f6e27f,#b48cff)}.seat162{position:fixed;z-index:175;width:92px;height:92px;border-radius:50%;display:grid;place-items:center;text-align:center;color:#fff;font:1000 11px system-ui;background:rgba(0,0,0,.74);border:2px solid rgba(180,140,255,.55);pointer-events:none}.seat162.active{border-color:#f6e27f;box-shadow:0 0 24px #f6e27f;color:#f6e27f}.hero162{left:50%;bottom:370px;transform:translateX(-50%)}.bot162{left:50%;top:188px;transform:translateX(-50%)}.dealer162{right:34px;top:45%;transform:translateY(-50%);border-color:#ff5572}.small{display:block;color:#e6d7ff;font-size:9px;margin-top:2px}';document.head.appendChild(style);
const turn=document.createElement('div');turn.id='turn162';turn.textContent='PHASE 162 TURN INDICATORS READY';document.body.appendChild(turn);
const watch=document.createElement('div');watch.id='watch162';document.body.appendChild(watch);
const hero=document.createElement('div');hero.className='seat162 hero162 active';document.body.appendChild(hero);
const bot=document.createElement('div');bot.className='seat162 bot162';document.body.appendChild(bot);
const dealer=document.createElement('div');dealer.className='seat162 dealer162';dealer.innerHTML='DEALER<span class="small">LEFT TO RIGHT</span>';document.body.appendChild(dealer);
let mirror={timer:20,street:'PREFLOP',pot:30,last:'READY'},last='';
function read(){const s=window.SVR_PHASE161_LAST_STATE;if(!s)return;const k=JSON.stringify({h:s.hand,st:s.street,t:s.timer,p:s.pot,l:s.last});if(k===last)return;last=k;mirror.timer=Number.isFinite(s.timer)?s.timer:mirror.timer;mirror.street=s.street||mirror.street;mirror.pot=Number.isFinite(s.pot)?s.pot:mirror.pot;mirror.last=s.last||mirror.last;}
function render(){if(sceneKey!=='scorpion'){turn.textContent='PHASE 162 PRESERVED - WATCH ACTIVE ONLY IN SCORPION';watch.innerHTML='<div class="wlogo"></div><b>SVR WATCH</b><br/>Private room preserved.';hero.style.display=bot.style.display=dealer.style.display='none';return}read();const active=mirror.street!=='SHOWDOWN';const pct=Math.max(0,Math.min(100,mirror.timer*5));turn.textContent=(active?'PLAYER TURN':'SHOWDOWN')+' - '+mirror.street+' - '+mirror.timer+'s - '+mirror.last;hero.classList.toggle('active',active);bot.classList.toggle('active',!active);hero.innerHTML='PLAYER<span class="small">'+(active?'ACTIVE':'WAIT')+'</span>';bot.innerHTML='BOT NOVA<span class="small">'+(!active?'ACTIVE':'WAIT')+'</span>';watch.innerHTML='<div class="wlogo"></div><b>SVR WATCH</b><div>Scorpion Room</div><div class="wline"><span>Street</span><span class="wv">'+mirror.street+'</span></div><div class="wline"><span>Timer</span><span class="wv">'+mirror.timer+'s</span></div><div class="wline"><span>Pot</span><span class="wv">'+mirror.pot+'</span></div><div class="wline"><span>Turn</span><span class="wv">'+(active?'PLAYER':'BOT')+'</span></div><div class="bar" style="--w:'+pct+'%"><i></i></div><div style="margin-top:8px;color:#b8a8d8">Display only. Teleport untouched.</div>'}
setInterval(render,250);setTimeout(()=>{if(sceneKey==='scorpion'){st('Phase 162 indicators online');md('Watch display safe')}else{st('Phase 162 room preserved');md('Watch inactive here')}render()},900);
