import './private_scene_runtime_phase166.js';
import { createPokerGame, evaluateSeven } from '../poker/poker.js';

const PHASE='PHASE-170-POKERJS-LOCK-AND-LOBBY-QA';
const sceneKey=(new URLSearchParams(location.search).get('scene')||'private').toLowerCase();
window.SVR_BUILD_PHASE=PHASE;
window.SVR_PHASE170_POKERJS_LOCK={phase:PHASE,scene:sceneKey,siteTouched:false,gameTouched:true,engine:'game/poker/poker.js',lockedRules:{leftToRightDeal:true,fold:true,check:true,call:true,raise:true,allIn:true,nextHand:true,preflopFlopTurnRiverShowdown:true,winnerEvaluation:true,potAccounting:true,botActions:true,twentySecondTimer:true,autoCheckFree:true,autoFoldFacingBet:true},nextBuild:'PHASE-171-POKER-3D-TABLE-BINDINGS-AND-QA'};
const statusEl=document.getElementById('status'),modeEl=document.getElementById('mode'),titleEl=document.getElementById('title');
function st(t){if(statusEl)statusEl.textContent=t}function md(t){if(modeEl)modeEl.textContent=t}if(titleEl)titleEl.textContent='PHASE-170';

const game=createPokerGame();
let started=false,lastBot=0,timerTick=performance.now();
const style=document.createElement('style');style.textContent='#p170{position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:280;width:min(820px,calc(100vw - 24px));border:2px solid rgba(127,245,199,.9);border-radius:20px;background:rgba(0,0,0,.88);color:#fff;font:900 12px/1.35 system-ui;padding:12px;box-shadow:0 18px 54px rgba(0,0,0,.72);pointer-events:none}.p170title{color:#7ff5c7;font-size:15px;margin-bottom:7px}.p170row{display:flex;justify-content:space-between;gap:8px;margin:4px 0}.p170v{color:#f6e27f}.p170cards{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0}.p170card{width:47px;height:64px;border-radius:8px;background:#fff;color:#111;display:grid;place-items:center;font:1000 22px system-ui;border:2px solid #f6e27f;box-shadow:0 8px 20px rgba(0,0,0,.6)}.p170red{color:#c80030}.p170btns{position:fixed;left:50%;bottom:14px;transform:translateX(-50%);z-index:285;display:flex;gap:8px;flex-wrap:wrap;justify-content:center;width:min(840px,calc(100vw - 24px))}.p170btn{pointer-events:auto;border:1px solid rgba(246,226,127,.95);border-radius:999px;background:rgba(0,0,0,.90);color:#f6e27f;font:1000 13px system-ui;padding:11px 15px;box-shadow:0 10px 30px rgba(0,0,0,.55);cursor:pointer}.p170btn.primary{border-color:#7ff5c7;color:#7ff5c7}.p170btn.danger{border-color:#ff5572;color:#ffb6c5}.p170hist{position:fixed;right:12px;top:86px;z-index:281;width:min(340px,calc(100vw - 24px));max-height:44vh;overflow:hidden;border:1px solid rgba(180,140,255,.8);border-radius:18px;background:rgba(0,0,0,.84);color:#e6d7ff;font:900 11px/1.32 system-ui;padding:10px;pointer-events:none}.p170h{border-top:1px solid rgba(255,255,255,.12);padding:5px 0}.p170ok{color:#7ff5c7}';document.head.appendChild(style);
const panel=document.createElement('div');panel.id='p170';document.body.appendChild(panel);const buttons=document.createElement('div');buttons.className='p170btns';document.body.appendChild(buttons);const hist=document.createElement('div');hist.className='p170hist';document.body.appendChild(hist);
function red(c){return /H|D|♥|♦/.test(c)}function card(c){return '<span class="p170card '+(red(c)?'p170red':'')+'">'+c+'</span>'}function snap(){return game.snapshot()}function start(){game.startHand();started=true;sync('start-hand')}
function sync(type){const s=snap();window.SVR_PHASE170_LAST_STATE={type,at:new Date().toISOString(),...s};window.SVR_PHASE161_LAST_STATE={type,hand:s.handNo,street:s.street,timer:s.timer,pot:s.pot,ps:s.seats[0]?.stack,bs:s.seats[1]?.stack,hero:s.seats[0]?.cards||[],bot:s.seats[1]?.cards||[],board:s.board||[],last:s.history[0]?.type||type};window.SVR_PHASE160_LAST_WINNER=s.winner?{at:new Date().toISOString(),handNumber:s.handNo,winner:s.winner.seat,pot:s.winner.pot,hero:s.seats[0]?.cards||[],bot:s.seats[1]?.cards||[],community:s.board||[]}:window.SVR_PHASE160_LAST_WINNER;}
function act(a,amt){if(!started)start();else game.action(a,amt);sync(a);botLoop(true);render()}
function botLoop(force=false){let guard=0;while(game.state.street!=='SHOWDOWN'&&game.state.seats[game.state.active]?.name?.startsWith('BOT')&&guard<8){game.botAction();sync('bot-action');guard++;}}
function tick(){if(sceneKey==='scorpion'){if(!started)start();const now=performance.now();if(now-timerTick>1000){timerTick=now;if(game.state.street!=='SHOWDOWN'){game.state.timer=Math.max(0,game.state.timer-1);if(game.state.timer<=0){game.timeout();sync('timeout');botLoop(true)}}}if(now-lastBot>1200){lastBot=now;botLoop()}render()}requestAnimationFrame(tick)}
function render(){if(sceneKey!=='scorpion'){panel.innerHTML='<div class="p170title">PHASE 170 POKER.JS LOCK</div><div>Preserved. Active only in Scorpion.</div>';buttons.innerHTML='';hist.innerHTML='';return}const s=snap(),hero=s.seats[0]||{},active=s.seats[s.active]||{},toCall=Math.max(0,(s.currentBet||0)-(active.bet||0));const best=s.street==='SHOWDOWN'&&hero.cards?.length&&s.board?.length>=5?evaluateSeven([...hero.cards,...s.board]):null;panel.innerHTML='<div class="p170title">PHASE 170 POKER.JS LOCK • REAL ENGINE ACTIVE</div><div class="p170row"><span>Street</span><span class="p170v">'+s.street+'</span></div><div class="p170row"><span>Active</span><span class="p170v">'+(active.name||'-')+'</span></div><div class="p170row"><span>Timer</span><span class="p170v">'+s.timer+'s</span></div><div class="p170row"><span>Pot</span><span class="p170v">'+s.pot+'</span></div><div class="p170row"><span>To call</span><span class="p170v">'+toCall+'</span></div><div class="p170row"><span>Player stack</span><span class="p170v">'+(hero.stack||0)+'</span></div><div>Your cards</div><div class="p170cards">'+(hero.cards||[]).map(card).join('')+'</div><div>Board</div><div class="p170cards">'+(s.board?.length?s.board.map(card).join(''):'<span class="p170ok">waiting for flop</span>')+'</div><div class="p170row"><span>Winner</span><span class="p170v">'+(s.winner?`${s.winner.seat} • ${s.winner.hand}`:'pending')+'</span></div><div class="p170row"><span>Best hand</span><span class="p170v">'+(best?.name||'pending')+'</span></div>';buttons.innerHTML='<button class="p170btn primary" id="p170Check">CHECK</button><button class="p170btn primary" id="p170Call">CALL</button><button class="p170btn" id="p170Raise">RAISE +25</button><button class="p170btn" id="p170Allin">ALL-IN</button><button class="p170btn danger" id="p170Fold">FOLD</button><button class="p170btn" id="p170Next">NEXT HAND</button>';document.getElementById('p170Check')?.addEventListener('click',()=>act('check'));document.getElementById('p170Call')?.addEventListener('click',()=>act('call'));document.getElementById('p170Raise')?.addEventListener('click',()=>act('raise',25));document.getElementById('p170Allin')?.addEventListener('click',()=>act('allin'));document.getElementById('p170Fold')?.addEventListener('click',()=>act('fold'));document.getElementById('p170Next')?.addEventListener('click',()=>start());hist.innerHTML='<b>HAND HISTORY</b>'+s.history.slice(0,10).map(h=>'<div class="p170h"><b>'+h.type+'</b><br>'+JSON.stringify(h.detail).slice(0,92)+'</div>').join('')}
setTimeout(()=>{if(sceneKey==='scorpion'){st('Phase 170 poker.js lock online');md('Playable poker engine')}else{st('Phase 170 room preserved');md('Poker engine inactive here')}tick()},900);
