import './private_scene_runtime_phase163.js';
const PHASE='PHASE-164-SCORPION-ACTION-STATE-HAND-HISTORY-STRIP-LOCK';
const sceneKey=(new URLSearchParams(location.search).get('scene')||'private').toLowerCase();
window.SVR_PHASE164_SCORPION_ACTION_HISTORY={phase:PHASE,scene:sceneKey,officialLogo:'../logo.png',noMusic:true,safety:{teleportChanged:false,movementChanged:false,handTrackingChanged:false,webXrDollyChanged:false,referenceSpaceChanged:false},nextBuild:'PHASE-165-SCORPION-3D-POT-VACUUM-AND-WINNING-HAND-DISPLAY'};
const statusEl=document.getElementById('status'),modeEl=document.getElementById('mode'),titleEl=document.getElementById('title');
function st(t){if(statusEl)statusEl.textContent=t}function md(t){if(modeEl)modeEl.textContent=t}if(titleEl)titleEl.textContent='PHASE-164';
const style=document.createElement('style');
style.textContent='#hist164{position:fixed;left:12px;top:185px;z-index:225;width:min(360px,calc(100vw - 24px));max-height:52vh;overflow:hidden;border:1px solid rgba(246,226,127,.9);border-radius:18px;background:rgba(0,0,0,.88);color:#fff;font:900 12px/1.35 system-ui;padding:12px;box-shadow:0 16px 44px rgba(0,0,0,.65);pointer-events:none}.h164title{display:flex;gap:10px;align-items:center;color:#f6e27f;font-size:14px;margin-bottom:8px}.h164logo{width:34px;height:34px;border-radius:50%;background:url(../logo.png) center/contain no-repeat;filter:drop-shadow(0 0 8px #b48cff)}.h164row{border-top:1px solid rgba(255,255,255,.13);padding:6px 0;color:#e6d7ff}.h164row b{color:#fff}.h164meta{color:#b8a8d8;font-size:11px}.state164{position:fixed;right:12px;top:185px;z-index:226;width:min(330px,calc(100vw - 24px));border:1px solid rgba(127,245,199,.85);border-radius:18px;background:rgba(0,0,0,.86);color:#eafff7;font:900 12px/1.35 system-ui;padding:12px;box-shadow:0 16px 44px rgba(0,0,0,.65);pointer-events:none}.line164{display:flex;justify-content:space-between;gap:8px;margin:4px 0}.v164{color:#f6e27f}.tag164{display:inline-block;border:1px solid rgba(180,140,255,.75);border-radius:999px;padding:4px 7px;margin:2px;color:#e6d7ff;background:rgba(180,140,255,.12)}.ok164{color:#7ff5c7}.warn164{color:#ffb6c5}.strip164{position:fixed;left:50%;top:58px;transform:translateX(-50%);z-index:224;width:min(720px,calc(100vw - 24px));display:flex;gap:8px;overflow:hidden;justify-content:center;pointer-events:none}.pill164{border:1px solid rgba(246,226,127,.82);border-radius:999px;background:rgba(0,0,0,.78);color:#f6e27f;font:1000 11px system-ui;padding:6px 10px;box-shadow:0 8px 24px rgba(0,0,0,.45)}';
document.head.appendChild(style);
const hist=document.createElement('div');hist.id='hist164';document.body.appendChild(hist);const state=document.createElement('div');state.className='state164';document.body.appendChild(state);const strip=document.createElement('div');strip.className='strip164';document.body.appendChild(strip);
const history=[];let lastState='',lastWinner='',lastWatch='';
function add(type,label,detail){const item={type,label,detail,at:new Date().toLocaleTimeString()};history.unshift(item);if(history.length>12)history.pop();window.SVR_PHASE164_HAND_HISTORY=history.slice()}
function read(){const s=window.SVR_PHASE161_LAST_STATE;if(s){const key=JSON.stringify({type:s.type,hand:s.hand,street:s.street,timer:s.timer,pot:s.pot,last:s.last});if(key!==lastState){lastState=key;add(s.type||'STATE','H'+(s.hand||'?')+' '+(s.street||'-'),s.last||'state updated');window.SVR_PHASE164_LAST_ACTION_STATE=Object.assign({recordedAt:new Date().toISOString(),source:'phase161'},s)}}const w=window.SVR_PHASE160_LAST_WINNER;if(w){const key=JSON.stringify({hand:w.handNumber,winner:w.winner,pot:w.pot,at:w.at});if(key!==lastWinner){lastWinner=key;add('WINNER','Winner '+(w.winner||'-'),'Pot '+(w.pot||0)+' winning hand display queued');window.SVR_PHASE164_LAST_WINNER_RECORD=Object.assign({recordedAt:new Date().toISOString(),source:'phase160'},w)}}const a=window.SVR_PHASE163_LAST_WATCH_ACTION;if(a){const key=JSON.stringify({action:a.action,at:a.at});if(key!==lastWatch){lastWatch=key;add('WATCH','Watch '+String(a.action||'').toUpperCase(),'mirrored action button');window.SVR_PHASE164_LAST_WATCH_ACTION_RECORD=Object.assign({recordedAt:new Date().toISOString(),source:'phase163'},a)}}}
function current(){return window.SVR_PHASE161_LAST_STATE||{}}
function render(){if(sceneKey!=='scorpion'){hist.innerHTML='<div class="h164title"><div class="h164logo"></div><div>PHASE 164 HISTORY</div></div><div class="h164row">Preserved. Active only in Scorpion.</div>';state.innerHTML='<b>Action State</b><br><span class="warn164">Inactive outside Scorpion</span>';strip.innerHTML='';return}read();const s=current(),timer=Number.isFinite(s.timer)?s.timer:'-',street=s.street||'PREFLOP',pot=Number.isFinite(s.pot)?s.pot:30,hero=(s.hero||[]).join(' '),board=(s.board||[]).join(' ')||'-',turn=street==='SHOWDOWN'?'SHOWDOWN':'PLAYER';hist.innerHTML='<div class="h164title"><div class="h164logo"></div><div>HAND HISTORY STRIP</div></div>'+history.map(h=>'<div class="h164row"><b>'+h.label+'</b><div>'+h.detail+'</div><div class="h164meta">'+h.at+' - '+h.type+'</div></div>').join('');state.innerHTML='<b>SCORPION ACTION STATE</b><div class="line164"><span>Street</span><span class="v164">'+street+'</span></div><div class="line164"><span>Timer</span><span class="v164">'+timer+'s</span></div><div class="line164"><span>Pot</span><span class="v164">'+pot+'</span></div><div class="line164"><span>Turn</span><span class="v164">'+turn+'</span></div><div class="line164"><span>Hero</span><span class="v164">'+hero+'</span></div><div class="line164"><span>Board</span><span class="v164">'+board+'</span></div><div style="margin-top:8px"><span class="tag164">AUTO CHECK</span><span class="tag164">AUTO FOLD</span><span class="tag164">AUTO CALL STAGE</span><span class="tag164">LEFT TO RIGHT</span></div><div style="margin-top:8px" class="ok164">Audit record live. Teleport untouched.</div>';strip.innerHTML=history.slice(0,6).map(h=>'<div class="pill164">'+h.label+'</div>').join('')}
setInterval(render,350);setTimeout(()=>{if(sceneKey==='scorpion'){st('Phase 164 history online');md('Action records live')}else{st('Phase 164 room preserved');md('History inactive here')}render()},900);
