import './private_scene_runtime_phase164.js';
const PHASE='PHASE-165-SCORPION-3D-POT-VACUUM-WINNING-HAND-DISPLAY-LOCK';
const sceneKey=(new URLSearchParams(location.search).get('scene')||'private').toLowerCase();
window.SVR_PHASE165_SCORPION_POT_WINNER={phase:PHASE,scene:sceneKey,officialLogo:'../logo.png',noMusic:true,scope:'3D-style pot vacuum and stronger winning-hand display',safety:{teleportChanged:false,movementChanged:false,handTrackingChanged:false,webXrDollyChanged:false,referenceSpaceChanged:false},nextBuild:'PHASE-166-SCORPION-BET-LINE-CHIP-STACKS-REALISM'};
const statusEl=document.getElementById('status'),modeEl=document.getElementById('mode'),titleEl=document.getElementById('title');
function st(t){if(statusEl)statusEl.textContent=t}function md(t){if(modeEl)modeEl.textContent=t}if(titleEl)titleEl.textContent='PHASE-165';
const style=document.createElement('style');style.textContent='#win165{position:fixed;left:50%;top:104px;transform:translateX(-50%);z-index:240;width:min(680px,calc(100vw - 24px));padding:14px 18px;border:2px solid #f6e27f;border-radius:20px;background:linear-gradient(90deg,rgba(255,85,114,.30),rgba(180,140,255,.38),rgba(0,0,0,.86));color:#fff;text-align:center;font:1000 17px system-ui;box-shadow:0 18px 54px rgba(0,0,0,.72),0 0 24px rgba(246,226,127,.35);pointer-events:none}.win165sub{font-size:12px;color:#e6d7ff;margin-top:4px}.vac165{position:fixed;left:50%;bottom:350px;transform:translateX(-50%);z-index:239;width:min(560px,calc(100vw - 24px));height:88px;border:1px solid rgba(246,226,127,.78);border-radius:999px;background:rgba(0,0,0,.55);overflow:hidden;pointer-events:none;box-shadow:inset 0 0 22px rgba(180,140,255,.30)}.chip165{position:absolute;top:31px;width:25px;height:25px;border-radius:50%;background:radial-gradient(circle at 35% 28%,#fff,#f6e27f 24%,#a76a00 68%);box-shadow:0 0 16px #f6e27f;animation:vacuum165 1.25s ease-in-out infinite}.chip165:nth-child(2){animation-delay:.12s}.chip165:nth-child(3){animation-delay:.24s}.chip165:nth-child(4){animation-delay:.36s}.chip165:nth-child(5){animation-delay:.48s}.chip165:nth-child(6){animation-delay:.60s}@keyframes vacuum165{0%{left:48%;transform:scale(.8);opacity:.55}45%{opacity:1}100%{left:var(--to,84%);transform:scale(1.18);opacity:.25}}.hand165{position:fixed;left:50%;top:178px;transform:translateX(-50%);z-index:241;display:flex;gap:8px;justify-content:center;pointer-events:none}.card165{width:50px;height:70px;border-radius:9px;background:#fff;color:#111;display:grid;place-items:center;font:1000 23px system-ui;border:2px solid #f6e27f;box-shadow:0 10px 26px rgba(0,0,0,.62)}.red165{color:#c80030}.dim165{opacity:.45}.side165{position:fixed;right:14px;bottom:248px;z-index:242;width:min(310px,calc(100vw - 24px));border:1px solid rgba(127,245,199,.9);border-radius:18px;background:rgba(0,0,0,.86);color:#eafff7;font:900 12px/1.35 system-ui;padding:12px;box-shadow:0 16px 44px rgba(0,0,0,.65);pointer-events:none}.line165{display:flex;justify-content:space-between;gap:8px;margin:5px 0}.val165{color:#f6e27f}.ok165{color:#7ff5c7;margin-top:8px}';document.head.appendChild(style);
const win=document.createElement('div');win.id='win165';document.body.appendChild(win);const hand=document.createElement('div');hand.className='hand165';document.body.appendChild(hand);const vac=document.createElement('div');vac.className='vac165';vac.innerHTML='<i class="chip165"></i><i class="chip165"></i><i class="chip165"></i><i class="chip165"></i><i class="chip165"></i><i class="chip165"></i>';document.body.appendChild(vac);const side=document.createElement('div');side.className='side165';document.body.appendChild(side);
let lastWinner='',pulse=false;
function red(c){return /H|D|♥|♦/.test(c)}function card(c,dim){return '<span class="card165 '+(red(c)?'red165 ':'')+(dim?'dim165':'')+'">'+c+'</span>'}
function state(){return window.SVR_PHASE161_LAST_STATE||{}}
function winner(){return window.SVR_PHASE164_LAST_WINNER_RECORD||window.SVR_PHASE160_LAST_WINNER||null}
function render(){if(sceneKey!=='scorpion'){win.textContent='PHASE 165 PRESERVED';hand.innerHTML='';vac.style.display='none';side.innerHTML='Active only in Scorpion room.';return}const s=state(),w=winner(),street=s.street||'PREFLOP',pot=Number.isFinite(s.pot)?s.pot:30,hero=s.hero||[],board=s.board||[];let activeWinner=w&&w.winner;let label=activeWinner?'WINNER: '+w.winner+' • POT '+(w.pot||pot):'POT VACUUM READY • WAITING FOR SHOWDOWN';let sub=activeWinner?'Winning hand display active. Chips vacuum to '+w.winner+'.':'Winner banner arms automatically at showdown.';win.innerHTML=label+'<div class="win165sub">'+sub+'</div>';hand.innerHTML=[...hero,...board].slice(0,7).map((c,i)=>card(c,i>1&&street==='PREFLOP')).join('');vac.style.display='block';vac.querySelectorAll('.chip165').forEach(ch=>ch.style.setProperty('--to',activeWinner&&String(w.winner).includes('BOT')?'16%':'84%'));side.innerHTML='<b>PHASE 165 VISUAL STATE</b><div class="line165"><span>Street</span><span class="val165">'+street+'</span></div><div class="line165"><span>Pot</span><span class="val165">'+pot+'</span></div><div class="line165"><span>Winner</span><span class="val165">'+(activeWinner||'pending')+'</span></div><div class="line165"><span>Cards</span><span class="val165">'+hero.join(' ')+'</span></div><div class="line165"><span>Board</span><span class="val165">'+(board.join(' ')||'-')+'</span></div><div class="ok165">Display layer only. Teleport and movement untouched.</div>';if(activeWinner&&lastWinner!==JSON.stringify(w)){lastWinner=JSON.stringify(w);window.SVR_PHASE165_LAST_POT_VACUUM={at:new Date().toISOString(),winner:w.winner,pot:w.pot||pot,hero,board};}}
setInterval(render,300);setTimeout(()=>{if(sceneKey==='scorpion'){st('Phase 165 pot vacuum online');md('Winner display visual')}else{st('Phase 165 room preserved');md('Scorpion visuals inactive')}render()},900);
