import './private_scene_runtime_phase160.js';

const PHASE='PHASE-161-SCORPION-TABLE-CARD-MESHES-ACTION-BUTTONS-LOCK';
const params=new URLSearchParams(location.search);
const sceneKey=(params.get('scene')||'private').toLowerCase();
window.SVR_PHASE161_SCORPION_TABLE_ACTIONS={phase:PHASE,scene:sceneKey,officialLogo:'../logo.png',noMusic:true,noWatch:true,activeOnlyInScorpion:true,features:['table-card-layer','action-buttons','left-to-right-deal','20-second-timer','auto-check','auto-fold','auto-staged-call'],nextBuild:'PHASE-162-SCORPION-SEAT-TURN-INDICATORS-WATCH-REINTRO'};
const statusEl=document.getElementById('status'),modeEl=document.getElementById('mode'),titleEl=document.getElementById('title');
function setStatus(t){if(statusEl)statusEl.textContent=t;}function setMode(t){if(modeEl)modeEl.textContent=t;}if(titleEl)titleEl.textContent='PHASE-161';
const style=document.createElement('style');style.textContent='#svr161{position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:155;width:min(760px,calc(100vw - 24px));pointer-events:none;color:#fff;font-family:system-ui,Arial}.t161{position:relative;height:260px;border:2px solid rgba(180,140,255,.9);border-radius:50%/38%;background:radial-gradient(circle at 50% 45%,rgba(27,90,58,.96),rgba(7,42,31,.94) 54%,rgba(0,0,0,.88) 78%);box-shadow:0 20px 70px rgba(0,0,0,.72),inset 0 0 42px rgba(180,140,255,.32);overflow:hidden}.logo161{position:absolute;left:50%;top:48%;transform:translate(-50%,-50%);width:110px;height:110px;border-radius:50%;background:url(../logo.png) center/contain no-repeat;opacity:.78;filter:drop-shadow(0 0 12px #b48cff)}.lane161{position:absolute;left:50%;transform:translateX(-50%);display:flex;gap:10px;justify-content:center;align-items:center}.board161{top:92px}.hero161{bottom:24px}.bot161{top:24px}.card161{width:54px;height:76px;border-radius:9px;background:#fff;color:#111;display:grid;place-items:center;font-size:24px;font-weight:1000;border:2px solid #f6e27f;box-shadow:0 8px 20px rgba(0,0,0,.62)}.red161{color:#c80030}.back161{background:linear-gradient(135deg,#1c052e,#7c2cff,#0c1630);color:#f6e27f}.pot161{position:absolute;left:50%;top:56%;transform:translate(-50%,-50%);padding:7px 12px;border-radius:999px;border:1px solid #f6e27f;background:rgba(0,0,0,.76);color:#f6e27f;font-weight:1000;font-size:13px}.dealer161{position:absolute;left:24px;top:50%;transform:translateY(-50%);padding:8px 10px;border:1px solid rgba(255,85,114,.9);border-radius:12px;background:rgba(0,0,0,.65);font-size:12px;color:#ffd7df}.meta161{position:absolute;right:22px;top:50%;transform:translateY(-50%);text-align:right;color:#e6d7ff;font-size:12px;font-weight:900}.timer161{color:#f6e27f;font-size:22px}.active161{outline:3px solid #f6e27f;box-shadow:0 0 22px #f6e27f,0 8px 20px rgba(0,0,0,.62)}#a161{position:fixed;left:50%;bottom:14px;transform:translateX(-50%);z-index:170;display:flex;gap:10px;flex-wrap:wrap;justify-content:center;width:min(780px,calc(100vw - 24px))}.btn161{pointer-events:auto;border:1px solid rgba(246,226,127,.95);border-radius:999px;background:rgba(0,0,0,.88);color:#f6e27f;font:1000 13px system-ui,Arial;padding:12px 16px;box-shadow:0 10px 30px rgba(0,0,0,.55);cursor:pointer}#b161{position:fixed;left:50%;top:82px;transform:translateX(-50%);z-index:160;min-width:min(620px,calc(100vw - 24px));padding:11px 16px;border:1px solid rgba(255,85,114,.95);border-radius:16px;background:linear-gradient(90deg,rgba(255,85,114,.30),rgba(180,140,255,.30));color:#fff;text-align:center;font:1000 15px system-ui,Arial;box-shadow:0 12px 36px rgba(0,0,0,.58);pointer-events:none}';document.head.appendChild(style);
const stage=document.createElement('div');stage.id='svr161';const banner=document.createElement('div');banner.id='b161';banner.textContent='PHASE 161 TABLE CARD LAYER READY';const actions=document.createElement('div');actions.id='a161';document.body.appendChild(banner);document.body.appendChild(stage);document.body.appendChild(actions);
const deck=['AS','KH','QD','JC','10S','9H','8D','7C','6S','5H','4D','3C','2S','AH','KD','QC','JS','10H','9D','8C','7S','AD','KS','QH'];let di=0,hand=0,street='PREFLOP',timer=20,pot=30,ps=500,bs=500,hero=[],bot=[],board=[],last='READY',lastTick=performance.now();
function red(c){return /H|D/.test(c);}function card(c,cls=''){return '<span class="card161 '+(red(c)?'red161 ':'')+cls+'">'+c+'</span>';}function back(){return '<span class="card161 back161">SVR</span>';}function draw(){const c=deck[di%deck.length];di++;return c;}function rec(type){window.SVR_PHASE161_LAST_STATE={type,at:new Date().toISOString(),hand,street,timer,pot,ps,bs,hero:[...hero],bot:[...bot],board:[...board],last};}
function start(){hand++;street='PREFLOP';timer=20;pot=30;hero=[draw(),draw()];bot=[draw(),draw()];board=[];last='LEFT TO RIGHT DEAL COMPLETE';banner.textContent='HAND '+hand+' - PLAYER ACTION - 20s TIMER';rec('hand-start');render();}
function nextStreet(){timer=20;if(street==='PREFLOP'){street='FLOP';board=[draw(),draw(),draw()];pot+=20;banner.textContent='FLOP - CHECK IS FREE';}else if(street==='FLOP'){street='TURN';board.push(draw());pot+=15;banner.textContent='TURN - CALL AUTO-STAGED';}else if(street==='TURN'){street='RIVER';board.push(draw());pot+=15;banner.textContent='RIVER - FINAL ACTION';}else{return showdown();}last='STREET ADVANCED';rec('street');render();}
function showdown(){street='SHOWDOWN';timer=0;const w=hand%2?'PLAYER':'BOT NOVA';if(w==='PLAYER')ps+=pot;else bs+=pot;banner.textContent='WINNER: '+w+' - POT '+pot;last='WINNER BANNER + POT VACUUM';rec('winner');setTimeout(start,3200);render();}
function act(a){if(sceneKey!=='scorpion'||street==='SHOWDOWN')return;if(a==='check'){last='PLAYER CHECK';nextStreet();}if(a==='call'){ps=Math.max(0,ps-10);pot+=10;last='AUTO-STAGED CALL 10';nextStreet();}if(a==='raise'){ps=Math.max(0,ps-25);bs=Math.max(0,bs-25);pot+=50;last='RAISE EXTRA 25 - BOT CALL';nextStreet();}if(a==='fold'){bs+=pot;street='SHOWDOWN';banner.textContent='PLAYER FOLD - BOT WINS '+pot;last='FOLD RESOLUTION';rec('fold');setTimeout(start,2800);render();}rec(a);}
function render(){if(sceneKey!=='scorpion'){stage.innerHTML='<div class="t161"><div class="logo161"></div><div class="pot161">PHASE 161 ACTIVE ONLY IN SCORPION</div></div>';actions.innerHTML='';return;}const boardHtml=board.length?board.map(c=>card(c)).join(''):card('--')+card('--')+card('--');stage.innerHTML='<div class="t161"><div class="logo161"></div><div class="lane161 bot161">'+(street==='SHOWDOWN'?bot.map(c=>card(c)).join(''):back()+back())+'</div><div class="lane161 board161">'+boardHtml+'</div><div class="lane161 hero161">'+hero.map((c,i)=>card(c,i===0?'active161':'')).join('')+'</div><div class="pot161">POT '+pot+'</div><div class="dealer161">DEALER<br/>LEFT → RIGHT</div><div class="meta161"><div>'+street+'</div><div class="timer161">'+timer+'s</div><div>PLAYER '+ps+'</div><div>BOT '+bs+'</div><div>'+last+'</div></div></div>';actions.innerHTML='<button class="btn161" id="c161">CHECK</button><button class="btn161" id="ca161">CALL AUTO</button><button class="btn161" id="r161">RAISE +25</button><button class="btn161" id="f161">FOLD</button>';document.getElementById('c161')?.addEventListener('click',()=>act('check'));document.getElementById('ca161')?.addEventListener('click',()=>act('call'));document.getElementById('r161')?.addEventListener('click',()=>act('raise'));document.getElementById('f161')?.addEventListener('click',()=>act('fold'));}
function tick(){const now=performance.now();if(sceneKey==='scorpion'&&street!=='SHOWDOWN'&&now-lastTick>1000){lastTick=now;timer--;if(timer<=0)act('check');render();}requestAnimationFrame(tick);}setTimeout(()=>{if(sceneKey==='scorpion'){setStatus('Phase 161 table cards online');setMode('Action buttons active');start();}else{setStatus('Phase 161 room preserved');setMode('Scorpion table inactive here');}render();tick();},950);
