(function(){
  const BUILD="VERSION-1.7.4-LOBBY-POLISH-DEPLOY-VISIBILITY-RESCUE";
  const ROOT_ID="svr.module.lobby.polish.primary";
  window.SVR_BUILD_LABEL=BUILD;
  const portals=[
    ["POKER",0,-2.8,0xffd36a,2.05],["REIKI / RICI",6.5,-7.0,0xa66cff,1.55],["PGA GOLF",6.6,5.0,0x39ff88,1.45],
    ["VIBES THEATER",-7.4,-4.7,0xffcc66,1.55],["SCORPION",-6.4,5.2,0xff4b35,1.35],["LOUNGE",-2.4,7.2,0xc58a52,1.15],["VR STORE",2.5,7.2,0x66f5ff,1.15]
  ];
  function domProof(){
    let b=document.getElementById("svr174DeployProofBadge");
    if(!b){b=document.createElement("div");b.id="svr174DeployProofBadge";b.style.cssText="position:fixed;left:10px;top:10px;z-index:2147483647;background:linear-gradient(135deg,rgba(0,0,0,.94),rgba(30,0,50,.94));border:2px solid #20ffb0;border-radius:12px;box-shadow:0 0 22px rgba(32,255,176,.65);color:#eaffff;font:900 12px Arial,sans-serif;padding:10px 12px;pointer-events:none;max-width:370px";document.body.appendChild(b)}
    b.innerHTML="<div style='color:#20ffb0'>SVR LOBBY POLISH DEPLOYED</div><div>"+BUILD+"</div><div style='color:#ffe69a;font-size:11px;margin-top:4px'>If you see this, the new game build is live.</div>";
    let p=document.getElementById("svr174LobbyDomPanel");
    if(!p){p=document.createElement("div");p.id="svr174LobbyDomPanel";p.style.cssText="position:fixed;right:14px;top:78px;z-index:2147483646;width:280px;background:rgba(0,0,0,.72);border:1px solid rgba(255,214,120,.8);border-radius:14px;box-shadow:0 0 18px rgba(255,204,102,.32);color:#fff;font:800 12px Arial,sans-serif;padding:12px;pointer-events:none";document.body.appendChild(p)}
    p.innerHTML="<div style='color:#ffe69a;font-size:15px;margin-bottom:6px'>SVR LOBBY DIRECTORY</div><div>POKER TABLE</div><div>REIKI / RICI PREVIEW</div><div>PGA GOLF HUB</div><div>VIBES THEATER</div><div>SMOKER LOUNGE</div><div>SCORPION ROOM</div><div>VR STORE</div><div style='margin-top:8px;color:#20ffb0'>Module polish rescue active.</div>";
  }
  function scene(){const af=document.querySelector("a-scene");if(af&&af.object3D&&af.object3D.add)return af.object3D;for(const k of ["scene","SVR_SCENE","svrScene"]){if(window[k]&&window[k].add)return window[k];if(window[k]&&window[k].object3D&&window[k].object3D.add)return window[k].object3D}if(window.world&&window.world.scene&&window.world.scene.add)return window.world.scene;if(window.SVR_WORLD&&window.SVR_WORLD.scene&&window.SVR_WORLD.scene.add)return window.SVR_WORLD.scene;return null}
  function txt(msg,w,h,px,color){const c=document.createElement("canvas");c.width=2048;c.height=1024;const x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);x.textAlign="center";x.textBaseline="middle";x.fillStyle=color||"#fff";x.shadowColor=color||"#fff";x.shadowBlur=24;x.font="900 "+px+"px Arial,sans-serif";const lines=String(msg).split("\n"),lh=px*1.18;lines.forEach((line,i)=>x.fillText(line,c.width/2,c.height/2+(i-(lines.length-1)/2)*lh));const tex=new THREE.CanvasTexture(c);if(THREE.SRGBColorSpace)tex.colorSpace=THREE.SRGBColorSpace;return new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide,depthWrite:false}))}
  function smat(color,op,int){return new THREE.MeshStandardMaterial({color,transparent:op<1,opacity:op,roughness:.28,metalness:.1,emissive:color,emissiveIntensity:int??.14,side:THREE.DoubleSide})}
  function b(w,h,d,color,op,int){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),smat(color,op??1,int))}
  function basic(color,op){return new THREE.MeshBasicMaterial({color,transparent:op<1,opacity:op,side:THREE.DoubleSide,depthWrite:false})}
  function panel(title,body,w,h,accent){const g=new THREE.Group();g.add(b(w,h,.12,0x03030a,.9,.05));const top=b(w+.18,.08,.16,accent||0xffcc66,1,.28);top.position.y=h/2+.07;g.add(top);const bot=b(w+.18,.055,.16,0x00eaff,1,.22);bot.position.y=-h/2-.055;g.add(bot);const t=txt(title,w*.96,h*.25,118,"#ffe69a");t.position.set(0,h*.3,.09);g.add(t);const bd=txt(body,w*.92,h*.68,64,"#eaffff");bd.position.set(0,-h*.1,.1);g.add(bd);return g}
  function clean(s){const rm=[];s.traverse(o=>{const n=String(o.name||"");const id=(o.userData||{}).SVR_MODULE_ID;if(n.includes("SVR_LOBBY_POLISH_1_7_")||id===ROOT_ID)rm.push(o)});rm.forEach(o=>{if(o.parent)o.parent.remove(o)})}
  function add3d(){const s=scene();if(!s||!window.THREE)return false;clean(s);const root=new THREE.Group();root.name="SVR_LOBBY_POLISH_1_7_4_ROOT_DEPLOY_VISIBILITY_RESCUE";root.userData.SVR_MODULE_ID=ROOT_ID;root.userData.SVR_VERSION=BUILD;root.userData.SVR_OVERLAY_ONLY=true;root.userData.SVR_LOCKED=true;
    const confirm=panel("SVR LOBBY POLISH ACTIVE","Directory â€¢ Portal Rings â€¢ Daily Board â€¢ VIP Lighting\nThis confirms the deployed 3D lobby overlay is running.",6.6,1.65,0x20ffb0);confirm.position.set(0,3.15,2.85);confirm.rotation.y=Math.PI;root.add(confirm);
    const dir=panel("SVR LOBBY DIRECTORY","POKER TABLE\nREIKI / RICI PREVIEW\nPGA GOLF HUB\nVIBES THEATER\nSMOKER LOUNGE\nSCORPION ROOM\nVR STORE\nEVENTS / GIVEAWAYS",4.4,3.25,0x00eaff);dir.position.set(-4.7,2.75,2.55);dir.rotation.y=Math.PI*.86;root.add(dir);
    const daily=panel("TODAY IN SVR","Daily Chip Bonus: 5,000\nFeatured Room: VIBES Theater\nReiki Preview: Approval Pending\nNext Poker Event: Coming Soon\nSponsor Slots: Open",4.4,2.35,0xd28bff);daily.position.set(4.7,2.68,2.65);daily.rotation.y=-Math.PI*.86;root.add(daily);
    const rings=[];portals.forEach((p,i)=>{const ring=new THREE.Mesh(new THREE.RingGeometry(p[4]*.74,p[4],128),basic(p[3],.58));ring.name="SVR_LOBBY_POLISH_1_7_4_RING_"+p[0].replace(/\W+/g,"_");ring.position.set(p[1],.06,p[2]);ring.rotation.x=-Math.PI/2;ring.renderOrder=999;root.add(ring);rings.push(ring);const lab=txt("ENTER\n"+p[0],1.7,.62,130,"#ffffff");lab.position.set(p[1],.09,p[2]+p[4]+.33);lab.rotation.x=-Math.PI/2;lab.renderOrder=1000;root.add(lab)});
    [[0,3.6],[0,1.0],[0,-1.8],[3.5,-5.3],[6.2,-7.2],[2.0,-3.8],[-2.0,-3.8],[-7.1,-4.9],[-3,2.6],[3,2.7]].slice(0,-1).forEach((a,i,arr)=>{const c=[[0,3.6],[0,1.0],[0,-1.8],[3.5,-5.3],[6.2,-7.2],[2.0,-3.8],[-2.0,-3.8],[-7.1,-4.9],[-3,2.6],[3,2.7]][i+1];const dx=c[0]-a[0],dz=c[1]-a[1],len=Math.sqrt(dx*dx+dz*dz);const bar=b(.1,.04,len,i%2?0x9b6cff:0xffcc66,.78,.22);bar.position.set((a[0]+c[0])/2,.065,(a[1]+c[1])/2);bar.rotation.y=Math.atan2(dx,dz);root.add(bar)});
    [[-6.4,-3.2,0xffcc66],[5,-6.2,0x9b6cff],[5.4,4.2,0x36ff88],[-2.4,-.6,0xffffff],[2.4,6.2,0x66f5ff]].forEach((p,i)=>{const npc=new THREE.Group();npc.name="SVR_LOBBY_POLISH_1_7_4_AMBIENT_GUEST_"+i;npc.userData.SVR_AMBIENT_SILHOUETTE=true;npc.position.set(p[0],.08,p[1]);const body=b(.34,1.1,.22,0x08080d,.86,.02);body.position.y=.78;npc.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.18,24,12),smat(0x08080d,.88,.06));head.position.y=1.5;npc.add(head);const halo=new THREE.Mesh(new THREE.RingGeometry(.25,.28,32),basic(p[2],.55));halo.position.y=1.5;halo.rotation.y=Math.PI/2;npc.add(halo);root.add(npc)});
    const insp=panel("SVR MODULE LOCK STATUS","Moon: Locked\nMars: Locked\nAndroid Controls: Locked\nQuest Controls: Locked\nPoker Table: Locked\nReiki/RICI: Locked\nPGA: Locked\nVIBES Theater: Locked\nScorpion: Locked\nSmoker Lounge: Locked\nVR Store: Locked",5,2.75,0x20ffb0);insp.position.set(0,4.18,4.35);insp.rotation.y=Math.PI;insp.visible=location.search.includes("debug=1")||location.search.includes("qa=1")||location.hash.includes("debug");root.add(insp);
    s.add(root);function tick(){const t=performance.now()*.003;rings.forEach((r,i)=>{r.material.opacity=.44+Math.sin(t+i*.5)*.12;const sc=1+Math.sin(t+i*.45)*.065;r.scale.set(sc,sc,sc)});root.traverse(o=>{if((o.userData||{}).SVR_AMBIENT_SILHOUETTE)o.rotation.y+=.0012});requestAnimationFrame(tick)}requestAnimationFrame(tick);window.SVR_174_LOBBY_POLISH_AUDIT={build:BUILD,domProof:true,threeProof:true,sceneFound:true,loadedAt:new Date().toISOString()};console.log("[SVR]",BUILD,"3D overlay active");return true}
  function apply(){domProof();if(!add3d()){window.SVR_174_LOBBY_POLISH_AUDIT={build:BUILD,domProof:true,threeProof:false,sceneFound:false,loadedAt:new Date().toISOString()};console.warn("[SVR]",BUILD,"DOM proof loaded; waiting for 3D scene")}}
  document.addEventListener("DOMContentLoaded",apply);window.addEventListener("load",()=>setTimeout(apply,400));[900,1600,2800,4200,6500,9000].forEach(ms=>setTimeout(apply,ms));setInterval(domProof,5000);window.SVR_174_LOBBY_POLISH_DEPLOY_RESCUE={build:BUILD,apply};
})();
