CREATE TABLE IF NOT EXISTS GameBootRecoveryReports (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
  BuildLabel NVARCHAR(120) NULL,
  Reason NVARCHAR(255) NULL,
  Payload NVARCHAR(MAX) NULL
);
