CREATE TABLE BootRouteRecoveryReports (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Build NVARCHAR(120) NULL,
  Reason NVARCHAR(200) NULL,
  Payload NVARCHAR(MAX) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
