IF OBJECT_ID('dbo.AutoApplyHealth','U') IS NULL
CREATE TABLE dbo.AutoApplyHealth (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  BuildLabel NVARCHAR(120) NOT NULL,
  Status NVARCHAR(50) NOT NULL,
  Payload NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
